insert into public.products (
  id, slug, brand_id, name, category, category_id, price, description, accent,
  badge, affiliate_url, affiliate_network, image_url, rating, review_count,
  size, how_to_use, good_for, smells_like, finish, features, is_published, placed_by
) values
  (
    'b0000000-0000-0000-0000-000000000003',
    $mj$sleepy-magnesi-om$mj$,
    (select id from public.brands where slug = 'moon-juice'),
    $mj$Sleepy Magnesi-Om$mj$,
    'supplements',
    (select id from public.categories where slug = 'supplements'),
    34.3,
    $mj$Plant melatonin + magnesium for deep sleep$mj$,
    $mj$#5E4B45$mj$,
    $mj$Popular$mj$,
    $mj$https://moonjuice.com/products/sleepy-magnesiom-magnesium-powder-with-melatonin-for-sleep$mj$,
    'direct',
    $mj$https://moonjuice.com/cdn/shop/files/9_SleepyMag.png?v=1782413613&width=800$mj$,
    4.7,
    323,
    $mj$35 servings$mj$,
    $mj$Mix in 10oz water before bed as needed. This Magnesium and Melatonin powder for sleep is great for travel, shift work, and nights you have trouble falling asleep. Friendly for adults and kids 9+.$mj$,
    $mj$Sleep:Supports slumber without the hangover, decreases duration to fall asleep, supports sleep quality; Relaxation:Supports the body's stress response and muscle relaxation$mj$,
    $mj$$mj$,
    $mj$$mj$,
    array[$f$100% Traceable$f$, $f$Clinically Proven Potency$f$, $f$3rd Party Tested$f$, $f$Vegan$f$, $f$No Fillers or Junk$f$, $f$Bioavailable$f$]::text[],
    true,
    $mj$catoegy$mj$
  )
on conflict (slug) do update set
  brand_id = excluded.brand_id,
  name = excluded.name,
  category = excluded.category,
  category_id = excluded.category_id,
  price = excluded.price,
  description = excluded.description,
  accent = excluded.accent,
  badge = excluded.badge,
  affiliate_url = excluded.affiliate_url,
  affiliate_network = excluded.affiliate_network,
  image_url = excluded.image_url,
  rating = excluded.rating,
  review_count = excluded.review_count,
  size = excluded.size,
  how_to_use = excluded.how_to_use,
  good_for = excluded.good_for,
  features = excluded.features,
  is_published = excluded.is_published,
  placed_by = excluded.placed_by;
