insert into public.products (
  id, slug, brand_id, name, category, category_id, price, description, accent,
  badge, affiliate_url, affiliate_network, image_url, rating, review_count,
  size, how_to_use, good_for, smells_like, finish, features, is_published, placed_by
) values
  (
    'b0000000-0000-0000-0000-000000000029',
    $mj$superbrain$mj$,
    (select id from public.brands where slug = 'moon-juice'),
    $mj$SuperBrain$mj$,
    'supplements',
    (select id from public.categories where slug = 'supplements'),
    54,
    $mj$Adaptogens for focus. Mental stamina, alertness & concentration.$mj$,
    $mj$#5E4B45$mj$,
    null,
    $mj$https://moonjuice.com/products/super-brain$mj$,
    'direct',
    $mj$https://moonjuice.com/cdn/shop/files/MoonJuice_PPage_SuperBrain_V2.png?v=1762199756&width=800$mj$,
    4.8,
    4,
    $mj$14 servings$mj$,
    $mj$Take 4 caps of SuperBrain every morning, with or without food.*$mj$,
    $mj$Mental Stamina:; Targets stress to promote mental stamina and clarity; Alertness:$mj$,
    $mj$$mj$,
    $mj$$mj$,
    array[$f$100% Traceable$f$, $f$Clinically Proven Potency$f$, $f$3rd Party Tested$f$, $f$Vegan$f$, $f$No Fillers or Junk$f$, $f$Bioavailable$f$]::text[],
    true,
    $mj$catoegy$mj$
  )
on conflict (slug) do update set
  brand_id = excluded.brand_id,
  name = excluded.name,
  category = excluded.category,
  category_id = excluded.category_id,
  price = excluded.price,
  description = excluded.description,
  accent = excluded.accent,
  badge = excluded.badge,
  affiliate_url = excluded.affiliate_url,
  affiliate_network = excluded.affiliate_network,
  image_url = excluded.image_url,
  rating = excluded.rating,
  review_count = excluded.review_count,
  size = excluded.size,
  how_to_use = excluded.how_to_use,
  good_for = excluded.good_for,
  features = excluded.features,
  is_published = excluded.is_published,
  placed_by = excluded.placed_by;
