insert into public.products (
  id, slug, brand_id, name, category, category_id, price, description, accent,
  badge, affiliate_url, affiliate_network, image_url, rating, review_count,
  size, how_to_use, good_for, smells_like, finish, features, is_published, placed_by
) values
  (
    'b0000000-0000-0000-0000-000000000011',
    $mj$beauty-dust$mj$,
    (select id from public.brands where slug = 'moon-juice'),
    $mj$Beauty Dust$mj$,
    'supplements',
    (select id from public.categories where slug = 'supplements'),
    26.6,
    $mj$Skin clarity + protection from accelerated aging$mj$,
    $mj$#5E4B45$mj$,
    $mj$Popular$mj$,
    $mj$https://moonjuice.com/products/beauty-dust$mj$,
    'direct',
    $mj$https://moonjuice.com/cdn/shop/files/Beauty_dust_ecom.png?v=1762198098&width=800$mj$,
    4.7,
    410,
    $mj$30 servings$mj$,
    $mj$Tart, berry flavor -- pairs well with matcha, water & lemonade; or add to any smoothie. Blend 1 tsp per serving. Our berry-heavy blend Beauty Dust can clump or harden if not used regularly. This does not affect the potency. If you are a casual Duster, Beauty Dust is also available in a boxed set of 12 single serving sachets.$mj$,
    $mj$Traditionally used to help:; Organic Amla:Helps protect the skin from oxidative stress; Organic Schisandra:Traditionally used for its hydrating properties and to promote skin clarity$mj$,
    $mj$$mj$,
    $mj$$mj$,
    array[$f$100% Traceable$f$, $f$Clinically Proven Potency$f$, $f$3rd Party Tested$f$, $f$Vegan$f$, $f$No Fillers or Junk$f$, $f$Bioavailable$f$]::text[],
    true,
    $mj$catoegy$mj$
  )
on conflict (slug) do update set
  brand_id = excluded.brand_id,
  name = excluded.name,
  category = excluded.category,
  category_id = excluded.category_id,
  price = excluded.price,
  description = excluded.description,
  accent = excluded.accent,
  badge = excluded.badge,
  affiliate_url = excluded.affiliate_url,
  affiliate_network = excluded.affiliate_network,
  image_url = excluded.image_url,
  rating = excluded.rating,
  review_count = excluded.review_count,
  size = excluded.size,
  how_to_use = excluded.how_to_use,
  good_for = excluded.good_for,
  features = excluded.features,
  is_published = excluded.is_published,
  placed_by = excluded.placed_by;
