insert into public.products (
  id, slug, brand_id, name, category, category_id, price, description, accent,
  badge, affiliate_url, affiliate_network, image_url, rating, review_count,
  size, how_to_use, good_for, smells_like, finish, features, is_published, placed_by
) values
  (
    'b0000000-0000-0000-0000-000000000001',
    $mj$neuro-magnesi-om$mj$,
    (select id from public.brands where slug = 'moon-juice'),
    $mj$Neuro Magnesi-Om$mj$,
    'supplements',
    (select id from public.categories where slug = 'supplements'),
    51.8,
    $mj$Cognitive speed + brain longevity$mj$,
    $mj$#5E4B45$mj$,
    null,
    $mj$https://moonjuice.com/products/neuro-magnesi-om$mj$,
    'direct',
    $mj$https://moonjuice.com/cdn/shop/files/Ecom-Neuro_Matcha_Mag.png?v=1779567262&width=800$mj$,
    4.7,
    35,
    $mj$30 servings$mj$,
    $mj$Blend 1 rounded tsp in 6oz hot or cold water or milk, up to 2x a day. Neuro Magnesi-Om contains caffeine; it's best taken in the morning---or at least not so late in the day that it'll affect your sleep.$mj$,
    $mj$Short-term memory + cognitive speed; Mental stamina + alertness; Neuroplasticity + synaptic density$mj$,
    $mj$$mj$,
    $mj$$mj$,
    array[$f$100% Traceable$f$, $f$Clinically Proven Potency$f$, $f$3rd Party Tested$f$, $f$Vegan$f$, $f$No Fillers or Junk$f$, $f$Bioavailable$f$]::text[],
    true,
    $mj$catoegy$mj$
  )
on conflict (slug) do update set
  brand_id = excluded.brand_id,
  name = excluded.name,
  category = excluded.category,
  category_id = excluded.category_id,
  price = excluded.price,
  description = excluded.description,
  accent = excluded.accent,
  badge = excluded.badge,
  affiliate_url = excluded.affiliate_url,
  affiliate_network = excluded.affiliate_network,
  image_url = excluded.image_url,
  rating = excluded.rating,
  review_count = excluded.review_count,
  size = excluded.size,
  how_to_use = excluded.how_to_use,
  good_for = excluded.good_for,
  features = excluded.features,
  is_published = excluded.is_published,
  placed_by = excluded.placed_by;

insert into public.products (
  id, slug, brand_id, name, category, category_id, price, description, accent,
  badge, affiliate_url, affiliate_network, image_url, rating, review_count,
  size, how_to_use, good_for, smells_like, finish, features, is_published, placed_by
) values
  (
    'b0000000-0000-0000-0000-000000000002',
    $mj$magnesi-om$mj$,
    (select id from public.brands where slug = 'moon-juice'),
    $mj$Magnesi-Om$mj$,
    'supplements',
    (select id from public.categories where slug = 'supplements'),
    30.8,
    $mj$Rest, relaxation + regularity$mj$,
    $mj$#5E4B45$mj$,
    $mj$Best seller$mj$,
    $mj$https://moonjuice.com/products/magnesi-om-magnesium-supplement$mj$,
    'direct',
    $mj$https://moonjuice.com/cdn/shop/products/Mag_New_800x800_4dbf7a23-5fdf-4b50-81ee-e0618d9f8c2b.png?v=1782516533&width=800$mj$,
    4.8,
    3853,
    $mj$30 servings$mj$,
    $mj$Mix 1 tsp of our magnesium powder in water every night or when you need to chill. Or mix one serving size with Tart Cherry Juice + sparkling water to make your own Sleepy Girl Mocktail.$mj$,
    $mj$Relaxation: Enhances feelings of calm, improves mood, reduces muscle aches; Brain Health: Supports healthy cognitive aging and brain function; Regularity: Supports regular bowel movement, soothes and$mj$,
    $mj$$mj$,
    $mj$$mj$,
    array[$f$100% Traceable$f$, $f$Clinically Proven Potency$f$, $f$3rd Party Tested$f$, $f$Vegan$f$, $f$No Fillers or Junk$f$, $f$Bioavailable$f$]::text[],
    true,
    $mj$catoegy$mj$
  )
on conflict (slug) do update set
  brand_id = excluded.brand_id,
  name = excluded.name,
  category = excluded.category,
  category_id = excluded.category_id,
  price = excluded.price,
  description = excluded.description,
  accent = excluded.accent,
  badge = excluded.badge,
  affiliate_url = excluded.affiliate_url,
  affiliate_network = excluded.affiliate_network,
  image_url = excluded.image_url,
  rating = excluded.rating,
  review_count = excluded.review_count,
  size = excluded.size,
  how_to_use = excluded.how_to_use,
  good_for = excluded.good_for,
  features = excluded.features,
  is_published = excluded.is_published,
  placed_by = excluded.placed_by;

insert into public.products (
  id, slug, brand_id, name, category, category_id, price, description, accent,
  badge, affiliate_url, affiliate_network, image_url, rating, review_count,
  size, how_to_use, good_for, smells_like, finish, features, is_published, placed_by
) values
  (
    'b0000000-0000-0000-0000-000000000003',
    $mj$sleepy-magnesi-om$mj$,
    (select id from public.brands where slug = 'moon-juice'),
    $mj$Sleepy Magnesi-Om$mj$,
    'supplements',
    (select id from public.categories where slug = 'supplements'),
    34.3,
    $mj$Plant melatonin + magnesium for deep sleep$mj$,
    $mj$#5E4B45$mj$,
    $mj$Popular$mj$,
    $mj$https://moonjuice.com/products/sleepy-magnesiom-magnesium-powder-with-melatonin-for-sleep$mj$,
    'direct',
    $mj$https://moonjuice.com/cdn/shop/files/9_SleepyMag.png?v=1782413613&width=800$mj$,
    4.7,
    323,
    $mj$35 servings$mj$,
    $mj$Mix in 10oz water before bed as needed. This Magnesium and Melatonin powder for sleep is great for travel, shift work, and nights you have trouble falling asleep. Friendly for adults and kids 9+.$mj$,
    $mj$Sleep:Supports slumber without the hangover, decreases duration to fall asleep, supports sleep quality; Relaxation:Supports the body's stress response and muscle relaxation$mj$,
    $mj$$mj$,
    $mj$$mj$,
    array[$f$100% Traceable$f$, $f$Clinically Proven Potency$f$, $f$3rd Party Tested$f$, $f$Vegan$f$, $f$No Fillers or Junk$f$, $f$Bioavailable$f$]::text[],
    true,
    $mj$catoegy$mj$
  )
on conflict (slug) do update set
  brand_id = excluded.brand_id,
  name = excluded.name,
  category = excluded.category,
  category_id = excluded.category_id,
  price = excluded.price,
  description = excluded.description,
  accent = excluded.accent,
  badge = excluded.badge,
  affiliate_url = excluded.affiliate_url,
  affiliate_network = excluded.affiliate_network,
  image_url = excluded.image_url,
  rating = excluded.rating,
  review_count = excluded.review_count,
  size = excluded.size,
  how_to_use = excluded.how_to_use,
  good_for = excluded.good_for,
  features = excluded.features,
  is_published = excluded.is_published,
  placed_by = excluded.placed_by;

insert into public.products (
  id, slug, brand_id, name, category, category_id, price, description, accent,
  badge, affiliate_url, affiliate_network, image_url, rating, review_count,
  size, how_to_use, good_for, smells_like, finish, features, is_published, placed_by
) values
  (
    'b0000000-0000-0000-0000-000000000004',
    $mj$superyou$mj$,
    (select id from public.brands where slug = 'moon-juice'),
    $mj$SuperYou$mj$,
    'supplements',
    (select id from public.categories where slug = 'supplements'),
    37.8,
    $mj$Daily cortisol management. Energy, mood + focus$mj$,
    $mj$#5E4B45$mj$,
    $mj$Best seller$mj$,
    $mj$https://moonjuice.com/products/superyou$mj$,
    'direct',
    $mj$https://moonjuice.com/cdn/shop/products/SuperYou_800x800_9fa65f73-f367-4e26-bf80-88b4ef9aff53.png?v=1762198134&width=800$mj$,
    4.8,
    3220,
    $mj$30 servings$mj$,
    $mj$Take 2 caps every morning, with or without food.$mj$,
    $mj$reduce physical, mental and emotional fatigue; reduce cortisol by 24%; boost energy and mood$mj$,
    $mj$$mj$,
    $mj$$mj$,
    array[$f$100% Traceable$f$, $f$Clinically Proven Potency$f$, $f$3rd Party Tested$f$, $f$Vegan$f$, $f$No Fillers or Junk$f$, $f$Bioavailable$f$]::text[],
    true,
    $mj$catoegy$mj$
  )
on conflict (slug) do update set
  brand_id = excluded.brand_id,
  name = excluded.name,
  category = excluded.category,
  category_id = excluded.category_id,
  price = excluded.price,
  description = excluded.description,
  accent = excluded.accent,
  badge = excluded.badge,
  affiliate_url = excluded.affiliate_url,
  affiliate_network = excluded.affiliate_network,
  image_url = excluded.image_url,
  rating = excluded.rating,
  review_count = excluded.review_count,
  size = excluded.size,
  how_to_use = excluded.how_to_use,
  good_for = excluded.good_for,
  features = excluded.features,
  is_published = excluded.is_published,
  placed_by = excluded.placed_by;

insert into public.products (
  id, slug, brand_id, name, category, category_id, price, description, accent,
  badge, affiliate_url, affiliate_network, image_url, rating, review_count,
  size, how_to_use, good_for, smells_like, finish, features, is_published, placed_by
) values
  (
    'b0000000-0000-0000-0000-000000000005',
    $mj$superhair$mj$,
    (select id from public.brands where slug = 'moon-juice'),
    $mj$SuperHair$mj$,
    'supplements',
    (select id from public.categories where slug = 'supplements'),
    46.2,
    $mj$Healthier, stronger, thicker hair$mj$,
    $mj$#5E4B45$mj$,
    $mj$Best seller$mj$,
    $mj$https://moonjuice.com/products/superhair$mj$,
    'direct',
    $mj$https://moonjuice.com/cdn/shop/products/SuperHair_800x800_1e036d6d-c5a7-4bc3-ada4-58fb5e0c09bc.png?v=1762198161&width=800$mj$,
    4.7,
    2106,
    $mj$30 servings$mj$,
    $mj$Take 4 caps of SuperHair every morning, with or without food, for healthier, thicker, stronger hair.*$mj$,
    $mj$Helps balance stress hormones and reduce the effects of oxidative stress, which can contribute to hair loss; Help inhibit the hair-destructive hormone, DHT, to support healthy hair follicles and promo$mj$,
    $mj$$mj$,
    $mj$$mj$,
    array[$f$100% Traceable$f$, $f$Clinically Proven Potency$f$, $f$3rd Party Tested$f$, $f$Vegan$f$, $f$No Fillers or Junk$f$, $f$Bioavailable$f$]::text[],
    true,
    $mj$catoegy$mj$
  )
on conflict (slug) do update set
  brand_id = excluded.brand_id,
  name = excluded.name,
  category = excluded.category,
  category_id = excluded.category_id,
  price = excluded.price,
  description = excluded.description,
  accent = excluded.accent,
  badge = excluded.badge,
  affiliate_url = excluded.affiliate_url,
  affiliate_network = excluded.affiliate_network,
  image_url = excluded.image_url,
  rating = excluded.rating,
  review_count = excluded.review_count,
  size = excluded.size,
  how_to_use = excluded.how_to_use,
  good_for = excluded.good_for,
  features = excluded.features,
  is_published = excluded.is_published,
  placed_by = excluded.placed_by;

insert into public.products (
  id, slug, brand_id, name, category, category_id, price, description, accent,
  badge, affiliate_url, affiliate_network, image_url, rating, review_count,
  size, how_to_use, good_for, smells_like, finish, features, is_published, placed_by
) values
  (
    'b0000000-0000-0000-0000-000000000006',
    $mj$superbeauty$mj$,
    (select id from public.brands where slug = 'moon-juice'),
    $mj$SuperBeauty$mj$,
    'supplements',
    (select id from public.categories where slug = 'supplements'),
    46.2,
    $mj$Cellular skin care. Collagen, elasticity + cell vitality$mj$,
    $mj$#5E4B45$mj$,
    $mj$Popular$mj$,
    $mj$https://moonjuice.com/products/superbeauty$mj$,
    'direct',
    $mj$https://moonjuice.com/cdn/shop/products/SuperBeauty_800x800_a9883c0f-7510-4398-9bf3-1514540ce66e.png?v=1762198217&width=800$mj$,
    4.9,
    678,
    $mj$30 servings$mj$,
    $mj$Take 2 caps every morning, with or without food.$mj$,
    $mj$minimize the appearance of fine lines; promote collagen and elasticity; protect protein, lipids and DNA from oxidative damage* †$mj$,
    $mj$$mj$,
    $mj$$mj$,
    array[$f$100% Traceable$f$, $f$Clinically Proven Potency$f$, $f$3rd Party Tested$f$, $f$Vegan$f$, $f$No Fillers or Junk$f$, $f$Bioavailable$f$]::text[],
    true,
    $mj$catoegy$mj$
  )
on conflict (slug) do update set
  brand_id = excluded.brand_id,
  name = excluded.name,
  category = excluded.category,
  category_id = excluded.category_id,
  price = excluded.price,
  description = excluded.description,
  accent = excluded.accent,
  badge = excluded.badge,
  affiliate_url = excluded.affiliate_url,
  affiliate_network = excluded.affiliate_network,
  image_url = excluded.image_url,
  rating = excluded.rating,
  review_count = excluded.review_count,
  size = excluded.size,
  how_to_use = excluded.how_to_use,
  good_for = excluded.good_for,
  features = excluded.features,
  is_published = excluded.is_published,
  placed_by = excluded.placed_by;

insert into public.products (
  id, slug, brand_id, name, category, category_id, price, description, accent,
  badge, affiliate_url, affiliate_network, image_url, rating, review_count,
  size, how_to_use, good_for, smells_like, finish, features, is_published, placed_by
) values
  (
    'b0000000-0000-0000-0000-000000000007',
    $mj$superpower$mj$,
    (select id from public.brands where slug = 'moon-juice'),
    $mj$SuperPower$mj$,
    'supplements',
    (select id from public.categories where slug = 'supplements'),
    29.4,
    $mj$Radical immune support$mj$,
    $mj$#5E4B45$mj$,
    null,
    $mj$https://moonjuice.com/products/superpower$mj$,
    'direct',
    $mj$https://moonjuice.com/cdn/shop/products/SuperPower800x800.png?v=1762198322&width=800$mj$,
    4.7,
    200,
    $mj$10 servings$mj$,
    $mj$For daily maintenance, take 1 capsule. If you need extra support or feel your system is compromised, take 3 capsules every day for 10 days.$mj$,
    $mj$Support healthy immunity; Activate cells for a quick response; Balance an overactive immune system$mj$,
    $mj$$mj$,
    $mj$$mj$,
    array[$f$100% Traceable$f$, $f$Clinically Proven Potency$f$, $f$3rd Party Tested$f$, $f$Vegan$f$, $f$No Fillers or Junk$f$, $f$Bioavailable$f$]::text[],
    true,
    $mj$catoegy$mj$
  )
on conflict (slug) do update set
  brand_id = excluded.brand_id,
  name = excluded.name,
  category = excluded.category,
  category_id = excluded.category_id,
  price = excluded.price,
  description = excluded.description,
  accent = excluded.accent,
  badge = excluded.badge,
  affiliate_url = excluded.affiliate_url,
  affiliate_network = excluded.affiliate_network,
  image_url = excluded.image_url,
  rating = excluded.rating,
  review_count = excluded.review_count,
  size = excluded.size,
  how_to_use = excluded.how_to_use,
  good_for = excluded.good_for,
  features = excluded.features,
  is_published = excluded.is_published,
  placed_by = excluded.placed_by;

insert into public.products (
  id, slug, brand_id, name, category, category_id, price, description, accent,
  badge, affiliate_url, affiliate_network, image_url, rating, review_count,
  size, how_to_use, good_for, smells_like, finish, features, is_published, placed_by
) values
  (
    'b0000000-0000-0000-0000-000000000008',
    $mj$sex-dust$mj$,
    (select id from public.brands where slug = 'moon-juice'),
    $mj$Sex Dust$mj$,
    'supplements',
    (select id from public.categories where slug = 'supplements'),
    26.6,
    $mj$Adaptogens for fire + creative energy$mj$,
    $mj$#5E4B45$mj$,
    $mj$Popular$mj$,
    $mj$https://moonjuice.com/products/sex-dust$mj$,
    'direct',
    $mj$https://moonjuice.com/cdn/shop/files/Sex_Dust_ecom.png?v=1762198103&width=800$mj$,
    4.5,
    904,
    $mj$14 servings$mj$,
    $mj$Using a milk frother or blender, mix 1 tsp of this natural libido supplement into coffee, black tea, hot water with a splash of milk, or cocoa. Commit daily for maximum benefits.$mj$,
    $mj$LIBIDO + HORMONAL BALANCE; Shown to help:; Shatavarisupports healthy hormonal balance and juiciness$mj$,
    $mj$$mj$,
    $mj$$mj$,
    array[$f$100% Traceable$f$, $f$Clinically Proven Potency$f$, $f$3rd Party Tested$f$, $f$Vegan$f$, $f$No Fillers or Junk$f$, $f$Bioavailable$f$]::text[],
    true,
    $mj$catoegy$mj$
  )
on conflict (slug) do update set
  brand_id = excluded.brand_id,
  name = excluded.name,
  category = excluded.category,
  category_id = excluded.category_id,
  price = excluded.price,
  description = excluded.description,
  accent = excluded.accent,
  badge = excluded.badge,
  affiliate_url = excluded.affiliate_url,
  affiliate_network = excluded.affiliate_network,
  image_url = excluded.image_url,
  rating = excluded.rating,
  review_count = excluded.review_count,
  size = excluded.size,
  how_to_use = excluded.how_to_use,
  good_for = excluded.good_for,
  features = excluded.features,
  is_published = excluded.is_published,
  placed_by = excluded.placed_by;

insert into public.products (
  id, slug, brand_id, name, category, category_id, price, description, accent,
  badge, affiliate_url, affiliate_network, image_url, rating, review_count,
  size, how_to_use, good_for, smells_like, finish, features, is_published, placed_by
) values
  (
    'b0000000-0000-0000-0000-000000000009',
    $mj$brain-dust$mj$,
    (select id from public.brands where slug = 'moon-juice'),
    $mj$Brain Dust$mj$,
    'supplements',
    (select id from public.categories where slug = 'supplements'),
    26.6,
    $mj$Mental stamina, alertness + concentration$mj$,
    $mj$#5E4B45$mj$,
    $mj$Popular$mj$,
    $mj$https://moonjuice.com/products/brain-dust$mj$,
    'direct',
    $mj$https://moonjuice.com/cdn/shop/files/Brain_dust_ecom.png?v=1762198100&width=800$mj$,
    4.7,
    736,
    $mj$14 servings$mj$,
    $mj$Malty & bitter -- pairs well with tea, coffee, chocolate & milk; or add to any smoothie. Blend 1 tsp per serving.$mj$,
    $mj$Organic Lion's Mane:Known to be neuroprotective; Ginkgo:Supports speedy processing; Rhodiola:Promotes alertness and concentration$mj$,
    $mj$$mj$,
    $mj$$mj$,
    array[$f$100% Traceable$f$, $f$Clinically Proven Potency$f$, $f$3rd Party Tested$f$, $f$Vegan$f$, $f$No Fillers or Junk$f$, $f$Bioavailable$f$]::text[],
    true,
    $mj$catoegy$mj$
  )
on conflict (slug) do update set
  brand_id = excluded.brand_id,
  name = excluded.name,
  category = excluded.category,
  category_id = excluded.category_id,
  price = excluded.price,
  description = excluded.description,
  accent = excluded.accent,
  badge = excluded.badge,
  affiliate_url = excluded.affiliate_url,
  affiliate_network = excluded.affiliate_network,
  image_url = excluded.image_url,
  rating = excluded.rating,
  review_count = excluded.review_count,
  size = excluded.size,
  how_to_use = excluded.how_to_use,
  good_for = excluded.good_for,
  features = excluded.features,
  is_published = excluded.is_published,
  placed_by = excluded.placed_by;

insert into public.products (
  id, slug, brand_id, name, category, category_id, price, description, accent,
  badge, affiliate_url, affiliate_network, image_url, rating, review_count,
  size, how_to_use, good_for, smells_like, finish, features, is_published, placed_by
) values
  (
    'b0000000-0000-0000-0000-000000000010',
    $mj$spirit-dust$mj$,
    (select id from public.brands where slug = 'moon-juice'),
    $mj$Spirit Dust$mj$,
    'supplements',
    (select id from public.categories where slug = 'supplements'),
    26.6,
    $mj$Relief of tension + irritability$mj$,
    $mj$#5E4B45$mj$,
    $mj$Popular$mj$,
    $mj$https://moonjuice.com/products/spirit-dust$mj$,
    'direct',
    $mj$https://moonjuice.com/cdn/shop/files/Spirit_dust_ecom.png?v=1762198101&width=800$mj$,
    4.8,
    473,
    $mj$14 servings$mj$,
    $mj$Sweet & nutty -- pairs well with tea, coffee, chocolate & milk; or add to any smoothie. Blend 1 tsp per serving.$mj$,
    $mj$Traditionally used to help:; Organic Reishi:Known to nourish and calm, providing a sense of joy and peace; Organic Ashwagandha:Helps promote emotional wellbeing$mj$,
    $mj$$mj$,
    $mj$$mj$,
    array[$f$100% Traceable$f$, $f$Clinically Proven Potency$f$, $f$3rd Party Tested$f$, $f$Vegan$f$, $f$No Fillers or Junk$f$, $f$Bioavailable$f$]::text[],
    true,
    $mj$catoegy$mj$
  )
on conflict (slug) do update set
  brand_id = excluded.brand_id,
  name = excluded.name,
  category = excluded.category,
  category_id = excluded.category_id,
  price = excluded.price,
  description = excluded.description,
  accent = excluded.accent,
  badge = excluded.badge,
  affiliate_url = excluded.affiliate_url,
  affiliate_network = excluded.affiliate_network,
  image_url = excluded.image_url,
  rating = excluded.rating,
  review_count = excluded.review_count,
  size = excluded.size,
  how_to_use = excluded.how_to_use,
  good_for = excluded.good_for,
  features = excluded.features,
  is_published = excluded.is_published,
  placed_by = excluded.placed_by;

insert into public.products (
  id, slug, brand_id, name, category, category_id, price, description, accent,
  badge, affiliate_url, affiliate_network, image_url, rating, review_count,
  size, how_to_use, good_for, smells_like, finish, features, is_published, placed_by
) values
  (
    'b0000000-0000-0000-0000-000000000011',
    $mj$beauty-dust$mj$,
    (select id from public.brands where slug = 'moon-juice'),
    $mj$Beauty Dust$mj$,
    'supplements',
    (select id from public.categories where slug = 'supplements'),
    26.6,
    $mj$Skin clarity + protection from accelerated aging$mj$,
    $mj$#5E4B45$mj$,
    $mj$Popular$mj$,
    $mj$https://moonjuice.com/products/beauty-dust$mj$,
    'direct',
    $mj$https://moonjuice.com/cdn/shop/files/Beauty_dust_ecom.png?v=1762198098&width=800$mj$,
    4.7,
    410,
    $mj$30 servings$mj$,
    $mj$Tart, berry flavor -- pairs well with matcha, water & lemonade; or add to any smoothie. Blend 1 tsp per serving. Our berry-heavy blend Beauty Dust can clump or harden if not used regularly. This does not affect the potency. If you are a casual Duster, Beauty Dust is also available in a boxed set of 12 single serving sachets.$mj$,
    $mj$Traditionally used to help:; Organic Amla:Helps protect the skin from oxidative stress; Organic Schisandra:Traditionally used for its hydrating properties and to promote skin clarity$mj$,
    $mj$$mj$,
    $mj$$mj$,
    array[$f$100% Traceable$f$, $f$Clinically Proven Potency$f$, $f$3rd Party Tested$f$, $f$Vegan$f$, $f$No Fillers or Junk$f$, $f$Bioavailable$f$]::text[],
    true,
    $mj$catoegy$mj$
  )
on conflict (slug) do update set
  brand_id = excluded.brand_id,
  name = excluded.name,
  category = excluded.category,
  category_id = excluded.category_id,
  price = excluded.price,
  description = excluded.description,
  accent = excluded.accent,
  badge = excluded.badge,
  affiliate_url = excluded.affiliate_url,
  affiliate_network = excluded.affiliate_network,
  image_url = excluded.image_url,
  rating = excluded.rating,
  review_count = excluded.review_count,
  size = excluded.size,
  how_to_use = excluded.how_to_use,
  good_for = excluded.good_for,
  features = excluded.features,
  is_published = excluded.is_published,
  placed_by = excluded.placed_by;

insert into public.products (
  id, slug, brand_id, name, category, category_id, price, description, accent,
  badge, affiliate_url, affiliate_network, image_url, rating, review_count,
  size, how_to_use, good_for, smells_like, finish, features, is_published, placed_by
) values
  (
    'b0000000-0000-0000-0000-000000000012',
    $mj$power-dust$mj$,
    (select id from public.brands where slug = 'moon-juice'),
    $mj$Power Dust$mj$,
    'supplements',
    (select id from public.categories where slug = 'supplements'),
    26.6,
    $mj$Adaptogens for energy. Stamina, recovery + healthy immunity$mj$,
    $mj$#5E4B45$mj$,
    $mj$Popular$mj$,
    $mj$https://moonjuice.com/products/power-dust$mj$,
    'direct',
    $mj$https://moonjuice.com/cdn/shop/files/Power_dust_ecom.png?v=1762198106&width=800$mj$,
    4.8,
    321,
    $mj$14 servings$mj$,
    $mj$Bright & earthy -- pairs well with citrus, tea, milk & coffee; or add to any smoothie. Blend 1 tsp per serving.$mj$,
    $mj$Traditionally used to help:; Organic Cordyceps:Traditionally used to support healthy lung capacity; Organic Ginseng:Known to help rejuvenate energy$mj$,
    $mj$$mj$,
    $mj$$mj$,
    array[$f$100% Traceable$f$, $f$Clinically Proven Potency$f$, $f$3rd Party Tested$f$, $f$Vegan$f$, $f$No Fillers or Junk$f$, $f$Bioavailable$f$]::text[],
    true,
    $mj$catoegy$mj$
  )
on conflict (slug) do update set
  brand_id = excluded.brand_id,
  name = excluded.name,
  category = excluded.category,
  category_id = excluded.category_id,
  price = excluded.price,
  description = excluded.description,
  accent = excluded.accent,
  badge = excluded.badge,
  affiliate_url = excluded.affiliate_url,
  affiliate_network = excluded.affiliate_network,
  image_url = excluded.image_url,
  rating = excluded.rating,
  review_count = excluded.review_count,
  size = excluded.size,
  how_to_use = excluded.how_to_use,
  good_for = excluded.good_for,
  features = excluded.features,
  is_published = excluded.is_published,
  placed_by = excluded.placed_by;

insert into public.products (
  id, slug, brand_id, name, category, category_id, price, description, accent,
  badge, affiliate_url, affiliate_network, image_url, rating, review_count,
  size, how_to_use, good_for, smells_like, finish, features, is_published, placed_by
) values
  (
    'b0000000-0000-0000-0000-000000000013',
    $mj$ting$mj$,
    (select id from public.brands where slug = 'moon-juice'),
    $mj$Ting$mj$,
    'supplements',
    (select id from public.categories where slug = 'supplements'),
    29.4,
    $mj$Caffeine-free pick-me-up. Energy, metabolism + mood$mj$,
    $mj$#5E4B45$mj$,
    $mj$Popular$mj$,
    $mj$https://moonjuice.com/products/ting$mj$,
    'direct',
    $mj$https://moonjuice.com/cdn/shop/products/Ting_800x800_69845d2f-7a2c-41e0-881b-30dce02dc809.png?v=1762198447&width=800$mj$,
    4.8,
    674,
    $mj$25 servings$mj$,
    $mj$½ tsp to 12oz of water daily. Tips: + Dissolves best when added to glass before water. + Store in the fridge for warmer months or climates. Our Tulsi and Guava plant-based B Complex can get sticky. Since we don't add any flow agents, fillers, or unwanted additives, keeping it in the fridge can help prevent any clumping.$mj$,
    $mj$Metabolism: Converts fat, protein, and carbs into cellular currency; Energy: Enhances performance; Mood: Supports normal serotonin production, brain function, and short-term memory$mj$,
    $mj$$mj$,
    $mj$$mj$,
    array[$f$100% Traceable$f$, $f$Clinically Proven Potency$f$, $f$3rd Party Tested$f$, $f$Vegan$f$, $f$No Fillers or Junk$f$, $f$Bioavailable$f$]::text[],
    true,
    $mj$catoegy$mj$
  )
on conflict (slug) do update set
  brand_id = excluded.brand_id,
  name = excluded.name,
  category = excluded.category,
  category_id = excluded.category_id,
  price = excluded.price,
  description = excluded.description,
  accent = excluded.accent,
  badge = excluded.badge,
  affiliate_url = excluded.affiliate_url,
  affiliate_network = excluded.affiliate_network,
  image_url = excluded.image_url,
  rating = excluded.rating,
  review_count = excluded.review_count,
  size = excluded.size,
  how_to_use = excluded.how_to_use,
  good_for = excluded.good_for,
  features = excluded.features,
  is_published = excluded.is_published,
  placed_by = excluded.placed_by;

insert into public.products (
  id, slug, brand_id, name, category, category_id, price, description, accent,
  badge, affiliate_url, affiliate_network, image_url, rating, review_count,
  size, how_to_use, good_for, smells_like, finish, features, is_published, placed_by
) values
  (
    'b0000000-0000-0000-0000-000000000014',
    $mj$mini-dew$mj$,
    (select id from public.brands where slug = 'moon-juice'),
    $mj$Mini Dew$mj$,
    'electrolytes',
    (select id from public.categories where slug = 'electrolytes'),
    30.8,
    $mj$Hydration + mineralization$mj$,
    $mj$#5E4B45$mj$,
    $mj$Popular$mj$,
    $mj$https://moonjuice.com/products/mini-dew-electrolyte-powder-mix$mj$,
    'direct',
    $mj$https://moonjuice.com/cdn/shop/files/Mini_Dew_SFP_800x800_0fae2dde-03ee-45de-b9b5-9a0382b371d9.png?v=1762198818&width=800$mj$,
    4.6,
    442,
    $mj$30 servings$mj$,
    $mj$Mix 1 tsp of this electrolyte drink powder in 12oz of water every day. Also great for saunas, exercise, travel, or when you're feeling blah. Friendly for adults and kids 4+.$mj$,
    $mj$Hydration supports optimal hydration by maintaining water balance in and around cells; Brain enhances memory and cognitive performance, helps reduce brain fog and mental fatigue; Hormones can reduce P$mj$,
    $mj$$mj$,
    $mj$$mj$,
    array[$f$100% Traceable$f$, $f$Clinically Proven Potency$f$, $f$3rd Party Tested$f$, $f$Vegan$f$, $f$No Fillers or Junk$f$, $f$Bioavailable$f$]::text[],
    true,
    $mj$catoegy$mj$
  )
on conflict (slug) do update set
  brand_id = excluded.brand_id,
  name = excluded.name,
  category = excluded.category,
  category_id = excluded.category_id,
  price = excluded.price,
  description = excluded.description,
  accent = excluded.accent,
  badge = excluded.badge,
  affiliate_url = excluded.affiliate_url,
  affiliate_network = excluded.affiliate_network,
  image_url = excluded.image_url,
  rating = excluded.rating,
  review_count = excluded.review_count,
  size = excluded.size,
  how_to_use = excluded.how_to_use,
  good_for = excluded.good_for,
  features = excluded.features,
  is_published = excluded.is_published,
  placed_by = excluded.placed_by;

insert into public.products (
  id, slug, brand_id, name, category, category_id, price, description, accent,
  badge, affiliate_url, affiliate_network, image_url, rating, review_count,
  size, how_to_use, good_for, smells_like, finish, features, is_published, placed_by
) values
  (
    'b0000000-0000-0000-0000-000000000015',
    $mj$cellular-waters-sticks$mj$,
    (select id from public.brands where slug = 'moon-juice'),
    $mj$Cellular Waters Sticks$mj$,
    'electrolytes',
    (select id from public.categories where slug = 'electrolytes'),
    26.6,
    $mj$Ting, Mini Dew & Magnesi-Om for energy, hydration & sleep. 15 sticks.$mj$,
    $mj$#5E4B45$mj$,
    null,
    $mj$https://moonjuice.com/products/cellular-waters-sticks$mj$,
    'direct',
    $mj$https://moonjuice.com/cdn/shop/files/Cellular-Water-Sticks.png?v=1762198958&width=800$mj$,
    4.9,
    31,
    $mj$15 sticks$mj$,
    $mj$Ting 1 stick in water every day Mini Dew 1 stick in 12 oz water every day Magnesi-Om 1 stick in water every night$mj$,
    $mj$Ting:; * + Metabolismconverts fat, protein, and carbs into cellular currency; * + Energyenhances performance$mj$,
    $mj$$mj$,
    $mj$$mj$,
    array[$f$100% Traceable$f$, $f$Clinically Proven Potency$f$, $f$3rd Party Tested$f$, $f$Vegan$f$, $f$No Fillers or Junk$f$, $f$Bioavailable$f$]::text[],
    true,
    $mj$catoegy$mj$
  )
on conflict (slug) do update set
  brand_id = excluded.brand_id,
  name = excluded.name,
  category = excluded.category,
  category_id = excluded.category_id,
  price = excluded.price,
  description = excluded.description,
  accent = excluded.accent,
  badge = excluded.badge,
  affiliate_url = excluded.affiliate_url,
  affiliate_network = excluded.affiliate_network,
  image_url = excluded.image_url,
  rating = excluded.rating,
  review_count = excluded.review_count,
  size = excluded.size,
  how_to_use = excluded.how_to_use,
  good_for = excluded.good_for,
  features = excluded.features,
  is_published = excluded.is_published,
  placed_by = excluded.placed_by;

insert into public.products (
  id, slug, brand_id, name, category, category_id, price, description, accent,
  badge, affiliate_url, affiliate_network, image_url, rating, review_count,
  size, how_to_use, good_for, smells_like, finish, features, is_published, placed_by
) values
  (
    'b0000000-0000-0000-0000-000000000016',
    $mj$cosmic-cocoa$mj$,
    (select id from public.brands where slug = 'moon-juice'),
    $mj$Cosmic Cocoa$mj$,
    'supplements',
    (select id from public.categories where slug = 'supplements'),
    30.8,
    $mj$Hot chocolate for libido, mood + skin$mj$,
    $mj$#5E4B45$mj$,
    $mj$Popular$mj$,
    $mj$https://moonjuice.com/products/cosmic-cocoa$mj$,
    'direct',
    $mj$https://moonjuice.com/cdn/shop/files/Cosmic-COCOA-new-label.png?v=1782322781&width=800$mj$,
    4.8,
    726,
    $mj$14 servings$mj$,
    $mj$Add 2 tbsp of this adaptogen + mushroom hot chocolate blend to 8 oz hot water or hot milk of choice (almond milk, coconut milk). Blend on high. Sip in bliss.$mj$,
    $mj$Traditionally used to help:; Organic cacao:Antioxidant arousal food; Vegan creamer for skin, hair + nails.$mj$,
    $mj$$mj$,
    $mj$$mj$,
    array[$f$100% Traceable$f$, $f$Clinically Proven Potency$f$, $f$3rd Party Tested$f$, $f$Vegan$f$, $f$No Fillers or Junk$f$, $f$Bioavailable$f$]::text[],
    true,
    $mj$catoegy$mj$
  )
on conflict (slug) do update set
  brand_id = excluded.brand_id,
  name = excluded.name,
  category = excluded.category,
  category_id = excluded.category_id,
  price = excluded.price,
  description = excluded.description,
  accent = excluded.accent,
  badge = excluded.badge,
  affiliate_url = excluded.affiliate_url,
  affiliate_network = excluded.affiliate_network,
  image_url = excluded.image_url,
  rating = excluded.rating,
  review_count = excluded.review_count,
  size = excluded.size,
  how_to_use = excluded.how_to_use,
  good_for = excluded.good_for,
  features = excluded.features,
  is_published = excluded.is_published,
  placed_by = excluded.placed_by;

insert into public.products (
  id, slug, brand_id, name, category, category_id, price, description, accent,
  badge, affiliate_url, affiliate_network, image_url, rating, review_count,
  size, how_to_use, good_for, smells_like, finish, features, is_published, placed_by
) values
  (
    'b0000000-0000-0000-0000-000000000017',
    $mj$collagen-protect$mj$,
    (select id from public.brands where slug = 'moon-juice'),
    $mj$Collagen Protect$mj$,
    'supplements',
    (select id from public.categories where slug = 'supplements'),
    40.6,
    $mj$Minimize fine lines + deep skin hydration$mj$,
    $mj$#5E4B45$mj$,
    $mj$Popular$mj$,
    $mj$https://moonjuice.com/products/beauty-shroom-vegan-collagen-protection$mj$,
    'direct',
    $mj$https://moonjuice.com/cdn/shop/products/Collagen_Protect_Bag_800x800_1.png?v=1766547630&width=800$mj$,
    4.7,
    928,
    $mj$30 servings$mj$,
    $mj$Collagen Protect is a vegan collagen supplement. Add 1 rounded tbsp of this skin-protecting creamer to coffee or smoothies to promote healthy skin. Our plant-based collagen powder is a collagen builder that contains no additives, so it may clump. Blend for maximum yum.$mj$,
    $mj$preserve your natural collagen production; hydrate skin; improve skin elasticity$mj$,
    $mj$$mj$,
    $mj$$mj$,
    array[$f$100% Traceable$f$, $f$Clinically Proven Potency$f$, $f$3rd Party Tested$f$, $f$Vegan$f$, $f$No Fillers or Junk$f$, $f$Bioavailable$f$]::text[],
    true,
    $mj$catoegy$mj$
  )
on conflict (slug) do update set
  brand_id = excluded.brand_id,
  name = excluded.name,
  category = excluded.category,
  category_id = excluded.category_id,
  price = excluded.price,
  description = excluded.description,
  accent = excluded.accent,
  badge = excluded.badge,
  affiliate_url = excluded.affiliate_url,
  affiliate_network = excluded.affiliate_network,
  image_url = excluded.image_url,
  rating = excluded.rating,
  review_count = excluded.review_count,
  size = excluded.size,
  how_to_use = excluded.how_to_use,
  good_for = excluded.good_for,
  features = excluded.features,
  is_published = excluded.is_published,
  placed_by = excluded.placed_by;

insert into public.products (
  id, slug, brand_id, name, category, category_id, price, description, accent,
  badge, affiliate_url, affiliate_network, image_url, rating, review_count,
  size, how_to_use, good_for, smells_like, finish, features, is_published, placed_by
) values
  (
    'b0000000-0000-0000-0000-000000000018',
    $mj$plump-jelly$mj$,
    (select id from public.brands where slug = 'moon-juice'),
    $mj$Plump Jelly$mj$,
    'skincare',
    (select id from public.categories where slug = 'skincare'),
    40.6,
    $mj$A glass of water for your face$mj$,
    $mj$#5E4B45$mj$,
    $mj$Popular$mj$,
    $mj$https://moonjuice.com/products/beauty-shroom-plumping-jelly-serum$mj$,
    'direct',
    $mj$https://moonjuice.com/cdn/shop/products/Plump_Jelly_New_800x800_e3f92bf7-9fcd-417b-b30d-ddfe337fcbdd.png?v=1762198144&width=800$mj$,
    4.8,
    823,
    $mj$$mj$,
    $mj$AM + PM. Apply 3 pumps onto damp skin. Use after in the PM. Follow with . Hydrates lips too. Tips + Cherub facial: apply 6 pumps to soaking wet face/neck + Use as a primer (let it sink in)$mj$,
    $mj$Shown to help:; hydrate in and around the cells; preserve elasticity and bounce$mj$,
    $mj$$mj$,
    $mj$$mj$,
    array[$f$100% Traceable$f$, $f$Clinically Proven Potency$f$, $f$3rd Party Tested$f$, $f$Vegan$f$, $f$No Fillers or Junk$f$, $f$Bioavailable$f$]::text[],
    true,
    $mj$catoegy$mj$
  )
on conflict (slug) do update set
  brand_id = excluded.brand_id,
  name = excluded.name,
  category = excluded.category,
  category_id = excluded.category_id,
  price = excluded.price,
  description = excluded.description,
  accent = excluded.accent,
  badge = excluded.badge,
  affiliate_url = excluded.affiliate_url,
  affiliate_network = excluded.affiliate_network,
  image_url = excluded.image_url,
  rating = excluded.rating,
  review_count = excluded.review_count,
  size = excluded.size,
  how_to_use = excluded.how_to_use,
  good_for = excluded.good_for,
  features = excluded.features,
  is_published = excluded.is_published,
  placed_by = excluded.placed_by;

insert into public.products (
  id, slug, brand_id, name, category, category_id, price, description, accent,
  badge, affiliate_url, affiliate_network, image_url, rating, review_count,
  size, how_to_use, good_for, smells_like, finish, features, is_published, placed_by
) values
  (
    'b0000000-0000-0000-0000-000000000019',
    $mj$acid-potion$mj$,
    (select id from public.brands where slug = 'moon-juice'),
    $mj$Acid Potion$mj$,
    'skincare',
    (select id from public.categories where slug = 'skincare'),
    29.4,
    $mj$Quickie liquid facial. Exfoliate, unclog + soothe$mj$,
    $mj$#5E4B45$mj$,
    $mj$Popular$mj$,
    $mj$https://moonjuice.com/products/beauty-shroom-exfoliating-acid-potion$mj$,
    'direct',
    $mj$https://moonjuice.com/cdn/shop/products/Acid_Potion_New_800x800_ecfe112d-af61-458c-a2b6-1564d1282f9f.png?v=1762198144&width=800$mj$,
    4.8,
    867,
    $mj$$mj$,
    $mj$PM. Use 3 nights a week. Shake a quarter sized amount into palm and pat into clean face/neck with fingertips. Don't rinse! Follow with and . Tips + Ditch the cotton round, apply directly with palms + Use multiple nights in a row to penetrate stubborn pores + Target a specificskin concernorproblem area (doesn't have to be your full face)$mj$,
    $mj$Shown to help:; resurface skin and unclog pores; stimulate collagen production$mj$,
    $mj$$mj$,
    $mj$$mj$,
    array[$f$100% Traceable$f$, $f$Clinically Proven Potency$f$, $f$3rd Party Tested$f$, $f$Vegan$f$, $f$No Fillers or Junk$f$, $f$Bioavailable$f$]::text[],
    true,
    $mj$catoegy$mj$
  )
on conflict (slug) do update set
  brand_id = excluded.brand_id,
  name = excluded.name,
  category = excluded.category,
  category_id = excluded.category_id,
  price = excluded.price,
  description = excluded.description,
  accent = excluded.accent,
  badge = excluded.badge,
  affiliate_url = excluded.affiliate_url,
  affiliate_network = excluded.affiliate_network,
  image_url = excluded.image_url,
  rating = excluded.rating,
  review_count = excluded.review_count,
  size = excluded.size,
  how_to_use = excluded.how_to_use,
  good_for = excluded.good_for,
  features = excluded.features,
  is_published = excluded.is_published,
  placed_by = excluded.placed_by;

insert into public.products (
  id, slug, brand_id, name, category, category_id, price, description, accent,
  badge, affiliate_url, affiliate_network, image_url, rating, review_count,
  size, how_to_use, good_for, smells_like, finish, features, is_published, placed_by
) values
  (
    'b0000000-0000-0000-0000-000000000020',
    $mj$acid-potion-travel-size$mj$,
    (select id from public.brands where slug = 'moon-juice'),
    $mj$Acid Potion Travel Size$mj$,
    'skincare',
    (select id from public.categories where slug = 'skincare'),
    18,
    $mj$Quickie liquid facial. Exfoliate, unclog & soothe.$mj$,
    $mj$#5E4B45$mj$,
    null,
    $mj$https://moonjuice.com/products/acid-potion-travel-size$mj$,
    'direct',
    $mj$https://moonjuice.com/cdn/shop/products/220801_MJ_Capture_22-08-01_046.png?v=1762198641&width=800$mj$,
    4.7,
    36,
    $mj$$mj$,
    $mj$PM. Use 3 nights a week. Shake a quarter sized amount into palm and pat into clean face/neck with fingertips. Don't rinse! Follow with and .$mj$,
    $mj$Helps:; * + resurface skin and unclog pores; * + stimulate collagen production$mj$,
    $mj$$mj$,
    $mj$$mj$,
    array[$f$100% Traceable$f$, $f$Clinically Proven Potency$f$, $f$3rd Party Tested$f$, $f$Vegan$f$, $f$No Fillers or Junk$f$, $f$Bioavailable$f$]::text[],
    true,
    $mj$catoegy$mj$
  )
on conflict (slug) do update set
  brand_id = excluded.brand_id,
  name = excluded.name,
  category = excluded.category,
  category_id = excluded.category_id,
  price = excluded.price,
  description = excluded.description,
  accent = excluded.accent,
  badge = excluded.badge,
  affiliate_url = excluded.affiliate_url,
  affiliate_network = excluded.affiliate_network,
  image_url = excluded.image_url,
  rating = excluded.rating,
  review_count = excluded.review_count,
  size = excluded.size,
  how_to_use = excluded.how_to_use,
  good_for = excluded.good_for,
  features = excluded.features,
  is_published = excluded.is_published,
  placed_by = excluded.placed_by;

insert into public.products (
  id, slug, brand_id, name, category, category_id, price, description, accent,
  badge, affiliate_url, affiliate_network, image_url, rating, review_count,
  size, how_to_use, good_for, smells_like, finish, features, is_published, placed_by
) values
  (
    'b0000000-0000-0000-0000-000000000021',
    $mj$cosmic-cream$mj$,
    (select id from public.brands where slug = 'moon-juice'),
    $mj$Cosmic Cream$mj$,
    'skincare',
    (select id from public.categories where slug = 'skincare'),
    40.6,
    $mj$Moisturize + replenish$mj$,
    $mj$#5E4B45$mj$,
    $mj$Popular$mj$,
    $mj$https://moonjuice.com/products/cosmic-cream$mj$,
    'direct',
    $mj$https://moonjuice.com/cdn/shop/products/Cosmic_Cream_New_800x800_2d7fc7cb-584d-4bee-b1ba-20cd19f3e92f.png?v=1762198193&width=800$mj$,
    4.8,
    398,
    $mj$$mj$,
    $mj$AM + PM. Swipe onto face/neck after applying or other serums. Leaves a dewy finish.$mj$,
    $mj$Shown to help:; Seal in moisture.; Improve skin's natural elasticity and firmness.$mj$,
    $mj$$mj$,
    $mj$$mj$,
    array[$f$100% Traceable$f$, $f$Clinically Proven Potency$f$, $f$3rd Party Tested$f$, $f$Vegan$f$, $f$No Fillers or Junk$f$, $f$Bioavailable$f$]::text[],
    true,
    $mj$catoegy$mj$
  )
on conflict (slug) do update set
  brand_id = excluded.brand_id,
  name = excluded.name,
  category = excluded.category,
  category_id = excluded.category_id,
  price = excluded.price,
  description = excluded.description,
  accent = excluded.accent,
  badge = excluded.badge,
  affiliate_url = excluded.affiliate_url,
  affiliate_network = excluded.affiliate_network,
  image_url = excluded.image_url,
  rating = excluded.rating,
  review_count = excluded.review_count,
  size = excluded.size,
  how_to_use = excluded.how_to_use,
  good_for = excluded.good_for,
  features = excluded.features,
  is_published = excluded.is_published,
  placed_by = excluded.placed_by;

insert into public.products (
  id, slug, brand_id, name, category, category_id, price, description, accent,
  badge, affiliate_url, affiliate_network, image_url, rating, review_count,
  size, how_to_use, good_for, smells_like, finish, features, is_published, placed_by
) values
  (
    'b0000000-0000-0000-0000-000000000022',
    $mj$milk-cleanse$mj$,
    (select id from public.brands where slug = 'moon-juice'),
    $mj$Milk Cleanse$mj$,
    'skincare',
    (select id from public.categories where slug = 'skincare'),
    22.4,
    $mj$Cleanse, soothe + nourish$mj$,
    $mj$#5E4B45$mj$,
    $mj$Popular$mj$,
    $mj$https://moonjuice.com/products/milk-cleanse$mj$,
    'direct',
    $mj$https://moonjuice.com/cdn/shop/products/Milk_Cleanse_New_800x800_cc1149bb-cc99-4ac2-8678-021068b2016e.png?v=1762198193&width=800$mj$,
    4.9,
    359,
    $mj$$mj$,
    $mj$Massage onto wet skin and rinse. AM, follow with and . PM, follow with , , and . Tips + Safe as a double cleanser + Use as a vulva wash (it's pH balanced)$mj$,
    $mj$Shown to help:; match skin's pH and never strip; hydrate and nourish$mj$,
    $mj$$mj$,
    $mj$$mj$,
    array[$f$100% Traceable$f$, $f$Clinically Proven Potency$f$, $f$3rd Party Tested$f$, $f$Vegan$f$, $f$No Fillers or Junk$f$, $f$Bioavailable$f$]::text[],
    true,
    $mj$catoegy$mj$
  )
on conflict (slug) do update set
  brand_id = excluded.brand_id,
  name = excluded.name,
  category = excluded.category,
  category_id = excluded.category_id,
  price = excluded.price,
  description = excluded.description,
  accent = excluded.accent,
  badge = excluded.badge,
  affiliate_url = excluded.affiliate_url,
  affiliate_network = excluded.affiliate_network,
  image_url = excluded.image_url,
  rating = excluded.rating,
  review_count = excluded.review_count,
  size = excluded.size,
  how_to_use = excluded.how_to_use,
  good_for = excluded.good_for,
  features = excluded.features,
  is_published = excluded.is_published,
  placed_by = excluded.placed_by;

insert into public.products (
  id, slug, brand_id, name, category, category_id, price, description, accent,
  badge, affiliate_url, affiliate_network, image_url, rating, review_count,
  size, how_to_use, good_for, smells_like, finish, features, is_published, placed_by
) values
  (
    'b0000000-0000-0000-0000-000000000023',
    $mj$ashwagandha$mj$,
    (select id from public.brands where slug = 'moon-juice'),
    $mj$Ashwagandha$mj$,
    'supplements',
    (select id from public.categories where slug = 'supplements'),
    26.6,
    $mj$15:1 full-spectrum root extract$mj$,
    $mj$#5E4B45$mj$,
    $mj$Popular$mj$,
    $mj$https://moonjuice.com/products/ashwagandha-root-extract$mj$,
    'direct',
    $mj$https://moonjuice.com/cdn/shop/products/Ashwagandha_New_800x800_cfb8d640-1544-44b1-bd66-733000f40682.png?v=1762197951&width=800$mj$,
    4.8,
    421,
    $mj$58 servings$mj$,
    $mj$A dark, brown organic Ashwagandha root powder with a bitter, molasses-like flavor. Pairs well with chocolate, coffee, maple, and baked goods. The suggested use is between 1/4--1/2 tsp daily to experience optimal Ashwagandha benefits.$mj$,
    $mj$reduce stress and regulate cortisol levels; enhance focus and mental stamina; reduce irritability and stress-related cravings$mj$,
    $mj$$mj$,
    $mj$$mj$,
    array[$f$100% Traceable$f$, $f$Clinically Proven Potency$f$, $f$3rd Party Tested$f$, $f$Vegan$f$, $f$No Fillers or Junk$f$, $f$Bioavailable$f$]::text[],
    true,
    $mj$catoegy$mj$
  )
on conflict (slug) do update set
  brand_id = excluded.brand_id,
  name = excluded.name,
  category = excluded.category,
  category_id = excluded.category_id,
  price = excluded.price,
  description = excluded.description,
  accent = excluded.accent,
  badge = excluded.badge,
  affiliate_url = excluded.affiliate_url,
  affiliate_network = excluded.affiliate_network,
  image_url = excluded.image_url,
  rating = excluded.rating,
  review_count = excluded.review_count,
  size = excluded.size,
  how_to_use = excluded.how_to_use,
  good_for = excluded.good_for,
  features = excluded.features,
  is_published = excluded.is_published,
  placed_by = excluded.placed_by;

insert into public.products (
  id, slug, brand_id, name, category, category_id, price, description, accent,
  badge, affiliate_url, affiliate_network, image_url, rating, review_count,
  size, how_to_use, good_for, smells_like, finish, features, is_published, placed_by
) values
  (
    'b0000000-0000-0000-0000-000000000024',
    $mj$pearl$mj$,
    (select id from public.brands where slug = 'moon-juice'),
    $mj$Pearl$mj$,
    'supplements',
    (select id from public.categories where slug = 'supplements'),
    37.8,
    $mj$Beauty gem for collagen hair + nails$mj$,
    $mj$#5E4B45$mj$,
    $mj$Popular$mj$,
    $mj$https://moonjuice.com/products/pearl$mj$,
    'direct',
    $mj$https://moonjuice.com/cdn/shop/products/Pearl_800x800_3431461e-5e0e-4bfe-b903-f39c29de3809.png?v=1762197964&width=800$mj$,
    4.8,
    564,
    $mj$30 servings$mj$,
    $mj$Pairs well with everything---smoothies, coffee, tea, tonics, milks, and baking. Add a pinch to your moisturizer or raw honey for a mask, or brush directly onto skin before bed. Use 1/2 tsp daily.$mj$,
    $mj$stimulate the body's natural collagen; even skin tone; strengthen hair, skin, and nails$mj$,
    $mj$$mj$,
    $mj$$mj$,
    array[$f$100% Traceable$f$, $f$Clinically Proven Potency$f$, $f$3rd Party Tested$f$, $f$Vegan$f$, $f$No Fillers or Junk$f$, $f$Bioavailable$f$]::text[],
    true,
    $mj$catoegy$mj$
  )
on conflict (slug) do update set
  brand_id = excluded.brand_id,
  name = excluded.name,
  category = excluded.category,
  category_id = excluded.category_id,
  price = excluded.price,
  description = excluded.description,
  accent = excluded.accent,
  badge = excluded.badge,
  affiliate_url = excluded.affiliate_url,
  affiliate_network = excluded.affiliate_network,
  image_url = excluded.image_url,
  rating = excluded.rating,
  review_count = excluded.review_count,
  size = excluded.size,
  how_to_use = excluded.how_to_use,
  good_for = excluded.good_for,
  features = excluded.features,
  is_published = excluded.is_published,
  placed_by = excluded.placed_by;

insert into public.products (
  id, slug, brand_id, name, category, category_id, price, description, accent,
  badge, affiliate_url, affiliate_network, image_url, rating, review_count,
  size, how_to_use, good_for, smells_like, finish, features, is_published, placed_by
) values
  (
    'b0000000-0000-0000-0000-000000000025',
    $mj$cordyceps$mj$,
    (select id from public.brands where slug = 'moon-juice'),
    $mj$Cordyceps$mj$,
    'supplements',
    (select id from public.categories where slug = 'supplements'),
    43.2,
    $mj$Energy, stamina + lung capacity$mj$,
    $mj$#5E4B45$mj$,
    null,
    $mj$https://moonjuice.com/products/cordyceps$mj$,
    'direct',
    $mj$https://moonjuice.com/cdn/shop/products/Cordyceps_800x800_08ab29c6-1823-4d35-bc4f-f6e481feaf62.png?v=1762197958&width=800$mj$,
    4.9,
    179,
    $mj$36 servings$mj$,
    $mj$A golden powder with a slightly sweet anise-y, woody flavor. Pairs well with tropical fruits, citrus, ginger, chocolate, and coffee. Use between 1--3 tsp of this dietary supplement daily. Our Cordyceps mushroom extract is a key ingredient in Milk Chocolate Momentum. Find the recipe in$mj$,
    $mj$Traditionally used to help:; Sustain energy and stamina.; Encourage healthy lung capacity.$mj$,
    $mj$$mj$,
    $mj$$mj$,
    array[$f$100% Traceable$f$, $f$Clinically Proven Potency$f$, $f$3rd Party Tested$f$, $f$Vegan$f$, $f$No Fillers or Junk$f$, $f$Bioavailable$f$]::text[],
    true,
    $mj$catoegy$mj$
  )
on conflict (slug) do update set
  brand_id = excluded.brand_id,
  name = excluded.name,
  category = excluded.category,
  category_id = excluded.category_id,
  price = excluded.price,
  description = excluded.description,
  accent = excluded.accent,
  badge = excluded.badge,
  affiliate_url = excluded.affiliate_url,
  affiliate_network = excluded.affiliate_network,
  image_url = excluded.image_url,
  rating = excluded.rating,
  review_count = excluded.review_count,
  size = excluded.size,
  how_to_use = excluded.how_to_use,
  good_for = excluded.good_for,
  features = excluded.features,
  is_published = excluded.is_published,
  placed_by = excluded.placed_by;

insert into public.products (
  id, slug, brand_id, name, category, category_id, price, description, accent,
  badge, affiliate_url, affiliate_network, image_url, rating, review_count,
  size, how_to_use, good_for, smells_like, finish, features, is_published, placed_by
) values
  (
    'b0000000-0000-0000-0000-000000000026',
    $mj$reishi$mj$,
    (select id from public.brands where slug = 'moon-juice'),
    $mj$Reishi$mj$,
    'supplements',
    (select id from public.categories where slug = 'supplements'),
    33.6,
    $mj$Nootropic mushroom. Mood + concentration$mj$,
    $mj$#5E4B45$mj$,
    null,
    $mj$https://moonjuice.com/products/reishi$mj$,
    'direct',
    $mj$https://moonjuice.com/cdn/shop/files/Reishi_800x800_27ba2f24-b43a-4be7-bd5e-a280927ee0ee.png?v=1762197965&width=800$mj$,
    4.9,
    188,
    $mj$14 servings$mj$,
    $mj$A dark brown powder with a strong, botanical aroma and an intensely tannic taste with some bitterness. Pairs well with chocolate and coffee. Use between 1--4 tsp daily. Reishi is a key ingredient in Queen Healer Bread. Find the recipe in .$mj$,
    $mj$Traditionally used to help:; Balance mood and support concentration.; Crowned Queen Healer in TCM because of its ability to strengthen the heart and mind.$mj$,
    $mj$$mj$,
    $mj$$mj$,
    array[$f$100% Traceable$f$, $f$Clinically Proven Potency$f$, $f$3rd Party Tested$f$, $f$Vegan$f$, $f$No Fillers or Junk$f$, $f$Bioavailable$f$]::text[],
    true,
    $mj$catoegy$mj$
  )
on conflict (slug) do update set
  brand_id = excluded.brand_id,
  name = excluded.name,
  category = excluded.category,
  category_id = excluded.category_id,
  price = excluded.price,
  description = excluded.description,
  accent = excluded.accent,
  badge = excluded.badge,
  affiliate_url = excluded.affiliate_url,
  affiliate_network = excluded.affiliate_network,
  image_url = excluded.image_url,
  rating = excluded.rating,
  review_count = excluded.review_count,
  size = excluded.size,
  how_to_use = excluded.how_to_use,
  good_for = excluded.good_for,
  features = excluded.features,
  is_published = excluded.is_published,
  placed_by = excluded.placed_by;

insert into public.products (
  id, slug, brand_id, name, category, category_id, price, description, accent,
  badge, affiliate_url, affiliate_network, image_url, rating, review_count,
  size, how_to_use, good_for, smells_like, finish, features, is_published, placed_by
) values
  (
    'b0000000-0000-0000-0000-000000000027',
    $mj$chaga$mj$,
    (select id from public.brands where slug = 'moon-juice'),
    $mj$Chaga$mj$,
    'supplements',
    (select id from public.categories where slug = 'supplements'),
    33.6,
    $mj$Protective mushroom. Energy + immunity$mj$,
    $mj$#5E4B45$mj$,
    null,
    $mj$https://moonjuice.com/products/chaga$mj$,
    'direct',
    $mj$https://moonjuice.com/cdn/shop/products/Chaga_800x800_1b367417-2355-4347-8401-7cd972bed033.png?v=1762197955&width=800$mj$,
    4.9,
    155,
    $mj$13 servings$mj$,
    $mj$This organic Chaga supplement is a dark, brown powder with a very mild and palatable earthy flavor, perfect for pairing with smoothies, lattes, coffee, andherbal tea. Use 1 tsp daily.$mj$,
    $mj$Support healthy immune system.; Balance energy.; Reduce fatigue.$mj$,
    $mj$$mj$,
    $mj$$mj$,
    array[$f$100% Traceable$f$, $f$Clinically Proven Potency$f$, $f$3rd Party Tested$f$, $f$Vegan$f$, $f$No Fillers or Junk$f$, $f$Bioavailable$f$]::text[],
    true,
    $mj$catoegy$mj$
  )
on conflict (slug) do update set
  brand_id = excluded.brand_id,
  name = excluded.name,
  category = excluded.category,
  category_id = excluded.category_id,
  price = excluded.price,
  description = excluded.description,
  accent = excluded.accent,
  badge = excluded.badge,
  affiliate_url = excluded.affiliate_url,
  affiliate_network = excluded.affiliate_network,
  image_url = excluded.image_url,
  rating = excluded.rating,
  review_count = excluded.review_count,
  size = excluded.size,
  how_to_use = excluded.how_to_use,
  good_for = excluded.good_for,
  features = excluded.features,
  is_published = excluded.is_published,
  placed_by = excluded.placed_by;

insert into public.products (
  id, slug, brand_id, name, category, category_id, price, description, accent,
  badge, affiliate_url, affiliate_network, image_url, rating, review_count,
  size, how_to_use, good_for, smells_like, finish, features, is_published, placed_by
) values
  (
    'b0000000-0000-0000-0000-000000000028',
    $mj$supersex$mj$,
    (select id from public.brands where slug = 'moon-juice'),
    $mj$SuperSex$mj$,
    'supplements',
    (select id from public.categories where slug = 'supplements'),
    54,
    $mj$Adaptogens for Fire. Libido, Hormonal Balance & Creative Energy.$mj$,
    $mj$#5E4B45$mj$,
    null,
    $mj$https://moonjuice.com/products/supersex$mj$,
    'direct',
    $mj$https://moonjuice.com/cdn/shop/files/MoonJuice_PPage_SuperSex_1_V2.png?v=1762199763&width=800$mj$,
    5,
    5,
    $mj$20 servings$mj$,
    $mj$Take 3 caps of SuperSex every morning, with or without food.$mj$,
    $mj$Libido:; Helps ignite desire and strengthen sensation; Hormonal Balance:$mj$,
    $mj$$mj$,
    $mj$$mj$,
    array[$f$100% Traceable$f$, $f$Clinically Proven Potency$f$, $f$3rd Party Tested$f$, $f$Vegan$f$, $f$No Fillers or Junk$f$, $f$Bioavailable$f$]::text[],
    true,
    $mj$catoegy$mj$
  )
on conflict (slug) do update set
  brand_id = excluded.brand_id,
  name = excluded.name,
  category = excluded.category,
  category_id = excluded.category_id,
  price = excluded.price,
  description = excluded.description,
  accent = excluded.accent,
  badge = excluded.badge,
  affiliate_url = excluded.affiliate_url,
  affiliate_network = excluded.affiliate_network,
  image_url = excluded.image_url,
  rating = excluded.rating,
  review_count = excluded.review_count,
  size = excluded.size,
  how_to_use = excluded.how_to_use,
  good_for = excluded.good_for,
  features = excluded.features,
  is_published = excluded.is_published,
  placed_by = excluded.placed_by;

insert into public.products (
  id, slug, brand_id, name, category, category_id, price, description, accent,
  badge, affiliate_url, affiliate_network, image_url, rating, review_count,
  size, how_to_use, good_for, smells_like, finish, features, is_published, placed_by
) values
  (
    'b0000000-0000-0000-0000-000000000029',
    $mj$superbrain$mj$,
    (select id from public.brands where slug = 'moon-juice'),
    $mj$SuperBrain$mj$,
    'supplements',
    (select id from public.categories where slug = 'supplements'),
    54,
    $mj$Adaptogens for focus. Mental stamina, alertness & concentration.$mj$,
    $mj$#5E4B45$mj$,
    null,
    $mj$https://moonjuice.com/products/super-brain$mj$,
    'direct',
    $mj$https://moonjuice.com/cdn/shop/files/MoonJuice_PPage_SuperBrain_V2.png?v=1762199756&width=800$mj$,
    4.8,
    4,
    $mj$14 servings$mj$,
    $mj$Take 4 caps of SuperBrain every morning, with or without food.*$mj$,
    $mj$Mental Stamina:; Targets stress to promote mental stamina and clarity; Alertness:$mj$,
    $mj$$mj$,
    $mj$$mj$,
    array[$f$100% Traceable$f$, $f$Clinically Proven Potency$f$, $f$3rd Party Tested$f$, $f$Vegan$f$, $f$No Fillers or Junk$f$, $f$Bioavailable$f$]::text[],
    true,
    $mj$catoegy$mj$
  )
on conflict (slug) do update set
  brand_id = excluded.brand_id,
  name = excluded.name,
  category = excluded.category,
  category_id = excluded.category_id,
  price = excluded.price,
  description = excluded.description,
  accent = excluded.accent,
  badge = excluded.badge,
  affiliate_url = excluded.affiliate_url,
  affiliate_network = excluded.affiliate_network,
  image_url = excluded.image_url,
  rating = excluded.rating,
  review_count = excluded.review_count,
  size = excluded.size,
  how_to_use = excluded.how_to_use,
  good_for = excluded.good_for,
  features = excluded.features,
  is_published = excluded.is_published,
  placed_by = excluded.placed_by;
