insert into public.products (
  id, slug, brand_id, name, category, category_id, price, description, accent,
  badge, affiliate_url, affiliate_network, image_url, rating, review_count,
  size, how_to_use, good_for, smells_like, finish, features, is_published, placed_by
) values
  (
    'b0000000-0000-0000-0000-000000000018',
    $mj$plump-jelly$mj$,
    (select id from public.brands where slug = 'moon-juice'),
    $mj$Plump Jelly$mj$,
    'skincare',
    (select id from public.categories where slug = 'skincare'),
    40.6,
    $mj$A glass of water for your face$mj$,
    $mj$#5E4B45$mj$,
    $mj$Popular$mj$,
    $mj$https://moonjuice.com/products/beauty-shroom-plumping-jelly-serum$mj$,
    'direct',
    $mj$https://moonjuice.com/cdn/shop/products/Plump_Jelly_New_800x800_e3f92bf7-9fcd-417b-b30d-ddfe337fcbdd.png?v=1762198144&width=800$mj$,
    4.8,
    823,
    $mj$$mj$,
    $mj$AM + PM. Apply 3 pumps onto damp skin. Use after in the PM. Follow with . Hydrates lips too. Tips + Cherub facial: apply 6 pumps to soaking wet face/neck + Use as a primer (let it sink in)$mj$,
    $mj$Shown to help:; hydrate in and around the cells; preserve elasticity and bounce$mj$,
    $mj$$mj$,
    $mj$$mj$,
    array[$f$100% Traceable$f$, $f$Clinically Proven Potency$f$, $f$3rd Party Tested$f$, $f$Vegan$f$, $f$No Fillers or Junk$f$, $f$Bioavailable$f$]::text[],
    true,
    $mj$catoegy$mj$
  )
on conflict (slug) do update set
  brand_id = excluded.brand_id,
  name = excluded.name,
  category = excluded.category,
  category_id = excluded.category_id,
  price = excluded.price,
  description = excluded.description,
  accent = excluded.accent,
  badge = excluded.badge,
  affiliate_url = excluded.affiliate_url,
  affiliate_network = excluded.affiliate_network,
  image_url = excluded.image_url,
  rating = excluded.rating,
  review_count = excluded.review_count,
  size = excluded.size,
  how_to_use = excluded.how_to_use,
  good_for = excluded.good_for,
  features = excluded.features,
  is_published = excluded.is_published,
  placed_by = excluded.placed_by;
