insert into public.products (
  id, slug, brand_id, name, category, category_id, price, description, accent,
  badge, affiliate_url, affiliate_network, image_url, rating, review_count,
  size, how_to_use, good_for, smells_like, finish, features, is_published, placed_by
) values
  (
    'b0000000-0000-0000-0000-000000000002',
    $mj$magnesi-om$mj$,
    (select id from public.brands where slug = 'moon-juice'),
    $mj$Magnesi-Om$mj$,
    'supplements',
    (select id from public.categories where slug = 'supplements'),
    30.8,
    $mj$Rest, relaxation + regularity$mj$,
    $mj$#5E4B45$mj$,
    $mj$Best seller$mj$,
    $mj$https://moonjuice.com/products/magnesi-om-magnesium-supplement$mj$,
    'direct',
    $mj$https://moonjuice.com/cdn/shop/products/Mag_New_800x800_4dbf7a23-5fdf-4b50-81ee-e0618d9f8c2b.png?v=1782516533&width=800$mj$,
    4.8,
    3853,
    $mj$30 servings$mj$,
    $mj$Mix 1 tsp of our magnesium powder in water every night or when you need to chill. Or mix one serving size with Tart Cherry Juice + sparkling water to make your own Sleepy Girl Mocktail.$mj$,
    $mj$Relaxation: Enhances feelings of calm, improves mood, reduces muscle aches; Brain Health: Supports healthy cognitive aging and brain function; Regularity: Supports regular bowel movement, soothes and$mj$,
    $mj$$mj$,
    $mj$$mj$,
    array[$f$100% Traceable$f$, $f$Clinically Proven Potency$f$, $f$3rd Party Tested$f$, $f$Vegan$f$, $f$No Fillers or Junk$f$, $f$Bioavailable$f$]::text[],
    true,
    $mj$catoegy$mj$
  )
on conflict (slug) do update set
  brand_id = excluded.brand_id,
  name = excluded.name,
  category = excluded.category,
  category_id = excluded.category_id,
  price = excluded.price,
  description = excluded.description,
  accent = excluded.accent,
  badge = excluded.badge,
  affiliate_url = excluded.affiliate_url,
  affiliate_network = excluded.affiliate_network,
  image_url = excluded.image_url,
  rating = excluded.rating,
  review_count = excluded.review_count,
  size = excluded.size,
  how_to_use = excluded.how_to_use,
  good_for = excluded.good_for,
  features = excluded.features,
  is_published = excluded.is_published,
  placed_by = excluded.placed_by;
