insert into public.products (
  id, slug, brand_id, name, category, category_id, price, description, accent,
  badge, affiliate_url, affiliate_network, image_url, rating, review_count,
  size, how_to_use, good_for, smells_like, finish, features, is_published, placed_by
) values
  (
    'b0000000-0000-0000-0000-000000000023',
    $mj$ashwagandha$mj$,
    (select id from public.brands where slug = 'moon-juice'),
    $mj$Ashwagandha$mj$,
    'supplements',
    (select id from public.categories where slug = 'supplements'),
    26.6,
    $mj$15:1 full-spectrum root extract$mj$,
    $mj$#5E4B45$mj$,
    $mj$Popular$mj$,
    $mj$https://moonjuice.com/products/ashwagandha-root-extract$mj$,
    'direct',
    $mj$https://moonjuice.com/cdn/shop/products/Ashwagandha_New_800x800_cfb8d640-1544-44b1-bd66-733000f40682.png?v=1762197951&width=800$mj$,
    4.8,
    421,
    $mj$58 servings$mj$,
    $mj$A dark, brown organic Ashwagandha root powder with a bitter, molasses-like flavor. Pairs well with chocolate, coffee, maple, and baked goods. The suggested use is between 1/4--1/2 tsp daily to experience optimal Ashwagandha benefits.$mj$,
    $mj$reduce stress and regulate cortisol levels; enhance focus and mental stamina; reduce irritability and stress-related cravings$mj$,
    $mj$$mj$,
    $mj$$mj$,
    array[$f$100% Traceable$f$, $f$Clinically Proven Potency$f$, $f$3rd Party Tested$f$, $f$Vegan$f$, $f$No Fillers or Junk$f$, $f$Bioavailable$f$]::text[],
    true,
    $mj$catoegy$mj$
  )
on conflict (slug) do update set
  brand_id = excluded.brand_id,
  name = excluded.name,
  category = excluded.category,
  category_id = excluded.category_id,
  price = excluded.price,
  description = excluded.description,
  accent = excluded.accent,
  badge = excluded.badge,
  affiliate_url = excluded.affiliate_url,
  affiliate_network = excluded.affiliate_network,
  image_url = excluded.image_url,
  rating = excluded.rating,
  review_count = excluded.review_count,
  size = excluded.size,
  how_to_use = excluded.how_to_use,
  good_for = excluded.good_for,
  features = excluded.features,
  is_published = excluded.is_published,
  placed_by = excluded.placed_by;
