insert into public.products (
  id, slug, brand_id, name, category, category_id, price, description, accent,
  badge, affiliate_url, affiliate_network, image_url, rating, review_count,
  size, how_to_use, good_for, smells_like, finish, features, is_published, placed_by
) values
  (
    'b0000000-0000-0000-0000-000000000006',
    $mj$superbeauty$mj$,
    (select id from public.brands where slug = 'moon-juice'),
    $mj$SuperBeauty$mj$,
    'supplements',
    (select id from public.categories where slug = 'supplements'),
    46.2,
    $mj$Cellular skin care. Collagen, elasticity + cell vitality$mj$,
    $mj$#5E4B45$mj$,
    $mj$Popular$mj$,
    $mj$https://moonjuice.com/products/superbeauty$mj$,
    'direct',
    $mj$https://moonjuice.com/cdn/shop/products/SuperBeauty_800x800_a9883c0f-7510-4398-9bf3-1514540ce66e.png?v=1762198217&width=800$mj$,
    4.9,
    678,
    $mj$30 servings$mj$,
    $mj$Take 2 caps every morning, with or without food.$mj$,
    $mj$minimize the appearance of fine lines; promote collagen and elasticity; protect protein, lipids and DNA from oxidative damage* †$mj$,
    $mj$$mj$,
    $mj$$mj$,
    array[$f$100% Traceable$f$, $f$Clinically Proven Potency$f$, $f$3rd Party Tested$f$, $f$Vegan$f$, $f$No Fillers or Junk$f$, $f$Bioavailable$f$]::text[],
    true,
    $mj$catoegy$mj$
  )
on conflict (slug) do update set
  brand_id = excluded.brand_id,
  name = excluded.name,
  category = excluded.category,
  category_id = excluded.category_id,
  price = excluded.price,
  description = excluded.description,
  accent = excluded.accent,
  badge = excluded.badge,
  affiliate_url = excluded.affiliate_url,
  affiliate_network = excluded.affiliate_network,
  image_url = excluded.image_url,
  rating = excluded.rating,
  review_count = excluded.review_count,
  size = excluded.size,
  how_to_use = excluded.how_to_use,
  good_for = excluded.good_for,
  features = excluded.features,
  is_published = excluded.is_published,
  placed_by = excluded.placed_by;
