insert into public.products (
  id, slug, brand_id, name, category, category_id, price, description, accent,
  badge, affiliate_url, affiliate_network, image_url, rating, review_count,
  size, how_to_use, good_for, smells_like, finish, features, is_published, placed_by
) values
  (
    'b0000000-0000-0000-0000-000000000021',
    $mj$cosmic-cream$mj$,
    (select id from public.brands where slug = 'moon-juice'),
    $mj$Cosmic Cream$mj$,
    'skincare',
    (select id from public.categories where slug = 'skincare'),
    40.6,
    $mj$Moisturize + replenish$mj$,
    $mj$#5E4B45$mj$,
    $mj$Popular$mj$,
    $mj$https://moonjuice.com/products/cosmic-cream$mj$,
    'direct',
    $mj$https://moonjuice.com/cdn/shop/products/Cosmic_Cream_New_800x800_2d7fc7cb-584d-4bee-b1ba-20cd19f3e92f.png?v=1762198193&width=800$mj$,
    4.8,
    398,
    $mj$$mj$,
    $mj$AM + PM. Swipe onto face/neck after applying or other serums. Leaves a dewy finish.$mj$,
    $mj$Shown to help:; Seal in moisture.; Improve skin's natural elasticity and firmness.$mj$,
    $mj$$mj$,
    $mj$$mj$,
    array[$f$100% Traceable$f$, $f$Clinically Proven Potency$f$, $f$3rd Party Tested$f$, $f$Vegan$f$, $f$No Fillers or Junk$f$, $f$Bioavailable$f$]::text[],
    true,
    $mj$catoegy$mj$
  )
on conflict (slug) do update set
  brand_id = excluded.brand_id,
  name = excluded.name,
  category = excluded.category,
  category_id = excluded.category_id,
  price = excluded.price,
  description = excluded.description,
  accent = excluded.accent,
  badge = excluded.badge,
  affiliate_url = excluded.affiliate_url,
  affiliate_network = excluded.affiliate_network,
  image_url = excluded.image_url,
  rating = excluded.rating,
  review_count = excluded.review_count,
  size = excluded.size,
  how_to_use = excluded.how_to_use,
  good_for = excluded.good_for,
  features = excluded.features,
  is_published = excluded.is_published,
  placed_by = excluded.placed_by;
