insert into public.products (
  id, slug, brand_id, name, category, category_id, price, description, accent,
  badge, affiliate_url, affiliate_network, image_url, rating, review_count,
  size, how_to_use, good_for, smells_like, finish, features, is_published, placed_by
) values
  (
    'b0000000-0000-0000-0000-000000000022',
    $mj$milk-cleanse$mj$,
    (select id from public.brands where slug = 'moon-juice'),
    $mj$Milk Cleanse$mj$,
    'skincare',
    (select id from public.categories where slug = 'skincare'),
    22.4,
    $mj$Cleanse, soothe + nourish$mj$,
    $mj$#5E4B45$mj$,
    $mj$Popular$mj$,
    $mj$https://moonjuice.com/products/milk-cleanse$mj$,
    'direct',
    $mj$https://moonjuice.com/cdn/shop/products/Milk_Cleanse_New_800x800_cc1149bb-cc99-4ac2-8678-021068b2016e.png?v=1762198193&width=800$mj$,
    4.9,
    359,
    $mj$$mj$,
    $mj$Massage onto wet skin and rinse. AM, follow with and . PM, follow with , , and . Tips + Safe as a double cleanser + Use as a vulva wash (it's pH balanced)$mj$,
    $mj$Shown to help:; match skin's pH and never strip; hydrate and nourish$mj$,
    $mj$$mj$,
    $mj$$mj$,
    array[$f$100% Traceable$f$, $f$Clinically Proven Potency$f$, $f$3rd Party Tested$f$, $f$Vegan$f$, $f$No Fillers or Junk$f$, $f$Bioavailable$f$]::text[],
    true,
    $mj$catoegy$mj$
  )
on conflict (slug) do update set
  brand_id = excluded.brand_id,
  name = excluded.name,
  category = excluded.category,
  category_id = excluded.category_id,
  price = excluded.price,
  description = excluded.description,
  accent = excluded.accent,
  badge = excluded.badge,
  affiliate_url = excluded.affiliate_url,
  affiliate_network = excluded.affiliate_network,
  image_url = excluded.image_url,
  rating = excluded.rating,
  review_count = excluded.review_count,
  size = excluded.size,
  how_to_use = excluded.how_to_use,
  good_for = excluded.good_for,
  features = excluded.features,
  is_published = excluded.is_published,
  placed_by = excluded.placed_by;
