insert into public.products (
  id, slug, brand_id, name, category, category_id, price, description, accent,
  badge, affiliate_url, affiliate_network, image_url, rating, review_count,
  size, how_to_use, good_for, smells_like, finish, features, is_published, placed_by
) values
  (
    'b0000000-0000-0000-0000-000000000024',
    $mj$pearl$mj$,
    (select id from public.brands where slug = 'moon-juice'),
    $mj$Pearl$mj$,
    'supplements',
    (select id from public.categories where slug = 'supplements'),
    37.8,
    $mj$Beauty gem for collagen hair + nails$mj$,
    $mj$#5E4B45$mj$,
    $mj$Popular$mj$,
    $mj$https://moonjuice.com/products/pearl$mj$,
    'direct',
    $mj$https://moonjuice.com/cdn/shop/products/Pearl_800x800_3431461e-5e0e-4bfe-b903-f39c29de3809.png?v=1762197964&width=800$mj$,
    4.8,
    564,
    $mj$30 servings$mj$,
    $mj$Pairs well with everything---smoothies, coffee, tea, tonics, milks, and baking. Add a pinch to your moisturizer or raw honey for a mask, or brush directly onto skin before bed. Use 1/2 tsp daily.$mj$,
    $mj$stimulate the body's natural collagen; even skin tone; strengthen hair, skin, and nails$mj$,
    $mj$$mj$,
    $mj$$mj$,
    array[$f$100% Traceable$f$, $f$Clinically Proven Potency$f$, $f$3rd Party Tested$f$, $f$Vegan$f$, $f$No Fillers or Junk$f$, $f$Bioavailable$f$]::text[],
    true,
    $mj$catoegy$mj$
  )
on conflict (slug) do update set
  brand_id = excluded.brand_id,
  name = excluded.name,
  category = excluded.category,
  category_id = excluded.category_id,
  price = excluded.price,
  description = excluded.description,
  accent = excluded.accent,
  badge = excluded.badge,
  affiliate_url = excluded.affiliate_url,
  affiliate_network = excluded.affiliate_network,
  image_url = excluded.image_url,
  rating = excluded.rating,
  review_count = excluded.review_count,
  size = excluded.size,
  how_to_use = excluded.how_to_use,
  good_for = excluded.good_for,
  features = excluded.features,
  is_published = excluded.is_published,
  placed_by = excluded.placed_by;
