insert into public.products (
  id, slug, brand_id, name, category, category_id, price, description, accent,
  badge, affiliate_url, affiliate_network, image_url, rating, review_count,
  size, how_to_use, good_for, smells_like, finish, features, is_published, placed_by
) values
  (
    'b0000000-0000-0000-0000-000000000009',
    $mj$brain-dust$mj$,
    (select id from public.brands where slug = 'moon-juice'),
    $mj$Brain Dust$mj$,
    'supplements',
    (select id from public.categories where slug = 'supplements'),
    26.6,
    $mj$Mental stamina, alertness + concentration$mj$,
    $mj$#5E4B45$mj$,
    $mj$Popular$mj$,
    $mj$https://moonjuice.com/products/brain-dust$mj$,
    'direct',
    $mj$https://moonjuice.com/cdn/shop/files/Brain_dust_ecom.png?v=1762198100&width=800$mj$,
    4.7,
    736,
    $mj$14 servings$mj$,
    $mj$Malty & bitter -- pairs well with tea, coffee, chocolate & milk; or add to any smoothie. Blend 1 tsp per serving.$mj$,
    $mj$Organic Lion's Mane:Known to be neuroprotective; Ginkgo:Supports speedy processing; Rhodiola:Promotes alertness and concentration$mj$,
    $mj$$mj$,
    $mj$$mj$,
    array[$f$100% Traceable$f$, $f$Clinically Proven Potency$f$, $f$3rd Party Tested$f$, $f$Vegan$f$, $f$No Fillers or Junk$f$, $f$Bioavailable$f$]::text[],
    true,
    $mj$catoegy$mj$
  )
on conflict (slug) do update set
  brand_id = excluded.brand_id,
  name = excluded.name,
  category = excluded.category,
  category_id = excluded.category_id,
  price = excluded.price,
  description = excluded.description,
  accent = excluded.accent,
  badge = excluded.badge,
  affiliate_url = excluded.affiliate_url,
  affiliate_network = excluded.affiliate_network,
  image_url = excluded.image_url,
  rating = excluded.rating,
  review_count = excluded.review_count,
  size = excluded.size,
  how_to_use = excluded.how_to_use,
  good_for = excluded.good_for,
  features = excluded.features,
  is_published = excluded.is_published,
  placed_by = excluded.placed_by;
