insert into public.products (
  id, slug, brand_id, name, category, category_id, price, description, accent,
  badge, affiliate_url, affiliate_network, image_url, rating, review_count,
  size, how_to_use, good_for, smells_like, finish, features, is_published, placed_by
) values
  (
    'b0000000-0000-0000-0000-000000000015',
    $mj$cellular-waters-sticks$mj$,
    (select id from public.brands where slug = 'moon-juice'),
    $mj$Cellular Waters Sticks$mj$,
    'electrolytes',
    (select id from public.categories where slug = 'electrolytes'),
    26.6,
    $mj$Ting, Mini Dew & Magnesi-Om for energy, hydration & sleep. 15 sticks.$mj$,
    $mj$#5E4B45$mj$,
    null,
    $mj$https://moonjuice.com/products/cellular-waters-sticks$mj$,
    'direct',
    $mj$https://moonjuice.com/cdn/shop/files/Cellular-Water-Sticks.png?v=1762198958&width=800$mj$,
    4.9,
    31,
    $mj$15 sticks$mj$,
    $mj$Ting 1 stick in water every day Mini Dew 1 stick in 12 oz water every day Magnesi-Om 1 stick in water every night$mj$,
    $mj$Ting:; * + Metabolismconverts fat, protein, and carbs into cellular currency; * + Energyenhances performance$mj$,
    $mj$$mj$,
    $mj$$mj$,
    array[$f$100% Traceable$f$, $f$Clinically Proven Potency$f$, $f$3rd Party Tested$f$, $f$Vegan$f$, $f$No Fillers or Junk$f$, $f$Bioavailable$f$]::text[],
    true,
    $mj$catoegy$mj$
  )
on conflict (slug) do update set
  brand_id = excluded.brand_id,
  name = excluded.name,
  category = excluded.category,
  category_id = excluded.category_id,
  price = excluded.price,
  description = excluded.description,
  accent = excluded.accent,
  badge = excluded.badge,
  affiliate_url = excluded.affiliate_url,
  affiliate_network = excluded.affiliate_network,
  image_url = excluded.image_url,
  rating = excluded.rating,
  review_count = excluded.review_count,
  size = excluded.size,
  how_to_use = excluded.how_to_use,
  good_for = excluded.good_for,
  features = excluded.features,
  is_published = excluded.is_published,
  placed_by = excluded.placed_by;
