insert into public.products (
  id, slug, brand_id, name, category, category_id, price, description, accent,
  badge, affiliate_url, affiliate_network, image_url, rating, review_count,
  size, how_to_use, good_for, smells_like, finish, features, is_published, placed_by
) values
  (
    'b0000000-0000-0000-0000-000000000025',
    $mj$cordyceps$mj$,
    (select id from public.brands where slug = 'moon-juice'),
    $mj$Cordyceps$mj$,
    'supplements',
    (select id from public.categories where slug = 'supplements'),
    43.2,
    $mj$Energy, stamina + lung capacity$mj$,
    $mj$#5E4B45$mj$,
    null,
    $mj$https://moonjuice.com/products/cordyceps$mj$,
    'direct',
    $mj$https://moonjuice.com/cdn/shop/products/Cordyceps_800x800_08ab29c6-1823-4d35-bc4f-f6e481feaf62.png?v=1762197958&width=800$mj$,
    4.9,
    179,
    $mj$36 servings$mj$,
    $mj$A golden powder with a slightly sweet anise-y, woody flavor. Pairs well with tropical fruits, citrus, ginger, chocolate, and coffee. Use between 1--3 tsp of this dietary supplement daily. Our Cordyceps mushroom extract is a key ingredient in Milk Chocolate Momentum. Find the recipe in$mj$,
    $mj$Traditionally used to help:; Sustain energy and stamina.; Encourage healthy lung capacity.$mj$,
    $mj$$mj$,
    $mj$$mj$,
    array[$f$100% Traceable$f$, $f$Clinically Proven Potency$f$, $f$3rd Party Tested$f$, $f$Vegan$f$, $f$No Fillers or Junk$f$, $f$Bioavailable$f$]::text[],
    true,
    $mj$catoegy$mj$
  )
on conflict (slug) do update set
  brand_id = excluded.brand_id,
  name = excluded.name,
  category = excluded.category,
  category_id = excluded.category_id,
  price = excluded.price,
  description = excluded.description,
  accent = excluded.accent,
  badge = excluded.badge,
  affiliate_url = excluded.affiliate_url,
  affiliate_network = excluded.affiliate_network,
  image_url = excluded.image_url,
  rating = excluded.rating,
  review_count = excluded.review_count,
  size = excluded.size,
  how_to_use = excluded.how_to_use,
  good_for = excluded.good_for,
  features = excluded.features,
  is_published = excluded.is_published,
  placed_by = excluded.placed_by;
