insert into public.products (
  id, slug, brand_id, name, category, category_id, price, description, accent,
  badge, affiliate_url, affiliate_network, image_url, rating, review_count,
  size, how_to_use, good_for, smells_like, finish, features, is_published, placed_by
) values
  (
    'b0000000-0000-0000-0000-000000000014',
    $mj$mini-dew$mj$,
    (select id from public.brands where slug = 'moon-juice'),
    $mj$Mini Dew$mj$,
    'electrolytes',
    (select id from public.categories where slug = 'electrolytes'),
    30.8,
    $mj$Hydration + mineralization$mj$,
    $mj$#5E4B45$mj$,
    $mj$Popular$mj$,
    $mj$https://moonjuice.com/products/mini-dew-electrolyte-powder-mix$mj$,
    'direct',
    $mj$https://moonjuice.com/cdn/shop/files/Mini_Dew_SFP_800x800_0fae2dde-03ee-45de-b9b5-9a0382b371d9.png?v=1762198818&width=800$mj$,
    4.6,
    442,
    $mj$30 servings$mj$,
    $mj$Mix 1 tsp of this electrolyte drink powder in 12oz of water every day. Also great for saunas, exercise, travel, or when you're feeling blah. Friendly for adults and kids 4+.$mj$,
    $mj$Hydration supports optimal hydration by maintaining water balance in and around cells; Brain enhances memory and cognitive performance, helps reduce brain fog and mental fatigue; Hormones can reduce P$mj$,
    $mj$$mj$,
    $mj$$mj$,
    array[$f$100% Traceable$f$, $f$Clinically Proven Potency$f$, $f$3rd Party Tested$f$, $f$Vegan$f$, $f$No Fillers or Junk$f$, $f$Bioavailable$f$]::text[],
    true,
    $mj$catoegy$mj$
  )
on conflict (slug) do update set
  brand_id = excluded.brand_id,
  name = excluded.name,
  category = excluded.category,
  category_id = excluded.category_id,
  price = excluded.price,
  description = excluded.description,
  accent = excluded.accent,
  badge = excluded.badge,
  affiliate_url = excluded.affiliate_url,
  affiliate_network = excluded.affiliate_network,
  image_url = excluded.image_url,
  rating = excluded.rating,
  review_count = excluded.review_count,
  size = excluded.size,
  how_to_use = excluded.how_to_use,
  good_for = excluded.good_for,
  features = excluded.features,
  is_published = excluded.is_published,
  placed_by = excluded.placed_by;
