insert into public.products (
  id, slug, brand_id, name, category, category_id, price, description, accent,
  badge, affiliate_url, affiliate_network, image_url, rating, review_count,
  size, how_to_use, good_for, smells_like, finish, features, is_published, placed_by
) values
  (
    'b0000000-0000-0000-0000-000000000001',
    $mj$neuro-magnesi-om$mj$,
    (select id from public.brands where slug = 'moon-juice'),
    $mj$Neuro Magnesi-Om$mj$,
    'supplements',
    (select id from public.categories where slug = 'supplements'),
    51.8,
    $mj$Cognitive speed + brain longevity$mj$,
    $mj$#5E4B45$mj$,
    null,
    $mj$https://moonjuice.com/products/neuro-magnesi-om$mj$,
    'direct',
    $mj$https://moonjuice.com/cdn/shop/files/Ecom-Neuro_Matcha_Mag.png?v=1779567262&width=800$mj$,
    4.7,
    35,
    $mj$30 servings$mj$,
    $mj$Blend 1 rounded tsp in 6oz hot or cold water or milk, up to 2x a day. Neuro Magnesi-Om contains caffeine; it's best taken in the morning---or at least not so late in the day that it'll affect your sleep.$mj$,
    $mj$Short-term memory + cognitive speed; Mental stamina + alertness; Neuroplasticity + synaptic density$mj$,
    $mj$$mj$,
    $mj$$mj$,
    array[$f$100% Traceable$f$, $f$Clinically Proven Potency$f$, $f$3rd Party Tested$f$, $f$Vegan$f$, $f$No Fillers or Junk$f$, $f$Bioavailable$f$]::text[],
    true,
    $mj$catoegy$mj$
  )
on conflict (slug) do update set
  brand_id = excluded.brand_id,
  name = excluded.name,
  category = excluded.category,
  category_id = excluded.category_id,
  price = excluded.price,
  description = excluded.description,
  accent = excluded.accent,
  badge = excluded.badge,
  affiliate_url = excluded.affiliate_url,
  affiliate_network = excluded.affiliate_network,
  image_url = excluded.image_url,
  rating = excluded.rating,
  review_count = excluded.review_count,
  size = excluded.size,
  how_to_use = excluded.how_to_use,
  good_for = excluded.good_for,
  features = excluded.features,
  is_published = excluded.is_published,
  placed_by = excluded.placed_by;
