insert into public.products (
  id, slug, brand_id, name, category, category_id, price, description, accent,
  badge, affiliate_url, affiliate_network, image_url, rating, review_count,
  size, how_to_use, good_for, smells_like, finish, features, is_published, placed_by
) values
  (
    'b0000000-0000-0000-0000-000000000026',
    $mj$reishi$mj$,
    (select id from public.brands where slug = 'moon-juice'),
    $mj$Reishi$mj$,
    'supplements',
    (select id from public.categories where slug = 'supplements'),
    33.6,
    $mj$Nootropic mushroom. Mood + concentration$mj$,
    $mj$#5E4B45$mj$,
    null,
    $mj$https://moonjuice.com/products/reishi$mj$,
    'direct',
    $mj$https://moonjuice.com/cdn/shop/files/Reishi_800x800_27ba2f24-b43a-4be7-bd5e-a280927ee0ee.png?v=1762197965&width=800$mj$,
    4.9,
    188,
    $mj$14 servings$mj$,
    $mj$A dark brown powder with a strong, botanical aroma and an intensely tannic taste with some bitterness. Pairs well with chocolate and coffee. Use between 1--4 tsp daily. Reishi is a key ingredient in Queen Healer Bread. Find the recipe in .$mj$,
    $mj$Traditionally used to help:; Balance mood and support concentration.; Crowned Queen Healer in TCM because of its ability to strengthen the heart and mind.$mj$,
    $mj$$mj$,
    $mj$$mj$,
    array[$f$100% Traceable$f$, $f$Clinically Proven Potency$f$, $f$3rd Party Tested$f$, $f$Vegan$f$, $f$No Fillers or Junk$f$, $f$Bioavailable$f$]::text[],
    true,
    $mj$catoegy$mj$
  )
on conflict (slug) do update set
  brand_id = excluded.brand_id,
  name = excluded.name,
  category = excluded.category,
  category_id = excluded.category_id,
  price = excluded.price,
  description = excluded.description,
  accent = excluded.accent,
  badge = excluded.badge,
  affiliate_url = excluded.affiliate_url,
  affiliate_network = excluded.affiliate_network,
  image_url = excluded.image_url,
  rating = excluded.rating,
  review_count = excluded.review_count,
  size = excluded.size,
  how_to_use = excluded.how_to_use,
  good_for = excluded.good_for,
  features = excluded.features,
  is_published = excluded.is_published,
  placed_by = excluded.placed_by;
