insert into public.products (
  id, slug, brand_id, name, category, category_id, price, description, accent,
  badge, affiliate_url, affiliate_network, image_url, rating, review_count,
  size, how_to_use, good_for, smells_like, finish, features, is_published, placed_by
) values
  (
    'b0000000-0000-0000-0000-000000000019',
    $mj$acid-potion$mj$,
    (select id from public.brands where slug = 'moon-juice'),
    $mj$Acid Potion$mj$,
    'skincare',
    (select id from public.categories where slug = 'skincare'),
    29.4,
    $mj$Quickie liquid facial. Exfoliate, unclog + soothe$mj$,
    $mj$#5E4B45$mj$,
    $mj$Popular$mj$,
    $mj$https://moonjuice.com/products/beauty-shroom-exfoliating-acid-potion$mj$,
    'direct',
    $mj$https://moonjuice.com/cdn/shop/products/Acid_Potion_New_800x800_ecfe112d-af61-458c-a2b6-1564d1282f9f.png?v=1762198144&width=800$mj$,
    4.8,
    867,
    $mj$$mj$,
    $mj$PM. Use 3 nights a week. Shake a quarter sized amount into palm and pat into clean face/neck with fingertips. Don't rinse! Follow with and . Tips + Ditch the cotton round, apply directly with palms + Use multiple nights in a row to penetrate stubborn pores + Target a specificskin concernorproblem area (doesn't have to be your full face)$mj$,
    $mj$Shown to help:; resurface skin and unclog pores; stimulate collagen production$mj$,
    $mj$$mj$,
    $mj$$mj$,
    array[$f$100% Traceable$f$, $f$Clinically Proven Potency$f$, $f$3rd Party Tested$f$, $f$Vegan$f$, $f$No Fillers or Junk$f$, $f$Bioavailable$f$]::text[],
    true,
    $mj$catoegy$mj$
  )
on conflict (slug) do update set
  brand_id = excluded.brand_id,
  name = excluded.name,
  category = excluded.category,
  category_id = excluded.category_id,
  price = excluded.price,
  description = excluded.description,
  accent = excluded.accent,
  badge = excluded.badge,
  affiliate_url = excluded.affiliate_url,
  affiliate_network = excluded.affiliate_network,
  image_url = excluded.image_url,
  rating = excluded.rating,
  review_count = excluded.review_count,
  size = excluded.size,
  how_to_use = excluded.how_to_use,
  good_for = excluded.good_for,
  features = excluded.features,
  is_published = excluded.is_published,
  placed_by = excluded.placed_by;
