insert into public.products (
  id, slug, brand_id, name, category, category_id, price, description, accent,
  badge, affiliate_url, affiliate_network, image_url, rating, review_count,
  size, how_to_use, good_for, smells_like, finish, features, is_published, placed_by
) values
  (
    'b0000000-0000-0000-0000-000000000008',
    $mj$sex-dust$mj$,
    (select id from public.brands where slug = 'moon-juice'),
    $mj$Sex Dust$mj$,
    'supplements',
    (select id from public.categories where slug = 'supplements'),
    26.6,
    $mj$Adaptogens for fire + creative energy$mj$,
    $mj$#5E4B45$mj$,
    $mj$Popular$mj$,
    $mj$https://moonjuice.com/products/sex-dust$mj$,
    'direct',
    $mj$https://moonjuice.com/cdn/shop/files/Sex_Dust_ecom.png?v=1762198103&width=800$mj$,
    4.5,
    904,
    $mj$14 servings$mj$,
    $mj$Using a milk frother or blender, mix 1 tsp of this natural libido supplement into coffee, black tea, hot water with a splash of milk, or cocoa. Commit daily for maximum benefits.$mj$,
    $mj$LIBIDO + HORMONAL BALANCE; Shown to help:; Shatavarisupports healthy hormonal balance and juiciness$mj$,
    $mj$$mj$,
    $mj$$mj$,
    array[$f$100% Traceable$f$, $f$Clinically Proven Potency$f$, $f$3rd Party Tested$f$, $f$Vegan$f$, $f$No Fillers or Junk$f$, $f$Bioavailable$f$]::text[],
    true,
    $mj$catoegy$mj$
  )
on conflict (slug) do update set
  brand_id = excluded.brand_id,
  name = excluded.name,
  category = excluded.category,
  category_id = excluded.category_id,
  price = excluded.price,
  description = excluded.description,
  accent = excluded.accent,
  badge = excluded.badge,
  affiliate_url = excluded.affiliate_url,
  affiliate_network = excluded.affiliate_network,
  image_url = excluded.image_url,
  rating = excluded.rating,
  review_count = excluded.review_count,
  size = excluded.size,
  how_to_use = excluded.how_to_use,
  good_for = excluded.good_for,
  features = excluded.features,
  is_published = excluded.is_published,
  placed_by = excluded.placed_by;
