insert into public.products (
  id, slug, brand_id, name, category, category_id, price, description, accent,
  badge, affiliate_url, affiliate_network, image_url, rating, review_count,
  size, how_to_use, good_for, smells_like, finish, features, is_published, placed_by
) values
  (
    'b0000000-0000-0000-0000-000000000005',
    $mj$superhair$mj$,
    (select id from public.brands where slug = 'moon-juice'),
    $mj$SuperHair$mj$,
    'supplements',
    (select id from public.categories where slug = 'supplements'),
    46.2,
    $mj$Healthier, stronger, thicker hair$mj$,
    $mj$#5E4B45$mj$,
    $mj$Best seller$mj$,
    $mj$https://moonjuice.com/products/superhair$mj$,
    'direct',
    $mj$https://moonjuice.com/cdn/shop/products/SuperHair_800x800_1e036d6d-c5a7-4bc3-ada4-58fb5e0c09bc.png?v=1762198161&width=800$mj$,
    4.7,
    2106,
    $mj$30 servings$mj$,
    $mj$Take 4 caps of SuperHair every morning, with or without food, for healthier, thicker, stronger hair.*$mj$,
    $mj$Helps balance stress hormones and reduce the effects of oxidative stress, which can contribute to hair loss; Help inhibit the hair-destructive hormone, DHT, to support healthy hair follicles and promo$mj$,
    $mj$$mj$,
    $mj$$mj$,
    array[$f$100% Traceable$f$, $f$Clinically Proven Potency$f$, $f$3rd Party Tested$f$, $f$Vegan$f$, $f$No Fillers or Junk$f$, $f$Bioavailable$f$]::text[],
    true,
    $mj$catoegy$mj$
  )
on conflict (slug) do update set
  brand_id = excluded.brand_id,
  name = excluded.name,
  category = excluded.category,
  category_id = excluded.category_id,
  price = excluded.price,
  description = excluded.description,
  accent = excluded.accent,
  badge = excluded.badge,
  affiliate_url = excluded.affiliate_url,
  affiliate_network = excluded.affiliate_network,
  image_url = excluded.image_url,
  rating = excluded.rating,
  review_count = excluded.review_count,
  size = excluded.size,
  how_to_use = excluded.how_to_use,
  good_for = excluded.good_for,
  features = excluded.features,
  is_published = excluded.is_published,
  placed_by = excluded.placed_by;
