insert into public.products (
  id, slug, brand_id, name, category, category_id, price, description, accent,
  badge, affiliate_url, affiliate_network, image_url, rating, review_count,
  size, how_to_use, good_for, smells_like, finish, features, is_published, placed_by
) values
  (
    'b0000000-0000-0000-0000-000000000020',
    $mj$acid-potion-travel-size$mj$,
    (select id from public.brands where slug = 'moon-juice'),
    $mj$Acid Potion Travel Size$mj$,
    'skincare',
    (select id from public.categories where slug = 'skincare'),
    18,
    $mj$Quickie liquid facial. Exfoliate, unclog & soothe.$mj$,
    $mj$#5E4B45$mj$,
    null,
    $mj$https://moonjuice.com/products/acid-potion-travel-size$mj$,
    'direct',
    $mj$https://moonjuice.com/cdn/shop/products/220801_MJ_Capture_22-08-01_046.png?v=1762198641&width=800$mj$,
    4.7,
    36,
    $mj$$mj$,
    $mj$PM. Use 3 nights a week. Shake a quarter sized amount into palm and pat into clean face/neck with fingertips. Don't rinse! Follow with and .$mj$,
    $mj$Helps:; * + resurface skin and unclog pores; * + stimulate collagen production$mj$,
    $mj$$mj$,
    $mj$$mj$,
    array[$f$100% Traceable$f$, $f$Clinically Proven Potency$f$, $f$3rd Party Tested$f$, $f$Vegan$f$, $f$No Fillers or Junk$f$, $f$Bioavailable$f$]::text[],
    true,
    $mj$catoegy$mj$
  )
on conflict (slug) do update set
  brand_id = excluded.brand_id,
  name = excluded.name,
  category = excluded.category,
  category_id = excluded.category_id,
  price = excluded.price,
  description = excluded.description,
  accent = excluded.accent,
  badge = excluded.badge,
  affiliate_url = excluded.affiliate_url,
  affiliate_network = excluded.affiliate_network,
  image_url = excluded.image_url,
  rating = excluded.rating,
  review_count = excluded.review_count,
  size = excluded.size,
  how_to_use = excluded.how_to_use,
  good_for = excluded.good_for,
  features = excluded.features,
  is_published = excluded.is_published,
  placed_by = excluded.placed_by;
