insert into public.products (
  id, slug, brand_id, name, category, category_id, price, description, accent,
  badge, affiliate_url, affiliate_network, image_url, rating, review_count,
  size, how_to_use, good_for, smells_like, finish, features, is_published, placed_by
) values
  (
    'b0000000-0000-0000-0000-000000000004',
    $mj$superyou$mj$,
    (select id from public.brands where slug = 'moon-juice'),
    $mj$SuperYou$mj$,
    'supplements',
    (select id from public.categories where slug = 'supplements'),
    37.8,
    $mj$Daily cortisol management. Energy, mood + focus$mj$,
    $mj$#5E4B45$mj$,
    $mj$Best seller$mj$,
    $mj$https://moonjuice.com/products/superyou$mj$,
    'direct',
    $mj$https://moonjuice.com/cdn/shop/products/SuperYou_800x800_9fa65f73-f367-4e26-bf80-88b4ef9aff53.png?v=1762198134&width=800$mj$,
    4.8,
    3220,
    $mj$30 servings$mj$,
    $mj$Take 2 caps every morning, with or without food.$mj$,
    $mj$reduce physical, mental and emotional fatigue; reduce cortisol by 24%; boost energy and mood$mj$,
    $mj$$mj$,
    $mj$$mj$,
    array[$f$100% Traceable$f$, $f$Clinically Proven Potency$f$, $f$3rd Party Tested$f$, $f$Vegan$f$, $f$No Fillers or Junk$f$, $f$Bioavailable$f$]::text[],
    true,
    $mj$catoegy$mj$
  )
on conflict (slug) do update set
  brand_id = excluded.brand_id,
  name = excluded.name,
  category = excluded.category,
  category_id = excluded.category_id,
  price = excluded.price,
  description = excluded.description,
  accent = excluded.accent,
  badge = excluded.badge,
  affiliate_url = excluded.affiliate_url,
  affiliate_network = excluded.affiliate_network,
  image_url = excluded.image_url,
  rating = excluded.rating,
  review_count = excluded.review_count,
  size = excluded.size,
  how_to_use = excluded.how_to_use,
  good_for = excluded.good_for,
  features = excluded.features,
  is_published = excluded.is_published,
  placed_by = excluded.placed_by;
