insert into public.products (
  id, slug, brand_id, name, category, category_id, price, description, accent,
  badge, affiliate_url, affiliate_network, image_url, rating, review_count,
  size, how_to_use, good_for, smells_like, finish, features, is_published, placed_by
) values
  (
    'b0000000-0000-0000-0000-000000000027',
    $mj$chaga$mj$,
    (select id from public.brands where slug = 'moon-juice'),
    $mj$Chaga$mj$,
    'supplements',
    (select id from public.categories where slug = 'supplements'),
    33.6,
    $mj$Protective mushroom. Energy + immunity$mj$,
    $mj$#5E4B45$mj$,
    null,
    $mj$https://moonjuice.com/products/chaga$mj$,
    'direct',
    $mj$https://moonjuice.com/cdn/shop/products/Chaga_800x800_1b367417-2355-4347-8401-7cd972bed033.png?v=1762197955&width=800$mj$,
    4.9,
    155,
    $mj$13 servings$mj$,
    $mj$This organic Chaga supplement is a dark, brown powder with a very mild and palatable earthy flavor, perfect for pairing with smoothies, lattes, coffee, andherbal tea. Use 1 tsp daily.$mj$,
    $mj$Support healthy immune system.; Balance energy.; Reduce fatigue.$mj$,
    $mj$$mj$,
    $mj$$mj$,
    array[$f$100% Traceable$f$, $f$Clinically Proven Potency$f$, $f$3rd Party Tested$f$, $f$Vegan$f$, $f$No Fillers or Junk$f$, $f$Bioavailable$f$]::text[],
    true,
    $mj$catoegy$mj$
  )
on conflict (slug) do update set
  brand_id = excluded.brand_id,
  name = excluded.name,
  category = excluded.category,
  category_id = excluded.category_id,
  price = excluded.price,
  description = excluded.description,
  accent = excluded.accent,
  badge = excluded.badge,
  affiliate_url = excluded.affiliate_url,
  affiliate_network = excluded.affiliate_network,
  image_url = excluded.image_url,
  rating = excluded.rating,
  review_count = excluded.review_count,
  size = excluded.size,
  how_to_use = excluded.how_to_use,
  good_for = excluded.good_for,
  features = excluded.features,
  is_published = excluded.is_published,
  placed_by = excluded.placed_by;
