insert into public.products (
  id, slug, brand_id, name, category, category_id, price, description, accent,
  badge, affiliate_url, affiliate_network, image_url, rating, review_count,
  size, how_to_use, good_for, smells_like, finish, features, is_published, placed_by
) values
  (
    'b0000000-0000-0000-0000-000000000017',
    $mj$collagen-protect$mj$,
    (select id from public.brands where slug = 'moon-juice'),
    $mj$Collagen Protect$mj$,
    'supplements',
    (select id from public.categories where slug = 'supplements'),
    40.6,
    $mj$Minimize fine lines + deep skin hydration$mj$,
    $mj$#5E4B45$mj$,
    $mj$Popular$mj$,
    $mj$https://moonjuice.com/products/beauty-shroom-vegan-collagen-protection$mj$,
    'direct',
    $mj$https://moonjuice.com/cdn/shop/products/Collagen_Protect_Bag_800x800_1.png?v=1766547630&width=800$mj$,
    4.7,
    928,
    $mj$30 servings$mj$,
    $mj$Collagen Protect is a vegan collagen supplement. Add 1 rounded tbsp of this skin-protecting creamer to coffee or smoothies to promote healthy skin. Our plant-based collagen powder is a collagen builder that contains no additives, so it may clump. Blend for maximum yum.$mj$,
    $mj$preserve your natural collagen production; hydrate skin; improve skin elasticity$mj$,
    $mj$$mj$,
    $mj$$mj$,
    array[$f$100% Traceable$f$, $f$Clinically Proven Potency$f$, $f$3rd Party Tested$f$, $f$Vegan$f$, $f$No Fillers or Junk$f$, $f$Bioavailable$f$]::text[],
    true,
    $mj$catoegy$mj$
  )
on conflict (slug) do update set
  brand_id = excluded.brand_id,
  name = excluded.name,
  category = excluded.category,
  category_id = excluded.category_id,
  price = excluded.price,
  description = excluded.description,
  accent = excluded.accent,
  badge = excluded.badge,
  affiliate_url = excluded.affiliate_url,
  affiliate_network = excluded.affiliate_network,
  image_url = excluded.image_url,
  rating = excluded.rating,
  review_count = excluded.review_count,
  size = excluded.size,
  how_to_use = excluded.how_to_use,
  good_for = excluded.good_for,
  features = excluded.features,
  is_published = excluded.is_published,
  placed_by = excluded.placed_by;
