import type { Brand } from "./types";

/** Wave 101: small organic / toxic-free brands across marketplace categories (c1475+). */
export const catalogBrandsWave101: Brand[] = [
  {
    id: "c1475",
    slug: "smart-charlie-naturals",
    name: "Smart Charlie Naturals",
    tagline: "10% nano-hydroxyapatite toothpaste — fluoride-free, family-batch, four real flavors",
    story:
      "Family-founded oral care from Steph, a former SQF practitioner who got tired of long fluoride lists and built a 10% nano-hydroxyapatite toothpaste kids and adults can share. Peppermint, spearmint, orange cream, and mojito — plus small-batch soap, magnesium butter, and a beeswax night balm. Evidence-minded, short labels, made in small batches.",
    location: "United States",
    founded: 2023,
    categories: ["oral", "skincare"],
    accent: "#3D6B4A",
    rating: 4.7,
    reviewCount: 214,
    followerCount: 3800,
    websiteUrl: "https://smartcharlienaturals.com",
    logoUrl: "/brands/smart-charlie-naturals.svg",
  },
  {
    id: "c1476",
    slug: "warrior-salt",
    name: "Warrior Salt",
    tagline: "Stevia-free electrolytes — cane sugar, pink salt, and real lemon-lime or strawberry",
    story:
      "Kitchen-started hydration for people who want electrolytes without stevia, citric acid dumps, or mystery natural flavors. Citrus Victory and Strawberry Victory mix organic cane sugar with pink Himalayan salt, potassium, magnesium malate, and real fruit powders — formulated by athletes who wanted a clean bottle they could actually finish.",
    location: "United States",
    founded: 2023,
    categories: ["electrolytes"],
    accent: "#C45C26",
    rating: 4.8,
    reviewCount: 1020,
    followerCount: 6400,
    websiteUrl: "https://warriorsalt.com",
    logoUrl: "/brands/warrior-salt.svg",
  },
  {
    id: "c1477",
    slug: "natural-nutrients",
    name: "Natural Nutrients",
    tagline: "UK grass-fed whey isolate and concentrate — unflavoured through strawberry, plus Creapure",
    story:
      "Independent UK nutrition built around grass-fed whey isolate and concentrate you can actually read — unflavoured, chocolate, vanilla, strawberry — plus Creapure creatine, greens, and everyday capsules. No merch wall, no mystery blends, just pasture-raised protein and a short supplement shelf.",
    location: "United Kingdom",
    founded: 2018,
    categories: ["protein", "supplements"],
    accent: "#2F5C4A",
    rating: 4.7,
    reviewCount: 860,
    followerCount: 9200,
    websiteUrl: "https://naturalnutrients.co.uk",
    logoUrl: "/brands/natural-nutrients.png",
  },
  {
    id: "c1478",
    slug: "miyazaki-tallow",
    name: "Miyazaki Tallow",
    tagline: "Green-tea tallow mineral sunscreen, sweet yuzu balm, and lavender body butter",
    story:
      "Japanese-inspired ancestral skin — grass-fed tallow whipped with Kyoto green tea and non-nano zinc for everyday mineral sun, plus a vitamin-C yuzu balm and a lavender body butter. Short farm-to-face lists for people who want reef-safer zinc without a 40-ingredient bottle.",
    location: "United States",
    founded: 2023,
    categories: ["sunscreen", "skincare"],
    accent: "#6B8F4E",
    rating: 4.8,
    reviewCount: 96,
    followerCount: 2100,
    websiteUrl: "https://miyazakitallow.com",
    logoUrl: "/brands/miyazaki-tallow.svg",
  },
  {
    id: "c1479",
    slug: "toups-and-co",
    name: "Toups and Co",
    tagline: "Alabama grass-fed tallow deodorant, mineral sun, and regenerative skin + hair",
    story:
      "Fairhope, Alabama tallow care from a family that started with regenerative farms and a never-list — aluminum-free deodorant in five scents, extra-strength for long days, mineral sun stick and balm, whipped tallow, dry shampoo, and wash-day bars. No sets, no makeup wall: just the formulas that earn a spot on the sink.",
    location: "Fairhope, AL",
    founded: 2016,
    categories: ["deodorant", "sunscreen", "skincare", "hair"],
    accent: "#8B5A3C",
    rating: 4.8,
    reviewCount: 4120,
    followerCount: 28000,
    websiteUrl: "https://toupsandco.com",
    logoUrl: "/brands/toups-and-co.svg",
  },
  {
    id: "c1480",
    slug: "mama-shrooms",
    name: "Mama Shrooms",
    tagline: "Brighton fruiting-body tincture and day / night / teen mushroom rituals",
    story:
      "Brighton-born functional mushrooms from chef and founder Gemma Ogston — a dual-extracted Lion's Mane tincture from 100% fruiting bodies, plus Day, Night, and Teen blends built like food, not filler. No supper-club tickets, no family packs: just the bottles she wanted in her own kitchen.",
    location: "Brighton, United Kingdom",
    founded: 2024,
    categories: ["supplements"],
    accent: "#5A3D2B",
    rating: 4.8,
    reviewCount: 340,
    followerCount: 5600,
    websiteUrl: "https://mamashrooms.co.uk",
    logoUrl: "/brands/mama-shrooms.svg",
  }
];
