import type { Product } from "./types";
import catalogProductsJson from "../../data/catalog-products-raw.json";

/** Product catalogs for curated brands — generated by scripts/fetch-catalog-products.mjs */
export const catalogProducts = catalogProductsJson as Product[];
