import type { Brand } from "./types";

/** Wave 38: small organic / toxic-free brands across marketplace categories (c1019+). */
export const catalogBrandsWave38: Brand[] = [
  {
    id: "c1048",
    slug: "sugar-pine",
    name: "Sugar Pine Products",
    tagline: "Oregon-made grass-fed tallow balms plus a non-nano zinc sun shield — no merch hat wall",
    story: "A small Pacific Northwest tallow kitchen that whips locally sourced suet into everyday balms and a seven-ingredient non-nano zinc sun shield instead of a chemical-filter lotion aisle. Lip bundles stay as their own listings. Hats, hair merch, and empty tins stay in the merch locker.",
    location: "Oregon, United States",
    founded: 2023,
    categories: ["sunscreen","skincare"],
    accent: "#3D5A3A",
    rating: 4.7,
    reviewCount: 180,
    followerCount: 3200,
    websiteUrl: "https://sugarpineproducts.com",
    logoUrl: "/brands/sugar-pine.svg",
  },
  {
    id: "c1049",
    slug: "little-pasture",
    name: "Little Pasture",
    tagline: "Grass-fed tallow balms plus a reef-safe SPF 50 zinc sun cream — scent variants, no merch",
    story: "A tiny pasture-to-jar house that infuses 100% grass-fed tallow with blue tansy, sea kelp, and kukui, then folds jojoba-coated non-nano zinc into a water-resistant SPF 50 instead of a chemical-filter wall. Each infused balm stays as its own listing. No merch, no empty tins.",
    location: "United States",
    founded: 2024,
    categories: ["sunscreen","skincare"],
    accent: "#6B4F2A",
    rating: 4.6,
    reviewCount: 140,
    followerCount: 2600,
    websiteUrl: "https://thelittlepasture.com",
    logoUrl: "/brands/little-pasture.svg",
  },
  {
    id: "c1050",
    slug: "manna-tallow",
    name: "Manna Tallow",
    tagline: "Heirloom whipped tallow, peppermint lip sticks, and a carrot-seed zinc sun balm — no blush shop",
    story: "A small-batch tallow kitchen that dry-renders grass-fed suet into whipped balms, peppermint chap sticks, and a non-nano zinc sun cream with carrot seed oil instead of a makeup-and-fragrance wall. Lip scents stay as their own listings. Blush tints, starter kits stuffed with color cosmetics, and merch stay out.",
    location: "United States",
    founded: 2023,
    categories: ["sunscreen","skincare"],
    accent: "#8B5A2B",
    rating: 4.6,
    reviewCount: 210,
    followerCount: 3800,
    websiteUrl: "https://mannatallow.com",
    logoUrl: "/brands/manna-tallow.svg",
  },
  {
    id: "c1051",
    slug: "twice-oral",
    name: "Twice",
    tagline: "Nano-hydroxyapatite mint toothpaste plus gum-shield mouthwash — no whitening-gadget wall",
    story: "A dentist-developed oral house that folds 5% nano-hydroxyapatite into fluoride-free Happy Mint paste and a fluoride spearmint option instead of a peroxide-strip aisle. Gum Shield mouthwash and soft gum-friendly brushes stay. Stadium merch and electric-head shops stay out.",
    location: "United States",
    founded: 2017,
    categories: ["oral"],
    accent: "#1B4F72",
    rating: 4.6,
    reviewCount: 4200,
    followerCount: 38000,
    websiteUrl: "https://smiletwice.com",
    logoUrl: "/brands/twice-oral.svg",
  },
  {
    id: "c1052",
    slug: "high-end-hippie",
    name: "High End Hippie",
    tagline: "Okanagan-made wildcrafted shampoo and conditioner bars — scent variants, no travel-case shop",
    story: "A mother-founded BC workshop that wildcrafts salon-strength solid shampoo and conditioner bars from Okanagan botanicals instead of a sulfate-and-plastic-bottle wall. Each bar scent stays as its own listing. Travel cases, soap bags, and shower-storage kits stay in the accessory drawer.",
    location: "Okanagan Valley, British Columbia",
    founded: 2018,
    categories: ["hair"],
    accent: "#2C5F4E",
    rating: 4.7,
    reviewCount: 640,
    followerCount: 8900,
    websiteUrl: "https://highendhippie.ca",
    logoUrl: "/brands/high-end-hippie.svg",
  },
  {
    id: "c1053",
    slug: "margaret-river-made",
    name: "Margaret River Made",
    tagline: "Western Australia plastic-free shampoo bars, cocoa-clay deodorant, and face serums — no perfume aisle",
    story: "A Margaret River workshop that pours botanical shampoo and conditioner bars, a cocoa-and-clay pit deodorant, and sea-buckthorn face serum instead of a plastic-bottle-and-synthetic-fragrance wall. Bar scents stay as their own listings. Eau de parfum, limited perfume, and merch stay out.",
    location: "Margaret River, Western Australia",
    founded: 2016,
    categories: ["hair","deodorant","skincare"],
    accent: "#1F6B5A",
    rating: 4.8,
    reviewCount: 1049,
    followerCount: 14000,
    websiteUrl: "https://margaretrivermade.com.au",
    logoUrl: "/brands/margaret-river-made.svg",
  },
  {
    id: "c1054",
    slug: "durango-tallow",
    name: "Durango Tallow Company",
    tagline: "Colorado-made grass-fed tallow balms, drawing salves, and rosemary hair spritz — scent variants, no merch",
    story: "A Durango kitchen that renders grass-fed suet into restore balms, charcoal drawing salves, and a rosemary hydrosol hair spritz instead of a petroleum-and-fragrance wall. Bergamot-lavender and rose-ylang scents stay as their own listings. No merch, no empty tins.",
    location: "Durango, Colorado",
    founded: 2022,
    categories: ["skincare","hair"],
    accent: "#5C4033",
    rating: 4.7,
    reviewCount: 220,
    followerCount: 4100,
    websiteUrl: "https://durangotallowcompany.com",
    logoUrl: "/brands/durango-tallow.svg",
  },
  {
    id: "c1055",
    slug: "maui-mana",
    name: "Maui Mana Skincare",
    tagline: "Maui-made reef-safe mineral lotions, tinted sticks, and SPF lips — cacao tint, no chemical spray",
    story: "A small Maui workshop that blends non-nano mineral sunscreen, cacao-tinted face lotion, travel sticks, and peppermint SPF lips instead of an oxybenzone aisle. Lotion bars and after-sun stay. No merch totes, no chemical sprays.",
    location: "Maui, Hawaii",
    founded: 2021,
    categories: ["sunscreen","skincare"],
    accent: "#1B6B6B",
    rating: 4.6,
    reviewCount: 160,
    followerCount: 2800,
    websiteUrl: "https://mauimanaskincare.myshopify.com",
    logoUrl: "/brands/maui-mana.svg",
  },
  {
    id: "c1056",
    slug: "fat-cow-skin",
    name: "Fat Cow",
    tagline: "Britain-made grass-fed tallow face creams, balms, soaps, and a refill deodorant — no gua-sha tool shop",
    story: "A British tallow house that renders grass-fed suet into face cream, everyday balm, and charcoal cleanser soap instead of a 30-ingredient lotion wall. Each formula stays as its own listing. Gift cards, gua sha, and tool bundles stay out.",
    location: "United Kingdom",
    founded: 2022,
    categories: ["skincare","deodorant"],
    accent: "#6B3E26",
    rating: 4.6,
    reviewCount: 280,
    followerCount: 5200,
    websiteUrl: "https://fatcowskin.com",
    logoUrl: "/brands/fat-cow-skin.svg",
  },
  {
    id: "c1057",
    slug: "grin-natural",
    name: "Grin",
    tagline: "New Zealand hydroxyapatite toothpastes — enzyme whitening, microbiome, kids mint, no electric-brush shop",
    story: "A New Zealand oral kitchen that folds nano- and micro-hydroxyapatite plus postbiotics into enzyme-whitening, microbiome, travel, and kids pastes instead of a fluoride-and-SLS wall. Soft brushes stay. Silicone holders, toothbrush cases, and Seen-catalog duplicates stay out — this is the Grin house, not Seen Oral.",
    location: "New Zealand",
    founded: 2015,
    categories: ["oral"],
    accent: "#2E7D32",
    rating: 4.6,
    reviewCount: 890,
    followerCount: 12000,
    websiteUrl: "https://grinnatural.co.nz",
    logoUrl: "/brands/grin-natural.png",
  },
  {
    id: "c1058",
    slug: "sb-botanicals",
    name: "S&B Botanicals",
    tagline: "Washington-made aluminum-free deodorant, tallow soaps, and calendula serums — scent variants, no recipe ebook",
    story: "A Sunnyside, Washington herbal kitchen that pours baking-soda-free deodorant sticks, whipped tallow soaps, and calendula face oils instead of an aluminum-and-phthalate wall. Soap and deodorant scents stay as their own listings. Room sprays, gift cards, DIY recipe downloads, and supplier directories stay out.",
    location: "Sunnyside, Washington",
    founded: 2021,
    categories: ["deodorant","skincare"],
    accent: "#4A6741",
    rating: 4.7,
    reviewCount: 190,
    followerCount: 3400,
    websiteUrl: "https://sbbotanicalproducts.com",
    logoUrl: "/brands/sb-botanicals.svg",
  },
  {
    id: "c1059",
    slug: "simple-sunscreen",
    name: "Simple Sunscreen",
    tagline: "One-SKU USA mineral SPF 50 cream — no chemical filters, no merch",
    story: "A one-formula US mineral house that keeps a single SPF 50 zinc cream instead of a chemical-filter and fragrance wall. No merch, no self-tanner, no empty bottles.",
    location: "United States",
    founded: 2024,
    categories: ["sunscreen"],
    accent: "#C45C26",
    rating: 4.5,
    reviewCount: 40,
    followerCount: 700,
    websiteUrl: "https://simplesunscreen.com",
    logoUrl: "/brands/simple-sunscreen.svg",
  },
];
