import type { Brand } from "./types";

/** Wave 30: small organic / toxic-free brands across marketplace categories (c956+). */
export const catalogBrandsWave30: Brand[] = [
  {
    id: "c956",
    slug: "creamly",
    name: "CREAMLY",
    tagline: "12% hydroxyapatite toothpaste — no fluoride, no SLS, no glycerin filler paste",
    story: "A UK house that wrote a fluoride-free toothpaste around a high dose of hydroxyapatite, arginine, and Celtic salt instead of a glycerin-heavy natural paste. The toothpaste stays. The deodorant and Woe Balm stay. Consultations, PDF guides, and intimate lubricant stay out.",
    location: "United Kingdom",
    founded: 2022,
    categories: ["oral","deodorant","skincare"],
    accent: "#C4A07A",
    rating: 4.8,
    reviewCount: 210,
    followerCount: 3800,
    websiteUrl: "https://creamly.co.uk",
    logoUrl: "/brands/creamly.svg",
  },
  {
    id: "c957",
    slug: "nourish-organic",
    name: "Nourish Organic",
    tagline: "USDA organic lotions and serums — short plant lists, no synthetic fragrance dump",
    story: "A US organic skin line that keeps lotions, cleansers, and face oils to certified botanicals instead of a 40-ingredient cream aisle. Unscented, vanilla chamomile, and lavender mint lotion variants stay as their own listings. Eye treatments and serums stay. Merch stays out.",
    location: "United States",
    founded: 2003,
    categories: ["skincare"],
    accent: "#6B8F71",
    rating: 4.6,
    reviewCount: 420,
    followerCount: 8900,
    websiteUrl: "https://nourishorganic.com",
    logoUrl: "/brands/nourish-organic.png",
  },
  {
    id: "c958",
    slug: "farwell-lake-homestead",
    name: "Farwell Lake Homestead",
    tagline: "Homestead tallow deodorant and shampoo bars — aluminum-free, no perfume-oil stick",
    story: "A small US homestead kitchen that pours patchouli tallow deodorant and cuts shampoo and soap bars from rendered fat instead of a drugstore antiperspirant. Deodorant and soap scent variants stay as their own listings. Tallow balm stays. Sweatshirts, candles, elderberry kits, and foaming hand soap stay in the barn.",
    location: "United States",
    founded: 2021,
    categories: ["deodorant","hair","skincare"],
    accent: "#5C4033",
    rating: 4.7,
    reviewCount: 90,
    followerCount: 1400,
    websiteUrl: "https://farwelllakehomestead.com",
    logoUrl: "/brands/farwell-lake-homestead.svg",
  },
  {
    id: "c959",
    slug: "ancient-healings",
    name: "Ancient Health & Healings",
    tagline: "Halal grass-fed tallow deodorant — magnesium, no aluminum, no synthetic fragrance dump",
    story: "A US tallow kitchen that renders halal grass-fed fat, then pours aluminum-free deodorant with magnesium hydroxide and charcoal instead of a chemical antiperspirant. Deodorant scent variants stay as their own listings. Face and body balms stay. Bug spray, fire cider, wash tabs, and bone meal stay out.",
    location: "United States",
    founded: 2022,
    categories: ["deodorant","skincare"],
    accent: "#8B5A2B",
    rating: 4.8,
    reviewCount: 160,
    followerCount: 2700,
    websiteUrl: "https://www.ancienthealings.co",
    logoUrl: "/brands/ancient-healings.svg",
  },
  {
    id: "c960",
    slug: "qet-botanicals",
    name: "Qēt Botanicals",
    tagline: "Six-ingredient mineral sunscreen serum — non-nano zinc, no chemical-filter cocktail",
    story: "A botanical house that folds non-nano zinc into a six-ingredient serum boost instead of a 30-line chemical SPF. The mineral sunscreen stays. Camellia, plum, rosehip, and squalane serums stay. Hair and root oil stays. Perfume, gua sha stones, wooden brushes, and gift cards stay out.",
    location: "United States",
    founded: 2018,
    categories: ["sunscreen","skincare","hair"],
    accent: "#7A9E7E",
    rating: 4.7,
    reviewCount: 280,
    followerCount: 6200,
    websiteUrl: "https://qetbotanicals.com",
    logoUrl: "/brands/qet-botanicals.png",
  },
  {
    id: "c961",
    slug: "tru-nature-beauty",
    name: "Tru-Nature Beauty",
    tagline: "Hand-whipped grass-fed tallow and charcoal toothpaste — no fluoride, no filler cream",
    story: "A small tallow kitchen that whips grass-fed fat with mineral oils and pours a fluoride-free charcoal toothpaste instead of a drugstore paste. Whipped tallow scent variants stay as their own listings. Toothpaste stays. Tea, candles, vanilla extract, migraine rollers, bug spray, and wax wraps stay in the pantry.",
    location: "United States",
    founded: 2023,
    categories: ["skincare","oral"],
    accent: "#6B4F3A",
    rating: 4.6,
    reviewCount: 70,
    followerCount: 1100,
    websiteUrl: "https://tru-nature-beauty.myshopify.com",
    logoUrl: "/brands/tru-nature-beauty.svg",
  },
  {
    id: "c962",
    slug: "solis",
    name: "Solis",
    tagline: "Organic plant protein with probiotics and MCT — no gums, no artificial sweetener aisle",
    story: "A clean-label protein house that blends organic plant protein with coconut MCT, prebiotics, and 2 billion CFU probiotics instead of a chalky gum-thickened shake. Pouch, sachet, and routine sizes stay. Flavor is kept when the shop publishes it as its own listing. Shakers stay out.",
    location: "United States",
    founded: 2021,
    categories: ["protein"],
    accent: "#C4A35A",
    rating: 4.7,
    reviewCount: 150,
    followerCount: 2400,
    websiteUrl: "https://solislifestyle.com",
    logoUrl: "/brands/solis.svg",
  },
  {
    id: "c963",
    slug: "bush-tucker-blends",
    name: "Bush Tucker Blends",
    tagline: "Australian native plant protein and everyday electrolytes — bio-fermented, no bloat gum",
    story: "An Australian house that ferments pea and hemp protein with Kakadu botanicals and ocean magnesium, then bags an everyday electrolyte instead of a neon sport drink. Protein and electrolyte flavor variants stay as their own listings. Organ and magnesium capsules stay. Bottles, hand mixers, and drinkware stay out.",
    location: "Australia",
    founded: 2020,
    categories: ["protein","electrolytes","supplements"],
    accent: "#B86B3A",
    rating: 4.8,
    reviewCount: 190,
    followerCount: 3100,
    websiteUrl: "https://bushtuckerblends.com",
    logoUrl: "/brands/bush-tucker-blends.svg",
  },
  {
    id: "c964",
    slug: "forge-men",
    name: "Forge Men",
    tagline: "Mineral tallow sunscreen SPF 30 and organ complexes — non-nano zinc, no chemical filter",
    story: "A US ancestral kitchen that folds non-nano zinc into grass-fed tallow for an SPF 30 stick, then keeps organ complexes to a short label. The mineral sunscreen stays. Tallow balm and joint cream stay. Beef organ, liver, thyroid, and adrenal complexes stay. Free-gift merch stacks stay out.",
    location: "United States",
    founded: 2022,
    categories: ["sunscreen","skincare","supplements"],
    accent: "#3D4A3D",
    rating: 4.7,
    reviewCount: 220,
    followerCount: 4500,
    websiteUrl: "https://try-forge.com",
    logoUrl: "/brands/forge-men.svg",
  },
  {
    id: "c965",
    slug: "honey-and-tallow",
    name: "Honey & Tallow",
    tagline: "Tallow-and-honey balms and soap — short farm lists, no 40-ingredient cream",
    story: "A small kitchen that stirs rendered tallow with honey into balms, soaps, and masks instead of a silicone cream. Lavender and unscented balm variants stay as their own listings. Soap and face masks stay. Accessory packs that are only merch stay out.",
    location: "United States",
    founded: 2021,
    categories: ["skincare"],
    accent: "#C4A35A",
    rating: 4.6,
    reviewCount: 80,
    followerCount: 1600,
    websiteUrl: "https://honeyandtallow.com",
    logoUrl: "/brands/honey-and-tallow.svg",
  },
  {
    id: "c966",
    slug: "thrive-natural-care",
    name: "Thrive Natural Care",
    tagline: "Reef-safe BodyShield 50 — non-nano zinc, pine-rosin water resistance, no chemical filter",
    story: "A plant-extract sun house that builds BodyShield 50 and a daily mineral balm around non-nano zinc and pine rosin instead of oxybenzone. BodyShield, daily sunscreen, and the defense balm stay. Recovery serum, eye stick, and face wash stay. Holiday gift wrap stays when it is the same formulas.",
    location: "United States",
    founded: 2016,
    categories: ["sunscreen","skincare"],
    accent: "#2F6F5E",
    rating: 4.8,
    reviewCount: 640,
    followerCount: 12000,
    websiteUrl: "https://thrivecare.co",
    logoUrl: "/brands/thrive-natural-care.png",
  },
  {
    id: "c967",
    slug: "silver-falls",
    name: "Silver Falls Sustainability",
    tagline: "Oregon small-batch shampoo bars and magnesium deodorant — plastic-free, no sulfate strip",
    story: "A Silver Falls, Oregon kitchen that pours shampoo and conditioner bars and a magnesium deodorant instead of a plastic bottle aisle. Hair-bar and deodorant scent variants stay as their own listings. Serums, eye cream, and lip balm stay. Laundry strips, donation SKUs, and gift cards stay out.",
    location: "Oregon, United States",
    founded: 2019,
    categories: ["deodorant","hair","skincare"],
    accent: "#3D6B5A",
    rating: 4.7,
    reviewCount: 310,
    followerCount: 5400,
    websiteUrl: "https://sfsustainable.com",
    logoUrl: "/brands/silver-falls.svg",
  },
  {
    id: "c968",
    slug: "premium-tallow",
    name: "Premium Tallow",
    tagline: "Black Angus suet tallow and hydroxyapatite tooth powder — no fluoride, no filler jar",
    story: "A Canadian render house that specialty-renders Black Angus suet and bags an MCHA hydroxyapatite tooth powder instead of a fluoride paste. Single tallow balms and tooth-mineral powders stay. Six-pack wholesale cartons, empty refill kits, and pearl-powder pantry bags stay out.",
    location: "Canada",
    founded: 2020,
    categories: ["skincare","oral"],
    accent: "#8B6914",
    rating: 4.7,
    reviewCount: 130,
    followerCount: 2100,
    websiteUrl: "https://premiumtallow.ca",
    logoUrl: "/brands/premium-tallow.svg",
  },
  {
    id: "c969",
    slug: "the-primal",
    name: "The Primal",
    tagline: "Grass-fed tallow toothpaste and lotion — fluoride-free, SLS-free, no synthetic foam",
    story: "A US tallow house that writes a peppermint toothpaste from grass-fed fat, calcium carbonate, and matcha, then whips lotions and shampoo bars from the same render. Toothpaste, lotion scent variants, and the honey tallow shampoo bar stay. Loofahs and 12-pack wholesale balms stay out.",
    location: "United States",
    founded: 2021,
    categories: ["oral","hair","skincare"],
    accent: "#6B3E26",
    rating: 4.8,
    reviewCount: 240,
    followerCount: 3900,
    websiteUrl: "https://shop.theprimal.com",
    logoUrl: "/brands/the-primal.svg",
  },
];
