import type { Brand } from "./types";

/** Wave 69: small organic / toxic-free brands across marketplace categories (c1283+). */
export const catalogBrandsWave69: Brand[] = [
  {
    id: "c1283",
    slug: "bastet",
    name: "Bastét",
    tagline: "Montreal 10% nano-hydroxyapatite French mint toothpaste in an aluminum tube",
    story: "A new Canadian oral house that treats brushing as a four-minute ritual. The French Mint paste is 10% nano-hydroxyapatite with seaweed algin, xylitol, and a triple-mint stack — no fluoride, no SLS. One 90 g aluminum tube. Cart.js is CAD and converts at 0.73.",
    location: "Montreal, Canada",
    founded: 2026,
    categories: ["oral"],
    accent: "#1F3A3A",
    rating: 4.9,
    reviewCount: 22,
    followerCount: 800,
    websiteUrl: "https://bastetritual.com",
    logoUrl: "/brands/bastet.svg",
  },
  {
    id: "c1284",
    slug: "mindful-mrkt",
    name: "Mindful Mrkt",
    tagline: "Zero-sugar lemon-lime electrolytes with 1,000 mg Redmond Real Salt and no natural flavors",
    story: "A tiny clean-hydration house with one lemon-lime drink mix: 1,000 mg sodium from ancient Redmond Real Salt, potassium citrate, magnesium malate, coconut water, real lemon and lime, taurine, B12, monk fruit, and stevia. Serving count is size. Free kanna chocolate, fruit chews, and starter stacks stay boxed.",
    location: "United States",
    founded: 2024,
    categories: ["electrolytes"],
    accent: "#3A6A4A",
    rating: 4.6,
    reviewCount: 48,
    followerCount: 1100,
    websiteUrl: "https://mindfulmrkt.com",
    logoUrl: "/brands/mindful-mrkt.svg",
  },
  {
    id: "c1285",
    slug: "active-stacks",
    name: "Active Stacks",
    tagline: "Four-ingredient grass-fed beef protein isolate and collagen in chocolate and vanilla",
    story: "A small paleo protein house built on HydroBEEF isolate plus cocoa, glycine, and stevia — no whey, no gums, no artificial sweeteners. Vanilla and Chocolate already live on separate titles for the 2 lb protein and collagen tubs. Sample packets and honey rice-crisp bars stay boxed. Cart.js is USD.",
    location: "United States",
    founded: 2018,
    categories: ["protein","supplements"],
    accent: "#5A3A28",
    rating: 4.7,
    reviewCount: 186,
    followerCount: 3200,
    websiteUrl: "https://activestacks.com",
    logoUrl: "/brands/active-stacks.svg",
  },
  {
    id: "c1286",
    slug: "no-bull-tallow",
    name: "No Bull Tallow",
    tagline: "Ontario grass-fed tallow sun balm, whipped butters, and shampoo bars without the fillers",
    story: "A small Elora, Ontario kitchen that renders local grass-fed tallow into a 20% non-nano zinc Sun Balm, whipped body butters, soap and shampoo bars, and barrier creams. Butter Blend and soap Blend scents expand; jar ounces stay size. Bug spray, soap ends, bundles, leather balm, dishes, and gift cards stay boxed. Cart.js is CAD × 0.73.",
    location: "Elora, Ontario",
    founded: 2023,
    categories: ["sunscreen","skincare","hair"],
    accent: "#6A4A2A",
    rating: 4.8,
    reviewCount: 74,
    followerCount: 1600,
    websiteUrl: "https://nobulltallow.com",
    logoUrl: "/brands/no-bull-tallow.svg",
  },
  {
    id: "c1287",
    slug: "simply-pioneer",
    name: "Simply Pioneer",
    tagline: "Farmhouse tallow deodorant and goat-milk tallow soaps in named homestead scents",
    story: "A tiny homestead maker pouring aluminum-free tallow deodorant (Clean & Unscented, Lavender & Rosemary, Blue Tansy), named goat-milk tallow soap bars, and whipped tallow creams. Deodorant Scent expands; cream Style/Color scents expand and jar ounces stay size. Laundry powder and dish soap stay boxed.",
    location: "United States",
    founded: 2022,
    categories: ["deodorant","skincare"],
    accent: "#7A5A3A",
    rating: 4.7,
    reviewCount: 56,
    followerCount: 900,
    websiteUrl: "https://simplypioneer.com",
    logoUrl: "/brands/simply-pioneer.svg",
  },
  {
    id: "c1288",
    slug: "goat-milk-soaper",
    name: "Goat Milk Soaper",
    tagline: "Plastic-free goat-milk shampoo bars, conditioner bars, soaps, and lotions",
    story: "A small goat-milk soap kitchen that presses true syndet shampoo and conditioner bars plus goat-milk soaps, lotions, tallow creams, lip balms, and sugar scrubs. Shampoo and conditioner Scent expand (Almond Biscotti through Unscented). Gift packs, laundry soap, bath bombs, bubble scoops, shower steamers, classes, and merch pouches stay boxed.",
    location: "United States",
    founded: 2019,
    categories: ["hair","skincare"],
    accent: "#8A6A4A",
    rating: 4.8,
    reviewCount: 240,
    followerCount: 2800,
    websiteUrl: "https://goatmilksoaper.com",
    logoUrl: "/brands/goat-milk-soaper.svg",
  },
];
