import type { Brand } from "./types";

/** Wave 4: small organic / toxic-free brands across marketplace categories (c460+). */
export const catalogBrandsWave4: Brand[] = [
  {
    id: "c460",
    slug: "soleil-toujours",
    name: "Soleil Toujours",
    tagline: "Luxury mineral SPF with a skincare finish",
    story: "Clean, reef-conscious sun care that wears like a serum — mineral and hybrid SPF, after-sun, and glow without the chalky paste.",
    location: "United States",
    founded: 2013,
    categories: ["sunscreen","skincare"],
    accent: "#E8A54B",
    rating: 4.7,
    reviewCount: 2100,
    followerCount: 18000,
    websiteUrl: "https://soleiltoujours.com",
    logoUrl: "/brands/soleil-toujours.png",
  },
  {
    id: "c461",
    slug: "solara-suncare",
    name: "Solara Suncare",
    tagline: "Clean mineral sun care with a ritual feel",
    story: "Small-batch mineral SPF and after-sun built around botanicals — no oxybenzone, formulas that respect reefs and skin barriers.",
    location: "United States",
    founded: 2018,
    categories: ["sunscreen","skincare"],
    accent: "#1B4F72",
    rating: 4.6,
    reviewCount: 890,
    followerCount: 7200,
    websiteUrl: "https://solarasuncare.com",
    logoUrl: "/brands/solara-suncare.svg",
  },
  {
    id: "c462",
    slug: "swellies",
    name: "Swellies",
    tagline: "Five-ingredient mineral SPF, no white cast",
    story: "Colorado-made mineral sunscreen with a five-ingredient formula — non-nano zinc, no silicones, no fragrance, no chemical filters.",
    location: "Colorado",
    founded: 2023,
    categories: ["sunscreen"],
    accent: "#1A4A6B",
    rating: 4.8,
    reviewCount: 240,
    followerCount: 3100,
    websiteUrl: "https://www.swellies.com",
    logoUrl: "/brands/swellies.svg",
  },
  {
    id: "c463",
    slug: "island-butter",
    name: "Island Butter",
    tagline: "Reef-safe mineral butter for untamed days",
    story: "Tampa-made all-natural mineral sun butter — reef-safe, sweatproof, and built to nourish skin instead of coating it in synthetics.",
    location: "Tampa, FL",
    founded: 2022,
    categories: ["sunscreen"],
    accent: "#2A9D8F",
    rating: 4.7,
    reviewCount: 180,
    followerCount: 2400,
    websiteUrl: "https://www.islandbutter.co",
    logoUrl: "/brands/island-butter.svg",
  },
  {
    id: "c464",
    slug: "nuud",
    name: "Nuud",
    tagline: "Microbiome-friendly cream deodorant that lasts days",
    story: "Dutch natural deodorant cream in a tiny tube — prebiotic, aluminum-free, and designed to work with your skin instead of blasting it.",
    location: "Netherlands",
    founded: 2015,
    categories: ["deodorant"],
    accent: "#E07A5F",
    rating: 4.5,
    reviewCount: 6400,
    followerCount: 42000,
    websiteUrl: "https://nuudcare.com",
    logoUrl: "/brands/nuud.svg",
  },
  {
    id: "c465",
    slug: "crystal-deodorant",
    name: "Crystal",
    tagline: "Mineral salt deodorant without the junk",
    story: "Potassium-alum mineral deodorant — no aluminum chlorohydrate, no parabens, no scent circus. Just a stone that actually works.",
    location: "United States",
    founded: 1984,
    categories: ["deodorant"],
    accent: "#4A90A4",
    rating: 4.4,
    reviewCount: 3800,
    followerCount: 15000,
    websiteUrl: "https://thecrystal.com",
    logoUrl: "/brands/crystal-deodorant.png",
  },
  {
    id: "c466",
    slug: "fygg",
    name: "Fygg",
    tagline: "Hydroxyapatite toothpaste for the whole family",
    story: "Nano-hydroxyapatite oral care without the plastic-tube guilt trip — clean toothpaste that remineralizes instead of just foaming.",
    location: "United States",
    founded: 2021,
    categories: ["oral"],
    accent: "#7EB8A2",
    rating: 4.8,
    reviewCount: 920,
    followerCount: 8600,
    websiteUrl: "https://fygg.com",
    logoUrl: "/brands/fygg.svg",
  },
  {
    id: "c467",
    slug: "dr-tungs",
    name: "Dr. Tung's",
    tagline: "Oil pulling and clean oral care, the long way",
    story: "Holistic oral care from oil-pulling concentrates to tongue cleaners — simple, effective tools without the supermarket chemistry set.",
    location: "United States",
    founded: 1994,
    categories: ["oral"],
    accent: "#8B6914",
    rating: 4.6,
    reviewCount: 2700,
    followerCount: 12000,
    websiteUrl: "https://drtungs.com",
    logoUrl: "/brands/dr-tungs.png",
  },
  {
    id: "c468",
    slug: "sprout-living",
    name: "Sprout Living",
    tagline: "Organic plant protein with real-food ingredients",
    story: "Chicago-born organic protein and superfood powders — short labels, recognizable plants, no gums-and-junk smoothie dust.",
    location: "Chicago, IL",
    founded: 2010,
    categories: ["protein","supplements"],
    accent: "#3D8B6E",
    rating: 4.7,
    reviewCount: 4100,
    followerCount: 28000,
    websiteUrl: "https://sproutliving.com",
    logoUrl: "/brands/sprout-living.png",
  },
  {
    id: "c469",
    slug: "nuzest",
    name: "Nuzest",
    tagline: "European golden pea protein, clean and quiet",
    story: "Pea protein isolates with short ingredient lists — no dairy, no soy, no stevia drama. Just plant protein that mixes like it means it.",
    location: "New Zealand",
    founded: 2012,
    categories: ["protein","supplements"],
    accent: "#2E7D32",
    rating: 4.6,
    reviewCount: 3300,
    followerCount: 19000,
    websiteUrl: "https://nuzest-usa.com",
    logoUrl: "/brands/nuzest.png",
  },
  {
    id: "c470",
    slug: "kos",
    name: "KOS",
    tagline: "Organic plant protein that actually tastes like food",
    story: "Organic plant protein and superfood blends with flavor that doesn't taste like chalk — clean labels for daily shakes.",
    location: "United States",
    founded: 2017,
    categories: ["protein","supplements"],
    accent: "#C4783A",
    rating: 4.5,
    reviewCount: 8900,
    followerCount: 54000,
    websiteUrl: "https://kos.com",
    logoUrl: "/brands/kos.svg",
  },
  {
    id: "c471",
    slug: "cure",
    name: "CURE",
    tagline: "Plant-based electrolytes with coconut water",
    story: "Hydration from coconut water and pink salt — no artificial dyes, no mystery sweeteners, just electrolytes that taste like fruit.",
    location: "United States",
    founded: 2018,
    categories: ["electrolytes"],
    accent: "#E07A5F",
    rating: 4.6,
    reviewCount: 5200,
    followerCount: 36000,
    websiteUrl: "https://curehydration.com",
    logoUrl: "/brands/cure.svg",
  },
  {
    id: "c472",
    slug: "hydrant",
    name: "Hydrant",
    tagline: "Rapid hydration packets without the junk",
    story: "Electrolyte drink mixes with real sugar in the right dose — no artificial colors, built for travel days and actual thirst.",
    location: "United States",
    founded: 2016,
    categories: ["electrolytes"],
    accent: "#1B4F72",
    rating: 4.5,
    reviewCount: 2800,
    followerCount: 16000,
    websiteUrl: "https://drinkhydrant.com",
    logoUrl: "/brands/hydrant.svg",
  },
  {
    id: "c473",
    slug: "earth-harbor",
    name: "Earth Harbor",
    tagline: "Sea-powered clean skincare from a family lab",
    story: "Woman-owned, independently made botanicals and mineral SPF — sea algae, clean actives, and no outsourcing the formula.",
    location: "United States",
    founded: 2017,
    categories: ["skincare","sunscreen"],
    accent: "#2A9D8F",
    rating: 4.8,
    reviewCount: 3600,
    followerCount: 41000,
    websiteUrl: "https://earthharbor.com",
    logoUrl: "/brands/earth-harbor.svg",
  },
  {
    id: "c474",
    slug: "evolve-beauty",
    name: "Evolve Beauty",
    tagline: "Certified organic British skincare",
    story: "Hertfordshire-made organic skincare with COSMOS credentials — short, honest formulas and refill pouches that skip the greenwash.",
    location: "United Kingdom",
    founded: 2018,
    categories: ["skincare"],
    accent: "#5B7A3A",
    rating: 4.7,
    reviewCount: 2400,
    followerCount: 22000,
    websiteUrl: "https://evolvebeauty.co.uk",
    logoUrl: "/brands/evolve-beauty.png",
  },
  {
    id: "c475",
    slug: "mad-hippie",
    name: "Mad Hippie",
    tagline: "High-performance naturals without the toxins",
    story: "Vitamin C, retinol alternatives, and everyday serums with transparent INCI lists — clean actives, no paraben-phthalate fog.",
    location: "United States",
    founded: 2009,
    categories: ["skincare"],
    accent: "#7B4B94",
    rating: 4.6,
    reviewCount: 5100,
    followerCount: 29000,
    websiteUrl: "https://madhippie.com",
    logoUrl: "/brands/mad-hippie.png",
  },
  {
    id: "c476",
    slug: "honua",
    name: "Honua Hawaiian Skincare",
    tagline: "Hawaiian botanicals, small-batch skin rituals",
    story: "Oahu-made skincare rooted in native plants — kukui, noni, and clean oils for skin that wants island botanicals, not filler.",
    location: "Oahu, HI",
    founded: 2014,
    categories: ["skincare"],
    accent: "#2F6F5E",
    rating: 4.8,
    reviewCount: 760,
    followerCount: 9800,
    websiteUrl: "https://honuaskincare.com",
    logoUrl: "/brands/honua.svg",
  },
  {
    id: "c477",
    slug: "melanin-haircare",
    name: "Melanin Haircare",
    tagline: "Clean hair care built for textured hair",
    story: "Multi-use oils, twists, and wash-day formulas for afro-textured hair — no mineral oil, no petrolatum, just ingredients that earn their spot.",
    location: "United States",
    founded: 2018,
    categories: ["hair"],
    accent: "#6B3E26",
    rating: 4.8,
    reviewCount: 4300,
    followerCount: 120000,
    websiteUrl: "https://melaninhaircare.com",
    logoUrl: "/brands/melanin-haircare.svg",
  },
  {
    id: "c478",
    slug: "sun-potion",
    name: "Sun Potion",
    tagline: "Tonic herbs and adaptogens, the slow way",
    story: "Ceremonial-grade mushrooms, tonic herbs, and blends for people who treat supplements like a ritual — not a neon gummy aisle.",
    location: "California",
    founded: 2013,
    categories: ["supplements"],
    accent: "#C4A484",
    rating: 4.7,
    reviewCount: 1900,
    followerCount: 34000,
    websiteUrl: "https://sunpotion.com",
    logoUrl: "/brands/sun-potion.png",
  },
  {
    id: "c479",
    slug: "needed",
    name: "Needed",
    tagline: "Clinical-grade nutrition for pregnancy and beyond",
    story: "Women's health supplements with doses that match the research — prenatal, collagen, and daily support without the candy-store formula.",
    location: "United States",
    founded: 2017,
    categories: ["supplements"],
    accent: "#8B6F5C",
    rating: 4.7,
    reviewCount: 2800,
    followerCount: 27000,
    websiteUrl: "https://thisisneeded.com",
    logoUrl: "/brands/needed.svg",
  },
  {
    id: "c480",
    slug: "anima-mundi",
    name: "Anima Mundi",
    tagline: "Organic herbal apothecary for daily ritual",
    story: "Brooklyn herbalists making organic powders, tonics, and adaptogens — regenerative botanicals with labels you can actually read.",
    location: "Brooklyn, NY",
    founded: 2016,
    categories: ["supplements"],
    accent: "#6B3E26",
    rating: 4.8,
    reviewCount: 2200,
    followerCount: 89000,
    websiteUrl: "https://animamundiherbals.com",
    logoUrl: "/brands/anima-mundi.svg",
  },
];
