import type { Brand } from "./types";

/** Wave 63: small organic / toxic-free brands across marketplace categories (c1249+). */
export const catalogBrandsWave63: Brand[] = [
  {
    id: "c1249",
    slug: "klyyr",
    name: "Klyyr",
    tagline: "Utah 10% nano + micro hydroxyapatite toothpaste — SLS-free, dye-free, named mint",
    story: "A small Utah oral house that publishes the hydroxyapatite dose on the tube: 10% nano + micro, sixteen listed ingredients, no SLS and no dyes. One+ stays. Tube size is size, not a flavor tree. There is no merch aisle.",
    location: "Utah, United States",
    founded: 2024,
    categories: ["oral"],
    accent: "#1F4E5F",
    rating: 4.6,
    reviewCount: 86,
    followerCount: 1900,
    websiteUrl: "https://klyyr.com",
    logoUrl: "/brands/klyyr.svg",
  },
  {
    id: "c1250",
    slug: "baili-essentials",
    name: "Bai-li Essentials",
    tagline: "Tennessee magnesium deodorant in compostable tubes — aluminum-free, baking-soda-free",
    story: "Bailey's Tennessee shop pours a magnesium-hydroxide cream into a home-compostable cardboard tube so the plastic stick never comes home. Five deodorant scents expand, plus lavender/unscented lotion bars and peppermint/unscented lip. Gift cards and pulse-point perfume oils stay boxed. Full size vs travel is size, not a scent.",
    location: "Tennessee, United States",
    founded: 2019,
    categories: ["deodorant","skincare"],
    accent: "#6B7F4A",
    rating: 4.7,
    reviewCount: 64,
    followerCount: 1600,
    websiteUrl: "https://bailiessentials.com",
    logoUrl: "/brands/baili-essentials.svg",
  },
  {
    id: "c1251",
    slug: "without-compromise",
    name: "Without Compromise",
    tagline: "Canadian tallow moisturizers, lion's mane shampoo bar, and mineral sun tallow",
    story: "A Canadian bath-and-beauty house that renders tallow with lion's mane, then pours individual moisturizers, a Grow-Th shampoo bar, scalp serum, and a mineral sun tallow. Individual balms, named lip balms, the 3-in-1 bar, mocha scrub, and sun tallow stay. Gift certificates, beauty bundles, tinted makeup, cheek tints, sample pots, and ritual protocols stay boxed. CAD prices convert to USD. Jar size is not a flavor.",
    location: "Canada",
    founded: 2021,
    categories: ["skincare","hair","sunscreen"],
    accent: "#4A5E3A",
    rating: 4.7,
    reviewCount: 112,
    followerCount: 2400,
    websiteUrl: "https://withoutcompromise.ca",
    logoUrl: "/brands/without-compromise.svg",
  },
  {
    id: "c1252",
    slug: "i-lyte-you",
    name: "I Lyte You",
    tagline: "Zero-sugar hydration sticks — lemon lime, orange zest, and green apple",
    story: "A one-SKU hydration house packing zero-sugar electrolyte and vitamin sticks into a 9-count sleeve. Lemon lime, orange zest, and green apple expand. Pack count is size, not a second flavor tree. INR prices convert to USD. There is no merch aisle.",
    location: "India",
    founded: 2023,
    categories: ["electrolytes"],
    accent: "#2A6F8F",
    rating: 4.4,
    reviewCount: 38,
    followerCount: 900,
    websiteUrl: "https://ilyteyou.com",
    logoUrl: "/brands/i-lyte-you.svg",
  },
  {
    id: "c1253",
    slug: "fruiting-bodies",
    name: "Fruiting Bodies",
    tagline: "US-grown fruiting-body dual extracts — lion's mane, reishi, cordyceps, chaga, turkey tail",
    story: "A small US extract shop that dual-extracts organic fruiting bodies with cane alcohol and water, then ultrasonically opens the chitin. Dedicated lion's mane, reishi, cordyceps, chaga, turkey tail, and Synergy tinctures stay, plus individual gummies. Art prints, chocolate bars, gummy trios, flower-essence drops, books, and gift cards stay boxed. There is no flavor-option tree.",
    location: "United States",
    founded: 2022,
    categories: ["supplements"],
    accent: "#5B3A1F",
    rating: 4.6,
    reviewCount: 74,
    followerCount: 2100,
    websiteUrl: "https://fruitingbodies.co",
    logoUrl: "/brands/fruiting-bodies.svg",
  },
];
