import type { Brand } from "./types";

/** Wave 103: small organic / toxic-free brands across marketplace categories (c1487+). */
export const catalogBrandsWave103: Brand[] = [
  {
    id: "c1487",
    slug: "jack-n-jill",
    name: "Jack N' Jill",
    tagline: "Melbourne kids' oral care — COSMOS-certified fruit toothpaste, corn-starch brushes, xylitol gel",
    story:
      "Melbourne couple Rachel and Justin Bernhaut were photographing in New York when their first tooth sent them hunting for a paste that was safe to swallow and didn't taste like medicine. Justin's pharmacist father still owned the vintage Jack N' Jill name — an Aussie pharmacy staple since 1949 — plus the mid-century machines. They rebuilt the formula themselves and relaunched in 2011: COSMOS-certified fruit gels from strawberry and watermelon to flavor-free, corn-starch bio brushes, Fairy Floss, and a chamomile teething gel. No sonic gadgets, no tooth-fairy merch: the tubes and brushes that actually live by the sink.",
    location: "Melbourne, Australia",
    founded: 2011,
    categories: ["oral", "skincare", "hair"],
    accent: "#E85D75",
    rating: 4.7,
    reviewCount: 2840,
    followerCount: 18600,
    websiteUrl: "https://www.jackandjillkids.com",
    logoUrl: "/brands/jack-n-jill.png",
  },
  {
    id: "c1488",
    slug: "natrilyte",
    name: "Natrilyte",
    tagline: "Canadian zero-sugar electrolytes — 1000 mg sodium, three real flavors, no medicine aftertaste",
    story:
      "A Canadian training pair got tired of the electrolyte aisle — sugar bombs, underdosed sticks, and marketing that had nothing to do with a hard session. Natrilyte is the tub they wanted: 1000 mg sodium, 400 mg potassium, 60 mg magnesium, zero sugar, and three flavors that don't taste like a clinic. Lemon lime, strawberry lemonade, and pineapple. Made in Canada by people who actually train. No variety packs, no shaker merch: one scoop, 16 ounces, done.",
    location: "Canada",
    founded: 2025,
    categories: ["electrolytes"],
    accent: "#1B6B5A",
    rating: 4.6,
    reviewCount: 86,
    followerCount: 1400,
    websiteUrl: "https://natrilyte.com",
    logoUrl: "/brands/natrilyte.svg",
  },
  {
    id: "c1489",
    slug: "smash-melon",
    name: "Smash Melon",
    tagline: "One-ingredient watermelon-seed protein — cold-pressed, neutral, no gums or flavors",
    story:
      "Delaware founder Ben Wadden got tired of fifteen-ingredient tubs pretending to be food. Smash Melon is cold-pressed watermelon seed — dehulled, cleaned in a family-owned allergen-free US plant, and left alone. One scoop, 22 g complete plant protein, no sweeteners, no 'natural flavors,' no gums. Stir it into the oatmeal or soup you already eat. No sample four-packs, no shakers: just the pouch.",
    location: "Delaware",
    founded: 2023,
    categories: ["protein"],
    accent: "#2F8F6B",
    rating: 4.8,
    reviewCount: 64,
    followerCount: 2100,
    websiteUrl: "https://www.smashmelon.com",
    logoUrl: "/brands/smash-melon.svg",
  },
  {
    id: "c1490",
    slug: "we-are-feel-good-inc",
    name: "We Are Feel Good Inc.",
    tagline: "Dunsborough surf-trip SPF 50+ — mineral zinc sticks, sensitive lotion, Kakadu and coconut",
    story:
      "Six outdoor friends — including a skin-cancer doctor and a pro surfer — sketched a sunscreen they could actually feel good about around a campfire on a family surf trip. We Are Feel Good Inc. launched from Dunsborough, Western Australia: SPF 50+ lotions for sport, sensitive skin, kids, and bubs, tinted mineral zinc sticks, Kakadu plum and coconut, plus SPF lip balms. Australian-made, reef-minded filters, no dry bags or holiday bundles. The bottles you throw in a beach bag.",
    location: "Dunsborough, Western Australia",
    founded: 2015,
    categories: ["sunscreen", "skincare"],
    accent: "#F4A261",
    rating: 4.8,
    reviewCount: 3120,
    followerCount: 42800,
    websiteUrl: "https://wearefeelgoodinc.com.au",
    logoUrl: "/brands/we-are-feel-good-inc.svg",
  },
  {
    id: "c1491",
    slug: "mooses-tallow",
    name: "Moose's Tallow",
    tagline: "Lebanon, PA kitchen tallow — aluminum-free deodorant, zinc sun balm, whipped butters, three-ingredient lips",
    story:
      "A health scare sent Brian (Moose) Smith into the kitchen in Lebanon, Pennsylvania, rendering small-batch beef tallow his wife and daughters would actually wear. Aluminum-free deodorant with magnesium and zinc ricinoleate in lavender, sandalwood, forest, coconut, and unscented. Non-nano zinc sun balms at 10, 20, and 30%. Whipped body butters in real food scents, three-ingredient lip balms (tallow, egg-yolk oil, beeswax), beard balms, and hair clay. No bug spray, no dog balm: the jars that live on the dresser.",
    location: "Lebanon, PA",
    founded: 2023,
    categories: ["deodorant", "sunscreen", "skincare", "hair"],
    accent: "#6B4A32",
    rating: 4.7,
    reviewCount: 890,
    followerCount: 7400,
    websiteUrl: "https://moosestallow.com",
    logoUrl: "/brands/mooses-tallow.svg",
  },
  {
    id: "c1492",
    slug: "forest-of-dean-mushrooms",
    name: "Forest of Dean Mushrooms",
    tagline: "Forest of Dean fruiting-body tinctures — Lion's Mane and reishi, grown on the farm, no spawn kits",
    story:
      "A family agro-ecological farm in England's Forest of Dean grows Lion's Mane and reishi from agar plate to fruiting body — no imported blocks, no grain-spawn side hustle on this shelf. Dual-extracted 1:3 tinctures in organic grain alcohol and distilled water, bottled in small runs on the same land. Shiitake logs and culinary dried oysters stay at the farm gate. Two bottles: the mushrooms they actually grew.",
    location: "Forest of Dean, UK",
    founded: 2021,
    categories: ["supplements"],
    accent: "#3D5A3A",
    rating: 4.7,
    reviewCount: 48,
    followerCount: 920,
    websiteUrl: "https://www.forestofdeanmushrooms.com",
    logoUrl: "/brands/forest-of-dean-mushrooms.svg",
  },
];
