import type { Brand } from "./types";

/** Wave 11: small organic / toxic-free brands across marketplace categories (c601+). */
export const catalogBrandsWave10: Brand[] = [
  {
    id: "c601",
    slug: "manda",
    name: "MANDA",
    tagline: "Organic coconut sun paste handmade in the Columbia River Gorge",
    story: "A tiny Gorge kitchen making food-grade sun paste from organic coconut, fair-trade botanicals, and regenerative tallow — water-and-sweat resistant for hours, no chemical filters, and a formula that reads like a pantry instead of a lab.",
    location: "Columbia River Gorge, OR",
    founded: 2014,
    categories: ["sunscreen","skincare"],
    accent: "#C45C26",
    rating: 4.8,
    reviewCount: 420,
    followerCount: 8900,
    websiteUrl: "https://mandanaturals.com",
    logoUrl: "/brands/manda.svg",
  },
  {
    id: "c602",
    slug: "suntegrity",
    name: "Suntegrity",
    tagline: "Certified organic mineral SPF that actually feels like skincare",
    story: "A long-running clean-sun house built around non-nano zinc and certified organic botanicals — unscented body SPF, tinted face formulas, and lip balm that skip oxybenzone, octinoxate, and the usual chemical-filter cocktail.",
    location: "United States",
    founded: 2010,
    categories: ["sunscreen","skincare"],
    accent: "#E8A317",
    rating: 4.7,
    reviewCount: 2100,
    followerCount: 34000,
    websiteUrl: "https://suntegrity.myshopify.com",
    logoUrl: "/brands/suntegrity.svg",
  },
  {
    id: "c603",
    slug: "kokua",
    name: "Kōkua Sun Care",
    tagline: "Hawaiian non-nano zinc in sugarcane tubes — no eye sting, no reef toxins",
    story: "Reef-safe Hawaiian zinc that rubs in like a moisturizer: 25% non-nano zinc in the SPF 50, Hawaiian antioxidants, vegan formulas, and carbon-negative bio-resin tubes. Built for sweat, swells, and kids who hate the sting.",
    location: "Hawaii",
    founded: 2018,
    categories: ["sunscreen"],
    accent: "#1B6B5A",
    rating: 4.7,
    reviewCount: 680,
    followerCount: 12000,
    websiteUrl: "https://www.kokuasuncare.com",
    logoUrl: "/brands/kokua.svg",
  },
  {
    id: "c604",
    slug: "goodonya",
    name: "GOODONYA",
    tagline: "USDA Organic hydration with six ingredients and a lemonade-stand taste",
    story: "Born in an Encinitas organic café, GOODONYA Hydrate is lemon juice, coconut water, sea magnesium, Himalayan salt, stevia leaf, and vitamin C — certified organic, glyphosate-free, and 1g of sugar. No “natural flavors,” no neon dyes.",
    location: "Encinitas, CA",
    founded: 2001,
    categories: ["electrolytes","supplements"],
    accent: "#3D7A4A",
    rating: 4.8,
    reviewCount: 940,
    followerCount: 18000,
    websiteUrl: "https://goodonyaorganic.com",
    logoUrl: "/brands/goodonya.png",
  },
  {
    id: "c605",
    slug: "junp",
    name: "Junp Hydration",
    tagline: "Zero-sugar electrolyte sticks that skip the dye drawer",
    story: "A small hydration house making stick-pack electrolytes without added sugar or the usual artificial-color parade — lemonade and everyday mixes you can toss in a bag instead of another neon sports drink.",
    location: "United States",
    founded: 2021,
    categories: ["electrolytes"],
    accent: "#2A6F97",
    rating: 4.6,
    reviewCount: 720,
    followerCount: 14000,
    websiteUrl: "https://junphydration.com",
    logoUrl: "/brands/junp.svg",
  },
  {
    id: "c606",
    slug: "adapted",
    name: "Adapted Nutrition",
    tagline: "Clean daily hydration sticks without the locker-room additive stack",
    story: "A quiet electrolyte brand building quick-stick hydration around minerals instead of sugar bombs — daily and pro formulas for people who want to drink water that actually tastes like water, with electrolytes in it.",
    location: "United States",
    founded: 2022,
    categories: ["electrolytes"],
    accent: "#4A6741",
    rating: 4.6,
    reviewCount: 310,
    followerCount: 6200,
    websiteUrl: "https://adapted-nutrition.com",
    logoUrl: "/brands/adapted.svg",
  },
  {
    id: "c607",
    slug: "koia",
    name: "Koia",
    tagline: "Plant protein shakes that drink like a smoothie, not a chalk tub",
    story: "A plant-protein house known for ready-to-drink shakes with a short-ish label and flavors that lean dessert-without-the-junk — dairy-free protein you can grab cold instead of fighting a shaker bottle.",
    location: "United States",
    founded: 2014,
    categories: ["protein"],
    accent: "#C47A2C",
    rating: 4.5,
    reviewCount: 3800,
    followerCount: 72000,
    websiteUrl: "https://drinkkoia.com",
    logoUrl: "/brands/koia.png",
  },
  {
    id: "c608",
    slug: "suprey",
    name: "Suprey Life",
    tagline: "European plant protein and zero-sugar electrolytes, no extra theater",
    story: "A tiny European kitchen making Sweetpeace plant protein (with enzymes and fiber, no added sugar) and Hydust electrolytes — science-minded formulas with a short ingredient brief and none of the neon tub energy.",
    location: "Europe",
    founded: 2023,
    categories: ["protein","electrolytes"],
    accent: "#5B3A7A",
    rating: 4.7,
    reviewCount: 80,
    followerCount: 1400,
    websiteUrl: "https://shop.suprey.life",
    logoUrl: "/brands/suprey.svg",
  },
  {
    id: "c609",
    slug: "complement",
    name: "Complement",
    tagline: "One essential vegan multi and clean protein — no kitchen-sink megadose",
    story: "A plant-based supplement house that started by asking what vegans actually run low on. Complement Essential, bone support, and organic protein without a 47-ingredient mystery blend — third-party tested, short lists, no megadose theater.",
    location: "United States",
    founded: 2017,
    categories: ["supplements","protein"],
    accent: "#6B4F3A",
    rating: 4.7,
    reviewCount: 2600,
    followerCount: 41000,
    websiteUrl: "https://www.lovecomplement.com",
    logoUrl: "/brands/complement.svg",
  },
  {
    id: "c610",
    slug: "pure-mess",
    name: "Pure Mess",
    tagline: "West Wittering cream deodorant and skin care, poured without bicarb drama",
    story: "Handcrafted on the English coast: aluminum-free deodorant in compostable tubes, with a magnesium-and-kaolin sensitive formula for people who break out from baking soda. Vegan, plastic-free, and scented only with real essential oils.",
    location: "West Wittering, UK",
    founded: 2019,
    categories: ["deodorant","skincare"],
    accent: "#7A6A4F",
    rating: 4.8,
    reviewCount: 540,
    followerCount: 9800,
    websiteUrl: "https://www.puremessskincare.com",
    logoUrl: "/brands/pure-mess.svg",
  },
  {
    id: "c611",
    slug: "wild",
    name: "Wild",
    tagline: "Refillable UK deodorant and a solid mineral SPF that skips the plastic pump",
    story: "A refill-first British house known for aluminum-free deodorant cases you keep, plus a solid-block mineral sunscreen and probiotic cleanser. Plastic-light, travel-proof, and built for people who are tired of throwing away another empty stick.",
    location: "United Kingdom",
    founded: 2017,
    categories: ["deodorant","sunscreen","skincare"],
    accent: "#2C5F4E",
    rating: 4.6,
    reviewCount: 12400,
    followerCount: 180000,
    websiteUrl: "https://wearewild.myshopify.com",
    logoUrl: "/brands/wild.svg",
  },
  {
    id: "c612",
    slug: "barepaste",
    name: "BarePaste",
    tagline: "US-made nano-hydroxyapatite toothpaste without fluoride or SLS foam circus",
    story: "A tiny oral-care kitchen making one job well: fluoride-free nano-hydroxyapatite paste with a clean mint and none of the SLS, parabens, or dye stack. Lab-made n-Ha, bottled in the US, for people who want enamel support without the drugstore extras.",
    location: "United States",
    founded: 2023,
    categories: ["oral"],
    accent: "#4A7C8C",
    rating: 4.8,
    reviewCount: 90,
    followerCount: 1600,
    websiteUrl: "https://www.barepaste.com",
    logoUrl: "/brands/barepaste.svg",
  },
  {
    id: "c613",
    slug: "gutology",
    name: "Gutology",
    tagline: "99.9% natural hydroxyapatite toothpaste for the oral microbiome",
    story: "A UK oral-microbiome house that treats the mouth like the rest of the gut. SLS-free hydroxyapatite paste, charcoal floss, and a copper tongue cleaner — clean ingredients with receipts, not just a “free-from” sticker.",
    location: "United Kingdom",
    founded: 2018,
    categories: ["oral"],
    accent: "#3E5A3D",
    rating: 4.7,
    reviewCount: 860,
    followerCount: 22000,
    websiteUrl: "https://gutology.co",
    logoUrl: "/brands/gutology.svg",
  },
  {
    id: "c614",
    slug: "selfwise",
    name: "Selfwise",
    tagline: "Nano-hydroxyapatite mouthwash and tsubaki hair masks, short lists only",
    story: "A small US house pairing science-y oral care (xylitol + n-Ha mouthwash, oil pulling) with rosemary-and-tsubaki hair masks. Transparent labels, no fluoride theater, and formulas that sit between traditional botanicals and modern enamel research.",
    location: "United States",
    founded: 2022,
    categories: ["oral","hair"],
    accent: "#8B5A2B",
    rating: 4.7,
    reviewCount: 210,
    followerCount: 3800,
    websiteUrl: "https://selfwisebrand.com",
    logoUrl: "/brands/selfwise.svg",
  },
  {
    id: "c615",
    slug: "organic-skin-co",
    name: "The Organic Skin Co",
    tagline: "Certified organic Australian face oils and greens you can actually finish",
    story: "A New Zealand–born, Australia-loved organic house known for The Good Oil and a short certified-organic lineup — face oils, collagen builders, and glow greens without the 40-step K-beauty pile-on or a paragraph of petrochemical fillers.",
    location: "Australia / New Zealand",
    founded: 2015,
    categories: ["skincare","supplements"],
    accent: "#2E8B6A",
    rating: 4.7,
    reviewCount: 1900,
    followerCount: 48000,
    websiteUrl: "https://theorganicskinco.com",
    logoUrl: "/brands/organic-skin-co.svg",
  },
  {
    id: "c616",
    slug: "uma",
    name: "UMA Oils",
    tagline: "Ayurvedic face oils from a fifth-generation herbalist family",
    story: "A family Ayurvedic house making facial oils, masks, and youth rituals from cold-pressed botanicals — no paraben-and-perfume pile-on, just the kind of short, fragrant lists that read like a spice cabinet and a clinical facial at once.",
    location: "India / United States",
    founded: 2015,
    categories: ["skincare"],
    accent: "#8B3A2A",
    rating: 4.7,
    reviewCount: 1400,
    followerCount: 36000,
    websiteUrl: "https://www.umaoils.com",
    logoUrl: "/brands/uma.png",
  },
  {
    id: "c617",
    slug: "less-is-more",
    name: "Less is More",
    tagline: "Austrian organic hair care that treats “less” as the whole point",
    story: "Salzburg-born certified organic hair care: shampoos, conditioners, and styling that skip silicones, sulfates, and synthetic fragrance. Small-batch European botanicals for people who want their wash day to look like a garden, not a lab.",
    location: "Salzburg, Austria",
    founded: 2007,
    categories: ["hair","skincare"],
    accent: "#4A6741",
    rating: 4.8,
    reviewCount: 980,
    followerCount: 19000,
    websiteUrl: "https://www.lessismore.at",
    logoUrl: "/brands/less-is-more.png",
  },
  {
    id: "c618",
    slug: "abache",
    name: "Abaché Organics",
    tagline: "COSMOS organic, preservative-free hair care that treats scalp like skin",
    story: "An Australian certified-organic hair house making vegan, preservative-free shampoos, density serums, and shine oils — audited plant essences, waterway-friendly formulas, and no synthetic “vegan” detergents pretending to be a garden.",
    location: "Australia",
    founded: 2016,
    categories: ["hair"],
    accent: "#6B3E26",
    rating: 4.8,
    reviewCount: 340,
    followerCount: 7200,
    websiteUrl: "https://www.abacheorganics.com",
    logoUrl: "/brands/abache.svg",
  },
  {
    id: "c619",
    slug: "selkie",
    name: "Selkie",
    tagline: "Powder-to-liquid shampoo you mix at home — 98% natural, zero bottle water",
    story: "A tiny sustainable hair studio that ships powder, not water. Sulfate-free, silicone-free shampoo and conditioner you reconstitute at the sink — 98%+ natural origin, refill pouches instead of another single-use bottle, and every ingredient published.",
    location: "Independent / DTC",
    founded: 2022,
    categories: ["hair"],
    accent: "#1A4A6B",
    rating: 4.7,
    reviewCount: 160,
    followerCount: 4100,
    websiteUrl: "https://selkiehaircare.com",
    logoUrl: "/brands/selkie.svg",
  },
  {
    id: "c620",
    slug: "plant-people",
    name: "Plant People",
    tagline: "Functional mushroom gummies and sleep rituals without the candy-aisle junk",
    story: "A plant-forward supplement house making sleep, focus, and family gummies around functional mushrooms and botanicals — cleaner than the gas-station vitamin aisle, with flavors kids will finish and labels adults can read out loud.",
    location: "United States",
    founded: 2018,
    categories: ["supplements"],
    accent: "#3F6B4B",
    rating: 4.6,
    reviewCount: 2200,
    followerCount: 54000,
    websiteUrl: "https://www.plantpeople.co",
    logoUrl: "/brands/plant-people.svg",
  },
];
