import type { Brand } from "./types";

/** Wave 57: small organic / toxic-free brands across marketplace categories (c1212+). */
export const catalogBrandsWave57: Brand[] = [
  {
    id: "c1212",
    slug: "essential-toothpaste",
    name: "Essential Toothpaste",
    tagline: "Canadian 10% nano-hydroxyapatite toothpaste tablets",
    story: "A small Canadian oral house pressing fluoride-free 10% nano-hydroxyapatite toothpaste tablets with xylitol and mint or tropical oils. Individual 65-tab mint and Tropical jars stay. The single bamboo brush stays. The Explorer travel case, three-month 195-tab pack, and five-brush bundle stay boxed. CAD prices convert to USD.",
    location: "Canada",
    founded: 2023,
    categories: ["oral"],
    accent: "#3F6B52",
    rating: 4.6,
    reviewCount: 64,
    followerCount: 1400,
    websiteUrl: "https://essentialtoothpaste.com",
    logoUrl: "/brands/essential-toothpaste.svg",
  },
  {
    id: "c1213",
    slug: "heavenly-tallow",
    name: "Heavenly Tallow",
    tagline: "North Carolina grass-fed tallow sun cream, whipped jars, and goat-milk soap",
    story: "A family tallow kitchen in North Carolina, started in 2024, that whips grass-fed tallow into a mineral Sun Shade cream, named face-and-body jars, goat-milk soap bars, and two lip balms. Sun cream and whipped jars stay. Makeup tints, bug guard, and CBD stay out. Jar size is not a flavor.",
    location: "North Carolina, United States",
    founded: 2024,
    categories: ["sunscreen","skincare"],
    accent: "#7A5A3A",
    rating: 4.7,
    reviewCount: 92,
    followerCount: 1800,
    websiteUrl: "https://heavenlytallow.com",
    logoUrl: "/brands/heavenly-tallow.svg",
  },
  {
    id: "c1214",
    slug: "papabear",
    name: "PapaBear Naturals",
    tagline: "USA-made tallow sunblock, magnesium deodorant, and charcoal tooth powder",
    story: "A small American homestead line pouring a non-nano zinc tallow sunblock, Bear Necessity deodorant, mint charcoal tooth powder, neem mouthwash, whipped tallow, beard oil, and named soaps. Individual formulas stay. Bundles, popcorn, chips, cooking tallow, pet aisle, laundry, and candles stay out. Balm and wash scents expand. Size stays one listing.",
    location: "United States",
    founded: 2022,
    categories: ["sunscreen","deodorant","oral","skincare","hair"],
    accent: "#5C4033",
    rating: 4.6,
    reviewCount: 148,
    followerCount: 2400,
    websiteUrl: "https://thepapabear.com",
    logoUrl: "/brands/papabear.svg",
  },
  {
    id: "c1215",
    slug: "hands-organic",
    name: "Hands Organic",
    tagline: "Oregon vegan mineral deodorant creams and botanical face balms",
    story: "A small Oregon studio making a vegan mineral deodorant cream in four scents, a lemon-lavender summer stick, a deo detox mask, and short-list botanical moisturizers and cleansers. Deodorant Style options expand. Perfume oils, lip gloss, wooden spoons, and artisan mask sets stay out.",
    location: "Oregon, United States",
    founded: 2018,
    categories: ["deodorant","skincare"],
    accent: "#6B3E26",
    rating: 4.7,
    reviewCount: 86,
    followerCount: 1600,
    websiteUrl: "https://handsorganicskincare.com",
    logoUrl: "/brands/hands-organic.svg",
  },
  {
    id: "c1216",
    slug: "hydee",
    name: "HYDEE",
    tagline: "New Zealand fruit-powder electrolytes with Himalayan salt and monk fruit",
    story: "A New Zealand hydration house mixing freeze-dried fruit, Himalayan pink salt, and monk fruit into Everyday and Ultra electrolyte sachets, plus a clean creatine tub. Everyday and Ultra flavors expand. Sachet versus bulk is size, not a flavor. Protein oats, bottles, and bundles stay out. NZD prices convert to USD.",
    location: "New Zealand",
    founded: 2023,
    categories: ["electrolytes","supplements"],
    accent: "#1B4F72",
    rating: 4.6,
    reviewCount: 78,
    followerCount: 1700,
    websiteUrl: "https://hydeeblends.com",
    logoUrl: "/brands/hydee.svg",
  },
  {
    id: "c1217",
    slug: "encompass-farming",
    name: "Encompass Farming",
    tagline: "Oregon Cascade fruiting-body extracts, goat-milk soap, and tallow balm",
    story: "A family organic mushroom farm in the Oregon Cascades that dual-extracts Lion's Mane & Cordyceps and Reishi & Turkey Tail, then pours a simple deodorant, tallow balm, goat-milk soap, and lip balm. Individual extracts and formulas stay. Laundry soap, candles, $850 ritual oils, free gifts, and bundles stay out.",
    location: "Oregon Cascade foothills, United States",
    founded: 2021,
    categories: ["supplements","deodorant","skincare"],
    accent: "#4A5D23",
    rating: 4.7,
    reviewCount: 54,
    followerCount: 1100,
    websiteUrl: "https://encompassfarming.com",
    logoUrl: "/brands/encompass-farming.svg",
  },
];
