import type { Brand } from "./types";

/** Wave 66: small organic / toxic-free brands across marketplace categories (c1266+). */
export const catalogBrandsWave66: Brand[] = [
  {
    id: "c1266",
    slug: "tidalove",
    name: "Tidalove",
    tagline: "Plastic-free nano-hydroxyapatite toothpaste tablets in Cool Mint, Cinnamon, and Yuzu",
    story: "A small oral house that presses 5% nano-hydroxyapatite into chew-to-brush tablets instead of a plastic tube. Cool Mint, Cinnamon, and Yuzu Mint already live on separate 1-month titles; tin vs refill is size, not flavor. 4-month people-packs, gift trios, holders, and pearl serum stay boxed.",
    location: "United States",
    founded: 2023,
    categories: ["oral","skincare"],
    accent: "#2F6F7A",
    rating: 4.6,
    reviewCount: 88,
    followerCount: 1600,
    websiteUrl: "https://tidalove.com",
    logoUrl: "/brands/tidalove.svg",
  },
  {
    id: "c1267",
    slug: "enact-hydration",
    name: "Enact Hydration",
    tagline: "Cardiologist-formulated stick electrolytes with a six-ingredient label and no stevia",
    story: "UNC cardiologist Dr. Christopher Kelly mixed a POTS-minded daily drink with 600 mg sodium and a short published list: sodium citrate, cane sugar, potassium citrate, magnesium citrate, and salt, plus lemon essence on Lemon Bliss. Unflavored and Lemon Bliss already live on separate titles. No merch aisle.",
    location: "North Carolina",
    founded: 2024,
    categories: ["electrolytes"],
    accent: "#C4A15A",
    rating: 4.7,
    reviewCount: 142,
    followerCount: 2800,
    websiteUrl: "https://enacthydration.com",
    logoUrl: "/brands/enact-hydration.svg",
  },
  {
    id: "c1268",
    slug: "flora-fauna-skin",
    name: "Flora Fauna Skin",
    tagline: "Grass-fed tallow sun balm with 15% non-nano zinc, plus a four-SKU botanical face line",
    story: "A tiny US tallow house that folds 15% non-nano zinc into a grass-fed tallow, kokum, and jojoba sun balm, then pairs it with Tallow Glow, a gentle enzyme cleanser, and Desert Daze mist. There is no merch aisle. The sun balm stays sunscreen; the other three stay skincare.",
    location: "United States",
    founded: 2023,
    categories: ["sunscreen","skincare"],
    accent: "#6B8F4E",
    rating: 4.8,
    reviewCount: 30,
    followerCount: 900,
    websiteUrl: "https://florafaunaskin.com",
    logoUrl: "/brands/flora-fauna-skin.svg",
  },
  {
    id: "c1269",
    slug: "oxford-hill",
    name: "Oxford Hill",
    tagline: "Aluminum-free tallow-and-magnesium deodorant with clay pomade and sea-salt texture spray",
    story: "A small grooming shop that pours aluminum-free tallow magnesium deodorant next to unscented and scented hair clays, a texture paste, an air-dry cream, and a sea-salt spray. Perfume oil, gift cards, and clay-plus-spray kits stay boxed. Jar size is not a flavor.",
    location: "United States",
    founded: 2023,
    categories: ["deodorant","hair"],
    accent: "#3D4A3A",
    rating: 4.6,
    reviewCount: 54,
    followerCount: 1100,
    websiteUrl: "https://oxfordhill.co",
    logoUrl: "/brands/oxford-hill.svg",
  },
  {
    id: "c1270",
    slug: "mindful-crumb",
    name: "MindfulCrumb",
    tagline: "Porto single-ingredient grass-fed whey with no gums, stevia, or seed oils",
    story: "A Porto kitchen that treats protein like food: the whey concentrate is one ingredient, grass-fed and low-lactose, with published lab notes on the site. Cart.js is EUR, so the €40 bag stores as USD. Protein balls, brioche, ritual kits, shilajit stacks, and gift cards stay boxed.",
    location: "Porto, Portugal",
    founded: 2023,
    categories: ["protein"],
    accent: "#8B5A3A",
    rating: 4.7,
    reviewCount: 41,
    followerCount: 800,
    websiteUrl: "https://mindfulcrumb.com",
    logoUrl: "/brands/mindful-crumb.svg",
  },
  {
    id: "c1271",
    slug: "mmm-farms",
    name: "MMM Farms",
    tagline: "Family mushroom farm tinctures from 100% fruiting-body lion's mane, reishi, and cordyceps",
    story: "Mountain Meadow Mushrooms still grows and bottles on the farm: lion's mane, reishi, cordyceps, maitake, shiitake, and turkey tail tinctures plus a lion's mane powder, all labeled 100% fruiting body. Grow kits, dried culinary bags, and gift cards stay boxed.",
    location: "United States",
    founded: 1952,
    categories: ["supplements"],
    accent: "#5A6B3A",
    rating: 4.6,
    reviewCount: 36,
    followerCount: 700,
    websiteUrl: "https://mmmfarms.myshopify.com",
    logoUrl: "/brands/mmm-farms.svg",
  },
];
