import type { Brand } from "./types";

/** Wave 104: small organic / toxic-free brands across marketplace categories (c1493+). */
export const catalogBrandsWave104: Brand[] = [
  {
    id: "c1493",
    slug: "huppy",
    name: "Huppy",
    tagline: "LA plastic-free n-HA toothpaste tablets — peppermint, strawberry, cinnamon, charcoal mint",
    story:
      "A Los Angeles crew got tired of squeezing fluoride tubes into the landfill. Huppy is the chew-and-brush tablet they wanted: nano-hydroxyapatite instead of fluoride, compostable refill pouches, and a tin you keep. Peppermint, strawberry, cinnamon, and charcoal mint. Plus mouthwash tablets, silk-style floss, a tongue cleaner, and a bamboo travel brush. No toiletry merch, no gift cards: the tablets that live by the sink.",
    location: "Los Angeles, CA",
    founded: 2020,
    categories: ["oral"],
    accent: "#2BB3A3",
    rating: 4.7,
    reviewCount: 2140,
    followerCount: 18600,
    websiteUrl: "https://www.behuppy.com",
    logoUrl: "/brands/huppy.svg",
  },
  {
    id: "c1494",
    slug: "drinkwel",
    name: "Drinkwel",
    tagline: "Great Salt Lake LyteShow drops and LytePow — unsweetened minerals, lemon-lime powder, no sports-drink dye",
    story:
      "Two friends left Vegas with a pile of single-purpose vitamins and one question: why isn't the hydration in one clean bottle? Drinkwel's Lyte line is the answer they kept — LyteShow drops from Great Salt Lake ionic minerals (magnesium, potassium, sodium, chloride, zinc), LytePow lemon-lime powder, LyteCaps, LyteTrace, and LyteMAG. No sugar sports-drink dyes, no hangover-pill merch on this shelf. A few drops in water, or a scoop of lemon-lime. That's the ritual.",
    location: "United States",
    founded: 2013,
    categories: ["electrolytes"],
    accent: "#1E6B8A",
    rating: 4.6,
    reviewCount: 1280,
    followerCount: 9200,
    websiteUrl: "https://drinkwel.com",
    logoUrl: "/brands/drinkwel.png",
  },
  {
    id: "c1495",
    slug: "pulsin",
    name: "Pulsin",
    tagline: "Gloucester plant protein pouches — pea, faba, rice, soya, and a complete vanilla-chocolate blend",
    story:
      "Bristol uni friends Simon, Nick, and Ben started rolling energy balls after hours in a London café kitchen, then gave up the day jobs in 2007 for a small factory. Pulsin now makes the pouches from Gloucestershire: unflavoured pea, faba bean, rice, and soya, plus a complete pea-faba-pumpkin blend in vanilla, chocolate, chocolate hazelnut, and pumpkin spice. Twenty grams of plant protein, no bars, no brownie multipacks. The powders you actually scoop.",
    location: "Gloucester, UK",
    founded: 2007,
    categories: ["protein"],
    accent: "#3D8B6E",
    rating: 4.6,
    reviewCount: 1860,
    followerCount: 14200,
    websiteUrl: "https://pulsin.co.uk",
    logoUrl: "/brands/pulsin.svg",
  },
  {
    id: "c1496",
    slug: "swellies",
    name: "Swellies",
    tagline: "Colorado five-ingredient SPF 46 — 21% non-nano zinc, serum-gel, zero white cast",
    story:
      "She grew up sailing busted Lasers on Lake Michigan, then moved to the Big Island for wilderness therapy and learned the hard way that most 'reef-safe' bottles are silicones and a white cast. Her partner Brooks locked in for a year of kitchen batches. Swellies is the five-ingredient SPF 46 they landed on in Colorado: 21% non-nano zinc oxide, coco-caprylate, dextrin palmitate, polyhydroxystearic acid, iron oxides. No chemical filters, no fragrance, no second SKU. One bottle for skin that actually lives outside.",
    location: "Colorado",
    founded: 2025,
    categories: ["sunscreen"],
    accent: "#2A6F8F",
    rating: 4.8,
    reviewCount: 42,
    followerCount: 1100,
    websiteUrl: "https://swellies.com",
    logoUrl: "/brands/swellies.svg",
  },
  {
    id: "c1497",
    slug: "little-tallow-co",
    name: "Little Tallow Co",
    tagline: "Pennsylvania kitchen tallow — aluminum-free deodorant, whipped balms, goat-milk soap, bear-tallow hair",
    story:
      "Taylor built Little Tallow Co at the kitchen table after her son's eczema laughed at every 'clean' cream on the shelf. Grass-fed, grass-finished tallow from a regenerative Pennsylvania farm — no hormones, no soy, no grain finish. Aluminum-free deodorant in bergamot, tea tree, and orange cedarwood. Whipped balms, Everywhere sticks, goat-milk soap, a bear-tallow scalp serum, and a shampoo bar. No mugs, no trucker hats: the jars her kids still help label.",
    location: "Pennsylvania",
    founded: 2023,
    categories: ["deodorant", "skincare", "hair"],
    accent: "#8B5E3C",
    rating: 4.8,
    reviewCount: 640,
    followerCount: 5200,
    websiteUrl: "https://littletallow.com",
    logoUrl: "/brands/little-tallow-co.svg",
  },
  {
    id: "c1498",
    slug: "gribb",
    name: "Gribb",
    tagline: "Portimão organic fruiting-body tinctures — Lion's Mane to reishi, grown on the farm, no grow kits",
    story:
      "Cláudia and Ion studied mycology until the Russian word grib (mushroom) became a farm. Gribb is a certified-organic vertical farm in Portimão, Algarve — spore to fruiting body on sawdust from Monchique woodshops, dual-extracted 10:1, bottled under PT-BIO-10. Lion's Mane, reishi, cordyceps, chaga, shiitake, maitake, tremella, Agaricus blazei, and mesima. No coffee, no cacao, no grow-your-first-mushroom class. Nine tinctures from the mushrooms they actually grew.",
    location: "Portimão, Portugal",
    founded: 2021,
    categories: ["supplements"],
    accent: "#3A4F3A",
    rating: 4.7,
    reviewCount: 186,
    followerCount: 3400,
    websiteUrl: "https://gribbworld.com",
    logoUrl: "/brands/gribb.svg",
  },
];
