import type { Brand } from "./types";

/** Wave 64: small organic / toxic-free brands across marketplace categories (c1254+). */
export const catalogBrandsWave64: Brand[] = [
  {
    id: "c1254",
    slug: "keeko",
    name: "Keeko",
    tagline: "Australian hydroxyapatite toothpaste, oil-pull sachets, and plastic-neutral brushes",
    story: "Australia's plastic-neutral oral house puts COSMOS hydroxyapatite and Kakadu plum into a fluoride-free Dream Clean paste, then pairs it with mint oil-pull sachets, coconut floss, and a copper tongue cleaner. Individual tubes, sachets, the single biodegradable brush, floss, and scraper stay. Bundles, gift cards, shipping protection, and the whitening pen stay boxed. Cart.js is USD — do not apply AUD. Brush color is color, not a flavor tree.",
    location: "Australia",
    founded: 2018,
    categories: ["oral"],
    accent: "#2F6B4F",
    rating: 4.6,
    reviewCount: 128,
    followerCount: 3200,
    websiteUrl: "https://keekooralcare.com",
    logoUrl: "/brands/keeko.svg",
  },
  {
    id: "c1255",
    slug: "oovii",
    name: "Oovii",
    tagline: "One-SKU UK kids mineral face SPF — non-nano zinc, daily habit not beach-only",
    story: "Two fashion insiders in the UK built Face First so kids' SPF could live next to the toothbrush, not only in the beach bag. Non-nano zinc oxide in a single facial sunscreen. There is no merch aisle and no flavor-option tree. GBP prices convert to USD.",
    location: "United Kingdom",
    founded: 2025,
    categories: ["sunscreen"],
    accent: "#E8B86D",
    rating: 4.5,
    reviewCount: 42,
    followerCount: 1100,
    websiteUrl: "https://oovii.com",
    logoUrl: "/brands/oovii.svg",
  },
  {
    id: "c1256",
    slug: "bison-protein",
    name: "Bison Protein",
    tagline: "Zero-sugar Australian collagen-protein cola — citrus, no crash",
    story: "A small Australian drink house that folds 10g of collagen peptides into a zero-sugar clean cola. The citrus cola is the live priced SKU; coconut-water bottles currently list at $0 and drop. AUD prices convert to USD. There is no merch aisle.",
    location: "Australia",
    founded: 2024,
    categories: ["protein"],
    accent: "#C45C26",
    rating: 4.4,
    reviewCount: 36,
    followerCount: 800,
    websiteUrl: "https://bisonprotein.com",
    logoUrl: "/brands/bison-protein.svg",
  },
  {
    id: "c1257",
    slug: "massie-provisions",
    name: "Massie Provisions",
    tagline: "Indiana farm-rendered tallow — sun balm, magnesium deodorant, soaps, and beard",
    story: "Owen County cattle, rendered in-house, then poured into a mineral sun balm, aluminum-free deodorant, T-Balm jars, T-Soap, T-Sticks, pomade, and beard balm. Deodorant, balm, soap, stick, pomade, beard, hydrosol, scrub, and salve scents expand. Cooking tallow, raw honey, candles, wax melts, and provision sets stay boxed. Jar size is not a flavor.",
    location: "Indiana, United States",
    founded: 2022,
    categories: ["skincare","sunscreen","deodorant","hair"],
    accent: "#6B4A2A",
    rating: 4.7,
    reviewCount: 88,
    followerCount: 1900,
    websiteUrl: "https://massieprovisions.com",
    logoUrl: "/brands/massie-provisions.svg",
  },
  {
    id: "c1258",
    slug: "hemsworth-homestead",
    name: "Hemsworth Homestead",
    tagline: "Iowa homestead tallow creams, aluminum-free deodorant, and sulfate-free shampoo bars",
    story: "A family homestead in Iowa that whips grass-fed tallow, pours aluminum- and baking-soda-free deodorant, and cuts rosemary-thyme shampoo and conditioner bars. After-sun spray stays sunscreen. Deodorant, lip, lotion, body-butter, sugar-scrub, and magnesium-cream scents expand; dry-shampoo Dark/Light expands. Tees, candles, syrup, room spray, tea, perfume, dog soap, gua sha, dishes, sisal, tinted lip, and gift sets stay boxed. Jar size is not a flavor.",
    location: "Iowa, United States",
    founded: 2021,
    categories: ["skincare","deodorant","hair","sunscreen"],
    accent: "#7A5A3A",
    rating: 4.8,
    reviewCount: 156,
    followerCount: 2800,
    websiteUrl: "https://hemsworthhomestead.com",
    logoUrl: "/brands/hemsworth-homestead.svg",
  },
  {
    id: "c1259",
    slug: "longevity-power",
    name: "Longevity Power",
    tagline: "Naked coconut-water electrolytes plus fruiting-body mushroom and ancestral powders",
    story: "A clean-label powder house that skips 'natural flavors' and builds Epic Electrolytes from Arctic sea salt and coconut water, then dual-extracts lion's mane, reishi, and mixed mushrooms. Electrolyte Naked Coconut Water and Vanilla Café Ritual expand; Ancestral Feast and Epic Beef Liver flavors expand. Serving size is size. Stacks, bundles, kits, and gift cards stay boxed.",
    location: "United States",
    founded: 2021,
    categories: ["electrolytes","supplements"],
    accent: "#1F4E5F",
    rating: 4.6,
    reviewCount: 94,
    followerCount: 2400,
    websiteUrl: "https://longevitypower.com",
    logoUrl: "/brands/longevity-power.svg",
  },
  {
    id: "c1260",
    slug: "essee-farms",
    name: "Essee Farms",
    tagline: "Goat-milk rice-water shampoo bars and farm lotions — no sulfates, no wax-melt aisle",
    story: "A small US farm shop that saponifies goat milk with fermented rice water and walnut oil, then bottles matching lotions and lotion bars. Individual shampoo bars, named soaps, and lotions stay. Wax melts, car diffusers, essential-oil singles, soap racks, bath sprinkles, gift cards, and in-store misc stay boxed. 2 oz vs 8 oz is size, not a flavor.",
    location: "United States",
    founded: 2019,
    categories: ["skincare","hair"],
    accent: "#8B6B3A",
    rating: 4.5,
    reviewCount: 72,
    followerCount: 1400,
    websiteUrl: "https://esseefarms.com",
    logoUrl: "/brands/essee-farms.svg",
  },
];
