import type { Brand } from "./types";

/** Wave 8: small organic / toxic-free brands across marketplace categories (c541+). */
export const catalogBrandsWave8: Brand[] = [
  {
    id: "c541",
    slug: "mama-sol",
    name: "Mama Sol",
    tagline: "Pregnancy-safe 100% mineral SPF that feels like skincare",
    story: "Los Angeles moms built Facebrella after chemical filters showed up on the pregnancy avoid-list — non-nano zinc, glass bottles, and a 3-in-1 moisturizer-primer-SPF that skips the chalky white cast.",
    location: "Los Angeles, CA",
    founded: 2017,
    categories: ["sunscreen","skincare"],
    accent: "#E8A54B",
    rating: 4.7,
    reviewCount: 420,
    followerCount: 9800,
    websiteUrl: "https://www.shopmamasol.com",
    logoUrl: "/brands/mama-sol.svg",
  },
  {
    id: "c542",
    slug: "oyster-suncare",
    name: "Oyster Suncare",
    tagline: "Certified organic mineral SPF50+ from the Australian coast",
    story: "A small Australian sun house packing 25% non-nano zinc into certified organic creams — reef-minded SPF50+ that hydrates like a face cream instead of a greasy sport lotion.",
    location: "Australia",
    founded: 2020,
    categories: ["sunscreen"],
    accent: "#0E7490",
    rating: 4.8,
    reviewCount: 310,
    followerCount: 6400,
    websiteUrl: "https://oystersuncare.com",
    logoUrl: "/brands/oyster-suncare.svg",
  },
  {
    id: "c543",
    slug: "spooge",
    name: "SPOOGE",
    tagline: "Derm-developed mineral all-screen from Reno-Tahoe",
    story: "A skin-cancer surgeon got tired of patients skipping SPF — so she made a sheer 22% zinc formula without oxybenzone, octinoxate, parabens, or phthalates that actually gets worn on ski days and trail days.",
    location: "Reno-Tahoe, NV",
    founded: 2023,
    categories: ["sunscreen"],
    accent: "#C45C26",
    rating: 4.7,
    reviewCount: 180,
    followerCount: 5200,
    websiteUrl: "https://spooge.co",
    logoUrl: "/brands/spooge.svg",
  },
  {
    id: "c544",
    slug: "jigsaw",
    name: "Jigsaw Health",
    tagline: "Timed-release magnesium and short-list electrolytes",
    story: "Arizona-born mineral formulas — SRT magnesium and pickleball-ready hydration without sugar dyes or a mystery ‘proprietary blend.’ The salts and the cofactors, not a candy packet.",
    location: "Scottsdale, AZ",
    founded: 2005,
    categories: ["electrolytes","supplements"],
    accent: "#1B4F72",
    rating: 4.7,
    reviewCount: 8600,
    followerCount: 41000,
    websiteUrl: "https://jigsawhealth.com",
    logoUrl: "/brands/jigsaw.png",
  },
  {
    id: "c545",
    slug: "trace-minerals",
    name: "Trace Minerals",
    tagline: "Great Salt Lake minerals in drops, paks, and powders",
    story: "Utah’s ConcenTrace house — full-spectrum ionic minerals and Hydro Pak electrolytes from the Great Salt Lake, without the neon sport-drink dye job.",
    location: "Ogden, UT",
    founded: 1972,
    categories: ["electrolytes","supplements"],
    accent: "#0E7490",
    rating: 4.6,
    reviewCount: 12400,
    followerCount: 38000,
    websiteUrl: "https://traceminerals.com",
    logoUrl: "/brands/trace-minerals.png",
  },
  {
    id: "c546",
    slug: "pulsin",
    name: "Pulsin",
    tagline: "Gloucestershire plant protein without soy isolate sludge",
    story: "A UK kitchen that treats protein like food — pea, rice, and pumpkin blends, chocolate and vanilla pouches, and bars that skip artificial sweeteners and a bodybuilder label.",
    location: "Gloucestershire, United Kingdom",
    founded: 2005,
    categories: ["protein"],
    accent: "#16A34A",
    rating: 4.6,
    reviewCount: 3200,
    followerCount: 18000,
    websiteUrl: "https://pulsin.co.uk",
    logoUrl: "/brands/pulsin.svg",
  },
  {
    id: "c547",
    slug: "owyn",
    name: "OWYN",
    tagline: "Plant protein shakes for the top allergen-avoiders",
    story: "Only What You Need — pea, pumpkin, and flax protein shakes without dairy, soy, gluten, egg, or the usual shake-aisle junk. Flavors that read like a diner menu, not a lab.",
    location: "New York, NY",
    founded: 2016,
    categories: ["protein"],
    accent: "#5B21B6",
    rating: 4.5,
    reviewCount: 9800,
    followerCount: 72000,
    websiteUrl: "https://liveowyn.com",
    logoUrl: "/brands/owyn.svg",
  },
  {
    id: "c548",
    slug: "honestly-phresh",
    name: "Honestly pHresh",
    tagline: "Prebiotic magnesium deodorant, no aluminum or baking soda",
    story: "In-house magnesium sticks and sprays that keep the underarm microbiome in mind — aluminum-free, baking-soda-free, and scented with real botanicals instead of a fragrance fog.",
    location: "United States",
    founded: 2021,
    categories: ["deodorant"],
    accent: "#2C5F4E",
    rating: 4.7,
    reviewCount: 640,
    followerCount: 8900,
    websiteUrl: "https://honestlyphresh.com",
    logoUrl: "/brands/honestly-phresh.png",
  },
  {
    id: "c549",
    slug: "tanit",
    name: "TANIT",
    tagline: "Plastic-free Canadian deodorant and toothpaste tablets",
    story: "Montreal-made magnesium deodorant in compostable cardboard and toothpaste tablets you can actually finish — no aluminum, no baking soda rash, no plastic tube graveyard.",
    location: "Montreal, QC",
    founded: 2018,
    categories: ["deodorant","oral"],
    accent: "#365314",
    rating: 4.7,
    reviewCount: 2100,
    followerCount: 16000,
    websiteUrl: "https://www.tanit.co",
    logoUrl: "/brands/tanit.svg",
  },
  {
    id: "c550",
    slug: "theodent",
    name: "Theodent",
    tagline: "Theobromine toothpaste from a New Orleans chocolate lab",
    story: "Tulane scientists noticed cocoa made enamel harder — so they built a fluoride-free paste around theobromine instead of a mint-candy chemical stack. Kids and classic tubes, same idea.",
    location: "New Orleans, LA",
    founded: 2012,
    categories: ["oral"],
    accent: "#6B3E26",
    rating: 4.6,
    reviewCount: 1800,
    followerCount: 12000,
    websiteUrl: "https://theodent.com",
    logoUrl: "/brands/theodent.png",
  },
  {
    id: "c551",
    slug: "grants-of-australia",
    name: "Grants of Australia",
    tagline: "Australian natural toothpaste without SLS foam circus",
    story: "Family-run Aussie oral care — peppermint whitening, kids’ berry pastes, and mouthwash that skip sodium lauryl sulfate, artificial colors, and the usual supermarket foam show.",
    location: "Australia",
    founded: 1999,
    categories: ["oral"],
    accent: "#0E7490",
    rating: 4.6,
    reviewCount: 2400,
    followerCount: 11000,
    websiteUrl: "https://grantsofaustralia.com",
    logoUrl: "/brands/grants-of-australia.svg",
  },
  {
    id: "c552",
    slug: "ranavat",
    name: "Ranavat",
    tagline: "Ayurvedic saffron skincare, farm-direct from Rajasthan",
    story: "A Rajasthan-to-LA line that treats saffron, bakuchi, and rose like actives — brightening cleansers and firming serums with a short botanical list and none of the synthetic filler fog.",
    location: "Los Angeles, CA / Rajasthan",
    founded: 2017,
    categories: ["skincare"],
    accent: "#9A3412",
    rating: 4.8,
    reviewCount: 1600,
    followerCount: 28000,
    websiteUrl: "https://ranavat.com",
    logoUrl: "/brands/ranavat.svg",
  },
  {
    id: "c553",
    slug: "clearstem",
    name: "CLEARSTEM",
    tagline: "Acne-safe clean skincare without pore-clogging junk",
    story: "A derm-meets-esthetician shortlist — acne-safe serums, masks, and mineral SPF that skip comedogenic oils, endocrine circus, and the ‘clean’ products that still break people out.",
    location: "San Diego, CA",
    founded: 2018,
    categories: ["skincare","sunscreen"],
    accent: "#BE185D",
    rating: 4.7,
    reviewCount: 5400,
    followerCount: 62000,
    websiteUrl: "https://clearstemskincare.com",
    logoUrl: "/brands/clearstem.svg",
  },
  {
    id: "c554",
    slug: "eat-my-face",
    name: "Eat My Face",
    tagline: "Small-batch grass-fed tallow cream and mineral SPF",
    story: "Hand-poured the week you order it — grass-fed tallow moisturizers and a reef-safe 21.6% non-nano zinc sunscreen with edible-grade supporting oils and no chemical-filter cocktail.",
    location: "United States",
    founded: 2023,
    categories: ["skincare","sunscreen"],
    accent: "#6B3E26",
    rating: 4.8,
    reviewCount: 290,
    followerCount: 4100,
    websiteUrl: "https://eatmyface.co",
    logoUrl: "/brands/eat-my-face.svg",
  },
  {
    id: "c555",
    slug: "alaffia",
    name: "Alaffia",
    tagline: "Fair-trade Togolese shea, black soap, and wash-day care",
    story: "Founded in Togo and Olympia on a simple deal — pay shea collectives fairly, keep the ingredient list plant-first. African black soap, curl cream, and unscented Everyday Shea without the drugstore junk drawer.",
    location: "Olympia, WA / Togo",
    founded: 2003,
    categories: ["hair","skincare"],
    accent: "#4D7C0F",
    rating: 4.7,
    reviewCount: 6800,
    followerCount: 54000,
    websiteUrl: "https://alaffia.com",
    logoUrl: "/brands/alaffia.png",
  },
  {
    id: "c556",
    slug: "yarok",
    name: "Yarok",
    tagline: "Organic salon haircare that skips silicones and sulfates",
    story: "A New York organic hair house — Feed Your Moisture shampoos, feed-your-style stylers, and oils that treat botanicals like the formula, not the afterthought.",
    location: "New York, NY",
    founded: 2010,
    categories: ["hair"],
    accent: "#365314",
    rating: 4.6,
    reviewCount: 1900,
    followerCount: 22000,
    websiteUrl: "https://yarokhair.com",
    logoUrl: "/brands/yarok.png",
  },
  {
    id: "c557",
    slug: "intelligent-nutrients",
    name: "Intelligent Nutrients",
    tagline: "Certified organic hair and face oils from Aveda’s founder",
    story: "Horst Rechelbacher’s second act — USDA organic hair oils, serums, and regimens with a food-grade mindset. If you wouldn’t eat the philosophy, it doesn’t go in the bottle.",
    location: "Minneapolis, MN",
    founded: 2008,
    categories: ["hair","skincare"],
    accent: "#2C5F4E",
    rating: 4.7,
    reviewCount: 2100,
    followerCount: 19000,
    websiteUrl: "https://intelligentnutrients.com",
    logoUrl: "/brands/intelligent-nutrients.png",
  },
  {
    id: "c558",
    slug: "host-defense",
    name: "Host Defense",
    tagline: "Paul Stamets mushroom extracts, grown in Washington woods",
    story: "Mycologist Paul Stamets’ daily mushroom line — lion’s mane, reishi, turkey tail, and MycoBotanicals grown and extracted in Washington, not mycelium-on-grain dust from a mystery warehouse.",
    location: "Olympia, WA",
    founded: 2008,
    categories: ["supplements"],
    accent: "#365314",
    rating: 4.7,
    reviewCount: 9200,
    followerCount: 67000,
    websiteUrl: "https://hostdefense.com",
    logoUrl: "/brands/host-defense.svg",
  },
  {
    id: "c559",
    slug: "organifi",
    name: "Organifi",
    tagline: "Organic green, gold, and red superfood powders",
    story: "San Diego superfoods you actually stir into a glass — USDA organic greens, gold turmeric, and red berry blends without the candy-aisle sweetener stack.",
    location: "San Diego, CA",
    founded: 2016,
    categories: ["supplements"],
    accent: "#16A34A",
    rating: 4.6,
    reviewCount: 15400,
    followerCount: 98000,
    websiteUrl: "https://organifi.com",
    logoUrl: "/brands/organifi.svg",
  },
  {
    id: "c560",
    slug: "ancestral-supplements",
    name: "Ancestral Supplements",
    tagline: "Grass-fed organ meats, protein, and ancestral electrolytes",
    story: "Texas nose-to-tail nutrition — grass-fed liver, thyroid, tallow balm, and protein that treats organs like food instead of isolating a single vitamin out of a factory.",
    location: "Texas",
    founded: 2016,
    categories: ["supplements","protein"],
    accent: "#6B3E26",
    rating: 4.7,
    reviewCount: 4800,
    followerCount: 34000,
    websiteUrl: "https://ancestralsupplements.com",
    logoUrl: "/brands/ancestral-supplements.svg",
  },
];
