import type { Brand } from "./types";

/** Wave 40: small organic / toxic-free brands across marketplace categories (c1077+). */
export const catalogBrandsWave40: Brand[] = [
  {
    id: "c1077",
    slug: "house-of-tallow",
    name: "House of Tallow",
    tagline: "Tallow mineral SOL sun sticks plus aluminum-free deodorant — tint variants, no merch wall",
    story: "A small tallow kitchen that pours grass-fed suet into zinc sun sticks, a three-ingredient SOL spray, aluminum-free deodorant, and whipped butters instead of a chemical-filter-and-fragrance aisle. Deep Bronze, Warm Tint, and unscented sticks stay as their own listings. No merch, no empty tins.",
    location: "United States",
    founded: 2023,
    categories: ["sunscreen","deodorant","skincare","hair"],
    accent: "#8B5A2B",
    rating: 4.6,
    reviewCount: 180,
    followerCount: 3200,
    websiteUrl: "https://houseoftallow.com",
    logoUrl: "/brands/house-of-tallow.svg",
  },
  {
    id: "c1078",
    slug: "nefertem",
    name: "Nefertem",
    tagline: "Illinois family-rendered grass-fed tallow soaps and moisturizers since 2012 — scent SKUs, no bundle wall",
    story: "A Midwest family shop that has hand-rendered grass-fed, grass-finished suet since 2012 and folds it into short-list soaps, moisturizers, and lip balms instead of a 40-ingredient lotion wall. Individual formulas and lip scents stay. Soap-and-moisturizer bundles, gift cards, and cold-shipping kits stay out.",
    location: "Illinois, United States",
    founded: 2012,
    categories: ["skincare"],
    accent: "#6B3E26",
    rating: 4.7,
    reviewCount: 420,
    followerCount: 7800,
    websiteUrl: "https://nefertemnaturals.com",
    logoUrl: "/brands/nefertem.svg",
  },
  {
    id: "c1079",
    slug: "hawaii-tallow",
    name: "Hawaiʻi Alchemy Apothecary",
    tagline: "Hawaiʻi Island farm-rendered tallow plus fruiting-body mushroom extracts — no candle shop",
    story: "A Hawaiʻi Island farm kitchen that slow-renders local grass-fed tallow into face balms, coffee-eye tallow, and island soap bars, then dual-extracts reishi and lion's mane grown for the apothecary. Tallow, toners, serums, hair rinse, and mushroom extracts stay. Beeswax candles, intimacy oils, and ritual kits stay on the farm.",
    location: "Hawaiʻi Island, Hawaii",
    founded: 2021,
    categories: ["skincare","supplements","hair"],
    accent: "#2C5F4E",
    rating: 4.7,
    reviewCount: 160,
    followerCount: 2900,
    websiteUrl: "https://hawaiitallowskincare.com",
    logoUrl: "/brands/hawaii-tallow.svg",
  },
  {
    id: "c1080",
    slug: "oak-grove-farms",
    name: "Oak Grove Farms",
    tagline: "Two-SKU organic fruiting-body tinctures — lion's mane and turkey tail, no grow-kit shop",
    story: "A small organic mushroom farm that dual-extracts only fruiting-body lion's mane and turkey tail in-house instead of a mycelium-on-grain capsule wall. Two tinctures stay. No spawn, no merch, no fresh culinary boxes.",
    location: "United States",
    founded: 2022,
    categories: ["supplements"],
    accent: "#3D5A3A",
    rating: 4.6,
    reviewCount: 48,
    followerCount: 900,
    websiteUrl: "https://oakgrovefarms.myshopify.com",
    logoUrl: "/brands/oak-grove-farms.svg",
  },
  {
    id: "c1081",
    slug: "mahealani-farms",
    name: "Māhealani Farms",
    tagline: "Carpinteria farm tinctures plus lion's mane cream and snow-mushroom serum — no fresh-box shop",
    story: "A Carpinteria, California family farm that freeze-dries its own lion's mane for tinctures and folds snow mushroom and lion's mane into a serum, night cream, and rescue balm instead of a grow-kit-and-fresh-box wall. Tinctures, creams, serum, balm, and reishi-shiitake hair oil stay. Fresh culinary mushrooms, dried mixes, and gift boxes stay on the farm.",
    location: "Carpinteria, California",
    founded: 2019,
    categories: ["supplements","skincare","hair"],
    accent: "#4A6741",
    rating: 4.7,
    reviewCount: 140,
    followerCount: 2600,
    websiteUrl: "https://mahealanifarms.store",
    logoUrl: "/brands/mahealani-farms.svg",
  },
  {
    id: "c1082",
    slug: "dakhota-prairie",
    name: "Dakhota Prairie",
    tagline: "Native-owned reservation-made grass-fed tallow ritual — cleanser, exfoliant, salve, no set wall",
    story: "A Native-owned prairie house that handcrafts grass-fed tallow into a facial purifiant, sugar exfoliant, and luxe salve instead of a synthetic-retinoid wall. Individual formulas stay. Discovery and renewal sets stay out.",
    location: "United States",
    founded: 2024,
    categories: ["skincare"],
    accent: "#5C4033",
    rating: 4.6,
    reviewCount: 70,
    followerCount: 1400,
    websiteUrl: "https://dakhota-prairie.luxury",
    logoUrl: "/brands/dakhota-prairie.svg",
  },
  {
    id: "c1083",
    slug: "tallow-made",
    name: "Tallow Made",
    tagline: "Whipped tallow, healing cream, and aluminum-free deodorant — lavender, vanilla, wild rose, stonewood",
    story: "A small tallow kitchen that keeps whipped tallow, a healing cream, body butter, and a four-scent aluminum-free deodorant instead of a petroleum-and-aluminum aisle. Lavender, vanilla, wild rose, and stonewood stay as their own listings. No merch, no empty jars.",
    location: "United States",
    founded: 2023,
    categories: ["skincare","deodorant"],
    accent: "#6B4F2A",
    rating: 4.6,
    reviewCount: 90,
    followerCount: 1600,
    websiteUrl: "https://www.tallowmade.com",
    logoUrl: "/brands/tallow-made.svg",
  },
  {
    id: "c1084",
    slug: "orawellness",
    name: "OraWellness",
    tagline: "Hydroxyapatite tooth powder and paleo or vegan toothpaste — orange-vanilla and cinnamony mint, no gadget shop",
    story: "A long-running mineral oral house that folds microcrystalline hydroxyapatite into Shine tooth powder plus paleo and vegan pastes instead of a fluoride-and-SLS wall. Orange-vanilla and cinnamony mint stay as their own listings. Red-light gadgets, ebooks, and pH-strip kits stay out.",
    location: "United States",
    founded: 2010,
    categories: ["oral"],
    accent: "#1B4F72",
    rating: 4.7,
    reviewCount: 2400,
    followerCount: 18000,
    websiteUrl: "https://store.orawellness.com",
    logoUrl: "/brands/orawellness.svg",
  },
  {
    id: "c1085",
    slug: "clearly",
    name: "Clearly",
    tagline: "European grass-fed whey and electrolyte powders — vanilla, chocolate, lemon, raspberry, no bottle shop",
    story: "A Netherlands-made clean-stack house that keeps European grass-fed whey and a four-flavor electrolyte powder instead of a sucralose-and-dye tub wall. Whey and electrolyte flavors stay as their own listings. Steel bottles, totes, shakers, olive oil, and matcha stay out. EUR prices convert to USD.",
    location: "Netherlands / Finland",
    founded: 2021,
    categories: ["protein","electrolytes","supplements"],
    accent: "#1F4E79",
    rating: 4.6,
    reviewCount: 320,
    followerCount: 5400,
    websiteUrl: "https://clearly.fi",
    logoUrl: "/brands/clearly.svg",
  },
];
