import type { Brand } from "./types";

/** Wave 92: small organic / toxic-free brands across marketplace categories (c1421+). */
export const catalogBrandsWave92: Brand[] = [
  {
    id: "c1421",
    slug: "nobiesse",
    name: "Nobiesse",
    tagline: "EWG-verified n-HA toothpaste, aluminum-free deodorant, and small-batch clean bars",
    story: "The unused multi-SKU n-HA leftover after dedicated toothpaste-only shops ran out — fluoride-free remineralizing and whitening pastes plus two aluminum-free deodorants, a beeswax lip, shower-and-shampoo bar, and face care. Pack count is size — keep singles. Methylene-blue capsules/soaps/creams, Greenmaid laundry/dish/floor, bug-and-tick soap, and every bundle stay boxed. Cart.js is USD. Toothpaste and deodorant pages are key-ingredient essays (leave empty); hardcode the published beeswax lip and barley bath-bar lists.",
    location: "United States",
    founded: 2021,
    categories: ["oral","deodorant","skincare","hair"],
    accent: "#1F3A4D",
    rating: 4.6,
    reviewCount: 210,
    followerCount: 3200,
    websiteUrl: "https://nobiesse.com",
    logoUrl: "/brands/nobiesse.svg",
  },
  {
    id: "c1422",
    slug: "reef-replenish",
    name: "Reef Replenish",
    tagline: "Tropical coconut-water electrolytes with Himalayan salt — no sucralose",
    story: "The unused clean hydration leftover after wave4–91 — six 30-serving jars (Lemon Lime / Grapefruit / Strawberry Kiwi / Mango Tangerine / Wildberry / Raspberry Lemonade) built on coconut water powder, pink Himalayan salt, and ocean minerals. Flavors already live on titles. Serving count is size. Stevia, no sucralose. Cart.js is USD. Pages are adventure-copy marketing (leave empty).",
    location: "United States",
    founded: 2023,
    categories: ["electrolytes"],
    accent: "#1A6B7A",
    rating: 4.6,
    reviewCount: 64,
    followerCount: 1400,
    websiteUrl: "https://reefreplenish.com",
    logoUrl: "/brands/reef-replenish.svg",
  },
  {
    id: "c1423",
    slug: "organic-protein-company",
    name: "The Organic Protein Company",
    tagline: "UK organic pasture whey — unflavoured, vanilla, cacao, banana, cookies, and coffee",
    story: "The unused British organic whey leftover after wave4–91 — gently filtered whey from organic pasture-grazed cows in six tub flavors (Pure Unflavoured / Madagascan Vanilla / Chocolate Cacao & Maca / Banana & Lucuma / Cookies & Cream / Real Coffee). 400 g vs 1.2 kg / multi-bag is size — keep 400 g (600 g on banana). Sachets, discovery packs, taster bundles, scoops, and estimated tax stay boxed. Cart.js is **GBP** × 1.27 (£26 → $33.02). Pages are additive-free marketing (leave empty); hardcode the one-ingredient unflavoured list.",
    location: "United Kingdom",
    founded: 2014,
    categories: ["protein"],
    accent: "#3D5A2C",
    rating: 4.7,
    reviewCount: 890,
    followerCount: 12000,
    websiteUrl: "https://theorganicproteincompany.co.uk",
    logoUrl: "/brands/organic-protein-company.svg",
  },
  {
    id: "c1424",
    slug: "avocado-zinc",
    name: "Avocado Zinc",
    tagline: "Australian 100% mineral SPF 50 with avocado oil — tinted, body, and glow drops",
    story: "The leftover unused mineral sun house after wave4–91 — reef-safe zinc SPF 50 (clear physical, tinted moisturiser, concealer, bronzer, lip-and-cheek) plus SPF 30 body and SPF 50 glow / bronzing drops. Colour expands tinted, concealer, bronzer, and lip-and-cheek. Bundles, pouches, hats, gift cards, and the SPF brush stay boxed. Cart.js and products.json are **AUD** × 0.65 (A$40 → $26.00). Pages are benefit essays (leave empty).",
    location: "Australia",
    founded: 2018,
    categories: ["sunscreen"],
    accent: "#3F6B3A",
    rating: 4.7,
    reviewCount: 540,
    followerCount: 18000,
    websiteUrl: "https://avocadozinc.com",
    logoUrl: "/brands/avocado-zinc.svg",
  },
  {
    id: "c1425",
    slug: "amallow",
    name: "Amallow",
    tagline: "Cincinnati tallow sun balm, aluminum-free deodorant, dry shampoo, and goat-milk soap",
    story: "The unused Ohio tallow leftover after wave4–91 — grass-fed tallow sun balm with non-nano zinc, aluminum-free deodorant (Scent expands Citrus Blossom / Root & Petal / Everwood / Orange Creamsicle / Unscented), dry shampoo, whipped tallow creams, squeezable lips, and four goat-milk soaps. Quantity / 1-pack vs 3-pack is size. Perfume rollers, candles, leather conditioner, tees, gift cards, sampler deodorant, and every trio/duo/bundle stay boxed. Cart.js is USD. Hardcode the published deodorant, dry-shampoo, sun-balm, lip, and soap lists — whipped-cream pages are farm-story marketing (leave empty).",
    location: "Cincinnati, OH",
    founded: 2023,
    categories: ["deodorant","sunscreen","hair","skincare"],
    accent: "#8B5A3C",
    rating: 4.8,
    reviewCount: 280,
    followerCount: 6400,
    websiteUrl: "https://amallow.com",
    logoUrl: "/brands/amallow.svg",
  },
  {
    id: "c1426",
    slug: "hawaiian-health-co",
    name: "Hawaiian Health Co.",
    tagline: "Kaua‘i electrolytes with Hawaiian sea salt, coconut water, and island lion’s mane",
    story: "The unused Kaua‘i leftover after wave4–91 — Unflavored / Dragonfruit / Passionfruit electrolytes plus mineral drops, pineapple magnesium, lion’s mane extract, and lion’s mane cacao. Flavors already live on titles. The summer bundle stays boxed. Cart.js is USD. Hardcode the published Hawaiian-salt / coconut-water / magnesium-glycinate electrolyte list — cacao and extract pages are farm-story marketing (leave empty).",
    location: "Kīlauea, Kaua‘i",
    founded: 2022,
    categories: ["electrolytes","supplements"],
    accent: "#C45C26",
    rating: 4.7,
    reviewCount: 96,
    followerCount: 2100,
    websiteUrl: "https://hawaiianhealth.co",
    logoUrl: "/brands/hawaiian-health-co.svg",
  },
];
