import type { Brand } from "./types";

/** Wave 9: small organic / toxic-free brands across marketplace categories (c561+). */
export const catalogBrandsWave9: Brand[] = [
  {
    id: "c561",
    slug: "little-urchin",
    name: "Little Urchin",
    tagline: "Reef-safe Australian zinc that started at the daycare gate",
    story: "A Sydney dad watched his kid come home caked in chemical-smelling SPF and built a clear-zinc house instead — organic botanicals, 1% for the Planet, and tinted sticks that skip oxybenzone for the school run and the surf.",
    location: "Sydney, Australia",
    founded: 2016,
    categories: ["sunscreen","skincare"],
    accent: "#E07A3D",
    rating: 4.8,
    reviewCount: 2100,
    followerCount: 18000,
    websiteUrl: "https://www.littleurchin.com.au",
    logoUrl: "/brands/little-urchin.png",
  },
  {
    id: "c562",
    slug: "wotnot",
    name: "Wotnot",
    tagline: "Australia’s refillable clear-zinc sun care for families",
    story: "Sydney-made mineral SPF since 2006 — refillable roll-ons, baby zinc, and sensitive-skin lotions that treat sun care like a refill ritual instead of another plastic bottle in the beach bag.",
    location: "Sydney, Australia",
    founded: 2006,
    categories: ["sunscreen","skincare"],
    accent: "#2A9D8F",
    rating: 4.7,
    reviewCount: 5400,
    followerCount: 42000,
    websiteUrl: "https://www.wotnot.com.au",
    logoUrl: "/brands/wotnot.svg",
  },
  {
    id: "c563",
    slug: "sunslayer",
    name: "Sunslayer",
    tagline: "Refillable mineral SPF50 with a kids’ book about the reef",
    story: "A tiny Australian sun house packing mineral SPF50 into refillable Slayshells and roll-ons — ocean-minded zinc in peach sorbet and dragonfruit tints, plus a storybook about fighting pollution instead of another disposable tube.",
    location: "Australia",
    founded: 2021,
    categories: ["sunscreen"],
    accent: "#F4A261",
    rating: 4.7,
    reviewCount: 380,
    followerCount: 9200,
    websiteUrl: "https://www.sunslayer.co",
    logoUrl: "/brands/sunslayer.svg",
  },
  {
    id: "c564",
    slug: "gnarly",
    name: "Gnarly Nutrition",
    tagline: "NSF outdoor electrolytes and protein for people who earn it outside",
    story: "Salt Lake City sports nutrition built by an outdoor therapist — hydration, whey, and plant protein formulated for heat, altitude, and long days, NSF-certified so the label matches what you actually put in the bottle.",
    location: "Salt Lake City, UT",
    founded: 2014,
    categories: ["electrolytes","protein"],
    accent: "#1B4F72",
    rating: 4.7,
    reviewCount: 3200,
    followerCount: 28000,
    websiteUrl: "https://gognarly.com",
    logoUrl: "/brands/gnarly.png",
  },
  {
    id: "c565",
    slug: "nootrient",
    name: "Nootrient",
    tagline: "Clinician-made whey isolate and electrolyte sticks",
    story: "A psychologist and a physical therapist got tired of chalky tubs — short-list whey isolate and hydration sticks for dancers, creatives, and anyone who wants protein that tastes like food instead of a locker-room shake.",
    location: "United States",
    founded: 2023,
    categories: ["electrolytes","protein"],
    accent: "#5B8C5A",
    rating: 4.8,
    reviewCount: 240,
    followerCount: 4100,
    websiteUrl: "https://nootrient.co",
    logoUrl: "/brands/nootrient.svg",
  },
  {
    id: "c566",
    slug: "nur-protein",
    name: "NUR",
    tagline: "Clear fermented protein plus electrolytes, no milky sludge",
    story: "Two LA founders who couldn’t find a gut-kind protein built Hydration Hero — precision-fermented BLG, electrolytes, and 40-calorie sticks that dissolve clear in water instead of tasting like a milkshake you have to survive.",
    location: "Los Angeles, CA",
    founded: 2025,
    categories: ["protein","electrolytes"],
    accent: "#C45C7A",
    rating: 4.7,
    reviewCount: 160,
    followerCount: 3800,
    websiteUrl: "https://nurprotein.com",
    logoUrl: "/brands/nur-protein.svg",
  },
  {
    id: "c567",
    slug: "jive-nutrition",
    name: "Jive Nutrition",
    tagline: "Clear grass-fed whey isolate with electrolytes built in",
    story: "Protein Hydrator treats a shake like a juice — 22g grass-fed whey isolate, 875mg electrolytes, and zero added sugar in flavors you actually finish, without the chalk, the dye job, or the milky weight.",
    location: "United States",
    founded: 2024,
    categories: ["protein","electrolytes"],
    accent: "#E07A3D",
    rating: 4.6,
    reviewCount: 190,
    followerCount: 2700,
    websiteUrl: "https://jivenu.com",
    logoUrl: "/brands/jive-nutrition.svg",
  },
  {
    id: "c568",
    slug: "bpm-deodorant",
    name: "BPM Deodorant",
    tagline: "Canadian metal-tube deodorant without baking soda or wax",
    story: "Performance-first natural deodorant poured in Canada — magnesium, a recyclable metal tube, and scents like Bergamot & Lime that skip baking soda, heavy waxes, and the plastic stick that usually comes with “clean.”",
    location: "Canada",
    founded: 2024,
    categories: ["deodorant"],
    accent: "#1A1A1A",
    rating: 4.8,
    reviewCount: 210,
    followerCount: 3400,
    websiteUrl: "https://bpmdeodorant.com",
    logoUrl: "/brands/bpm-deodorant.svg",
  },
  {
    id: "c569",
    slug: "finally-all-natural",
    name: "Finally All Natural",
    tagline: "Prebiotic deodorant and body care without the baking-soda sting",
    story: "Aluminum-free, baking-soda-free sticks powered by plant prebiotics, kaolin, and pomegranate oil — plus body butters and belly oil for skin that wants a short, readable list instead of a chemistry set.",
    location: "United States",
    founded: 2021,
    categories: ["deodorant","skincare"],
    accent: "#7B4B94",
    rating: 4.7,
    reviewCount: 860,
    followerCount: 12000,
    websiteUrl: "https://www.finallyallnatural.com",
    logoUrl: "/brands/finally-all-natural.svg",
  },
  {
    id: "c570",
    slug: "by-robin",
    name: "By Robin Creations",
    tagline: "Santa Fe small-batch vegan deodorant, skin, and oral care",
    story: "Robin started with unlabeled camping lip balm and built a two-person Santa Fe workshop — probiotic deodorant in compostable tubes, sulfate-free shampoo, and toothpaste poured in small batches with organic oils and no mystery fillers.",
    location: "Santa Fe, NM",
    founded: 2015,
    categories: ["deodorant","skincare","hair","oral"],
    accent: "#C45C26",
    rating: 4.8,
    reviewCount: 1400,
    followerCount: 8600,
    websiteUrl: "https://www.byrobincreations.com",
    logoUrl: "/brands/by-robin.svg",
  },
  {
    id: "c571",
    slug: "better-and-better",
    name: "Better & Better",
    tagline: "Vitamin-D toothpaste and refillable bamboo brushes",
    story: "Oral care that treats the tube like part of the ritual — Fortify, Purity, and Detoxify pastes plus a bamboo sonic brush you refill instead of tossing, without SLS foam-parties or a plastic mountain under the sink.",
    location: "United States",
    founded: 2019,
    categories: ["oral"],
    accent: "#2D6A4F",
    rating: 4.6,
    reviewCount: 980,
    followerCount: 15000,
    websiteUrl: "https://www.betterandbetter.com",
    logoUrl: "/brands/better-and-better.svg",
  },
  {
    id: "c572",
    slug: "grind-goods",
    name: "Grind Goods",
    tagline: "Hydroxyapatite toothpaste in flavors that are actually fun",
    story: "Micro- and nano-hydroxyapatite plus theobromine from cacao — fluoride-free pastes in Mint Chip, Lemon Love, and Cinnamon Kick that skip peroxide, parabens, sulfates, and the “tastes like a dentist’s office” problem.",
    location: "United States",
    founded: 2022,
    categories: ["oral"],
    accent: "#1A1A1A",
    rating: 4.7,
    reviewCount: 640,
    followerCount: 8900,
    websiteUrl: "https://grindgoods.com",
    logoUrl: "/brands/grind-goods.svg",
  },
  {
    id: "c573",
    slug: "heart-tone",
    name: "Heart Tone Botanicals",
    tagline: "Farm-grown hydroxyapatite toothpaste and botanical hair care",
    story: "JD and Christina grow the botanicals, then pour Living Crystal toothpaste, mouth rinse, and Roots & Locks hair care — farm-to-tube oral care with hydroxyapatite and herbs instead of a lab-only ingredient deck.",
    location: "United States",
    founded: 2018,
    categories: ["oral","hair","skincare"],
    accent: "#6B3E26",
    rating: 4.8,
    reviewCount: 720,
    followerCount: 6400,
    websiteUrl: "https://htbotanicals.com",
    logoUrl: "/brands/heart-tone.svg",
  },
  {
    id: "c574",
    slug: "mukti",
    name: "Mukti Organics",
    tagline: "Certified organic Byron-shire skincare, made on site",
    story: "Mukti has formulated in Mullumbimby since 2000 — certified organic serums, eye crèmes, and native botanicals mixed in the same facility you can visit, with peptides and Australian plants instead of a 40-ingredient mystery cream.",
    location: "Mullumbimby, Australia",
    founded: 2000,
    categories: ["skincare"],
    accent: "#3D6B4F",
    rating: 4.8,
    reviewCount: 4100,
    followerCount: 52000,
    websiteUrl: "https://muktiorganics.com",
    logoUrl: "/brands/mukti.png",
  },
  {
    id: "c575",
    slug: "ere-perez",
    name: "Ere Perez",
    tagline: "Superfood skincare and makeup from a Mexican-Australian kitchen",
    story: "Ere Perez has spent two decades putting quinoa, jojoba, and chia into skin and color — cleanse-and-care kits and botanicals gentle enough for sensitive skin, made without the usual clean-beauty greenwash.",
    location: "Tamarama, Australia",
    founded: 2002,
    categories: ["skincare"],
    accent: "#C4785A",
    rating: 4.7,
    reviewCount: 3600,
    followerCount: 78000,
    websiteUrl: "https://ereperez.com",
    logoUrl: "/brands/ere-perez.png",
  },
  {
    id: "c576",
    slug: "green-people",
    name: "Green People",
    tagline: "Sussex organic sun, skin, hair, and toothpaste since 1997",
    story: "Charlotte Vohtz built a Soil Association organic house in West Sussex after she couldn’t find clean SPF for her child — scent-free mineral sun, age-defy serums, repair shampoo, and minty toothpaste without the supermarket additive stack.",
    location: "West Sussex, United Kingdom",
    founded: 1997,
    categories: ["skincare","sunscreen","hair","oral"],
    accent: "#2E7D32",
    rating: 4.8,
    reviewCount: 8900,
    followerCount: 61000,
    websiteUrl: "https://www.greenpeople.co.uk",
    logoUrl: "/brands/green-people.png",
  },
  {
    id: "c577",
    slug: "oyin",
    name: "Oyin Handmade",
    tagline: "Brooklyn-made moisture for textured hair, poured by hand",
    story: "Jamyla Bennu started in a Brooklyn kitchen in 2001 — honey, oils, and short-list butters for curls, coils, and beards, handmade in small batches without the silicone-slick “moisture” that rinses out in a week.",
    location: "Brooklyn, NY",
    founded: 2001,
    categories: ["hair","skincare"],
    accent: "#8B3A2A",
    rating: 4.8,
    reviewCount: 6700,
    followerCount: 89000,
    websiteUrl: "https://oyinhandmade.com",
    logoUrl: "/brands/oyin.png",
  },
  {
    id: "c578",
    slug: "the-doux",
    name: "The Doux",
    tagline: "Humidity-proof styling for textured hair without the crunch",
    story: "A stylist-built line for curls that actually meet weather — Block Star mousse, wash-day shampoos, and definition gels that skip the helmet-hold plastics and treat textured hair like it lives outside, not under a studio light.",
    location: "United States",
    founded: 2015,
    categories: ["hair"],
    accent: "#F2C94C",
    rating: 4.7,
    reviewCount: 2800,
    followerCount: 46000,
    websiteUrl: "https://thedoux.com",
    logoUrl: "/brands/the-doux.png",
  },
  {
    id: "c579",
    slug: "superfeast",
    name: "SuperFeast",
    tagline: "Di Dao tonic herbs and mushrooms from a Mullumbimby garage",
    story: "Mason Taylor started SuperFeast in his mum’s Sydney garage in 2011, then moved the tonic-herb house to Byron country — dual-extracted reishi, lion’s mane, jing blends, and gynostemma tea grown and sourced the Taoist way, not mycelium-on-oat filler.",
    location: "Mullumbimby, Australia",
    founded: 2011,
    categories: ["supplements"],
    accent: "#5C4033",
    rating: 4.8,
    reviewCount: 5200,
    followerCount: 71000,
    websiteUrl: "https://www.superfeast.com",
    logoUrl: "/brands/superfeast.svg",
  },
  {
    id: "c580",
    slug: "harmonic-arts",
    name: "Harmonic Arts",
    tagline: "Vancouver Island mushroom extracts, mylks, and herbal tonics",
    story: "A Cumberland, BC apothecary pouring chaga tea, 5 Mushroom Cacao, and nettle tinctures — small-batch dual extracts and herbal lattes from the island woods, without a proprietary-blend disappearing act on the label.",
    location: "Cumberland, BC",
    founded: 2010,
    categories: ["supplements"],
    accent: "#3D5A3D",
    rating: 4.8,
    reviewCount: 3100,
    followerCount: 24000,
    websiteUrl: "https://harmonicarts.ca",
    logoUrl: "/brands/harmonic-arts.png",
  },
];
