import type { Brand } from "./types";

/** Wave 76: small organic / toxic-free brands across marketplace categories (c1325+). */
export const catalogBrandsWave76: Brand[] = [
  {
    id: "c1325",
    slug: "mouthology",
    name: "Mouthology",
    tagline: "10% nano-hydroxyapatite toothpaste, tablets, and kids paste without fluoride",
    story: "A US oral house built around 10% nHAp paste in Fresh Mint and Unflavored, plus swallow-safe kids flavors (Watermelon, Strawberry, Subtle Mint), tablets, and Dental Pro tubes. Flavor expands. Pack count is size. Bundles, 3-pack titles, 100-count sample tubes, insured shipping, and toothbrush multi-packs stay boxed. Pages are science-marketing (leave empty unless a real INCI list is published).",
    location: "United States",
    founded: 2022,
    categories: ["oral"],
    accent: "#1F6B63",
    rating: 4.7,
    reviewCount: 890,
    followerCount: 18000,
    websiteUrl: "https://mouthology.com",
    logoUrl: "/brands/mouthology.svg",
  },
  {
    id: "c1326",
    slug: "hydrx",
    name: "Hydrx",
    tagline: "Zero-sugar daily electrolytes in Lemon-Lime, Orange-Pineapple, Watermelon, and Grape",
    story: "A small hydration house skipping sugar and artificial sweeteners — Flavour expands Lemon-Lime / Orange-Pineapple / Watermelon / Grape. The $0 bundle builder stays boxed. Cart.js is USD. Pages are performance-marketing (leave empty unless a real formula is published).",
    location: "United States",
    founded: 2023,
    categories: ["electrolytes"],
    accent: "#2E8F9A",
    rating: 4.6,
    reviewCount: 72,
    followerCount: 2100,
    websiteUrl: "https://hydrxhydration.com",
    logoUrl: "/brands/hydrx.svg",
  },
  {
    id: "c1327",
    slug: "australian-natural-protein",
    name: "Australian Natural Protein Company",
    tagline: "Victorian grass-fed whey in Signature Native, Pure Vanilla Bean, and Organic Artisan Cocoa",
    story: "A Victoria coast whey house sourcing pasture-raised Australian dairy — Signature Native is one-ingredient concentrate; Vanilla Bean and Artisan Cocoa add real food. Flavors already live on separate titles. Kilogram bundles, samples, shakers, and scoops stay boxed. Cart.js is AUD × 0.65. Pages publish short whey lists.",
    location: "Victoria, Australia",
    founded: 2018,
    categories: ["protein"],
    accent: "#C4A35A",
    rating: 4.8,
    reviewCount: 340,
    followerCount: 9200,
    websiteUrl: "https://ausnaturalprotein.com",
    logoUrl: "/brands/australian-natural-protein.svg",
  },
  {
    id: "c1328",
    slug: "pantry",
    name: "Pantry",
    tagline: "Salt Lake City handmade mineral sunscreen, aluminum-free deodorant, and low-waste hair and skin care",
    story: "A Salt Lake City kitchen house pouring non-nano zinc SPF 30, baking-soda-free deodorant, rosemary mint hair bars, and short-list face and body care. Deodorant, soap, lotion, and lip Scent/Flavor expand. Tube vs tin vs oz is size. Candles, tea, pet, laundry, bug spray, menstrual cups, tools, perfume, and gift kits stay boxed. Sunscreen publishes coconut / grapeseed / zinc / beeswax / shea.",
    location: "Salt Lake City, UT",
    founded: 2016,
    categories: ["sunscreen","deodorant","hair","skincare"],
    accent: "#B56B3A",
    rating: 4.8,
    reviewCount: 640,
    followerCount: 15000,
    websiteUrl: "https://shoppantryproducts.com",
    logoUrl: "/brands/pantry.svg",
  },
  {
    id: "c1329",
    slug: "heart-tone",
    name: "Heart Tone Botanicals",
    tagline: "Vero Beach farm-grown Living Crystal toothpaste, bioactive deodorant, and botanical hair and face care",
    story: "A Vero Beach biodynamic farm house making Living Crystal micro-hydroxyapatite toothpaste with theobromine, restorative rinse, oil pulls, bioactive deodorants, Roots & Locks hair, and short-list face creams. Body butter Scent expands. Plastic vs glass is packaging. Kits, household cleaners, dish soap, veggie wash, sample packs, and loofahs stay boxed. Toothpaste and rinse pages publish mineral/botanical lists when a real formula is on the page.",
    location: "Vero Beach, FL",
    founded: 2019,
    categories: ["oral","deodorant","hair","skincare"],
    accent: "#6B3A4A",
    rating: 4.7,
    reviewCount: 210,
    followerCount: 5400,
    websiteUrl: "https://htbotanicals.com",
    logoUrl: "/brands/heart-tone.svg",
  },
  {
    id: "c1330",
    slug: "bristol-fungarium",
    name: "Bristol Fungarium",
    tagline: "Soil Association organic lion's mane, reishi, chaga, and cordyceps tinctures grown in Somerset",
    story: "A Somerset mushroom farm growing and triple-extracting Soil Association organic fruiting bodies — lion's mane, reishi, chaga, cordyceps, maitake, oyster, and shiitake. Bundles, tees, chocolate bars, and cacao drinks stay boxed. Cart.js is GBP × 1.27. Tincture pages publish fruiting-body + alcohol + water when a real formula is listed.",
    location: "Somerset, United Kingdom",
    founded: 2018,
    categories: ["supplements"],
    accent: "#3D5A32",
    rating: 4.8,
    reviewCount: 480,
    followerCount: 12000,
    websiteUrl: "https://fungarium.shop",
    logoUrl: "/brands/bristol-fungarium.svg",
  },
];
