import type { Brand } from "./types";

/** Wave 48: small organic / toxic-free brands across marketplace categories (c1153+). */
export const catalogBrandsWave48: Brand[] = [
  {
    id: "c1153",
    slug: "forah",
    name: "FORAH",
    tagline: "London mineral SPF — zinc surf balm, sun milk, everyday lotion",
    story: "A London mineral-sun house built around non-nano zinc: a surf balm, a concentrated sun milk, and everyday SPF 25/30 lotions, plus a cleansing oil and glow serum. Keep the mineral sunscreens and face formulas. Konjac sponges, travel towels, mesh bags, totes, discovery kits, and gift cards stay packed.",
    location: "London, United Kingdom",
    founded: 2019,
    categories: ["sunscreen","skincare"],
    accent: "#C4A574",
    rating: 4.7,
    reviewCount: 420,
    followerCount: 8900,
    websiteUrl: "https://www.forah.co",
    logoUrl: "/brands/forah.svg",
  },
  {
    id: "c1154",
    slug: "neptune-health",
    name: "Neptune Health",
    tagline: "USA grass-fed tallow mineral SPF 30 — six-ingredient sun care, honey balms",
    story: "A small US tallow house that pairs grass-fed tallow with non-nano zinc for an edible-feeling SPF 30 and a mineral spray, then finishes the ritual with honey and manuka balms, a magnesium cream, and a lip balm. Keep one of each unique sunscreen and balm. Buy-X-get-Y bundles, Trinity packs, shipping protection, and hemp cloths stay boxed.",
    location: "United States",
    founded: 2023,
    categories: ["sunscreen","skincare"],
    accent: "#1B4F72",
    rating: 4.6,
    reviewCount: 310,
    followerCount: 7400,
    websiteUrl: "https://www.neptunehealthco.com",
    logoUrl: "/brands/neptune-health.svg",
  },
  {
    id: "c1155",
    slug: "field-flower-tallow",
    name: "Field Flower Tallow Co.",
    tagline: "Grass-fed tallow cream deodorant, zinc sun-barrier balms, and whipped flowers",
    story: "A US pasture house that hand-whips lifetime grass-fed tallow into cream deodorants (cucumber, honey blossom, desert sage, apricot), unscented and salted-seaside zinc sun-barrier balms, face and body balms, cleansing serums, goat-milk soaps, and flavored lip balms. Individual formulas stay. Bundles, gift bags, gift cards, imperfect 3-packs, and soap samplers stay in the shed. Size options stay as one listing.",
    location: "United States",
    founded: 2023,
    categories: ["deodorant","sunscreen","skincare"],
    accent: "#C47A8A",
    rating: 4.8,
    reviewCount: 180,
    followerCount: 4100,
    websiteUrl: "https://fieldflowertallowco.com",
    logoUrl: "/brands/field-flower-tallow.svg",
  },
  {
    id: "c1156",
    slug: "holycow",
    name: "HolyCow",
    tagline: "Family-rendered grass-fed tallow soap, whipped balm, and peppermint lip",
    story: "A family tallow house that cold-presses grass-fed soap and whips unscented, herb-infused, orange-vanilla, lavender-vanilla, and vanilla-bean balms, plus a peppermint lip. Soap and balm scents expand. Sample sizes, sampler sets, and 4-pack lips stay on the farm.",
    location: "United States",
    founded: 2022,
    categories: ["skincare","hair"],
    accent: "#6B4F2A",
    rating: 4.7,
    reviewCount: 96,
    followerCount: 2800,
    websiteUrl: "https://www.shopholycow.net",
    logoUrl: "/brands/holycow.svg",
  },
  {
    id: "c1157",
    slug: "sote",
    name: "Sote",
    tagline: "Salt of the Earth everyday electrolytes — real-fruit sticks, no merch wall",
    story: "A small hydration house that packs everyday electrolytes into stick packs: orange, tropical hibiscus, strawberry kiwi, watermelon, lemon lime, pink lemonade, grapefruit, chocolate, and unflavored, plus a creatine stick. Flavors are already their own SKUs. Hats, hoodies, merino kits, variety packs, glass bottles, stickers, and gift cards stay in the locker.",
    location: "United States",
    founded: 2024,
    categories: ["electrolytes","supplements"],
    accent: "#1B6B4A",
    rating: 4.6,
    reviewCount: 140,
    followerCount: 3600,
    websiteUrl: "https://drinksote.com",
    logoUrl: "/brands/sote.svg",
  },
  {
    id: "c1158",
    slug: "himalayan-hydration",
    name: "Himalayan Hydration",
    tagline: "Canadian Himalayan-salt electrolyte drink mix — berry, lemon, orange grapefruit",
    story: "A Canadian hydration house that mixes Himalayan salt into a light everyday drink: Mixed Berry, Lemon, and Orange Grapefruit cases. Keep the three flavor cases. Mixed and sampler cases stay boxed. CAD converts to USD.",
    location: "Canada",
    founded: 2023,
    categories: ["electrolytes"],
    accent: "#C45C26",
    rating: 4.5,
    reviewCount: 64,
    followerCount: 1900,
    websiteUrl: "https://himalayanhydration.com",
    logoUrl: "/brands/himalayan-hydration.svg",
  },
];
