import type { Brand } from "./types";

/** Curated clean / natural brands for the marketplace brands section. */
export const catalogBrands: Brand[] = [
  {
    id: "c001",
    slug: "supergoop",
    name: "Supergoop!",
    tagline: "Sunscreen for every day, every body",
    story: "Clean, feel-good SPF formulas that skip the greasy finish — from Unseen Sunscreen to mineral options for faces that live outside.",
    location: "United States",
    founded: 2007,
    categories: ["sunscreen", "skincare"],
    accent: "#F2C94C",
    rating: 4.7,
    reviewCount: 18400,
    followerCount: 92000,
    websiteUrl: "https://supergoop.com",
    logoUrl: "/brands/supergoop.png",
  },
  {
    id: "c002",
    slug: "osea",
    name: "OSEA",
    tagline: "Undaria seaweed skincare from Malibu",
    story: "Ocean-born skincare built around sustainably harvested seaweed, mineral-rich formulas, and a Malibu coastal ritual for skin that wants to glow without the junk.",
    location: "Malibu, CA",
    founded: 1996,
    categories: ["skincare"],
    accent: "#2A9D8F",
    rating: 4.8,
    reviewCount: 22100,
    followerCount: 110000,
    websiteUrl: "https://oseamalibu.com",
    logoUrl: "/brands/osea.png",
  },
  {
    id: "c003",
    slug: "herbivore",
    name: "Herbivore Botanicals",
    tagline: "Plant-powered, short-list skincare",
    story: "Minimalist clean beauty from Seattle — oils, masks, and serums with transparent ingredient lists and botanicals that actually show up on the label.",
    location: "Seattle, WA",
    founded: 2011,
    categories: ["skincare"],
    accent: "#7EB8A2",
    rating: 4.6,
    reviewCount: 15600,
    followerCount: 78000,
    websiteUrl: "https://www.herbivorebotanicals.com",
    logoUrl: "/brands/herbivore.svg",
  },
  {
    id: "c004",
    slug: "youth-to-the-people",
    name: "Youth To The People",
    tagline: "Superfood skincare for city skin",
    story: "Cold-pressed greens and antioxidants in cleansers and serums designed for pollution-exposed, caffeine-fueled skin — clean formulas with a juice-bar vibe.",
    location: "Los Angeles, CA",
    founded: 2016,
    categories: ["skincare"],
    accent: "#3D8B6E",
    rating: 4.7,
    reviewCount: 31200,
    followerCount: 145000,
    websiteUrl: "https://www.youthtothepeople.com",
    logoUrl: "/brands/youth-to-the-people.png",
  },
  {
    id: "c005",
    slug: "tata-harper",
    name: "Tata Harper",
    tagline: "Farm-to-face natural skincare",
    story: "Vermont farm–grown botanicals in clinical-feeling natural formulas — made in small batches with a focus on what goes on your skin and what stays out.",
    location: "Vermont",
    founded: 2010,
    categories: ["skincare"],
    accent: "#C4A484",
    rating: 4.8,
    reviewCount: 9800,
    followerCount: 62000,
    websiteUrl: "https://www.tataharperskincare.com",
    logoUrl: "/brands/tata-harper.png",
  },
  {
    id: "c006",
    slug: "true-botanicals",
    name: "True Botanicals",
    tagline: "Certified organic, high-performance naturals",
    story: "Made Safe–certified and organic-forward skincare that aims for visible results without endocrine disruptors — serums, cleansers, and oils with receipts.",
    location: "Sausalito, CA",
    founded: 2015,
    categories: ["skincare"],
    accent: "#8B7355",
    rating: 4.7,
    reviewCount: 7400,
    followerCount: 41000,
    websiteUrl: "https://truebotanicals.com",
    logoUrl: "/brands/true-botanicals.svg",
  },
  {
    id: "c007",
    slug: "biossance",
    name: "Biossance",
    tagline: "Sugarcane squalane, science-backed clean",
    story: "Biotech beauty from the team behind squalane — plant-derived moisture and clean actives without the petroleum footprint of traditional oils.",
    location: "San Francisco, CA",
    founded: 2017,
    categories: ["skincare"],
    accent: "#5B8A9A",
    rating: 4.6,
    reviewCount: 12800,
    followerCount: 55000,
    websiteUrl: "https://biossance.com",
    logoUrl: "/brands/biossance.png",
  },
  {
    id: "c008",
    slug: "kora-organics",
    name: "KORA Organics",
    tagline: "Certified organic skincare by Miranda Kerr",
    story: "Australia-born organic formulas starring noni extract — cleansers, oils, and creams certified to stay close to plants and far from the usual nasties.",
    location: "Australia",
    founded: 2009,
    categories: ["skincare"],
    accent: "#E8A0BF",
    rating: 4.5,
    reviewCount: 8600,
    followerCount: 88000,
    websiteUrl: "https://www.koraorganics.com",
    logoUrl: "/brands/kora-organics.png",
  },
  {
    id: "c009",
    slug: "drunk-elephant",
    name: "Drunk Elephant",
    tagline: "Compatible clean clinical skincare",
    story: "Skip the suspicious six — Drunk Elephant builds actives-first routines around what plays nice together, with transparent labels and a cult following.",
    location: "Houston, TX",
    founded: 2012,
    categories: ["skincare"],
    accent: "#F4A6C4",
    rating: 4.6,
    reviewCount: 45200,
    followerCount: 210000,
    websiteUrl: "https://www.drunkelephant.com",
    logoUrl: "/brands/drunk-elephant.png",
  },
  {
    id: "c010",
    slug: "ren",
    name: "REN Clean Skincare",
    tagline: "Clean British skincare, recycled packaging",
    story: "London-born clean formulas focused on skin barrier health and ocean-minded packaging — brightening, calming, and daily essentials without the drama.",
    location: "London, UK",
    founded: 2000,
    categories: ["skincare"],
    accent: "#4A90A4",
    rating: 4.6,
    reviewCount: 11200,
    followerCount: 48000,
    websiteUrl: "https://www.renskincare.com",
    logoUrl: "/brands/ren.png",
  },
  {
    id: "c011",
    slug: "jurlique",
    name: "Jurlique",
    tagline: "Biodynamic botanicals from South Australia",
    story: "Farm-grown herbs and flowers in skincare rooted in biodynamic farming — rose, calendula, and herbal extracts for skin that wants plants first.",
    location: "South Australia",
    founded: 1985,
    categories: ["skincare"],
    accent: "#C97B84",
    rating: 4.7,
    reviewCount: 6400,
    followerCount: 32000,
    websiteUrl: "https://www.jurlique.com",
    logoUrl: "/brands/jurlique.png",
  },
  {
    id: "c012",
    slug: "100-percent-pure",
    name: "100% Pure",
    tagline: "Fruit-pigmented clean beauty",
    story: "Fruit and vegetable pigments instead of synthetic dyes — skincare and color with a long list of what they leave out and a short list of what they put in.",
    location: "San Jose, CA",
    founded: 2005,
    categories: ["skincare", "hair"],
    accent: "#E07A5F",
    rating: 4.5,
    reviewCount: 19100,
    followerCount: 67000,
    websiteUrl: "https://www.100percentpure.com",
    logoUrl: "/brands/100-percent-pure.png",
  },
  {
    id: "c013",
    slug: "acure",
    name: "ACURE",
    tagline: "Accessible clean skincare & hair",
    story: "Drugstore-friendly clean formulas that skip sulfates, parabens, and mineral oil — serums, cleansers, and hair care for everyday budgets.",
    location: "Phoenix, AZ",
    founded: 2005,
    categories: ["skincare", "hair"],
    accent: "#6BAA75",
    rating: 4.4,
    reviewCount: 27800,
    followerCount: 54000,
    websiteUrl: "https://acure.com",
    logoUrl: "/brands/acure.png",
  },
  {
    id: "c014",
    slug: "alpyn-beauty",
    name: "Alpyn Beauty",
    tagline: "Wildcrafted alpine skincare",
    story: "Jackson Hole–inspired formulas with wildcrafted Yellowstone yeast and mountain botanicals — clean actives for barrier-first skin.",
    location: "Jackson Hole, WY",
    founded: 2018,
    categories: ["skincare"],
    accent: "#5C7A6E",
    rating: 4.7,
    reviewCount: 3200,
    followerCount: 18000,
    websiteUrl: "https://alpynbeauty.com",
    logoUrl: "/brands/alpyn-beauty.svg",
  },
  {
    id: "c015",
    slug: "versed",
    name: "Versed",
    tagline: "Clean skincare without the markup",
    story: "Target-aisle clean beauty that keeps formulas effective and prices honest — retinoids, moisturizers, and SPF for first-time clean shoppers.",
    location: "Los Angeles, CA",
    founded: 2019,
    categories: ["skincare", "sunscreen"],
    accent: "#F2D0A4",
    rating: 4.5,
    reviewCount: 14500,
    followerCount: 72000,
    websiteUrl: "https://www.versedskin.com",
    logoUrl: "/brands/versed.png",
  },
  {
    id: "c016",
    slug: "byoma",
    name: "Byoma",
    tagline: "Barrier-first skincare for real life",
    story: "Tri-Ceramide Complex formulas aimed at calming and strengthening skin barriers — drugstore-accessible, fragrance-conscious, and routine-simple.",
    location: "United Kingdom",
    founded: 2022,
    categories: ["skincare"],
    accent: "#9BC4BC",
    rating: 4.6,
    reviewCount: 9800,
    followerCount: 61000,
    websiteUrl: "https://byoma.com",
    logoUrl: "/brands/byoma.png",
  },
  {
    id: "c017",
    slug: "the-ordinary",
    name: "The Ordinary",
    tagline: "Clinical formulations with integrity",
    story: "Deciem’s no-fluff clinical actives — niacinamide, acids, and peptides at transparent prices for people who want the ingredient, not the story.",
    location: "Toronto, Canada",
    founded: 2016,
    categories: ["skincare"],
    accent: "#2F2F2F",
    rating: 4.5,
    reviewCount: 89000,
    followerCount: 320000,
    websiteUrl: "https://theordinary.com",
    logoUrl: "/brands/the-ordinary.png",
  },
  {
    id: "c018",
    slug: "paulas-choice",
    name: "Paula's Choice",
    tagline: "Evidence-based skincare, no fluff",
    story: "Dermatologist-minded formulas and ingredient education — BHAs, retinoids, and moisturizers built for people who read the label first.",
    location: "Seattle, WA",
    founded: 1995,
    categories: ["skincare"],
    accent: "#1F4E79",
    rating: 4.7,
    reviewCount: 56000,
    followerCount: 190000,
    websiteUrl: "https://www.paulaschoice.com",
    logoUrl: "/brands/paulas-choice.png",
  },
  {
    id: "c019",
    slug: "cocokind",
    name: "Cocokind",
    tagline: "Thoughtful skincare, soft on skin",
    story: "Accessible clean formulas with a focus on sensitive skin, refill options, and community — ceramide creams, oils, and everyday essentials.",
    location: "San Francisco, CA",
    founded: 2015,
    categories: ["skincare"],
    accent: "#E8B4BC",
    rating: 4.6,
    reviewCount: 18200,
    followerCount: 95000,
    websiteUrl: "https://www.cocokind.com",
    logoUrl: "/brands/cocokind.svg",
  },
  {
    id: "c020",
    slug: "good-molecules",
    name: "Good Molecules",
    tagline: "Targeted treatments, kind prices",
    story: "Straightforward serums and treatments that name the active on the bottle — niacinamide, peptides, and discolouration care without luxury markups.",
    location: "United States",
    founded: 2019,
    categories: ["skincare"],
    accent: "#7BA3A8",
    rating: 4.6,
    reviewCount: 24100,
    followerCount: 88000,
    websiteUrl: "https://goodmolecules.com",
    logoUrl: "/brands/good-molecules.png",
  },
  {
    id: "c021",
    slug: "peach-and-lily",
    name: "Peach & Lily",
    tagline: "Clean K-beauty glass skin rituals",
    story: "Korean skincare favorites curated and created for sensitive-friendly, fragrance-conscious routines — essences, serums, and SPF that layer well.",
    location: "New York, NY",
    founded: 2012,
    categories: ["skincare", "sunscreen"],
    accent: "#F5A9C5",
    rating: 4.7,
    reviewCount: 16300,
    followerCount: 102000,
    websiteUrl: "https://www.peachandlily.com",
    logoUrl: "/brands/peach-and-lily.png",
  },
  {
    id: "c022",
    slug: "krave-beauty",
    name: "Krave Beauty",
    tagline: "Skin barrier care, no overdoing it",
    story: "Founded by a beauty YouTuber who wanted less irritation — gentle cleansers, barrier serums, and sunscreen for skin that’s been through too much.",
    location: "United States",
    founded: 2017,
    categories: ["skincare", "sunscreen"],
    accent: "#C4D7A4",
    rating: 4.7,
    reviewCount: 12100,
    followerCount: 76000,
    websiteUrl: "https://kravebeauty.com",
    logoUrl: "/brands/krave-beauty.svg",
  },
  {
    id: "c023",
    slug: "summer-fridays",
    name: "Summer Fridays",
    tagline: "Soft skin, soft launches",
    story: "Jet-Lag Mask energy turned full clean-leaning lifestyle skincare — lip butter, cloud cream, and SPF for the forever-weekend mood.",
    location: "Los Angeles, CA",
    founded: 2018,
    categories: ["skincare", "sunscreen"],
    accent: "#F0C7A4",
    rating: 4.6,
    reviewCount: 20800,
    followerCount: 134000,
    websiteUrl: "https://www.summerfridays.com",
    logoUrl: "/brands/summer-fridays.png",
  },
  {
    id: "c024",
    slug: "tower-28",
    name: "Tower 28",
    tagline: "Clean beauty for sensitive skin",
    story: "Hypochlorous SOS spray and clean makeup for reactive skin — National Eczema Association–accepted formulas that still feel like fun beauty.",
    location: "Los Angeles, CA",
    founded: 2019,
    categories: ["skincare"],
    accent: "#7EC8E3",
    rating: 4.7,
    reviewCount: 9400,
    followerCount: 81000,
    websiteUrl: "https://tower28beauty.com",
    logoUrl: "/brands/tower-28.svg",
  },
  {
    id: "c025",
    slug: "ilia",
    name: "ILIA",
    tagline: "Clean makeup with mineral SPF",
    story: "Skin-tint culture starters — clean color and multi-tasking SPF formulas that blur the line between skincare and makeup.",
    location: "Laguna Beach, CA",
    founded: 2011,
    categories: ["skincare", "sunscreen"],
    accent: "#D4A574",
    rating: 4.6,
    reviewCount: 15200,
    followerCount: 98000,
    websiteUrl: "https://www.iliabeauty.com",
    logoUrl: "/brands/ilia.svg",
  },
  {
    id: "c026",
    slug: "kosas",
    name: "Kosas",
    tagline: "Clean makeup that skincare-natives trust",
    story: "Revealer concealer energy — clean color cosmetics with skincare actives and a soft-focus finish for people who hate heavy makeup.",
    location: "Los Angeles, CA",
    founded: 2015,
    categories: ["skincare"],
    accent: "#E8A598",
    rating: 4.5,
    reviewCount: 11800,
    followerCount: 89000,
    websiteUrl: "https://kosas.com",
    logoUrl: "/brands/kosas.png",
  },
  {
    id: "c027",
    slug: "saie",
    name: "Saie",
    tagline: "Soft-focus clean makeup",
    story: "Dewy blushes and clean bases for the no-makeup makeup look — lightweight formulas with a calm, skin-first point of view.",
    location: "Los Angeles, CA",
    founded: 2019,
    categories: ["skincare"],
    accent: "#F2C2C2",
    rating: 4.6,
    reviewCount: 8700,
    followerCount: 74000,
    websiteUrl: "https://saiehello.com",
    logoUrl: "/brands/saie.svg",
  },
  {
    id: "c028",
    slug: "merit",
    name: "Merit",
    tagline: "Minimalist clean makeup wardrobe",
    story: "Fewer products, better ones — clean multi-use sticks and bases for a capsule makeup drawer that still feels elevated.",
    location: "Los Angeles, CA",
    founded: 2021,
    categories: ["skincare"],
    accent: "#C9B8A6",
    rating: 4.6,
    reviewCount: 10200,
    followerCount: 112000,
    websiteUrl: "https://www.meritbeauty.com",
    logoUrl: "/brands/merit.png",
  },
  {
    id: "c029",
    slug: "rms-beauty",
    name: "RMS Beauty",
    tagline: "Living oil clean color",
    story: "Creamy, coconut-oil–rooted clean makeup from a pioneer of the category — Living Luminizer and beyond for luminous skin.",
    location: "Los Angeles, CA",
    founded: 2009,
    categories: ["skincare"],
    accent: "#E8D5B7",
    rating: 4.6,
    reviewCount: 7600,
    followerCount: 52000,
    websiteUrl: "https://www.rmsbeauty.com",
    logoUrl: "/brands/rms-beauty.png",
  },
  {
    id: "c030",
    slug: "weleda",
    name: "Weleda",
    tagline: "Natural care since 1921",
    story: "Swiss natural body and skin care with decades of herbal know-how — Skin Food and calendula classics that still feel current.",
    location: "Switzerland",
    founded: 1921,
    categories: ["skincare", "hair"],
    accent: "#E85D04",
    rating: 4.7,
    reviewCount: 33400,
    followerCount: 140000,
    websiteUrl: "https://www.weleda.com",
    logoUrl: "/brands/weleda.png",
  },
  {
    id: "c031",
    slug: "pacifica",
    name: "Pacifica",
    tagline: "Vegan clean beauty for everyone",
    story: "Cruelty-free, vegan formulas across scent, skin, hair, and color — approachable clean beauty with a beachy Portland spirit.",
    location: "Portland, OR",
    founded: 2007,
    categories: ["skincare", "hair"],
    accent: "#00A8A8",
    rating: 4.5,
    reviewCount: 28900,
    followerCount: 97000,
    websiteUrl: "https://www.pacificabeauty.com",
    logoUrl: "/brands/pacifica.png",
  },
  {
    id: "c032",
    slug: "burt-bees",
    name: "Burt's Bees",
    tagline: "Naturally nourishing everyday care",
    story: "Beeswax lip balm that became a natural care staple — body, lip, and face formulas built around simple, recognizable ingredients.",
    location: "Durham, NC",
    founded: 1984,
    categories: ["skincare"],
    accent: "#F4C430",
    rating: 4.6,
    reviewCount: 72000,
    followerCount: 250000,
    websiteUrl: "https://www.burtsbees.com",
    logoUrl: "/brands/burt-bees.png",
  },
  {
    id: "c033",
    slug: "dr-bronner",
    name: "Dr. Bronner's",
    tagline: "All-one soap and clean body care",
    story: "Castile soap legends with peppermint punch — organic oils, fair trade sourcing, and a label you can actually read (in tiny print).",
    location: "Vista, CA",
    founded: 1948,
    categories: ["skincare", "oral", "hair"],
    accent: "#1B4D3E",
    rating: 4.8,
    reviewCount: 41000,
    followerCount: 180000,
    websiteUrl: "https://www.drbronner.com",
    logoUrl: "/brands/dr-bronner.png",
  },
  {
    id: "c034",
    slug: "attitude",
    name: "ATTITUDE",
    tagline: "Plastic-free clean living",
    story: "EWG-verified and often plastic-free personal care — solid bars, mineral SPF, and family formulas for low-waste bathrooms.",
    location: "Montreal, Canada",
    founded: 2009,
    categories: ["skincare", "sunscreen", "hair"],
    accent: "#2D6A4F",
    rating: 4.5,
    reviewCount: 8900,
    followerCount: 28000,
    websiteUrl: "https://attitudeliving.com",
    logoUrl: "/brands/attitude.svg",
  },
  {
    id: "c035",
    slug: "badger",
    name: "Badger Balm",
    tagline: "Organic balms and mineral SPF",
    story: "New Hampshire–made organic balms and zinc sunscreens in tins — simple, certified organic care for outdoorsy skin.",
    location: "Gilsum, NH",
    founded: 1995,
    categories: ["sunscreen", "skincare"],
    accent: "#D97706",
    rating: 4.8,
    reviewCount: 15200,
    followerCount: 34000,
    websiteUrl: "https://www.badgerbalm.com",
    logoUrl: "/brands/badger.png",
  },
  {
    id: "c036",
    slug: "all-good",
    name: "All Good",
    tagline: "Reef-friendly mineral sunscreen",
    story: "Hawaii-rooted mineral SPF and body care for ocean people — zinc formulas meant for surf, sun, and sensitive skin.",
    location: "Hawaii",
    founded: 2011,
    categories: ["sunscreen", "skincare"],
    accent: "#0E7490",
    rating: 4.7,
    reviewCount: 6100,
    followerCount: 22000,
    websiteUrl: "https://allgoodproducts.com",
    logoUrl: "/brands/all-good.png",
  },
  {
    id: "c037",
    slug: "bare-republic",
    name: "Bare Republic",
    tagline: "Mineral sunscreen that feels lighter",
    story: "Sporty mineral SPF sticks and lotions designed to cut the chalk — clean sun care for kids and active days.",
    location: "United States",
    founded: 2013,
    categories: ["sunscreen"],
    accent: "#38BDF8",
    rating: 4.5,
    reviewCount: 9400,
    followerCount: 19000,
    websiteUrl: "https://www.barerepublic.com",
    logoUrl: "/brands/bare-republic.svg",
  },
  {
    id: "c038",
    slug: "thinkbaby",
    name: "Thinkbaby",
    tagline: "Mineral SPF for babies and beyond",
    story: "Pediatrician-minded zinc sunscreens and lotions for the whole family — EWG favorites for sensitive, sun-heavy days.",
    location: "United States",
    founded: 2010,
    categories: ["sunscreen", "skincare"],
    accent: "#FBBF24",
    rating: 4.6,
    reviewCount: 18700,
    followerCount: 41000,
    websiteUrl: "https://www.thinkbaby.com",
    logoUrl: "/brands/thinkbaby.png",
  },
  {
    id: "c039",
    slug: "blue-lizard",
    name: "Blue Lizard",
    tagline: "Mineral sunscreen, color-changing bottle",
    story: "Australian-born mineral SPF with the famous blue bottle that turns color in UV — sensitive-skin formulas for serious sun.",
    location: "Australia / USA",
    founded: 1995,
    categories: ["sunscreen"],
    accent: "#2563EB",
    rating: 4.6,
    reviewCount: 22300,
    followerCount: 38000,
    websiteUrl: "https://www.bluelizardsunscreen.com",
    logoUrl: "/brands/blue-lizard.png",
  },
  {
    id: "c040",
    slug: "coola",
    name: "COOLA",
    tagline: "Organic sunscreen with a lifestyle bent",
    story: "Plant-forward SPF mists, lotions, and sticks — organic ingredients and scents that make reapplication feel less like a chore.",
    location: "San Diego, CA",
    founded: 2008,
    categories: ["sunscreen", "skincare"],
    accent: "#84CC16",
    rating: 4.5,
    reviewCount: 13400,
    followerCount: 67000,
    websiteUrl: "https://www.coola.com",
    logoUrl: "/brands/coola.png",
  },
  {
    id: "c041",
    slug: "sun-bum",
    name: "Sun Bum",
    tagline: "Happy, colorful sun care",
    story: "Bright yellow bottles of SPF, after-sun, and hair care with a surf shop attitude — reef-conscious formulas for beach days.",
    location: "Cocoa Beach, FL",
    founded: 2010,
    categories: ["sunscreen", "hair"],
    accent: "#FACC15",
    rating: 4.6,
    reviewCount: 29800,
    followerCount: 156000,
    websiteUrl: "https://www.sunbum.com",
    logoUrl: "/brands/sun-bum.png",
  },
  {
    id: "c042",
    slug: "kopari",
    name: "Kopari",
    tagline: "Coconut oil clean body care",
    story: "Coconut-obsessed body oils, butters, and clean essentials from a founder who wanted beachy glow without the heavy scent bomb.",
    location: "San Diego, CA",
    founded: 2015,
    categories: ["skincare"],
    accent: "#F5D0C5",
    rating: 4.5,
    reviewCount: 7200,
    followerCount: 58000,
    websiteUrl: "https://www.koparibeauty.com",
    logoUrl: "/brands/kopari.png",
  },
  {
    id: "c043",
    slug: "necessaire",
    name: "Nécessaire",
    tagline: "Clinical body care, clean formulas",
    story: "Body serum and deodorant that treat the body like the face — fragrance-conscious, clinical actives, refillable bottles.",
    location: "New York, NY",
    founded: 2018,
    categories: ["skincare", "deodorant"],
    accent: "#1C1C1C",
    rating: 4.6,
    reviewCount: 8900,
    followerCount: 71000,
    websiteUrl: "https://www.necessaire.com",
    logoUrl: "/brands/necessaire.png",
  },
  {
    id: "c044",
    slug: "native",
    name: "Native",
    tagline: "Naturally derived deodorant that smells good",
    story: "Aluminum-free deodorant with a huge scent library and simple ingredient lists — also expanding into body wash and oral care.",
    location: "San Francisco, CA",
    founded: 2015,
    categories: ["deodorant", "oral", "skincare"],
    accent: "#5B8C5A",
    rating: 4.5,
    reviewCount: 67000,
    followerCount: 210000,
    websiteUrl: "https://www.nativecos.com",
    logoUrl: "/brands/native.png",
  },
  {
    id: "c045",
    slug: "schmidts",
    name: "Schmidt's",
    tagline: "Bold natural deodorant",
    story: "Jar-to-stick natural deodorant pioneers — baking soda and magnesium formulas with strong scents and a cult following.",
    location: "Portland, OR",
    founded: 2010,
    categories: ["deodorant", "oral"],
    accent: "#166534",
    rating: 4.4,
    reviewCount: 42000,
    followerCount: 98000,
    websiteUrl: "https://www.schmidts.com",
    logoUrl: "/brands/schmidts.png",
  },
  {
    id: "c046",
    slug: "each-and-every",
    name: "each & every",
    tagline: "Sensitive-skin natural deodorant",
    story: "Prebiotic deodorant without baking soda or aluminum — built for people who tried natural sticks and got the itch.",
    location: "United States",
    founded: 2018,
    categories: ["deodorant"],
    accent: "#A7C4BC",
    rating: 4.5,
    reviewCount: 5600,
    followerCount: 24000,
    websiteUrl: "https://www.eachandevery.com",
    logoUrl: "/brands/each-and-every.png",
  },
  {
    id: "c047",
    slug: "primally-pure",
    name: "Primally Pure",
    tagline: "Tallow-based natural body care",
    story: "Farm-inspired charcoal deodorant, tallow balms, and herbal body care for people who want ancestral ingredients in modern jars.",
    location: "Temecula, CA",
    founded: 2015,
    categories: ["deodorant", "skincare"],
    accent: "#B08968",
    rating: 4.7,
    reviewCount: 11200,
    followerCount: 64000,
    websiteUrl: "https://primallypure.com",
    logoUrl: "/brands/primally-pure.svg",
  },
  {
    id: "c048",
    slug: "salt-and-stone",
    name: "Salt & Stone",
    tagline: "California natural deodorant & SPF",
    story: "Coastal-inspired natural deodorant and sun care with elevated scents — clean formulas that feel more boutique than basic.",
    location: "California",
    founded: 2016,
    categories: ["deodorant", "sunscreen"],
    accent: "#64748B",
    rating: 4.6,
    reviewCount: 7800,
    followerCount: 45000,
    websiteUrl: "https://saltandstone.com",
    logoUrl: "/brands/salt-and-stone.svg",
  },
  {
    id: "c049",
    slug: "ursa-major",
    name: "Ursa Major",
    tagline: "Fantastic face stuff from Vermont",
    story: "Plant-based face wash, deodorant, and grooming with a outdoorsy Vermont soul — clean formulas for people who hike and hydrate.",
    location: "Vermont",
    founded: 2009,
    categories: ["skincare", "deodorant"],
    accent: "#3F6212",
    rating: 4.6,
    reviewCount: 5400,
    followerCount: 29000,
    websiteUrl: "https://www.ursamajorvt.com",
    logoUrl: "/brands/ursa-major.png",
  },
  {
    id: "c050",
    slug: "meow-meow-tweet",
    name: "Meow Meow Tweet",
    tagline: "Zero-waste clean body care",
    story: "Brooklyn-made baking soda and sensitive deodorants in compostable packaging — queer-owned, plastic-light personal care.",
    location: "Brooklyn, NY",
    founded: 2009,
    categories: ["deodorant", "skincare"],
    accent: "#DB2777",
    rating: 4.5,
    reviewCount: 4100,
    followerCount: 21000,
    websiteUrl: "https://meowmeowtweet.com",
    logoUrl: "/brands/meow-meow-tweet.png",
  },
  {
    id: "c051",
    slug: "hi-bar",
    name: "HiBAR",
    tagline: "Plastic-free shampoo & conditioner bars",
    story: "Solid hair care bars that ditch the bottle — concentrated clean formulas for travel and low-waste showers.",
    location: "United States",
    founded: 2018,
    categories: ["hair"],
    accent: "#0EA5E9",
    rating: 4.5,
    reviewCount: 6800,
    followerCount: 33000,
    websiteUrl: "https://hi-bar.com",
    logoUrl: "/brands/hi-bar.svg",
  },
  {
    id: "c052",
    slug: "ethique",
    name: "Ethique",
    tagline: "Solid bars for hair, skin, and more",
    story: "New Zealand–born concentrated bars that replace bottles — shampoo, conditioner, and body care designed to shrink plastic waste.",
    location: "New Zealand",
    founded: 2012,
    categories: ["hair", "skincare"],
    accent: "#059669",
    rating: 4.6,
    reviewCount: 14300,
    followerCount: 72000,
    websiteUrl: "https://ethique.com",
    logoUrl: "/brands/ethique.svg",
  },
  {
    id: "c053",
    slug: "briogeo",
    name: "Briogeo",
    tagline: "Clean hair care that actually works",
    story: "Don't Despair, Repair! and friends — clean, inclusive hair care for curl patterns and damage repair without silicones galore.",
    location: "New York, NY",
    founded: 2014,
    categories: ["hair"],
    accent: "#F97316",
    rating: 4.6,
    reviewCount: 19800,
    followerCount: 110000,
    websiteUrl: "https://www.briogeo.com",
    logoUrl: "/brands/briogeo.png",
  },
  {
    id: "c054",
    slug: "ouai",
    name: "OUAI",
    tagline: "Hair care for every ouai of life",
    story: "Celebrity stylist–born hair care with clean-leaning formulas and cult leave-ins — scent-forward, schedule-friendly hair rituals.",
    location: "Los Angeles, CA",
    founded: 2016,
    categories: ["hair"],
    accent: "#111827",
    rating: 4.5,
    reviewCount: 24600,
    followerCount: 185000,
    websiteUrl: "https://www.theouai.com",
    logoUrl: "/brands/ouai.png",
  },
  {
    id: "c055",
    slug: "pattern",
    name: "Pattern",
    tagline: "Curl care by Tracee Ellis Ross",
    story: "Texture-first hair care for curls, coils, and tight textures — clean-leaning formulas that celebrate moisture and definition.",
    location: "United States",
    founded: 2019,
    categories: ["hair"],
    accent: "#7C3AED",
    rating: 4.7,
    reviewCount: 16700,
    followerCount: 142000,
    websiteUrl: "https://www.patternbeauty.com",
    logoUrl: "/brands/pattern.svg",
  },
  {
    id: "c056",
    slug: "function-of-beauty",
    name: "Function of Beauty",
    tagline: "Custom clean-leaning hair formulas",
    story: "Personalized shampoo and conditioner built from a quiz — targeted clean-leaning hair care without one-size-fits-all bottles.",
    location: "New York, NY",
    founded: 2016,
    categories: ["hair"],
    accent: "#EC4899",
    rating: 4.4,
    reviewCount: 22100,
    followerCount: 98000,
    websiteUrl: "https://www.functionofbeauty.com",
    logoUrl: "/brands/function-of-beauty.png",
  },
  {
    id: "c057",
    slug: "davines",
    name: "Davines",
    tagline: "Sustainable professional hair care",
    story: "Italian salon formulas with a serious sustainability practice — essential haircare that still feels luxe in the shower.",
    location: "Parma, Italy",
    founded: 1983,
    categories: ["hair"],
    accent: "#15803D",
    rating: 4.7,
    reviewCount: 8900,
    followerCount: 64000,
    websiteUrl: "https://www.davines.com",
    logoUrl: "/brands/davines.png",
  },
  {
    id: "c058",
    slug: "act-and-acre",
    name: "Act+Acre",
    tagline: "Scalp-first clean hair care",
    story: "Cold-processed oils and scalp treatments for hair health from the root — clean formulas for people who treat scalp like skin.",
    location: "New York, NY",
    founded: 2018,
    categories: ["hair"],
    accent: "#78716C",
    rating: 4.6,
    reviewCount: 4300,
    followerCount: 27000,
    websiteUrl: "https://actandacre.com",
    logoUrl: "/brands/act-and-acre.svg",
  },
  {
    id: "c059",
    slug: "risewell",
    name: "RiseWell",
    tagline: "Hydroxyapatite toothpaste, clean oral care",
    story: "Nano-hydroxyapatite toothpaste and oral care without the usual suspects — remineralizing formulas for grown-up bathrooms.",
    location: "United States",
    founded: 2017,
    categories: ["oral"],
    accent: "#F8FAFC",
    rating: 4.6,
    reviewCount: 9200,
    followerCount: 38000,
    websiteUrl: "https://risewell.com",
    logoUrl: "/brands/risewell.svg",
  },
  {
    id: "c060",
    slug: "hello",
    name: "hello",
    tagline: "Naturally friendly oral care",
    story: "Playful toothpaste, mouthwash, and floss with naturally derived ingredients — fluoride and fluoride-free options that don’t taste medicinal.",
    location: "New York, NY",
    founded: 2013,
    categories: ["oral"],
    accent: "#000000",
    rating: 4.5,
    reviewCount: 38000,
    followerCount: 120000,
    websiteUrl: "https://www.hello.com",
    logoUrl: "/brands/hello.png",
  },
  {
    id: "c061",
    slug: "boka",
    name: "Boka",
    tagline: "nHA toothpaste for modern mouths",
    story: "Nano-hydroxyapatite oral care with elevated flavors — clean toothpaste for people rewriting their fluoride routine.",
    location: "United States",
    founded: 2019,
    categories: ["oral"],
    accent: "#0F766E",
    rating: 4.6,
    reviewCount: 11400,
    followerCount: 46000,
    websiteUrl: "https://www.boka.com",
    logoUrl: "/brands/boka.png",
  },
  {
    id: "c062",
    slug: "bite",
    name: "Bite",
    tagline: "Toothpaste bits, plastic-free oral care",
    story: "Chewable toothpaste tablets and refillable oral care — less plastic tubes, still a proper clean feeling after brushing.",
    location: "New York, NY",
    founded: 2018,
    categories: ["oral"],
    accent: "#F43F5E",
    rating: 4.5,
    reviewCount: 15800,
    followerCount: 82000,
    websiteUrl: "https://bitetoothpaste.com",
    logoUrl: "/brands/bite.svg",
  },
  {
    id: "c063",
    slug: "georganics",
    name: "Georganics",
    tagline: "Natural mineral oral care",
    story: "UK natural toothpaste, oils, and powders in glass jars — mineral-based oral care for plastic-light bathroom shelves.",
    location: "United Kingdom",
    founded: 2015,
    categories: ["oral"],
    accent: "#A8A29E",
    rating: 4.5,
    reviewCount: 6100,
    followerCount: 29000,
    websiteUrl: "https://georganics.com",
    logoUrl: "/brands/georganics.png",
  },
  {
    id: "c064",
    slug: "ritual",
    name: "Ritual",
    tagline: "Transparent essential vitamins",
    story: "See-through capsules and traceable ingredients — multivitamins and targeted supplements with a design-forward daily habit.",
    location: "Los Angeles, CA",
    founded: 2015,
    categories: ["supplements"],
    accent: "#111827",
    rating: 4.6,
    reviewCount: 28400,
    followerCount: 160000,
    websiteUrl: "https://ritual.com",
    logoUrl: "/brands/ritual.png",
  },
  {
    id: "c065",
    slug: "athletic-greens",
    name: "AG1",
    tagline: "Daily foundational nutrition",
    story: "One scoop greens-and-nutrient drink for busy routines — foundational vitamins, probiotics, and adaptogens in a travel-ready tin.",
    location: "United States",
    founded: 2010,
    categories: ["supplements", "protein"],
    accent: "#166534",
    rating: 4.5,
    reviewCount: 41000,
    followerCount: 240000,
    websiteUrl: "https://drinkag1.com",
    logoUrl: "/brands/athletic-greens.png",
  },
  {
    id: "c066",
    slug: "hum-nutrition",
    name: "HUM Nutrition",
    tagline: "Personalized clean beauty vitamins",
    story: "Beauty-from-within supplements with quiz-led routines — hair, skin, and stress formulas packaged like a daily ritual.",
    location: "Los Angeles, CA",
    founded: 2012,
    categories: ["supplements"],
    accent: "#BE185D",
    rating: 4.5,
    reviewCount: 17300,
    followerCount: 98000,
    websiteUrl: "https://www.humnutrition.com",
    logoUrl: "/brands/hum-nutrition.png",
  },
  {
    id: "c067",
    slug: "seed",
    name: "Seed",
    tagline: "Synbiotic gut health",
    story: "Daily synbiotic capsules with a sustainability bent — gut and skin axis supplements for people who track their microbiome talk.",
    location: "Los Angeles, CA",
    founded: 2018,
    categories: ["supplements"],
    accent: "#15803D",
    rating: 4.6,
    reviewCount: 12600,
    followerCount: 87000,
    websiteUrl: "https://seed.com",
    logoUrl: "/brands/seed.svg",
  },
  {
    id: "c068",
    slug: "care-of",
    name: "Care/of",
    tagline: "Personalized vitamin packs",
    story: "Quiz-built daily vitamin packs in paper envelopes — targeted supplements without a cabinet full of nearly empty bottles.",
    location: "New York, NY",
    founded: 2016,
    categories: ["supplements"],
    accent: "#F59E0B",
    rating: 4.4,
    reviewCount: 19800,
    followerCount: 76000,
    websiteUrl: "https://www.takecareof.com",
    logoUrl: "/brands/care-of.png",
  },
  {
    id: "c069",
    slug: "golde",
    name: "Golde",
    tagline: "Turmeric lattes and beauty dusts",
    story: "Functional latte blends and skin-forward powders — turmeric, superfoods, and ritual drinks with a bright yellow point of view.",
    location: "Brooklyn, NY",
    founded: 2016,
    categories: ["supplements", "skincare"],
    accent: "#FACC15",
    rating: 4.5,
    reviewCount: 5400,
    followerCount: 72000,
    websiteUrl: "https://www.golde.co",
    logoUrl: "/brands/golde.svg",
  },
  {
    id: "c070",
    slug: "sakara",
    name: "Sakara",
    tagline: "Nutrition programs and beauty foods",
    story: "Plant-rich nutrition and beauty supplements for people who treat meals like skincare — powders, programs, and pantry staples.",
    location: "New York, NY",
    founded: 2012,
    categories: ["supplements", "protein"],
    accent: "#EC4899",
    rating: 4.5,
    reviewCount: 8900,
    followerCount: 110000,
    websiteUrl: "https://www.sakara.com",
    logoUrl: "/brands/sakara.png",
  },
  {
    id: "c071",
    slug: "vital-proteins",
    name: "Vital Proteins",
    tagline: "Collagen for coffee and smoothies",
    story: "Collagen peptides that dissolve into coffee — beauty and joint support powders for the daily mug ritual.",
    location: "United States",
    founded: 2013,
    categories: ["supplements", "protein"],
    accent: "#0EA5E9",
    rating: 4.5,
    reviewCount: 52000,
    followerCount: 198000,
    websiteUrl: "https://www.vitalproteins.com",
    logoUrl: "/brands/vital-proteins.png",
  },
  {
    id: "c072",
    slug: "ancient-nutrition",
    name: "Ancient Nutrition",
    tagline: "Bone broth and multi collagen",
    story: "Collagen, bone broth, and fermented supplements rooted in traditional foods — protein powders with an ancestral tilt.",
    location: "United States",
    founded: 2016,
    categories: ["supplements", "protein"],
    accent: "#92400E",
    rating: 4.5,
    reviewCount: 24600,
    followerCount: 86000,
    websiteUrl: "https://ancientnutrition.com",
    logoUrl: "/brands/ancient-nutrition.png",
  },
  {
    id: "c073",
    slug: "orgain",
    name: "Orgain",
    tagline: "Organic protein for busy days",
    story: "Organic plant and grass-fed protein powders that show up in smoothies and offices — clean-ish macros without chalk city.",
    location: "Irvine, CA",
    founded: 2009,
    categories: ["protein"],
    accent: "#65A30D",
    rating: 4.5,
    reviewCount: 48000,
    followerCount: 132000,
    websiteUrl: "https://www.orgain.com",
    logoUrl: "/brands/orgain.png",
  },
  {
    id: "c074",
    slug: "truvani",
    name: "Truvani",
    tagline: "Plant protein with short labels",
    story: "Plant-based protein with recognizable ingredients — clean powders and bars for people who hate ingredient novels.",
    location: "United States",
    founded: 2019,
    categories: ["protein"],
    accent: "#15803D",
    rating: 4.6,
    reviewCount: 11200,
    followerCount: 54000,
    websiteUrl: "https://truvani.com",
    logoUrl: "/brands/truvani.png",
  },
  {
    id: "c075",
    slug: "laird-superfood",
    name: "Laird Superfood",
    tagline: "Plant-based creamers and fuel",
    story: "Athlete-founded creamers, hydration, and plant fuel — functional pantry staples for coffee, travel, and training days.",
    location: "Sisters, OR",
    founded: 2015,
    categories: ["protein", "electrolytes", "supplements"],
    accent: "#CA8A04",
    rating: 4.5,
    reviewCount: 16700,
    followerCount: 78000,
    websiteUrl: "https://lairdsuperfood.com",
    logoUrl: "/brands/laird-superfood.png",
  },
  {
    id: "c076",
    slug: "liquid-iv",
    name: "Liquid I.V.",
    tagline: "Hydration multiplier electrolytes",
    story: "Cellular Transport Technology electrolyte packets — travel, workout, and hangover hydration in stick packs.",
    location: "United States",
    founded: 2012,
    categories: ["electrolytes"],
    accent: "#F97316",
    rating: 4.6,
    reviewCount: 61000,
    followerCount: 220000,
    websiteUrl: "https://www.liquid-iv.com",
    logoUrl: "/brands/liquid-iv.png",
  },
  {
    id: "c077",
    slug: "lmnt",
    name: "LMNT",
    tagline: "High-sodium electrolyte drink mix",
    story: "No-sugar electrolyte packets with serious sodium for keto, fasting, and sweaty training — bold flavors, simple labels.",
    location: "United States",
    founded: 2018,
    categories: ["electrolytes"],
    accent: "#111827",
    rating: 4.7,
    reviewCount: 28400,
    followerCount: 145000,
    websiteUrl: "https://drinklmnt.com",
    logoUrl: "/brands/lmnt.png",
  },
  {
    id: "c078",
    slug: "nuun",
    name: "Nuun",
    tagline: "Electrolyte tablets for active days",
    story: "Effervescent electrolyte tablets that drop into a water bottle — low-sugar hydration for cycling, running, and desk days.",
    location: "Seattle, WA",
    founded: 2004,
    categories: ["electrolytes"],
    accent: "#0284C7",
    rating: 4.5,
    reviewCount: 19800,
    followerCount: 67000,
    websiteUrl: "https://nuunlife.com",
    logoUrl: "/brands/nuun.png",
  },
  {
    id: "c079",
    slug: "skratch",
    name: "Skratch Labs",
    tagline: "Real-food inspired sports hydration",
    story: "Exercise scientist–built hydration and recovery with real fruit flavors — electrolytes that taste like food, not candy syrup.",
    location: "Boulder, CO",
    founded: 2012,
    categories: ["electrolytes", "protein"],
    accent: "#EA580C",
    rating: 4.7,
    reviewCount: 9200,
    followerCount: 41000,
    websiteUrl: "https://www.skratchlabs.com",
    logoUrl: "/brands/skratch.png",
  },
  {
    id: "c080",
    slug: "ultima-replenisher",
    name: "Ultima Replenisher",
    tagline: "Plant-based electrolyte powder",
    story: "Sugar-free electrolyte drink mixes with stevia and bright flavors — daily hydration without the sports-drink sticky sweet.",
    location: "United States",
    founded: 1991,
    categories: ["electrolytes"],
    accent: "#C026D3",
    rating: 4.6,
    reviewCount: 14300,
    followerCount: 52000,
    websiteUrl: "https://ultimareplenisher.com",
    logoUrl: "/brands/ultima-replenisher.png",
  },
  {
    id: "c081",
    slug: "dripdrop",
    name: "DripDrop",
    tagline: "Medical-grade ORS electrolytes",
    story: "ORS-inspired electrolyte powder for dehydration — used from hospitals to hiking packs when water alone isn’t enough.",
    location: "United States",
    founded: 2010,
    categories: ["electrolytes"],
    accent: "#DC2626",
    rating: 4.6,
    reviewCount: 12100,
    followerCount: 39000,
    websiteUrl: "https://dripdrop.com",
    logoUrl: "/brands/dripdrop.png",
  },
  {
    id: "c082",
    slug: "beautycounter",
    name: "Beautycounter",
    tagline: "Safer products for skin and home",
    story: "Advocacy-minded clean beauty with a Never List — skincare and makeup built around stricter ingredient standards.",
    location: "Santa Monica, CA",
    founded: 2013,
    categories: ["skincare"],
    accent: "#1E3A5F",
    rating: 4.5,
    reviewCount: 16800,
    followerCount: 92000,
    websiteUrl: "https://www.beautycounter.com",
    logoUrl: "/brands/beautycounter.png",
  },
  {
    id: "c083",
    slug: "agent-nateur",
    name: "Agent Nateur",
    tagline: "Luxury clean deodorant & skin",
    story: "Holivood-loved holi(stick) deodorant and skincare — elevated clean formulas with a cult, fragrance-forward following.",
    location: "Los Angeles, CA",
    founded: 2015,
    categories: ["deodorant", "skincare"],
    accent: "#D6D3D1",
    rating: 4.6,
    reviewCount: 5100,
    followerCount: 48000,
    websiteUrl: "https://agentnateur.com",
    logoUrl: "/brands/agent-nateur.png",
  },
  {
    id: "c084",
    slug: "corpus",
    name: "Corpus",
    tagline: "Natural deodorant with designer scents",
    story: "Aluminum-free deodorant with fragrance-house scents — clean sticks that smell like niche perfume, not locker room.",
    location: "Los Angeles, CA",
    founded: 2017,
    categories: ["deodorant"],
    accent: "#44403C",
    rating: 4.5,
    reviewCount: 3600,
    followerCount: 27000,
    websiteUrl: "https://corpusnaturals.com",
    logoUrl: "/brands/corpus.png",
  },
  {
    id: "c085",
    slug: "hanni",
    name: "Hanni",
    tagline: "Bodycare for the in-between spots",
    story: "Ingrown-hair and body-texture care for areas makeup brands ignore — clean-leaning formulas for real bodies.",
    location: "United States",
    founded: 2018,
    categories: ["skincare"],
    accent: "#F472B6",
    rating: 4.5,
    reviewCount: 2800,
    followerCount: 22000,
    websiteUrl: "https://forhanni.com",
    logoUrl: "/brands/hanni.svg",
  },
  {
    id: "c086",
    slug: "dieux",
    name: "Dieux",
    tagline: "Evidence-obsessed clean clinical skin",
    story: "Reusable eye masks and barrier-loving formulas from a science-forward team — less waste, more receipts on actives.",
    location: "New York, NY",
    founded: 2020,
    categories: ["skincare"],
    accent: "#1D4ED8",
    rating: 4.7,
    reviewCount: 6400,
    followerCount: 53000,
    websiteUrl: "https://dieuxskin.com",
    logoUrl: "/brands/dieux.svg",
  },
  {
    id: "c087",
    slug: "topicals",
    name: "Topicals",
    tagline: "Skin solutions for flares & fades",
    story: "Faded serum and like+ culture — targeted treatments for dark spots and irritation with an inclusive, internet-native voice.",
    location: "United States",
    founded: 2020,
    categories: ["skincare"],
    accent: "#F97316",
    rating: 4.6,
    reviewCount: 9800,
    followerCount: 91000,
    websiteUrl: "https://mytopicals.com",
    logoUrl: "/brands/topicals.png",
  },
  {
    id: "c088",
    slug: "glow-recipe",
    name: "Glow Recipe",
    tagline: "Fruit-forward K-beauty glow",
    story: "Watermelon drops and fruit acids for dewy skin — playful clean-leaning Korean-inspired formulas with serious cult status.",
    location: "New York, NY",
    founded: 2014,
    categories: ["skincare"],
    accent: "#FB7185",
    rating: 4.6,
    reviewCount: 27400,
    followerCount: 178000,
    websiteUrl: "https://www.glowrecipe.com",
    logoUrl: "/brands/glow-recipe.png",
  },
  {
    id: "c089",
    slug: "tatcha",
    name: "Tatcha",
    tagline: "Japanese-inspired ritual skincare",
    story: "Hadaka purity and silk-derived formulas — elegant clean-leaning rituals rooted in geisha beauty traditions.",
    location: "San Francisco, CA",
    founded: 2009,
    categories: ["skincare"],
    accent: "#BE123C",
    rating: 4.7,
    reviewCount: 31200,
    followerCount: 165000,
    websiteUrl: "https://www.tatcha.com",
    logoUrl: "/brands/tatcha.png",
  },
  {
    id: "c090",
    slug: "laneige",
    name: "Laneige",
    tagline: "Water science lip & skin care",
    story: "Lip Sleeping Mask fame and hydration-focused Korean skincare — moisture barriers, sleeping masks, and soft lips.",
    location: "South Korea",
    founded: 1994,
    categories: ["skincare"],
    accent: "#38BDF8",
    rating: 4.6,
    reviewCount: 48000,
    followerCount: 210000,
    websiteUrl: "https://www.laneige.com",
    logoUrl: "/brands/laneige.png",
  },
  {
    id: "c091",
    slug: "innisfree",
    name: "Innisfree",
    tagline: "Jeju island green tea skincare",
    story: "Korean nature-inspired skincare from Jeju — green tea, volcanic clusters, and approachable daily essentials.",
    location: "South Korea",
    founded: 2000,
    categories: ["skincare", "sunscreen"],
    accent: "#16A34A",
    rating: 4.5,
    reviewCount: 26500,
    followerCount: 142000,
    websiteUrl: "https://www.innisfree.com",
    logoUrl: "/brands/innisfree.png",
  },
  {
    id: "c092",
    slug: "biore",
    name: "Biore",
    tagline: "UV aqua rich everyday SPF",
    story: "Japanese sunscreen culture in drugstore form — light SPF fluids and cleansing favorites for daily UV habits.",
    location: "Japan",
    founded: 1980,
    categories: ["sunscreen", "skincare"],
    accent: "#2563EB",
    rating: 4.5,
    reviewCount: 33000,
    followerCount: 98000,
    websiteUrl: "https://www.biore.com",
    logoUrl: "/brands/biore.png",
  },
  {
    id: "c093",
    slug: "isdin",
    name: "ISDIN",
    tagline: "Dermatological sun & skin care",
    story: "Spanish pharmacy sunscreens and dermocosmetics — Eryfotona and friends for serious UV and skin health routines.",
    location: "Barcelona, Spain",
    founded: 1975,
    categories: ["sunscreen", "skincare"],
    accent: "#0E7490",
    rating: 4.7,
    reviewCount: 15200,
    followerCount: 64000,
    websiteUrl: "https://www.isdin.com",
    logoUrl: "/brands/isdin.png",
  },
  {
    id: "c094",
    slug: "la-roche-posay",
    name: "La Roche-Posay",
    tagline: "Dermatologist-recommended sensitive care",
    story: "Thermal spring water and Toleriane energy — pharmacy skincare and SPF for reactive, compromised barriers.",
    location: "France",
    founded: 1975,
    categories: ["skincare", "sunscreen"],
    accent: "#0284C7",
    rating: 4.7,
    reviewCount: 72000,
    followerCount: 280000,
    websiteUrl: "https://www.laroche-posay.us",
    logoUrl: "/brands/la-roche-posay.png",
  },
  {
    id: "c095",
    slug: "aveeno",
    name: "Aveeno",
    tagline: "Oat-based gentle skin care",
    story: "Colloidal oatmeal classics for dry and sensitive skin — everyday lotions and face care with a calm, clinical softness.",
    location: "United States",
    founded: 1945,
    categories: ["skincare"],
    accent: "#4D7C0F",
    rating: 4.6,
    reviewCount: 54000,
    followerCount: 190000,
    websiteUrl: "https://www.aveeno.com",
    logoUrl: "/brands/aveeno.png",
  },
  {
    id: "c096",
    slug: "cerave",
    name: "CeraVe",
    tagline: "Ceramides for barrier repair",
    story: "Developed with dermatologists — ceramide moisturizers and cleansers that became the internet’s barrier-repair default.",
    location: "United States",
    founded: 2005,
    categories: ["skincare"],
    accent: "#1D4ED8",
    rating: 4.7,
    reviewCount: 98000,
    followerCount: 310000,
    websiteUrl: "https://www.cerave.com",
    logoUrl: "/brands/cerave.png",
  },
  {
    id: "c097",
    slug: "vanicream",
    name: "Vanicream",
    tagline: "Free-of formulas for sensitive skin",
    story: "Almost-nothing ingredient lists for eczema-prone and reactive skin — free of dyes, fragrance, and the usual irritants.",
    location: "United States",
    founded: 1980,
    categories: ["skincare"],
    accent: "#E2E8F0",
    rating: 4.8,
    reviewCount: 21000,
    followerCount: 47000,
    websiteUrl: "https://www.vanicream.com",
    logoUrl: "/brands/vanicream.png",
  },
  {
    id: "c098",
    slug: "pipette",
    name: "Pipette",
    tagline: "Plant-derived squalane baby & adult care",
    story: "Baby-born formulas with sugarcane squalane that adults stole — gentle cleansers and lotions for sensitive households.",
    location: "United States",
    founded: 2019,
    categories: ["skincare"],
    accent: "#F9A8D4",
    rating: 4.6,
    reviewCount: 7400,
    followerCount: 35000,
    websiteUrl: "https://www.pipettebaby.com",
    logoUrl: "/brands/pipette.png",
  },
  {
    id: "c099",
    slug: "earth-mama",
    name: "Earth Mama",
    tagline: "Herbal care for pregnancy & family",
    story: "Organic herbal body care for pregnancy, postpartum, and babies — calming balms and washes with herbalist roots.",
    location: "Oregon",
    founded: 2002,
    categories: ["skincare"],
    accent: "#B45309",
    rating: 4.8,
    reviewCount: 12800,
    followerCount: 56000,
    websiteUrl: "https://earthmamaorganics.com",
    logoUrl: "/brands/earth-mama.png",
  },
  {
    id: "c100",
    slug: "honest",
    name: "Honest Beauty",
    tagline: "Clean beauty & baby essentials",
    story: "Jessica Alba’s clean beauty and household line — makeup, skin, and baby care with a long Never List and big retail reach.",
    location: "Los Angeles, CA",
    founded: 2012,
    categories: ["skincare", "hair"],
    accent: "#F472B6",
    rating: 4.5,
    reviewCount: 26500,
    followerCount: 148000,
    websiteUrl: "https://www.honest.com",
    logoUrl: "/brands/honest.png",
  }
];
