import type { Brand } from "./types";

/** Wave 82: small organic / toxic-free brands across marketplace categories (c1361+). */
export const catalogBrandsWave82: Brand[] = [
  {
    id: "c1361",
    slug: "barepaste",
    name: "BarePaste",
    tagline: "US 10% nano-hydroxyapatite toothpaste in a single Bare Mint tube",
    story: "A one-SKU American n-HA oral house packing 10% nano-hydroxyapatite with coconut oil, xylitol, and peppermint — fluoride-free, SLS-free, and dye-free. Tube count is size (keep the single 4 oz over the 3-pack). Cart.js is USD. Pages publish a marketing story plus a short Water / silica / glycerin / n-HA list when a real formula is on the page.",
    location: "United States",
    founded: 2023,
    categories: ["oral"],
    accent: "#3F6B5C",
    rating: 4.6,
    reviewCount: 180,
    followerCount: 2400,
    websiteUrl: "https://www.barepaste.com",
    logoUrl: "/brands/barepaste.svg",
  },
  {
    id: "c1362",
    slug: "protocol-performance",
    name: "Protocol Performance",
    tagline: "Grass-fed whey isolate and sugar-free electrolytes without artificial sweeteners",
    story: "A clean-label performance house mixing grass-fed whey isolate and a plant protein with monk-fruit sweetness, plus a zero-sugar electrolyte drink mix. Flavor expands whey Chocolate Pretzel / Chocolate / Vanilla Ice Cream, vegan Chocolate / Vanilla, and electrolytes Orange Sunrise / Raspberry Lime / Watermelon Splash. Serving count is size. Shakers, sling bags, mystery gifts, pre-workout, fat burners, and testosterone boosters stay boxed. Cart.js is USD. Pages publish the short whey / mineral list when a real formula is on the page.",
    location: "United States",
    founded: 2021,
    categories: ["protein","electrolytes"],
    accent: "#2C4A3E",
    rating: 4.6,
    reviewCount: 320,
    followerCount: 4800,
    websiteUrl: "https://protocolperformance.com",
    logoUrl: "/brands/protocol-performance.svg",
  },
  {
    id: "c1363",
    slug: "hope-and-health",
    name: "Hope and Health",
    tagline: "Black Hills tallow deodorant, after-sun lotion, and botanical shampoo bars",
    story: "A South Dakota maker pouring grass-fed tallow deodorant, whipped and unwhipped balms, after-sun lotion, foaming face wash, lip, and a botanical shampoo + conditioner. Deodorant and balm scents already live on separate titles. Shampoo vs conditioner expands; jar oz and dry-shampoo Dark / Light are size or shade. Bundles stay boxed. Cart.js is USD. Pages publish tallow / magnesium / oil lists when a real INCI is on the page.",
    location: "Black Hills, SD",
    founded: 2022,
    categories: ["deodorant","skincare","hair","sunscreen"],
    accent: "#6B4E32",
    rating: 4.8,
    reviewCount: 210,
    followerCount: 3100,
    websiteUrl: "https://hopeandhealth.shop",
    logoUrl: "/brands/hope-and-health.svg",
  },
  {
    id: "c1364",
    slug: "loxy",
    name: "Loxy",
    tagline: "pH-balanced shampoo and conditioner bars plus clean body-wash bars",
    story: "A US zero-waste hair house making pH-balanced vegan shampoo and conditioner bars (Soothe, Relax, Boost, Fortify, Maintain, Tone) plus dry shampoo, collagen body butter, lip balm, and essential-oil body-wash bars. Individual shampoo and conditioner titles already live separately — drop the combo & kits. Dry-shampoo Hair Color expands Light / Brown / Dark; lip and body-butter Scent expand; jar oz is size. Saver bags, travel tins, and starter kits stay boxed. Cart.js is USD. Pages publish oil / surfactant lists when a real INCI is on the page.",
    location: "United States",
    founded: 2020,
    categories: ["hair","skincare"],
    accent: "#7A5A6A",
    rating: 4.7,
    reviewCount: 890,
    followerCount: 12000,
    websiteUrl: "https://loxyhair.com",
    logoUrl: "/brands/loxy.svg",
  },
  {
    id: "c1365",
    slug: "soil-to-soul",
    name: "Soil to Soul",
    tagline: "Farm dual-extract mushroom and herb tinctures without the freeze-dried pantry",
    story: "A small US farm house making dual-extract Lion's Mane, Reishi, Turkey Tail, Chaga, and Cordyceps tinctures plus ashwagandha, milk thistle, dandelion, calendula, turmeric extract, and beet capsules. Bottle oz and capsule count are size. Freeze-dried fruit, ramen toppings, chicken, fire rub, and culinary oils stay boxed. Cart.js is USD. Pages publish fruiting-body + alcohol + water lists when a real formula is on the page.",
    location: "United States",
    founded: 2021,
    categories: ["supplements"],
    accent: "#4A6B3A",
    rating: 4.7,
    reviewCount: 140,
    followerCount: 1800,
    websiteUrl: "https://soiltosoul.us",
    logoUrl: "/brands/soil-to-soul.svg",
  },
  {
    id: "c1366",
    slug: "grizzly-naturals",
    name: "Grizzly Naturals",
    tagline: "Stafford VA aluminum-free deodorant, shampoo bars, and grit soaps for real outdoor days",
    story: "A Virginia workshop pressing aluminum-free baking-soda-free deodorant, palm-oil-free shampoo and conditioner bars, grit soaps, lotions, lip tins, and beard oils in scents like Forest Fresh, Shipwreck Rum, and Cozy Cabin. Hair-care Choose Product expands Shampoo Bar / Conditioner Bar — sets stay boxed. Scents already live on separate deodorant, lotion, soap, and lip titles. Imperfect bars, scrap packs, 3/6/18-packs, dog soap, gift cards, and liquid hand soap stay boxed. Cart.js is USD. Pages publish oil / butter / magnesium lists when a real INCI is on the page.",
    location: "Stafford, VA",
    founded: 2018,
    categories: ["deodorant","hair","skincare"],
    accent: "#3D4F3A",
    rating: 4.8,
    reviewCount: 2400,
    followerCount: 18000,
    websiteUrl: "https://grizzlynaturals.com",
    logoUrl: "/brands/grizzly-naturals.svg",
  },
];
