import type { Brand } from "./types";

/** Wave 77: small organic / toxic-free brands across marketplace categories (c1331+). */
export const catalogBrandsWave77: Brand[] = [
  {
    id: "c1331",
    slug: "chomp",
    name: "Chomp",
    tagline: "Nano-hydroxyapatite toothpaste tablets in Peppermint, Cinnamon, Cool Fruit, and kids Very Berry",
    story: "A Vista, California oral house pressing n-HA toothpaste tablets, mouthwash, and breath sprays so you can skip the plastic tube. Flavors already live on separate titles (Peppermint, Cinnamon, Cool Fruit, Spearmint, JR Very Berry). Pack count and tablet refill vs bottle are size. Electric brushes, water flossers, wholesale, gum, candy, toothbrush combos, and 2/3-packs stay boxed. Pages publish tablet INCI when a real list is on the page.",
    location: "Vista, CA",
    founded: 2018,
    categories: ["oral"],
    accent: "#2C6E5A",
    rating: 4.6,
    reviewCount: 1260,
    followerCount: 22000,
    websiteUrl: "https://chomptoothpaste.com",
    logoUrl: "/brands/chomp.svg",
  },
  {
    id: "c1332",
    slug: "horsepower",
    name: "Horsepower Hydration",
    tagline: "Zero-sugar electrolyte stick packs in Lemon-Lime and Mixed Berry, built for long hot race days",
    story: "A small US hydration house from the dirt-track circuit — Lemon-Lime and Mixed Berry already live on separate titles, 30 sticks is size. No sugar, no merch jugs. Cart.js is USD. Pages are performance-marketing (leave empty unless a real formula is published).",
    location: "United States",
    founded: 2024,
    categories: ["electrolytes"],
    accent: "#C45A2A",
    rating: 4.6,
    reviewCount: 84,
    followerCount: 1900,
    websiteUrl: "https://horsepowerhydration.com",
    logoUrl: "/brands/horsepower.svg",
  },
  {
    id: "c1333",
    slug: "levels",
    name: "Levels",
    tagline: "Jupiter, Florida grass-fed whey, casein, and unflavored collagen with nothing fake",
    story: "A Jupiter whey house built around grass-fed dairy and short labels — Whey Flavor expands Vanilla Bean / Double Chocolate / Pure Chocolate / Chocolate Peanut Butter / Unflavored / Strawberry / Vanilla Cinnamon / Chocolate Mocha / Cappuccino; Casein expands Vanilla Bean / Pure Chocolate. Pound count is size. Duffels, shakers, stickers, funnels, sample packs, and gift cards stay boxed. Cart.js is USD.",
    location: "Jupiter, FL",
    founded: 2015,
    categories: ["protein"],
    accent: "#3D6B4F",
    rating: 4.7,
    reviewCount: 4100,
    followerCount: 38000,
    websiteUrl: "https://levelsprotein.com",
    logoUrl: "/brands/levels.svg",
  },
  {
    id: "c1334",
    slug: "sky-and-sol",
    name: "Sky and Sol",
    tagline: "Six-ingredient mineral tallow SPF 30 and 50 with non-nano zinc, jojoba, beeswax, and propolis",
    story: "A small mineral-sun house pouring non-nano zinc with organic grass-fed tallow, jojoba, beeswax, and propolis — Face & Body, Everyday, Sports, Kids, after-sun, and short-list tallow creams. SPF 30 vs 50 is size. Bundles, custom kits, gift cards, red-light gadgets, tanning oil, 6-packs, and 500 g bulk bags stay boxed. Sunscreen pages publish the six-ingredient zinc list when a real formula is on the page.",
    location: "United States",
    founded: 2023,
    categories: ["sunscreen","skincare","hair"],
    accent: "#C9A24A",
    rating: 4.8,
    reviewCount: 720,
    followerCount: 14000,
    websiteUrl: "https://skyandsol.co",
    logoUrl: "/brands/sky-and-sol.svg",
  },
  {
    id: "c1335",
    slug: "fat-chance-farm",
    name: "Fat Chance Farm",
    tagline: "Vermont tallow-and-lard soap and Farmer Pits aluminum-free deodorant from a working farm",
    story: "A Vermont farm house rendering tallow and lard into cold-process bars, Farmer Pits deodorant, and short-list lip and skin salves. Deodorant, lip, and salve Scent expand. Dish soap, stain sticks, gift sets, soap bags, dishes, mystery packs, labels, and leftover thrifty bars stay boxed. Deodorant publishes tallow / coconut / arrowroot / magnesium / candelilla.",
    location: "Vermont",
    founded: 2016,
    categories: ["deodorant","skincare"],
    accent: "#6B4A2A",
    rating: 4.8,
    reviewCount: 540,
    followerCount: 8700,
    websiteUrl: "https://fatchancesoap.com",
    logoUrl: "/brands/fat-chance-farm.svg",
  },
  {
    id: "c1336",
    slug: "hodgins-harvest",
    name: "Hodgins Harvest",
    tagline: "Upstate New York organic fruiting-body lion's mane, reishi, turkey tail, and cordyceps dual extracts",
    story: "An Upstate New York mushroom farm growing and dual-extracting certified organic fruiting bodies — lion's mane, reishi, turkey tail, cordyceps, and named blends. 2 oz vs 4 oz is size. Grow kits, dried culinary, tees, hoodies, trucker caps, gift cards, and tincture bundles stay boxed. Tincture pages publish fruiting-body + alcohol + water when a real formula is listed.",
    location: "Upstate New York",
    founded: 2019,
    categories: ["supplements"],
    accent: "#3F5A32",
    rating: 4.8,
    reviewCount: 390,
    followerCount: 11000,
    websiteUrl: "https://hodginsharvest.com",
    logoUrl: "/brands/hodgins-harvest.svg",
  },
];
