import type { Brand } from "./types";

/** Wave 97: small organic / toxic-free brands across marketplace categories (c1451+). */
export const catalogBrandsWave97: Brand[] = [
  {
    id: "c1451",
    slug: "clockwork",
    name: "Clockwork",
    tagline: "India-made 10% nanoXIM·CarePaste toothpaste — SCCS-approved n-HA, fluoride-free peppermint and kids pastes",
    story:
      "The leftover unused multi-SKU n-HA oral house after dedicated shops ran out through wave4–96 — parent-founded Clockwork in India. Keep singles of Peppermint 100 g and kids Orange Vanilla / Strawberry Watermelon 80 g. Ritual kits, duos, dentist partner kits, and people-packs stay boxed. Pack / gram count is size. Cart.js is INR (× 0.012). Pages are n-HA essays (leave empty).",
    location: "India",
    founded: 2023,
    categories: ["oral"],
    accent: "#2F4A6B",
    rating: 4.6,
    reviewCount: 210,
    followerCount: 3400,
    websiteUrl: "https://www.clockworkrituals.com",
    logoUrl: "/brands/clockwork.svg",
  },
  {
    id: "c1452",
    slug: "elation-hydration",
    name: "Elation Hydration",
    tagline: "Zero-sugar AM/PM berry electrolytes — allulose and stevia, no sucralose, kid and adult jars",
    story:
      "Leftover unused four-flavor hydration house after wave4–96. Keep Morning Berry, Moon Berry, kids Berry Melon Burst, and Berry Melon Mellow. Family bundles stay boxed. Serving / jar count is size. Cart.js is USD. Pages are key-ingredient essays (leave empty).",
    location: "United States",
    founded: 2023,
    categories: ["electrolytes"],
    accent: "#C45A7A",
    rating: 4.5,
    reviewCount: 88,
    followerCount: 1200,
    websiteUrl: "https://elationhydration.com",
    logoUrl: "/brands/elation-hydration.svg",
  },
  {
    id: "c1453",
    slug: "kono-nutrition",
    name: "KONO Nutrition",
    tagline: "Utah regenerative Irish grass-fed whey isolate and beef protein — unflavored or cacao, no sucralose",
    story:
      "Alex Conley’s unused Health First house. Flavor expands whey Unflavored / Raw Chocolate and beef Madagascar Vanilla / Raw Chocolate; pre-workout Lemons & Limes / Strawberries. Bag vs stick pack is size. Merch, ebooks, tees, hats, frothers, massage guns, gift cards, Route protection, and $0 bundles stay boxed. Cart.js is USD. Hardcode published whey lists — hydrate/pre pages are key-ingredient marketing (leave empty).",
    location: "Utah, USA",
    founded: 2022,
    categories: ["protein", "electrolytes"],
    accent: "#3D5A3A",
    rating: 4.7,
    reviewCount: 156,
    followerCount: 2800,
    websiteUrl: "https://kononutrition.com",
    logoUrl: "/brands/kono-nutrition.svg",
  },
  {
    id: "c1454",
    slug: "mama-sol",
    name: "Mama Sol",
    tagline: "Newport Beach 100% mineral FACEBRELLA, tinted glow serum, and LIPBRELLA — non-nano zinc for mamas",
    story:
      "Arielle Moody and Tahlia Disisto’s 2023 unused mineral sun house. Color expands FACEBRELLA Tints and EYEBRELLA Fair / Light / Medium / Dark; LIPBRELLA Rise / Shine. Keep unscented FACEBRELLA SPF 30. Duos, trios, systems, brushes, gifts, and donations stay boxed. Cart.js is USD. Hardcode the published FACEBRELLA SPF 30 INCI — tint/lip/eye pages are glow-benefit marketing (leave empty).",
    location: "Newport Beach, CA",
    founded: 2023,
    categories: ["sunscreen"],
    accent: "#D4A574",
    rating: 4.8,
    reviewCount: 94,
    followerCount: 4100,
    websiteUrl: "https://www.shopmamasol.com",
    logoUrl: "/brands/mama-sol.svg",
  },
  {
    id: "c1455",
    slug: "rivas-ranch",
    name: "Rivas Ranch",
    tagline: "North Carolina family-farm tallow deodorant, Sun Slayer zinc, whipped balm, and lip — aluminum-free",
    story:
      "Unused Rivas Ranch leftover after wave4–96. Deodorant scents already on separate titles; Flavor expands lip Cocoa / Strawberry / Cherry Ice / Creamsicle / Pina Colada / Naked / Vanilla Mint; Scent expands Tallow Dots. 4 oz / 8 oz is size. Halal dupes of the same scent, 3-packs, and 6-packs stay boxed. Cart.js is USD. Hardcode published deodorant and lip lists — sun/whip pages are farm-story marketing (leave empty).",
    location: "North Carolina, USA",
    founded: 2021,
    categories: ["deodorant", "skincare", "sunscreen"],
    accent: "#8B5A2B",
    rating: 4.8,
    reviewCount: 240,
    followerCount: 3600,
    websiteUrl: "https://grassfedtallowproducts.com",
    logoUrl: "/brands/rivas-ranch.svg",
  },
  {
    id: "c1456",
    slug: "feral-fungi",
    name: "Feral Fungi",
    tagline: "Estacada Oregon wild and US-grown fruiting-body spagyric tinctures — lion's mane, reishi, chaga, cordyceps",
    story:
      "Jason Scott’s 2016 leftover unused Oregon extract house. Keep single-mushroom extracts, spagyric essences, Myco blend tinctures, and functional gummies. 1 oz / 2 oz / 4 oz / 10 ml is size. Bundles, sets, coffee, gift cards, and the free reference guide stay boxed. Cart.js is USD. Pages are alchemy-process essays (leave empty).",
    location: "Estacada, OR",
    founded: 2016,
    categories: ["supplements"],
    accent: "#4A5C32",
    rating: 4.9,
    reviewCount: 320,
    followerCount: 5400,
    websiteUrl: "https://feralfungi.com",
    logoUrl: "/brands/feral-fungi.svg",
  }
];
