import type { Brand } from "./types";

/** Wave 41: small organic / toxic-free brands across marketplace categories (c1086+). */
export const catalogBrandsWave41: Brand[] = [
  {
    id: "c1086",
    slug: "himaya",
    name: "Himaya",
    tagline: "Irish mineral zinc SPF 30 and 50+ for ocean and mountain days — refillable, no chemical-filter wall",
    story: "An Ireland-born sports sunscreen house that has poured non-nano zinc into reef-safe SPF 30 and 50+ lotions and a pocket stick since 2002, instead of a chemical-filter aisle. Refillable 50ml and 200ml bottles stay. EUR prices convert to USD. No merch, no self-tan.",
    location: "Ireland",
    founded: 2002,
    categories: ["sunscreen"],
    accent: "#1F6B5B",
    rating: 4.7,
    reviewCount: 380,
    followerCount: 6200,
    websiteUrl: "https://himaya.com",
    logoUrl: "/brands/himaya.svg",
  },
  {
    id: "c1087",
    slug: "miococo",
    name: "MIOCOCO",
    tagline: "Women's grass-fed whey and electrolyte drink mixes — vanilla bean, cocoa sea salt, lemon lime, no blender shop",
    story: "A clean-stack house that keeps grass-fed whey isolate, a vanilla-bean vegan protein, and four electrolyte drink mixes instead of a sucralose-and-dye tub wall. Whey, vegan protein, electrolytes, and the cranberry-grape debloat powder stay. The electric blender wand stays out.",
    location: "United States",
    founded: 2022,
    categories: ["protein","electrolytes","supplements"],
    accent: "#C45C7A",
    rating: 4.6,
    reviewCount: 210,
    followerCount: 4800,
    websiteUrl: "https://miococo.com",
    logoUrl: "/brands/miococo.svg",
  },
  {
    id: "c1088",
    slug: "natch-labs",
    name: "Natch Labs",
    tagline: "German postbiotic toothpaste and mouthwash tablets — Dr. Shaman, Wake-Up Call, Boombastic, no gadget shop",
    story: "A Berlin oral house that presses postbiotic toothpaste and mouthwash into refillable tablet bottles instead of a fluoride-and-SLS tube wall. Individual formulas stay, including kids Tooth Monster and copper tongue care. UK duplicate listings, gift cards, and sampler travel kits stay out. EUR prices convert to USD.",
    location: "Berlin, Germany",
    founded: 2021,
    categories: ["oral"],
    accent: "#2C6E49",
    rating: 4.6,
    reviewCount: 890,
    followerCount: 14000,
    websiteUrl: "https://natchlabs.com",
    logoUrl: "/brands/natch-labs.svg",
  },
  {
    id: "c1089",
    slug: "yamabushi-farms",
    name: "Yamabushi Farms",
    tagline: "Los Angeles farm lion's mane — MEZAME tincture, powder, capsules, no merch wall",
    story: "A Los Angeles mushroom farm that dual-extracts the same hardwood-grown lion's mane it sells to kitchens, then bottles MEZAME, IBUKI, and MAMORU instead of a mycelium-on-grain capsule wall. Tinctures, powder, and capsules stay. Bandanas, tees, and tea stay on the farm.",
    location: "Los Angeles, California",
    founded: 2021,
    categories: ["supplements"],
    accent: "#4A6741",
    rating: 4.8,
    reviewCount: 90,
    followerCount: 2100,
    websiteUrl: "https://yamabushifarms.com",
    logoUrl: "/brands/yamabushi-farms.svg",
  },
  {
    id: "c1090",
    slug: "tilted-cap",
    name: "Tilted Cap Mushrooms",
    tagline: "Eastern North Carolina farm dual-extract tinctures — lion's mane, reishi, turkey tail, no bundle wall",
    story: "A small Eastern North Carolina farm that dual-extracts its own fruiting-body lion's mane, reishi, and turkey tail in-house instead of a grow-kit-and-spawn shop. Three tinctures stay. The daily wellness bundle stays out.",
    location: "Eastern North Carolina",
    founded: 2022,
    categories: ["supplements"],
    accent: "#5C4033",
    rating: 4.6,
    reviewCount: 42,
    followerCount: 800,
    websiteUrl: "https://tiltedcapllc.com",
    logoUrl: "/brands/tilted-cap.svg",
  },
  {
    id: "c1091",
    slug: "hodgins-harvest",
    name: "Hodgins Harvest",
    tagline: "Certified-organic Upstate New York fruiting-body tinctures — lion's mane, reishi, turkey tail, cordyceps",
    story: "A certified-organic Orange County, New York mushroom farm that dual-extracts only fruiting bodies grown on the farm instead of imported mycelium powder. Single and paired tinctures stay. Grow kits, dried culinary mushrooms, hoodies, and trucker caps stay on the farm.",
    location: "Orange County, New York",
    founded: 2019,
    categories: ["supplements"],
    accent: "#3D5A3A",
    rating: 4.7,
    reviewCount: 160,
    followerCount: 3400,
    websiteUrl: "https://hodginsharvest.com",
    logoUrl: "/brands/hodgins-harvest.svg",
  },
  {
    id: "c1092",
    slug: "hearth-and-hide",
    name: "Hearth & Hide",
    tagline: "Mackenzie Country farm-to-skin tallow — lamb balms and Golden Peaks lip, no merch wall",
    story: "A New Zealand high-country house that renders Cloudy Peaks Station tallow back on the farm into lamb balms and three lip balms instead of a synthetic-moisturizer wall. Homestead, Shepherd's, Alpine, Wild Earth, and citrus balms stay. NZD prices convert to USD. No merch, no candles.",
    location: "Mackenzie Country, New Zealand",
    founded: 2024,
    categories: ["skincare"],
    accent: "#6B4F2A",
    rating: 4.7,
    reviewCount: 55,
    followerCount: 1100,
    websiteUrl: "https://hearthandhide.co.nz",
    logoUrl: "/brands/hearth-and-hide.svg",
  },
  {
    id: "c1093",
    slug: "greene-grass-tallow",
    name: "Greene Grass Tallow",
    tagline: "Wisconsin kitchen-rendered whipped tallow — frankincense, lavender honey, vanilla, no cooking-jar shop",
    story: "A Wisconsin family kitchen that hand-renders local suet into unscented-adjacent whipped butters with frankincense, lavender honey, coffee vanilla, and a propolis lip instead of a synthetic-fragrance lotion wall. Whipped butters and the lip balm stay. Cooking tallow jars stay out.",
    location: "Wisconsin, United States",
    founded: 2023,
    categories: ["skincare"],
    accent: "#6B3E26",
    rating: 4.6,
    reviewCount: 70,
    followerCount: 1500,
    websiteUrl: "https://greenegrasstallow.com",
    logoUrl: "/brands/greene-grass-tallow.svg",
  },
  {
    id: "c1094",
    slug: "hide-tallow",
    name: "Hide Tallow Co.",
    tagline: "Scottsdale grass-fed whipped tallow — lavender, lemongrass, vanilla, unscented, no waitlist wall",
    story: "A Scottsdale tallow kitchen that triple-purifies regenerative Delaware suet into glass jars, pocket sticks, travel tins, and a daily soap bar instead of a petroleum cream aisle. Lavender, lemongrass, vanilla, and unscented stay as their own listings. Zero-price waitlist SKUs stay out.",
    location: "Scottsdale, Arizona",
    founded: 2023,
    categories: ["skincare"],
    accent: "#8B5A2B",
    rating: 4.6,
    reviewCount: 85,
    followerCount: 1900,
    websiteUrl: "https://hidetallow.com",
    logoUrl: "/brands/hide-tallow.svg",
  },
  {
    id: "c1095",
    slug: "fat-chance-farm",
    name: "Fat Chance Farm",
    tagline: "Vermont tallow deodorant and soap — Farmer Pits scents, aluminum-free, no dish-soap shop",
    story: "A Vermont farm soap shop that pours grass-fed tallow into aluminum-free Farmer Pits deodorant bars and push-up tubes, plus short-list tallow soaps and lip balms. Cedar-thyme, lavender-geranium, lemongrass, and unscented stay as their own listings. Soap dishes, stain sticks, dish soap, and gift-card kits stay out.",
    location: "Vermont, United States",
    founded: 2018,
    categories: ["deodorant","skincare"],
    accent: "#7A5C3A",
    rating: 4.7,
    reviewCount: 240,
    followerCount: 3600,
    websiteUrl: "https://fatchancesoap.com",
    logoUrl: "/brands/fat-chance-farm.svg",
  },
  {
    id: "c1096",
    slug: "bearsville",
    name: "Bearsville Soap Company",
    tagline: "Hudson Valley aluminum-free deodorant plus shampoo bars — scent SKUs, no candle shop",
    story: "A Hudson Valley cold-process house that keeps aluminum-free deodorant, daily moisturizer, shampoo and conditioner bars, and beard oil instead of a paraffin-and-cologne wall. Individual scent formulas stay. Candles, cologne, gift cards, and bundle stacks stay out.",
    location: "Hudson Valley, New York",
    founded: 2016,
    categories: ["deodorant","skincare","hair"],
    accent: "#3D4F3A",
    rating: 4.6,
    reviewCount: 520,
    followerCount: 8900,
    websiteUrl: "https://bearsvillesoaps.com",
    logoUrl: "/brands/bearsville.svg",
  },
  {
    id: "c1097",
    slug: "my-neighbors-tallow",
    name: "My Neighbor's Tallow",
    tagline: "Hudson Valley regenerative tallow — Blue Moon balm, rose lip, rosemary hair oil, no scarf shop",
    story: "A Hudson Valley house that renders local grass-fed suet into Blue Moon and Wild Bergamot balms, rose lips, collagen-cleanser soap, and a rosemary-juniper hair oil instead of a general-store merch wall. Balms, soaps, serum, body wash, and hair oil stay. Scarves, journals, calendars, candles, and leather bags stay out.",
    location: "Hudson Valley, New York",
    founded: 2022,
    categories: ["skincare","hair"],
    accent: "#5C4033",
    rating: 4.7,
    reviewCount: 110,
    followerCount: 2400,
    websiteUrl: "https://myneighborstallow.com",
    logoUrl: "/brands/my-neighbors-tallow.svg",
  },
];
