import type { Brand } from "./types";

/** Wave 28: small organic / toxic-free brands across marketplace categories (c921+). */
export const catalogBrandsWave28: Brand[] = [
  {
    id: "c921",
    slug: "heaven-tallow",
    name: "Heaven Tallow",
    tagline: "Organic tallow SPF 50 and bergamot deodorant — six-ingredient sticks, no aluminum dump",
    story: "A US tallow kitchen that puts non-nano zinc in grass-fed fat for an organic SPF 50++ sun stick, then pours a six-ingredient bergamot deodorant instead of an aluminum antiperspirant. Sun sticks, deodorant, soap, and lip balm stay. Methylene-blue peptide serums and VIP merch stay in the lab drawer.",
    location: "United States",
    founded: 2023,
    categories: ["sunscreen","deodorant","skincare"],
    accent: "#C4A35A",
    rating: 4.8,
    reviewCount: 210,
    followerCount: 3400,
    websiteUrl: "https://www.heaventallow.com",
    logoUrl: "/brands/heaven-tallow.svg",
  },
  {
    id: "c922",
    slug: "wellness-and-wildflowers",
    name: "Wellness and Wildflowers",
    tagline: "Four-ingredient mineral sunscreen — tallow, zinc, no chemical-filter cocktail",
    story: "A tiny US apothecary that keeps sun care to coconut oil, grass-fed tallow, non-nano zinc, and beeswax. The Safe Sunscreen ~30+ SPF stays. Healing balms and salves stay. No merch aisle.",
    location: "United States",
    founded: 2021,
    categories: ["sunscreen","skincare"],
    accent: "#6B8F71",
    rating: 4.7,
    reviewCount: 90,
    followerCount: 1100,
    websiteUrl: "https://wellnessandwildflowers.com",
    logoUrl: "/brands/wellness-and-wildflowers.svg",
  },
  {
    id: "c923",
    slug: "jr-ranch",
    name: "Johnson Reservoir Ranch",
    tagline: "Ranch-made tallow sunscreen and deodorant — short lists, no petroleum cream",
    story: "A working ranch kitchen that twists tallow sunscreen into a stick and pours an all-natural tallow deodorant by hand. Magnesium whipped balms and honey moisturizer stay. Tattoo salve stays as skincare. Empty packaging stays out.",
    location: "United States",
    founded: 2022,
    categories: ["sunscreen","deodorant","skincare"],
    accent: "#8B5A2B",
    rating: 4.6,
    reviewCount: 70,
    followerCount: 800,
    websiteUrl: "https://jrranch.myshopify.com",
    logoUrl: "/brands/jr-ranch.svg",
  },
  {
    id: "c924",
    slug: "rawvelo",
    name: "Rawvelo",
    tagline: "Organic hydration and recovery mixes — coconut water, pea protein, no neon sport dye",
    story: "A UK endurance kitchen that flavors hydration sachets with real fruit and mixes organic pea protein into a recovery drink instead of a candy-aisle tub. Lemon and raspberry hydration stay as their own listings. Recovery drink mix stays. Water bottles and energy-bar merch stay in the kit bag.",
    location: "United Kingdom",
    founded: 2018,
    categories: ["electrolytes","protein"],
    accent: "#C45C26",
    rating: 4.7,
    reviewCount: 420,
    followerCount: 5600,
    websiteUrl: "https://www.rawvelo.com",
    logoUrl: "/brands/rawvelo.svg",
  },
  {
    id: "c925",
    slug: "clockwork-rituals",
    name: "Clockwork Rituals",
    tagline: "Clinical-grade nano-hydroxyapatite toothpaste — no fluoride, no SLS foam circus",
    story: "Two founders who sourced Portuguese nanoXIM hydroxyapatite and 10% organic xylitol instead of a neon fluoride gel. Peppermint, orange-vanilla, and strawberry-watermelon stay as their own listings. Kids nHAP pastes stay. Dentist kits stay when they are the same formulas.",
    location: "Independent / DTC",
    founded: 2024,
    categories: ["oral"],
    accent: "#2C5F4E",
    rating: 4.8,
    reviewCount: 180,
    followerCount: 2700,
    websiteUrl: "https://www.clockworkrituals.com",
    logoUrl: "/brands/clockwork-rituals.svg",
  },
  {
    id: "c926",
    slug: "the-humble-co",
    name: "The Humble Co.",
    tagline: "Swedish plant-based oral care — COSMOS toothpaste, bamboo brushes, no plastic-tube guilt",
    story: "A Stockholm house that still makes plant-based toothbrushes and COSMOS-certified pastes in recyclable aluminum instead of a supermarket plastic tube. Fresh mint, sensitive, whitening, and kids strawberry stay as their own listings. Floss and tongue scrapers stay. Mouthwash cups stay in the merch drawer.",
    location: "Stockholm, Sweden",
    founded: 2013,
    categories: ["oral"],
    accent: "#3D8B6E",
    rating: 4.6,
    reviewCount: 2400,
    followerCount: 32000,
    websiteUrl: "https://www.thehumble.co",
    logoUrl: "/brands/the-humble-co.svg",
  },
  {
    id: "c927",
    slug: "jack-n-jill",
    name: "Jack N' Jill",
    tagline: "Certified natural kids toothpaste — real fruit flavors, no SLS foam circus",
    story: "An Australian family oral-care house that certifies kids pastes with real fruit flavors instead of a candy-aisle gel. Watermelon, apple, strawberry, blueberry, and berries-and-cream stay as their own listings. Flossers and toothbrushes stay. Bath toys and cotton face masks stay in the play drawer.",
    location: "Australia",
    founded: 2007,
    categories: ["oral","hair","skincare"],
    accent: "#E07A5F",
    rating: 4.7,
    reviewCount: 1600,
    followerCount: 18000,
    websiteUrl: "https://www.jackandjillkids.com",
    logoUrl: "/brands/jack-n-jill.svg",
  },
  {
    id: "c928",
    slug: "pestle-and-mortar",
    name: "Pestle & Mortar",
    tagline: "Irish clean skincare — short, readable formulas, no 40-ingredient cream",
    story: "A Dublin-born house that still writes short INCI lists for hydrate creams, hyaluronic serums, and clay masks. Face, body, and hand care stay. Face cloths and GWP testers stay out when they are empty accessories.",
    location: "Ireland",
    founded: 2014,
    categories: ["skincare"],
    accent: "#B76E79",
    rating: 4.7,
    reviewCount: 890,
    followerCount: 14000,
    websiteUrl: "https://www.pestleandmortar.com",
    logoUrl: "/brands/pestle-and-mortar.svg",
  },
  {
    id: "c929",
    slug: "lumera-morel",
    name: "Lumera Morel",
    tagline: "Wild-foraged mushroom skincare — glycerin extracts, no essential-oil dump",
    story: "A new US kitchen that slow-extracts wild morels, reishi, and tremella in glycerin for reactive skin instead of an alcohol toner. The Fun-gal Revival cleanser and Adaptogenic Renewal moisturizer stay. Tools stay out.",
    location: "United States",
    founded: 2025,
    categories: ["skincare"],
    accent: "#4A5D23",
    rating: 4.8,
    reviewCount: 40,
    followerCount: 600,
    websiteUrl: "https://lumeramorel.com",
    logoUrl: "/brands/lumera-morel.svg",
  },
  {
    id: "c930",
    slug: "wild-crafted-kitchen",
    name: "Wild Crafted Kitchen",
    tagline: "Minnesota tallow kitchen — aluminum-free deodorant, zinc sun balm, no fragrance-oil dump",
    story: "A Minnesota homestead that renders tallow for face balms, then pours an aluminum-free deodorant and a zinc sun balm instead of a drugstore stick. Lotion scent variants stay as their own listings. Hair oil stays. Bug balm, dish soap, and paw balm stay in the barn.",
    location: "Minnesota, United States",
    founded: 2021,
    categories: ["skincare","deodorant","sunscreen"],
    accent: "#5B7A3A",
    rating: 4.8,
    reviewCount: 260,
    followerCount: 3900,
    websiteUrl: "https://wildcraftedkitchenmn.myshopify.com",
    logoUrl: "/brands/wild-crafted-kitchen.svg",
  },
  {
    id: "c931",
    slug: "holmestyle",
    name: "HolmeStyle",
    tagline: "Bison tallow deodorant and soap — small-batch homestead bars, no aluminum stick",
    story: "A homestead kitchen that blends bison tallow into an aluminum-free deodorant and pours scent-forward soap bars by hand. Deodorant stays. Soap scent variants stay as their own listings. Pup scrub, socks, and mason-jar candles stay in the merch drawer.",
    location: "United States",
    founded: 2020,
    categories: ["deodorant","skincare"],
    accent: "#6B3E26",
    rating: 4.7,
    reviewCount: 150,
    followerCount: 2200,
    websiteUrl: "https://holmestylehomestead.myshopify.com",
    logoUrl: "/brands/holmestyle.svg",
  },
  {
    id: "c932",
    slug: "jessicurl",
    name: "Jessicurl",
    tagline: "California curl care — fragrance-free options, no silicone slip",
    story: "A long-running California curl house that still mixes Rockin' Ringlets and Gelebration Spray without a dimethicone serum. Shampoo, conditioner, and styling potions stay. Scent variants stay as their own listings. Shower caps, pillowcases, and towels stay in the merch drawer.",
    location: "Arcata, California",
    founded: 2004,
    categories: ["hair"],
    accent: "#7B3F6E",
    rating: 4.6,
    reviewCount: 3100,
    followerCount: 28000,
    websiteUrl: "https://jessicurl.com",
    logoUrl: "/brands/jessicurl.svg",
  },
  {
    id: "c933",
    slug: "boucleme",
    name: "Bouclème",
    tagline: "British curl care — 95% natural formulas, no silicone, no drying alcohol",
    story: "A UK curl kitchen that keeps shampoo, conditioner, and curl creams at 95% natural origin instead of a silicone smoothie. Hydration and hold formulas stay. Scent and size options stay when they are real variants. Brushes stay out.",
    location: "United Kingdom",
    founded: 2014,
    categories: ["hair"],
    accent: "#1B4F72",
    rating: 4.7,
    reviewCount: 2200,
    followerCount: 41000,
    websiteUrl: "https://www.boucleme.co.uk",
    logoUrl: "/brands/boucleme.svg",
  },
  {
    id: "c934",
    slug: "zerean",
    name: "Zerean",
    tagline: "Functional-mushroom beauty gummies — reishi and lion's mane, no candy-aisle biotin jar",
    story: "A small US lab that pairs biotin with reishi and lion's mane instead of a one-note beauty gummy. Flow, Bloom, Luna, Balance, and Flexa stay as their own listings. Merch stays out.",
    location: "United States",
    founded: 2024,
    categories: ["supplements"],
    accent: "#3D5A3D",
    rating: 4.7,
    reviewCount: 80,
    followerCount: 1400,
    websiteUrl: "https://www.zereanlabs.com",
    logoUrl: "/brands/zerean.svg",
  },
  {
    id: "c935",
    slug: "earthling-mushroom-farm",
    name: "Earthling Mushroom Farm",
    tagline: "US farm mushroom capsules and gummies — fruiting-body extracts, no grain-filler mycelium aisle",
    story: "A working mushroom farm that extracts lion's mane, reishi, and cordyceps for capsules and gummies instead of a mycelium-on-oats tub. The stack, capsules, and extra-strength gummies stay. Fresh culinary boxes, farm tours, and seltzers stay on the farm stand.",
    location: "United States",
    founded: 2020,
    categories: ["supplements"],
    accent: "#4A5D23",
    rating: 4.8,
    reviewCount: 190,
    followerCount: 2800,
    websiteUrl: "https://www.earthlingmushroomfarm.com",
    logoUrl: "/brands/earthling-mushroom-farm.svg",
  },
  {
    id: "c936",
    slug: "mushroom-alchemy",
    name: "Mushroom Alchemy",
    tagline: "EU organic lion's mane extract — fruiting body only, no mycelium-on-grain filler",
    story: "A small European extract house that mills organic lion's mane fruiting bodies at a 10:1 dual extract instead of a grain-filler capsule. The powder, eight-mushroom blend, and bundle stay. Merch stays out.",
    location: "Europe",
    founded: 2022,
    categories: ["supplements"],
    accent: "#5E4B45",
    rating: 4.7,
    reviewCount: 60,
    followerCount: 900,
    websiteUrl: "https://mushroom-alchemy.myshopify.com",
    logoUrl: "/brands/mushroom-alchemy.svg",
  },
];
