import type { Brand } from "./types";

/** Wave 32: small organic / toxic-free brands across marketplace categories (c985+). */
export const catalogBrandsWave32: Brand[] = [
  {
    id: "c985",
    slug: "hurraw",
    name: "Hurraw!",
    tagline: "Montana mineral SUNUP and volcanic tooth powder — organic, vegan, no chemical SPF",
    story: "A Whitefish, Montana kitchen that still makes lip balm, a seasonal mineral SUNUP cream, and a volcanic tooth powder in-house instead of a drugstore chemical-filter aisle. Flavor variants stay as their own listings. Wholesale displays, tube keys, and import-duty SKUs stay in the warehouse.",
    location: "Whitefish, Montana",
    founded: 2007,
    categories: ["sunscreen","oral","skincare","hair"],
    accent: "#C45C26",
    rating: 4.8,
    reviewCount: 4200,
    followerCount: 68000,
    websiteUrl: "https://hurrawbalm.com",
    logoUrl: "/brands/hurraw.png",
  },
  {
    id: "c986",
    slug: "grassfed-tallow",
    name: "Grassfed Tallow Co",
    tagline: "Six-SKU tallow house — non-nano zinc summer balm plus short-list whipped creams",
    story: "A small US render kitchen that only needed six jars: a non-nano zinc summer balm and whipped tallow creams in vanilla, eucalyptus, ho wood, lavender, and unscented. Scent variants stay as their own listings. Empty merch stays out.",
    location: "United States",
    founded: 2023,
    categories: ["sunscreen","skincare"],
    accent: "#8B6914",
    rating: 4.7,
    reviewCount: 90,
    followerCount: 1400,
    websiteUrl: "https://grassfedtallowshop.com",
    logoUrl: "/brands/grassfed-tallow.svg",
  },
  {
    id: "c987",
    slug: "tallow-twins",
    name: "Tallow Twins",
    tagline: "Ontario twin kitchen — aluminum-free tallow deodorant, sun milk, and scalp oil",
    story: "Two sisters in Ontario who render local grass-fed tallow into an aluminum-free deodorant, a mineral sun milk, and a scalp hair oil instead of a silicone cream aisle. Scent variants stay as their own listings. Hats, konjac sponges, gua sha, methylene-blue balms, and bug balm stay out.",
    location: "Ontario, Canada",
    founded: 2022,
    categories: ["deodorant","skincare","hair","sunscreen"],
    accent: "#5C4033",
    rating: 4.8,
    reviewCount: 380,
    followerCount: 9200,
    websiteUrl: "https://tallowtwins.ca",
    logoUrl: "/brands/tallow-twins.svg",
  },
  {
    id: "c988",
    slug: "ethos",
    name: "Ethos",
    tagline: "Baja salt electrolytes — organic fruit powders, no sugar alcohol, no fake flavor",
    story: "A two-SKU hydration house that seasons water with Baja sea salt, potassium, magnesium, and organic goji, dragon fruit, and lime instead of a neon sports-drink stick. Pack sizes stay. Empty bottles and merch stay out.",
    location: "United States",
    founded: 2024,
    categories: ["electrolytes"],
    accent: "#1B4F72",
    rating: 4.6,
    reviewCount: 70,
    followerCount: 1100,
    websiteUrl: "https://drinkethos.co",
    logoUrl: "/brands/ethos.svg",
  },
  {
    id: "c989",
    slug: "salties",
    name: "Salties",
    tagline: "Utah salt-lake hydration drops — unflavored electrolytes, no junk, family-made",
    story: "A one-SKU family kitchen that concentrates Great Salt Lake minerals into unflavored hydration drops instead of a sweetened stick pack. The drops stay. Apparel stays out.",
    location: "United States",
    founded: 2020,
    categories: ["electrolytes"],
    accent: "#2C5F4E",
    rating: 4.6,
    reviewCount: 80,
    followerCount: 900,
    websiteUrl: "https://salties.shop",
    logoUrl: "/brands/salties.svg",
  },
  {
    id: "c990",
    slug: "hela",
    name: "HeLa Nutrition",
    tagline: "Toronto organic plant protein — pea, hemp, pumpkin, no gum-thickened shake",
    story: "A Toronto women-owned kitchen that blends organic pea, hemp, pumpkin, basil, and chia into a complete plant protein instead of a chalky gum shake. Flavor variants stay as their own listings. Shaker bottles, frothers, and scoops stay in the cupboard.",
    location: "Toronto, Canada",
    founded: 2021,
    categories: ["protein"],
    accent: "#6B3E26",
    rating: 4.7,
    reviewCount: 220,
    followerCount: 3800,
    websiteUrl: "https://helanutrition.com",
    logoUrl: "/brands/hela.svg",
  },
  {
    id: "c991",
    slug: "alaya",
    name: "Alaya Naturals",
    tagline: "Organic plant protein and grass-fed whey — short stacks, no candy-multivitamin aisle",
    story: "A clean-label US house that keeps protein as organic pea-hemp-spirulina or grass-fed whey, then stacks collagen, creatine, and a daily foundation instead of a 40-ingredient gummy wall. Flavor variants stay as their own listings. Gift cards stay out.",
    location: "United States",
    founded: 2018,
    categories: ["protein","supplements"],
    accent: "#3D6B5A",
    rating: 4.6,
    reviewCount: 640,
    followerCount: 12000,
    websiteUrl: "https://alayanaturals.com",
    logoUrl: "/brands/alaya.svg",
  },
  {
    id: "c992",
    slug: "allpa",
    name: "Allpa Botanicals",
    tagline: "Bottled-fresh rosemary hair — sulfate-free shampoo, conditioner, and seed oils",
    story: "A small workshop that bottles rosemary shampoo, conditioner, and seed-oil hair treatments the day they leave instead of a warehouse-aged salon wall. Scented body-wash and face-oil variants stay as their own listings. Gift cards stay out.",
    location: "United States",
    founded: 2022,
    categories: ["hair","skincare"],
    accent: "#5B7A3A",
    rating: 4.7,
    reviewCount: 310,
    followerCount: 5400,
    websiteUrl: "https://allpabotanicals.com",
    logoUrl: "/brands/allpa.svg",
  },
  {
    id: "c993",
    slug: "simply-wild",
    name: "Simply Wild",
    tagline: "Kansas City herbalist hair — whole-plant infusions, no sulfate strip, no synthetic scent",
    story: "A Kansas City herbalist kitchen that starts shampoo and conditioner with whole-plant infusions and organic hydrosols instead of a silicone bottle. Beard balm, leave-in, and face cream stay. Tea blends stay in the kettle.",
    location: "Kansas City, United States",
    founded: 2019,
    categories: ["hair","skincare"],
    accent: "#7A9E7E",
    rating: 4.7,
    reviewCount: 160,
    followerCount: 2700,
    websiteUrl: "https://simplywild.store",
    logoUrl: "/brands/simply-wild.svg",
  },
  {
    id: "c994",
    slug: "everist",
    name: "Everist",
    tagline: "Concentrate shampoo and body wash — refill tins, no sulfate, no plastic bottle ritual",
    story: "A plastic-light hair house that ships shampoo, conditioner, and body-wash concentrates in refillable tins instead of a 16-oz plastic bottle. Scalp serum and UV hair oil stay. Jute pouches, combs, keep-caps, and empty packaging stay out.",
    location: "Canada",
    founded: 2019,
    categories: ["hair","skincare"],
    accent: "#2A6F6A",
    rating: 4.7,
    reviewCount: 890,
    followerCount: 22000,
    websiteUrl: "https://www.everistbeauty.com",
    logoUrl: "/brands/everist.svg",
  },
  {
    id: "c995",
    slug: "mycotonics",
    name: "Mycotonics",
    tagline: "Devon farm extracts — organic lion's mane, reishi, chaga, cordyceps, fruiting body only",
    story: "A Devon farm that grows lion's mane, reishi, chaga, and cordyceps, then dual-extracts the fruiting bodies on site instead of an imported mycelium-on-oat powder. Single extracts and the Vital 5 blend stay. Apparel stays out.",
    location: "Devon, United Kingdom",
    founded: 2020,
    categories: ["supplements"],
    accent: "#6B4F3A",
    rating: 4.8,
    reviewCount: 140,
    followerCount: 2100,
    websiteUrl: "https://mycotonics.uk",
    logoUrl: "/brands/mycotonics.svg",
  },
  {
    id: "c996",
    slug: "vesper",
    name: "Vesper Mushrooms",
    tagline: "US farm double extracts — alcohol-free lion's mane, reishi, turkey tail, no merch pile",
    story: "A US mushroom farm that double-extracts lion's mane, reishi, turkey tail, chaga, and cordyceps — including alcohol-free bottles — instead of a grain-mycelium capsule. Drink mixes and mushroom creams stay. Tees, hoodies, posters, and water bottles stay in the merch bin.",
    location: "United States",
    founded: 2021,
    categories: ["supplements","skincare"],
    accent: "#3D4A3D",
    rating: 4.7,
    reviewCount: 210,
    followerCount: 3600,
    websiteUrl: "https://vespermushrooms.com",
    logoUrl: "/brands/vesper.svg",
  },
  {
    id: "c997",
    slug: "slipstream",
    name: "Slipstream Farm",
    tagline: "Three-SKU farm extracts — lion's mane and a forager's blend, grown and bottled on site",
    story: "A tiny farm house that only needed three jars: lion's mane in two sizes and a forager's blend, grown and extracted on the same land instead of an imported capsule. All three stay. Grow kits and fresh culinary boxes stay in the barn.",
    location: "United States",
    founded: 2022,
    categories: ["supplements"],
    accent: "#5B7A3A",
    rating: 4.8,
    reviewCount: 50,
    followerCount: 800,
    websiteUrl: "https://slipstreamfarm.com",
    logoUrl: "/brands/slipstream.svg",
  },
  {
    id: "c998",
    slug: "c-and-o",
    name: "C&O Skincare",
    tagline: "One-balm UK house — collagen plump-and-repair, short list, no 40-ingredient cream",
    story: "A one-SKU British kitchen that only needed a collagen plump-and-repair balm instead of a 12-step routine. The balm stays. Empty merch stays out.",
    location: "United Kingdom",
    founded: 2023,
    categories: ["skincare"],
    accent: "#B85C38",
    rating: 4.6,
    reviewCount: 40,
    followerCount: 600,
    websiteUrl: "https://candoskincare.com",
    logoUrl: "/brands/c-and-o.svg",
  },
];
