import type { Brand } from "./types";

/** Wave 12: small organic / toxic-free brands across marketplace categories (c621+). */
export const catalogBrandsWave12: Brand[] = [
  {
    id: "c621",
    slug: "cotz",
    name: "CōTZ",
    tagline: "All-mineral zinc and titanium SPF that actually feels like skincare",
    story: "A Wisconsin mineral-sun house that never added a chemical filter. Non-nano zinc and titanium in tinted face formulas, kids sticks, and sensitive-skin lotions — no oxybenzone, no octinoxate, no “hybrid” compromise. Built for tattoos, school pickup, and skin that hates the drugstore burn.",
    location: "Wisconsin",
    founded: 2001,
    categories: ["sunscreen","skincare"],
    accent: "#2A6F97",
    rating: 4.7,
    reviewCount: 2400,
    followerCount: 38000,
    websiteUrl: "https://cotzskincare.com",
    logoUrl: "/brands/cotz.svg",
  },
  {
    id: "c622",
    slug: "radiant-bloom",
    name: "Radiant Bloom Organic",
    tagline: "ECOCERT mineral SPF and organic face care without the chemical-filter drawer",
    story: "A tiny European organic house making COSMOS-minded mineral sticks and face washes — non-nano zinc and titanium wrapped in organic oils, with a blendable tint that skips the white-cast excuse. No oxybenzone, no octinoxate, no reef-bleaching filters.",
    location: "Europe",
    founded: 2021,
    categories: ["sunscreen","skincare"],
    accent: "#C47A2C",
    rating: 4.7,
    reviewCount: 180,
    followerCount: 4200,
    websiteUrl: "https://www.radiantbloomorganic.com",
    logoUrl: "/brands/radiant-bloom.svg",
  },
  {
    id: "c623",
    slug: "bask",
    name: "Bask Suncare",
    tagline: "Feel-good SPF with a mineral line and 10% of sales to free sunscreen",
    story: "Started after a family skin-cancer loss: lightweight gels, fragrance-free mineral sprays, and a balm you actually want to reapply. Ten percent of sales fund The Skin Protection Foundation, and they give bottles away on beaches instead of pretending sunscreen is a lifestyle perfume.",
    location: "Florida",
    founded: 2018,
    categories: ["sunscreen"],
    accent: "#E8A317",
    rating: 4.6,
    reviewCount: 3100,
    followerCount: 52000,
    websiteUrl: "https://basksuncare.com",
    logoUrl: "/brands/bask.svg",
  },
  {
    id: "c624",
    slug: "eirlyte",
    name: "EirLyte",
    tagline: "Irish mineral sea-salt electrolytes without the neon sports-drink stack",
    story: "A small Irish hydration kitchen built around mineral sea salt instead of a dye-and-maltodextrin packet. Clean electrolyte powder for people who want minerals in their water, not another locker-room candy drink.",
    location: "Ireland",
    founded: 2022,
    categories: ["electrolytes"],
    accent: "#1B6B5A",
    rating: 4.7,
    reviewCount: 90,
    followerCount: 1800,
    websiteUrl: "https://eirlyte.com",
    logoUrl: "/brands/eirlyte.svg",
  },
  {
    id: "c625",
    slug: "purishh",
    name: "PÜR-ISHH",
    tagline: "Organic freeze-dried fruit electrolytes — no “natural flavors,” no erythritol",
    story: "Clean hydration built from organic freeze-dried fruit, unrefined Himalayan salt, and monk fruit that isn’t cut with erythritol. No artificial flavors, no mystery “natural flavor” systems, no refined sugar — just minerals and fruit you can pronounce.",
    location: "United States",
    founded: 2023,
    categories: ["electrolytes","skincare"],
    accent: "#4A6741",
    rating: 4.7,
    reviewCount: 220,
    followerCount: 5400,
    websiteUrl: "https://www.purishh.com",
    logoUrl: "/brands/purishh.svg",
  },
  {
    id: "c626",
    slug: "purple-tree",
    name: "Purple Tree",
    tagline: "USDA Organic zero-sugar hydration with Dead Sea mineral salts",
    story: "A California organic hydration house using mineral-rich Dead Sea salts, organic aloe, and monk fruit — zero sugar, no synthetic dyes, no chalky grit. Everyday packets for still or sparkling water instead of another neon sports stick.",
    location: "California",
    founded: 2021,
    categories: ["electrolytes"],
    accent: "#5B3A7A",
    rating: 4.6,
    reviewCount: 640,
    followerCount: 12000,
    websiteUrl: "https://purpletree.com",
    logoUrl: "/brands/purple-tree.svg",
  },
  {
    id: "c627",
    slug: "eco-protein",
    name: "ECO Protein",
    tagline: "Single-ingredient organic water-lentil protein — no gums, no flavor theater",
    story: "One ingredient: whole-ground water lentils (duckweed) grown on water, not farmland. A complete plant amino profile with naturally occurring iron and magnesium — no sweeteners, no masking agents, no pea-protein chalk. The opposite of a 19-ingredient tub.",
    location: "United States",
    founded: 2022,
    categories: ["protein"],
    accent: "#3D7A4A",
    rating: 4.6,
    reviewCount: 140,
    followerCount: 3100,
    websiteUrl: "https://ecoprotein.co",
    logoUrl: "/brands/eco-protein.svg",
  },
  {
    id: "c628",
    slug: "basic-af",
    name: "Basic AF",
    tagline: "Two-ingredient grass-fed beef protein. That’s the whole list.",
    story: "Hydrolyzed bovine collagen and grass-fed beef protein. No whey, no dairy, no soy, no “proprietary blend,” no fake vanilla fog. Unflavored on purpose so it disappears into a smoothie or bone broth — third-party tested, made in the USA.",
    location: "United States",
    founded: 2023,
    categories: ["protein"],
    accent: "#6B3E26",
    rating: 4.7,
    reviewCount: 80,
    followerCount: 1600,
    websiteUrl: "https://basicafnutrition.com",
    logoUrl: "/brands/basic-af.svg",
  },
  {
    id: "c629",
    slug: "bare-protein",
    name: "Bare Protein",
    tagline: "Canadian grass-fed beef isolate — three ingredients, monk fruit, done",
    story: "A tiny Canadian kitchen making grass-fed beef isolate with ceremonial cacao, vanilla bean, or matcha and a pinch of monk fruit. Dairy-free, soy-free, no gums — 21g of protein that reads like a pantry, not a lab.",
    location: "Canada",
    founded: 2022,
    categories: ["protein"],
    accent: "#8B5A2B",
    rating: 4.7,
    reviewCount: 160,
    followerCount: 2800,
    websiteUrl: "https://bare-protein.com",
    logoUrl: "/brands/bare-protein.svg",
  },
  {
    id: "c630",
    slug: "lifelong",
    name: "Lifelong",
    tagline: "Refillable natural deodorant in compostable pouches — no aluminum, no plastic stick",
    story: "A UK refill house: a reusable case and plastic-free compostable powder refills with zinc ricinoleate and magnesium hydroxide. Aluminum-free, plant-based, and built to last years instead of another single-use plastic stick in the bin.",
    location: "United Kingdom",
    founded: 2021,
    categories: ["deodorant","skincare"],
    accent: "#4A7C8C",
    rating: 4.6,
    reviewCount: 420,
    followerCount: 8900,
    websiteUrl: "https://www.lifelongdeo.com",
    logoUrl: "/brands/lifelong.svg",
  },
  {
    id: "c631",
    slug: "nudge",
    name: "Nudge",
    tagline: "10% nano-hydroxyapatite toothpaste, fluoride-free and SLS-free",
    story: "A small oral-care kitchen making 10% n-Ha paste and tablets without fluoride or SLS foam circus. Mineral enamel support, bamboo brushes, and probiotic gum — clean ingredients with a number on the label instead of a “free-from” sticker and nothing behind it.",
    location: "United States",
    founded: 2023,
    categories: ["oral"],
    accent: "#2C5F4E",
    rating: 4.7,
    reviewCount: 380,
    followerCount: 7200,
    websiteUrl: "https://shopnudge.com",
    logoUrl: "/brands/nudge.svg",
  },
  {
    id: "c632",
    slug: "ollie",
    name: "Ollie",
    tagline: "Eleven-ingredient 10% rod-shaped n-Ha toothpaste you can actually finish",
    story: "A tiny US oral house that put 10% rod-shaped nano-hydroxyapatite in a short mint, cinnamon, orange, and strawberry lineup. No SLS, no dyes, no glycerin pile-on — enamel support at the concentration the studies actually used.",
    location: "United States",
    founded: 2022,
    categories: ["oral"],
    accent: "#3E5A3D",
    rating: 4.6,
    reviewCount: 2200,
    followerCount: 18000,
    websiteUrl: "https://olliesmile.com",
    logoUrl: "/brands/ollie.svg",
  },
  {
    id: "c633",
    slug: "miltodent",
    name: "Miltodent",
    tagline: "UK hydroxyapatite toothpaste with a short, mineral-first label",
    story: "A British oral-care studio making fluoride-free hydroxyapatite paste — enamel-matching mineral, no drugstore dye stack, no SLS theater. One job: a cleaner brush that treats teeth like bone, not a mint candy.",
    location: "United Kingdom",
    founded: 2023,
    categories: ["oral"],
    accent: "#1A4A6B",
    rating: 4.7,
    reviewCount: 70,
    followerCount: 1200,
    websiteUrl: "https://miltodent.com",
    logoUrl: "/brands/miltodent.svg",
  },
  {
    id: "c634",
    slug: "obvs",
    name: "Obvs Skincare",
    tagline: "Soil Association COSMOS organic, plastic-free packaging for reactive skin",
    story: "A UK certified-organic house for acne- and eczema-prone skin: fragrance-free cleansers, mineral SPF 50, and plant-based biodegradable tubes. Vegan Society certified, no pesticide-grown botanicals, no microplastic pump bottle.",
    location: "United Kingdom",
    founded: 2018,
    categories: ["skincare","sunscreen"],
    accent: "#7A6A4F",
    rating: 4.8,
    reviewCount: 860,
    followerCount: 16000,
    websiteUrl: "https://obvs-skincare.com",
    logoUrl: "/brands/obvs.svg",
  },
  {
    id: "c635",
    slug: "ziji",
    name: "Ziji Skin",
    tagline: "Ayurvedic small-batch oils and salves with COSMOS-approved botanicals",
    story: "Founder-formulated in small batches: calendula salves, facial oils, and body butter bars built around Ayurveda and upcycled actives. No fragrance pile-on, no endocrine-disruptor cocktail — ritual formulas for skin that wants fewer steps and better plants.",
    location: "India",
    founded: 2020,
    categories: ["skincare"],
    accent: "#8B3A2A",
    rating: 4.8,
    reviewCount: 210,
    followerCount: 5400,
    websiteUrl: "https://zijiskin.com",
    logoUrl: "/brands/ziji.svg",
  },
  {
    id: "c636",
    slug: "moscarter",
    name: "MOSCARTER",
    tagline: "COSMOS-certified plant skincare and hair masks, handmade in small batches",
    story: "Earth-first formulas with about 95% certified-organic ingredients — nourishing creams, oil-free gels, and keratin-free botanical hair masks. No parabens, no sulfates, no synthetic fragrance. Small-batch, vegan, and audited instead of self-declared “clean.”",
    location: "Independent / DTC",
    founded: 2019,
    categories: ["skincare","hair"],
    accent: "#2E8B6A",
    rating: 4.7,
    reviewCount: 340,
    followerCount: 6800,
    websiteUrl: "https://www.moscarter.com",
    logoUrl: "/brands/moscarter.svg",
  },
  {
    id: "c637",
    slug: "ingreendients",
    name: "Ingreendients",
    tagline: "Plant-made hair care that publishes a 1,400-ingredient never list",
    story: "A plant-formula hair and body house: sulfate-free, silicone-free shampoos and conditioners plus body wash that skips the usual detergent theater. They spent two years on a “made from plants” brief and a public never-list instead of a greenwashed “naturally derived” sticker.",
    location: "United States",
    founded: 2019,
    categories: ["hair","skincare"],
    accent: "#3F6B4B",
    rating: 4.7,
    reviewCount: 500,
    followerCount: 14000,
    websiteUrl: "https://ingreendients.com",
    logoUrl: "/brands/ingreendients.svg",
  },
  {
    id: "c638",
    slug: "seek-bamboo",
    name: "Seek Bamboo",
    tagline: "Plastic-free hydroxyapatite toothpaste tablets and coconut hair care",
    story: "A plastic-light studio making n-Ha toothpaste tablets, coconut shampoo bars, and soap — fluoride-free, SLS-free, and built to leave the tube in the past. Enamel mineral in a tablet, wash-day botanicals without another bottle of water.",
    location: "United States",
    founded: 2020,
    categories: ["oral","hair"],
    accent: "#4A6741",
    rating: 4.6,
    reviewCount: 720,
    followerCount: 11000,
    websiteUrl: "https://seekbamboo.com",
    logoUrl: "/brands/seek-bamboo.svg",
  },
  {
    id: "c639",
    slug: "kion",
    name: "Kion",
    tagline: "Clean aminos, creatine, and protein without the bro-tub additive stack",
    story: "A performance-nutrition house from the Primal Kitchen lineage: essential aminos, creatine, and clean protein with short labels and third-party testing. No neon pre-workout circus — just the few things a training day actually needs.",
    location: "United States",
    founded: 2017,
    categories: ["supplements","protein"],
    accent: "#6B4F3A",
    rating: 4.6,
    reviewCount: 4800,
    followerCount: 92000,
    websiteUrl: "https://getkion.com",
    logoUrl: "/brands/kion.png",
  },
  {
    id: "c640",
    slug: "pote",
    name: "Products of the Earth",
    tagline: "Hand-crafted botanical supplements since 2005 — if you can’t eat it, skip it",
    story: "Chicago-born, Las Vegas–made botanical formulas: glucose support, hair systems, and daily tonics from plant and mineral ingredients only. Small-batch, vegan, and stubborn about the rule that what goes on (or in) should look like food, not a lab.",
    location: "Las Vegas, NV",
    founded: 2005,
    categories: ["supplements","hair"],
    accent: "#5B7A3A",
    rating: 4.7,
    reviewCount: 280,
    followerCount: 4500,
    websiteUrl: "https://productsoftheearthvegas.com",
    logoUrl: "/brands/pote.svg",
  },
];
