import type { Brand } from "./types";

/** Wave 84: small organic / toxic-free brands across marketplace categories (c1373+). */
export const catalogBrandsWave84: Brand[] = [
  {
    id: "c1373",
    slug: "miltodent",
    name: "MILTODENT",
    tagline: "Dentist-formulated 15% micro-hydroxyapatite toothpaste without fluoride or glycerin",
    story: "A dentist-developed fluoride-free toothpaste house using 15% micro-hydroxyapatite — the non-nano mineral enamel is made of — plus xylitol, with no SLS, glycerin, or artificial sweeteners. The Cool Mint tube is the unused one-SKU leftover after dedicated multi-SKU n-HA Shopify houses ran out in wave4–83. Pack count is size (keep 1 Pack). The UK handle is a region duplicate of the same paste. Cart.js is USD. Pages publish key-ingredient marketing (leave empty when there is no comma INCI).",
    location: "United States",
    founded: 2023,
    categories: ["oral"],
    accent: "#3A6B7A",
    rating: 4.6,
    reviewCount: 180,
    followerCount: 2400,
    websiteUrl: "https://miltodent.com",
    logoUrl: "/brands/miltodent.svg",
  },
  {
    id: "c1374",
    slug: "key-nutrients",
    name: "Key Nutrients",
    tagline: "Scottsdale sugar-free electrolyte powder sweetened with organic stevia, no sucralose",
    story: "A Scottsdale, Arizona hydration house (founded 2017) mixing sugar-free Recovery Plus electrolyte powder with organic stevia — no sucralose. Flavor expands Lemonade / Peach Mango / Cherry Pom / Blue Raspberry / Watermelon / Pink Lemonade / Orange / Pineapple Coconut; drop Fan Favorites (variety). 90 servings vs 20 vs 3x90 is size. Prefix Key Nutrients so Lemonade is not a bare flavor title. Variety packs, $0 gut-health teasers, and gift cards stay boxed. Capsules and Gut Health stay supplements. Cart.js is USD. Pages publish stevia-story marketing (leave empty when there is no comma formula).",
    location: "Scottsdale, AZ",
    founded: 2017,
    categories: ["electrolytes","supplements"],
    accent: "#2E6B8A",
    rating: 4.5,
    reviewCount: 2100,
    followerCount: 18000,
    websiteUrl: "https://keynutrients.com",
    logoUrl: "/brands/key-nutrients.png",
  },
  {
    id: "c1375",
    slug: "wild-society",
    name: "Wild Society",
    tagline: "Grass-fed whey and clear isolate with mushroom adaptogens, no artificial dyes",
    story: "A US grass-fed whey house blending pasture whey and clear isolate with a superfood mushroom mix — Vanilla Bean / Dutch Chocolate whey and Rocket Pop / Citrus Punch / Strawberry Coconut / Watermelon Lime / Lemon Lime clear isolate expand on Flavor. Prefix Wild Society so Vanilla Bean is not a bare flavor title. Single-serve packets are size/samples. Shakers, whisks, $0 gifts, UFC/protocol bundles, Caveman snack bags, and nootropic energy drinks stay boxed. Collagen and liver capsules stay supplements; the Dragonfruit electrolyte mix stays electrolytes. Cart.js is USD. Pages publish performance-story marketing (leave empty when there is no comma formula).",
    location: "United States",
    founded: 2021,
    categories: ["protein","electrolytes","supplements"],
    accent: "#1F3D2F",
    rating: 4.6,
    reviewCount: 640,
    followerCount: 8900,
    websiteUrl: "https://wildsocietynutrition.com",
    logoUrl: "/brands/wild-society.svg",
  },
  {
    id: "c1376",
    slug: "sunmud",
    name: "SUNMUD",
    tagline: "San Diego clay-tinted non-nano zinc sunscreen in recyclable aluminum tins",
    story: "A San Diego mineral house (formula work from 2017, launched by a PhD founder) pouring non-nano zinc, Fuller's earth clay, and organic butters into infinitely recyclable aluminum tins — Ivory, Sahara, Terra, and Ebony already live on separate tin and sports-stick titles. 1.5 oz vs 0.5 oz is size. Plastic-free / surfer bundles and mixed samples stay boxed. After-sun Solar Repair and the lip / muscle balms stay skincare. Cart.js is USD. Pages publish the zinc / shea / tamanu / hemp / beeswax / clay list when a real formula is on the page.",
    location: "San Diego, CA",
    founded: 2017,
    categories: ["sunscreen","skincare"],
    accent: "#C4A574",
    rating: 4.7,
    reviewCount: 890,
    followerCount: 12000,
    websiteUrl: "https://sunmudsunscreen.com",
    logoUrl: "/brands/sunmud.svg",
  },
  {
    id: "c1377",
    slug: "finally-all-natural",
    name: "Finally All Natural",
    tagline: "Baking-soda-free prebiotic deodorant plus short-list oils for sensitive skin",
    story: "A small clean body-care house pouring aluminum-free, baking-soda-free prebiotic deodorant with kaolin and blue agave — Jasmine and Unscented expand on Scent — plus face, body, baby, beard, and scalp oils without synthetic fragrance. Spray vs dropper is packaging. Ritual sets, sample kits, gift cards, bamboo pads, and scalp-massager merch stay boxed. Keep the full scalp-oil set over the refill-only option. Cart.js is USD. Pages publish key-ingredient marketing (leave empty when the list is a benefit essay).",
    location: "United States",
    founded: 2021,
    categories: ["deodorant","skincare","hair"],
    accent: "#7A8F6B",
    rating: 4.6,
    reviewCount: 320,
    followerCount: 4100,
    websiteUrl: "https://finallyallnatural.com",
    logoUrl: "/brands/finally-all-natural.svg",
  },
  {
    id: "c1378",
    slug: "teelixir",
    name: "Teelixir",
    tagline: "Melbourne certified-organic mushroom extracts and tonic herbs since 2015",
    story: "Australia's first certified-organic medicinal mushroom house (Melbourne, 2015) dual-extracting Lion's Mane, Reishi, Cordyceps, Turkey Tail, Chaga, Maitake, Tremella, and Meshima plus shilajit, ashwagandha, and cacao / turmeric / matcha lattes. Gram and ml count is size (keep 50 g / 30 g / 30 ml / 100 g latte over 250 g–1 kg). $0 gift SKUs, sample sachets, frothers, water bottles, and 5 g singles stay boxed. Cart.js is AUD — convert × 0.65. Pages publish 100% extract lines when a real formula is on the page; extraction-method essays stay empty.",
    location: "Melbourne, Australia",
    founded: 2015,
    categories: ["supplements"],
    accent: "#6B3A2A",
    rating: 4.7,
    reviewCount: 1800,
    followerCount: 22000,
    websiteUrl: "https://teelixir.com",
    logoUrl: "/brands/teelixir.svg",
  },
];
