import type { Brand } from "./types";

/** Wave 27: small organic / toxic-free brands across marketplace categories (c907+). */
export const catalogBrandsWave27: Brand[] = [
  {
    id: "c907",
    slug: "shwally",
    name: "Shwally",
    tagline: "Edible-ingredient sun balm and 30% hydroxyapatite toothpaste — seed-oil-free, no chemical-filter dump",
    story: "A Southern California family kitchen that puts non-nano zinc in grass-fed tallow and avocado oil, then makes a 30% hydroxyapatite toothpaste instead of a neon gel tube. Sun balms, pulling oil, and repair serums stay. Play mats and monitor SKUs stay on the home site.",
    location: "Southern California",
    founded: 2021,
    categories: ["oral","sunscreen","skincare"],
    accent: "#2C5F4E",
    rating: 4.7,
    reviewCount: 380,
    followerCount: 5400,
    websiteUrl: "https://shwallycompany.com",
    logoUrl: "/brands/shwally.svg",
  },
  {
    id: "c908",
    slug: "true-friend",
    name: "True Friend",
    tagline: "Small-batch aluminum-free deodorant — organic oils, baking-soda and baking-soda-free sticks",
    story: "A US stick kitchen that spent two years on an organic shea-and-wax deodorant instead of an aluminum antiperspirant. Vanilla + Citrus, Lavender + Lemon, and Eucalyptus + Mint stay as their own listings. Sensitive baking-soda-free versions stay. Konjac sponges stay in the merch drawer.",
    location: "United States",
    founded: 2023,
    categories: ["deodorant","skincare"],
    accent: "#6B5B95",
    rating: 4.8,
    reviewCount: 220,
    followerCount: 3100,
    websiteUrl: "https://truefriendco.com",
    logoUrl: "/brands/true-friend.svg",
  },
  {
    id: "c909",
    slug: "tallow-vera",
    name: "Tallow Vera",
    tagline: "Triple-purified tallow balms and lip tins — short lists, no water-lotion filler",
    story: "A small tallow house that renders and purifies grass-fed fat for face, body, and lips instead of a 40-ingredient cream. Lip balm scent variants stay. Bundles stay when they are the same formulas. Empty applicators stay out.",
    location: "United States",
    founded: 2022,
    categories: ["skincare"],
    accent: "#C4A484",
    rating: 4.7,
    reviewCount: 410,
    followerCount: 6200,
    websiteUrl: "https://tallowvera.com",
    logoUrl: "/brands/tallow-vera.svg",
  },
  {
    id: "c910",
    slug: "selkyn-tallow",
    name: "Sēlkyn Tallow",
    tagline: "Byron hinterland organic tallow — slow-infused botanicals, aluminum-free paste deodorant",
    story: "A woman-owned herbal kitchen in the Byron Bay hinterland that slow-infuses organic Australian tallow with calendula and lavender. Face and body balms stay. Lemon Myrtle and sensitive-skin deodorant pastes stay as their own listings. Lip balm flavors stay.",
    location: "Byron Bay hinterland, Australia",
    founded: 2022,
    categories: ["skincare","deodorant"],
    accent: "#2A6F4E",
    rating: 4.8,
    reviewCount: 190,
    followerCount: 2800,
    websiteUrl: "https://selkyntallow.com",
    logoUrl: "/brands/selkyn-tallow.svg",
  },
  {
    id: "c911",
    slug: "humby-organics",
    name: "Humby Organics",
    tagline: "Handmade Ohio shampoo and conditioner bars — zero-waste lather, no plastic bottle circus",
    story: "A Columbus studio that still pours shampoo and conditioner bars by hand for curly, fine, colored, and dandruff hair. Blueberry Fields, Mango Breeze, and other scent bars stay as their own listings. Empty bottles and combs stay out.",
    location: "Columbus, Ohio",
    founded: 2019,
    categories: ["hair"],
    accent: "#7B3F6E",
    rating: 4.6,
    reviewCount: 2100,
    followerCount: 18000,
    websiteUrl: "https://humbyorganics.com",
    logoUrl: "/brands/humby-organics.svg",
  },
  {
    id: "c912",
    slug: "noun-naturals",
    name: "Noun Naturals",
    tagline: "Black-seed and turmeric hair ritual — shampoo, batana oil, no silicone slip",
    story: "A small clean-hair house built around black seed, amla, batana, and rosemary instead of a dimethicone serum. Shampoo, conditioner, hair oil, and clay texture powder stay. Salt scrub stays as skincare. Tools stay out.",
    location: "United States",
    founded: 2021,
    categories: ["hair","skincare"],
    accent: "#1B4F72",
    rating: 4.7,
    reviewCount: 340,
    followerCount: 4500,
    websiteUrl: "https://nounnaturals.com",
    logoUrl: "/brands/noun-naturals.svg",
  },
  {
    id: "c913",
    slug: "tallow-balm-shop",
    name: "Tallow Balm Shop",
    tagline: "Australian grass-fed tallow balm — one or two ingredients, no water-lotion filler",
    story: "A small Australian kitchen that renders pasture-raised tallow and whips it with honey or lavender instead of a 30-ingredient cream. Honey, lavender, and unscented balms stay. Lip balm stays. Gift cards stay in the merch drawer.",
    location: "Australia",
    founded: 2023,
    categories: ["skincare"],
    accent: "#8B5A2B",
    rating: 4.8,
    reviewCount: 160,
    followerCount: 1900,
    websiteUrl: "https://tallowbalmshop.com",
    logoUrl: "/brands/tallow-balm-shop.svg",
  },
  {
    id: "c914",
    slug: "kalen-and-rose",
    name: "Kalén & Rose",
    tagline: "San Diego herbalist tallow balms — blue tansy Calm, caffeinated Glow, no synthetic fragrance",
    story: "Clinical herbalist Taylor Conrad still pours grass-fed tallow balms and bakuchiol serums in a San Diego kitchen named for her mother. Calm, Glow, and vitamin C stay. Beeswax candles stay in the merch drawer.",
    location: "San Diego, CA",
    founded: 2021,
    categories: ["skincare"],
    accent: "#B76E79",
    rating: 4.9,
    reviewCount: 280,
    followerCount: 4200,
    websiteUrl: "https://kalenandrose.com",
    logoUrl: "/brands/kalen-and-rose.svg",
  },
  {
    id: "c915",
    slug: "sodii",
    name: "Sodii",
    tagline: "Australian hydration salts — real mineral sodium, no neon sport-drink dye stack",
    story: "A small Australian salt kitchen that makes everyday hydration salts and salty bundles without a candy-aisle electrolyte tub. Chocolate, unflavoured, and other flavors stay as their own listings. Raw electrolyte honey stays. Shakers stay out.",
    location: "Australia",
    founded: 2021,
    categories: ["electrolytes"],
    accent: "#C45C26",
    rating: 4.7,
    reviewCount: 890,
    followerCount: 12000,
    websiteUrl: "https://sodii.com.au",
    logoUrl: "/brands/sodii.svg",
  },
  {
    id: "c916",
    slug: "sisu-mushrooms",
    name: "Sisu Mushrooms",
    tagline: "Veteran-owned organic lion's mane powder — fruiting body only, no grain-filler mycelium",
    story: "A small US mushroom house that mills 100% organic lion's mane fruiting bodies for coffee and smoothies instead of a mycelium-on-oats capsule. The powder stays. Merch stays out.",
    location: "United States",
    founded: 2023,
    categories: ["supplements"],
    accent: "#3D5A3D",
    rating: 4.8,
    reviewCount: 140,
    followerCount: 2100,
    websiteUrl: "https://www.sisumushrooms.com",
    logoUrl: "/brands/sisu-mushrooms.svg",
  },
  {
    id: "c917",
    slug: "texas-tallow",
    name: "Texas Tallow Products",
    tagline: "Texas tallow lotions — magnesium, blue clay, no cooking-fat jar on the face",
    story: "A Texas tallow kitchen that turns rendered fat into magnesium and clay lotions instead of a petroleum cream. Face and body lotions stay. Fresh cooking tallow and order-builder SKUs stay in the pantry.",
    location: "Texas, United States",
    founded: 2020,
    categories: ["skincare"],
    accent: "#8B3A2A",
    rating: 4.6,
    reviewCount: 520,
    followerCount: 7800,
    websiteUrl: "https://texastallowproducts.com",
    logoUrl: "/brands/texas-tallow.svg",
  },
  {
    id: "c918",
    slug: "summer-solace",
    name: "Summer Solace",
    tagline: "Northern California climate-beneficial tallow and emu face oil — farm fat, no coffee-roaster aisle",
    story: "A Northern California tallow house that renders climate-beneficial fat and blends emu face oil instead of a silicone serum. Tallow and emu skincare stay. Wool batting and coffee bags stay on the farm stand.",
    location: "Northern California",
    founded: 2018,
    categories: ["skincare"],
    accent: "#C4A35A",
    rating: 4.8,
    reviewCount: 640,
    followerCount: 9100,
    websiteUrl: "https://summersolacetallow.com",
    logoUrl: "/brands/summer-solace.svg",
  },
  {
    id: "c919",
    slug: "golden-tallow",
    name: "Golden Tallow",
    tagline: "Wagyu tallow soap bars — unscented, eucalyptus, sandalwood, no detergent brick",
    story: "A small soap kitchen that pours Wagyu tallow bars instead of a sodium-lauryl-sulfate brick. Unscented, eucalyptus, and sandalwood stay as their own listings. Tools stay out.",
    location: "United States",
    founded: 2022,
    categories: ["skincare"],
    accent: "#C9A227",
    rating: 4.7,
    reviewCount: 90,
    followerCount: 1200,
    websiteUrl: "https://goldentallow.com",
    logoUrl: "/brands/golden-tallow.svg",
  },
  {
    id: "c920",
    slug: "rooted-tallow",
    name: "Rooted Tallow",
    tagline: "Small-batch tallow soap — charcoal tea tree, unscented, no fragrance-oil dump",
    story: "A tiny tallow soap house that keeps the list short: fat, lye, and a botanical or two. Charcoal and tea tree, unscented, and Breathe Blend stay. Dishes and savers stay out.",
    location: "United States",
    founded: 2023,
    categories: ["skincare"],
    accent: "#4A5D23",
    rating: 4.6,
    reviewCount: 70,
    followerCount: 800,
    websiteUrl: "https://rootedtallow.com",
    logoUrl: "/brands/rooted-tallow.svg",
  },
];
