import type { Brand } from "./types";

/** Wave 17: small organic / toxic-free brands across marketplace categories (c721+). */
export const catalogBrandsWave17: Brand[] = [
  {
    id: "c721",
    slug: "beach-rooster",
    name: "The Beach Rooster",
    tagline: "Family-made mineral SPF 30 for face, body, and lips — reef-minded zinc, no chemical-filter fog",
    story: "A brother-and-dad kitchen that started making mineral sun care after a family skin-cancer scare. Non-nano zinc in lightweight sprays, tinted face, and lip SPF 30 — no oxybenzone, no octinoxate, no chalky ghost face. Built for beach days and everyday outside, not a drugstore chemical stack.",
    location: "United States",
    founded: 2022,
    categories: ["sunscreen"],
    accent: "#C45C26",
    rating: 4.7,
    reviewCount: 280,
    followerCount: 6400,
    websiteUrl: "https://thebeachrooster.com",
    logoUrl: "/brands/beach-rooster.svg",
  },
  {
    id: "c722",
    slug: "om-botanical",
    name: "OM Botanical",
    tagline: "Sheer mineral SPF 40 and plant-first recovery — organic botanicals, no chemical UV filters",
    story: "A clean sun-and-skin studio that treats SPF like skincare: sheer mineral zinc at SPF 40, plus recovery oils and active-day bundles. Organic botanicals, reef-minded filters only, and short readable lists — protection you can wear under a shirt without the grease-and-ghost routine.",
    location: "United States",
    founded: 2019,
    categories: ["sunscreen","skincare"],
    accent: "#2C5F4E",
    rating: 4.8,
    reviewCount: 410,
    followerCount: 9800,
    websiteUrl: "https://ombotanical.com",
    logoUrl: "/brands/om-botanical.svg",
  },
  {
    id: "c723",
    slug: "daily-shade",
    name: "Daily Shade",
    tagline: "Mom-formulated 100% non-nano zinc that disappears — no chemical boosters, no EU-banned stack",
    story: "Breelyn spent four years on a true mineral formula after watching chemical sunscreens fail her family. Daily Shade is 100% non-nano zinc, free of the 1,700-ingredient EU-banned list, and built to vanish on skin instead of leaving a ghost cast. A small, investor-free kitchen for kids, babies, and sensitive faces.",
    location: "United States",
    founded: 2021,
    categories: ["sunscreen"],
    accent: "#1B4F72",
    rating: 4.8,
    reviewCount: 520,
    followerCount: 12000,
    websiteUrl: "https://www.dailyshade.com",
    logoUrl: "/brands/daily-shade.svg",
  },
  {
    id: "c724",
    slug: "kona-pure",
    name: "Kona Pure",
    tagline: "Deep-ocean electrolytes from 2,200 feet off Kona — solar-evaporated, plastic-free stick packs",
    story: "Drawn from the Hawai‘i Ocean Science Technology Park, 2,200 feet down, then solar-evaporated on the Kona Coast. Full-spectrum ocean minerals in compostable stick packs — citrus, passion fruit, unflavored — without synthetic dye or a candy-aisle sweetener drawer. Hydration that actually came from the sea.",
    location: "Kona, HI",
    founded: 2023,
    categories: ["electrolytes"],
    accent: "#1A7A8C",
    rating: 4.7,
    reviewCount: 190,
    followerCount: 5400,
    websiteUrl: "https://konapure.com",
    logoUrl: "/brands/kona-pure.svg",
  },
  {
    id: "c725",
    slug: "go-good",
    name: "Go Good",
    tagline: "New Zealand grass-fed whey and creatine — real fruit, no artificial flavor fog",
    story: "A Kiwi protein kitchen that starts with pasture whey and keeps the rest short: organic banana, tropical, wildberry, and unflavoured creatine. Grass-fed cows, no soy, no GMO circus, nothing artificial. Recovery powder that still tastes like food from a country that actually has grass.",
    location: "New Zealand",
    founded: 2016,
    categories: ["protein"],
    accent: "#3D8B6E",
    rating: 4.8,
    reviewCount: 860,
    followerCount: 18000,
    websiteUrl: "https://gogood.co.nz",
    logoUrl: "/brands/go-good.svg",
  },
  {
    id: "c726",
    slug: "ancestral-nutrition-au",
    name: "Ancestral Nutrition",
    tagline: "Australian grass-fed organ capsules — nose-to-tail nutrients without a synthetic multi stack",
    story: "An Australian nose-to-tail studio that freeze-dries grass-fed organs into daily capsules instead of a 40-ingredient vitamin drawer. Liver, heart, bone, and primal blends from animals that actually lived outside. No fillers dressed up as 'proprietary blends' — just the parts your great-grandparents would have eaten.",
    location: "Australia",
    founded: 2018,
    categories: ["supplements"],
    accent: "#6B3E26",
    rating: 4.7,
    reviewCount: 740,
    followerCount: 21000,
    websiteUrl: "https://www.ancestralnutrition.com.au",
    logoUrl: "/brands/ancestral-nutrition-au.svg",
  },
  {
    id: "c727",
    slug: "mags-skin",
    name: "MAGS Skin",
    tagline: "Eczema-seal magnesium spray deodorant — no aluminum, no baking soda, no fragrance",
    story: "Born from a Hinge date and a rash: a Toronto chemist and a founder who were done flaring from 'natural' sticks. MAGS is a fragrance-free magnesium hydroxide spray with probiotics, aloe, and chamomile — National Eczema Association accepted, National Psoriasis Foundation recognized. Skincare for underarms that actually react.",
    location: "Toronto, Canada",
    founded: 2023,
    categories: ["deodorant","skincare"],
    accent: "#5B7C6A",
    rating: 4.8,
    reviewCount: 340,
    followerCount: 8900,
    websiteUrl: "https://magsskin.com",
    logoUrl: "/brands/mags-skin.svg",
  },
  {
    id: "c728",
    slug: "smart-charlie",
    name: "Smart Charlie Naturals",
    tagline: "Mom-made nano-hydroxyapatite toothpaste and small-batch balms — fluoride-free, no filler pile",
    story: "Steph spent 25 years in food manufacturing, then got tired of fluoride alternatives with novel-length labels. Smart Charlie is nano-hydroxyapatite toothpaste measured like a spec sheet, plus magnesium butter and cold-process soap poured in small batches. Family-safe oral care with receipts, not a neon-gel aisle.",
    location: "United States",
    founded: 2022,
    categories: ["oral","skincare"],
    accent: "#45B69C",
    rating: 4.7,
    reviewCount: 210,
    followerCount: 4200,
    websiteUrl: "https://smartcharlienaturals.com",
    logoUrl: "/brands/smart-charlie.svg",
  },
  {
    id: "c729",
    slug: "absolutely-pure",
    name: "Absolutely Pure",
    tagline: "OraWellness Smile hydroxyapatite toothpaste and clean B-complex — paleo minerals, no junk drawer",
    story: "A clean-label apothecary that stocks OraWellness Smile — microcrystalline hydroxyapatite from grass-fed New Zealand bone, plus a vegan nHA paste — and a B-complex that actually leaves B6 out when it should. Fluoride-free enamel care and supplements without the grocery-vitamin fog.",
    location: "United States",
    founded: 2014,
    categories: ["oral","supplements"],
    accent: "#1B4F72",
    rating: 4.6,
    reviewCount: 480,
    followerCount: 11000,
    websiteUrl: "https://absolutelypure.com",
    logoUrl: "/brands/absolutely-pure.png",
  },
  {
    id: "c730",
    slug: "vita-prima",
    name: "Vita Prima",
    tagline: "First liquid grass-fed tallow shampoo and conditioner — rosemary, Manuka, no sulphate fog",
    story: "The rare tallow house that cracked a shelf-stable liquid shampoo instead of another bar that won't dissolve. 100% grass-fed tallow with rosemary, raw Manuka honey, and organic jojoba — plus Legacy balm and mineral sunblock. Ancestral haircare you can actually pour, not a plastic bottle of silicones.",
    location: "United States",
    founded: 2022,
    categories: ["hair","skincare"],
    accent: "#6B4F2A",
    rating: 4.8,
    reviewCount: 390,
    followerCount: 14000,
    websiteUrl: "https://vitaprima.com",
    logoUrl: "/brands/vita-prima.svg",
  },
  {
    id: "c731",
    slug: "onaturelle",
    name: "O'Naturelle",
    tagline: "Handmade grass-fed tallow shampoo bars and lotion — essential-oil scents, no synthetic fragrance",
    story: "Small-batch bars saponified from grass-fed tallow, olive, coconut, and castor — plus lip balm and lotion with nothing but essential oils for scent. No sulphate detergent, no perfume fog. Hair and skin care that reads like a kitchen recipe, shipped without a plastic bottle mountain.",
    location: "United States / Canada",
    founded: 2020,
    categories: ["hair","skincare"],
    accent: "#7A4E2D",
    rating: 4.7,
    reviewCount: 260,
    followerCount: 5600,
    websiteUrl: "https://onaturelle.co",
    logoUrl: "/brands/onaturelle.svg",
  },
  {
    id: "c732",
    slug: "wildly-rooted",
    name: "Wildly Rooted",
    tagline: "Tallow shampoo bars with ACV, honey, and rosemary — plastic-free, no synthetic fragrance",
    story: "A homestead kitchen pouring Daily Lather: grass-fed tallow, organic apple cider vinegar, raw honey, and rosemary in a bar that replaces three bottles. Plus Wild Rescue balm and an outdoor protection stick. Traditional soapmaking, no perfume drawer, no filler pile.",
    location: "United States",
    founded: 2021,
    categories: ["hair","skincare"],
    accent: "#2F5D3A",
    rating: 4.8,
    reviewCount: 180,
    followerCount: 3800,
    websiteUrl: "https://livewildlyrooted.com",
    logoUrl: "/brands/wildly-rooted.svg",
  },
  {
    id: "c733",
    slug: "soapmomento",
    name: "Soapmomento",
    tagline: "Unscented grass-fed tallow shampoo bars and facial cleansers — zero-waste, no sulphate fog",
    story: "A minimalist soap studio that put grass-fed tallow and rice protein into an unscented shampoo bar for people who react to everything. Plus Manuka-jojoba facial bars and turmeric-lemongrass cleansers. Small-batch, organic oils, no synthetic fragrance — one bar instead of a plastic bottle.",
    location: "United States",
    founded: 2019,
    categories: ["hair","skincare"],
    accent: "#C4A484",
    rating: 4.7,
    reviewCount: 220,
    followerCount: 4100,
    websiteUrl: "https://www.soapmomento.com",
    logoUrl: "/brands/soapmomento.svg",
  },
  {
    id: "c734",
    slug: "grass-fed-soaps",
    name: "Grass Fed Soaps",
    tagline: "Virginia Beach tallow shampoo and conditioner — sulfate-free, no synthetic fragrance",
    story: "Handcrafted in Virginia Beach: grass-fed tallow with oat protein, aloe, and panthenol in a sulfate-free shampoo and conditioner that still rinses clean. Baby bundles, sun bundles, manly bundles — all poured in small batches without silicones or a perfume stack. Scalp care that feels like food, not a salon detergent.",
    location: "Virginia Beach, VA",
    founded: 2020,
    categories: ["hair","skincare"],
    accent: "#4A7C59",
    rating: 4.8,
    reviewCount: 310,
    followerCount: 7200,
    websiteUrl: "https://grassfedsoaps.com",
    logoUrl: "/brands/grass-fed-soaps.svg",
  },
  {
    id: "c735",
    slug: "gribb",
    name: "Gribb",
    tagline: "Portugal farm dual-extracts — certified organic fruiting bodies, no imported grain bags",
    story: "Gribb grows tremella, lion's mane, and the rest on their own certified-organic farm in Portimão, then double-extracts them in house. PT-BIO-10 certified, third-party tested, never a rebranded grain bag from overseas. Real mushrooms from a working Portuguese farm, standardized to beta-glucans you can actually read.",
    location: "Portimão, Portugal",
    founded: 2021,
    categories: ["supplements"],
    accent: "#3E2723",
    rating: 4.8,
    reviewCount: 160,
    followerCount: 5400,
    websiteUrl: "https://gribbworld.com",
    logoUrl: "/brands/gribb.svg",
  },
  {
    id: "c736",
    slug: "navi-organics",
    name: "Na'vi Organics",
    tagline: "Highland-workshop Yá Pearl dual-hydroxyapatite toothpaste — anhydrous, no fluoride, no SLS",
    story: "Hand-blended near Loch Shiel: Yá Pearl pairs two sizes of hydroxyapatite with levigated pearl in a water-free castor-oil base — no fluoride, no SLS, no sweeteners, nothing that needs a preservative circus. Wild-harvested botanicals from a Highland workshop that still treats toothpaste like a ritual, not a foam show.",
    location: "Scottish Highlands, UK",
    founded: 2017,
    categories: ["oral","skincare"],
    accent: "#5B3A6E",
    rating: 4.8,
    reviewCount: 290,
    followerCount: 8600,
    websiteUrl: "https://www.naviorganics.uk",
    logoUrl: "/brands/navi-organics.svg",
  },
  {
    id: "c737",
    slug: "happy-bum-co",
    name: "Happy Bum Co",
    tagline: "Happy Hydrate mineral packets and aftercare balms — clean electrolytes, no dye circus",
    story: "A gut-first studio that added Happy Hydrate — mineral electrolyte packets without the neon-sports-drink stack — next to simple aftercare balms. Short labels, no artificial dye fog. Built for people who want hydration and barrier care without a locker-room candy aisle.",
    location: "United States",
    founded: 2021,
    categories: ["electrolytes","skincare"],
    accent: "#E27D60",
    rating: 4.6,
    reviewCount: 140,
    followerCount: 3200,
    websiteUrl: "https://happybumco.com",
    logoUrl: "/brands/happy-bum-co.svg",
  },
];
