import type { Brand } from "./types";

/** Wave 15: small organic / toxic-free brands across marketplace categories (c681+). */
export const catalogBrandsWave15: Brand[] = [
  {
    id: "c681",
    slug: "mother-spf",
    name: "Mother SPF",
    tagline: "Australian mineral SPF 50 with an 11-ingredient zinc formula, no chemical-filter stack",
    story: "A female-founded Australian sun house that treats SPF like skincare: non-nano zinc, organic coconut and castor oils, and a short Eco-Cert list that skips fragrance, allergens, and the usual chemical-filter cocktail. Family-safe from six months up, 2-hour water resistant, solar-minded production, and tubes diverted from landfill — built for people who actually live outside.",
    location: "Australia",
    founded: 2021,
    categories: ["sunscreen"],
    accent: "#C45C26",
    rating: 4.8,
    reviewCount: 640,
    followerCount: 18000,
    websiteUrl: "https://www.motherspf.com",
    logoUrl: "/brands/mother-spf.svg",
  },
  {
    id: "c682",
    slug: "kind-sunscreen",
    name: "The Kind Sunscreen",
    tagline: "Nine-ingredient TGA-approved zinc SPF 30, reef-minded and baby-safe",
    story: "An Australian kitchen that refused the 40-ingredient sunscreen aisle. Non-nano zinc, organic coconut and candelilla, vitamin E — nine things, no white-cast theater, no chemical filters. TGA-approved, reef-friendly, and gentle enough for pregnancy, babies, and blemish-prone skin.",
    location: "Australia",
    founded: 2022,
    categories: ["sunscreen"],
    accent: "#2A9D8F",
    rating: 4.8,
    reviewCount: 420,
    followerCount: 12000,
    websiteUrl: "https://thekindsunscreen.com.au",
    logoUrl: "/brands/kind-sunscreen.svg",
  },
  {
    id: "c683",
    slug: "aussiezinc",
    name: "AussieZinc",
    tagline: "Organic vegan zinc SPF 50 for babies, kids, and everyday faces, minus the ghost cast",
    story: "A family-first Australian zinc house: 25% non-nano zinc in organic, vegan, reef-safe pastes for babies, kids, tinted everyday wear, and a mozzie-repellent sport stick. TGA-registered and batch-tested so the SPF on the tube is the SPF you actually get — no oxybenzone, no octinoxate, no drugstore chemical fog.",
    location: "Australia",
    founded: 2020,
    categories: ["sunscreen"],
    accent: "#E8A317",
    rating: 4.7,
    reviewCount: 890,
    followerCount: 22000,
    websiteUrl: "https://www.aussiezincsunscreen.com.au",
    logoUrl: "/brands/aussiezinc.svg",
  },
  {
    id: "c684",
    slug: "waterboy",
    name: "Waterboy",
    tagline: "Sugar-free hydration sticks with Himalayan salt, no sports-drink dye circus",
    story: "Two founders who got tired of sugar-bomb hydration packets. Daily, workout, and weekend formulas built on pink Himalayan salt, potassium, and magnesium — zero sugar, vegan, non-GMO, and flavored like watermelon and strawberry lemonade instead of a convenience-store syrup. Electrolytes for people who sweat, not for a locker-room candy aisle.",
    location: "United States",
    founded: 2021,
    categories: ["electrolytes"],
    accent: "#1B4F72",
    rating: 4.7,
    reviewCount: 2100,
    followerCount: 48000,
    websiteUrl: "https://www.waterboy.com",
    logoUrl: "/brands/waterboy.svg",
  },
  {
    id: "c685",
    slug: "lit-salt",
    name: "LIT",
    tagline: "Spanish sugar-free electrolyte sachets — sodium, potassium, magnesium, no dye stack",
    story: "A Madrid hydration kitchen packing 500 mg sodium with potassium and magnesium, lemon, and stevia. No sugar, no artificial colors, no microplastic theater. Made in Spain for long workdays, training, and hot weather — a clean sachet that tastes like citrus salt, not a neon sports drink.",
    location: "Madrid, Spain",
    founded: 2023,
    categories: ["electrolytes"],
    accent: "#E27D60",
    rating: 4.8,
    reviewCount: 380,
    followerCount: 9100,
    websiteUrl: "https://litsalt.com",
    logoUrl: "/brands/lit-salt.svg",
  },
  {
    id: "c686",
    slug: "peachie-spoon",
    name: "The Peachie Spoon",
    tagline: "Birmingham grass-fed whey, collagen, and creatine without the gum-and-chalk stack",
    story: "Meredith Mann's family kitchen in Alabama: 25 g grass-fed whey isolate in cupcake-vanilla and chocolate, plus collagen and creatine. No xanthan, no sugar alcohols, no mystery lecithin fog — small-batch tested for heavy metals and mold. Built for blood-sugar-friendly mornings, not a gas-station candy shake.",
    location: "Birmingham, AL",
    founded: 2019,
    categories: ["protein","supplements"],
    accent: "#E8A0BF",
    rating: 4.8,
    reviewCount: 740,
    followerCount: 310000,
    websiteUrl: "https://thepeachiespoon.com",
    logoUrl: "/brands/peachie-spoon.svg",
  },
  {
    id: "c687",
    slug: "agn-roots",
    name: "AGN Roots",
    tagline: "Irish pasture whey isolate, Informed Sport tested, one clean scoop",
    story: "A Houston-and-Kilkenny whey house that sources Irish grass-fed isolate from independent family farms. Cold-processed, unflavored, Informed Sport and Informed Protein certified — no artificial anything, a whisper of sunflower lecithin so it actually mixes. Built for people who want pasture protein with receipts, not a flavored candy tub.",
    location: "Houston, TX / Kilkenny, Ireland",
    founded: 2019,
    categories: ["protein"],
    accent: "#2C5F4E",
    rating: 4.9,
    reviewCount: 1600,
    followerCount: 19000,
    websiteUrl: "https://agnroots.com",
    logoUrl: "/brands/agn-roots.svg",
  },
  {
    id: "c688",
    slug: "centenarius",
    name: "Centenarius Nutrition",
    tagline: "Irish grass-fed isolate, marine collagen, and magnesium — one ingredient, no bloating theater",
    story: "A purity-first nutrition shop: 27 g Irish pasture whey isolate, lactose-free, heavy-metal tested, plus marine collagen and magnesium for the days that aren't just a shake. Animal-welfare certified sourcing, ice-cold filtration, and labels that skip the filler drawer.",
    location: "United States",
    founded: 2021,
    categories: ["protein","supplements"],
    accent: "#4A7C59",
    rating: 4.7,
    reviewCount: 320,
    followerCount: 7400,
    websiteUrl: "https://centenariusnutrition.com",
    logoUrl: "/brands/centenarius.svg",
  },
  {
    id: "c689",
    slug: "slo-naturals",
    name: "Slo Naturals",
    tagline: "Aotearoa organic deodorant, hair clay, and toothpaste in compostable tubes",
    story: "A New Zealand kitchen pouring certified-organic deodorant, dry shampoo, hair clay, mouthwash, and lip balm into FSC compostable tubes. At least 70% organic, PETA vegan, no aluminum, no parabens, no synthetic fragrance fog. Made in Aotearoa for people who want plant-powered pits and hair without a plastic stick graveyard.",
    location: "New Zealand",
    founded: 2018,
    categories: ["deodorant","hair","oral","skincare"],
    accent: "#7EB8A2",
    rating: 4.8,
    reviewCount: 1100,
    followerCount: 16000,
    websiteUrl: "https://slonaturals.com",
    logoUrl: "/brands/slo-naturals.svg",
  },
  {
    id: "c690",
    slug: "ommade",
    name: "OmMade Organic Skincare",
    tagline: "South Australian naturopathic care — if you can't eat it, don't put it on your skin",
    story: "A decade-plus Adelaide apothecary: palm-oil-free moisturisers, magnesium deodorant, charcoal toothpaste, zinc sun lotion, and hemp serums made in small batches. No synthetic fragrance, no filler oils, just food-grade botanicals from a founder who healed adult acne by treating skin like something you nourish.",
    location: "South Australia",
    founded: 2014,
    categories: ["skincare","deodorant","oral","sunscreen","hair"],
    accent: "#6B3E26",
    rating: 4.8,
    reviewCount: 860,
    followerCount: 14000,
    websiteUrl: "https://www.ommadeorganicskincare.com",
    logoUrl: "/brands/ommade.svg",
  },
  {
    id: "c691",
    slug: "elims",
    name: "ELIMS",
    tagline: "Dentist-crafted 10% nano-hydroxyapatite toothpaste in foodie flavors, fluoride-free",
    story: "Dr. Casey Lau's oral-care studio: 10% nano-hydroxyapatite, xylitol, and coconut oil in lavender-vanilla-mint and pineapple-orange-mint — no fluoride, no SLS, no artificial dye. Recycled tubes and a take-back program for people who want enamel rebuilt, not a neon gel from the pharmacy aisle.",
    location: "United States",
    founded: 2021,
    categories: ["oral"],
    accent: "#574CD5",
    rating: 4.6,
    reviewCount: 980,
    followerCount: 27000,
    websiteUrl: "https://elims.co",
    logoUrl: "/brands/elims.svg",
  },
  {
    id: "c692",
    slug: "duo-toothpaste",
    name: "Duo",
    tagline: "NY-made nHA toothpaste tablets in glass — plastic-free, SLS-free, dentist-founded",
    story: "Two Seattle dentists who got tired of plastic tubes and drying detergents. Chewable nHA tablets in apothecary glass, compostable refill pouches, and optional immunity, energy, or sleep support absorbed as you brush. Vegan, fluoride-free, made in a New York cGMP kitchen — the future of brushing without a 500-year tube.",
    location: "New York / Seattle",
    founded: 2022,
    categories: ["oral"],
    accent: "#2C5F4E",
    rating: 4.9,
    reviewCount: 237,
    followerCount: 8900,
    websiteUrl: "https://duotoothpaste.com",
    logoUrl: "/brands/duo-toothpaste.svg",
  },
  {
    id: "c693",
    slug: "fawn-lily",
    name: "Fawn Lily Botanica",
    tagline: "Oregon handmade herbal serums, toners, and salves from a 25-year kitchen",
    story: "Irene's Eugene warehouse has been infusing organic herbs for a quarter century: facial oils, hydrosol toners, body butters, and herbal salves made by hand from foraged and fair-trade botanicals. No synthetic fragrance, no mystery preservative fog — traditional herbalism for skin the industry usually forgets.",
    location: "Eugene, OR",
    founded: 2001,
    categories: ["skincare"],
    accent: "#C4A484",
    rating: 4.8,
    reviewCount: 2400,
    followerCount: 38000,
    websiteUrl: "https://fawnlilybotanica.com",
    logoUrl: "/brands/fawn-lily.png",
  },
  {
    id: "c694",
    slug: "bears-beauty",
    name: "Bear's Beauty",
    tagline: "Colorado hormone-safe, low-PUFA, coconut-free balms for acne-prone skin",
    story: "Jerra's mountain kitchen: palm-free, coconut-free, xenoestrogen-free balms and cleansers for PCOS, acne, and ultra-sensitive skin. Organic beeswax, magnesium brine, and plant-based 'un-tallow' — food-grade, low-PUFA, and poured in small batches that fund an animal sanctuary. Skincare that refuses endocrine disruptors.",
    location: "Colorado",
    founded: 2013,
    categories: ["skincare"],
    accent: "#8B7355",
    rating: 4.8,
    reviewCount: 510,
    followerCount: 9200,
    websiteUrl: "https://bearsbeautyskincare.com",
    logoUrl: "/brands/bears-beauty.svg",
  },
  {
    id: "c695",
    slug: "beneath-your-mask",
    name: "Beneath Your Mask",
    tagline: "Lupus-born whipped soufflés and lip balms with a short, non-toxic list",
    story: "Dana Jackson built this line after lupus wrecked her skin and hair and the drugstore aisle had nothing clean enough. Whipped soufflés, conditioning lip balms, and mini rituals with pure botanicals — no synthetic fragrance fog, no mystery preservative stack. Healing-first formulas from someone who needed them.",
    location: "United States",
    founded: 2016,
    categories: ["skincare"],
    accent: "#B85C38",
    rating: 4.7,
    reviewCount: 680,
    followerCount: 21000,
    websiteUrl: "https://beneathyourmask.com",
    logoUrl: "/brands/beneath-your-mask.svg",
  },
  {
    id: "c696",
    slug: "cornish-seaweed",
    name: "The Cornish Seaweed Bath Co",
    tagline: "Hand-harvested organic Cornish seaweed shampoo, conditioner, and bath rituals",
    story: "A Penzance house since 2013: sustainably hand-harvested organic seaweed in shampoo, conditioner, body wash, cold-process soap, and facial oils. Fragrance-free options for itchy scalps, recyclable aluminium bottles, and a sea-to-skin ritual that skips the salon chemical fog.",
    location: "Penzance, Cornwall",
    founded: 2013,
    categories: ["hair","skincare"],
    accent: "#1A5276",
    rating: 4.7,
    reviewCount: 1900,
    followerCount: 24000,
    websiteUrl: "https://cornishseaweedbath.co.uk",
    logoUrl: "/brands/cornish-seaweed.svg",
  },
  {
    id: "c697",
    slug: "eczema-kids",
    name: "Eczema Kids",
    tagline: "Tallow-and-zinc mineral sunscreen and barrier care for flare-prone little skin",
    story: "A parent-built eczema kitchen: uncoated non-nano zinc on a base of tallow, jojoba, and beeswax so sun protection doesn't sting. Zero chemical filters, zero synthetic fragrance, zero 'natural' essential-oil theater that flares kids. Reef-safer mineral coverage for families who have already tried everything.",
    location: "United States",
    founded: 2022,
    categories: ["sunscreen","skincare"],
    accent: "#3D8B6E",
    rating: 4.8,
    reviewCount: 290,
    followerCount: 6400,
    websiteUrl: "https://eczemakids.com",
    logoUrl: "/brands/eczema-kids.svg",
  },
  {
    id: "c698",
    slug: "mama-natural",
    name: "Mama Natural",
    tagline: "USDA Organic one-a-day prenatal from food-based vitamins, no synthetic filler pile",
    story: "Genevieve Parker's pregnancy-education house turned into a real supplement: one small USDA Organic tablet with 19 vitamins and 12 antioxidant foods, third-party tested, vegan, and free of the usual prenatal dye-and-filler stack. Built for morning-sickness days when you can swallow exactly one thing.",
    location: "United States",
    founded: 2014,
    categories: ["supplements"],
    accent: "#C4A35A",
    rating: 4.7,
    reviewCount: 3200,
    followerCount: 180000,
    websiteUrl: "https://shop.mamanatural.com",
    logoUrl: "/brands/mama-natural.png",
  },
  {
    id: "c699",
    slug: "nunona",
    name: "Nunona",
    tagline: "Dietitian-made real-food prenatal bites — 27 micronutrients, nothing synthetic",
    story: "A motherhood-nutrition studio that skipped the horse-pill prenatal. Organic whole-food bites with 27 micronutrients, 3rd-party heavy-metal testing, and no synthetic vitamin theater — from preconception through postpartum milk. A snack that is the vitamin, not a candy gummy pretending to be one.",
    location: "United States",
    founded: 2021,
    categories: ["supplements"],
    accent: "#E27D60",
    rating: 4.8,
    reviewCount: 540,
    followerCount: 28000,
    websiteUrl: "https://www.nunonalife.com",
    logoUrl: "/brands/nunona.svg",
  },
  {
    id: "c700",
    slug: "fresh-heritage",
    name: "Fresh Heritage",
    tagline: "Brothers' beard oils and grooming kits for textured hair, no drugstore cologne cloud",
    story: "Jamil and Gamal Codner brought traditional African grooming oils back from a trip and built a line for men of color: beard oils, grooming kits, and simple tools without the synthetic cologne fog. Small-batch care for textured hair and skin that the drugstore aisle still treats as an afterthought.",
    location: "United States",
    founded: 2016,
    categories: ["hair"],
    accent: "#6B3E26",
    rating: 4.6,
    reviewCount: 1200,
    followerCount: 42000,
    websiteUrl: "https://freshheritage.com",
    logoUrl: "/brands/fresh-heritage.svg",
  },
];
