import type { Brand } from "./types";

/** Wave 75: small organic / toxic-free brands across marketplace categories (c1319+). */
export const catalogBrandsWave75: Brand[] = [
  {
    id: "c1319",
    slug: "ollie",
    name: "Ollie",
    tagline: "10% nano-hydroxyapatite toothpaste in Clean Mint, Strong Mint, Cinnamon, Orange, and Strawberry",
    story: "A US oral house built around 10% nHAp remineralizing paste — flavors already live on separate titles (Clean Mint, Strong Mint, Cinnamon, Orange, Strawberry) plus a fluoride + nHAp Fresh Mint tube. Pack count is size. Bundles, duos, trial packs, sample packs, donation kits, electric brushes, replacement heads, charging cords, whitening strips, and test listings stay boxed. Product pages are key-ingredient marketing (leave empty).",
    location: "United States",
    founded: 2021,
    categories: ["oral"],
    accent: "#2F7A6B",
    rating: 4.7,
    reviewCount: 420,
    followerCount: 14000,
    websiteUrl: "https://olliesmile.com",
    logoUrl: "/brands/ollie.svg",
  },
  {
    id: "c1320",
    slug: "purelytes",
    name: "Purelytes",
    tagline: "Zero-junk electrolytes flavored with organic freeze-dried fruit and sweetened with panela",
    story: "A small hydration house skipping stevia, monk fruit, and citric acid — Lemon-Lime, Mango, Pineapple, Strawberry, plus sweetened and unsweetened unflavored. Flavors already live on separate titles. Serving count is size. Cart.js is USD. Pages are ratio-marketing (leave empty).",
    location: "United States",
    founded: 2023,
    categories: ["electrolytes"],
    accent: "#E07A3D",
    rating: 4.6,
    reviewCount: 64,
    followerCount: 1800,
    websiteUrl: "https://getpurelytes.com",
    logoUrl: "/brands/purelytes.svg",
  },
  {
    id: "c1321",
    slug: "tidlos",
    name: "TIDLØS",
    tagline: "Three-ingredient New Zealand grass-fed whey sweetened with organic dates",
    story: "A founder-owned protein house sourcing non-denatured New Zealand grass-fed whey concentrate and flavoring it with real food — Vanilla (dates + Madagascar vanilla), Chocolate (dates + cacao), and Snickerdoodle (dates + Ceylon cinnamon + vanilla). Flavour expands. Energy gels, sample packs, and the smoothie ebook stay boxed. Published formula is whey + dates + the named flavor food.",
    location: "United States",
    founded: 2024,
    categories: ["protein"],
    accent: "#2B3A2E",
    rating: 4.8,
    reviewCount: 86,
    followerCount: 2400,
    websiteUrl: "https://tidlos.co",
    logoUrl: "/brands/tidlos.svg",
  },
  {
    id: "c1322",
    slug: "little-hands-hawaii",
    name: "Little Hands Hawaii",
    tagline: "Honolulu kitchen-born reef-safe mineral sunscreen with non-nano zinc and plastic-free tins",
    story: "A Honolulu nurse-mom house pouring non-nano zinc for keiki and reef since 2011 — Body & Face, baby, travel, and sport-stick formulas plus a grass-fed Hawaii tallow everything balm. Sunscreen Color expands Original / Light Neutral / Medium Neutral / Medium Dark / Dark. Whip Scent expands. Tin vs stick vs travel is size. Combos, big-wave bundles, and gift sets stay boxed. Sunscreen and balm pages publish Active / Inactive lists.",
    location: "Honolulu, HI",
    founded: 2011,
    categories: ["sunscreen","skincare"],
    accent: "#D4A054",
    rating: 4.8,
    reviewCount: 210,
    followerCount: 7200,
    websiteUrl: "https://littlehandshawaii.com",
    logoUrl: "/brands/little-hands-hawaii.svg",
  },
  {
    id: "c1323",
    slug: "lavami",
    name: "Lavami",
    tagline: "Calgary small-batch shampoo bars, conditioner bars, and gentle soaps for dry and sensitive skin",
    story: "A Calgary house started by Noni Doig after years of eczema and psoriasis — Juicy, Revitalize, and Restore solid hair bars plus named soaps, lotions, and short-list face oils. Shampoo and conditioner Scent expands Regular / Unscented. Box vs no-box is packaging, not flavor. Gift cards, trios, sets, bundles, and scalp massagers stay boxed. Cart.js is CAD × 0.73. Pages are key-ingredient essays (leave empty).",
    location: "Calgary, AB",
    founded: 2018,
    categories: ["hair","skincare"],
    accent: "#C4788A",
    rating: 4.7,
    reviewCount: 118,
    followerCount: 3600,
    websiteUrl: "https://www.lavami.ca",
    logoUrl: "/brands/lavami.svg",
  },
  {
    id: "c1324",
    slug: "mushroom-microfarm",
    name: "Mushroom Microfarm",
    tagline: "Small-batch dual-extract lion's mane, reishi, cordyceps, chaga, and turkey tail tinctures",
    story: "A micro-farm extract house dual-extracting lion's mane, reishi, cordyceps, chaga, turkey tail, and Japanese knotweed. One ounce vs two ounces is size. Tees, totes, tincture bundles, fresh culinary mushrooms, grow kits, and courses stay boxed. Product pages are use-case essays (leave empty).",
    location: "United States",
    founded: 2021,
    categories: ["supplements"],
    accent: "#4A5A32",
    rating: 4.6,
    reviewCount: 34,
    followerCount: 1100,
    websiteUrl: "https://mushroom-microfarm.myshopify.com",
    logoUrl: "/brands/mushroom-microfarm.svg",
  },
];
