import type { Brand } from "./types";

/** Wave 91: small organic / toxic-free brands across marketplace categories (c1415+). */
export const catalogBrandsWave91: Brand[] = [
  {
    id: "c1415",
    slug: "denttabs",
    name: "Denttabs",
    tagline: "Berlin toothpaste tablets with cellulose polish — mint, strawberry, and cinnamon, with or without fluoride",
    story: "The leftover unused German tablet house after dedicated multi-SKU n-HA shops ran out — foam-free microcrystalline-cellulose tablets that polish instead of paste. Flavors already live on separate 125-count titles (Mint / Strawberry with or without fluoride) plus cinnamon in a 250-count glass. Jahresvorrat / Halbjahresvorrat / 1 kg / kids sets / trial sachets / the book stay boxed. Keep one bamboo brush. Cart.js is **EUR** × 1.08 (€7.95 → $8.59). Hardcode the published cellulose / bicarbonate INCI.",
    location: "Berlin, Germany",
    founded: 2003,
    categories: ["oral"],
    accent: "#2F6B4A",
    rating: 4.6,
    reviewCount: 2100,
    followerCount: 18000,
    websiteUrl: "https://denttabs.com",
    logoUrl: "/brands/denttabs.svg",
  },
  {
    id: "c1416",
    slug: "stay-poised-naturals",
    name: "Stay Poised Naturals",
    tagline: "Great Salt Lake electrolytes with New Zealand mānuka honey and magnesium glycinate — no sucralose",
    story: "The unused one-SKU Great Salt Lake leftover after wave4–90 — Complete HYDRATION stick packs in Strawberry Lemonade, built around Utah lake minerals, mānuka honey, and magnesium glycinate. Flavor is already on the title. Stick count (10 / 16 / 30) is size — keep the 30-stick monthly. Cart.js is USD. Pages are performance marketing (leave empty).",
    location: "Utah",
    founded: 2023,
    categories: ["electrolytes"],
    accent: "#1F4E6B",
    rating: 4.6,
    reviewCount: 48,
    followerCount: 1200,
    websiteUrl: "https://staypoisednaturals.com",
    logoUrl: "/brands/stay-poised-naturals.svg",
  },
  {
    id: "c1417",
    slug: "purely-tallow",
    name: "Purely Tallow",
    tagline: "Family-made grass-fed tallow mineral SPF 25/35, hair oil, and whipped lotion",
    story: "The leftover unused tallow sun + hair house after wave4–90 — Serena’s family formulas pair grass-fed tallow with non-nano zinc for SPF 25 and SPF 35, plus hair-and-beard oil, soap, lotion, and lip tins. Approximate SPF expands the sunscreen. Scent / Variety / Options expand soap, lotion, spray, cleanser, mask, lip, and hair oil. 2 oz vs 4 oz / tube vs jar is size. Perfume (Pure-Fume), candles, gift cards, travel-size mixed SKUs, and bundles stay boxed. Cart.js is USD. Hardcode the published two-ingredient soap list — sun and lotion pages are ancestral-story marketing (leave empty).",
    location: "United States",
    founded: 2022,
    categories: ["sunscreen","hair","skincare"],
    accent: "#8B5A2B",
    rating: 4.8,
    reviewCount: 320,
    followerCount: 5400,
    websiteUrl: "https://purelytallow.com",
    logoUrl: "/brands/purely-tallow.svg",
  },
  {
    id: "c1418",
    slug: "dense-nutrition",
    name: "Dense Nutrition",
    tagline: "Alpine grass-fed whey, beef protein, and SALTE electrolytes — no sucralose",
    story: "The unused nose-to-tail protein leftover after wave4–90 — Alpine grass-fed whey concentrate (Flavor expands Unflavored Organic / Vanilla / Chocolate), grass-fed beef protein, collagen, bone-broth protein, colostrum, and organs, plus SALTE stick electrolytes (Flavour expands Unflavoured / Lemon / Orange / Strawberry / Apple / Watermelon / Pineapple). Variety packs, shakers, scoops, ghee, salt, vinegar, and broth jars stay boxed. Cart.js is **EUR** × 1.08 (€34.90 → $37.69). Pages are nutrient-density marketing (leave empty).",
    location: "Netherlands",
    founded: 2021,
    categories: ["protein","electrolytes","supplements"],
    accent: "#3D2B1F",
    rating: 4.7,
    reviewCount: 410,
    followerCount: 6800,
    websiteUrl: "https://densenutrition.com",
    logoUrl: "/brands/dense-nutrition.svg",
  },
  {
    id: "c1419",
    slug: "tallow-and-vine",
    name: "Tallow & Vine",
    tagline: "Small-batch grass-fed tallow deodorant, Manuka balm, and botanical after-sun",
    story: "The unused tallow deodorant leftover after wave4–90 — aluminum-free sticks with tallow, arrowroot, kaolin, and non-nano zinc, plus six-ingredient Manuka-chamomile balm, whipped vanilla balm, sea-moss body oil, and a published-INCI after-sun tin. Keep the 1-pack deodorant. 2-packs, peppermint 2-pack, zinc sun-stick 2-pack, and rescue/duo bundles stay boxed. Cart.js is USD. Hardcode the published after-sun comma list.",
    location: "United States",
    founded: 2023,
    categories: ["deodorant","skincare","sunscreen"],
    accent: "#5C6B3A",
    rating: 4.7,
    reviewCount: 86,
    followerCount: 1900,
    websiteUrl: "https://tallowandvine.com",
    logoUrl: "/brands/tallow-and-vine.svg",
  },
  {
    id: "c1420",
    slug: "octagon-farm",
    name: "Octagon Farm",
    tagline: "Vermont dual-extract mushroom and herbal tinctures from a basement grow room and woods",
    story: "The leftover unused Vermont tincture house after wave4–90 — chaga-started Octagon Farm grows lion’s mane, reishi, cordyceps, and turkey tail, then bottles dual extracts next to foraged and garden herbs (echinacea, tulsi, skullcap, usnea). Size is 1 oz vs 2 oz / 4 oz — keep 1 oz. Wild vs cultivated on reishi is source, not a flavor. Cart.js is USD. Pages are farm-story marketing (leave empty).",
    location: "Northern Vermont",
    founded: 2018,
    categories: ["supplements"],
    accent: "#3F5D3B",
    rating: 4.8,
    reviewCount: 74,
    followerCount: 1600,
    websiteUrl: "https://octagonfarm.shop",
    logoUrl: "/brands/octagon-farm.svg",
  },
];
