import type { Brand } from "./types";

/** Wave 46: small organic / toxic-free brands across marketplace categories (c1136+). */
export const catalogBrandsWave46: Brand[] = [
  {
    id: "c1136",
    slug: "laro-london",
    name: "Laro",
    tagline: "London hydroxyapatite toothpaste — fluoride-free, SLS-free, plastic-free tubes",
    story: "A London oral house that puts pharmaceutical-grade hydroxyapatite in a zero-plastic tube: fluoride-free, SLS-free, and microbiome-gentle. Keep the whitening toothpaste, alcohol-free mouth rinses, and Koh-I-Noor toothbrushes. Washbags, travel edits, quarterly bundles, and signature sets stay at the sink.",
    location: "London, England",
    founded: 2023,
    categories: ["oral"],
    accent: "#2C5F4E",
    rating: 4.7,
    reviewCount: 124,
    followerCount: 3800,
    websiteUrl: "https://larolondon.com",
    logoUrl: "/brands/laro-london.svg",
  },
  {
    id: "c1137",
    slug: "cove-suncare",
    name: "Cove Suncare",
    tagline: "Hayward mineral SPF for eczema-prone skin — non-nano zinc, reef-friendly",
    story: "A 2025 Hayward, California mineral house from a cosmetic-sourcing founder who could not find sunscreen her eczema-prone skin would wear. Three formulas stay: fragrance-free Skinny Dip SPF 50, lotion-feel Block Party SPF 50, and Mist Me SPF 40. Non-nano zinc, reef-friendly, no merch wall.",
    location: "Hayward, California",
    founded: 2025,
    categories: ["sunscreen"],
    accent: "#4A7C8C",
    rating: 4.6,
    reviewCount: 18,
    followerCount: 1400,
    websiteUrl: "https://www.covesuncare.com",
    logoUrl: "/brands/cove-suncare.svg",
  },
  {
    id: "c1138",
    slug: "skinmetal",
    name: "Skinmetal",
    tagline: "Madison mineral SPF 51 for boys and young men — non-nano zinc, no retail displays",
    story: "A Madison, Wisconsin mineral house founded by a pediatrician and melanoma survivor. Daily Metal Stealth is 12% non-nano zinc with niacinamide; Green Stealth adds bakuchiol. Keep daily, weekly, and one-day packets. Retail displays, socks, shirts, hats, and keychains stay in the foundry.",
    location: "Madison, Wisconsin",
    founded: 2025,
    categories: ["sunscreen"],
    accent: "#1B4F72",
    rating: 4.6,
    reviewCount: 42,
    followerCount: 2200,
    websiteUrl: "https://www.skinmetal.com",
    logoUrl: "/brands/skinmetal.svg",
  },
  {
    id: "c1139",
    slug: "ancient-nature",
    name: "Ancient Nature",
    tagline: "Los Angeles bison-tallow deodorant, sun balm, and cream — single-ranch, no aluminum",
    story: "A Los Angeles kitchen that pours grass-fed bison tallow from one Sierra Nevada ranch into an aluminum-free mineral deodorant, a zinc sun balm, hydrating cream, coffee exfoliant, and lip balm flavors. Individual jars stay. The discovery trio stays out so each formula can live as its own listing.",
    location: "Los Angeles, California",
    founded: 2024,
    categories: ["deodorant","sunscreen","skincare"],
    accent: "#6B4F2A",
    rating: 4.7,
    reviewCount: 86,
    followerCount: 3100,
    websiteUrl: "https://tryancientnature.com",
    logoUrl: "/brands/ancient-nature.svg",
  },
  {
    id: "c1140",
    slug: "allnat",
    name: "AllNat Co.",
    tagline: "Wisconsin grass-fed tallow + UMF 15+ manuka honey — whipped creams, no gift sets",
    story: "A small tallow house that whips organic Wisconsin grass-fed tallow with high-grade New Zealand manuka honey into glow cream, body butter, lip balm flavors, and a botanical face oil. Scent variants expand. Discovery sets, bestsellers bundles, and Try 2 stacks stay in the kitchen.",
    location: "United States",
    founded: 2023,
    categories: ["skincare"],
    accent: "#C4A35A",
    rating: 4.8,
    reviewCount: 210,
    followerCount: 5400,
    websiteUrl: "https://allnatco.com",
    logoUrl: "/brands/allnat.svg",
  },
  {
    id: "c1141",
    slug: "drgn-salt",
    name: "DRGN SALT",
    tagline: "1,200mg sodium zero-sugar electrolytes — Himalayan salt, watermelon / orange / lime",
    story: "A high-sodium hydration house built for heavy sweaters: 1,200mg sodium from pink Himalayan salt, potassium, and magnesium, zero sugar, stevia-sweetened. Flavor tubs expand. Hats, headbands, starter kits, and summer bundles stay on the sideline.",
    location: "United States",
    founded: 2024,
    categories: ["electrolytes"],
    accent: "#C45C26",
    rating: 4.6,
    reviewCount: 74,
    followerCount: 1900,
    websiteUrl: "https://drgnsalt.com",
    logoUrl: "/brands/drgn-salt.svg",
  },
  {
    id: "c1142",
    slug: "electrolete",
    name: "ELECTROLETE",
    tagline: "Plant City NSF-minded hydration — Limoné Rouge, no sugar, no merch wall",
    story: "A Florida hydration startup from Plant City: six electrolytes and four vitamins, zero sugar, zero artificial dyes, in one lemon-raspberry scoop. Keep Limoné Rouge. Performance hats, tanks, and tees stay in the dugout.",
    location: "Plant City, Florida",
    founded: 2026,
    categories: ["electrolytes"],
    accent: "#2A6F6A",
    rating: 4.5,
    reviewCount: 28,
    followerCount: 900,
    websiteUrl: "https://drinkelectrolete.com",
    logoUrl: "/brands/electrolete.svg",
  },
  {
    id: "c1143",
    slug: "protein-b",
    name: "Protein B",
    tagline: "Grass-fed clear whey with collagen and electrolytes — juice-light, no sample flight",
    story: "A small clear-whey house that drinks like juice: 22g grass-fed whey, 2.5g collagen, and 450mg electrolytes in mango pineapple passionfruit, dragonfruit lemonade, and coconut raspberry. Flavor options expand. Sample packets and the variety flight stay out so each tub can stand alone.",
    location: "United States",
    founded: 2024,
    categories: ["protein"],
    accent: "#8B3A4A",
    rating: 4.6,
    reviewCount: 96,
    followerCount: 2700,
    websiteUrl: "https://proteinb.com",
    logoUrl: "/brands/protein-b.svg",
  },
  {
    id: "c1144",
    slug: "kind2",
    name: "KIND2",
    tagline: "London plastic-free shampoo and conditioner bars — pH-balanced, no loofah wall",
    story: "A UK solid-hair house that swaps bottles for concentrated, plastic-free bars: hydrating, fragrance-free, rosemary-caffeine growth, metal-detox, and matching conditioners. Individual bars stay. Loofahs, jade rollers, hair ties, dog chews, gift cards, trays, and duplicate parent SKUs stay packed away. GBP converts to USD.",
    location: "London, England",
    founded: 2018,
    categories: ["hair"],
    accent: "#5B7A3A",
    rating: 4.7,
    reviewCount: 640,
    followerCount: 12000,
    websiteUrl: "https://kind2.me",
    logoUrl: "/brands/kind2.svg",
  },
  {
    id: "c1145",
    slug: "soapwalla",
    name: "Soapwalla",
    tagline: "Brooklyn vegan deodorant creams, soaps, and serums — aluminum-free, small-batch",
    story: "A Brooklyn studio that still hand-mixes aluminum-free deodorant creams, organic soaps, facial serums, body oils, and lip balms from food-grade botanicals. Individual formulas stay. Gift sets, quartets, travel minis, totes, gift cards, shipping insurance, hand washes, and soaking salts stay in the studio.",
    location: "Brooklyn, New York",
    founded: 2009,
    categories: ["deodorant","skincare"],
    accent: "#7A5C3A",
    rating: 4.6,
    reviewCount: 1800,
    followerCount: 24000,
    websiteUrl: "https://www.soapwalla.com",
    logoUrl: "/brands/soapwalla.svg",
  },
];
