import type { Brand } from "./types";

/** Wave 100: small organic / toxic-free brands across marketplace categories (c1469+). */
export const catalogBrandsWave100: Brand[] = [
  {
    id: "c1469",
    slug: "nudge",
    name: "nudge",
    tagline: "10% nano-hydroxyapatite toothpaste — fluoride-free, SLS-free, lab-tested",
    story:
      "Harrisburg leftover unused multi-SKU n-HA house after wave4–99 shops ran out. Keep Natural Mint / Orange / Watermelon / Cinnamon and Clove toothpaste, Mint / Cinnamon and Clove tablets, alcohol-free mouthwash, PFAS-free silk floss, bamboo brushes, and probiotic gum. Pack count is size. Oral-care box, whitening kit/pen, purple serum, and travel pouch stay boxed. Cart.js is USD. Pages are key-ingredient marketing (leave empty).",
    location: "Harrisburg, PA",
    founded: 2023,
    categories: ["oral"],
    accent: "#2F6B4F",
    rating: 4.7,
    reviewCount: 186,
    followerCount: 4200,
    websiteUrl: "https://shopnudge.com",
    logoUrl: "/brands/nudge.svg",
  },
  {
    id: "c1470",
    slug: "cocobana",
    name: "CocoBana",
    tagline: "Five-ingredient electrolytes — coconut, banana, lemon, sea salt, marine magnesium",
    story:
      "Unused one-SKU real-fruit hydration house after wave4–99. Keep the clean electrolyte stick packs. No stevia, no monk fruit, no natural flavors. Cart.js is USD. Hardcode the published five-ingredient list.",
    location: "United States",
    founded: 2024,
    categories: ["electrolytes"],
    accent: "#E8B84A",
    rating: 4.6,
    reviewCount: 74,
    followerCount: 1100,
    websiteUrl: "https://drinkcocobana.com",
    logoUrl: "/brands/cocobana.svg",
  },
  {
    id: "c1471",
    slug: "rare-forms",
    name: "Rare Forms",
    tagline: "UK all-in-one whey isolate — creatine, collagen, and daily minerals in one scoop",
    story:
      "Unused London performance-protein house. Keep Performance Blend and Protein & Collagen Blend. Flavour is Vanilla-only. Shaker, straw, bottle, tumbler, and gift card stay boxed. Cart.js is GBP (× 1.27). Pages are stack-essay marketing (leave empty).",
    location: "United Kingdom",
    founded: 2023,
    categories: ["protein", "supplements"],
    accent: "#1F3A4D",
    rating: 4.6,
    reviewCount: 92,
    followerCount: 1600,
    websiteUrl: "https://rareforms.co",
    logoUrl: "/brands/rare-forms.svg",
  },
  {
    id: "c1472",
    slug: "birch-babe",
    name: "Birch Babe",
    tagline: "Canadian mineral SPF 40, CertClean skin, and sulfate-free shampoo bars",
    story:
      "Leftover unused Ontario mineral SPF + wash-day house after wave4–99 (sample/$0-gift-heavy). Scent expands SPF, body quench, body oils, baby lotion/wash, and beard. Bar Type expands body/face/shave/exfoliating bars. Keep full-size serums, creams, toner, micellar, mouthwash, and diaper balm. Samples, $0 gifts, bulk, wholesale, bundles, kits, and merch stay boxed. Cart.js is CAD (× 0.73). Hardcode published SPF + mouthwash INCI; other pages are benefit marketing (leave empty).",
    location: "Ontario, Canada",
    founded: 2016,
    categories: ["sunscreen", "skincare", "hair", "oral"],
    accent: "#3D6B4F",
    rating: 4.8,
    reviewCount: 640,
    followerCount: 18000,
    websiteUrl: "https://birchbabe.com",
    logoUrl: "/brands/birch-babe.svg",
  },
  {
    id: "c1473",
    slug: "magic-moo-tallow",
    name: "Magic Moo Tallow",
    tagline: "Grass-fed tallow deodorant, mineral sun protectant, and whipped ancestral balms",
    story:
      "Leftover unused tallow deodorant + sun protectant house after wave4–99. Scent expands Lavender Mint / Cedar Spruce / Cocoa Clementine deodorant. Keep sun protectant, all-purpose whip and stick, magnesium whip, men's salve, vanilla everywhere cream, emu elixir, and Magic Mist. Bundles, gift cards, illuminator, and lip-balm trio stay boxed. Jar oz is size. Cart.js is USD. Hardcode published deodorant + magnesium lists; sun page is a farm essay (leave empty).",
    location: "United States",
    founded: 2022,
    categories: ["deodorant", "sunscreen", "skincare"],
    accent: "#C4A574",
    rating: 4.8,
    reviewCount: 210,
    followerCount: 5400,
    websiteUrl: "https://magicmootallow.com",
    logoUrl: "/brands/magic-moo-tallow.svg",
  },
  {
    id: "c1474",
    slug: "mogo-farm",
    name: "Mogo Farm",
    tagline: "Derbyshire fruiting-body tinctures — grown, extracted, and bottled on the farm",
    story:
      "Unused Peak District dual-extract house after wave4–99. Keep Lion's Mane, Reishi, Cordyceps, Chaga, Shiitake, Maitake, Birch Polypore, and 5 Mushroom Blend. Free gift, 6-tincture bundle, and gift card stay boxed. Cart.js is GBP (× 1.27). Hardcode published fruiting-body + dual-extract lists.",
    location: "Derbyshire, United Kingdom",
    founded: 2021,
    categories: ["supplements"],
    accent: "#5A3D2B",
    rating: 4.8,
    reviewCount: 980,
    followerCount: 7200,
    websiteUrl: "https://mogofarm.co.uk",
    logoUrl: "/brands/mogo-farm.svg",
  }
];
