import type { Brand } from "./types";

/** Wave 47: small organic / toxic-free brands across marketplace categories (c1146+). */
export const catalogBrandsWave47: Brand[] = [
  {
    id: "c1146",
    slug: "amallow",
    name: "Amallow",
    tagline: "Grass-fed tallow deodorant, sun balm, and whipped cream — aluminum-free, baking-soda-free",
    story: "A husband-and-wife tallow house that hand-pours aluminum-free, baking-soda-free deodorant, a zinc sun balm, whipped tallow creams, goat-milk soaps, and a rice-powder cleanser. Scent variants expand. Perfume rollers, candles, leather conditioner, merch, gift cards, and ritual bundles stay in the kitchen.",
    location: "United States",
    founded: 2023,
    categories: ["deodorant","sunscreen","skincare","hair"],
    accent: "#C4A35A",
    rating: 4.7,
    reviewCount: 980,
    followerCount: 12000,
    websiteUrl: "https://amallow.com",
    logoUrl: "/brands/amallow.svg",
  },
  {
    id: "c1147",
    slug: "dersie",
    name: "Dersie",
    tagline: "Grass-fed tallow mineral SPF 50 — non-nano zinc, whipped balm, batana hair",
    story: "A St. Louis tallow house built around non-nano zinc SPF 50 (stick and cream), a whipped beef-tallow balm, frankincense balm, magnesium cream, and batana shampoo, conditioner, and oil. Keep the mineral sunscreens, balms, cream, and individual hair bottles. Multi-packs, rice-water duos, and ritual oil sets stay boxed.",
    location: "St. Louis, Missouri",
    founded: 2024,
    categories: ["sunscreen","skincare","hair"],
    accent: "#6B4F2A",
    rating: 4.5,
    reviewCount: 210,
    followerCount: 4200,
    websiteUrl: "https://dersie.com",
    logoUrl: "/brands/dersie.svg",
  },
  {
    id: "c1148",
    slug: "cooki-haircare",
    name: "Cooki Haircare",
    tagline: "Sydney plastic-free shampoo and conditioner bars — sulfate-free, no gift-box wall",
    story: "A female-founded Sydney solid-hair house that swaps bottles for concentrated, plastic-free bars: rice-water protein, argan, coconut, ginger, peppermint, cinnamon, lemon, jasmine, and purple toning, plus matching conditioners, hair masks, and a rosemary growth oil. Individual bars stay. Jumbo duos, gift boxes, starter packs, tins, brushes, combs, loofahs, and dishes stay packed away. AUD converts to USD.",
    location: "Sydney, Australia",
    founded: 2019,
    categories: ["hair","skincare"],
    accent: "#C45C26",
    rating: 4.8,
    reviewCount: 9000,
    followerCount: 18000,
    websiteUrl: "https://www.haircooki.com.au",
    logoUrl: "/brands/cooki-haircare.svg",
  },
  {
    id: "c1149",
    slug: "wayward-chickadee",
    name: "Wayward Chickadee",
    tagline: "Maine plant-based shampoo bars, citrus deodorant, and cold-process soaps — plastic-free",
    story: "A Maine maker that handcrafts plant-based solid shampoos, a ylang-lavender conditioner bar, a sweet-citrus natural deodorant, Edelweiss serum, lip and hand balms, and cold-process soaps in compostable packaging. Individual formulas stay. Candles, zipper pouches, gift cards, konjac sponges, mosquito sprays, soap dishes, and sample boxes stay in the woodshed.",
    location: "Maine",
    founded: 2018,
    categories: ["hair","deodorant","skincare"],
    accent: "#2C5F4E",
    rating: 4.7,
    reviewCount: 340,
    followerCount: 5600,
    websiteUrl: "https://waywardchickadee.com",
    logoUrl: "/brands/wayward-chickadee.svg",
  },
  {
    id: "c1150",
    slug: "salty-hydration",
    name: "SALTY",
    tagline: "Zero-sugar electrolytes with 72+ ionic trace minerals — Passion Orange Mango, no merch wall",
    story: "A small hydration house that pairs pink Himalayan salt with a 72-mineral ionic complex and fulvic acid: zero sugar, stevia-and-monk-fruit sweetened, built for sweat and recovery. Keep Passion Orange Mango. No apparel, no shakers, no ice-cube trays.",
    location: "United States",
    founded: 2024,
    categories: ["electrolytes"],
    accent: "#1B4F72",
    rating: 4.6,
    reviewCount: 86,
    followerCount: 2100,
    websiteUrl: "https://salty-hydration.com",
    logoUrl: "/brands/salty-hydration.svg",
  },
  {
    id: "c1151",
    slug: "honeysuckle-rose",
    name: "Honeysuckle Rose Skincare",
    tagline: "Texas grass-fed tallow mineral sunscreen, deodorant, and whipped butters — no water, no fillers",
    story: "A Texas maker that handcrafts grass-fed, grass-finished tallow formulas without water or fillers: a mineral Sun Shield tin and face stick, a blue-tansy natural deodorant, whipped tallow butters in sweet orange / vanilla / blue tansy, serums, and a healing balm. Individual formulas stay. Sunscreen sets, serum sets, bug-bite balm, and tinted lip color stay in the barn.",
    location: "Texas",
    founded: 2022,
    categories: ["sunscreen","deodorant","skincare"],
    accent: "#C47A8A",
    rating: 4.8,
    reviewCount: 180,
    followerCount: 3900,
    websiteUrl: "https://honeysuckleroseskincare.com",
    logoUrl: "/brands/honeysuckle-rose.svg",
  },
  {
    id: "c1152",
    slug: "tallowed-and-free",
    name: "Tallowed and Free",
    tagline: "Quebec grass-fed tallow balm, shampoo bar, and soaps — no synthetic fragrance wall",
    story: "A Canadian house that renders grass-fed, grass-finished Quebec tallow into a single-ingredient balm (regular and whipped), a Moroccan-clay shampoo bar, calendula and Dead Sea mud soaps, honey lip balm, and a black-seed rosemary hair oil. Individual formulas stay. Totes, soy candles, and room mists stay packed. CAD converts to USD.",
    location: "Quebec, Canada",
    founded: 2023,
    categories: ["skincare","hair"],
    accent: "#5C4033",
    rating: 4.7,
    reviewCount: 92,
    followerCount: 2400,
    websiteUrl: "https://tallowedandfree.com",
    logoUrl: "/brands/tallowed-and-free.svg",
  },
];
