import type { Brand } from "./types";

/** Wave 26: small organic / toxic-free brands across marketplace categories (c888+). */
export const catalogBrandsWave26: Brand[] = [
  {
    id: "c888",
    slug: "sky-and-sol",
    name: "Sky & Sol",
    tagline: "Tallow mineral SPF 30 — 25% non-nano zinc, no chemical-filter dump",
    story: "A small US sun kitchen that puts non-nano zinc in a grass-fed tallow base instead of a 30-ingredient lotion. Sachets, after-sun gel, and ritual sets stay. Custom bundle kits stay only when they are real formulas.",
    location: "United States",
    founded: 2023,
    categories: ["sunscreen","skincare"],
    accent: "#C45C26",
    rating: 4.7,
    reviewCount: 420,
    followerCount: 6800,
    websiteUrl: "https://skyandsol.co",
    logoUrl: "/brands/sky-and-sol.svg",
  },
  {
    id: "c889",
    slug: "doos-naturals",
    name: "Doo's Naturals",
    tagline: "Small-batch tallow deodorant, sun balm, and hair clay — five ingredients, no aluminum stick",
    story: "A US homestead kitchen that still pours tallow soap, magnesium-zinc deodorant, and a zinc sun balm by hand. Scent variants stay. Bundles stay when they are the same formulas, not merch.",
    location: "United States",
    founded: 2022,
    categories: ["deodorant","skincare","sunscreen","hair"],
    accent: "#6B3E26",
    rating: 4.8,
    reviewCount: 310,
    followerCount: 4200,
    websiteUrl: "https://doosnaturals.com",
    logoUrl: "/brands/doos-naturals.svg",
  },
  {
    id: "c890",
    slug: "sprinjene",
    name: "SprinJene",
    tagline: "Black-seed-oil toothpaste — fluoride-free and fluoride options, no SLS foam circus",
    story: "A natural oral house built around black seed oil and zinc instead of a neon gel tube. Fresh Boost, White Boost, kids flavors, and mouthwash stay. Flavor variants stay as their own listings.",
    location: "United States",
    founded: 2016,
    categories: ["oral"],
    accent: "#2A9D8F",
    rating: 4.6,
    reviewCount: 1800,
    followerCount: 12000,
    websiteUrl: "https://sprinjene.com",
    logoUrl: "/brands/sprinjene.png",
  },
  {
    id: "c891",
    slug: "flyte",
    name: "FLYTE",
    tagline: "Clear grass-fed whey isolate — juice-like protein, no chalky shake tub",
    story: "A small US protein kitchen that makes whey drink like juice: 20g isolate plus electrolytes, no neon dye stack. Blue Razz, watermelon, and other flavors stay. Shaker bottles stay in the merch drawer.",
    location: "United States",
    founded: 2024,
    categories: ["protein"],
    accent: "#1565C0",
    rating: 4.6,
    reviewCount: 280,
    followerCount: 5100,
    websiteUrl: "https://www.nonstopflyte.com",
    logoUrl: "/brands/flyte.svg",
  },
  {
    id: "c892",
    slug: "wild-society",
    name: "Wild Society",
    tagline: "Clear whey RTD and electrolyte mix — 20g protein, no candy-aisle scoop",
    story: "A clean-fuel house that puts clear whey and sweat minerals in a resealable bottle instead of a chalky shaker. Flavor variants stay. 100%-off gimmicks and whisks stay off this shelf.",
    location: "United States",
    founded: 2023,
    categories: ["protein","electrolytes"],
    accent: "#1B4F72",
    rating: 4.5,
    reviewCount: 190,
    followerCount: 3400,
    websiteUrl: "https://wildsocietynutrition.com",
    logoUrl: "/brands/wild-society.svg",
  },
  {
    id: "c893",
    slug: "amandean",
    name: "Amandean",
    tagline: "Marine collagen, creatine HCl, and eye vitamins — short labels, no gummy aisle",
    story: "A US supplement kitchen that still treats collagen and creatine like food, not a neon tub. Wild-caught marine collagen, CON-CRET creatine, and lutein stay. Gift cards stay off the marketplace.",
    location: "United States",
    founded: 2016,
    categories: ["supplements","protein"],
    accent: "#5E4B45",
    rating: 4.7,
    reviewCount: 2400,
    followerCount: 18000,
    websiteUrl: "https://amandean.com",
    logoUrl: "/brands/amandean.svg",
  },
  {
    id: "c894",
    slug: "myoxcience",
    name: "Myoxcience",
    tagline: "Practitioner-grade magnesium, collagen, and B-complex — no megastore multi",
    story: "A small US formula house that keeps the list short: glycinate, grass-fed collagen peptides, methylated B vitamins. Stacks stay when they are real formulas. No candy-aisle gummy dump.",
    location: "United States",
    founded: 2014,
    categories: ["supplements","protein"],
    accent: "#2C5F4E",
    rating: 4.7,
    reviewCount: 1600,
    followerCount: 11000,
    websiteUrl: "https://myoxcience.com",
    logoUrl: "/brands/myoxcience.svg",
  },
  {
    id: "c895",
    slug: "haashrooms",
    name: "HaaShrooms",
    tagline: "Virginia-grown mushroom coffee, tinctures, and tremella shampoo — farm fungi, no candy-aisle scoop",
    story: "A family mushroom farm in Goochland that still grows, extracts, and bottles on site. Lion's mane cocoa, chaga tinctures, and tremella shampoo stay. Foraging hunts stay off this shelf.",
    location: "Goochland, VA",
    founded: 2020,
    categories: ["supplements","hair"],
    accent: "#5B7A3A",
    rating: 4.8,
    reviewCount: 240,
    followerCount: 3900,
    websiteUrl: "https://haashrooms.com",
    logoUrl: "/brands/haashrooms.svg",
  },
  {
    id: "c896",
    slug: "imarais",
    name: "Imaraïs",
    tagline: "Sugar-free mushroom hair gummies — reishi, chaga, snow mushroom, no neon-gummy aisle",
    story: "A vegan hair-from-within studio that puts organic functional mushrooms in a sugar-free gummy instead of a 30-ingredient smoothie. Nourish, Thrive, Glow, and Clarity stay.",
    location: "United States",
    founded: 2021,
    categories: ["hair","supplements"],
    accent: "#6B4C7A",
    rating: 4.6,
    reviewCount: 380,
    followerCount: 7200,
    websiteUrl: "https://www.imaraisbeauty.com",
    logoUrl: "/brands/imarais.svg",
  },
  {
    id: "c897",
    slug: "shroomwell",
    name: "Shroomwell",
    tagline: "Nordic functional mushroom extracts — focus, sleep, immunity, no candy-aisle scoop",
    story: "A Nordic fungi house that bottles lion's mane, reishi, and chaga as dual extracts instead of a flavored coffee mix. Discovery bundles stay when they are real formulas. Soft-drink merch stays off this shelf.",
    location: "Europe",
    founded: 2019,
    categories: ["supplements"],
    accent: "#3D6B4F",
    rating: 4.6,
    reviewCount: 520,
    followerCount: 8100,
    websiteUrl: "https://shroomwell.com",
    logoUrl: "/brands/shroomwell.svg",
  },
  {
    id: "c898",
    slug: "nello",
    name: "Nello",
    tagline: "Functional drink mixes for focus, glow, calm, and sleep — no neon energy-drink stack",
    story: "A small ritual kitchen that treats nootropics like tea, not a gas-station can. Superfocus, Superglow, Supercalm, and Supersleep stay. Flavor variants stay as their own listings.",
    location: "United States",
    founded: 2022,
    categories: ["supplements"],
    accent: "#2E7D32",
    rating: 4.5,
    reviewCount: 640,
    followerCount: 9400,
    websiteUrl: "https://drinknello.com",
    logoUrl: "/brands/nello.svg",
  },
  {
    id: "c899",
    slug: "krowa",
    name: "Krowa Beauty",
    tagline: "Grass-fed tallow face balms and ancestral beauty capsules — short INCI, no 40-step serum aisle",
    story: "A US tallow kitchen that still renders pasture fat into morning and night balms, plus a liver-and-collagen beauty capsule. No merch drawer. No 12-SKU serum circus.",
    location: "United States",
    founded: 2021,
    categories: ["skincare","supplements"],
    accent: "#8B5A2B",
    rating: 4.8,
    reviewCount: 180,
    followerCount: 2600,
    websiteUrl: "https://krowa.com",
    logoUrl: "/brands/krowa.svg",
  },
  {
    id: "c900",
    slug: "serenique-skin",
    name: "Serenique Skin",
    tagline: "Waterless Canadian tallow balms — no preservative soup, no diluted cream",
    story: "A Canadian waterless house that keeps tallow undiluted: face balm, body butter, shave balm, lip balm. Organic oils only. No synthetic-fragrance dump.",
    location: "Canada",
    founded: 2022,
    categories: ["skincare"],
    accent: "#C4A484",
    rating: 4.8,
    reviewCount: 140,
    followerCount: 2100,
    websiteUrl: "https://sereniqueskin.ca",
    logoUrl: "/brands/serenique-skin.svg",
  },
  {
    id: "c901",
    slug: "milk-and-honey-tallow",
    name: "Milk & Honey Tallow",
    tagline: "Tallow face cream and mineral deodorant — magnesium, zinc, no aluminum stick",
    story: "A small tallow studio that still whips face cream and a baking-soda-free mineral deodorant with magnesium hydroxide and zinc. Scent variants stay. Soap-dish merch stays in the studio drawer.",
    location: "United States",
    founded: 2022,
    categories: ["skincare","deodorant"],
    accent: "#C4A484",
    rating: 4.7,
    reviewCount: 260,
    followerCount: 3800,
    websiteUrl: "https://milkandhoneytallow.com",
    logoUrl: "/brands/milk-and-honey-tallow.svg",
  },
  {
    id: "c902",
    slug: "lady-may",
    name: "Lady May",
    tagline: "Southern whipped tallow and flavored lip balm — farm fat, no seed-oil filler stack",
    story: "A family tallow kitchen that started by whipping cooking fat for a restaurant regular named Lady May. Unscented, eucalyptus, gardenia, and lip-balm flavors stay. Candles stay off this shelf.",
    location: "Southern United States",
    founded: 2018,
    categories: ["skincare"],
    accent: "#E27D60",
    rating: 4.8,
    reviewCount: 890,
    followerCount: 7600,
    websiteUrl: "https://ladymaytallow.com",
    logoUrl: "/brands/lady-may.svg",
  },
  {
    id: "c903",
    slug: "pure-good",
    name: "Pure Good",
    tagline: "Sixth-generation ranch whipped tallow — Revival stick, no 40-ingredient lotion",
    story: "A family ranch that turned a homeschool project into whipped tallow: Revival moisturizer, face-and-body sticks, and a short-list serum. Sampler sets stay when they are real formulas.",
    location: "United States",
    founded: 2020,
    categories: ["skincare"],
    accent: "#5B7A3A",
    rating: 4.8,
    reviewCount: 540,
    followerCount: 6200,
    websiteUrl: "https://shoppuregood.com",
    logoUrl: "/brands/pure-good.svg",
  },
  {
    id: "c904",
    slug: "conscious-botanist",
    name: "Conscious Botanist",
    tagline: "Rice-water shampoo in aluminum — sulfate-free, silicone-free, no plastic bottle graveyard",
    story: "A plant-hair studio that bottles rice water, nettle, and rosemary in recycled aluminum. Solid shampoo and ritual sets stay. Empty reusable pumps stay in the merch drawer.",
    location: "Independent / DTC",
    founded: 2021,
    categories: ["hair"],
    accent: "#2C5F4E",
    rating: 4.6,
    reviewCount: 210,
    followerCount: 3400,
    websiteUrl: "https://consciousbotanist.co",
    logoUrl: "/brands/conscious-botanist.svg",
  },
  {
    id: "c905",
    slug: "the-powder-shampoo",
    name: "The Powder Shampoo",
    tagline: "Waterless powder shampoo — probiotics, no 30-ingredient smoothie bottle",
    story: "A plastic-light hair house that ships powder instead of water: grapefruit probiotic shampoo and on-the-go trios. Discovery minis stay when they are a real formula. Body-wash powders stay as real wash, not merch.",
    location: "United Kingdom",
    founded: 2019,
    categories: ["hair"],
    accent: "#F2C94C",
    rating: 4.6,
    reviewCount: 980,
    followerCount: 14000,
    websiteUrl: "https://thepowdershampoo.com",
    logoUrl: "/brands/the-powder-shampoo.svg",
  },
  {
    id: "c906",
    slug: "heritage-store",
    name: "Heritage Store",
    tagline: "Rosewater and witch hazel since 1969 — flower waters, no 40-ingredient cream",
    story: "A long-running apothecary that still bottles rosewater, cucumber hydrosol, and witch hazel the old way. Toners and mists stay. Viral-bundle merch stays only when it is the same formulas.",
    location: "United States",
    founded: 1969,
    categories: ["skincare"],
    accent: "#7EB8A2",
    rating: 4.7,
    reviewCount: 3200,
    followerCount: 19000,
    websiteUrl: "https://heritagestore.com",
    logoUrl: "/brands/heritage-store.svg",
  },
];
