import type { Brand } from "./types";

/** Wave 54: small organic / toxic-free brands across marketplace categories (c1193+). */
export const catalogBrandsWave54: Brand[] = [
  {
    id: "c1193",
    slug: "wonder-oral",
    name: "Wonder Oral Wellness",
    tagline: "MCHA tooth powders in refillable jars plus plastic-free brushes",
    story: "A small US oral house that mills fluoride-free tooth powders with microcrystalline hydroxyapatite from grass-fed Australian bone, plus bamboo and recycled brushes, a tongue cleaner, and silk floss. Individual peppermint, cocoa mint, citrus berry, whitening, and unflavored jars stay. Starter kits, ebooks, pH strips, and mouth tape stay boxed.",
    location: "United States",
    founded: 2021,
    categories: ["oral"],
    accent: "#3D6B4F",
    rating: 4.8,
    reviewCount: 186,
    followerCount: 4200,
    websiteUrl: "https://wonderoralwellness.com",
    logoUrl: "/brands/wonder-oral.svg",
  },
  {
    id: "c1194",
    slug: "rain-valley",
    name: "Rain Valley Naturals",
    tagline: "Flagstaff grass-fed tallow sun stick, sun cream, and whipped jars",
    story: "A Flagstaff, Arizona homestead that renders 100% grass-fed tallow into a non-nano zinc sun stick, a whipped sun cream, lotions, whipped creams, hydrosols, and peppermint-eucalyptus lip. Scent and tint options expand. Jar size stays one listing.",
    location: "Flagstaff, AZ",
    founded: 2023,
    categories: ["sunscreen","skincare"],
    accent: "#4A6B3A",
    rating: 4.7,
    reviewCount: 64,
    followerCount: 1100,
    websiteUrl: "https://rainvalleynaturals.com",
    logoUrl: "/brands/rain-valley.svg",
  },
  {
    id: "c1195",
    slug: "candid-naturals",
    name: "Candid Naturals",
    tagline: "Wisconsin tallow sun stick plus herb-infused tallow creams",
    story: "A Wisconsin studio that pours a 20% non-nano zinc tallow sun stick and herb-infused tallow creams, balms, body oil, magnesium butter, serums, and a two-flavor lip. Individual formulas stay. Makeup, empty palettes, discovery sets, and gift cards stay in the color-cosmetics drawer.",
    location: "Wisconsin, United States",
    founded: 2020,
    categories: ["sunscreen","skincare"],
    accent: "#C47A6A",
    rating: 4.7,
    reviewCount: 210,
    followerCount: 5400,
    websiteUrl: "https://candidnaturals.com",
    logoUrl: "/brands/candid-naturals.svg",
  },
  {
    id: "c1196",
    slug: "simply-tallow",
    name: "Simply Tallow & Co.",
    tagline: "Aluminum-free tallow deodorant, whipped jars, soaps, and beard balm",
    story: "A small US tallow house with aluminum-free cream deodorant in unscented, bergamot-lime, lemongrass-tea tree, and juniper, plus named whipped tallows, soaps, lip flavors, beard balms, and a honey balm. Scent options expand. Jar size stays one listing. Beanies, stickers, gua sha, soap savers, and bundles stay out.",
    location: "United States",
    founded: 2022,
    categories: ["deodorant","skincare","hair"],
    accent: "#6B3E26",
    rating: 4.6,
    reviewCount: 128,
    followerCount: 2800,
    websiteUrl: "https://simplytallowandcompany.com",
    logoUrl: "/brands/simply-tallow.svg",
  },
  {
    id: "c1197",
    slug: "nutristrength",
    name: "Nutristrength",
    tagline: "UK whey isolate and pea protein in cocoa, vanilla, and unflavoured",
    story: "A small British protein house milling whey isolate and pea protein in roasted cocoa, classic vanilla, and unflavoured pouches — short labels, recyclable packs, no dessert-aisle stack. Dedicated flavor SKUs stay. Glass shakers stay on the merch rack. GBP prices convert to USD.",
    location: "United Kingdom",
    founded: 2014,
    categories: ["protein"],
    accent: "#2F4A3C",
    rating: 4.6,
    reviewCount: 340,
    followerCount: 8900,
    websiteUrl: "https://nutristrength.com",
    logoUrl: "/brands/nutristrength.png",
  },
  {
    id: "c1198",
    slug: "zeal",
    name: "Zeal",
    tagline: "Zero-sugar electrolyte tubs and sticks plus clean collagen and mag",
    story: "A small US hydration house mixing stevia-sweetened electrolyte powders in more than a dozen fruit flavors, plus stick packs, an energy line, creatine, magnesium, and grass-fed collagen. Dedicated flavor SKUs stay and stick/energy/collagen flavors expand. Bottles, fat-burner caps, and the Amazon-style vitamin stack stay out.",
    location: "United States",
    founded: 2019,
    categories: ["electrolytes","supplements"],
    accent: "#E07A3D",
    rating: 4.5,
    reviewCount: 420,
    followerCount: 6200,
    websiteUrl: "https://livezeal.com",
    logoUrl: "/brands/zeal.svg",
  },
];
