import type { Brand } from "./types";

/** Wave 59: small organic / toxic-free brands across marketplace categories (c1223+). */
export const catalogBrandsWave59: Brand[] = [
  {
    id: "c1223",
    slug: "elektra",
    name: "Elektra",
    tagline: "Six-ingredient berry electrolytes with sea salt, coconut water, and stevia",
    story: "A tiny hydration house that kept the label to six things you can pronounce: sea salt, potassium, magnesium, coconut water powder, citric acid, and stevia. The Full Tub and the Starter Pack stay. Serving count is size, not a flavor — Berry Splash is the house flavor, not a variant tree.",
    location: "United States",
    founded: 2025,
    categories: ["electrolytes"],
    accent: "#2B4C7E",
    rating: 4.6,
    reviewCount: 38,
    followerCount: 700,
    websiteUrl: "https://elektralytes.com",
    logoUrl: "/brands/elektra.svg",
  },
  {
    id: "c1224",
    slug: "primals",
    name: "PRIMALS",
    tagline: "10% rod-shaped n-HA toothpaste tablets plus plastic-free brushes and short-list wash",
    story: "A small US clean-living shop whose oral line is 10% rod-shaped nano-hydroxyapatite tablets in glass, copper tongue scrapers, and horse- or boar-bristle bamboo brushes. Individual tablets, scrapers, bamboo brushes, and the short-list shampoo, conditioner, body wash, and lotion stay. Electric brushes, air pods, shower filters, blue-light glasses, underwear, and e-guides stay boxed.",
    location: "United States",
    founded: 2023,
    categories: ["oral","hair","skincare"],
    accent: "#3D4A32",
    rating: 4.6,
    reviewCount: 92,
    followerCount: 2400,
    websiteUrl: "https://primals.shop",
    logoUrl: "/brands/primals.svg",
  },
  {
    id: "c1225",
    slug: "papr",
    name: "PĀPR",
    tagline: "Los Angeles paper-tube deodorant with coconut oil, shea, and essential-oil scents",
    story: "A Los Angeles plastic-free deodorant house packing aluminum-free sticks into compostable paper tubes. Coconut oil, shea butter, and baking soda do the work; scents are already separate titles from Golden Coast to From Dusk Till Dawn. Custom bundles stay out. Scent is the product, not a size option.",
    location: "Los Angeles, California, United States",
    founded: 2019,
    categories: ["deodorant"],
    accent: "#C45C26",
    rating: 4.5,
    reviewCount: 210,
    followerCount: 4800,
    websiteUrl: "https://papercosmetics.com",
    logoUrl: "/brands/papr.svg",
  },
  {
    id: "c1226",
    slug: "tallowhead",
    name: "TallowHead",
    tagline: "Missouri homestead tallow with non-nano zinc sunscreen and magnesium deodorant",
    story: "A Missouri homestead pouring 100% grass-fed and finished tallow in small batches, then infusing botanicals. The ~SPF 30 non-nano zinc sunscreen expands unscented versus vanilla. Deodorant and lip balm scents expand. Jar size is not a flavor. Gift cards and pick-your-own bundles stay out.",
    location: "Missouri, United States",
    founded: 2023,
    categories: ["sunscreen","skincare","deodorant","hair"],
    accent: "#6B3E26",
    rating: 4.7,
    reviewCount: 64,
    followerCount: 1500,
    websiteUrl: "https://tallowhead.com",
    logoUrl: "/brands/tallowhead.svg",
  },
  {
    id: "c1227",
    slug: "mill-creek-tallow",
    name: "Mill Creek Tallow",
    tagline: "East Texas grass-fed tallow deodorant, shampoo bar, and whipped face creams",
    story: "A Buna, Texas maker rendering grass-fed tallow into magnesium deodorant, a tallow shampoo bar, soap, beard balm, and whipped face and body creams. Deodorant, soap, and lip scents expand. Jar size is not a flavor. Bath salts, bug balm, pet balm, soap trays, and saver bags stay boxed.",
    location: "Buna, Texas, United States",
    founded: 2022,
    categories: ["skincare","deodorant","hair"],
    accent: "#7A5A2B",
    rating: 4.7,
    reviewCount: 54,
    followerCount: 1100,
    websiteUrl: "https://millcreektallow.com",
    logoUrl: "/brands/mill-creek-tallow.svg",
  },
  {
    id: "c1228",
    slug: "xotic-mushrooms",
    name: "Xotic Mushrooms",
    tagline: "Melbourne-grown lion's mane, reishi, and cordyceps fruiting-body extracts",
    story: "A Victorian mushroom farm that grows, dries, and dual-extracts lion's mane, reishi, and cordyceps under one roof — fruiting body only, hardwood substrate, no grain padding. The three extract powders stay. AUD prices convert to USD. There is no merch aisle to drop.",
    location: "Melbourne, Victoria, Australia",
    founded: 2024,
    categories: ["supplements"],
    accent: "#1F4E3D",
    rating: 4.7,
    reviewCount: 41,
    followerCount: 900,
    websiteUrl: "https://xoticmushrooms.com.au",
    logoUrl: "/brands/xotic-mushrooms.svg",
  },
];
