import type { Brand } from "./types";

/** Wave 96: small organic / toxic-free brands across marketplace categories (c1445+). */
export const catalogBrandsWave96: Brand[] = [
  {
    id: "c1445",
    slug: "gutology",
    name: "Gutology",
    tagline: "Alcester microbiome hydroxyapatite toothpaste with TrueBiotic® — fluoride-free adult and kids paste",
    story:
      "The leftover unused multi-SKU hydroxyapatite oral house after dedicated n-HA shops ran out through wave4–95 — Ollie Gallant’s 2020 gut-podcast brand. Keep US singles of adult HAP paste, kids 75 ml, bamboo charcoal floss, and copper tongue scraper. UK region dupes, 2-pack/starter/family kits, and 3-packs stay boxed. Pack size is size. Cart.js is USD. Pages are microbiome essays (leave empty).",
    location: "Alcester, England",
    founded: 2020,
    categories: ["oral"],
    accent: "#3D6B4F",
    rating: 4.6,
    reviewCount: 890,
    followerCount: 12000,
    websiteUrl: "https://gutology.co",
    logoUrl: "/brands/gutology.svg",
  },
  {
    id: "c1446",
    slug: "plan-d",
    name: "Plan D",
    tagline: "Seattle monk-fruit electrolytes — no stevia, no sucralose, beet root, magnesium, and Himalayan salt",
    story:
      "Seattle leftover unused one-flavor hydration house after wave4–95. Keep Strawberry Lemonade sticks. 10 / 20 / 30 stick counts are size. Sample 3-packs, $1 water bottles, and shipping protection stay boxed. Cart.js is USD. Page is a six-bullet key-ingredient essay (leave empty).",
    location: "Seattle, WA",
    founded: 2024,
    categories: ["electrolytes"],
    accent: "#C45A3A",
    rating: 4.5,
    reviewCount: 64,
    followerCount: 980,
    websiteUrl: "https://drinkpland.com",
    logoUrl: "/brands/plan-d.svg",
  },
  {
    id: "c1447",
    slug: "forall-nutrition",
    name: "FORALL Nutrition",
    tagline: "One-ingredient European grass-fed whey isolate — flavorless, no lecithin, no sucralose",
    story:
      "Leftover unused one-ingredient grass-fed isolate after wave4–95. Keep the 20-scoop bag. Welcome kits, whisks, and WATER+PROTEIN 12-packs stay boxed. Pack / bag count is size. Cart.js is USD. Hardcode the published one-ingredient list.",
    location: "Wilmington, DE",
    founded: 2023,
    categories: ["protein"],
    accent: "#1F4E79",
    rating: 4.7,
    reviewCount: 410,
    followerCount: 6400,
    websiteUrl: "https://forallnutrition.com",
    logoUrl: "/brands/forall-nutrition.svg",
  },
  {
    id: "c1448",
    slug: "maui-mana-skincare",
    name: "Maui Mana Skincare",
    tagline: "Kihei reef-safe mineral SPF 30, cacao-tinted sun, after-sun, and island lip balm",
    story:
      "Unused Maui mineral sun leftover — keep reef-safe jar and stick SPF 30, cacao-tinted mineral sunscreen, Aloe-ha after-sun, Go-Balm, Kula lavender lotion bar and salt scrub, plus peppermint / coco / mauka mint lips. Cart.js is USD. Pages are aloha-story marketing (leave empty).",
    location: "Kihei, HI",
    founded: 2022,
    categories: ["sunscreen", "skincare"],
    accent: "#2A7A6A",
    rating: 4.8,
    reviewCount: 38,
    followerCount: 720,
    websiteUrl: "https://mauimanaskincare.com",
    logoUrl: "/brands/maui-mana-skincare.svg",
  },
  {
    id: "c1449",
    slug: "cowlo",
    name: "COWLO",
    tagline: "Virginia family grass-fed tallow deodorant, whipped balm, soap, and lip — aluminum-free, baking-soda-free",
    story:
      "Family-made leftover after wave4–95 — deodorant scents already on separate titles (Unscented, Lavender, Sweet Vanilla Mint, Cedarwood & Peppermint); whipped and lip scents are separate SKUs. Bug balm, gift cards, and 3-soap promos stay boxed. Cart.js is USD. Hardcode published deodorant and short whipped lists — soap pages are farm-story marketing (leave empty).",
    location: "Virginia, USA",
    founded: 2023,
    categories: ["deodorant", "skincare"],
    accent: "#8B4A2A",
    rating: 4.8,
    reviewCount: 156,
    followerCount: 2400,
    websiteUrl: "https://www.cowlotallow.com",
    logoUrl: "/brands/cowlo.svg",
  },
  {
    id: "c1450",
    slug: "noble-mushrooms",
    name: "Noble Mushrooms",
    tagline: "Hillsborough USDA organic fruiting-body lion's mane, reishi, cordyceps, turkey tail, and shiitake tinctures",
    story:
      "NJ lab-and-farm leftover after wave4–95 — keep dual-extract fruiting-body tinctures and dried fruiting-body bags. Mushroom option expands dried Lion's Mane / Cordyceps / Albino Cordyceps / Reishi. Grow kits, spawn, liquid culture, classes, CSA, gift cards, and the Focus-Energy-Calm trio stay boxed. Cart.js is USD. Hardcode published dual-extract lists.",
    location: "Hillsborough, NJ",
    founded: 2021,
    categories: ["supplements"],
    accent: "#4A5C32",
    rating: 4.8,
    reviewCount: 72,
    followerCount: 1100,
    websiteUrl: "https://www.noblemushrooms.com",
    logoUrl: "/brands/noble-mushrooms.svg",
  }
];
