import type { Brand } from "./types";

/** Wave 45: small organic / toxic-free brands across marketplace categories (c1129+). */
export const catalogBrandsWave45: Brand[] = [
  {
    id: "c1129",
    slug: "halo-toothpaste",
    name: "Halo Toothpaste",
    tagline: "Dorset hydroxyapatite toothpaste tablets — fluoride-free, plastic-pouch, travel-ready",
    story: "A UK oral house that swaps the plastic tube for 100 vegan hydroxyapatite tablets in a recyclable pouch. Dentist-backed enamel mineral, silica polish, and peppermint — no fluoride, no SLS. Shop already lists USD. One formula, no merch wall.",
    location: "Dorset, England",
    founded: 2023,
    categories: ["oral"],
    accent: "#4A7C8C",
    rating: 4.7,
    reviewCount: 86,
    followerCount: 2100,
    websiteUrl: "https://halotoothpaste.com",
    logoUrl: "/brands/halo-toothpaste.svg",
  },
  {
    id: "c1130",
    slug: "tallowshine",
    name: "Tallowshine",
    tagline: "Virginia tallow + 25% non-nano zinc sun shield stick and cream",
    story: "A Bentonville kitchen that pours grass-fed tallow with 25% non-nano zinc into a reef-safe sun stick and cream, then keeps cleansing balm, facial creams, magnesium cream, lip balm flavors, and a baby balm. Individual formulas stay. Blush makeup, imperfect seconds, and bundles stay out.",
    location: "Bentonville, Virginia",
    founded: 2023,
    categories: ["sunscreen","skincare"],
    accent: "#C4A35A",
    rating: 4.6,
    reviewCount: 54,
    followerCount: 1200,
    websiteUrl: "https://tallowshine.com",
    logoUrl: "/brands/tallowshine.svg",
  },
  {
    id: "c1131",
    slug: "magsol",
    name: "MAGSOL",
    tagline: "Chicago four-ingredient magnesium deodorant — aluminum-free, baking-soda-free",
    story: "A Chicago magnesium house built around four simple ingredients: no aluminum, no baking soda, just scent SKUs that already live as their own listings. Unscented, santal, hunter, patchouli, rose, jasmine, and kids gummy/explorer/dreamer sticks stay. No merch, no gadget wall.",
    location: "Chicago, Illinois",
    founded: 2021,
    categories: ["deodorant"],
    accent: "#2C5F4E",
    rating: 4.8,
    reviewCount: 7500,
    followerCount: 18000,
    websiteUrl: "https://magsolnaturals.com",
    logoUrl: "/brands/magsol.svg",
  },
  {
    id: "c1132",
    slug: "saltivate",
    name: "Saltivate",
    tagline: "Hull, MA high-sodium zero-sugar electrolytes — 800mg sodium, no stevia bite",
    story: "A Massachusetts hydration house for heavy sweaters: 800mg sodium, potassium, and magnesium in watermelon, mango pineapple, orange, and raw unflavored jars and stick packs. Sweetened with Reb M instead of stevia leaf. Consumer tubs and packets stay. Wholesale cases, tumblers, shakers, towels, and acrylic organizers stay in the warehouse.",
    location: "Hull, Massachusetts",
    founded: 2022,
    categories: ["electrolytes"],
    accent: "#C45C26",
    rating: 4.6,
    reviewCount: 210,
    followerCount: 4800,
    websiteUrl: "https://saltivate.com",
    logoUrl: "/brands/saltivate.svg",
  },
  {
    id: "c1133",
    slug: "vaer-skin",
    name: "VÆR Skin",
    tagline: "Bend ancestral tallow balms — no seed oils, four rituals, no $210 set",
    story: "An Oregon tallow house that keeps four grass-fed, seed-oil-free balms in recyclable glass: Balancer, Energizer, Healer, and Bare. Whole ingredients the skin recognizes — tallow, jojoba, beeswax, botanicals. Individual jars stay. The $210 four-balm ritual collection stays out so each formula can live as its own listing.",
    location: "Bend, Oregon",
    founded: 2024,
    categories: ["skincare"],
    accent: "#6B4F2A",
    rating: 4.7,
    reviewCount: 48,
    followerCount: 1600,
    websiteUrl: "https://vaer.skin",
    logoUrl: "/brands/vaer-skin.svg",
  },
  {
    id: "c1134",
    slug: "wicked-protein",
    name: "WICKED Protein",
    tagline: "New Hampshire Clean Label clear whey — ice pop, cherry limeade, blue raspberry",
    story: "A small Amherst clear-whey house that keeps individual isolate flavors — ice pop, cherry limeade, blue raspberry, tropical punch, watermelon, lemonade, and unflavored — instead of a tee-and-shaker shop. Flavor options expand. Order protection, athletic tees, shaker bottles, Amazon 12-packs, and sold-out bundle deals stay out.",
    location: "Amherst, New Hampshire",
    founded: 2023,
    categories: ["protein"],
    accent: "#1B4F72",
    rating: 4.5,
    reviewCount: 190,
    followerCount: 4200,
    websiteUrl: "https://wickedprotein.com",
    logoUrl: "/brands/wicked-protein.svg",
  },
  {
    id: "c1135",
    slug: "wander-wash",
    name: "Wander Wash Co.",
    tagline: "Butte shampoo bars, colored deodorant sticks, and beard balms — no tee wall",
    story: "A Montana cold-process kitchen that hand-pours shampoo and conditioner bars, aluminum-free colored deodorant sticks, lotions, soaps, and beard oils in-house. Individual formulas stay. Tees, tanks, gift cards, shower caddies, travel stacks, and soap bundles stay on the trail.",
    location: "Butte, Montana",
    founded: 2021,
    categories: ["hair","deodorant","skincare"],
    accent: "#7A5C3A",
    rating: 4.7,
    reviewCount: 320,
    followerCount: 5400,
    websiteUrl: "https://wanderwashco.com",
    logoUrl: "/brands/wander-wash.svg",
  },
];
