import type { Brand } from "./types";

/** Wave 24: small organic / toxic-free brands across marketplace categories (c848+). */
export const catalogBrandsWave24: Brand[] = [
  {
    id: "c848",
    slug: "mama-kuleana",
    name: "Mama Kuleana",
    tagline: "Hawaiian reef-safe mineral sunscreen — island-made, no oxybenzone circus",
    story: "A tiny Hawaiʻi sun house that keeps the formula reef-safe and short. The mineral stick is built for real ocean days, not a 30-ingredient chemical-filter bottle. Single tins stay; multipacks stay as the same sunscreen, not merch.",
    location: "Hawaiʻi, United States",
    founded: 2019,
    categories: ["sunscreen"],
    accent: "#1B6B5A",
    rating: 4.8,
    reviewCount: 420,
    followerCount: 5100,
    websiteUrl: "https://mamakuleana.com",
    logoUrl: "/brands/mama-kuleana.svg",
  },
  {
    id: "c849",
    slug: "vitamin-bee",
    name: "Vitamin Bee",
    tagline: "Small-batch Lowcountry sun balm with non-nano zinc — botanical, reef-conscious",
    story: "A Bluffton mama kitchen that pours a non-nano zinc sun veil instead of a chemical-filter lotion. Botanical oils do the glide; zinc does the block. Bug spray, fire cider, and merch stay off this shelf.",
    location: "Bluffton, SC",
    founded: 2021,
    categories: ["sunscreen","skincare"],
    accent: "#C45C26",
    rating: 4.7,
    reviewCount: 180,
    followerCount: 2400,
    websiteUrl: "https://hellovitaminbee.com",
    logoUrl: "/brands/vitamin-bee.svg",
  },
  {
    id: "c850",
    slug: "summer-salt-body",
    name: "Summer Salt Body",
    tagline: "Australian mineral SPF and body oils — clean botanicals, no chemical-filter dump",
    story: "Gold Coast body care that treats sun and skin like the same ritual: mineral SPF, oils, and balms with readable botanicals. Tanning mitts, mystery boxes, and Christmas crackers stay in the merch drawer.",
    location: "Australia",
    founded: 2018,
    categories: ["sunscreen","skincare"],
    accent: "#E27D60",
    rating: 4.6,
    reviewCount: 2100,
    followerCount: 18000,
    websiteUrl: "https://summersaltbody.com",
    logoUrl: "/brands/summer-salt-body.svg",
  },
  {
    id: "c851",
    slug: "hello-sunday",
    name: "Hello Sunday",
    tagline: "SPF-first UK skincare — mineral moisturizer and daily sun without the greasy circus",
    story: "A London SPF house that puts mineral moisturizer and everyday sunscreen ahead of a 12-step drawer. The Everyday One Mineral SPF 50 stays. Digital gift cards do not.",
    location: "United Kingdom",
    founded: 2020,
    categories: ["sunscreen","skincare"],
    accent: "#F2C94C",
    rating: 4.6,
    reviewCount: 3400,
    followerCount: 26000,
    websiteUrl: "https://hellosundayspf.com",
    logoUrl: "/brands/hello-sunday.svg",
  },
  {
    id: "c852",
    slug: "dulese",
    name: "Dulesé",
    tagline: "Refillable natural deodorant cream — aluminum-free, plastic-light, no baking-soda burn",
    story: "A small deodorant studio that sells one refillable cream and the refill, not a 14-scent aisle. Aluminum stays out. Gift cards and donation SKUs stay off the marketplace.",
    location: "New Zealand",
    founded: 2022,
    categories: ["deodorant"],
    accent: "#2C5F4E",
    rating: 4.8,
    reviewCount: 260,
    followerCount: 3200,
    websiteUrl: "https://dulese.com",
    logoUrl: "/brands/dulese.svg",
  },
  {
    id: "c853",
    slug: "brooklyn-grooming",
    name: "Brooklyn Grooming",
    tagline: "Williamsburg pomade, hinoki deodorant, and balms — small-batch Brooklyn, no synthetic-fragrance dump",
    story: "A Brooklyn barbershop kitchen that still pours pomade, deodorant, and grooming balm by hand. Hinoki deodorant and hair clay stay. Hats, skull merch, and shaving-brush accessories do not.",
    location: "Brooklyn, NY",
    founded: 2012,
    categories: ["deodorant","hair","skincare"],
    accent: "#1A1A1A",
    rating: 4.7,
    reviewCount: 1900,
    followerCount: 14000,
    websiteUrl: "https://brooklyngrooming.com",
    logoUrl: "/brands/brooklyn-grooming.png",
  },
  {
    id: "c854",
    slug: "triumph-and-disaster",
    name: "Triumph & Disaster",
    tagline: "New Zealand athletic deodorant and grooming — short lists, no aluminum stick circus",
    story: "An Auckland grooming house that built Athletic Deodorant for sweat, not a perfume-lab stick. Daily formulas stay. Eau de parfum, conversation cards, and multi-tools stay off this shelf.",
    location: "Auckland, New Zealand",
    founded: 2011,
    categories: ["deodorant","skincare"],
    accent: "#1B4F72",
    rating: 4.6,
    reviewCount: 2800,
    followerCount: 19000,
    websiteUrl: "https://triumphanddisaster.com",
    logoUrl: "/brands/triumph-and-disaster.png",
  },
  {
    id: "c855",
    slug: "the-tallow-shop",
    name: "The Tallow Shop",
    tagline: "Grass-fed tallow deodorant, lip balm, and soap — farm fat, no seed-oil filler stack",
    story: "A tallow counter that treats pits and skin like the same fat: deodorant, lip balm, and body soap from rendered tallow. Room sprays and gift baskets stay in the barn.",
    location: "United States",
    founded: 2021,
    categories: ["deodorant","skincare"],
    accent: "#8B5A2B",
    rating: 4.8,
    reviewCount: 310,
    followerCount: 4100,
    websiteUrl: "https://thetallowshop.com",
    logoUrl: "/brands/the-tallow-shop.svg",
  },
  {
    id: "c856",
    slug: "closys",
    name: "CloSYS",
    tagline: "Chlorine-dioxide oral rinse — no alcohol, no SLS foam show, dentist-trusted",
    story: "A US oral house that uses stabilized chlorine dioxide instead of a burn-your-mouth alcohol rinse. Healthy gums, sensitive, and mouth-sores formulas stay. Third-party dandruff shampoo that landed in the catalog feed does not.",
    location: "United States",
    founded: 1991,
    categories: ["oral"],
    accent: "#1565C0",
    rating: 4.7,
    reviewCount: 6200,
    followerCount: 28000,
    websiteUrl: "https://closys.com",
    logoUrl: "/brands/closys.png",
  },
  {
    id: "c857",
    slug: "hawaiian-health",
    name: "Hawaiian Health Co",
    tagline: "Kauaʻi electrolytes with Hawaiian sea salt, coconut water, and real fruit — no neon sports-drink aisle",
    story: "Mixed on Kauaʻi with hand-harvested Hawaiian salt, freeze-dried coconut water, and fruit. Dragonfruit, passionfruit, unflavored, and mineral drops stay. Lion's mane cacao stays as a real supplement, not a candy mix.",
    location: "Kīlauea, Kauaʻi, HI",
    founded: 2022,
    categories: ["electrolytes","supplements"],
    accent: "#2A9D8F",
    rating: 4.7,
    reviewCount: 540,
    followerCount: 6200,
    websiteUrl: "https://hawaiianhealth.co",
    logoUrl: "/brands/hawaiian-health.svg",
  },
  {
    id: "c858",
    slug: "salty",
    name: "SALTE",
    tagline: "Clean electrolyte drink mixes — real fruit flavors, no candy-aisle dye stack",
    story: "A small hydration house that sells fruit-forward electrolyte packs instead of a neon sports-drink tub. Watermelon, pineapple, and apple stay. Ice-cube trays and sports bottles stay in the merch drawer.",
    location: "Independent / DTC",
    founded: 2021,
    categories: ["electrolytes"],
    accent: "#E27D60",
    rating: 4.6,
    reviewCount: 890,
    followerCount: 7400,
    websiteUrl: "https://drinksalty.com",
    logoUrl: "/brands/salty.svg",
  },
  {
    id: "c859",
    slug: "osmo",
    name: "OSMO Nutrition",
    tagline: "Research-backed hydration powders — sodium-smart sport fuel without the neon dump",
    story: "A sport-hydration lab that still treats electrolytes like physiology, not candy. Drink mixes and recovery fuel stay. Water bottles and runner hats do not.",
    location: "United States",
    founded: 2012,
    categories: ["electrolytes"],
    accent: "#1B4F72",
    rating: 4.6,
    reviewCount: 1600,
    followerCount: 12000,
    websiteUrl: "https://osmonutrition.com",
    logoUrl: "/brands/osmo.png",
  },
  {
    id: "c860",
    slug: "baltispore",
    name: "BaltiSpore",
    tagline: "Baltimore-grown lion's mane tinctures — fruiting body only, dual extracted in-house",
    story: "They grow, extract, and bottle in Baltimore so the tincture never leaves the same building. Fruiting-body lion's mane and full-spectrum sets stay. Cotton tees and grow merch do not.",
    location: "Baltimore, MD",
    founded: 2020,
    categories: ["supplements"],
    accent: "#6B4C7A",
    rating: 4.8,
    reviewCount: 380,
    followerCount: 4500,
    websiteUrl: "https://baltispore.com",
    logoUrl: "/brands/baltispore.svg",
  },
  {
    id: "c861",
    slug: "arbor-spring",
    name: "Arbor Spring Farms",
    tagline: "Michigan-grown lion's mane tincture, powder, and coffee — no grain-filler mycelium",
    story: "A Michigan farm that dates the bottles and keeps the mushroom 100% fruiting body. Tincture, powder, and lion's mane coffee stay. No imported grain-spawn capsules.",
    location: "Michigan, United States",
    founded: 2019,
    categories: ["supplements"],
    accent: "#5B7A3A",
    rating: 4.8,
    reviewCount: 210,
    followerCount: 2800,
    websiteUrl: "https://arborspringfarms.com",
    logoUrl: "/brands/arbor-spring.svg",
  },
  {
    id: "c862",
    slug: "spore-and-bloom",
    name: "Spore & Bloom",
    tagline: "UK-grown dual-extract mushroom tinctures — fruiting body only, no mycelium-on-oats",
    story: "A UK extract kitchen that dual-extracts lion's mane, reishi, chaga, and oyster from fruiting bodies. Signature tinctures and stacks stay. No grain-filler mycelium.",
    location: "United Kingdom",
    founded: 2021,
    categories: ["supplements"],
    accent: "#2E7D32",
    rating: 4.8,
    reviewCount: 640,
    followerCount: 7200,
    websiteUrl: "https://sporeandbloom.co.uk",
    logoUrl: "/brands/spore-and-bloom.svg",
  },
  {
    id: "c863",
    slug: "happy-fungi",
    name: "Happy Fungi",
    tagline: "Somerset-grown lion's mane triple extract — renewable-powered, fruiting body only",
    story: "Grown in a Somerset shipping container on biogas, then triple-extracted. The super-strength tincture and dried fruiting body stay. No mycelium-on-grain shortcuts.",
    location: "Somerset, United Kingdom",
    founded: 2022,
    categories: ["supplements"],
    accent: "#6B4C7A",
    rating: 4.8,
    reviewCount: 290,
    followerCount: 3600,
    websiteUrl: "https://www.happyfungi.co.uk",
    logoUrl: "/brands/happy-fungi.svg",
  },
  {
    id: "c864",
    slug: "life-cykel",
    name: "Life Cykel",
    tagline: "Australian mushroom extracts — lion's mane and cordyceps without a candy-gummy stack",
    story: "An Australian extract house that still bottles lion's mane and cordyceps like a lab, not a gummy aisle. Extracts stay. Copper water bottles stay off the marketplace.",
    location: "Australia",
    founded: 2016,
    categories: ["supplements"],
    accent: "#3D6B4F",
    rating: 4.6,
    reviewCount: 4100,
    followerCount: 32000,
    websiteUrl: "https://lifecykel.com",
    logoUrl: "/brands/life-cykel.svg",
  },
  {
    id: "c865",
    slug: "teelixir",
    name: "Teelixir",
    tagline: "Australian tonic herbs and mushroom extracts — organic lion's mane, reishi, shilajit",
    story: "A tonic-herb kitchen that puts organic mushroom extracts and shilajit on a short label. Lion's mane, reishi, turkey tail, and schizandra stay. 100%-off hook SKUs get dropped.",
    location: "Australia",
    founded: 2014,
    categories: ["supplements"],
    accent: "#5E4B45",
    rating: 4.7,
    reviewCount: 2200,
    followerCount: 18000,
    websiteUrl: "https://teelixir.com",
    logoUrl: "/brands/teelixir.svg",
  },
  {
    id: "c866",
    slug: "tallow-me-pretty",
    name: "Tallow Me Pretty",
    tagline: "Small-batch whipped tallow moisturizers — farm fat, short INCI, no 40-ingredient lotion",
    story: "A tallow studio that whips moisturizers instead of a silicone cream. Head-to-toe jars stay. Gua sha stones and gift-set merch stay off this shelf.",
    location: "United States",
    founded: 2021,
    categories: ["skincare"],
    accent: "#C4A484",
    rating: 4.8,
    reviewCount: 870,
    followerCount: 9400,
    websiteUrl: "https://tallowmepretty.com",
    logoUrl: "/brands/tallow-me-pretty.svg",
  },
  {
    id: "c867",
    slug: "tallow-theory",
    name: "Tallow Theory",
    tagline: "Whipped tallow, scalp treatment, and lip balm — ancestral fat, no seed-oil filler stack",
    story: "A short-list tallow house: awakened and enlightened whipped jars, a scalp treatment, and a lip balm. Bath salts stay only when they are a real formula. No 40-ingredient lotion drawer.",
    location: "United States",
    founded: 2022,
    categories: ["skincare","hair"],
    accent: "#6B3E26",
    rating: 4.8,
    reviewCount: 240,
    followerCount: 3100,
    websiteUrl: "https://tallowtheory.com",
    logoUrl: "/brands/tallow-theory.svg",
  },
];
