import type { Brand } from "./types";

/** Wave 36: small organic / toxic-free brands across marketplace categories (c1032+). */
export const catalogBrandsWave36: Brand[] = [
  {
    id: "c1032",
    slug: "cota-hydration",
    name: "Cota Hydration",
    tagline: "Sweat-ratio electrolytes — lemonade, strawberry, peach, monk fruit, no sucralose wall",
    story: "A three-founder hydration kitchen that seasons water with sea salt, potassium, and magnesium malate instead of a neon sports-drink stick. Lemonade, strawberry, and peach stay as their own listings. Water bottles stay in the merch locker.",
    location: "United States",
    founded: 2024,
    categories: ["electrolytes"],
    accent: "#1565C0",
    rating: 4.6,
    reviewCount: 180,
    followerCount: 3200,
    websiteUrl: "https://cotahydration.com",
    logoUrl: "/brands/cota-hydration.svg",
  },
  {
    id: "c1033",
    slug: "two-sisters-pure-goods",
    name: "2 Sisters Pure Goods",
    tagline: "Five-ingredient tallow mineral sun cream plus regenerative balms — no pet pantry, no 128oz wholesale jug",
    story: "A sister-run tallow kitchen that melts grass-fed suet with non-nano zinc, argan hair mists, and lamb-tallow lip nectar instead of a 30-ingredient lotion aisle. The mineral sun cream, dry-shampoo shades, and lotion-bar scents stay as their own listings. Nose-and-toes pet balm and gallon massage oil stay out.",
    location: "United States",
    founded: 2021,
    categories: ["sunscreen","skincare","hair"],
    accent: "#6B3E26",
    rating: 4.7,
    reviewCount: 420,
    followerCount: 6800,
    websiteUrl: "https://2sisterspuregoods.com",
    logoUrl: "/brands/two-sisters-pure-goods.svg",
  },
  {
    id: "c1034",
    slug: "some-essentials",
    name: "Some Essentials",
    tagline: "Non-nano zinc lotions and clay deodorant — tint and scent variants, no wreath shop",
    story: "A small US apothecary that pours unscented and lavender non-nano zinc, tinted and plain, plus a clay-and-tea-tree deodorant instead of a chemical-filter-and-aluminum wall. Lip lotions, lotion bars, and body oils stay as their own scent listings. Thermostat wreaths, empty tins, and sample packs stay in the gift drawer.",
    location: "United States",
    founded: 2019,
    categories: ["sunscreen","deodorant","skincare"],
    accent: "#5B7A3A",
    rating: 4.6,
    reviewCount: 260,
    followerCount: 4100,
    websiteUrl: "https://someessentials.com",
    logoUrl: "/brands/some-essentials.svg",
  },
  {
    id: "c1035",
    slug: "enml",
    name: "ENML",
    tagline: "Dentist-made hydroxyapatite toothpaste tablets — mint, cinnamon, lavender, limoncello, no dad-hat merch",
    story: "A US oral house that compresses micro-hydroxyapatite into chewable tablets instead of a plastic-tube aisle. Mint, cinnamon, lavender, limoncello, whitening, kids paste, mouthwash tablets, and bamboo brushes stay. Dad hats, mouth tape, hotel bulk packs, and empty travel tins stay out.",
    location: "United States",
    founded: 2022,
    categories: ["oral"],
    accent: "#2C5F4E",
    rating: 4.7,
    reviewCount: 890,
    followerCount: 14000,
    websiteUrl: "https://www.enml.com",
    logoUrl: "/brands/enml.svg",
  },
  {
    id: "c1036",
    slug: "tallow-mama",
    name: "Tallow Mama",
    tagline: "Regenerative tallow soaps and whipped butters — blood orange, blue tansy, baby unscented, no sticker shop",
    story: "A regenerative-tallow kitchen that pours blood-orange clay soap, blue-tansy face butter, and unscented baby balm instead of a fragrance-heavy cream wall. Soaps, butters, lip balm, and cleansing oil stay. Gift cards, donation stickers, soap scrap bags, and sisal pouches stay in the farm stand.",
    location: "United States",
    founded: 2023,
    categories: ["skincare"],
    accent: "#C45C26",
    rating: 4.8,
    reviewCount: 210,
    followerCount: 3600,
    websiteUrl: "https://tallowmama.com",
    logoUrl: "/brands/tallow-mama.svg",
  },
  {
    id: "c1037",
    slug: "pure-tallow",
    name: "The Pure Tallow",
    tagline: "Velvet Hour tallow balms — Moon Dew, Rose Noir, Amber Glow, no mascara refill wall",
    story: "A three-scent tallow house that whips Velvet Hour balms into Moon Dew, Rose Noir, and Amber Glow instead of a 40-ingredient cream aisle. Each scent stays as its own listing, including the minis. Aer Cosmetics mascara tablets stay in the makeup drawer.",
    location: "United States",
    founded: 2024,
    categories: ["skincare"],
    accent: "#8B6914",
    rating: 4.6,
    reviewCount: 70,
    followerCount: 1200,
    websiteUrl: "https://thepuretallow.com",
    logoUrl: "/brands/pure-tallow.svg",
  },
  {
    id: "c1038",
    slug: "austin-handcrafted",
    name: "Austin Handcrafted",
    tagline: "Texas-made shampoo bar, facial serum, and beard oil — no holiday brine pantry",
    story: "A three-SKU Austin workshop that pours an eco shampoo bar, a restore facial serum, and a beard oil instead of a plastic-bottle-and-synthetic-fragrance wall. The formulas stay. Citrus herb brine and BBQ rub stay in the pantry.",
    location: "Austin, Texas",
    founded: 2020,
    categories: ["hair","skincare"],
    accent: "#5B7A3A",
    rating: 4.5,
    reviewCount: 90,
    followerCount: 1400,
    websiteUrl: "https://austinhandcrafted.com",
    logoUrl: "/brands/austin-handcrafted.svg",
  },
];
