import type { Brand } from "./types";

/** Wave 20: small organic / toxic-free brands across marketplace categories (c778+). */
export const catalogBrandsWave20: Brand[] = [
  {
    id: "c778",
    slug: "seaflora",
    name: "Seaflora Skincare",
    tagline: "Wild BC seaweed and non-nano zinc — mineral sun shield from a Sooke shoreline studio",
    story: "Hand-harvested West Coast seaweed is the water in Seaflora's formulas. The Sea-to-Skin sun shield pairs wild Pyropia with reef-safe non-nano zinc — no chemical filters, no coral-killing cocktail. Shampoo, conditioner, and lotions stay in the same short, ocean-minded list.",
    location: "Sooke, British Columbia",
    founded: 2009,
    categories: ["sunscreen","hair","skincare"],
    accent: "#1B6B6A",
    rating: 4.8,
    reviewCount: 640,
    followerCount: 12000,
    websiteUrl: "https://seafloraskincare.com",
    logoUrl: "/brands/seaflora.png",
  },
  {
    id: "c779",
    slug: "people4ocean",
    name: "people4ocean",
    tagline: "Australian mineral SPF 50+ zinc sticks and bioactive creams that fund ocean work",
    story: "A small Australian house that treats sunscreen as ocean advocacy. Non-nano zinc creams and tinted sticks skip oxybenzone and octinoxate, and a cut of each tin goes back to reef and shoreline projects. After-sun gel is the only extra — no perfume aisle, no chemical-filter stack.",
    location: "Australia",
    founded: 2015,
    categories: ["sunscreen"],
    accent: "#1D6A8A",
    rating: 4.7,
    reviewCount: 890,
    followerCount: 18000,
    websiteUrl: "https://people4ocean.com",
    logoUrl: "/brands/people4ocean.png",
  },
  {
    id: "c780",
    slug: "field-and-forge",
    name: "Field And Forge",
    tagline: "Trail-ready mineral sun balm — cacao-tinted zinc with mango butter and jojoba",
    story: "Built for surf, snow, and sunny trail days. Daily Mineral Defense is a short-list balm: non-nano zinc, mango butter, jojoba, castor, vitamin E, cacao. No chemical filters, no water, no preservative circus. Lip balm and facial oils stay in the same kitchen-simple register.",
    location: "United States",
    founded: 2021,
    categories: ["sunscreen","skincare"],
    accent: "#6B4A2A",
    rating: 4.8,
    reviewCount: 210,
    followerCount: 4200,
    websiteUrl: "https://shopfieldandforge.com",
    logoUrl: "/brands/field-and-forge.svg",
  },
  {
    id: "c781",
    slug: "purelytes",
    name: "Purelytes",
    tagline: "Organic freeze-dried fruit electrolytes sweetened with panela — no stevia, no monk fruit",
    story: "Hydration that reads like a fruit bowl. Purelytes flavors with organic freeze-dried fruit and sweetens with unrefined panela cane juice — sodium, potassium, and magnesium without stevia, monk fruit, or mystery 'natural flavors.' Lemon-lime, mango, pineapple, strawberry, plus unsweetened.",
    location: "United States",
    founded: 2022,
    categories: ["electrolytes"],
    accent: "#E27D60",
    rating: 4.7,
    reviewCount: 380,
    followerCount: 6500,
    websiteUrl: "https://getpurelytes.com",
    logoUrl: "/brands/purelytes.svg",
  },
  {
    id: "c782",
    slug: "peak-hydration",
    name: "Peak Hydration",
    tagline: "Certified organic hydration multiplier with collagen — 2g glucose, no artificial sweeteners",
    story: "A single clean formula: organic electrolytes plus collagen, with just enough organic glucose to help the sodium land. No artificial sweeteners, no preservatives, soy-free and gluten-free. Made in the US for people who want hydration that also reads like a wellness powder.",
    location: "United States",
    founded: 2021,
    categories: ["electrolytes"],
    accent: "#2A9D8F",
    rating: 4.6,
    reviewCount: 160,
    followerCount: 3100,
    websiteUrl: "https://www.peakhydration.com",
    logoUrl: "/brands/peak-hydration.svg",
  },
  {
    id: "c783",
    slug: "powah",
    name: "Powah",
    tagline: "Organic Nordic berry hydration — sea buckthorn, cloudberry, rhodiola, no fillers",
    story: "Daily Hustle and Daily Joy are all-in-one drink mixes: organic Nordic superberries, Himalayan salt, ginseng, and rhodiola. Third-party tested, zero sugar, no 'natural flavors.' Hydration with adaptogens that still fits in a shaker, not a candy aisle.",
    location: "United States",
    founded: 2023,
    categories: ["electrolytes"],
    accent: "#5B2C6F",
    rating: 4.6,
    reviewCount: 140,
    followerCount: 2800,
    websiteUrl: "https://shoppowah.com",
    logoUrl: "/brands/powah.svg",
  },
  {
    id: "c784",
    slug: "mycopro",
    name: "MycoPro",
    tagline: "UK plant protein with lion's mane and cordyceps — pea, hemp, fava, no junk",
    story: "A small UK house that treats protein like a nootropic. Twenty grams from pea, hemp, and fava, then a real dose of lion's mane and cordyceps plus a digestive enzyme blend. Chocolate and vanilla, sugar-free, Himalayan salt — no gums-for-the-sake-of-gums formula.",
    location: "United Kingdom",
    founded: 2022,
    categories: ["protein"],
    accent: "#3D6B4F",
    rating: 4.7,
    reviewCount: 220,
    followerCount: 5400,
    websiteUrl: "https://mycoproworld.com",
    logoUrl: "/brands/mycopro.svg",
  },
  {
    id: "c785",
    slug: "bee-you",
    name: "Bee You Organics",
    tagline: "Pacific Northwest kitchen — organic pit balm, coconut-milk shampoo bars, food-grade oils",
    story: "Handmade from scratch in the Pacific Northwest with USDA organic, food-grade oils. The pit balm is aluminum-free; shampoo bars are vegan, palm-oil-free, and plastic-free. No alcohol, no synthetic fragrance, no parabens — the kind of label you can read out loud.",
    location: "Pacific Northwest, United States",
    founded: 2016,
    categories: ["deodorant","hair","skincare"],
    accent: "#C45C26",
    rating: 4.8,
    reviewCount: 1100,
    followerCount: 16000,
    websiteUrl: "https://beeyouorganics.com",
    logoUrl: "/brands/bee-you.svg",
  },
  {
    id: "c786",
    slug: "moose-tallow",
    name: "Moose's Tallow",
    tagline: "Lebanon, PA family tallow — baking-soda-free deodorant, whipped butters, beard balms",
    story: "A family kitchen in Lebanon, Pennsylvania that renders tallow and pours deodorant without aluminum or baking soda. Zinc and magnesium handle odor; whipped body butters and egg-yolk beard balms stay short-list. Small batches, no propylene glycol, no perfume-lab mystery.",
    location: "Lebanon, Pennsylvania",
    founded: 2020,
    categories: ["deodorant","skincare","hair"],
    accent: "#6B3E26",
    rating: 4.8,
    reviewCount: 740,
    followerCount: 9800,
    websiteUrl: "https://moosestallow.com",
    logoUrl: "/brands/moose-tallow.svg",
  },
  {
    id: "c787",
    slug: "tallow-and-vine",
    name: "Tallow & Vine",
    tagline: "Grass-fed tallow deodorant and zinc sun sticks — no aluminum, no seed-oil filler stack",
    story: "USA-made tallow deodorant with shea, clays, and mineral odor control — aluminum-free, fragrance-honest, sensitive-skin minded. The same kitchen pours tallow-and-zinc sun sticks and after-sun balms. Short formulas for people who want pits and SPF from one grass-fed pot.",
    location: "United States",
    founded: 2022,
    categories: ["deodorant","sunscreen","skincare"],
    accent: "#2C5F4E",
    rating: 4.7,
    reviewCount: 430,
    followerCount: 7200,
    websiteUrl: "https://tallowandvine.com",
    logoUrl: "/brands/tallow-and-vine.svg",
  },
  {
    id: "c788",
    slug: "tallowbourn",
    name: "Tallowbourn",
    tagline: "Grass-fed tallow sun balm, extra-strength deodorant, and baking-soda-free sticks",
    story: "Outdoor-first tallow care: mineral zinc sun balm, extra-strength deodorant, and a baking-soda-free stick for reactive pits. Soaps and lip balms stay grass-fed and petroleum-free. Built for people who sweat outside and still want a label they can pronounce.",
    location: "United States",
    founded: 2021,
    categories: ["deodorant","sunscreen","skincare"],
    accent: "#8B5A2B",
    rating: 4.7,
    reviewCount: 310,
    followerCount: 5100,
    websiteUrl: "https://tallowbourn.com",
    logoUrl: "/brands/tallowbourn.svg",
  },
  {
    id: "c789",
    slug: "ht-botanicals",
    name: "HT Botanicals",
    tagline: "Vero Beach farm toothpaste — spherical hydroxyapatite, theobromine, 30+ botanicals",
    story: "Living Crystal toothpaste is hand-blended on a Vero Beach biodynamic farm: spherical hydroxyapatite plus cacao theobromine, not a fluoride swap with a marketing name. Mouth rinse, shampoo, and face serums stay in the same farm-grown, fluoride-free, SLS-free lane.",
    location: "Vero Beach, Florida",
    founded: 2018,
    categories: ["oral","hair","skincare"],
    accent: "#1B4F72",
    rating: 4.8,
    reviewCount: 560,
    followerCount: 8900,
    websiteUrl: "https://htbotanicals.com",
    logoUrl: "/brands/ht-botanicals.svg",
  },
  {
    id: "c790",
    slug: "cow-guys",
    name: "Cow Guys",
    tagline: "Texas rancher tallow — suet-rendered balms and magnesium deodorant, no baking soda",
    story: "Rancher-founded in Bryan, Texas. They render kidney suet low and slow, then blend balms and deodorant with magnesium hydroxide instead of baking soda. No aluminum, no hidden fragrance, no seed-oil filler stack — ranch tallow for people who actually work outside.",
    location: "Bryan, Texas",
    founded: 2021,
    categories: ["skincare","deodorant"],
    accent: "#7A3E1D",
    rating: 4.7,
    reviewCount: 280,
    followerCount: 4600,
    websiteUrl: "https://www.cowguys.shop",
    logoUrl: "/brands/cow-guys.svg",
  },
  {
    id: "c791",
    slug: "taddos-tallow",
    name: "Taddo's Tallow",
    tagline: "Grass-fed suet tallow deodorant and whipped balms — zinc, kaolin, no baking soda",
    story: "Water-free tallow care so nothing needs a preservative circus. Deodorant uses suet tallow, zinc, kaolin, and arrowroot — aluminum-free and baking-soda-free. Whipped tallow, lotion sticks, and lip balms stay in the same four-to-eight-ingredient kitchen.",
    location: "United States",
    founded: 2020,
    categories: ["skincare","deodorant"],
    accent: "#5B3A29",
    rating: 4.8,
    reviewCount: 390,
    followerCount: 6700,
    websiteUrl: "https://taddostallow.com",
    logoUrl: "/brands/taddos-tallow.svg",
  },
  {
    id: "c792",
    slug: "original-sprout",
    name: "Original Sprout",
    tagline: "Tear-free natural hair care for kids and grown-ups — short lists, no junk foam",
    story: "A family hair-care house that started with kids who couldn't tolerate the usual shampoo aisle. Island Bliss and Coastal lines stay tear-conscious and fragrance-honest, with protein mist and body wash in the same clean register. No sulfates-for-the-sake-of-foam formulas.",
    location: "United States",
    founded: 2008,
    categories: ["hair","skincare"],
    accent: "#3D8B6E",
    rating: 4.7,
    reviewCount: 2100,
    followerCount: 24000,
    websiteUrl: "https://www.originalsprout.com",
    logoUrl: "/brands/original-sprout.png",
  },
  {
    id: "c793",
    slug: "made-new",
    name: "Made New Naturals",
    tagline: "Plastic-free shampoo and conditioner bars plus tallow deodorant — small-batch, scent options",
    story: "Solid hair care that replaces the plastic bottle: shampoo bars in real scents, a conditioner bar, then tallow balm and deodorant for the rest of the bathroom. Small-batch, no sulfate circus, and the merch-and-study-book aisle stays off this marketplace shelf.",
    location: "United States",
    founded: 2022,
    categories: ["hair","deodorant","skincare"],
    accent: "#4A6B3A",
    rating: 4.6,
    reviewCount: 180,
    followerCount: 3400,
    websiteUrl: "https://madenewnaturals.com",
    logoUrl: "/brands/made-new.svg",
  },
  {
    id: "c794",
    slug: "mud-wtr",
    name: "MUD\\WTR",
    tagline: "Organic mushroom coffee alternative and Nourish protein — California-grown fruiting bodies",
    story: "A masala-chai-and-cacao morning ritual with lion's mane, chaga, reishi, and cordyceps instead of a third espresso. USDA organic, California-grown mushrooms, no mystery oils. Nourish adds 25g vegan protein plus nootropics and probiotics for people who want one clean scoop.",
    location: "California, United States",
    founded: 2018,
    categories: ["supplements","protein"],
    accent: "#4A3728",
    rating: 4.5,
    reviewCount: 8200,
    followerCount: 110000,
    websiteUrl: "https://mudwtr.com",
    logoUrl: "/brands/mud-wtr.svg",
  },
];
