import type { Brand } from "./types";

/** Wave 37: small organic / toxic-free brands across marketplace categories (c1019+). */
export const catalogBrandsWave37: Brand[] = [
  {
    id: "c1039",
    slug: "tallow-balm-co",
    name: "Tallow Balm Co",
    tagline: "USDA organic grass-fed tallow balms plus a non-nano mineral sun cream — no seed-oil wall, no merch tee",
    story: "A family-owned US tallow kitchen that whips USDA organic grass-fed suet into original balm, cloud moisturizer, pocket sticks, and a reef-safe non-nano zinc sun cream instead of a 30-ingredient lotion aisle. Lip serum tints stay as their own listings. The Tallow Guard shirt stays in the merch locker.",
    location: "United States",
    founded: 2023,
    categories: ["sunscreen","skincare"],
    accent: "#8B6914",
    rating: 4.7,
    reviewCount: 240,
    followerCount: 4100,
    websiteUrl: "https://www.tallowbalmco.com",
    logoUrl: "/brands/tallow-balm-co.svg",
  },
  {
    id: "c1040",
    slug: "tallow-and-wild",
    name: "Tallow & Wild",
    tagline: "Three-SKU tallow house — mineral SPF 35, honey balm, unscented balm, nothing else",
    story: "A tiny regenerative kitchen that pours organic grass-fed tallow into a mineral SPF 35, a honey balm, and an unscented balm instead of a fragrance-heavy cream wall. Each of the three formulas stays as its own listing. No merch, no pantry, no empty tins.",
    location: "United States",
    founded: 2024,
    categories: ["sunscreen","skincare"],
    accent: "#5B7A3A",
    rating: 4.6,
    reviewCount: 80,
    followerCount: 1400,
    websiteUrl: "https://tallowandwild.com",
    logoUrl: "/brands/tallow-and-wild.svg",
  },
  {
    id: "c1041",
    slug: "chagrin-valley",
    name: "Chagrin Valley Soap & Salve",
    tagline: "Ohio-made organic shampoo bars, soaps, and aluminum-free deodorants — scent variants, no pet aisle, no room spray",
    story: "A Chagrin Falls workshop that saponifies organic oils into shampoo bars, cold-process soaps, dry shampoos, and aluminum-free deodorants instead of a plastic-bottle-and-synthetic-fragrance wall. Lip balms, lotion bars, facial oils, and beard oils stay as their own scent listings. Subscription boxes, room sprays, pet SKUs, apparel, and massage candles stay out.",
    location: "Chagrin Falls, Ohio",
    founded: 1997,
    categories: ["hair","skincare","deodorant"],
    accent: "#2C5F4E",
    rating: 4.8,
    reviewCount: 2100,
    followerCount: 28000,
    websiteUrl: "https://www.chagrinvalleysoapandsalve.com",
    logoUrl: "/brands/chagrin-valley.svg",
  },
  {
    id: "c1042",
    slug: "haus-of-sage",
    name: "Haus of Sage",
    tagline: "Florida-made tallow deodorant, whipped moisturizers, and zinc sun balms — scent variants, no white-label 48-pack",
    story: "A woman-owned Florida tallow house that pours charcoal-mint and bergamot deodorant sticks, whipped tallow, and a zinc sun balm instead of an aluminum-and-chemical-filter wall. Lip balm and whipped-tallow scents stay as their own listings. White-label 48-packs and wholesale display jars stay in the retailer drawer.",
    location: "Florida, United States",
    founded: 2022,
    categories: ["deodorant","skincare","sunscreen"],
    accent: "#6B3E26",
    rating: 4.7,
    reviewCount: 360,
    followerCount: 6200,
    websiteUrl: "https://thehausofsage.com",
    logoUrl: "/brands/haus-of-sage.svg",
  },
  {
    id: "c1043",
    slug: "lather-and-leaf",
    name: "Lather and Leaf",
    tagline: "Small-batch coconut-milk and tallow soap bars — watermelon, lilac, goat-milk oatmeal, no accessory shop",
    story: "A cold-process soap kitchen that pours coconut-milk, triple-butter, and tallow bars in scents like watermelon, lilac, and goat-milk oatmeal instead of a detergent-and-fragrance wall. Each scent stays as its own listing. No merch, no soap dishes, no empty tins.",
    location: "United States",
    founded: 2020,
    categories: ["skincare"],
    accent: "#C45C26",
    rating: 4.6,
    reviewCount: 190,
    followerCount: 2800,
    websiteUrl: "https://latherandleaf.com",
    logoUrl: "/brands/lather-and-leaf.svg",
  },
  {
    id: "c1044",
    slug: "saint-oral",
    name: "Saint",
    tagline: "Nano-hydroxyapatite mint toothpaste plus coconut, tangerine, and wild-mint floss — no whitening-strip gadget wall",
    story: "A clean oral house that infuses nano-hydroxyapatite into fluoride and fluoride-free mint pastes instead of a plastic-tube-and-peroxide aisle. Coconut, tangerine, and wild-mint floss stay as their own listings. Hidden discount SKUs and peroxide whitening strips stay out.",
    location: "United States",
    founded: 2021,
    categories: ["oral"],
    accent: "#1B4F72",
    rating: 4.6,
    reviewCount: 1800,
    followerCount: 22000,
    websiteUrl: "https://saintoralhealth.com",
    logoUrl: "/brands/saint-oral.svg",
  },
  {
    id: "c1045",
    slug: "seen-oral",
    name: "Seen Oral Care",
    tagline: "New Zealand nano-hydroxyapatite toothpastes — enamel, enzyme whitening, microbiome, no electric-brush shop",
    story: "A New Zealand oral kitchen that folds nano-hydroxyapatite, manuka oil, and postbiotics into enamel-care, enzyme-whitening, and microbiome pastes instead of a fluoride-and-SLS wall. Floss-pick infusions and soft brushes stay. No electric heads, no merch totes.",
    location: "New Zealand",
    founded: 2022,
    categories: ["oral"],
    accent: "#1565C0",
    rating: 4.5,
    reviewCount: 420,
    followerCount: 5400,
    websiteUrl: "https://www.seenoralcare.com",
    logoUrl: "/brands/seen-oral.svg",
  },
  {
    id: "c1046",
    slug: "surface-sunscreen",
    name: "Surface Sunscreen",
    tagline: "Mineral SPF 30–60 lotions, tinted sticks, and SPF lip balms — tropix and unscented, no chemical dry-touch spray",
    story: "A California sport-sun house that keeps the mineral lotions, tinted face sticks, and mango / piña-colada / coconut-berry SPF lips instead of a chemical-filter dry-touch wall. After-sun aloe stays. Dry-touch chemical sprays, golf bundles, and anti-chafe sticks stay out.",
    location: "California, United States",
    founded: 2012,
    categories: ["sunscreen"],
    accent: "#1B4F72",
    rating: 4.6,
    reviewCount: 980,
    followerCount: 16000,
    websiteUrl: "https://surfacesunscreen.com",
    logoUrl: "/brands/surface-sunscreen.svg",
  },
  {
    id: "c1047",
    slug: "wellah",
    name: "Wellah",
    tagline: "Women's hydration sticks, grass-fed whey, and collagen — flavor variants, no pre-workout, no shaker merch",
    story: "A women's wellness kitchen that seasons water with strawberry-lemonade and peach-clementine electrolytes, then folds grass-fed whey and multi-collagen into everyday scoops instead of a neon pre-workout wall. Each flavor stays as its own listing. Pre-workout, shaker bottles, and sample-plus-shaker kits stay in the gym-bag drawer.",
    location: "United States",
    founded: 2023,
    categories: ["electrolytes","protein","supplements"],
    accent: "#C45C26",
    rating: 4.6,
    reviewCount: 740,
    followerCount: 11000,
    websiteUrl: "https://wellah.com",
    logoUrl: "/brands/wellah.svg",
  },
];
