import type { Brand } from "./types";

/** Wave 25: small organic / toxic-free brands across marketplace categories (c868+). */
export const catalogBrandsWave25: Brand[] = [
  {
    id: "c868",
    slug: "stream2sea",
    name: "Stream2Sea",
    tagline: "Reef-safe mineral sunscreen and swim-proof hair bars — zinc first, no oxybenzone circus",
    story: "A Florida ocean house that built mineral SPF and shampoo bars for people who actually get in the water. Coral Care and Water Sport sticks stay. Insect spray, gear wash, donations, and ball caps stay off this shelf.",
    location: "Florida, United States",
    founded: 2014,
    categories: ["sunscreen","hair","skincare"],
    accent: "#1B6B8A",
    rating: 4.7,
    reviewCount: 2100,
    followerCount: 18000,
    websiteUrl: "https://stream2sea.com",
    logoUrl: "/brands/stream2sea.png",
  },
  {
    id: "c869",
    slug: "raw-elements",
    name: "Raw Elements",
    tagline: "Non-nano zinc tins and tinted face SPF — plastic-light mineral sun, no chemical-filter dump",
    story: "A Vermont mineral house that still pours SPF 30 into tins and bio-resin tubes. Tinted face moisturizer, lip rescue, and after-sun stay. Lifeguard hats, sunshirts, and bug spray stay in the merch drawer.",
    location: "Vermont, United States",
    founded: 2013,
    categories: ["sunscreen","skincare"],
    accent: "#C45C26",
    rating: 4.7,
    reviewCount: 3400,
    followerCount: 22000,
    websiteUrl: "https://rawelementsusa.com",
    logoUrl: "/brands/raw-elements.png",
  },
  {
    id: "c870",
    slug: "brush-on-block",
    name: "Brush On Block",
    tagline: "Mineral powder sunscreen in a brush — zinc you sweep on, no greasy chemical lotion",
    story: "A powder-SPF studio that puts non-nano zinc in a refillable brush instead of a 30-ingredient lotion. Translucent, Touch of Tan, kids lotion, and refills stay. Protect-your-pout bags do not.",
    location: "United States",
    founded: 2011,
    categories: ["sunscreen"],
    accent: "#E27D60",
    rating: 4.6,
    reviewCount: 2800,
    followerCount: 16000,
    websiteUrl: "https://brushonblock.com",
    logoUrl: "/brands/brush-on-block.png",
  },
  {
    id: "c871",
    slug: "july-sky",
    name: "July Sky",
    tagline: "One mineral face sunscreen — 18.9% non-nano zinc, serum texture, no white-cast circus",
    story: "A tiny skincare kitchen that makes one thing: C-Shells, a sheer mineral SPF 30 with non-nano zinc and a short antioxidant list. No chemical filters. No 12-SKU sun aisle.",
    location: "United States",
    founded: 2021,
    categories: ["sunscreen","skincare"],
    accent: "#F2C94C",
    rating: 4.8,
    reviewCount: 120,
    followerCount: 1800,
    websiteUrl: "https://julyskyskincare.com",
    logoUrl: "/brands/july-sky.svg",
  },
  {
    id: "c872",
    slug: "hume",
    name: "Hume Supernatural",
    tagline: "All-over aluminum-free deodorant and clean body wash — no baking-soda burn, no perfume-lab stick",
    story: "A clean-body house that treats pits and skin like the same job: aluminum-free all-body deodorant plus a short-list wash. Scent variants stay. No conventional antiperspirant aisle.",
    location: "United States",
    founded: 2020,
    categories: ["deodorant","skincare"],
    accent: "#2C5F4E",
    rating: 4.6,
    reviewCount: 1900,
    followerCount: 14000,
    websiteUrl: "https://humesupernatural.com",
    logoUrl: "/brands/hume.svg",
  },
  {
    id: "c873",
    slug: "pretty-frank",
    name: "Pretty Frank",
    tagline: "Aluminum-free deodorant sticks and pastes — baking-soda and sensitive formulas, real scent variants",
    story: "A small deodorant kitchen that still makes sticks and jar pastes in unscented, orange vanilla, coconut lime, and woodlands. Aluminum stays out. Baking-soda-free options stay for skin that burns.",
    location: "United States",
    founded: 2016,
    categories: ["deodorant"],
    accent: "#C4A484",
    rating: 4.7,
    reviewCount: 1600,
    followerCount: 11000,
    websiteUrl: "https://prettyfrank.com",
    logoUrl: "/brands/pretty-frank.png",
  },
  {
    id: "c874",
    slug: "fussy",
    name: "Fussy",
    tagline: "Refillable UK deodorant and wash bars — compostable refills, no plastic-stick graveyard",
    story: "A London refill house that sells deodorant cases once and compostable refills forever. Sicilian lemon, rhubarb, peach, and sensitive packs stay. Body-wash and exfoliating bars stay as real formulas, not merch.",
    location: "London, United Kingdom",
    founded: 2019,
    categories: ["deodorant","skincare"],
    accent: "#6B4C7A",
    rating: 4.6,
    reviewCount: 4200,
    followerCount: 28000,
    websiteUrl: "https://fussy.com",
    logoUrl: "/brands/fussy.png",
  },
  {
    id: "c875",
    slug: "nelson-naturals",
    name: "Nelson Naturals",
    tagline: "Hydroxyapatite tooth powder in glass — fluoride-free, SLS-free, no neon-gel circus",
    story: "A Canadian oral kitchen that packs remineralizing powders into glass, not a plastic tube of foam. Hydroxyapatite jars, fennel, charcoal, and floss stay. Wholesale tubs and test SKUs stay off the marketplace.",
    location: "Canada",
    founded: 2011,
    categories: ["oral"],
    accent: "#1565C0",
    rating: 4.8,
    reviewCount: 890,
    followerCount: 7200,
    websiteUrl: "https://nelsonnaturals.com",
    logoUrl: "/brands/nelson-naturals.png",
  },
  {
    id: "c876",
    slug: "purelyte",
    name: "Purelyte",
    tagline: "Zero-sugar Australian electrolytes — full sweat minerals, no neon sports-drink dye stack",
    story: "An Australian hydration house that replaces what you actually sweat: sodium, potassium, magnesium, calcium. Fruit flavors stay. Wholesale cartons and steel bottles stay in the warehouse.",
    location: "Australia",
    founded: 2024,
    categories: ["electrolytes"],
    accent: "#2A9D8F",
    rating: 4.7,
    reviewCount: 340,
    followerCount: 4100,
    websiteUrl: "https://purelyte.com.au",
    logoUrl: "/brands/purelyte.svg",
  },
  {
    id: "c877",
    slug: "ancient-brave",
    name: "Ancient + Brave",
    tagline: "Grass-fed collagen, creatine, and hydration — short labels, no candy-aisle scoop",
    story: "A UK ritual kitchen that treats collagen and creatine like food, not a neon tub. True Collagen, Wild Collagen, True Hydration, and creatine stay. Flavor variants stay as their own listings.",
    location: "United Kingdom",
    founded: 2018,
    categories: ["protein","supplements","electrolytes"],
    accent: "#5E4B45",
    rating: 4.7,
    reviewCount: 5600,
    followerCount: 42000,
    websiteUrl: "https://ancientandbrave.earth",
    logoUrl: "/brands/ancient-brave.svg",
  },
  {
    id: "c878",
    slug: "wild-nutrition",
    name: "Wild Nutrition",
    tagline: "Food-Grown® vitamins and organic protein — no synthetic isolate stack, no megastore multi",
    story: "A British food-state house that grows minerals into food instead of dumping isolates in a capsule. Daily essentials, menopause complex, and organic protein stay. Trial minis stay only when they are a real formula.",
    location: "United Kingdom",
    founded: 2010,
    categories: ["supplements","protein"],
    accent: "#5B7A3A",
    rating: 4.7,
    reviewCount: 3800,
    followerCount: 26000,
    websiteUrl: "https://wildnutrition.com",
    logoUrl: "/brands/wild-nutrition.png",
  },
  {
    id: "c879",
    slug: "together-health",
    name: "Together Health",
    tagline: "Food-state vitamins in ocean-safe seaweed capsules — no titanium-dioxide tablet circus",
    story: "A small UK supplement house that puts vitamins in seaweed capsules instead of a dye-coated tablet. Pregnancy, vegan complete, milk thistle, and rhodiola stay. No megastore gummy aisle.",
    location: "United Kingdom",
    founded: 2015,
    categories: ["supplements"],
    accent: "#2E7D32",
    rating: 4.7,
    reviewCount: 2400,
    followerCount: 18000,
    websiteUrl: "https://togetherhealth.co.uk",
    logoUrl: "/brands/together-health.svg",
  },
  {
    id: "c880",
    slug: "josh-rosebrook",
    name: "Josh Rosebrook",
    tagline: "Organic herbal skincare and hair — farm botanicals, no 40-ingredient silicone cream",
    story: "A California herbalist kitchen that still treats face and hair like plants. Essential balm cleanse, nourish shampoo, and serums stay. Sample packets stay only when they are a real formula, not merch.",
    location: "California, United States",
    founded: 2008,
    categories: ["skincare","hair"],
    accent: "#6B3E26",
    rating: 4.8,
    reviewCount: 2100,
    followerCount: 19000,
    websiteUrl: "https://joshrosebrook.com",
    logoUrl: "/brands/josh-rosebrook.png",
  },
  {
    id: "c881",
    slug: "evan-healy",
    name: "Evan Healy",
    tagline: "Regenerative organic hydrosoils and oils — rose, shea, and clay, no synthetic-fragrance dump",
    story: "The first regenerative-organic beauty house: hydrosoils, whipped shea, and plant oils from farms they can name. Serums, clays, and rosemary hair stay. Postcards, booklets, and hang tags stay in the studio drawer.",
    location: "Oregon, United States",
    founded: 1999,
    categories: ["skincare","hair"],
    accent: "#8B5A2B",
    rating: 4.8,
    reviewCount: 1700,
    followerCount: 15000,
    websiteUrl: "https://evanhealy.com",
    logoUrl: "/brands/evan-healy.png",
  },
  {
    id: "c882",
    slug: "living-libations",
    name: "Living Libations",
    tagline: "Wildcrafted Best Skin Ever oils and oral care — botanical, no synthetic-detergent drawer",
    story: "A Canadian apothecary that still bottles face oils, dental blends, and sun care from plants. Best Skin Ever, Fresh Start dental, and sun kits stay. Essential-oil singles, incense, and dopp bags stay off this shelf.",
    location: "Ontario, Canada",
    founded: 2000,
    categories: ["skincare","hair","oral"],
    accent: "#3D6B4F",
    rating: 4.8,
    reviewCount: 3100,
    followerCount: 24000,
    websiteUrl: "https://livinglibations.com",
    logoUrl: "/brands/living-libations.png",
  },
  {
    id: "c883",
    slug: "kahina",
    name: "Kahina Giving Beauty",
    tagline: "Moroccan argan skincare with cooperatives — short INCI, no 40-step serum aisle",
    story: "A Giving Beauty house that pays cooperatives for argan and keeps the formula short: oil cleanser, masks, lip balm, body serum. Gift cards stay off the marketplace.",
    location: "United States / Morocco",
    founded: 2009,
    categories: ["skincare"],
    accent: "#C45C26",
    rating: 4.7,
    reviewCount: 980,
    followerCount: 8600,
    websiteUrl: "https://kahina-givingbeauty.com",
    logoUrl: "/brands/kahina.png",
  },
  {
    id: "c884",
    slug: "try-tallow",
    name: "TryTallow",
    tagline: "Grass-fed whipped tallow balm, sun-balm, and hair clay — farm fat, no seed-oil filler stack",
    story: "A small US tallow kitchen that triple-renders grass-fed fat into balm, soap, chapstick, and a zinc sun-balm. Scent variants stay. Spatulas stay in the merch drawer.",
    location: "United States",
    founded: 2022,
    categories: ["skincare","hair","sunscreen"],
    accent: "#C4A484",
    rating: 4.8,
    reviewCount: 740,
    followerCount: 9200,
    websiteUrl: "https://trytallow.com",
    logoUrl: "/brands/try-tallow.svg",
  },
  {
    id: "c885",
    slug: "fatco",
    name: "FATCO",
    tagline: "Ancestral tallow cream, deodorant, and shampoo bars — no soy, no 40-ingredient lotion",
    story: "A tallow house that still treats fat as the moisturizer: face cream, stank-stop deodorant, and shampoo bars. Tees, kids shirts, and travel bags stay off this shelf.",
    location: "United States",
    founded: 2014,
    categories: ["skincare","deodorant","hair"],
    accent: "#1A1A1A",
    rating: 4.7,
    reviewCount: 2200,
    followerCount: 17000,
    websiteUrl: "https://fatco.com",
    logoUrl: "/brands/fatco.png",
  },
  {
    id: "c886",
    slug: "eb-and-co",
    name: "EB & CO",
    tagline: "Short-list organic haircare for textured hair — growth oil, masque, no 30-ingredient smoothie",
    story: "A small textured-hair studio that keeps the list short on purpose: Gro, Redew, Textural Healing gel-cream, and a real masque. Bundles stay when they are the same formulas, not merch.",
    location: "United States",
    founded: 2021,
    categories: ["hair"],
    accent: "#6B3E26",
    rating: 4.8,
    reviewCount: 210,
    followerCount: 3400,
    websiteUrl: "https://ebonyandcompany.com",
    logoUrl: "/brands/eb-and-co.svg",
  },
  {
    id: "c887",
    slug: "qhemet",
    name: "Qhemet Biologics",
    tagline: "African botanical haircare — rhassoul, burdock, castor, no silicone-smoothie aisle",
    story: "A botanicals house built for densely textured hair: Moroccan rhassoul shampoo, burdock butter cream, rice-water scalp drops. Combs and satin sleep caps stay off this shelf. Growth drink mixes stay as real supplements.",
    location: "United States",
    founded: 2010,
    categories: ["hair","supplements"],
    accent: "#5B7A3A",
    rating: 4.8,
    reviewCount: 1600,
    followerCount: 21000,
    websiteUrl: "https://qhemetbiologics.com",
    logoUrl: "/brands/qhemet.png",
  },
];
