import type { Brand } from "./types";

/** Wave 10: small organic / toxic-free brands across marketplace categories (c581+). */
export const catalogBrandsWave10: Brand[] = [
  {
    id: "c581",
    slug: "goodspread",
    name: "Goodspread",
    tagline: "Austin mineral SPF built to be passed around the picnic table",
    story: "Felipe Correa got tired of greasy, chalky sunscreen that nobody wanted to share. Goodspread is non-nano zinc, fragrance-free, Hawaii Act 104 reef-safe, and Go Texan–certified — one universal formula for every skin tone at the trailhead or the backyard barbecue.",
    location: "Austin, TX",
    founded: 2020,
    categories: ["sunscreen"],
    accent: "#E8A317",
    rating: 4.7,
    reviewCount: 860,
    followerCount: 12000,
    websiteUrl: "https://goodspreadsuncare.com",
    logoUrl: "/brands/goodspread.svg",
  },
  {
    id: "c582",
    slug: "roots-and-leaves",
    name: "Roots and Leaves",
    tagline: "Mostly organic mineral SPF, soapnut hair, and kitchen-table botanicals",
    story: "A tiny house making reef-safe zinc with tremella mushroom and organic aloe, plus wild-fermented soapnut shampoo — short ingredient lists, no parabens or synthetic fragrance, and formulas that read more like a garden than a lab.",
    location: "United States",
    founded: 2019,
    categories: ["sunscreen","skincare","hair"],
    accent: "#3F6B4B",
    rating: 4.8,
    reviewCount: 210,
    followerCount: 3400,
    websiteUrl: "https://rootsandleaves.info",
    logoUrl: "/brands/roots-and-leaves.svg",
  },
  {
    id: "c583",
    slug: "tropic",
    name: "Tropic Skincare",
    tagline: "Kitchen-table tropical botanicals that grew into a clean UK house",
    story: "Susie Ma started Tropic at 15 selling her grandma’s body scrub at Greenwich Market. The brand still leans on tropical botanicals, vegan formulas, and clinical-feeling textures — SPF, deodorant, and skin rituals without the usual petrochemical junk.",
    location: "United Kingdom",
    founded: 2004,
    categories: ["skincare","sunscreen","deodorant"],
    accent: "#2E8B6A",
    rating: 4.7,
    reviewCount: 18400,
    followerCount: 210000,
    websiteUrl: "https://tropicskincare.com",
    logoUrl: "/brands/tropic.svg",
  },
  {
    id: "c584",
    slug: "griffys",
    name: "Griffy's Organics",
    tagline: "Organic sacha inchi protein and lemon-lime electrolytes without the junk drawer",
    story: "A small organic kitchen blending sacha inchi, hemp, pumpkin, and pea protein with monk fruit — plus clean electrolyte mixes — so the label looks like a pantry instead of a chemistry set.",
    location: "United States",
    founded: 2021,
    categories: ["electrolytes","protein"],
    accent: "#C45C26",
    rating: 4.6,
    reviewCount: 340,
    followerCount: 5200,
    websiteUrl: "https://griffysorganics.com",
    logoUrl: "/brands/griffys.svg",
  },
  {
    id: "c585",
    slug: "roar-organic",
    name: "Roar Organic",
    tagline: "USDA Organic hydration powders that taste like fruit, not a lab",
    story: "Organic drink mixes built around coconut water, electrolytes, and real fruit flavors — immune and daily wellness powders you stir into a bottle instead of another neon sports drink with a paragraph of dyes.",
    location: "United States",
    founded: 2014,
    categories: ["electrolytes"],
    accent: "#E85D4C",
    rating: 4.5,
    reviewCount: 4200,
    followerCount: 48000,
    websiteUrl: "https://www.roarorganic.com",
    logoUrl: "/brands/roar-organic.svg",
  },
  {
    id: "c586",
    slug: "wholier",
    name: "Wholier",
    tagline: "Organic plant protein flavored with real cacao — no gums, no 'natural flavors'",
    story: "A short-list organic protein house that refuses gums, sugar alcohols, and mystery flavor systems. Real cacao and vanilla bean, plant prebiotics, and a label you can read out loud without wincing.",
    location: "United States",
    founded: 2022,
    categories: ["protein","supplements"],
    accent: "#6B4F3A",
    rating: 4.8,
    reviewCount: 480,
    followerCount: 8900,
    websiteUrl: "https://www.livewholier.com",
    logoUrl: "/brands/wholier.svg",
  },
  {
    id: "c587",
    slug: "tejari",
    name: "Tejari",
    tagline: "Organic superfood protein sweetened with dates, not stevia",
    story: "Elena Rosemond-Hoerr built Tejari around organic pea and pumpkin protein, cacao, turmeric, and date powder — no monk fruit, no stevia, no preservatives. Blend it, bake it, or stir it into yogurt like a pantry staple.",
    location: "United States",
    founded: 2016,
    categories: ["protein"],
    accent: "#8B3A2A",
    rating: 4.7,
    reviewCount: 1100,
    followerCount: 32000,
    websiteUrl: "https://www.tejariandco.com",
    logoUrl: "/brands/tejari.svg",
  },
  {
    id: "c588",
    slug: "almond-protein",
    name: "Almond Protein",
    tagline: "Two-ingredient Canadian almond protein — the nut, plus coconut nectar",
    story: "A whole-almond protein milled in Canada under 60°C. No isolates, gums, or lecithin — just California almonds and a little coconut nectar, so the shake tastes like food instead of a locker-room tub.",
    location: "Canada",
    founded: 2023,
    categories: ["protein"],
    accent: "#C4A484",
    rating: 4.7,
    reviewCount: 160,
    followerCount: 2100,
    websiteUrl: "https://almondprotein.myshopify.com",
    logoUrl: "/brands/almond-protein.svg",
  },
  {
    id: "c589",
    slug: "earth-and-pebble",
    name: "Earth & Pebble",
    tagline: "Small-batch tallow soaps and magnesium deodorant poured by hand",
    story: "Handcrafted tallow soaps, balms, and an aluminum-free deodorant built on MCT oil, beeswax, and magnesium hydroxide — no baking soda, no parabens, and a formula that actually glides instead of crumbling.",
    location: "United States",
    founded: 2022,
    categories: ["deodorant","skincare"],
    accent: "#7A6A4F",
    rating: 4.8,
    reviewCount: 290,
    followerCount: 4100,
    websiteUrl: "https://earthandpebble.com",
    logoUrl: "/brands/earth-and-pebble.svg",
  },
  {
    id: "c590",
    slug: "nobiesse",
    name: "Nobiesse",
    tagline: "EWG Verified hydroxyapatite toothpaste and short-list clean body care",
    story: "A small-batch US house making fluoride-free nano-hydroxyapatite toothpaste that’s EWG Verified and heavy-metal tested, plus aluminum-free deodorant and mineral-minded skin and home formulas without SLS or parabens.",
    location: "United States",
    founded: 2023,
    categories: ["oral","skincare","deodorant"],
    accent: "#1F4E79",
    rating: 4.8,
    reviewCount: 220,
    followerCount: 3800,
    websiteUrl: "https://nobiesse.com",
    logoUrl: "/brands/nobiesse.svg",
  },
  {
    id: "c591",
    slug: "the-innate-life",
    name: "The Innate Life",
    tagline: "Canadian herbal hair care that treats the scalp like skin",
    story: "A Toronto-born botanical hair house built around herbal scalp treatments, rose elixirs, and clean shampoo and conditioner — high-quality oils and herbs instead of a silicone cocktail, for hair that wants to grow instead of just gleam.",
    location: "Toronto, Canada",
    founded: 2018,
    categories: ["hair"],
    accent: "#4A6741",
    rating: 4.7,
    reviewCount: 1900,
    followerCount: 28000,
    websiteUrl: "https://www.theinnatelife.com",
    logoUrl: "/brands/the-innate-life.svg",
  },
  {
    id: "c592",
    slug: "hikakai",
    name: "Hikakai",
    tagline: "Shikakai hairwash and neem rituals from an old Ayurvedic pantry",
    story: "Traditional shikakai, neem, and champi oils instead of sulfate shampoo — a tiny brand bringing edible-grade Ayurvedic hair botanicals to a modern rinse, including a herbal post-wash keshasuddhi that skips the foam circus.",
    location: "India / DTC",
    founded: 2023,
    categories: ["hair"],
    accent: "#5B7A3A",
    rating: 4.8,
    reviewCount: 140,
    followerCount: 2600,
    websiteUrl: "https://www.hikakai.com",
    logoUrl: "/brands/hikakai.svg",
  },
  {
    id: "c593",
    slug: "bread-beauty",
    name: "Bread Beauty Supply",
    tagline: "Wash day, simplified — clean textured-hair care from Brooklyn",
    story: "A Brooklyn hair house that treats coils and curls like they deserve a short, honest routine: clean shampoo, conditioner, and hold that skips the 30-step shelf. Built for textured hair without the usual mystery silicones.",
    location: "Brooklyn, NY",
    founded: 2019,
    categories: ["hair"],
    accent: "#C47A2C",
    rating: 4.6,
    reviewCount: 3200,
    followerCount: 95000,
    websiteUrl: "https://breadbeautysupply.com",
    logoUrl: "/brands/bread-beauty.svg",
  },
  {
    id: "c594",
    slug: "bohema",
    name: "Bohema",
    tagline: "A two-step, gender-neutral hair duo that keeps the label short",
    story: "A tiny hair studio making a shampoo-and-conditioner duo plus one ultra-light oil — minimalist, gender-neutral formulas for people who want clean hair care without a 12-bottle ritual.",
    location: "Independent / DTC",
    founded: 2024,
    categories: ["hair"],
    accent: "#2C3E50",
    rating: 4.7,
    reviewCount: 90,
    followerCount: 1800,
    websiteUrl: "https://bohemahair.com",
    logoUrl: "/brands/bohema.svg",
  },
  {
    id: "c595",
    slug: "skwalwen",
    name: "Sḵwálwen Botanicals",
    tagline: "Squamish-harvested botanicals and the first Indigenous-made mineral SPF",
    story: "Ethnobotanist Dr. Leigh Joseph (Sḵwx̱wú7mesh) wild-harvests plants from the Squamish Estuary and turns them into soaps, salves, and Kalkáy tinted SPF 30 — Indigenous-made mineral sun care with cranberry, jojoba, and language on the label.",
    location: "Squamish, BC",
    founded: 2019,
    categories: ["skincare","sunscreen"],
    accent: "#8B5A2B",
    rating: 4.9,
    reviewCount: 640,
    followerCount: 14000,
    websiteUrl: "https://skwalwen.com",
    logoUrl: "/brands/skwalwen.svg",
  },
  {
    id: "c596",
    slug: "kabana",
    name: "Kabana Skincare",
    tagline: "Colorado organics — magnesium crème, lip balm, and quiet skin formulas",
    story: "A long-running Colorado organic house known for simple, mineral-minded skin care. Short lists, magnesium crème, and lip balm that skip the usual perfume-and-paraben pile-on.",
    location: "Colorado",
    founded: 1995,
    categories: ["skincare"],
    accent: "#B8860B",
    rating: 4.6,
    reviewCount: 780,
    followerCount: 6200,
    websiteUrl: "https://www.kabanaskincare.com",
    logoUrl: "/brands/kabana.svg",
  },
  {
    id: "c597",
    slug: "munseyaan",
    name: "MunSeyaa'n Collective",
    tagline: "West African shea and kitchen-born hair oils, made without the harsh stuff",
    story: "A family brand that started in a kitchen and still imports shea from Liberia and Ghana. Paraben-free hair oils, butters, and skin care crafted in the US and West Africa — chemical-free formulas for every texture.",
    location: "United States / West Africa",
    founded: 2021,
    categories: ["hair","skincare"],
    accent: "#8B4513",
    rating: 4.8,
    reviewCount: 310,
    followerCount: 7400,
    websiteUrl: "https://munseyaancollective.com",
    logoUrl: "/brands/munseyaan.svg",
  },
  {
    id: "c598",
    slug: "bears-with-benefits",
    name: "Bears with Benefits",
    tagline: "Berlin vitamin gummies that treat supplements like a daily ritual, not a chore",
    story: "A Berlin-born gummy house making hair, skin, cycle, and focus complexes with a cleaner ingredient brief than the candy-aisle multivitamin — playful packaging, serious botanicals, and formulas you can actually finish.",
    location: "Berlin, Germany",
    founded: 2018,
    categories: ["supplements"],
    accent: "#E8A317",
    rating: 4.5,
    reviewCount: 8600,
    followerCount: 120000,
    websiteUrl: "https://bears-with-benefits.com",
    logoUrl: "/brands/bears-with-benefits.svg",
  },
  {
    id: "c599",
    slug: "dose-and-co",
    name: "Dose & Co",
    tagline: "Grass-fed collagen peptides and creamers without the dessert-aisle additives",
    story: "A collagen house known for unflavored peptides and vanilla creamers that mix like a pantry staple — grass-fed collagen protein without a paragraph of gums, for coffee, smoothies, and everyday beauty-from-within routines.",
    location: "New Zealand / United States",
    founded: 2018,
    categories: ["supplements","protein"],
    accent: "#D4A017",
    rating: 4.6,
    reviewCount: 5400,
    followerCount: 78000,
    websiteUrl: "https://doseandco.com",
    logoUrl: "/brands/dose-and-co.svg",
  },
  {
    id: "c600",
    slug: "ample",
    name: "Ample",
    tagline: "Low-carb, plant-based meal shakes with a label that still looks like food",
    story: "A small meal-shake company building dairy-free, low-carb bottles around real ingredients instead of a neon protein slurry — plant-based shakes for people who want a complete meal without the usual additive stack.",
    location: "United States",
    founded: 2016,
    categories: ["protein"],
    accent: "#3D5A3D",
    rating: 4.5,
    reviewCount: 2100,
    followerCount: 19000,
    websiteUrl: "https://www.amplemeal.com",
    logoUrl: "/brands/ample.png",
  },
];
