import type { Brand } from "./types";

/** Wave 52: small organic / toxic-free brands across marketplace categories (c1179+). */
export const catalogBrandsWave52: Brand[] = [
  {
    id: "c1179",
    slug: "thrive-made-simple",
    name: "Thrive Made Simple",
    tagline: "Australian hydroxyapatite tooth powder and grass-fed tallow creams",
    story: "A small Australian house that mills non-nano hydroxyapatite tooth powder in minty and unflavoured jars, then pours grass-fed tallow face cream and body moisturiser. Individual powders, refill pouches, tongue scrapers, and tallow jars stay. Bundles stay boxed. AUD prices convert to USD.",
    location: "Australia",
    founded: 2022,
    categories: ["oral","skincare"],
    accent: "#3F6B4F",
    rating: 4.7,
    reviewCount: 86,
    followerCount: 2400,
    websiteUrl: "https://www.thrivemadesimple.com.au",
    logoUrl: "/brands/thrive-made-simple.svg",
  },
  {
    id: "c1180",
    slug: "purely-tallow",
    name: "Purely Tallow",
    tagline: "Tallow sunscreen, whipped lotions, baby balms, and hair oil",
    story: "A US tallow studio that pours a mineral tallow sunscreen, whipped lotions, silken pump lotion, baby balms, lip, aftershave, salt scrub, and a hair-and-beard oil. Soap and lotion scents expand. Jar size stays one listing. Soap dishes, candles, perfume, travel packs, and gift sets stay in the shop.",
    location: "United States",
    founded: 2021,
    categories: ["sunscreen","skincare","hair"],
    accent: "#8B5A2B",
    rating: 4.8,
    reviewCount: 142,
    followerCount: 3800,
    websiteUrl: "https://purelytallow.com",
    logoUrl: "/brands/purely-tallow.svg",
  },
  {
    id: "c1181",
    slug: "frankie-apothecary",
    name: "Frankie Apothecary",
    tagline: "NZ kawakawa balm, SPF 40 sun defence, and plastic-free hair bars",
    story: "A New Zealand family house built around wild-harvested kawakawa — repair balm, SPF 40 sun defence, kumarahou shampoo and vanilla conditioner bars, kakadu facial oil, bakuchiol serum, and a cleansing cake. Individual formulas stay. Gift boxes, duos, and eczema trios stay boxed. NZD prices convert to USD.",
    location: "New Zealand",
    founded: 2016,
    categories: ["sunscreen","hair","skincare"],
    accent: "#2F5D3A",
    rating: 4.8,
    reviewCount: 2100,
    followerCount: 12000,
    websiteUrl: "https://frankieapothecary.co.nz",
    logoUrl: "/brands/frankie-apothecary.svg",
  },
  {
    id: "c1182",
    slug: "zoes-kawakawa",
    name: "Zoe's Kawakawa",
    tagline: "Palmerston North kawakawa balms, lip tins, and manuka beard balm",
    story: "A small Aotearoa house that infuses locally harvested kawakawa and manuka into face-and-body balms, strawberry through lemon-aid lip balms, jasmine glow balm, ylang-ylang hand balm, and a manuka aftershave beard balm. Individual balms stay. Gift boxes, room mist, and bugs-away spray stay out. Size tins stay one listing. NZD prices convert to USD.",
    location: "Palmerston North, New Zealand",
    founded: 2017,
    categories: ["skincare","hair"],
    accent: "#4A6B3A",
    rating: 4.7,
    reviewCount: 164,
    followerCount: 3100,
    websiteUrl: "https://zoeskawakawa.co.nz",
    logoUrl: "/brands/zoes-kawakawa.svg",
  },
  {
    id: "c1183",
    slug: "pure-haven",
    name: "Pure Haven",
    tagline: "Non-tox mineral toothpaste, aluminum-free deodorant, and after-sun care",
    story: "A US non-tox house with hydroxyapatite mineral toothpaste in mint and vanilla, baking-soda and baking-soda-free deodorant scents, a mineral sunstick, after-sun spray, honey-and-fig through supergreens hair, and probiotic-forward face care. Individual formulas stay. Laundry, dish soap, makeup, essential-oil singles, refill pumps, and routine sets stay in the home aisle.",
    location: "United States",
    founded: 2014,
    categories: ["oral","deodorant","hair","sunscreen","skincare"],
    accent: "#6B8F71",
    rating: 4.6,
    reviewCount: 890,
    followerCount: 18000,
    websiteUrl: "https://purehavennontox.com",
    logoUrl: "/brands/pure-haven.svg",
  },
];
