import type { Brand } from "./types";

/** Wave 81: small organic / toxic-free brands across marketplace categories (c1355+). */
export const catalogBrandsWave81: Brand[] = [
  {
    id: "c1355",
    slug: "truthpaste",
    name: "Truthpaste",
    tagline: "UK hydroxyapatite and botanical toothpastes in glass jars — fluoride-free options and probiotic mouthwash",
    story: "A British oral house packing hydroxyapatite, charcoal, fennel, and kids Mild Mint pastes in 100 ml glass jars, plus probiotic mouthwash and charcoal floss. Flavors already live on separate titles. Jar ml is size (keep 100 ml over 15 ml travel). Bundles, toothbrush color merch, interdental multipacks, cups, and spatulas stay boxed. Cart.js is GBP × 1.27. Pages publish full INCI under Ingredients.",
    location: "United Kingdom",
    founded: 2016,
    categories: ["oral"],
    accent: "#3D6B5A",
    rating: 4.7,
    reviewCount: 890,
    followerCount: 14000,
    websiteUrl: "https://truthpaste.co.uk",
    logoUrl: "/brands/truthpaste.svg",
  },
  {
    id: "c1356",
    slug: "ground-drink",
    name: "Ground",
    tagline: "Florida electrolytes in glass jars — real fruit flavors, no plastic scoop tubs",
    story: "A Florida hydration house mixing everyday electrolytes with non-GMO fruit and optional regenerative cane sugar or stevia. Flavor expands Lemon Lime, Orange, Grapefruit, and Unflavored. Sweetener is not a flavor — keep unsweetened when it exists. Cart.js is USD. Ingredient story lives on a marketing page (leave empty unless a real formula is on the product).",
    location: "Florida",
    founded: 2023,
    categories: ["electrolytes"],
    accent: "#2F5D4A",
    rating: 4.6,
    reviewCount: 210,
    followerCount: 3200,
    websiteUrl: "https://grounddrink.com",
    logoUrl: "/brands/ground-drink.svg",
  },
  {
    id: "c1357",
    slug: "miococo",
    name: "MIOCOCO",
    tagline: "Grass-fed whey isolate and monk-fruit electrolytes with real vanilla bean and cocoa",
    story: "A clean protein house blending grass-fed whey isolate with collagen, coconut milk, and monk fruit — Vanilla Bean and Chocolate Cocoa Sea Salt already live on separate titles, plus a vegan vanilla and four electrolyte drink mixes. Serving count is size. Blender wands stay boxed. Cart.js is USD. Pages publish the short whey / collagen / monk-fruit list when a real formula is on the page.",
    location: "United States",
    founded: 2022,
    categories: ["protein","electrolytes"],
    accent: "#7A4E3A",
    rating: 4.7,
    reviewCount: 340,
    followerCount: 5600,
    websiteUrl: "https://miococo.com",
    logoUrl: "/brands/miococo.svg",
  },
  {
    id: "c1358",
    slug: "eat-my-face",
    name: "Eat My Face",
    tagline: "Small-kitchen tallow mineral SPF 30 with non-nano zinc and short-list balms",
    story: "A US founder-poured tallow house making reef-safe SPF 30 (tube and tin), after-sun balm, whipped moisturizers, night cream, baby cream, and peppermint / citrus / unscented soaps. Jar vs tube is size — keep one of each sunscreen format. Duos, 2-packs, 3-packs, starter kits, and samplers stay boxed. Cart.js is USD. Pages publish tallow / zinc / oil lists when a real INCI is on the page.",
    location: "United States",
    founded: 2023,
    categories: ["sunscreen","skincare"],
    accent: "#C47A3A",
    rating: 4.8,
    reviewCount: 280,
    followerCount: 4100,
    websiteUrl: "https://eatmyface.co",
    logoUrl: "/brands/eat-my-face.svg",
  },
  {
    id: "c1359",
    slug: "naturallow",
    name: "Naturallow",
    tagline: "Magnesium probiotic deodorant and grass-fed tallow balms with a zinc sun lotion",
    story: "A US tallow house pouring aluminum-free magnesium deodorant, whipped moisturizer, body balm, lip, soap, sugar scrub, and a zinc oxide sun lotion. Scent expands Citrus / Relax / Vanilla / Orange Creamsicle on deodorant and matching balms. Bundles, sample sacks, and gift cards stay boxed. Cart.js is USD. Pages publish tallow / magnesium / oil lists when a real INCI is on the page.",
    location: "United States",
    founded: 2021,
    categories: ["deodorant","skincare","sunscreen"],
    accent: "#8B6B3E",
    rating: 4.8,
    reviewCount: 620,
    followerCount: 8900,
    websiteUrl: "https://www.naturallow.com",
    logoUrl: "/brands/naturallow.svg",
  },
  {
    id: "c1360",
    slug: "judds-suds",
    name: "Judds Suds",
    tagline: "Finger Lakes handmade shampoo bars, leave-in conditioners, and aluminum-free deodorant",
    story: "A New York artisan house making syndet shampoo bars, solid and liquid conditioners, leave-ins, goat-milk soaps, lotions, lip balms, and natural deodorant. Scents already live on separate titles. Candles, bath bombs, shower steamers, sensory bins, gift sets, dish soap, wax melts, body sprays, and foaming hand soaps stay boxed. Cart.js is USD. Pages publish oil / butter / surfactant lists when a real INCI is on the page.",
    location: "Finger Lakes, NY",
    founded: 2018,
    categories: ["hair","deodorant","skincare"],
    accent: "#5A7A6A",
    rating: 4.7,
    reviewCount: 540,
    followerCount: 7200,
    websiteUrl: "https://juddssuds.com",
    logoUrl: "/brands/judds-suds.svg",
  },
];
