import type { Brand } from "./types";

/** Wave 55: small organic / toxic-free brands across marketplace categories (c1199+). */
export const catalogBrandsWave55: Brand[] = [
  {
    id: "c1199",
    slug: "stop-oral",
    name: "Stop Oral Care",
    tagline: "Fluoride-free hemp and Dead Sea mineral toothpaste, spray, and rinse",
    story: "A small oral house from dentist Dr. Veronica Stahl that pairs hemp botanicals with Dead Sea minerals in a fluoride-free toothpaste, a protective oral spray, and a daily mouthwash. Individual formulas stay. EUR prices convert to USD.",
    location: "Israel",
    founded: 2019,
    categories: ["oral"],
    accent: "#3F6B4A",
    rating: 4.7,
    reviewCount: 142,
    followerCount: 3100,
    websiteUrl: "https://stop-oralcare.com",
    logoUrl: "/brands/stop-oral.svg",
  },
  {
    id: "c1200",
    slug: "palm-pine",
    name: "Palm & Pine",
    tagline: "Two-SKU vegan zinc SPF 50 face sunscreen and SPF 50 lip",
    story: "A small European sports-sunscreen house pouring a fragrance-free vegan zinc SPF 50 face tin and a matching SPF 50 lip balm in recyclable aluminum. The two live formulas stay. Damaged-packaging leftovers and the SPF 30 waitlist stay boxed. GBP prices convert to USD.",
    location: "United Kingdom",
    founded: 2022,
    categories: ["sunscreen"],
    accent: "#2F6B5A",
    rating: 4.6,
    reviewCount: 88,
    followerCount: 1600,
    websiteUrl: "https://www.palmpineskincare.com",
    logoUrl: "/brands/palm-pine.svg",
  },
  {
    id: "c1201",
    slug: "healthyderm",
    name: "HealthyDerm",
    tagline: "Tallow mineral SPF 50 plus simple grass-fed tallow jars",
    story: "A small US tallow studio that suspends 25% non-nano zinc in a grass-fed tallow moisturizer, plus a tallow cleanser, honey balm, body lotion, and vitamin C serum. Individual formulas stay. Copper-peptide, methylene-blue, stem-cell, under-eye gadgets, and complete systems stay out.",
    location: "United States",
    founded: 2024,
    categories: ["sunscreen","skincare"],
    accent: "#7A5A3A",
    rating: 4.6,
    reviewCount: 74,
    followerCount: 980,
    websiteUrl: "https://healthyderm.com",
    logoUrl: "/brands/healthyderm.svg",
  },
  {
    id: "c1202",
    slug: "tallow-me-now",
    name: "Tallow Me Now",
    tagline: "Arizona small-batch whipped tallow moisturizers and lip balms",
    story: "An Arizona homestead that renders locally sourced grass-fed tallow into named whipped moisturizers — vanilla, coffee-vanilla, citrus, lavender, unscented, plus a frankincense face balm and three lip flavors. Dedicated scent SKUs stay. Jar size stays one listing.",
    location: "Arizona, United States",
    founded: 2023,
    categories: ["skincare"],
    accent: "#8B5E3C",
    rating: 4.8,
    reviewCount: 96,
    followerCount: 1400,
    websiteUrl: "https://tallowmenow.com",
    logoUrl: "/brands/tallow-me-now.svg",
  },
  {
    id: "c1203",
    slug: "little-tallow-co",
    name: "Little Tallow Co",
    tagline: "Tallow deodorant, whipped jars, soap bars, and a shampoo bar",
    story: "A small US tallow house with aluminum-free cream deodorant in bergamot, tea tree, and orange-cedarwood, plus whipped and everywhere balms, goat-milk and pure tallow soaps, lip flavors, a shampoo bar, and a bear-tallow scalp serum. Scent options expand. Laundry, dish soap, gua sha, mugs, hats, and bundles stay out.",
    location: "United States",
    founded: 2022,
    categories: ["deodorant","skincare","hair"],
    accent: "#6B4A2A",
    rating: 4.7,
    reviewCount: 210,
    followerCount: 3800,
    websiteUrl: "https://littletallowco.com",
    logoUrl: "/brands/little-tallow-co.svg",
  },
  {
    id: "c1204",
    slug: "simply-fuel",
    name: "SimplyFUEL",
    tagline: "Two-ingredient unflavored grass-fed whey isolate",
    story: "A small US protein house milling a two-ingredient unflavored, unsweetened grass-fed whey isolate — no dessert aisle, no balls-and-bites snack line in this catalog. The dedicated whey pouch stays. Cookie-dough and protein-ball flavors stay in the snack tin.",
    location: "United States",
    founded: 2018,
    categories: ["protein"],
    accent: "#3D5A40",
    rating: 4.6,
    reviewCount: 168,
    followerCount: 2400,
    websiteUrl: "https://www.simplyfuel.com",
    logoUrl: "/brands/simply-fuel.svg",
  },
  {
    id: "c1205",
    slug: "hydrojoy",
    name: "HydroJoy",
    tagline: "Zero-sugar electrolyte sticks in cherry, raspberry, lemon, lime, grape",
    story: "A small US hydration house mixing zero-sugar, zero-carb electrolyte sticks with 1,200 mg sodium and a six-mineral blend. Dedicated cherry, raspberry, lemon, lime, and grape sticks stay. Variety packs stay boxed.",
    location: "United States",
    founded: 2024,
    categories: ["electrolytes"],
    accent: "#2E6F8A",
    rating: 4.5,
    reviewCount: 54,
    followerCount: 720,
    websiteUrl: "https://hydrojoy.com",
    logoUrl: "/brands/hydrojoy.svg",
  },
  {
    id: "c1206",
    slug: "bodyflow",
    name: "BodyFlow Hydration",
    tagline: "One-SKU sugar-free mineral electrolyte concentrate",
    story: "A small US hydration house mixing a sugar-free liquid electrolyte concentrate from magnesium, potassium, sodium, and water — no flavors, no sweeteners, one 30-pack. The daily hydration pouch stays.",
    location: "United States",
    founded: 2021,
    categories: ["electrolytes"],
    accent: "#4A6B8A",
    rating: 4.6,
    reviewCount: 120,
    followerCount: 1900,
    websiteUrl: "https://shop.bodyflowhydration.com",
    logoUrl: "/brands/bodyflow.svg",
  },
];
