import type { Brand } from "./types";

/** Wave 29: small organic / toxic-free brands across marketplace categories (c937+). */
export const catalogBrandsWave29: Brand[] = [
  {
    id: "c937",
    slug: "royal-tallow",
    name: "Royal Tallow",
    tagline: "Grass-fed tallow deodorant — magnesium, no aluminum, no baking-soda burn",
    story: "A US tallow kitchen that pours aluminum-free deodorant with magnesium hydroxide instead of a drugstore antiperspirant, then keeps the rest of the formula to grass-fed fat, arrowroot, coconut oil, and beeswax. Deodorant scent variants stay as their own listings. Soap, balm, and lip balm stay. Shipping protection stays out.",
    location: "United States",
    founded: 2023,
    categories: ["deodorant","skincare"],
    accent: "#C4A35A",
    rating: 4.7,
    reviewCount: 140,
    followerCount: 2200,
    websiteUrl: "https://www.royaltallow.com",
    logoUrl: "/brands/royal-tallow.svg",
  },
  {
    id: "c938",
    slug: "cowlo",
    name: "COWLO",
    tagline: "Small-batch tallow deodorant and soap — baking-soda free, no synthetic fragrance dump",
    story: "A handmade US tallow house that scents deodorant with vanilla mint, lavender, and cedarwood instead of a perfume-oil stick. Deodorant and soap scent variants stay as their own listings. Lip balms and whipped tallow stay. Bug balm stays in the barn.",
    location: "United States",
    founded: 2022,
    categories: ["deodorant","skincare"],
    accent: "#8B5A2B",
    rating: 4.8,
    reviewCount: 180,
    followerCount: 3100,
    websiteUrl: "https://www.cowlotallow.com",
    logoUrl: "/brands/cowlo.svg",
  },
  {
    id: "c939",
    slug: "magic-moo-tallow",
    name: "Magic Moo Tallow",
    tagline: "Organic suet tallow sun stick and deodorant — non-nano zinc, no chemical-filter cocktail",
    story: "A small kitchen that renders organic grass-fed suet, then folds non-nano zinc into a sun protectant and pours an aluminum-free deodorant. The tallow sun protectant stays. Deodorant scent variants stay as their own listings. Everyday balms stay. Makeup illuminators stay out.",
    location: "United States",
    founded: 2021,
    categories: ["sunscreen","deodorant","skincare"],
    accent: "#6B3E26",
    rating: 4.8,
    reviewCount: 260,
    followerCount: 4800,
    websiteUrl: "https://magicmootallow.com",
    logoUrl: "/brands/magic-moo-tallow.svg",
  },
  {
    id: "c940",
    slug: "silva-cosmetics",
    name: "Silva Cosmetics",
    tagline: "UK tallow skincare — aluminum-free deodorant, whipped tallow, no 40-ingredient cream",
    story: "A British house that still writes short tallow formulas for eczema-prone underarms and dry skin. The unisex deodorant stays. Lumi whipped tallow, Sano repair cream, and lip balm stay. Gift-set packaging stays when it is the same formulas.",
    location: "United Kingdom",
    founded: 2020,
    categories: ["deodorant","skincare"],
    accent: "#B76E79",
    rating: 4.7,
    reviewCount: 320,
    followerCount: 5400,
    websiteUrl: "https://www.silvacosmetics.com",
    logoUrl: "/brands/silva-cosmetics.svg",
  },
  {
    id: "c941",
    slug: "cohld",
    name: "Cohld",
    tagline: "Grass-fed collagen, tallow balm, and creatine hydration — no maltodextrin filler aisle",
    story: "A clean-fuel kitchen that sources grass-fed collagen and tallow, then mixes creatine into a hydration powder instead of a candy-aisle tub. Collagen, magnesium, maca, and the tallow balm stay. Charcoal soap stays. Stacks stay when they are the same formulas.",
    location: "United States",
    founded: 2024,
    categories: ["supplements","skincare","electrolytes"],
    accent: "#3D5A3D",
    rating: 4.7,
    reviewCount: 90,
    followerCount: 1600,
    websiteUrl: "https://www.cohld.com",
    logoUrl: "/brands/cohld.svg",
  },
  {
    id: "c942",
    slug: "hearth-and-homestead",
    name: "Hearth & Homestead",
    tagline: "Virginia ancestral tallow — magnesium deodorant, after-sun balm, no petroleum cream",
    story: "A family shop in Virginia that handcrafts grass-fed tallow balms, then pours a magnesium deodorant and an after-sun balm instead of a drugstore lotion. Deodorant and soap scent variants stay as their own listings. Hair oils and clarifying care stay. Gift-set merch stays when it is the same formulas.",
    location: "Virginia, United States",
    founded: 2019,
    categories: ["deodorant","skincare","hair"],
    accent: "#5B7A3A",
    rating: 4.8,
    reviewCount: 890,
    followerCount: 12000,
    websiteUrl: "https://www.hearthandhomesteadstore.com",
    logoUrl: "/brands/hearth-and-homestead.svg",
  },
  {
    id: "c943",
    slug: "tagg-organics",
    name: "Tagg Organics",
    tagline: "Organic grass-fed tallow deodorant and face cream — short lists, no fragrance-oil dump",
    story: "A tiny organic tallow house that keeps deodorant aluminum-free and writes face cream from grass-fed fat instead of a 30-ingredient moisturizer. Deodorant stays. Lip balm scent variants stay as their own listings. Breath balm and face cream stay.",
    location: "United States",
    founded: 2022,
    categories: ["deodorant","skincare"],
    accent: "#4A5D23",
    rating: 4.7,
    reviewCount: 70,
    followerCount: 900,
    websiteUrl: "https://www.taggorganics.com",
    logoUrl: "/brands/tagg-organics.svg",
  },
  {
    id: "c944",
    slug: "the-tallow-shop",
    name: "The Tallow Shop",
    tagline: "Handmade tallow deodorant and soap — calendula balm, no aluminum stick",
    story: "A small tallow shop — a different house from The Tallow Co. — that pours deodorant, facial soap, and a calendula-chamomile balm by hand. Deodorant stays. Soaps and whipped balm stay. Room sprays and wooden soap dishes stay in the merch drawer.",
    location: "United States",
    founded: 2021,
    categories: ["deodorant","skincare"],
    accent: "#6B8F71",
    rating: 4.6,
    reviewCount: 110,
    followerCount: 1400,
    websiteUrl: "https://www.thetallowshop.com",
    logoUrl: "/brands/the-tallow-shop.svg",
  },
  {
    id: "c945",
    slug: "flurrie-wellness",
    name: "Flurrie Wellness",
    tagline: "Real-fruit electrolyte powder — lion's mane, green-tea caffeine, no neon sport dye",
    story: "A tiny hydration house that flavors electrolyte powder with real fruit instead of a candy-aisle stick pack, then folds in lion's mane, L-theanine, and B vitamins. Strawberry lemon stays. No merch aisle.",
    location: "United States",
    founded: 2024,
    categories: ["electrolytes"],
    accent: "#E07A5F",
    rating: 4.6,
    reviewCount: 40,
    followerCount: 700,
    websiteUrl: "https://flurriewellness.com",
    logoUrl: "/brands/flurrie-wellness.svg",
  },
  {
    id: "c946",
    slug: "nur-protein",
    name: "NUR Protein",
    tagline: "Clear protein + electrolytes — precision-fermented BLG, no milky chalk shake",
    story: "A new protein kitchen that mixes precision-fermented BLG with sodium, potassium, and magnesium so the drink stays clear instead of a milky tub. Hydration Hero and stick mixes stay. Flavor variants stay as their own listings. Discovery packs stay when they are the same formulas.",
    location: "United States",
    founded: 2025,
    categories: ["protein","electrolytes"],
    accent: "#1B4F72",
    rating: 4.7,
    reviewCount: 55,
    followerCount: 1100,
    websiteUrl: "https://nurprotein.com",
    logoUrl: "/brands/nur-protein.svg",
  },
  {
    id: "c947",
    slug: "good-livin",
    name: "Good Livin.",
    tagline: "Brain electrolytes with lion's mane and creatine — freeze-dried fruit, no fake-juice dye",
    story: "A Canadian-minded kitchen that built Salty Einstein around lion's mane, creatine, and magnesium L-threonate instead of a neon sport stick. Salty Goddess, Salty Turbo, and Electric Energy stay. Mushroom boosters stay. Sauna hats, shades, and wholesale cartons stay out.",
    location: "Independent / DTC",
    founded: 2023,
    categories: ["electrolytes","supplements"],
    accent: "#2C5F4E",
    rating: 4.7,
    reviewCount: 210,
    followerCount: 3600,
    websiteUrl: "https://www.itsgoodlivin.com",
    logoUrl: "/brands/good-livin.svg",
  },
  {
    id: "c948",
    slug: "myfeelium",
    name: "MYFEELIUM",
    tagline: "Functional drink mixes — kava electrolytes, cacao, no candy-aisle tub",
    story: "A small functional kitchen that mixes Lazy Lightning with magnesium, amino acids, and lion's mane instead of a sugar stick. Focus, Calm, Energy, cacao, and coconut blends stay. Hats, tees, and hoodies stay in the merch drawer.",
    location: "Independent / DTC",
    founded: 2022,
    categories: ["electrolytes","supplements"],
    accent: "#5E4B45",
    rating: 4.6,
    reviewCount: 80,
    followerCount: 1500,
    websiteUrl: "https://myfeelium.co",
    logoUrl: "/brands/myfeelium.svg",
  },
  {
    id: "c949",
    slug: "koyah",
    name: "KOYAH",
    tagline: "Organic freeze-dried fruit and mushroom powders — single-ingredient capsules, no filler blend",
    story: "A US freeze-dry house that mills organic berries, greens, and lion's mane into powders and capsules instead of a 40-ingredient gummy. Lion's mane, greens, and berry capsules stay. Empty capsule bags stay out.",
    location: "United States",
    founded: 2016,
    categories: ["supplements"],
    accent: "#4A5D23",
    rating: 4.8,
    reviewCount: 640,
    followerCount: 8900,
    websiteUrl: "https://www.koyah.com",
    logoUrl: "/brands/koyah.svg",
  },
  {
    id: "c950",
    slug: "mushroom-maiden-farm",
    name: "Mushroom Maiden Farm",
    tagline: "Farm lion's mane capsules and coffee — fruiting-body powders, no grain-filler mycelium aisle",
    story: "A working mushroom farm that mills lion's mane and reishi for capsules, powders, and a mushroom coffee instead of a mycelium-on-oats tub. Capsules, powders, and coffee stay. Dried culinary boxes and finishing salts stay on the farm stand.",
    location: "United States",
    founded: 2020,
    categories: ["supplements"],
    accent: "#3D5A3D",
    rating: 4.7,
    reviewCount: 95,
    followerCount: 1300,
    websiteUrl: "https://www.mushroommaidenfarm.com",
    logoUrl: "/brands/mushroom-maiden-farm.svg",
  },
  {
    id: "c951",
    slug: "fungi-family-farm",
    name: "Fungi Family Farm",
    tagline: "Maui mushroom extracts — tremella tallow SPF, lion's mane tinctures, no filler creamer aisle",
    story: "A Maui farm that dual-extracts lion's mane, tremella, and a 14-mushroom blend, then folds tremella into a tallow SPF 30 balm. Tinctures, capsules, serums, and the sun balm stay. Dog toppers stay in the kennel.",
    location: "Maui, Hawaii",
    founded: 2019,
    categories: ["supplements","skincare","sunscreen"],
    accent: "#2A9D8F",
    rating: 4.8,
    reviewCount: 170,
    followerCount: 2800,
    websiteUrl: "https://fungifamilyfarm.com",
    logoUrl: "/brands/fungi-family-farm.svg",
  },
  {
    id: "c952",
    slug: "mill-slough-apothecary",
    name: "Mill Slough Apothecary",
    tagline: "Iowa homestead tallow and elderberry — small-batch face cream, no petroleum lotion",
    story: "An Adel, Iowa homestead that grows elderberry and forages mushrooms, then whips tallow face cream and elderberry gummies by hand. Tallow lotions, lip balm, tinctures, and gummies stay. Tea blends, bug balm, and dried culinary mushrooms stay in the pantry.",
    location: "Adel, Iowa",
    founded: 2021,
    categories: ["skincare","supplements"],
    accent: "#6B8F71",
    rating: 4.8,
    reviewCount: 60,
    followerCount: 800,
    websiteUrl: "https://mill-slough-apothecary.myshopify.com",
    logoUrl: "/brands/mill-slough-apothecary.svg",
  },
  {
    id: "c953",
    slug: "fitppl",
    name: "Fitppl",
    tagline: "Organic plant protein and greens — no stevia dump, no gum-thickened shake",
    story: "A small clean-nutrition house that keeps plant protein and a greens-and-reds powder free of stevia, gums, and filler blends. Optimal and Performance plant proteins stay. Daily greens stay. No merch aisle.",
    location: "Independent / DTC",
    founded: 2023,
    categories: ["protein","supplements"],
    accent: "#3D8B6E",
    rating: 4.6,
    reviewCount: 50,
    followerCount: 900,
    websiteUrl: "https://www.fitppl.com",
    logoUrl: "/brands/fitppl.svg",
  },
  {
    id: "c954",
    slug: "etee",
    name: "etee",
    tagline: "Refillable clean body care — prebiotic deodorant, mineral sunscreen, no plastic-pump guilt",
    story: "A zero-waste house that still makes a prebiotic deodorant, mineral sunscreen, and lavender shampoo in refillable jars instead of a supermarket plastic pump. Deodorant, sunscreen, shampoo, conditioner, and face care stay. Dish soap, scrubbers, and empty-kit housewares stay in the cleaning closet.",
    location: "Canada / United States",
    founded: 2017,
    categories: ["deodorant","sunscreen","hair","skincare"],
    accent: "#2C5F4E",
    rating: 4.6,
    reviewCount: 1200,
    followerCount: 18000,
    websiteUrl: "https://www.etee.com",
    logoUrl: "/brands/etee.svg",
  },
  {
    id: "c955",
    slug: "bounce-curl",
    name: "Bounce Curl",
    tagline: "Curl care with ceramide jelly and weightless shampoo — no silicone slip, no brush-only aisle",
    story: "A curl house that still mixes a pure-silk moisturizing shampoo, hydra-drench conditioner, and ceramide jelly without a dimethicone serum. Shampoo, conditioner, masks, leave-ins, and styling creams stay. Brushes, bonnets, and hair-tea merch stay in the tool drawer.",
    location: "United States",
    founded: 2016,
    categories: ["hair"],
    accent: "#7B3F6E",
    rating: 4.7,
    reviewCount: 2100,
    followerCount: 45000,
    websiteUrl: "https://www.bouncecurl.com",
    logoUrl: "/brands/bounce-curl.svg",
  },
];
