import type { Brand } from "./types";

/** Deodorant wave: organic / natural deodorant brands (c226–c250). */
export const catalogBrandsDeo: Brand[] = [
  {
    id: "c226",
    slug: "hume-supernatural",
    name: "Hume Supernatural",
    tagline: "Magnesium-powered all-body natural deodorant",
    story: "Aluminum-free deodorant that goes beyond pits — magnesium formulas for whole-body freshness without the synthetic fog.",
    location: "United States",
    founded: 2019,
    categories: ["deodorant"],
    accent: "#2C5F4E",
    rating: 4.6,
    reviewCount: 4200,
    followerCount: 28000,
    websiteUrl: "https://humesupernatural.com",
    logoUrl: "/brands/hume-supernatural.png",
  },
  {
    id: "c227",
    slug: "nelson-naturals",
    name: "Nelson Naturals",
    tagline: "Aluminum-free deodorant from Canadian clean-care makers",
    story: "Small-batch natural deodorant sticks built for people rewriting their underarm routine — simple ingredients, serious freshness.",
    location: "Canada",
    founded: 2012,
    categories: ["deodorant"],
    accent: "#1B4F72",
    rating: 4.5,
    reviewCount: 890,
    followerCount: 6200,
    websiteUrl: "https://nelsonnaturals.com",
    logoUrl: "/brands/nelson-naturals.png",
  },
  {
    id: "c228",
    slug: "earth-conscious",
    name: "Earth Conscious",
    tagline: "Plastic-free natural deodorant cream",
    story: "Bicarb-smart natural deodorant tins and sticks from the UK — plastic-free packaging with plant-powered odor control.",
    location: "United Kingdom",
    founded: 2016,
    categories: ["deodorant"],
    accent: "#3D6B4F",
    rating: 4.7,
    reviewCount: 3100,
    followerCount: 15000,
    websiteUrl: "https://earthconscious.co.uk",
    logoUrl: "/brands/earth-conscious.png",
  },
  {
    id: "c229",
    slug: "fussy",
    name: "Fussy",
    tagline: "Refillable natural deodorant with compostable refills",
    story: "Compostable deodorant refills in reusable cases — fragrance-first natural protection without single-use plastic sticks.",
    location: "United Kingdom",
    founded: 2018,
    categories: ["deodorant"],
    accent: "#C45C26",
    rating: 4.6,
    reviewCount: 8500,
    followerCount: 42000,
    websiteUrl: "https://www.fussy.com",
    logoUrl: "/brands/fussy.png",
  },
  {
    id: "c230",
    slug: "coconut-matter",
    name: "Coconut Matter",
    tagline: "Vegan coconut-oil natural deodorant",
    story: "MOOD deodorant made with coconut oil and essential oils — vegan, plastic-conscious, and built for everyday freshness.",
    location: "United Kingdom",
    founded: 2015,
    categories: ["deodorant"],
    accent: "#6B3E26",
    rating: 4.5,
    reviewCount: 1200,
    followerCount: 9800,
    websiteUrl: "https://coconutmatter.com",
    logoUrl: "/brands/coconut-matter.png",
  },
  {
    id: "c231",
    slug: "erbaviva",
    name: "Erbaviva",
    tagline: "Certified organic plant-based deodorant",
    story: "USDA organic deodorant sticks with botanical oils — clean underarm care from a pioneer of plant-based body rituals.",
    location: "United States",
    founded: 1996,
    categories: ["deodorant"],
    accent: "#5B7A3A",
    rating: 4.6,
    reviewCount: 2100,
    followerCount: 18000,
    websiteUrl: "https://erbaviva.com",
    logoUrl: "/brands/erbaviva.png",
  },
  {
    id: "c232",
    slug: "penny-lane-organics",
    name: "Penny Lane Organics",
    tagline: "Organic natural deodorant creams and sprays",
    story: "Canadian organic deodorant creams without aluminum — handcrafted scents for sensitive underarms and clean-beauty loyalists.",
    location: "Canada",
    founded: 2009,
    categories: ["deodorant"],
    accent: "#8E4A6B",
    rating: 4.7,
    reviewCount: 1600,
    followerCount: 11000,
    websiteUrl: "https://pennylaneorganics.com",
    logoUrl: "/brands/penny-lane-organics.png",
  },
  {
    id: "c233",
    slug: "pretty-frank",
    name: "Pretty Frank",
    tagline: "Aluminum-free deodorant for sensitive skin",
    story: "Baking-soda-optional natural deodorant sticks and pastes — gentle formulas for people who quit conventional sticks for good.",
    location: "United States",
    founded: 2014,
    categories: ["deodorant"],
    accent: "#B85C38",
    rating: 4.8,
    reviewCount: 5400,
    followerCount: 22000,
    websiteUrl: "https://prettyfrank.com",
    logoUrl: "/brands/pretty-frank.png",
  },
  {
    id: "c234",
    slug: "routine",
    name: "Routine",
    tagline: "Natural deodorant cream with cult scents",
    story: "Iconic cream deodorant jars from Calgary — baking-soda-free options, wild scent library, and aluminum-free everyday wear.",
    location: "Canada",
    founded: 2014,
    categories: ["deodorant"],
    accent: "#2E4057",
    rating: 4.8,
    reviewCount: 12000,
    followerCount: 55000,
    websiteUrl: "https://routinecream.com",
    logoUrl: "/brands/routine.png",
  },
  {
    id: "c235",
    slug: "akt-london",
    name: "AKT London",
    tagline: "Natural deodorant balm for modern life",
    story: "Balm-to-powder deodorant in scent chapters — natural odor control designed like a fragrance wardrobe, not a pharmacy stick.",
    location: "United Kingdom",
    founded: 2018,
    categories: ["deodorant"],
    accent: "#1A1A1A",
    rating: 4.7,
    reviewCount: 3800,
    followerCount: 31000,
    websiteUrl: "https://aktlondon.com",
    logoUrl: "/brands/akt-london.png",
  },
  {
    id: "c236",
    slug: "no-tox-life",
    name: "No Tox Life",
    tagline: "Zero-waste natural deodorant and underarm detox",
    story: "Plastic-free deodorant detox bars and creams — zero-waste underarm care for the low-tox lifestyle.",
    location: "United States",
    founded: 2014,
    categories: ["deodorant"],
    accent: "#4A6741",
    rating: 4.6,
    reviewCount: 2900,
    followerCount: 19000,
    websiteUrl: "https://notoxlife.com",
    logoUrl: "/brands/no-tox-life.png",
  },
  {
    id: "c237",
    slug: "herban-cowboy",
    name: "Herban Cowboy",
    tagline: "Plant-based deodorant for every cowboy",
    story: "Vegan stick and spray deodorant with bold forest and dusk scents — plant-powered freshness without aluminum.",
    location: "United States",
    founded: 2008,
    categories: ["deodorant"],
    accent: "#3E2723",
    rating: 4.5,
    reviewCount: 4700,
    followerCount: 14000,
    websiteUrl: "https://herbancowboy.com",
    logoUrl: "/brands/herban-cowboy.png",
  },
  {
    id: "c238",
    slug: "lavera",
    name: "Lavera",
    tagline: "Certified natural and organic deodorant",
    story: "German naturopathic deodorant sticks — certified natural cosmetics with botanical actives and aluminum-free formulas.",
    location: "Germany",
    founded: 1987,
    categories: ["deodorant"],
    accent: "#6B8E23",
    rating: 4.6,
    reviewCount: 6200,
    followerCount: 48000,
    websiteUrl: "https://www.lavera.com",
    logoUrl: "/brands/lavera.png",
  },
  {
    id: "c239",
    slug: "dr-squatch",
    name: "Dr. Squatch",
    tagline: "Natural deodorant for guys who want to smell great",
    story: "Nature-inspired deodorant sticks and invisible glides — aluminum-free scent stories from the woods to the coast.",
    location: "United States",
    founded: 2015,
    categories: ["deodorant"],
    accent: "#1B4332",
    rating: 4.5,
    reviewCount: 28000,
    followerCount: 120000,
    websiteUrl: "https://www.drsquatch.com",
    logoUrl: "/brands/dr-squatch.png",
  },
  {
    id: "c240",
    slug: "duke-cannon",
    name: "Duke Cannon",
    tagline: "Hardworking aluminum-free and antiperspirant deodorant",
    story: "Air Defense and Trench Warfare deodorant for long days — straightforward men's odor control without the boutique fluff.",
    location: "United States",
    founded: 2012,
    categories: ["deodorant"],
    accent: "#4A3728",
    rating: 4.6,
    reviewCount: 9100,
    followerCount: 67000,
    websiteUrl: "https://www.dukecannon.com",
    logoUrl: "/brands/duke-cannon.png",
  },
  {
    id: "c241",
    slug: "brickell",
    name: "Brickell Men's Products",
    tagline: "Natural deodorant formulated for men",
    story: "Clean men's deodorant with natural essential oils — simple underarm care from a natural grooming brand.",
    location: "United States",
    founded: 2011,
    categories: ["deodorant"],
    accent: "#1C2833",
    rating: 4.5,
    reviewCount: 3500,
    followerCount: 25000,
    websiteUrl: "https://www.brickellmensproducts.com",
    logoUrl: "/brands/brickell.png",
  },
  {
    id: "c242",
    slug: "green-beaver",
    name: "The Green Beaver Company",
    tagline: "Canadian natural deodorant and antiperspirant",
    story: "Aluminum-conscious deodorant and plant-based antiperspirant from Canada — family-made clean body care.",
    location: "Canada",
    founded: 2002,
    categories: ["deodorant"],
    accent: "#2E7D32",
    rating: 4.6,
    reviewCount: 2800,
    followerCount: 16000,
    websiteUrl: "https://greenbeaver.com",
    logoUrl: "/brands/green-beaver.png",
  },
  {
    id: "c243",
    slug: "eo-products",
    name: "EO Products",
    tagline: "Essential-oil natural deodorant sprays",
    story: "Organic essential-oil deodorant sprays from California — plant aromatics for clean, everyday underarm freshness.",
    location: "United States",
    founded: 1995,
    categories: ["deodorant"],
    accent: "#00796B",
    rating: 4.5,
    reviewCount: 4100,
    followerCount: 33000,
    websiteUrl: "https://www.eoproducts.com",
    logoUrl: "/brands/eo-products.png",
  },
  {
    id: "c244",
    slug: "megababe",
    name: "Megababe",
    tagline: "Body-positive natural deodorant",
    story: "Playful natural deodorants for real bodies — aluminum-free formulas with a body-care ethos beyond perfection.",
    location: "United States",
    founded: 2017,
    categories: ["deodorant"],
    accent: "#D81B60",
    rating: 4.6,
    reviewCount: 7200,
    followerCount: 89000,
    websiteUrl: "https://megababebeauty.com",
    logoUrl: "/brands/megababe.png",
  },
  {
    id: "c245",
    slug: "neals-yard",
    name: "Neal's Yard Remedies",
    tagline: "Organic herbal deodorant from British herbalists",
    story: "Certified organic roll-on and spray deodorant — herbalist formulas rooted in natural remedies since Covent Garden.",
    location: "United Kingdom",
    founded: 1981,
    categories: ["deodorant"],
    accent: "#33691E",
    rating: 4.7,
    reviewCount: 1500,
    followerCount: 41000,
    websiteUrl: "https://www.nealsyardremedies.com",
    logoUrl: "/brands/neals-yard.png",
  },
  {
    id: "c246",
    slug: "simple-alchemy",
    name: "Simple Alchemy",
    tagline: "Small-batch natural deodorant made simply",
    story: "Handcrafted aluminum-free deodorant with short ingredient lists — small-batch scent stories without the chemical choir.",
    location: "United States",
    founded: 2018,
    categories: ["deodorant"],
    accent: "#5D4037",
    rating: 4.8,
    reviewCount: 420,
    followerCount: 3100,
    websiteUrl: "https://simplealchemyco.com",
    logoUrl: "/brands/simple-alchemy.png",
  },
  {
    id: "c247",
    slug: "toms-of-maine",
    name: "Tom's of Maine",
    tagline: "Aluminum-free natural deodorant classics",
    story: "Stewardship-minded natural deodorant and antiperspirant — plant and mineral ingredients for everyday clean care.",
    location: "United States",
    founded: 1970,
    categories: ["deodorant"],
    accent: "#1565C0",
    rating: 4.4,
    reviewCount: 18000,
    followerCount: 95000,
    websiteUrl: "https://www.tomsofmaine.com",
    logoUrl: "/brands/toms-of-maine.png",
  },
  {
    id: "c248",
    slug: "raw-sugar",
    name: "Raw Sugar",
    tagline: "Naturally derived deodorant with bold scents",
    story: "Aluminum-free deodorant sticks with sensorial scent pairings — naturally derived formulas for a fresh daily reset.",
    location: "United States",
    founded: 2014,
    categories: ["deodorant"],
    accent: "#E65100",
    rating: 4.5,
    reviewCount: 2300,
    followerCount: 27000,
    websiteUrl: "https://rawsugarliving.com",
    logoUrl: "/brands/raw-sugar.png",
  },
  {
    id: "c249",
    slug: "bulldog",
    name: "Bulldog Skincare",
    tagline: "Natural men's spray deodorant",
    story: "Accessible natural deodorant sprays for men — essential-oil freshness without the overcomplicated grooming kit.",
    location: "United Kingdom",
    founded: 2007,
    categories: ["deodorant"],
    accent: "#212121",
    rating: 4.5,
    reviewCount: 5600,
    followerCount: 52000,
    websiteUrl: "https://www.bulldogskincare.com",
    logoUrl: "/brands/bulldog.png",
  },
  {
    id: "c250",
    slug: "bare-anatomy",
    name: "Bare Anatomy",
    tagline: "Science-led underarm odor and care",
    story: "Targeted underarm roll-ons and mists for odor control and pigmentation — derm-minded formulas for the underarm zone.",
    location: "India",
    founded: 2019,
    categories: ["deodorant"],
    accent: "#6A1B9A",
    rating: 4.4,
    reviewCount: 8900,
    followerCount: 61000,
    websiteUrl: "https://bareanatomy.com",
    logoUrl: "/brands/bare-anatomy.png",
  },
];
