import type { Brand } from "./types";

/** Wave 95: small organic / toxic-free brands across marketplace categories (c1439+). */
export const catalogBrandsWave95: Brand[] = [
  {
    id: "c1439",
    slug: "lumineux",
    name: "Lumineux",
    tagline: "Beverly Hills 10% nano-hydroxyapatite toothpaste, kids paste, and clean mouthwash",
    story:
      "The leftover unused multi-SKU n-HA oral house after wave4–94 — Dr. Kourosh Maddahi’s clean whitening line. Keep the 10% n-HA toothpaste, Unicorn kids paste, Clean & Fresh mouthwash, and Bright² whitening pen. 2-packs, 21/35-treatment strip packs, kits, duos, starter packs, and electric heads stay boxed. Cart.js is USD. Hardcode the published n-HA INCI — other pages are whitening essays (leave empty).",
    location: "Beverly Hills, CA",
    founded: 2014,
    categories: ["oral"],
    accent: "#4A7A8C",
    rating: 4.6,
    reviewCount: 4800,
    followerCount: 36000,
    websiteUrl: "https://www.lumineuxhealth.com",
    logoUrl: "/brands/lumineux.svg",
  },
  {
    id: "c1440",
    slug: "cota-hydration",
    name: "Cota Hydration",
    tagline: "Iowa monk-fruit + stevia electrolytes — no sucralose, sweat-ratio sodium, potassium, magnesium",
    story:
      "Three West Des Moines friends (Quinn, Jack, and Roan) mixing a zero-sugar drink that matches sweat minerals and skips sucralose. Flavor expands Lemonade / Strawberry / Peach. Water bottles and starter packs stay boxed. Cart.js is USD. Hardcode the published mineral + monk-fruit list.",
    location: "West Des Moines, IA",
    founded: 2025,
    categories: ["electrolytes"],
    accent: "#2A6F7A",
    rating: 4.6,
    reviewCount: 86,
    followerCount: 1400,
    websiteUrl: "https://cotahydration.com",
    logoUrl: "/brands/cota-hydration.svg",
  },
  {
    id: "c1441",
    slug: "simplyfuel",
    name: "simplyFUEL",
    tagline: "Two-ingredient grass-fed whey isolate — sunflower lecithin, no sucralose or stevia",
    story:
      "Leawood sports-dietitian Mitzi Dulan’s unused clean whey leftover after wave4–94 — keep the unflavored unsweetened grass-fed isolate. Protein balls, cookie-dough snacks, and variety packs stay boxed. Cart.js is USD. Hardcode the published two-ingredient list.",
    location: "Leawood, KS",
    founded: 2015,
    categories: ["protein"],
    accent: "#C45A2A",
    rating: 4.6,
    reviewCount: 420,
    followerCount: 8900,
    websiteUrl: "https://simplyfuel.com",
    logoUrl: "/brands/simplyfuel.svg",
  },
  {
    id: "c1442",
    slug: "sunkissed-by-heaven",
    name: "Sunkissed by Heaven",
    tagline: "Small-batch tallow mineral SPF 50 and whipped tallow moisturizer",
    story:
      "The leftover unused tallow sun house after wave4–94 — keep Tallow Sunscreen SPF 50 and one Tallow Moisturizer. Duplicate moisturizer handles stay one listing. Cart.js is USD. Pages are farm-story marketing (leave empty).",
    location: "United States",
    founded: 2023,
    categories: ["sunscreen", "skincare"],
    accent: "#C48A4A",
    rating: 4.7,
    reviewCount: 48,
    followerCount: 620,
    websiteUrl: "https://sunkissedbyheaven.com",
    logoUrl: "/brands/sunkissed-by-heaven.svg",
  },
  {
    id: "c1443",
    slug: "taddos-tallow",
    name: "Taddo's Tallow",
    tagline: "Arroyo Grande grass-fed tallow deodorant, whipped cream, lotion stick, and lip balm",
    story:
      "Tami Taddo’s Central Coast leftover after wave4–94 — Scent expands deodorant / whipped tallow / lotion stick (Unscented, Lavender, Sweet Orange, Sandalwood); Flavor expands lip (Unflavored, Vanilla, Strawberry, Watermelon). 4 oz / 2.65 oz is size. Collections, gift cards, konjac, and soap savers stay boxed. Cart.js is USD. Pages are eczema-story marketing (leave empty).",
    location: "Arroyo Grande, CA",
    founded: 2021,
    categories: ["deodorant", "skincare"],
    accent: "#8B5A3A",
    rating: 4.8,
    reviewCount: 310,
    followerCount: 5200,
    websiteUrl: "https://taddostallow.com",
    logoUrl: "/brands/taddos-tallow.svg",
  },
  {
    id: "c1444",
    slug: "mahealani-farms",
    name: "Māhealani Farms",
    tagline: "Carpinteria fruiting-body lion's mane, reishi, turkey tail, and cordyceps tinctures plus mushroom skin",
    story:
      "Damien and Terra’s unused Carpinteria farm leftover after wave4–94 — keep fruiting-body tinctures and lion’s mane / snow-mushroom skin and hair oil. Fresh/dried culinary mushrooms, gift boxes, and tincture sets stay boxed. Cart.js is USD. Hardcode published tincture and rescue-balm lists — cream pages are farm-story marketing (leave empty).",
    location: "Carpinteria, CA",
    founded: 2022,
    categories: ["supplements", "skincare", "hair"],
    accent: "#4A6B32",
    rating: 4.8,
    reviewCount: 94,
    followerCount: 1800,
    websiteUrl: "https://mahealanifarms.store",
    logoUrl: "/brands/mahealani-farms.svg",
  }
];
