import type { Brand } from "./types";

/** Wave 62: small organic / toxic-free brands across marketplace categories (c1242+). */
export const catalogBrandsWave62: Brand[] = [
  {
    id: "c1242",
    slug: "eezysun",
    name: "EEZYSUN",
    tagline: "Mineral zinc SPF 50 sticks, tinted BARE shades, and after-sun — no chemical filters",
    story: "A small US mineral house that packs non-nano zinc into convenient SPF 50 tubes, snap packets, and three BARE tinted shades so reapplication is actually easy. Mineral SPF 50, babies & kids, BARE Light / Tan / Deep, the daily convenience tube, and after-sun stay. Insect-repellent hybrids and gift cards stay boxed. Shade is already a separate title, not a size.",
    location: "United States",
    founded: 2021,
    categories: ["sunscreen"],
    accent: "#C45C26",
    rating: 4.6,
    reviewCount: 92,
    followerCount: 2100,
    websiteUrl: "https://eezysun.com",
    logoUrl: "/brands/eezysun.svg",
  },
  {
    id: "c1243",
    slug: "arame",
    name: "ARAME",
    tagline: "5% rod-shaped n-HA toothpaste plus polish — fluoride-free, miswak, hyaluronic acid",
    story: "A small US oral house that publishes 5% rod-shaped nano-hydroxyapatite in THE PASTE, then pairs it with hyaluronic acid and miswak instead of fluoride or SLS. THE PASTE and THE POLISH stay. THE DUO bundle and the bamboo toothbrush stay boxed. There is no flavor-option tree.",
    location: "United States",
    founded: 2023,
    categories: ["oral"],
    accent: "#2B4C3E",
    rating: 4.5,
    reviewCount: 48,
    followerCount: 1400,
    websiteUrl: "https://aramecare.com",
    logoUrl: "/brands/arame.svg",
  },
  {
    id: "c1244",
    slug: "elemental-deodorant",
    name: "Elemental",
    tagline: "Albuquerque refillable glass magnesium deodorant — baking-soda-free, 80% organic",
    story: "Handcrafted in Albuquerque, Elemental pours a magnesium-hydroxide cream into a refillable glass bottle so the plastic stick never comes home. NUR (essential-oil) and Air (fragrance-free) stay, plus the biodegradable refill pouch. Power / gift / refill / starter packs stay boxed. Scents are already separate titles.",
    location: "Albuquerque, NM",
    founded: 2022,
    categories: ["deodorant"],
    accent: "#4A6741",
    rating: 4.7,
    reviewCount: 76,
    followerCount: 1800,
    websiteUrl: "https://elementaldeodorant.com",
    logoUrl: "/brands/elemental-deodorant.svg",
  },
  {
    id: "c1245",
    slug: "superieur",
    name: "Superieur Electrolytes",
    tagline: "Family-made sea-mineral drink mix — acerola, Himalayan salt, plant stevia, zero sugar",
    story: "Seth's family-and-friend shop on the East End mixes Himalayan salt, inland-sea minerals, acerola berry vitamin C, bamboo silica, and real plant stevia — no erythritol, no dyes. Dedicated flavor canisters and stick packets stay. Canister vs packets is size, not a flavor tree. There is no merch aisle.",
    location: "Southampton, NY",
    founded: 2017,
    categories: ["electrolytes"],
    accent: "#1F5C6B",
    rating: 4.6,
    reviewCount: 118,
    followerCount: 2600,
    websiteUrl: "https://superieurelectrolytes.com",
    logoUrl: "/brands/superieur.svg",
  },
  {
    id: "c1246",
    slug: "caprifit",
    name: "CAPRIFIT",
    tagline: "European goat whey isolate — vanilla, dark chocolate, and cookies & cream tubs",
    story: "A small European goat-whey house packing pasture goat isolate into three dedicated flavor tubs for people who want 20g-plus of protein without cow-whey bloat. Vanilla, dark chocolate, and cookies & cream stay. Wafer bars and protein oats stay boxed. EUR prices convert to USD. Flavor lives on the handle because the storefront titles collide.",
    location: "Europe",
    founded: 2022,
    categories: ["protein"],
    accent: "#8A6A2F",
    rating: 4.5,
    reviewCount: 54,
    followerCount: 1100,
    websiteUrl: "https://caprifit.com",
    logoUrl: "/brands/caprifit.svg",
  },
  {
    id: "c1247",
    slug: "white-sparrow",
    name: "White Sparrow",
    tagline: "Idaho farm-store grass-fed tallow balms, lip, soap, and hair oil — short lists",
    story: "White Sparrow Farmacy renders grass-fed, grass-finished tallow by hand at a family general store in Idaho, then whips it with olive oil, honey, and beeswax. Individual balm and lip scents, named seasonal balms, soap scents, men's balms, hair oil, and cold cream stay. Nightgowns, culinary tallow, face tape, 3-packs, and builder trios stay boxed. Soap Style/Scent expands; jar size is not a flavor.",
    location: "Idaho, United States",
    founded: 2020,
    categories: ["skincare","hair"],
    accent: "#6B4A2B",
    rating: 4.8,
    reviewCount: 164,
    followerCount: 3200,
    websiteUrl: "https://whitesparrow.com",
    logoUrl: "/brands/white-sparrow.svg",
  },
  {
    id: "c1248",
    slug: "ancient-suds",
    name: "Ancient Suds",
    tagline: "Three-ingredient grass-fed tallow balm, deodorant, rice-water shampoo bar, and soaps",
    story: "A small tallow house that keeps the list short: grass-fed tallow, coconut oil, and beeswax in the balm, plus a rice-water shampoo bar and aluminum-free tallow deodorant. Individual soaps, balm sizes, deodorant sizes, beard balm, and the shampoo bar stay. Kits, gift sample boxes, and mesh soap pouches stay boxed. 1 oz vs 4 oz is size, not a scent.",
    location: "United States",
    founded: 2021,
    categories: ["skincare","deodorant","hair"],
    accent: "#5B3A1F",
    rating: 4.6,
    reviewCount: 68,
    followerCount: 1500,
    websiteUrl: "https://ancientsuds.com",
    logoUrl: "/brands/ancient-suds.svg",
  },
];
