import type { Brand } from "./types";

/** Wave 70: small organic / toxic-free brands across marketplace categories (c1289+). */
export const catalogBrandsWave70: Brand[] = [
  {
    id: "c1289",
    slug: "fizzy-oral",
    name: "Fizzy Oral",
    tagline: "20× n-HA mouthwash concentrate, floss, and retainer foam without fluoride",
    story: "A small US oral house that concentrates nano-hydroxyapatite and xylitol into a pocket mouthwash, plus coconut/mint floss and a 3-in-1 retainer foam. Mouthwash and foam flavors expand; pack count is size. Shipping protection, bundles, variety packs, and aligner chewies stay boxed.",
    location: "United States",
    founded: 2023,
    categories: ["oral"],
    accent: "#4A8A9A",
    rating: 4.7,
    reviewCount: 86,
    followerCount: 1900,
    websiteUrl: "https://fizzyoral.com",
    logoUrl: "/brands/fizzy-oral.svg",
  },
  {
    id: "c1290",
    slug: "cypher",
    name: "CYPHER",
    tagline: "Sugar-free Canadian 4-in-1 electrolyte mix in Blue Galaxy and Pink Slush",
    story: "A tiny Canadian hydration house with one 30-serving tub: 955 mg of five electrolytes, zero sugar, zero caffeine. Flavour expands Blue Galaxy and Pink Slush. Serving count is size. Cart.js is CAD and converts at 0.73.",
    location: "Canada",
    founded: 2024,
    categories: ["electrolytes"],
    accent: "#2A3A6A",
    rating: 4.6,
    reviewCount: 34,
    followerCount: 700,
    websiteUrl: "https://cyphersupps.com",
    logoUrl: "/brands/cypher.svg",
  },
  {
    id: "c1291",
    slug: "living-love-superfoods",
    name: "LivingLove Superfoods",
    tagline: "Eugene grass-fed whey and plant proteins blended with maca, chlorella, and probiotics",
    story: "A small Oregon kitchen mixing 100% grass-fed whey with hemp, pea, maca, and chlorella — no added sweeteners. Power Athlete, Resilience Whey, Performance Blend, and the vegan tubs already live on separate titles. Serving count is size. Single-scoop samples stay boxed. Maca powder and chlorella tablets stay supplements.",
    location: "Eugene, OR",
    founded: 2016,
    categories: ["protein","supplements"],
    accent: "#3A6A3A",
    rating: 4.8,
    reviewCount: 112,
    followerCount: 2400,
    websiteUrl: "https://livinglovesuperfoods.com",
    logoUrl: "/brands/living-love-superfoods.png",
  },
  {
    id: "c1292",
    slug: "tallow-balm-company",
    name: "Tallow Balm Co",
    tagline: "USDA organic grass-fed tallow mineral sun cream, cloud moisturizer, and original balm",
    story: "A small US tallow kitchen that pours a non-nano zinc Sun Cream plus whipped Cloud Moisturizer and a richer Original Balm. Cloud and Original Scent expand Subtle Vanilla / Unscented; jar ounces and Buy Two/Three are size. Grapple Guard tees, tinted lip, and duos stay boxed. Published sun-cream INCI is tallow / jojoba / beeswax / water / zinc / Geogard / lecithin / vanilla.",
    location: "United States",
    founded: 2024,
    categories: ["sunscreen","skincare"],
    accent: "#8A6A3A",
    rating: 4.8,
    reviewCount: 64,
    followerCount: 1300,
    websiteUrl: "https://www.tallowbalmcompany.com",
    logoUrl: "/brands/tallow-balm-company.svg",
  },
  {
    id: "c1293",
    slug: "sunny-soil",
    name: "SunnySoil",
    tagline: "Melbourne, Florida tallow deodorant, zinc sun balm, and farm-rendered soaps",
    story: "A tiny Florida farm shop rendering Grove Ladder tallow into aluminum-free deodorant (five scents), SunGaze zinc balm, REAL toothpaste and mouthwash, egg-yolk shampoo, and honey balms. Deodorant / soap / balm / shampoo SCENT expands; jar ounces stay size. Tees, totes, gift cards, bug spray, body spray, kits, and 3-pack lips stay boxed.",
    location: "Melbourne, FL",
    founded: 2022,
    categories: ["deodorant","sunscreen","oral","hair","skincare"],
    accent: "#6A7A3A",
    rating: 4.7,
    reviewCount: 98,
    followerCount: 1700,
    websiteUrl: "https://sunnysoil.shop",
    logoUrl: "/brands/sunny-soil.svg",
  },
  {
    id: "c1294",
    slug: "spruce-creek-mushrooms",
    name: "Spruce Creek Mushrooms",
    tagline: "Farm-grown dual-extract lion's mane, reishi, turkey tail, and cordyceps tinctures",
    story: "A small mushroom farm that dual-extracts its own fruiting bodies into lion's mane, reishi, turkey tail, cordyceps, shiitake, and maitake tinctures — plus an alcohol-free glycerin lion's mane. Published formula is species + cane alcohol + water (or glycerin + honey). Grow kits, liquid culture, agar, dried culinary, dog tincture, tees, and bundles stay boxed.",
    location: "United States",
    founded: 2021,
    categories: ["supplements"],
    accent: "#3A5A3A",
    rating: 4.7,
    reviewCount: 52,
    followerCount: 1100,
    websiteUrl: "https://sprucecreekmushrooms.com",
    logoUrl: "/brands/spruce-creek-mushrooms.svg",
  },
];
