import type { Brand } from "./types";

/** Wave 88: small organic / toxic-free brands across marketplace categories (c1397+). */
export const catalogBrandsWave88: Brand[] = [
  {
    id: "c1397",
    slug: "living-well-dr-michelle",
    name: "Living Well with Dr. Michelle",
    tagline: "Utah dentist hydroxyapatite toothpaste, tooth powder, and remineralizing rinse",
    story: "The leftover unused multi-SKU hydroxyapatite oral house after dedicated n-HA shops ran out — dentist-formulated fluoride-free toothpaste, tooth powders, hydroxyapatite mouthwash, remin floss, dry-mouth spray, probiotic deodorant, and a cocoa electrolyte mix. Flavors already live on separate titles (Cool Mint / Fresh Citrus / Mixed Berry / Soothing Mint). Pack count and 1-year supply are size. Bundles, kits, ebooks, masterclasses, yoga mats, glasses, dry brushes, shakers, and gardening tools stay boxed. Cart.js is USD. Pages are science-story marketing (leave empty when there is no comma formula).",
    location: "Payson, UT",
    founded: 2018,
    categories: ["oral","deodorant","electrolytes","supplements"],
    accent: "#3E6B54",
    rating: 4.8,
    reviewCount: 640,
    followerCount: 8900,
    websiteUrl: "https://livingwellwithdrmichelle.com",
    logoUrl: "/brands/living-well-dr-michelle.svg",
  },
  {
    id: "c1398",
    slug: "hydrant",
    name: "Hydrant",
    tagline: "Rapid hydration mix with real fruit, no stevia, and no sucralose",
    story: "The unused electrolyte leftover after wave4–87 — WHO-style hydration sticks with real fruit juice powder, balanced electrolytes, and no stevia or sucralose. Flavor expands Hydrate (Berry Burst / Lemonade / Watermelonade / Fruit Punch / Blood Orange / Lemon Lime plus zero-sugar twins), Energy (Lemon Squeeze / Raspberry Lemonade), and Sleep (Elderberry Chamomile / Cosmic Cherry). Serving count is size. Variety packs, 8-packs, 12-pack caddies, VIP bundles, TikTok dupes, scoops, gift cards, and shipping protection stay boxed. Cart.js is USD. Pages are use-case marketing (leave empty when there is no comma formula).",
    location: "New York, NY",
    founded: 2014,
    categories: ["electrolytes"],
    accent: "#1F6F8B",
    rating: 4.6,
    reviewCount: 4200,
    followerCount: 38000,
    websiteUrl: "https://drinkhydrant.com",
    logoUrl: "/brands/hydrant.svg",
  },
  {
    id: "c1399",
    slug: "centenarius",
    name: "Centenarius Nutrition",
    tagline: "Irish grass-fed whey isolate with one clean ingredient and no fillers",
    story: "The unused protein leftover after wave4–87 — a certified Irish grass-fed whey isolate (27g, sunflower lecithin only) plus marine collagen, creatine, glycine, dual magnesium, and a sleep formula. Flavors already live on the whey title (unflavored). Protocols, GLP-1 bundles, shakers, and shipping protection stay boxed. Cart.js is USD. Published whey formula is certified grass-fed isolate + non-GMO sunflower lecithin.",
    location: "United States",
    founded: 2022,
    categories: ["protein","supplements"],
    accent: "#2C4A3E",
    rating: 4.7,
    reviewCount: 180,
    followerCount: 2100,
    websiteUrl: "https://centenariusnutrition.com",
    logoUrl: "/brands/centenarius.svg",
  },
  {
    id: "c1400",
    slug: "oak-and-sage",
    name: "Oak & Sage",
    tagline: "Small-batch grass-fed tallow cream, hair oil, and plastic-free lip balm",
    story: "The leftover unused tallow skincare house after wave4–87 — Everywhere Cream scents, rose-geranium face cream, magnesium tallow cream, hair oil, beard balm, glow-drop shades, hydrosols, and three lip balms. Scent / Shade expand; 2 oz vs 8 oz / 16 oz is size. Bundles, gift cards, and tanning oil stay boxed. Cart.js is USD. Pages are farm-story marketing (leave empty when there is no comma formula).",
    location: "United States",
    founded: 2023,
    categories: ["skincare","hair"],
    accent: "#6B4E32",
    rating: 4.8,
    reviewCount: 210,
    followerCount: 2600,
    websiteUrl: "https://oaksageskincare.com",
    logoUrl: "/brands/oak-and-sage.svg",
  },
  {
    id: "c1401",
    slug: "tus-tallow",
    name: "Tu's Tallow",
    tagline: "Wyoming tallow mineral sunscreen, magnesium deodorant, and whipped balm",
    story: "The leftover unused tallow sun + deodorant house after wave4–87 — a 20% non-nano zinc mineral sunscreen, two magnesium deodorant scents (Outpost / Fine Company), body-and-face cream scents, soap bars, and lip flavors already on separate titles. 1 oz vs 2 oz is size. Lip 4-packs stay boxed. Cart.js is USD. Hardcode the published zinc / tallow sun list.",
    location: "Wyoming",
    founded: 2023,
    categories: ["sunscreen","deodorant","skincare"],
    accent: "#8A5A32",
    rating: 4.8,
    reviewCount: 94,
    followerCount: 980,
    websiteUrl: "https://tustallow.com",
    logoUrl: "/brands/tus-tallow.svg",
  },
  {
    id: "c1402",
    slug: "mycolove-farm",
    name: "Mycolove Farm",
    tagline: "Colorado farm lion's mane, reishi, cordyceps, and turkey tail extracts",
    story: "The unused leftover mushroom house after wave4–87 — alcohol and alcohol-free tinctures (Lion's Mane / Reishi / Cordyceps / Turkey Tail), Gnar Tar concentrates, and a fermented lion's mane powder grown and extracted on a Colorado farm. oz / mL is size. 4-sets and tees stay boxed. Cart.js is USD. Published tincture formula is fruiting body + alcohol or vegetable glycerine + water.",
    location: "Colorado",
    founded: 2021,
    categories: ["supplements"],
    accent: "#3F5A2C",
    rating: 4.7,
    reviewCount: 86,
    followerCount: 1400,
    websiteUrl: "https://www.mycolove.farm",
    logoUrl: "/brands/mycolove-farm.svg",
  },
];
