import type { Brand } from "./types";

/** Wave 60: small organic / toxic-free brands across marketplace categories (c1229+). */
export const catalogBrandsWave60: Brand[] = [
  {
    id: "c1229",
    slug: "wattz",
    name: "Wattz",
    tagline: "Hawaii-born mineral SPF 30 built for runners — non-nano zinc, no sting",
    story: "A one-SKU performance mineral house from Hawaii, formulated by athletes who wanted reef-minded zinc that stays put through a long run and does not sting the eyes. High-Performance SPF 30 stays. The published actives are 12% zinc oxide plus a short inactive list. There is no merch aisle and no flavor tree — size is not a scent.",
    location: "Hawaii, United States",
    founded: 2020,
    categories: ["sunscreen"],
    accent: "#1F3D2B",
    rating: 4.6,
    reviewCount: 48,
    followerCount: 2200,
    websiteUrl: "https://wattz.inc",
    logoUrl: "/brands/wattz.svg",
  },
  {
    id: "c1230",
    slug: "dentafari",
    name: "Dentafari",
    tagline: "German hydroxyapatite tooth powder in refill pouches — fluoride-free, plastic-light",
    story: "A family-owned German oral house packing functionalized hydroxyapatite into refill pouches instead of plastic tubes. Crisp Mint, Soothing Mint, and Orange-Mandarine stay as their own titles. 50 g versus 100 g is size, not a flavor. Starter kits, family bundles, empty amber jars, and the 4-brush kids pack stay boxed. EUR prices convert to USD.",
    location: "Germany",
    founded: 2022,
    categories: ["oral"],
    accent: "#3D5A4C",
    rating: 4.7,
    reviewCount: 86,
    followerCount: 1800,
    websiteUrl: "https://dentafari.com",
    logoUrl: "/brands/dentafari.svg",
  },
  {
    id: "c1231",
    slug: "something-nice",
    name: "Something Nice",
    tagline: "Orthodontist-founded 10% n-HA toothpaste with BioFuse oil matrix and nano-floss",
    story: "Dr. Ben Winters' small US oral house puts a published 10% nano-hydroxyapatite dose in Zero and Zero Pro, then pairs it with Halo gum and NanoFloss. Individual toothpaste, gum, and floss stay. NanoFloss flavors expand. Tube count is size. Kits, AquaClean gadgets, chargers, nozzles, Lumismart, and 3-packs stay boxed.",
    location: "United States",
    founded: 2023,
    categories: ["oral"],
    accent: "#2B6B5A",
    rating: 4.6,
    reviewCount: 224,
    followerCount: 5600,
    websiteUrl: "https://somethingnicecompany.com",
    logoUrl: "/brands/something-nice.svg",
  },
  {
    id: "c1232",
    slug: "aspen-kay",
    name: "Aspen Kay Naturals",
    tagline: "Colorado kitchen-born cold-process soaps, tallow balms, and plastic-free hair bars",
    story: "A 2012 home-kitchen soap house that still cold-processes organic oils and grass-fed tallow into bars, balms, and shampoo and conditioner bars. Individual soaps, tallow balm scents, glow face oil, unscented moisturizer, and named hair bars stay. Pack size is not a flavor. Brushes, combs, dishes, sisal, aromatherapy, gift cards, and bundle stacks stay boxed.",
    location: "United States",
    founded: 2012,
    categories: ["skincare","hair"],
    accent: "#7A4E2B",
    rating: 4.7,
    reviewCount: 310,
    followerCount: 4200,
    websiteUrl: "https://aspenkaynaturals.com",
    logoUrl: "/brands/aspen-kay.svg",
  },
  {
    id: "c1233",
    slug: "doms-deodorant",
    name: "Dom's Deodorant",
    tagline: "Canadian magnesium deodorant plus Crush & Brush hydroxyapatite tooth tablets",
    story: "A small Canadian shop pouring aluminum-free magnesium deodorant in named scents, then adding Crush & Brush hydroxyapatite tooth tablets, Crush & Swish mouthwash tabs, a copper-free stainless scraper, and a soft brush. Retail deodorant and oral SKUs stay. Scents are already separate titles. Wholesale cases, 1 L bulk, and Raven Roast coffee stay boxed. CAD prices convert to USD.",
    location: "Canada",
    founded: 2018,
    categories: ["deodorant","oral"],
    accent: "#4A6741",
    rating: 4.6,
    reviewCount: 140,
    followerCount: 2600,
    websiteUrl: "https://domsdeodorant.com",
    logoUrl: "/brands/doms-deodorant.svg",
  },
  {
    id: "c1234",
    slug: "lone-star-mushrooms",
    name: "Lone Star Mushrooms",
    tagline: "Texas fruiting-body extracts — lion's mane, reishi, cordyceps, chaga, turkey tail",
    story: "A Texas mushroom house dual-extracting lion's mane, reishi, cordyceps, chaga, and turkey tail, plus Rise and Rest complexes and a lion's mane coffee. Individual extracts stay. Dried culinary mushrooms and every bundle stay boxed. There is no merch aisle on the formula SKUs.",
    location: "Texas, United States",
    founded: 2021,
    categories: ["supplements"],
    accent: "#5B3A1F",
    rating: 4.5,
    reviewCount: 123,
    followerCount: 1900,
    websiteUrl: "https://lonestarmushrooms.com",
    logoUrl: "/brands/lone-star-mushrooms.svg",
  },
];
