import type { Brand } from "./types";

/** Wave 22: small organic / toxic-free brands across marketplace categories (c811+). */
export const catalogBrandsWave22: Brand[] = [
  {
    id: "c811",
    slug: "clean-kind",
    name: "Clean + Kind",
    tagline: "Grass-fed tallow mineral SPF 25–50 with non-nano zinc — reef-safe, short-list, no chemical filters",
    story: "A small tallow house that puts non-nano zinc in a grass-fed fat base instead of a silicone-and-filter cocktail. Face and kids SPFs stay mineral-only; body lotion stays on the same ranch-fat register. No oxybenzone, no avobenzone, no white-cast panic in a 30-ingredient bottle.",
    location: "United States",
    founded: 2023,
    categories: ["sunscreen","skincare"],
    accent: "#5B7A3A",
    rating: 4.8,
    reviewCount: 420,
    followerCount: 8900,
    websiteUrl: "https://shopcleankind.com",
    logoUrl: "/brands/clean-kind.svg",
  },
  {
    id: "c812",
    slug: "soleo-organics",
    name: "Soleo Organics",
    tagline: "Australian-made 100% natural mineral sunscreen — zinc, plant oils, no chemical UV filters",
    story: "Born in Australia for days that actually live outside. Soleo keeps the active as zinc oxide and the rest as plant oils and butters you can read aloud. Everyday, tropical, and travel packs skip oxybenzone, octinoxate, and the usual chemical-filter stack.",
    location: "Australia",
    founded: 2005,
    categories: ["sunscreen"],
    accent: "#C45C26",
    rating: 4.7,
    reviewCount: 1800,
    followerCount: 24000,
    websiteUrl: "https://soleoorganics.com",
    logoUrl: "/brands/soleo-organics.png",
  },
  {
    id: "c813",
    slug: "opportuniteas",
    name: "Opportuniteas",
    tagline: "Grass-fed whey isolate and concentrate plus a short-list vegan chocolate protein — no candy-aisle dyes",
    story: "A small nutrition shop that started with tea and stayed honest when it added protein. Grass-fed whey isolate and concentrate keep the scoop short; the vegan chocolate powder skips the 20-ingredient pea circus. Kidney-cleanse teas stay off this marketplace shelf.",
    location: "United States",
    founded: 2016,
    categories: ["protein"],
    accent: "#6B3E26",
    rating: 4.6,
    reviewCount: 960,
    followerCount: 12000,
    websiteUrl: "https://opportuniteas.com",
    logoUrl: "/brands/opportuniteas.svg",
  },
  {
    id: "c814",
    slug: "wholesome-story",
    name: "Wholesome Story",
    tagline: "Myo- and D-chiro inositol with MTHF folate and vitamin D3 — hormone-support powders without a junk stack",
    story: "A focused supplement house built around inositol ratios people actually look up. Myo- and D-chiro blends add methylfolate and D3 instead of a mystery proprietary blend. Spearmint and shipping-protection SKUs stay off the shelf.",
    location: "United States",
    founded: 2018,
    categories: ["supplements"],
    accent: "#7A4E8C",
    rating: 4.7,
    reviewCount: 3100,
    followerCount: 18000,
    websiteUrl: "https://wholesomestory.com",
    logoUrl: "/brands/wholesome-story.svg",
  },
  {
    id: "c815",
    slug: "nowa",
    name: "NoWa",
    tagline: "Dentist-formulated hydroxyapatite toothpaste tablets in aluminum tins — plastic-free, no SLS circus",
    story: "UK oral care that ships the paste as a tablet so the tube never shows up. Hydroxyapatite does the enamel work; aluminum tins and compostable pouches do the packaging. Bamboo brush heads stay; merch kits get a keep-if-oral filter.",
    location: "United Kingdom",
    founded: 2020,
    categories: ["oral"],
    accent: "#2C5F4E",
    rating: 4.8,
    reviewCount: 2378,
    followerCount: 16000,
    websiteUrl: "https://www.nowasite.com",
    logoUrl: "/brands/nowa.svg",
  },
  {
    id: "c816",
    slug: "antidote-hair",
    name: "ANTIDOTE Hair Care",
    tagline: "Salon-tested, plant-powered scalp care — biotin shield, rice-protein styler, no artificial color or fragrance",
    story: "A small US hair house that starts at the scalp. Gentle cleaners, organic oils, and rice protein replace the sulfate-and-silicone stack. Heat-and-UV shield and moisture conditioner stay on-niche; plastic-neutral shipping is the point, not a slogan on a tote.",
    location: "United States",
    founded: 2019,
    categories: ["hair"],
    accent: "#1B4F72",
    rating: 4.6,
    reviewCount: 540,
    followerCount: 7800,
    websiteUrl: "https://antidotehaircare.com",
    logoUrl: "/brands/antidote-hair.svg",
  },
  {
    id: "c817",
    slug: "faith-in-nature",
    name: "Faith In Nature",
    tagline: "UK botanical shampoo, conditioner, and body wash — 100% natural origin fragrance, vegan, no SLS",
    story: "A long-running British botanical house that still formulates like a small apothecary: aloe, shea, argan, dragon fruit, and essential-oil scent instead of a synthetic perfume dump. Shampoo and conditioner sets (including bulk refill sizes) stay on the hair-and-skin list.",
    location: "United Kingdom",
    founded: 1974,
    categories: ["hair","skincare"],
    accent: "#3D6B4F",
    rating: 4.7,
    reviewCount: 8900,
    followerCount: 42000,
    websiteUrl: "https://www.faithinnature.co.uk",
    logoUrl: "/brands/faith-in-nature.png",
  },
  {
    id: "c818",
    slug: "antipodes",
    name: "Antipodes",
    tagline: "New Zealand certified-natural skincare — vinanza grape, manuka, and short-list serums without the junk drawer",
    story: "Wellington-born clean beauty that puts South Island botanicals in glass. Certified-natural serums, moisturizers, and a haircare discovery set skip parabens, SLS, and petro-fragrance. Tester sachets stay; makeup-only extras get dropped.",
    location: "Wellington, New Zealand",
    founded: 2007,
    categories: ["skincare","hair"],
    accent: "#2E7D32",
    rating: 4.6,
    reviewCount: 4200,
    followerCount: 38000,
    websiteUrl: "https://www.antipodesnature.com",
    logoUrl: "/brands/antipodes.png",
  },
  {
    id: "c819",
    slug: "rivas-ranch",
    name: "Rivas Ranch",
    tagline: "North Carolina ranch-rendered tallow deodorant, balms, and a mineral sun slayer — farm-to-skin, no factory fat",
    story: "They raise the cattle in Tobaccoville, render the suet by hand, and pour deodorant and balms on the same ranch. Lemon basil, lavender rose, and cedar bergamot sticks skip aluminum and baking-soda burn. Sun Slayer keeps the outdoor days mineral.",
    location: "Tobaccoville, North Carolina",
    founded: 2021,
    categories: ["deodorant","skincare","sunscreen"],
    accent: "#6B3E26",
    rating: 4.8,
    reviewCount: 280,
    followerCount: 4100,
    websiteUrl: "https://grassfedtallowproducts.com",
    logoUrl: "/brands/rivas-ranch.svg",
  },
  {
    id: "c820",
    slug: "natural-gas",
    name: "Natural Gas",
    tagline: "USDA organic electrolyte sticks — peach mango, blue raspberry, cherry lime, no dye-and-sugar crash",
    story: "A tiny hydration house that treats electrolytes like food: organic minerals, real flavor, zero added sugar, no synthetic dyes. Stick packs for training days and heat, not a neon sports-drink aisle. Energy cans stay if they are on-niche drink mixes; merch does not.",
    location: "United States",
    founded: 2024,
    categories: ["electrolytes"],
    accent: "#E27D60",
    rating: 4.7,
    reviewCount: 190,
    followerCount: 3200,
    websiteUrl: "https://drinknaturalgas.com",
    logoUrl: "/brands/natural-gas.svg",
  },
  {
    id: "c821",
    slug: "kaylaan",
    name: "Kaylaan",
    tagline: "Plastic-free toothpaste tablets with neem and hydroxyapatite options — refill tins, no SLS foam show",
    story: "Tablet oral care that actually ships as a refill. Fluoride and non-fluoride neem mints, complete kits, and flavor samplers stay; empty packaging merch does not. The point is a bathroom that does not throw a plastic tube every month.",
    location: "United States",
    founded: 2018,
    categories: ["oral"],
    accent: "#2A9D8F",
    rating: 4.6,
    reviewCount: 1400,
    followerCount: 11000,
    websiteUrl: "https://www.kaylaan.com",
    logoUrl: "/brands/kaylaan.svg",
  },
  {
    id: "c822",
    slug: "homestead-tallowworks",
    name: "Homestead TallowWorks",
    tagline: "Small-batch tallow sun crème, moisture mousse, and lip balm — homestead fat, no seed-oil filler stack",
    story: "A homestead tallow kitchen that pours sun crème and whipped moisture instead of a 40-ingredient lotion. Lip balm and samplers stay on the skin list. No synthetic fragrance dump, no empty-jar merch.",
    location: "United States",
    founded: 2022,
    categories: ["skincare","sunscreen"],
    accent: "#B85C38",
    rating: 4.8,
    reviewCount: 160,
    followerCount: 2400,
    websiteUrl: "https://homesteadtallowworks.com",
    logoUrl: "/brands/homestead-tallowworks.svg",
  },
  {
    id: "c823",
    slug: "tallow-springs",
    name: "Tallow Springs",
    tagline: "Lilac tallow whip, body oil, salt face scrub, and pure soap — spring-water simple, no paraben stack",
    story: "A small tallow shop named like a creek: lilac whip, body oil, salt scrub, and a plain soap bar. Formulas stay short and farm-fat first. Household extras and empty packaging stay off the marketplace.",
    location: "United States",
    founded: 2022,
    categories: ["skincare"],
    accent: "#5B7A3A",
    rating: 4.7,
    reviewCount: 210,
    followerCount: 3100,
    websiteUrl: "https://tallowsprings.com",
    logoUrl: "/brands/tallow-springs.svg",
  },
  {
    id: "c824",
    slug: "willow-moon-farm",
    name: "Willow Moon Farm",
    tagline: "Farm-made lavender and patchouli body care plus baby balms — botanicals you can smell, not a perfume lab",
    story: "A farm apothecary that bundles lavender, patchouli, and baby-care jars from the same kettle. Glow and baby bundles stay if they are real skin or hair formulas. Produce, candles, and merch get dropped.",
    location: "United States",
    founded: 2019,
    categories: ["skincare","hair"],
    accent: "#6B4C7A",
    rating: 4.8,
    reviewCount: 340,
    followerCount: 5600,
    websiteUrl: "https://willowmoonfarm.com",
    logoUrl: "/brands/willow-moon-farm.png",
  },
  {
    id: "c825",
    slug: "sweet-bean-skin",
    name: "Sweet Bean Skin",
    tagline: "Mother, nurture, and little-bottom tallow balms — short INCI, no synthetic fragrance",
    story: "A tiny tallow studio for parents and dry skin. Mother Balm, Nurture Balm, and Little Bottom Balm keep the jar count small and the ingredient list readable. The how-to guide ebook stays off this shelf.",
    location: "United States",
    founded: 2021,
    categories: ["skincare"],
    accent: "#C4A484",
    rating: 4.8,
    reviewCount: 190,
    followerCount: 2800,
    websiteUrl: "https://sweetbeanskin.com",
    logoUrl: "/brands/sweet-bean-skin.svg",
  },
  {
    id: "c826",
    slug: "moo-tallow",
    name: "Moo Tallow",
    tagline: "Farm-to-face tallow soap and baby balm — grass-fed fat, no sweatshirt merch on this shelf",
    story: "A farm tallow label that renders for skin, not for a merch drop. MooBaby balm and tallow soap stay; cotton sweatshirts and gift cards do not. Short lists, ranch fat, no paraben stack.",
    location: "United States",
    founded: 2022,
    categories: ["skincare"],
    accent: "#8B5A2B",
    rating: 4.7,
    reviewCount: 150,
    followerCount: 2200,
    websiteUrl: "https://mootallow.com",
    logoUrl: "/brands/moo-tallow.svg",
  },
  {
    id: "c827",
    slug: "clae",
    name: "Clae",
    tagline: "Super Jojoba cleanser and a one-line face set — artisan jars, no 40-step routine",
    story: "A small jojoba-first studio that would rather sell one cleanser that works than a 12-step shelf. Super Jojoba facial cleanser, the One Line set, and essentials bundles stay. Empty artisan jars without formula get dropped.",
    location: "United States",
    founded: 2020,
    categories: ["skincare"],
    accent: "#1A1A1A",
    rating: 4.6,
    reviewCount: 380,
    followerCount: 6400,
    websiteUrl: "https://claeskin.com",
    logoUrl: "/brands/clae.svg",
  },
];
