import type { Brand } from "./types";

/** Wave 35: small organic / toxic-free brands across marketplace categories (c1019+). */
export const catalogBrandsWave35: Brand[] = [
  {
    id: "c1019",
    slug: "aelia",
    name: "AELIA",
    tagline: "Pilot-built mineral SPF 50 — non-nano zinc, no chemical-filter mousse wall",
    story: "A one-SKU high-altitude house that melts non-nano zinc oxide with pink microalgae and squalane instead of a 30-ingredient chemical-filter aisle. The Mineral SPF 50 stays. Empty travel kits stay in the suitcase.",
    location: "United States",
    founded: 2024,
    categories: ["sunscreen"],
    accent: "#1B4F72",
    rating: 4.6,
    reviewCount: 80,
    followerCount: 1400,
    websiteUrl: "https://aeliasun.com",
    logoUrl: "/brands/aelia.svg",
  },
  {
    id: "c1020",
    slug: "dune-suncare",
    name: "Dune Suncare",
    tagline: "Mineral melt sticks and sport sprays — zinc that actually rubs in, no surf-tee merch rack",
    story: "A California sun kitchen that pours mineral melt sticks, mug-and-bod guards, and sport sprays instead of a greasy paste wall. The Lifeguard, Mineral Melt, Slip Stick, and Golden Guard stay. Shred Lord sweatshirts, sunrise tees, gift cards, and Tally Health NAD+ widgets stay in the merch drawer.",
    location: "California, United States",
    founded: 2021,
    categories: ["sunscreen"],
    accent: "#C45C26",
    rating: 4.7,
    reviewCount: 2100,
    followerCount: 28000,
    websiteUrl: "https://dunesuncare.com",
    logoUrl: "/brands/dune-suncare.svg",
  },
  {
    id: "c1021",
    slug: "ecofam",
    name: "Ecofam",
    tagline: "Hydroxyapatite toothpaste tablets and mouthwash concentrates — flavor variants, no gadget tray",
    story: "A US oral house that compresses nano-hydroxyapatite and xylitol into chewable tablets instead of a plastic-tube aisle. Mint, bubble gum, and strawberry-kiwi stay as their own listings, plus peppermint mouthwash tablets. Free toothbrush giveaways and color-picker kits stay at checkout.",
    location: "United States",
    founded: 2020,
    categories: ["oral"],
    accent: "#2E7D32",
    rating: 4.6,
    reviewCount: 640,
    followerCount: 8900,
    websiteUrl: "https://ecofam.com",
    logoUrl: "/brands/ecofam.svg",
  },
  {
    id: "c1022",
    slug: "pioneer-tallow",
    name: "Pioneer Tallow",
    tagline: "Grass-fed whipped tallow moisturizers — scent variants, no cooking-jar pantry",
    story: "A small US tallow kitchen that whips grass-fed suet into short-list moisturizers instead of a 40-ingredient lotion wall. Calendula, vanilla bean, manuka, frankincense, and unscented stay as their own listings, plus goat-milk lotions. Build-your-own scent pickers stay expanded. Cooking tallow stays in the pantry.",
    location: "United States",
    founded: 2022,
    categories: ["skincare"],
    accent: "#6B3E26",
    rating: 4.7,
    reviewCount: 310,
    followerCount: 4200,
    websiteUrl: "https://pioneertallow.com",
    logoUrl: "/brands/pioneer-tallow.svg",
  },
  {
    id: "c1023",
    slug: "field-tallow",
    name: "Field Tallow",
    tagline: "Whipped bison tallow balms — Vanilla Sky, Quiet, Range, no merch tin wall",
    story: "A three-scent bison-tallow house that whips pasture fat into Vanilla Sky, Quiet, and Range instead of a fragrance-heavy cream aisle. Each scent stays as its own listing. The balm set stays. Tools stay out.",
    location: "United States",
    founded: 2023,
    categories: ["skincare"],
    accent: "#8B6914",
    rating: 4.8,
    reviewCount: 90,
    followerCount: 1600,
    websiteUrl: "https://fieldtallow.com",
    logoUrl: "/brands/field-tallow.svg",
  },
  {
    id: "c1024",
    slug: "good-flower-farm",
    name: "Good Flower Farm",
    tagline: "Oregon farm botanicals — plastic-free deodorant tubes, mushroom creams, no sticker shop",
    story: "An Oregon herb farm that pours tulsi body oil, magic-mushroom moisture cream, and charcoal-citrus deodorant in plastic-free tubes instead of a synthetic-fragrance wall. Lip balm and deodorant scents stay as their own listings. Testers, stickers, bandanas, consultation calls, and bug spray stay in the farm stand.",
    location: "Oregon, United States",
    founded: 2016,
    categories: ["skincare","deodorant"],
    accent: "#5B7A3A",
    rating: 4.8,
    reviewCount: 1800,
    followerCount: 22000,
    websiteUrl: "https://goodflowerfarm.com",
    logoUrl: "/brands/good-flower-farm.svg",
  },
  {
    id: "c1025",
    slug: "sunniemade",
    name: "Sunniemade",
    tagline: "Plastic-free shampoo and conditioner bars — mango, chia, bloom, no soap-dish accessory wall",
    story: "A plastic-free hair kitchen that ships Mighty Mango, Chia Glow, and Super Bloom bars instead of a water-heavy bottle aisle. Matching conditioner bars and lip balms stay, and scent variants stay as their own listings. Soap dishes, travel tins, scrap bags, and gift cards stay in the accessory drawer.",
    location: "United States",
    founded: 2019,
    categories: ["hair","skincare"],
    accent: "#C2185B",
    rating: 4.7,
    reviewCount: 920,
    followerCount: 14000,
    websiteUrl: "https://sunniemade.com",
    logoUrl: "/brands/sunniemade.svg",
  },
  {
    id: "c1026",
    slug: "green-routine",
    name: "My Green Routine",
    tagline: "UK dentist-made hydroxyapatite tablets plus plastic-free shampoo bars — no travel-pouch shop",
    story: "A UK bathroom house that chews 10% nano-hydroxyapatite into tablets and pours biotin, murumuru, and coconut shampoo bars instead of a fluoride-tube-and-plastic-bottle aisle. Dental and hair formulas stay. Donation SKUs, loofahs, hessian pouches, and travel tins stay out. Prices converted from GBP.",
    location: "United Kingdom",
    founded: 2018,
    categories: ["oral","hair"],
    accent: "#2C5F4E",
    rating: 4.6,
    reviewCount: 480,
    followerCount: 7600,
    websiteUrl: "https://mygreenroutine.earth",
    logoUrl: "/brands/green-routine.svg",
  },
  {
    id: "c1027",
    slug: "smash-melon",
    name: "Smash Melon",
    tagline: "One-ingredient watermelon-seed protein — no sweetener tub, no shaker merch",
    story: "A two-SKU US protein house that mills watermelon seeds into a complete plant powder instead of a gum-and-flavor tub wall. The bag and the sample singles stay. Shakers stay out.",
    location: "United States",
    founded: 2024,
    categories: ["protein"],
    accent: "#C62828",
    rating: 4.5,
    reviewCount: 70,
    followerCount: 1100,
    websiteUrl: "https://smashmelon.com",
    logoUrl: "/brands/smash-melon.svg",
  },
  {
    id: "c1028",
    slug: "kellemen",
    name: "Kellemen",
    tagline: "Athlete-tested aluminum-free deodorant — citrus, santal, ocean, no baking-soda sting",
    story: "A performance deodorant kitchen that uses zinc ricinoleate and magnesium hydroxide instead of a baking-soda rash stick. Citrus, Santal, Sandalwood, Ocean, and Fragrance-Free stay as their own listings, plus a jojoba body oil. The warmup kit stays if it is a formula, not merch.",
    location: "United States",
    founded: 2023,
    categories: ["deodorant","skincare"],
    accent: "#1A1A1A",
    rating: 4.7,
    reviewCount: 220,
    followerCount: 3400,
    websiteUrl: "https://kellemen.com",
    logoUrl: "/brands/kellemen.svg",
  },
  {
    id: "c1029",
    slug: "santa-cruz-paleo",
    name: "Santa Cruz Paleo",
    tagline: "All-natural electrolyte tubs, grass-fed whey, and tallow balms — flavor variants, no camo merch wall",
    story: "A Santa Cruz kitchen that seasons water with lychee, dragonfruit, and prickly-pear electrolytes, then bags grass-fed whey and pours bee-and-beef balm instead of a neon-sports-drink-and-lotion aisle. Flavor variants stay as their own listings. The mineral sun balm stays. Cooking tallow, GHK-Cu, pre-workout, dog treats, phone cases, and Make America Healthy tees stay out.",
    location: "Santa Cruz, California",
    founded: 2020,
    categories: ["electrolytes","protein","skincare","supplements"],
    accent: "#1565C0",
    rating: 4.6,
    reviewCount: 1500,
    followerCount: 19000,
    websiteUrl: "https://santacruzpaleo.com",
    logoUrl: "/brands/santa-cruz-paleo.svg",
  },
  {
    id: "c1030",
    slug: "adapt-electrolytes",
    name: "ADAPT",
    tagline: "Hydration, recovery, and sleep electrolyte mixes — watermelon lime, mango, tart cherry, no club-tee wall",
    story: "A drink-mix house that doses hydration, recovery, and sleep electrolytes instead of a sucralose sports-drink stick. Watermelon lime, pomegranate hibiscus, mango, and tart-cherry kiwi stay as their own listings. Halters, crewnecks, baby tees, glass bottles, and kids' shorts stay in the merch locker.",
    location: "United States",
    founded: 2022,
    categories: ["electrolytes"],
    accent: "#00695C",
    rating: 4.6,
    reviewCount: 380,
    followerCount: 6200,
    websiteUrl: "https://adaptelectrolytes.com",
    logoUrl: "/brands/adapt-electrolytes.svg",
  },
  {
    id: "c1031",
    slug: "myhydro",
    name: "MyHydro",
    tagline: "Two-flavor Himalayan-salt electrolytes — raspberry, lemon-lime, magnesium glycinate, no neon dye",
    story: "A two-SKU hydration house that seasons water with Himalayan salt, potassium, and magnesium glycinate instead of a maltodextrin packet. Raspberry and lemon-lime stay as their own listings. Prices converted from BHD.",
    location: "Bahrain",
    founded: 2024,
    categories: ["electrolytes"],
    accent: "#AD1457",
    rating: 4.5,
    reviewCount: 40,
    followerCount: 500,
    websiteUrl: "https://myhydro.me",
    logoUrl: "/brands/myhydro.svg",
  },
];
