import type { Brand } from "./types";

/** Wave 56: small organic / toxic-free brands across marketplace categories (c1207+). */
export const catalogBrandsWave56: Brand[] = [
  {
    id: "c1207",
    slug: "restore-oral",
    name: "Restore Oral Care",
    tagline: "Australian n-HA toothpaste from registered oral health therapists",
    story: "A Melbourne oral house formulated by registered oral health therapists around 15.5% nanoXIM nano-hydroxyapatite, xylitol, miswak, and green tea — fluoride-free, SLS-free, and low-foam. Individual Green Mint and Vanilla tubes stay. The two-tube duo stays boxed. AUD prices convert to USD.",
    location: "Melbourne, Australia",
    founded: 2024,
    categories: ["oral"],
    accent: "#3F6B52",
    rating: 4.7,
    reviewCount: 86,
    followerCount: 1900,
    websiteUrl: "https://restoreau.com",
    logoUrl: "/brands/restore-oral.svg",
  },
  {
    id: "c1208",
    slug: "origen",
    name: "Origen",
    tagline: "Canadian seawater electrolytes with 92 minerals and zero sugar",
    story: "A small Canadian hydration house that pouches Atlantic seawater electrolytes — 92 naturally occurring minerals, no sugar — in ready-to-drink 100 ml packs. The 7-Day Activation flavors expand (Mango, Unflavored, Wild Berry). The 12-pouch Premium listing stays. Protocol and duplicate 24/36/48 multipacks stay boxed. CAD prices convert to USD.",
    location: "Canada",
    founded: 2025,
    categories: ["electrolytes"],
    accent: "#1B4F72",
    rating: 4.6,
    reviewCount: 54,
    followerCount: 1200,
    websiteUrl: "https://origenseawater.com",
    logoUrl: "/brands/origen.svg",
  },
  {
    id: "c1209",
    slug: "fresh-harvest",
    name: "Fresh Harvest Farms",
    tagline: "Georgia-grown lion's mane, reishi, and cordyceps fruiting-body extracts",
    story: "A family mushroom farm in Dahlonega, Georgia that grows, extracts, and bottles 100% fruiting-body Lion's Mane, Reishi, and Cordyceps tinctures plus a Lion's Mane powder. Individual extracts stay. Daily bundles and microgreens pantry powders stay out.",
    location: "Dahlonega, Georgia, United States",
    founded: 2021,
    categories: ["supplements"],
    accent: "#4A5D23",
    rating: 4.7,
    reviewCount: 72,
    followerCount: 1400,
    websiteUrl: "https://freshharvestfarm.com",
    logoUrl: "/brands/fresh-harvest.svg",
  },
  {
    id: "c1210",
    slug: "tallow-spot",
    name: "The Tallow Spot",
    tagline: "Small-batch tallow sun stick, whipped jars, dry shampoo, and lip balms",
    story: "A small US tallow studio pouring a mineral sun stick and sun cream, named whipped tallow jars, a tallow lotion, dry shampoo, a frizz stick, and lip flavors. Sun stick versus sun cream expand as formats. Lip and sugar-scrub scents expand. Jar size stays one listing. Makeup tints, bath soaks, dish soap, rollers, elderberry kits, and gift wrap stay out.",
    location: "United States",
    founded: 2023,
    categories: ["sunscreen","skincare","hair"],
    accent: "#7A5A3A",
    rating: 4.6,
    reviewCount: 118,
    followerCount: 2100,
    websiteUrl: "https://thetallowspot.com",
    logoUrl: "/brands/tallow-spot.svg",
  },
  {
    id: "c1211",
    slug: "prairie-soap",
    name: "Prairie Soap Company",
    tagline: "North Dakota buffalo tallow lotion, soap bars, and lip balms",
    story: "A prairie soap kitchen that renders grass-fed buffalo tallow into a handcrafted lotion, the original bar that put the shop on the map, and a small-batch lip balm. Lotion fragrances, soap styles, and lip flavors expand. 2 oz versus 6 oz is size, not a flavor.",
    location: "North Dakota, United States",
    founded: 2018,
    categories: ["skincare"],
    accent: "#8B5E3C",
    rating: 4.8,
    reviewCount: 240,
    followerCount: 3600,
    websiteUrl: "https://prairiesoapco.com",
    logoUrl: "/brands/prairie-soap.svg",
  },
];
