import type { Brand } from "./types";

/** Wave 106: small organic / toxic-free brands across marketplace categories (c1505+). */
export const catalogBrandsWave106: Brand[] = [
  {
    id: "c1505",
    slug: "underbrush",
    name: "Underbrush",
    tagline: "Plastic-free n-HA chewing gum — chicle, xylitol, nano and micro hydroxyapatite, no aspartame",
    story:
      "Nathan was tired of gum that listed a secret plastic base and called it mint. Underbrush is the chew he built instead: a named chicle base, xylitol, and both nano and micro hydroxyapatite — the same mineral enamel is made of — in Mastic Mint and Cinna Mastic. Plus a pearl-powder tooth scrub and a boar-hair or castor-oil brush for the sink. Pack count is size. No hats, no walnut cases, no membership vault: the gum you actually chew.",
    location: "United States",
    founded: 2023,
    categories: ["oral"],
    accent: "#3D6B4F",
    rating: 4.6,
    reviewCount: 25200,
    followerCount: 41000,
    websiteUrl: "https://nathanandsons.com",
    logoUrl: "/brands/underbrush.svg",
  },
  {
    id: "c1506",
    slug: "electrik-kids",
    name: "Elec'trik Kids",
    tagline: "Vancouver mom-made kids electrolytes — coconut water, zero added sugar, four title flavors",
    story:
      "Carmen and Laura were watching Vancouver kids walk around with juice-box electrolytes and a sugar crash. Elec'trik is the powder they mixed for their own: coconut water, real minerals, seven added vitamins, zero added sugar. Go Go Grape, Power Punch, Tropical Turbo, Razzy Rocket — already on the title. No bundle, no juice aisle. The stick you tear for the water bottle in the backpack.",
    location: "Vancouver, BC",
    founded: 2025,
    categories: ["electrolytes"],
    accent: "#7B3FA0",
    rating: 4.7,
    reviewCount: 86,
    followerCount: 2400,
    websiteUrl: "https://get-electrik.com",
    logoUrl: "/brands/electrik-kids.svg",
  },
  {
    id: "c1507",
    slug: "noordcode",
    name: "Noordcode",
    tagline: "Dutch Alps grass-fed organic whey — one ingredient, cacao or unflavoured, plus organic plant protein",
    story:
      "Eduard left the corporate calendar in Uden because every European whey still hid a gum and a sweetener behind 'clean.' Noordcode is the Alps answer: organic, grass-fed whey concentrate — one ingredient, 80% protein — in unflavoured and cacao, plus an organic plant pouch for the people who do not do dairy. No bars, no coffee, no 3-pack. The bags you scoop.",
    location: "Uden, Netherlands",
    founded: 2019,
    categories: ["protein"],
    accent: "#1F3A5F",
    rating: 4.7,
    reviewCount: 1240,
    followerCount: 18000,
    websiteUrl: "https://noordcode.com",
    logoUrl: "/brands/noordcode.svg",
  },
  {
    id: "c1508",
    slug: "lazuli-farms",
    name: "Lazuli Farms",
    tagline: "Alberta family tallow — zinc sun balm, baking-soda-free deodorant, whipped butters poured on the farm",
    story:
      "A family in central Alberta started rendering grass-fed tallow because every 'clean' cream still left their skin tight in January. Lazuli Farms is the line that followed: a mineral zinc sun balm, a tinted zinc lip with SPF 15, and baking-soda-free deodorant in bergamot grapefruit, charcoal tea tree, and cedarwood patchouli lime. Plus whipped butters, face creams, shampoo bars, and lip balms. No candles, no dish soap, no gift sets: the jars they still pour by hand.",
    location: "Alberta, Canada",
    founded: 2019,
    categories: ["sunscreen", "deodorant", "skincare", "hair"],
    accent: "#5B6B3A",
    rating: 4.8,
    reviewCount: 640,
    followerCount: 8900,
    websiteUrl: "https://lazulifarms.com",
    logoUrl: "/brands/lazuli-farms.svg",
  },
  {
    id: "c1509",
    slug: "cattle-creek",
    name: "Cattle Creek Mercantile",
    tagline: "Farm tallow mercantile — aluminum-free deodorant, whipped butters, soap and lip scents from the herd",
    story:
      "Cattle Creek renders suet from the farm's own steers and turns it into the bathroom shelf: an aluminum-free tallow deodorant in clean-and-fresh, vanilla, and lavender peppermint. Whipped butters, a frankincense face cream, lip balms, shampoo bars, a beard balm, and a hair pomade. No free-gift loofahs, no soap trays, no build-a-box: the jars that come off the farm.",
    location: "United States",
    founded: 2021,
    categories: ["deodorant", "skincare", "hair"],
    accent: "#6B4A2A",
    rating: 4.8,
    reviewCount: 1452,
    followerCount: 6200,
    websiteUrl: "https://cattle-creek.com",
    logoUrl: "/brands/cattle-creek.svg",
  },
  {
    id: "c1510",
    slug: "roots-apothecary",
    name: "Roots Apothecary",
    tagline: "Texas handmade fruiting-body extracts — Lion's Mane tincture and powder, no mycelium-on-grain",
    story:
      "Roots has been bottling plant therapy in Texas for a decade — from scratch, not from a white-label tub. Lion's Mane as a fruiting-body tincture and an organic extract. Turkey tail, reishi, cordyceps. Lemon balm, rhodiola, ashwagandha, and the everyday tinctures they still make by hand. A scent-expand natural deodorant, a face serum, a cleanse, a body salve. No essential-oil racks, no honey, no people-packs: the droppers and jars from the workbench.",
    location: "Texas",
    founded: 2015,
    categories: ["supplements", "skincare", "deodorant"],
    accent: "#3A4A32",
    rating: 4.8,
    reviewCount: 980,
    followerCount: 14000,
    websiteUrl: "https://www.rootsapothecary.com",
    logoUrl: "/brands/roots-apothecary.svg",
  },
];
