import type { Brand } from "./types";

/** Wave 74: small organic / toxic-free brands across marketplace categories (c1313+). */
export const catalogBrandsWave74: Brand[] = [
  {
    id: "c1313",
    slug: "happy-tooth",
    name: "Happy Tooth",
    tagline: "Utah pediatric-dentist 10% micro-hydroxyapatite toothpaste in crave-worthy flavors",
    story: "A Utah oral house formulated by a pediatric dentist around naturally sourced micro-hydroxyapatite — Vanilla Frosting, Fresh Mint, Sweet Orange, Mint Brownie, Lemon Twist, and limited Strawberry Bubblegum. Flavors already live on separate titles; the parent Fluoride-Free listing stays boxed so those titles are not duplicated. Travel Flavor expands. Pack count is size. Bundles, gift cards, electric brushes, whitening strips, books, and stickers stay boxed. Product pages publish a full comma INCI.",
    location: "Utah",
    founded: 2019,
    categories: ["oral"],
    accent: "#3D7A6A",
    rating: 4.8,
    reviewCount: 560,
    followerCount: 18000,
    websiteUrl: "https://tryhappytooth.com",
    logoUrl: "/brands/happy-tooth.svg",
  },
  {
    id: "c1314",
    slug: "brdy-juice",
    name: "Brdy Juice",
    tagline: "Chicago small-batch zero-sugar electrolyte sticks built for a long day outside",
    story: "A Chicago hydration kitchen mixing 350 mg sodium, potassium, magnesium, and B vitamins into a zero-sugar stick with no artificial dyes. Flavour currently expands Iced Tea Lemonade. Twenty-seven sachets is size. Hats, sample packs, and bottle bundles stay boxed. Cart.js is USD.",
    location: "Chicago, IL",
    founded: 2024,
    categories: ["electrolytes"],
    accent: "#1F6B4A",
    rating: 4.6,
    reviewCount: 48,
    followerCount: 2200,
    websiteUrl: "https://www.brdyjuice.com",
    logoUrl: "/brands/brdy-juice.svg",
  },
  {
    id: "c1315",
    slug: "agn-roots",
    name: "AGN Roots",
    tagline: "Unflavored Irish grass-fed whey isolate with Informed-Sport testing and no junk sweeteners",
    story: "A US protein house sourcing Truly Grass-Fed Irish whey isolate from pasture dairies — one ingredient plus a touch of sunflower lecithin. One pound vs three pounds is size. No flavor expand. Published formula is grass-fed whey isolate.",
    location: "United States",
    founded: 2018,
    categories: ["protein"],
    accent: "#2C4A3E",
    rating: 4.8,
    reviewCount: 310,
    followerCount: 9600,
    websiteUrl: "https://agnroots.com",
    logoUrl: "/brands/agn-roots.svg",
  },
  {
    id: "c1316",
    slug: "kozon",
    name: "Kōzōn",
    tagline: "Boise mineral SPF 30, aluminum-free deodorant, and short-list ozonated skincare",
    story: "A family-owned Boise house pouring non-nano zinc Helios sunscreen plus a two-scent mineral deodorant and tallow-free balms. Deodorant Scent expands Grapefruit / Unscented. SPF on the O3 lip is size. Gua sha, gift sets, and tinted lip stay boxed. Helios publishes a jojoba / shea / beeswax / cocoa / zinc list.",
    location: "Boise, ID",
    founded: 2021,
    categories: ["sunscreen","deodorant","skincare"],
    accent: "#C4783A",
    rating: 4.7,
    reviewCount: 36,
    followerCount: 1400,
    websiteUrl: "https://kozonskincare.com",
    logoUrl: "/brands/kozon.svg",
  },
  {
    id: "c1317",
    slug: "sunniemade",
    name: "Sunniemade",
    tagline: "Steamboat Springs plastic-free shampoo bars, conditioner bars, and plant-oil soaps",
    story: "A Colorado bar house swapping watered-down bottles for Mighty Mango, Super Bloom, and Chia Glow solids plus rosemary and citrus body bars. Scents already live on separate titles. Dishes, tins, duos, starter kits, scrap bags, and gift cards stay boxed.",
    location: "Steamboat Springs, CO",
    founded: 2022,
    categories: ["hair","skincare"],
    accent: "#D48A3A",
    rating: 4.7,
    reviewCount: 92,
    followerCount: 3800,
    websiteUrl: "https://sunniemade.com",
    logoUrl: "/brands/sunniemade.svg",
  },
  {
    id: "c1318",
    slug: "shroomery-nm",
    name: "The Shroomery NM",
    tagline: "New Mexico fruiting-body lion's mane, cordyceps, and reishi tinctures grown in-house",
    story: "A New Mexico grow house dual-extracting fruiting bodies only — no mycelium on grain — into lion's mane, cordyceps, reishi, and a lion's mane + cordyceps mix. One ounce is size. Loose-leaf tea stays boxed. Published formula is species plus cane alcohol and water.",
    location: "New Mexico",
    founded: 2022,
    categories: ["supplements"],
    accent: "#5A3D2B",
    rating: 4.6,
    reviewCount: 28,
    followerCount: 900,
    websiteUrl: "https://theshroomerynm.com",
    logoUrl: "/brands/shroomery-nm.svg",
  },
];
