import type { Brand } from "./types";

/** Wave 58: small organic / toxic-free brands across marketplace categories (c1218+). */
export const catalogBrandsWave58: Brand[] = [
  {
    id: "c1218",
    slug: "dr-brite",
    name: "Dr. Brite",
    tagline: "USA-made coconut-oil whitening toothpaste and mint mouthwash",
    story: "A small American oral house pouring coconut-oil whitening toothpastes in mint, mint chip, coco chai, and kids berry, plus a mint mouthwash. Individual tubes and the mint rinse stay. The placeholder whitening pen, lorem-ipsum sprays, and size upgrades stay boxed. Size is not a flavor.",
    location: "United States",
    founded: 2014,
    categories: ["oral"],
    accent: "#2F6B62",
    rating: 4.6,
    reviewCount: 186,
    followerCount: 3200,
    websiteUrl: "https://drbrite.com",
    logoUrl: "/brands/dr-brite.png",
  },
  {
    id: "c1219",
    slug: "humble-goat",
    name: "The Humble Goat",
    tagline: "Minnesota goat-whey isolate from the Happy Goat dairy network",
    story: "Stickney Hill Dairy's protein shop in Minnesota's heartland, isolating goat whey from pasture-raised herds in the Happy Goat program. Vanilla and chocolate one-time tubs stay. Subscription SKUs stay boxed. Flavor is already a separate title.",
    location: "Minnesota, United States",
    founded: 2019,
    categories: ["protein"],
    accent: "#7A5A2B",
    rating: 4.7,
    reviewCount: 74,
    followerCount: 1600,
    websiteUrl: "https://thehumblegoat.com",
    logoUrl: "/brands/humble-goat.svg",
  },
  {
    id: "c1220",
    slug: "short-story",
    name: "Short Story",
    tagline: "Five-ingredient lemon electrolytes with coconut water and monk fruit",
    story: "A tiny hydration house mixing organic coconut water, organic lemon juice, marine magnesium, Himalayan pink salt, and monk fruit. The Daily 30-serving tub and the Intro 7-serving trial stay. Serving count is size, not a flavor.",
    location: "United States",
    founded: 2024,
    categories: ["electrolytes"],
    accent: "#C4A35A",
    rating: 4.6,
    reviewCount: 48,
    followerCount: 900,
    websiteUrl: "https://drinkshortstory.com",
    logoUrl: "/brands/short-story.svg",
  },
  {
    id: "c1221",
    slug: "live-kaizen",
    name: "Kaizen",
    tagline: "Himalayan-salt electrolytes with sea moss and taurine, plus mushroom coffee",
    story: "A small clean-hydration house blending Himalayan rock salt, magnesium glycinate, organic sea moss, taurine, and monk fruit. Lemon Lime, Mixed Berry, and Tropical Blend expand. Bulk versus travel pack is size. The mushroom coffee stays as a supplement. Frothers, bottles, sweatshirts, and free sample packs stay out.",
    location: "United States",
    founded: 2023,
    categories: ["electrolytes","supplements"],
    accent: "#1F4E3D",
    rating: 4.6,
    reviewCount: 62,
    followerCount: 1400,
    websiteUrl: "https://livekaizen.com",
    logoUrl: "/brands/live-kaizen.svg",
  },
  {
    id: "c1222",
    slug: "archwood",
    name: "Archwood Soapery",
    tagline: "Pennsylvania toxin-free cream deodorant, solid hair bars, and Filthy Vegan skin",
    story: "A Reading, Pennsylvania chemist-founder house making magnesium cream deodorant, salon-tested shampoo and conditioner bars, cold-process soap, and short-list serums under EU-minded rules — no titanium dioxide, no formaldehyde releasers. Deodorant and Filthy Vegan soap scents expand. Bug spray, shower trays, and lip gloss stay out.",
    location: "Reading, Pennsylvania, United States",
    founded: 2021,
    categories: ["deodorant","hair","skincare"],
    accent: "#4A3B2A",
    rating: 4.7,
    reviewCount: 98,
    followerCount: 2100,
    websiteUrl: "https://archwoodsoapery.com",
    logoUrl: "/brands/archwood.svg",
  },
];
