import type { Brand } from "./types";

/** Wave 73: small organic / toxic-free brands across marketplace categories (c1307+). */
export const catalogBrandsWave73: Brand[] = [
  {
    id: "c1307",
    slug: "grind-goods",
    name: "Grind Goods",
    tagline: "Fluoride-free dual hydroxyapatite toothpaste in nine crave-worthy flavors",
    story: "A US oral house built around DROXY — micro plus nano-hydroxyapatite with theobromine and xylitol — so brushing tastes like a treat and still rebuilds enamel. Flavors already live on separate titles (Achieve Mint through Berry Dip'd). Pack count is size. Three-packs stay boxed. Product-page INCI is published under Ingredients.",
    location: "United States",
    founded: 2020,
    categories: ["oral"],
    accent: "#1F3A2E",
    rating: 4.7,
    reviewCount: 186,
    followerCount: 5400,
    websiteUrl: "https://grindgoods.com",
    logoUrl: "/brands/grind-goods.svg",
  },
  {
    id: "c1308",
    slug: "eirlyte",
    name: "EirLyte",
    tagline: "Zero-sugar Irish sea-salt electrolytes in kiwi, pineapple, and watermelon",
    story: "An Irish hydration kitchen mixing organic mineral sea salt into a 2,900 mg zero-sugar stick pack. Flavour expands Kiwi / Pineapple / Watermelon. Thirty sticks is size. Bundle / 90-stick value packs stay boxed. Cart.js is USD — do not apply EUR 1.08.",
    location: "Ireland",
    founded: 2023,
    categories: ["electrolytes"],
    accent: "#1A5A6B",
    rating: 4.6,
    reviewCount: 72,
    followerCount: 1600,
    websiteUrl: "https://www.eirlyte.com",
    logoUrl: "/brands/eirlyte.svg",
  },
  {
    id: "c1309",
    slug: "peachie-spoon",
    name: "The Peachie Spoon",
    tagline: "Small-batch grass-fed whey, creatine, and collagen without gums or junk sweeteners",
    story: "A clean US kitchen behind Vanilla, Chocolate, and Cookies & Cream grass-fed whey plus Creavitalis creatine and unflavored hydrolyzed collagen. Flavors already live on separate titles. Tees and daily-essentials bundles stay boxed. Creatine stays supplements; creatine + electrolytes can sit with hydration.",
    location: "United States",
    founded: 2019,
    categories: ["protein","supplements"],
    accent: "#C45C6A",
    rating: 4.7,
    reviewCount: 128,
    followerCount: 8900,
    websiteUrl: "https://thepeachiespoon.com",
    logoUrl: "/brands/peachie-spoon.svg",
  },
  {
    id: "c1310",
    slug: "fango",
    name: "FANGO",
    tagline: "Puerto Rico reef-safe mineral sticks and balms with five-ingredient zinc formulas",
    story: "A Caribbean mineral house handcrafting non-nano zinc sticks and balms in Original, Lavender, Mangopaya, Passion, and Tinted. Scents already live on separate titles. SPF 30 vs 50 is size. Family packs, duos, kits, bug spray, and tanning oils stay boxed. Mint lip balm stays skincare. Pages publish a coconut / shea / beeswax / raspberry / zinc list.",
    location: "Puerto Rico",
    founded: 2022,
    categories: ["sunscreen","skincare"],
    accent: "#C45C26",
    rating: 4.8,
    reviewCount: 64,
    followerCount: 2100,
    websiteUrl: "https://fangospf.com",
    logoUrl: "/brands/fango.svg",
  },
  {
    id: "c1311",
    slug: "goat-milk-stuff",
    name: "Goat Milk Stuff",
    tagline: "Farm-fresh goat milk deodorant, cold-process soaps, and aluminum-free everyday care",
    story: "A family farm pouring fresh goat milk into aluminum-free deodorant, bagged cold-process bars, solid lotions, shampoo bars, lip balms, and a mineral tooth powder. Deodorant and large-lotion Scent expand. Naked, mega, travel, luffa, small, and tub listings are size. Laundry, dish, pet, perfume, gifts, irregular seconds, and merch stay boxed.",
    location: "United States",
    founded: 2008,
    categories: ["deodorant","skincare","hair"],
    accent: "#6B4A2A",
    rating: 4.8,
    reviewCount: 420,
    followerCount: 12000,
    websiteUrl: "https://goatmilkstuff.com",
    logoUrl: "/brands/goat-milk-stuff.png",
  },
  {
    id: "c1312",
    slug: "humby-organics",
    name: "Humby Organics",
    tagline: "Handmade US shampoo and conditioner bars plus scalp oils without plastic bottles",
    story: "A small American bar house pouring Blueberry Fields, Purple Rain, Mango Breeze, and a dozen more scents into solid shampoo and conditioner. Scent already lives on most titles; the parent Shampoo Bars / Conditioner Bars listings expand. Bundles, subscriptions, trays, combs, brushes, and tins stay boxed. Keep the hair oils.",
    location: "United States",
    founded: 2018,
    categories: ["hair"],
    accent: "#5B3A6A",
    rating: 4.7,
    reviewCount: 210,
    followerCount: 4300,
    websiteUrl: "https://humbyorganics.com",
    logoUrl: "/brands/humby-organics.svg",
  },
];
