import type { Brand } from "./types";

/** Wave 80: small organic / toxic-free brands across marketplace categories (c1349+). */
export const catalogBrandsWave80: Brand[] = [
  {
    id: "c1349",
    slug: "minvelle",
    name: "Minvelle",
    tagline: "Austrian nano-hydroxyapatite remineralizing whitening gum — sugar-free and fluoride-free",
    story: "An Austrian oral house making one remineralizing whitening gum with nano-hydroxyapatite — sugar-free, fluoride-free, and built to brighten between brushes. Box count is size (keep one box). Cart.js is EUR × 1.08. Pages publish the n-HA gum list when a real formula is on the page.",
    location: "Austria",
    founded: 2023,
    categories: ["oral"],
    accent: "#6B8F71",
    rating: 4.6,
    reviewCount: 180,
    followerCount: 2400,
    websiteUrl: "https://minvelle.com",
    logoUrl: "/brands/minvelle.svg",
  },
  {
    id: "c1350",
    slug: "lift-hydration",
    name: "Lift Hydration",
    tagline: "Sugar-free monk-fruit electrolyte sticks in Lemon Lime and Strawberry Lemonade",
    story: "A US hydration house mixing sodium, potassium, and magnesium with organic monk fruit — Lemon Lime and Strawberry Lemonade already live on separate 16-pack titles. Stick count is size. Bundles and multi-flavor mix packs stay boxed. Cart.js is USD. Pages publish the mineral + monk-fruit list when a real formula is on the page.",
    location: "United States",
    founded: 2022,
    categories: ["electrolytes"],
    accent: "#2E7D8A",
    rating: 4.6,
    reviewCount: 320,
    followerCount: 4800,
    websiteUrl: "https://lifthydration.com",
    logoUrl: "/brands/lift-hydration.svg",
  },
  {
    id: "c1351",
    slug: "earth-fed-muscle",
    name: "Earth Fed Muscle",
    tagline: "Truly Grass Fed whey isolate, casein, plant protein, and collagen with short ingredient lists",
    story: "A US protein house sourcing Truly Grass Fed Irish whey — Vanilla, Chocolate, mocha, peanut-butter cup, cookies and cream, unflavored, seasonal scoops, plus casein, Common Ground plant protein, and collagen. Flavors already live on separate titles. Serving count is size. Tees, shakers, samples, bars, pancake mix, preworkout, and shipping protection stay boxed. Elixir electrolytes expand Berry / Citrus. Cart.js is USD.",
    location: "United States",
    founded: 2015,
    categories: ["protein","electrolytes","supplements"],
    accent: "#3F6B3A",
    rating: 4.8,
    reviewCount: 4200,
    followerCount: 38000,
    websiteUrl: "https://earthfedmuscle.com",
    logoUrl: "/brands/earth-fed-muscle.svg",
  },
  {
    id: "c1352",
    slug: "balmy-tallow",
    name: "Balmy Tallow",
    tagline: "Dallas-made grass-fed tallow sunblock, aluminum-free deodorant, and short-list balms",
    story: "A Dallas farmers-market tallow house pouring mineral sunblock, aluminum-free deodorant in Citrus Vanilla and unscented, whipped balms, peppermint lip, magnesium bedtime balm, and remineralizing mint-and-egg tooth powder. Jar oz is size (keep 4 oz over 2 oz). Minis, spoons, bug balm, and the mini picker stay boxed. Cart.js is USD. Pages publish tallow / zinc / oil lists when a real INCI is on the page.",
    location: "Dallas, TX",
    founded: 2022,
    categories: ["sunscreen","deodorant","skincare","oral"],
    accent: "#C4A35A",
    rating: 4.8,
    reviewCount: 410,
    followerCount: 6200,
    websiteUrl: "https://balmytallow.com",
    logoUrl: "/brands/balmy-tallow.svg",
  },
  {
    id: "c1353",
    slug: "take-haven",
    name: "Take Haven",
    tagline: "Artisan herbal shampoo bars, hair oils, complexion bars, and small-batch plant skincare",
    story: "A US herbal house pouring sulfate-free shampoo bars (Hydrate + Shine, Clean + Condition, Strong + Voluminous, Balance + Soothe), matching hair oils, complexion bars, goat-free soaps, clay masks, face oils, and herbal moisturizers. Scents already live on separate titles. Room sprays, soaking salts, milk baths, and the oracle deck stay boxed. Cart.js is USD. Shampoo-bar pages publish saponified-oil INCI.",
    location: "United States",
    founded: 2018,
    categories: ["hair","skincare"],
    accent: "#7A5C8A",
    rating: 4.8,
    reviewCount: 760,
    followerCount: 11000,
    websiteUrl: "https://takehaven.com",
    logoUrl: "/brands/take-haven.svg",
  },
  {
    id: "c1354",
    slug: "fat-fox-thrive",
    name: "Fat Fox Thrive",
    tagline: "UK dual extracts of lion's mane, reishi, chaga, and shiitake from Fat Fox Mushrooms",
    story: "A UK mushroom house making dual-extracted fruiting-body tinctures — lion's mane, reishi, chaga, and shiitake. Bottle size is size. Grow kits stay on the sister shop. Cart.js is GBP × 1.27. Pages publish the fruiting-body + alcohol + water list when a real formula is on the page.",
    location: "United Kingdom",
    founded: 2020,
    categories: ["supplements"],
    accent: "#5A4632",
    rating: 4.8,
    reviewCount: 220,
    followerCount: 3600,
    websiteUrl: "https://fatfoxthrive.com",
    logoUrl: "/brands/fat-fox-thrive.svg",
  },
];
