import type { Brand } from "./types";

/** Wave 16: small organic / toxic-free brands across marketplace categories (c701+). */
export const catalogBrandsWave16: Brand[] = [
  {
    id: "c701",
    slug: "avocado-zinc",
    name: "Avocado Zinc",
    tagline: "Australian avocado-oil zinc SPF 50 that rubs in clear — no chemical-filter stack",
    story: "An Australian sun kitchen that starts with avocado oil and non-nano zinc instead of a 40-ingredient chemical cocktail. Physical SPF 50 pastes, tinted moisturisers, and glow drops made without synthetic fragrance or chemical UV filters — reef-minded coverage that actually feels like skincare.",
    location: "Australia",
    founded: 2021,
    categories: ["sunscreen"],
    accent: "#3D6B4F",
    rating: 4.8,
    reviewCount: 720,
    followerCount: 24000,
    websiteUrl: "https://avocadozinc.com",
    logoUrl: "/brands/avocado-zinc.svg",
  },
  {
    id: "c702",
    slug: "koy-skin",
    name: "köy",
    tagline: "Manchester-handmade tallow balms and reef-safe raspberry mineral sun cream",
    story: "Born from a Turkish village kitchen and poured in Manchester: grass-fed tallow, calendula, bakuchiol serum, and Raspberry Sun — a toxin-free mineral zinc cream with a short organic list. No synthetic fragrance fog, no filler oils — handmade rituals for skin that wants food, not a lab stack.",
    location: "Manchester, UK",
    founded: 2023,
    categories: ["sunscreen","skincare","hair"],
    accent: "#8B4A3A",
    rating: 4.8,
    reviewCount: 180,
    followerCount: 4200,
    websiteUrl: "https://www.koy.skin",
    logoUrl: "/brands/koy-skin.svg",
  },
  {
    id: "c703",
    slug: "kozon",
    name: "Kōzōn",
    tagline: "Boise family kitchen — Helios zinc SPF 30 and mineral deodorant in a short plant list",
    story: "Szilvia's Idaho studio: non-nano zinc in jojoba, shea, beeswax, and cocoa butter — Helios SPF 30 that sits on the skin instead of soaking in. Plus mineral deodorant, calendula and arnica balms, and activated-oxygen care. Kid-friendly, small-batch, and free of the drugstore chemical-filter fog.",
    location: "Boise, ID",
    founded: 2021,
    categories: ["sunscreen","deodorant","skincare"],
    accent: "#C45C26",
    rating: 4.7,
    reviewCount: 210,
    followerCount: 3800,
    websiteUrl: "https://kozonskincare.com",
    logoUrl: "/brands/kozon.svg",
  },
  {
    id: "c704",
    slug: "pantry-products",
    name: "Pantry Products",
    tagline: "Salt Lake City pantry — reef-safe zinc SPF 30 sticks, rosemary shampoo, and food-grade balms",
    story: "A Utah kitchen that treats sun care like a recipe: non-nano zinc, coconut, raspberry seed, and shea in a recyclable aluminum tube or tin. Handmade mineral SPF, rosemary-mint hair, and everywhere-balms poured in small batches — no oxybenzone, no octinoxate, no mystery preservative drawer.",
    location: "Salt Lake City, UT",
    founded: 2019,
    categories: ["sunscreen","hair","skincare"],
    accent: "#6B3E26",
    rating: 4.8,
    reviewCount: 640,
    followerCount: 11000,
    websiteUrl: "https://shoppantryproducts.com",
    logoUrl: "/brands/pantry-products.svg",
  },
  {
    id: "c705",
    slug: "reef-replenish",
    name: "Reef Replenish",
    tagline: "Tropical hydration with Himalayan salt and coconut water — zero added sugar, no dye circus",
    story: "A clean tropical hydration house: pink Himalayan salt, organic coconut water powder, and ocean minerals in lemon-lime, mango tangerine, and wildberry. Five electrolytes, no added sugar, no artificial sweeteners or neon dyes — built for trail days and saltwater, not a locker-room candy aisle.",
    location: "United States",
    founded: 2022,
    categories: ["electrolytes"],
    accent: "#1A7A8C",
    rating: 4.7,
    reviewCount: 310,
    followerCount: 8600,
    websiteUrl: "https://reefreplenish.com",
    logoUrl: "/brands/reef-replenish.svg",
  },
  {
    id: "c706",
    slug: "daily-electrolytes",
    name: "Daily Electrolytes",
    tagline: "Himalayan-salt stick packs in seven organic fruit flavors — no sugar, no dye stack",
    story: "A simple hydration kitchen: Himalayan pink salt, magnesium malate, potassium, and organic fruit flavors sweetened with stevia. Seven tropical rotations, keto- and paleo-friendly, zero sugar and zero artificial dyes — electrolytes you can actually read in one glance.",
    location: "United States",
    founded: 2021,
    categories: ["electrolytes"],
    accent: "#E27D60",
    rating: 4.6,
    reviewCount: 890,
    followerCount: 19000,
    websiteUrl: "https://dailyelectrolytes.com",
    logoUrl: "/brands/daily-electrolytes.svg",
  },
  {
    id: "c707",
    slug: "tidlos",
    name: "TIDLØS",
    tagline: "Three-ingredient New Zealand pasture whey sweetened with whole organic dates — no stevia, no gums",
    story: "A protein house that refused the flavor-lab drawer. New Zealand grass-fed whey concentrate from cows on pasture 365 days a year, sweetened with whole organic dates and flavored with real vanilla, cacao, or Ceylon cinnamon. No stevia, no 'natural flavors,' no emulsifier fog — recovery powder your grandmother would recognize.",
    location: "United States / New Zealand",
    founded: 2023,
    categories: ["protein"],
    accent: "#2C5F4E",
    rating: 4.8,
    reviewCount: 140,
    followerCount: 5200,
    websiteUrl: "https://tidlos.co",
    logoUrl: "/brands/tidlos.svg",
  },
  {
    id: "c708",
    slug: "prookie",
    name: "Prookie",
    tagline: "Winnipeg one-ingredient organic pea protein — 24g, no flavor fog, no filler pile",
    story: "A young Canadian kitchen packing North American peas into a bag with exactly one ingredient. Unflavoured, 24g protein, 80% isolate, no artificial flavors, no preservatives, no gums. Packed in Winnipeg for people who want plant protein without a candy-shake aftertaste.",
    location: "Winnipeg, Canada",
    founded: 2022,
    categories: ["protein"],
    accent: "#4A7C59",
    rating: 4.7,
    reviewCount: 96,
    followerCount: 2100,
    websiteUrl: "https://prookieprotein.ca",
    logoUrl: "/brands/prookie.svg",
  },
  {
    id: "c709",
    slug: "future-kind",
    name: "Future Kind",
    tagline: "Organic vegan pea protein in a compostable pouch, plus B12 and plant multis without the junk drawer",
    story: "A vegan nutrition studio that put organic non-GMO pea protein in a compostable pouch — 20g, third-party tested, made in the USA. Plus B12 energy gummies, plant multis, and collagen-booster botanicals without animal products or a synthetic dye stack. Clean labels for people who actually read them.",
    location: "United States",
    founded: 2018,
    categories: ["protein","supplements"],
    accent: "#3D8B6E",
    rating: 4.6,
    reviewCount: 2400,
    followerCount: 62000,
    websiteUrl: "https://www.futurekind.com",
    logoUrl: "/brands/future-kind.svg",
  },
  {
    id: "c710",
    slug: "green-forest-lady",
    name: "The Green Forest Lady",
    tagline: "Family-poured organic magnesium deodorant and herbal salves in glass — no aluminum, no baking soda",
    story: "A mom-run kitchen infusing nettle, dandelion, and borage into a baking-soda-free magnesium deodorant that actually soothes pits. Plus wildcrafted creosote and arnica salves, baby booty balm, and belly care in recyclable glass. Organic, plastic-free, and poured in small batches the family has used for years.",
    location: "United States",
    founded: 2016,
    categories: ["deodorant","skincare"],
    accent: "#2F5D3A",
    rating: 4.8,
    reviewCount: 430,
    followerCount: 7400,
    websiteUrl: "https://thegreenforestlady.com",
    logoUrl: "/brands/green-forest-lady.svg",
  },
  {
    id: "c711",
    slug: "wild-june",
    name: "Wild June Co.",
    tagline: "Award-winning magnesium deodorant cream in a glass jar — aluminum-free, baking-soda-free",
    story: "A 2026 Earth Day beauty-award kitchen: magnesium hydroxide, arrowroot, and kaolin in a reusable glass jar with a wooden stick. No aluminum, no baking soda, no synthetic fragrance — plus mountain mocha scrubs, lunar body oils, and peppermint lip balm poured in small batches for sensitive skin.",
    location: "United States",
    founded: 2020,
    categories: ["deodorant","skincare"],
    accent: "#7A4E2D",
    rating: 4.8,
    reviewCount: 380,
    followerCount: 9100,
    websiteUrl: "https://wildjuneco.com",
    logoUrl: "/brands/wild-june.svg",
  },
  {
    id: "c712",
    slug: "happy-tooth",
    name: "Happy Tooth",
    tagline: "10% micro-hydroxyapatite toothpaste and mineral mouthwash — fluoride-free, no filler pile",
    story: "A family oral-care studio that put 10% micro-hydroxyapatite — the mineral enamel is already made of — into a short, readable paste. Fresh mint and mineral mouthwash without fluoride, SLS, or the neon-gel theater. Built for people who want enamel rebuilt, not a pharmacy aisle aftertaste.",
    location: "United States",
    founded: 2021,
    categories: ["oral"],
    accent: "#45B69C",
    rating: 4.7,
    reviewCount: 560,
    followerCount: 14000,
    websiteUrl: "https://tryhappytooth.com",
    logoUrl: "/brands/happy-tooth.svg",
  },
  {
    id: "c713",
    slug: "mouthology",
    name: "Mouthology",
    tagline: "10% rod-shaped nano-hydroxyapatite toothpaste, tablets, and kids paste — fluoride-free, SLS-free",
    story: "A mouth-first studio that actually publishes the 10% nHA concentration most brands hide. Rod-shaped nano-hydroxyapatite in adult paste, chewable tablets, and kids formulas — plus oral probiotic mints and biodegradable floss. No fluoride, no SLS, no mystery dye. Enamel care with receipts.",
    location: "United States",
    founded: 2022,
    categories: ["oral"],
    accent: "#1B4F72",
    rating: 4.6,
    reviewCount: 290,
    followerCount: 6800,
    websiteUrl: "https://mouthology.com",
    logoUrl: "/brands/mouthology.svg",
  },
  {
    id: "c714",
    slug: "pureopia",
    name: "Pureopia",
    tagline: "Handmade organic tallow and calendula rescue for eczema-prone babies and sensitive skin",
    story: "A small-batch kitchen for the people who react to everything: organic tallow calendula balm, botanical body oils, mama-and-baby bundles, and lip balm with no synthetic fragrance. Tested by real moms on eczema-prone cheeks — GOTS-minded, filler-free, and safe from newborns up.",
    location: "United States",
    founded: 2022,
    categories: ["skincare"],
    accent: "#C4A484",
    rating: 4.8,
    reviewCount: 210,
    followerCount: 5600,
    websiteUrl: "https://pureopia.com",
    logoUrl: "/brands/pureopia.svg",
  },
  {
    id: "c715",
    slug: "cherokee-rose",
    name: "Cherokee Rose Organics",
    tagline: "Appalachian-trail organic moisturizers, herbal cleansers, and shampoo bars — no drugstore fog",
    story: "Skincare inspired by the Appalachian Trail and Cherokee plant wisdom: certified-organic moisturizers, chamomile cleansers, curl shampoo, and date-night shampoo bars. Cruelty-free, ethically sourced, and free of the harsh-chemical aisle — trail-minded care that still feels like a ritual.",
    location: "United States",
    founded: 2018,
    categories: ["skincare","hair"],
    accent: "#6B3E26",
    rating: 4.7,
    reviewCount: 340,
    followerCount: 7200,
    websiteUrl: "https://cherokeeroseorganics.com",
    logoUrl: "/brands/cherokee-rose.svg",
  },
  {
    id: "c716",
    slug: "bean-and-bee",
    name: "Bean and Bee",
    tagline: "PhD-formulated curly shampoo bars — palm-oil-free, silicone-free, Ecocert preserved",
    story: "A UK curl house started by a PhD biophysicist who got tired of plastic bottles and film-forming junk. Fragrance-free and lime-bergamot shampoo bars, plant-power conditioner, and curl custard — vegan, palm-oil-free, silicone-free, and packed with as many organic ingredients as the formula will hold.",
    location: "United Kingdom",
    founded: 2021,
    categories: ["hair"],
    accent: "#D4A017",
    rating: 4.8,
    reviewCount: 890,
    followerCount: 18000,
    websiteUrl: "https://www.beanandbee.co.uk",
    logoUrl: "/brands/bean-and-bee.svg",
  },
  {
    id: "c717",
    slug: "hairy-jayne",
    name: "Hairy Jayne",
    tagline: "Bristol hairdresser bars and refillable conditioner — plastic-free, vegan, no sulphate fog",
    story: "Jayne left London salons to pour hair care by hand in Bristol: fragrance-free conditioner, weekly treatment masks, refillable hair perfume, and soap bars scented with real essential oils. Plastic-free, vegan, cruelty-free — salon sense without the sulphate-and-silicone fog.",
    location: "Bristol, UK",
    founded: 2018,
    categories: ["hair","skincare"],
    accent: "#5B3A6E",
    rating: 4.8,
    reviewCount: 1100,
    followerCount: 16000,
    websiteUrl: "https://hairyjaynehandmade.co.uk",
    logoUrl: "/brands/hairy-jayne.svg",
  },
  {
    id: "c718",
    slug: "tend-prenatal",
    name: "Tend Prenatal",
    tagline: "Snackable whole-food prenatal bars — 25 earth-grown nutrients, no synthetic horse pills",
    story: "Hannah and Behzad got tired of gagging down synthetic prenatals. Tend is a real-food bar with 25 essential nutrients grown, not manufactured — strawberry patch, chocolate sea salt, peanut butter chocolate. No pills, no synthetics, no 'icks.' A prenatal you actually look forward to from preconception through postpartum.",
    location: "United States",
    founded: 2022,
    categories: ["supplements"],
    accent: "#E8A0BF",
    rating: 4.7,
    reviewCount: 480,
    followerCount: 22000,
    websiteUrl: "https://tendprenatal.com",
    logoUrl: "/brands/tend-prenatal.svg",
  },
  {
    id: "c719",
    slug: "harmony-mushroom",
    name: "Harmony Mushroom Co",
    tagline: "Jacksonville farm dual-extracts — USA fruiting bodies only, no grain-filler mycelium",
    story: "A Florida mushroom farm that grows lion's mane, cordyceps, turkey tail, chaga, and reishi, then dual-extracts them in organic cane alcohol. Fruiting bodies only — never imported grain bags passed off as mushrooms. Small-batch tinctures and a five-mushroom complex from mycologists who actually grow the crop.",
    location: "Jacksonville, FL",
    founded: 2020,
    categories: ["supplements"],
    accent: "#6B4F2A",
    rating: 4.8,
    reviewCount: 620,
    followerCount: 14000,
    websiteUrl: "https://harmonymushroom.com",
    logoUrl: "/brands/harmony-mushroom.svg",
  },
  {
    id: "c720",
    slug: "mindful-mushrooms",
    name: "Mindful Mushrooms",
    tagline: "San Diego farm tinctures and capsules — certified organic fruiting bodies, no myceliated oats",
    story: "Ivo Fedak's El Cajon farm grows lion's mane, cordyceps, and reishi under house lights, then dual-extracts them in alcohol — not the glycerol shortcut. Certified organic, third-party tested, never sourced overseas. Real mushrooms from a working San Diego farm, not a grain bag with a mushroom sticker.",
    location: "San Diego, CA",
    founded: 2019,
    categories: ["supplements"],
    accent: "#3E2723",
    rating: 4.8,
    reviewCount: 410,
    followerCount: 9800,
    websiteUrl: "https://www.mindfulmushroomstore.com",
    logoUrl: "/brands/mindful-mushrooms.svg",
  },
];
