import type { Brand } from "./types";

/** Wave 98: small organic / toxic-free brands across marketplace categories (c1457+). */
export const catalogBrandsWave98: Brand[] = [
  {
    id: "c1457",
    slug: "toothpow",
    name: "ToothPow",
    tagline: "Nine-ingredient spearmint tooth powder — kaolin and bentonite, fluoride-free",
    story:
      "The leftover unused dedicated oral house after multi-SKU n-HA shops ran out through wave4–97. Keep the Spearmint powder single. Pack count is size. Cart.js is USD. Page is a nine-ingredient essay (leave empty).",
    location: "United States",
    founded: 2021,
    categories: ["oral"],
    accent: "#3D6B5A",
    rating: 4.6,
    reviewCount: 74,
    followerCount: 980,
    websiteUrl: "https://toothpow.com",
    logoUrl: "/brands/toothpow.svg",
  },
  {
    id: "c1458",
    slug: "saltivate",
    name: "Saltivate",
    tagline: "Zero-sugar electrolytes — watermelon, mango pineapple, orange, or raw, no stevia",
    story:
      "Unused four-flavor hydration house after wave4–97. Keep the jars: Watermelon, Mango Pineapple, Orange, and Raw Unflavored. Stick counts and variety packs are size or merch. Wholesale cases, tumblers, shakers, and towels stay boxed. Cart.js is USD. Hardcode published stick-page lists onto the matching jars.",
    location: "United States",
    founded: 2022,
    categories: ["electrolytes"],
    accent: "#E07A3D",
    rating: 4.7,
    reviewCount: 186,
    followerCount: 2400,
    websiteUrl: "https://saltivate.com",
    logoUrl: "/brands/saltivate.svg",
  },
  {
    id: "c1459",
    slug: "purist-nutrition",
    name: "Purist Nutrition",
    tagline: "Grass-fed whey isolate, creatine, and hydration — no sucralose, NSF Sport tested",
    story:
      "Unused merch-heavy athlete house. Flavor expands whey Milk Chocolate / Vanilla, creatine Peach Mango / Unflavored, hydration Peach Mango / Strawberry Lemonade, and pre-workout Strawberry Lemonade / Peach Mango. Bag vs packets is size. Tees, hoodies, caps, shakers, duffels, protein bars, bundles, and $0 gifts stay boxed. Cart.js is USD. Pages are key-ingredient marketing (leave empty).",
    location: "United States",
    founded: 2021,
    categories: ["protein", "electrolytes", "supplements"],
    accent: "#1F3A4D",
    rating: 4.6,
    reviewCount: 142,
    followerCount: 3100,
    websiteUrl: "https://www.puristnutrition.com",
    logoUrl: "/brands/purist-nutrition.svg",
  },
  {
    id: "c1460",
    slug: "aussiezinc",
    name: "AussieZinc",
    tagline: "Australian organic non-nano zinc SPF50 — everyday, tinted, kids, baby, vitamin C glow",
    story:
      "Unused TGA-registered mineral sun house. Keep Everyday, Extra Sensitive, Kids, Baby, Sheer Medium Tint, and Vitamin C Daily Glow. Mozzie 2-in-1 is insect-repellent — drop. Cart.js is AUD (× 0.65). Pages are benefit-and-organic essays (leave empty).",
    location: "Australia",
    founded: 2020,
    categories: ["sunscreen"],
    accent: "#C4A35A",
    rating: 4.8,
    reviewCount: 210,
    followerCount: 2800,
    websiteUrl: "https://www.aussiezincsunscreen.com.au",
    logoUrl: "/brands/aussiezinc.svg",
  },
  {
    id: "c1461",
    slug: "lathr",
    name: "LATHR",
    tagline: "Canadian small-batch aluminum-free deodorant, tallow soap, and wash-day — baking-soda-free",
    story:
      "Leftover unused deodorant house after wave4–97. Deodorant scents already on separate titles; Scent expands Clear Glide. Keep soap bars, shampoo/conditioner singles, body butter, and tallow balm. Cologne, perfume dupes, room spray, merch, kits, bug balm, 2-paks, and soap savers stay boxed. Cart.js is CAD (× 0.73). Pages are scent-note marketing (leave empty).",
    location: "Canada",
    founded: 2018,
    categories: ["deodorant", "skincare", "hair"],
    accent: "#2C2C2C",
    rating: 4.7,
    reviewCount: 890,
    followerCount: 6200,
    websiteUrl: "https://lathr.com",
    logoUrl: "/brands/lathr.svg",
  },
  {
    id: "c1462",
    slug: "vesper-mushrooms",
    name: "Vesper Mushrooms",
    tagline: "Oregon fruiting-body double extracts — lion's mane, reishi, chaga, cordyceps, turkey tail",
    story:
      "Leftover unused Oregon extract house after wave4–97. Keep single-mushroom extracts, alcohol-free glycerites, Gold Metal / Pink Freud / Gray Matter blends, and retail DerMush face/body cream. 4 oz vs 8 oz body cream is size. Bundles, Spour coffee/matcha/chai, merch, posters, wholesale, and gift cards stay boxed. Cart.js is USD. Hardcode published extract lists.",
    location: "Oregon, USA",
    founded: 2019,
    categories: ["supplements", "skincare"],
    accent: "#4A3B2A",
    rating: 4.8,
    reviewCount: 164,
    followerCount: 2200,
    websiteUrl: "https://vespermushrooms.com",
    logoUrl: "/brands/vesper-mushrooms.svg",
  }
];
