import type { Brand } from "./types";

/** Wave 61: small organic / toxic-free brands across marketplace categories (c1235+). */
export const catalogBrandsWave61: Brand[] = [
  {
    id: "c1235",
    slug: "sea-summit",
    name: "Sea & Summit",
    tagline: "California lifeguard-born mineral zinc sticks and lotion — reef-minded, plastic-light",
    story: "Ryan Kell started Sea & Summit after working as a California lifeguard and Channel Islands marine guide who wanted non-nano zinc that stays put and skips reef-harming filters. The Athlete's SPF 50 stick, Daily Clear SPF 36 stick, and SPF 50 lotion stay. There is no merch aisle and no flavor tree — size is not a scent.",
    location: "California, United States",
    founded: 2018,
    categories: ["sunscreen"],
    accent: "#1F5C6B",
    rating: 4.6,
    reviewCount: 86,
    followerCount: 2400,
    websiteUrl: "https://seaandsummitsunscreen.com",
    logoUrl: "/brands/sea-summit.svg",
  },
  {
    id: "c1236",
    slug: "mastermedi",
    name: "MasterMedi",
    tagline: "10% n-HA mint toothpaste and chewable tablets — fluoride-free, PAP + xylitol",
    story: "A small US oral house that publishes a 10% nano-hydroxyapatite dose in Clean Mint paste and chewable tablets, then pairs it with copper and stainless scrapers. Individual toothpaste, tablets, and scrapers stay. Pack count is size, not a flavor. Whitening strips, electric brushes, UV water flossers, instrument kits, and zinc-oxide dental cement stay boxed.",
    location: "United States",
    founded: 2023,
    categories: ["oral"],
    accent: "#2B4C3E",
    rating: 4.5,
    reviewCount: 64,
    followerCount: 1800,
    websiteUrl: "https://mastermedi.co",
    logoUrl: "/brands/mastermedi.svg",
  },
  {
    id: "c1237",
    slug: "tandlers-tallow",
    name: "Tandler's Tallow",
    tagline: "Veteran-owned grass-fed tallow soaps, deodorant, shampoo bars, and mineral sun balm",
    story: "Jessica Tandler's veteran-owned American tallow house pours grass-fed moisturizer, body balm, aluminum-free deodorant, shampoo bars, and a mineral sun balm for people who actually work outside. Individual soaps, whipped-moisturizer scents, body-balm scents, shampoo-bar scents, liquid-soap scents, deodorant, and sun balm stay. Size is not a flavor. Bundles, five-packs, kits, tees, candles, beeswax wraps, and soap dishes stay boxed.",
    location: "United States",
    founded: 2022,
    categories: ["skincare","deodorant","hair","sunscreen"],
    accent: "#6B4A2B",
    rating: 4.7,
    reviewCount: 112,
    followerCount: 2100,
    websiteUrl: "https://tandlerstallow.com",
    logoUrl: "/brands/tandlers-tallow.svg",
  },
  {
    id: "c1238",
    slug: "gotpwr",
    name: "GotPwr",
    tagline: "One-SKU US goat whey isolate — 27g protein, gut-friendly, vanilla tub",
    story: "A fifth-generation goat-whey house packing pasture-raised goat isolate into a single two-pound vanilla tub. Goat milk is closer to human milk than cow whey, so the powder is built for people who want 27g of protein without the usual bloat. The vanilla tub stays. There is no merch aisle and no flavor-option tree.",
    location: "United States",
    founded: 2021,
    categories: ["protein"],
    accent: "#8A6A2F",
    rating: 4.5,
    reviewCount: 48,
    followerCount: 900,
    websiteUrl: "https://goatswhey.com",
    logoUrl: "/brands/gotpwr.svg",
  },
  {
    id: "c1239",
    slug: "plain-jane-tallow",
    name: "Plain Jane Tallow",
    tagline: "Farm-kitchen tallow balms, three-ingredient soaps, and Field Day zinc sun balm",
    story: "A small farm-kitchen tallow house that keeps the formula short: grass-fed tallow, lard, and a zinc Field Day sun balm. Individual balms, named soap bars, Fat Kiss lip, and the mineral sun balm stay. The Farmer's Lot set, Working Skincare bundle, Fat Kiss bundle, and dog shampoo stay boxed.",
    location: "United States",
    founded: 2021,
    categories: ["skincare","sunscreen"],
    accent: "#7A5A3A",
    rating: 4.6,
    reviewCount: 74,
    followerCount: 1600,
    websiteUrl: "https://plainjanetallow.com",
    logoUrl: "/brands/plain-jane-tallow.svg",
  },
  {
    id: "c1240",
    slug: "primal-glow",
    name: "Primal Glow",
    tagline: "Dutch tallow balms, SPF 50 zinc sun balm, and remineralizing tooth powder",
    story: "A small Dutch ancestral shop whipping tallow-and-honey balms, a tallow-and-zinc SPF 50 sun balm, Aleppo soap, and a mint or mint-free remineralizing tooth powder. Individual balms, sun-balm scents, soap scents, tooth-powder flavors, and lip stay. Jar size is not a flavor. Towels, soap dishes, bath salts, and horsehair brushes stay boxed. EUR prices convert to USD.",
    location: "Netherlands",
    founded: 2022,
    categories: ["skincare","sunscreen","oral"],
    accent: "#4A6741",
    rating: 4.6,
    reviewCount: 38,
    followerCount: 1100,
    websiteUrl: "https://primalglowcosmetics.com",
    logoUrl: "/brands/primal-glow.svg",
  },
  {
    id: "c1241",
    slug: "arizona-mushroom",
    name: "Arizona Mushroom Company",
    tagline: "Arizona-grown fruiting-body lion's mane and chaga tinctures plus Muddy Waterz",
    story: "A small Arizona grower dual-extracting its own cultivated lion's mane and chaga fruiting bodies, plus a Daily Dose blend and Muddy Waterz mushroom coffee alternative. Individual tinctures, chaga powder, Daily Dose, and Muddy Waterz stay. Umami seasonings and sun-dried culinary mushroom powders stay boxed.",
    location: "Arizona, United States",
    founded: 2020,
    categories: ["supplements"],
    accent: "#5B3A1F",
    rating: 4.5,
    reviewCount: 42,
    followerCount: 1300,
    websiteUrl: "https://arizona-mushroom-company.myshopify.com",
    logoUrl: "/brands/arizona-mushroom.svg",
  },
];
