import type { Brand } from "./types";

/** Wave 39: small organic / toxic-free brands across marketplace categories (c1060+). */
export const catalogBrandsWave39: Brand[] = [
  {
    id: "c1060",
    slug: "seaker-sun",
    name: "Seaker Sun Co",
    tagline: "Laguna Beach four-ingredient zinc sun balm — no chemical filters, no merch",
    story: "A 2026 Laguna Beach house that pours non-nano zinc oxide, beeswax, jojoba, and vitamin E into one tin instead of a 30-ingredient chemical-filter aisle. The two-pack stays as a size option. No merch, no self-tanner, no empty bottles.",
    location: "Laguna Beach, California",
    founded: 2026,
    categories: ["sunscreen"],
    accent: "#1B6B6B",
    rating: 4.6,
    reviewCount: 48,
    followerCount: 900,
    websiteUrl: "https://seakersunco.com",
    logoUrl: "/brands/seaker-sun.svg",
  },
  {
    id: "c1061",
    slug: "sunmud",
    name: "SUNMUD",
    tagline: "Reef-safe tinted mineral sport sticks and after-sun serum — shade variants, no bundle wall",
    story: "A performance mineral house that pours Hawaii-reef-act-compliant non-nano zinc into tinted sport sticks, travel tins, and a solar repair serum instead of an oxybenzone spray aisle. Ivory, Sahara, Terra, and Ebony stay as their own listings. Safari collabs, mixed samples, and merch bundles stay out.",
    location: "United States",
    founded: 2021,
    categories: ["sunscreen","skincare"],
    accent: "#C45C26",
    rating: 4.7,
    reviewCount: 640,
    followerCount: 9800,
    websiteUrl: "https://sunmudsunscreen.com",
    logoUrl: "/brands/sunmud.svg",
  },
  {
    id: "c1062",
    slug: "be-blessed",
    name: "Be Blessed Skincare",
    tagline: "Esthetician-made mineral SPF 50 plus short-list cleansers and serums — no wholesale candle shop",
    story: "A small clinical kitchen that folds sheer and tinted mineral SPF 50 beside green-tea cleanser, drench essence, and chaga barrier cream instead of a chemical-filter wall. Individual formulas stay. Wholesale soy candles, instruction-card packs, essential-oil blends, and $300+ kit walls stay out.",
    location: "United States",
    founded: 2018,
    categories: ["sunscreen","skincare"],
    accent: "#6B4F2A",
    rating: 4.6,
    reviewCount: 320,
    followerCount: 5400,
    websiteUrl: "https://beblessedskincare.com",
    logoUrl: "/brands/be-blessed.svg",
  },
  {
    id: "c1063",
    slug: "seaonic",
    name: "SEAONIC",
    tagline: "One-ingredient cold-filtered marine plasma sachets — hypertonic and isotonic, no drink-mix dyes",
    story: "A Bay of Biscay marine house that cold-microfilters deep seawater into plastic-free sachets instead of a maltodextrin-and-stevia tub. Hypertonic, isotonic, and the duo stay as their own listings. No neon drink mixes, no merch.",
    location: "France / DTC",
    founded: 2022,
    categories: ["electrolytes"],
    accent: "#1F4E79",
    rating: 4.6,
    reviewCount: 180,
    followerCount: 3100,
    websiteUrl: "https://seaonic.com",
    logoUrl: "/brands/seaonic.svg",
  },
  {
    id: "c1064",
    slug: "ion-electrolytes",
    name: "ION",
    tagline: "One-SKU clean electrolyte packets — no sugar dyes, no merch",
    story: "A one-formula hydration house that keeps a single clean electrolyte packet instead of a neon-sugar drink-mix wall. Pack-size options stay on one listing. No shakers, no merch, no pre-workout.",
    location: "United States",
    founded: 2024,
    categories: ["electrolytes"],
    accent: "#2C5F4E",
    rating: 4.5,
    reviewCount: 90,
    followerCount: 1600,
    websiteUrl: "https://drinkion.com",
    logoUrl: "/brands/ion-electrolytes.svg",
  },
  {
    id: "c1065",
    slug: "aus-natural-protein",
    name: "Australian Natural Protein Company",
    tagline: "Victorian grass-fed whey — signature, vanilla bean, and artisan cocoa, no hoodie shop",
    story: "A Victoria, Australia whey kitchen that keeps single-ingredient native grass-fed concentrate plus vanilla-bean and artisan-cocoa tubs instead of a gum-and-artificial-sweetener wall. Each flavor stays as its own listing. 5kg warehouse bags, steel shakers, and merch scoops stay out. AUD prices convert to USD.",
    location: "Victoria, Australia",
    founded: 2016,
    categories: ["protein"],
    accent: "#5C4033",
    rating: 4.7,
    reviewCount: 860,
    followerCount: 12000,
    websiteUrl: "https://ausnaturalprotein.com",
    logoUrl: "/brands/aus-natural-protein.svg",
  },
  {
    id: "c1066",
    slug: "perfect-deodorant",
    name: "Perfect Deodorant",
    tagline: "Four-ingredient unscented cream deodorant — no aluminum, no fragrance wall",
    story: "A founder-made cream deodorant that keeps four clean ingredients in a jar instead of an aluminum-and-synthetic-fragrance stick wall. Single, two-pack, and three-pack stay. No merch, no perfume oils.",
    location: "United States",
    founded: 2025,
    categories: ["deodorant"],
    accent: "#4A6741",
    rating: 4.6,
    reviewCount: 70,
    followerCount: 1200,
    websiteUrl: "https://perfectdeodorant.shop",
    logoUrl: "/brands/perfect-deodorant.svg",
  },
  {
    id: "c1067",
    slug: "boeuf-tallow",
    name: "Bœuf",
    tagline: "Vancouver Island grass-fed tallow whips — citrus-vanilla and cacao-vanilla, no merch",
    story: "A Vancouver Island kitchen that dry-renders local grass-fed suet into all-over and face whips with sea buckthorn and rosehip instead of a 40-ingredient lotion wall. Citrus-vanilla and cacao-vanilla stay as their own listings. CAD prices convert to USD. No merch, no empty tins.",
    location: "Vancouver Island, British Columbia",
    founded: 2023,
    categories: ["skincare"],
    accent: "#6B3E26",
    rating: 4.7,
    reviewCount: 150,
    followerCount: 2800,
    websiteUrl: "https://boeuftallow.com",
    logoUrl: "/brands/boeuf-tallow.svg",
  },
  {
    id: "c1068",
    slug: "superteeth",
    name: "SuperTeeth",
    tagline: "Hydroxyapatite prebiotic toothpaste, floss, and oral probiotics — mint and strawberry, no ebook shop",
    story: "A family oral house that folds micro- and nano-hydroxyapatite plus prebiotics into mint, mild mint, strawberry, and whitening pastes instead of a fluoride-and-SLS wall. Soft floss and dental probiotics stay. Oral-health ebooks and gadget kits stay out.",
    location: "United States",
    founded: 2019,
    categories: ["oral"],
    accent: "#1B4F72",
    rating: 4.6,
    reviewCount: 2100,
    followerCount: 24000,
    websiteUrl: "https://getsuperteeth.com",
    logoUrl: "/brands/superteeth.svg",
  },
  {
    id: "c1069",
    slug: "freo-living",
    name: "Freo Living",
    tagline: "Calgary-made shampoo bars, pit-stop deodorant, and lotion — scent variants, no bundle wall",
    story: "A woman-owned Calgary workshop that pours plant-powered shampoo and conditioner bars, a magnesium pit-stop deodorant, and unscented or vanilla-sandalwood lotion instead of a sulfate-bottle wall. Each scent stays as its own listing. Body bundles stay out. CAD prices convert to USD.",
    location: "Calgary, Alberta",
    founded: 2021,
    categories: ["hair","deodorant","skincare"],
    accent: "#2E7D32",
    rating: 4.7,
    reviewCount: 280,
    followerCount: 4600,
    websiteUrl: "https://freoliving.com",
    logoUrl: "/brands/freo-living.svg",
  },
  {
    id: "c1070",
    slug: "texas-tallow",
    name: "Texas Tallow",
    tagline: "Texas-made grass-fed tallow salves, whips, and honey-oat soaps — scent variants, no merch",
    story: "A Texas homestead kitchen that renders grass-fed tallow into restore salves, elderflower-rose luxury whip, and honey-oat soap instead of a petroleum-jelly wall. Soap scents and herbal cleansing blends stay as their own listings. This is a different house from claimed Texas Tallow Products. No merch, no empty tins.",
    location: "Texas, United States",
    founded: 2021,
    categories: ["skincare","hair"],
    accent: "#8B5A2B",
    rating: 4.7,
    reviewCount: 210,
    followerCount: 3900,
    websiteUrl: "https://texastallow.com",
    logoUrl: "/brands/texas-tallow.svg",
  },
  {
    id: "c1071",
    slug: "pasture-skincare",
    name: "Pasture Skincare",
    tagline: "One-SKU organic beef tallow moisturiser — no merch, no fragrance wall",
    story: "A one-formula tallow house that keeps a single organic beef tallow moisturiser instead of a 20-step serum wall. Size options stay on one listing. No merch, no candles, no pantry jars.",
    location: "United Kingdom",
    founded: 2024,
    categories: ["skincare"],
    accent: "#5C4033",
    rating: 4.5,
    reviewCount: 36,
    followerCount: 640,
    websiteUrl: "https://pastureskincare.com",
    logoUrl: "/brands/pasture-skincare.svg",
  },
  {
    id: "c1072",
    slug: "tallow-and-me",
    name: "Tallow and Me",
    tagline: "Chile-made tallow shampoo bars, cacao conditioner, and botanica body butter — no merch",
    story: "A small Chilean tallow kitchen that pours tea-tree eucalyptus shampoo bars, cacao conditioner, a natural deodorant stick, and calendula or botanica body butter instead of a sulfate-and-aluminum wall. Infusion variants stay as their own listings. CLP prices convert to USD. No merch.",
    location: "Chile",
    founded: 2023,
    categories: ["hair","deodorant","skincare"],
    accent: "#4A6741",
    rating: 4.6,
    reviewCount: 80,
    followerCount: 1400,
    websiteUrl: "https://tallowandme.com",
    logoUrl: "/brands/tallow-and-me.svg",
  },
  {
    id: "c1073",
    slug: "noble-mushrooms",
    name: "Noble Mushrooms",
    tagline: "New Jersey farm dual-extract tinctures — lion's mane, reishi, cordyceps, no grow-kit shop",
    story: "A New Jersey organic mycology lab that grows and extracts lion's mane, reishi, cordyceps, turkey tail, shiitake, and blue oyster in-house instead of a mycelium-on-grain capsule wall. Tinctures stay. Workshops, CSA shares, spawn, and fresh culinary boxes stay on the farm.",
    location: "New Jersey, United States",
    founded: 2021,
    categories: ["supplements"],
    accent: "#3D5A3A",
    rating: 4.7,
    reviewCount: 160,
    followerCount: 2900,
    websiteUrl: "https://noblemushrooms.com",
    logoUrl: "/brands/noble-mushrooms.svg",
  },
  {
    id: "c1074",
    slug: "sunshine-fungi",
    name: "Sunshine Fungi",
    tagline: "Sarasota farm dual extracts and lion's mane powder — no jerky, no spawn bags",
    story: "A family Sarasota farm that dual-extracts lion's mane, reishi, cordyceps, and turkey tail and mills lion's mane powder instead of a grow-kit-and-jerky wall. Extracts and functional powders stay. Fresh culinary boxes, jerky, grain spawn, and liquid culture stay out.",
    location: "Sarasota, Florida",
    founded: 2020,
    categories: ["supplements"],
    accent: "#C45C26",
    rating: 4.6,
    reviewCount: 120,
    followerCount: 2200,
    websiteUrl: "https://sunshinefungifarms.com",
    logoUrl: "/brands/sunshine-fungi.svg",
  },
  {
    id: "c1075",
    slug: "mycoterra",
    name: "Mycoterra Farm",
    tagline: "Organic fruiting-body tinctures plus lion's mane skin toner — no workshop or compost shop",
    story: "A certified-organic mushroom farm that triple-extracts lion's mane, reishi, chaga, cordyceps, maitake, and turkey tail and folds lion's mane into a skin toner instead of a book-and-grow-kit wall. Tinctures and toners stay. Workshops, CSA memberships, spawn plugs, and farm-pickup fresh cases stay out.",
    location: "United States",
    founded: 2016,
    categories: ["supplements","skincare"],
    accent: "#2C5F4E",
    rating: 4.7,
    reviewCount: 340,
    followerCount: 6100,
    websiteUrl: "https://shop.mycoterrafarm.com",
    logoUrl: "/brands/mycoterra.svg",
  },
  {
    id: "c1076",
    slug: "shroomery-nm",
    name: "The Shroomery NM",
    tagline: "New Mexico fruiting-body tinctures — lion's mane, cordyceps, reishi, no tea aisle",
    story: "A New Mexico grower that dual-extracts fruiting-body lion's mane, cordyceps, and reishi instead of a mycelium-on-oats capsule wall. Tinctures stay. Loose-leaf tea blends and glass infusers stay in the pantry.",
    location: "New Mexico, United States",
    founded: 2022,
    categories: ["supplements"],
    accent: "#5C4033",
    rating: 4.6,
    reviewCount: 70,
    followerCount: 1300,
    websiteUrl: "https://theshroomerynm.com",
    logoUrl: "/brands/shroomery-nm.svg",
  },
];
