import type { Brand } from "./types";

/** Wave 108: small organic / toxic-free brands across marketplace categories (c1517+). */
export const catalogBrandsWave108: Brand[] = [
  {
    id: "c1517",
    slug: "shwally-home",
    name: "Shwally",
    tagline: "30% hydroxyapatite toothpaste, zinc-charcoal tallow deodorant, avocado mineral sunbalm",
    story:
      "Shwally started under the Southern California sun because the family paste still hid water and a preservative, and the sunscreen still hid a chemical filter. The toothpaste is 30% hydroxyapatite — Cooling Mint, Mild Mint + Tulsi, Tahitian Vanilla Bean — already on the flavor option, no 3-pack. A cattle-bone and eggshell tooth powder. A peppermint coconut rinse. A black-seed pulling oil. The deodorant is grass-fed tallow with zinc and charcoal — Eucalyptus + Peppermint or unscented — already on the scent option. The SunBalm is four edible ingredients: tallow, avocado oil, beeswax, non-nano zinc. No playmat, no picnic blanket, no SpectrumView monitor: the tin you actually open.",
    location: "Southern California",
    founded: 2021,
    categories: ["oral", "deodorant", "sunscreen", "skincare"],
    accent: "#6B4A2A",
    rating: 4.7,
    reviewCount: 620,
    followerCount: 8900,
    websiteUrl: "https://shwallyhome.com",
    logoUrl: "/brands/shwally-home.svg",
  },
  {
    id: "c1518",
    slug: "kona-hydration",
    name: "Kona Hydration",
    tagline: "Hawaiian salt, Himalayan pink salt, coconut water — zero sugar, Watermelon or Pineapple",
    story:
      "Kona Hydration was mixed for heat, not for a flavor lab. Five hundred milligrams of sodium, two hundred of potassium, sixty of magnesium — Hawaiian sea salt, Himalayan pink salt, and coconut water powder, zero sugar. Watermelon. Pineapple. Already on the flavor option. Eight sticks, not the combo pack: the stick you tear for the bottle.",
    location: "Hawaii, United States",
    founded: 2023,
    categories: ["electrolytes"],
    accent: "#1F6B6B",
    rating: 4.6,
    reviewCount: 180,
    followerCount: 2400,
    websiteUrl: "https://konahydration.com",
    logoUrl: "/brands/kona-hydration.svg",
  },
  {
    id: "c1519",
    slug: "elevate-organic",
    name: "Elevate Organic",
    tagline: "Organic regenerative grass-fed whey — Chocolate or Vanilla, plus a plant pouch",
    story:
      "Elevate Organic starts in the soil: regenerative, organic, grass-fed A2 whey, then a plant pouch if dairy is not the day. Chocolate or Vanilla — already on the flavor option. A men's tub and a women's tub, eighteen servings, no glyphosate-detox aisle, no gummy, no 10-day gut reset: the bags you scoop.",
    location: "United States",
    founded: 2022,
    categories: ["protein"],
    accent: "#3D5A2A",
    rating: 4.6,
    reviewCount: 410,
    followerCount: 7200,
    websiteUrl: "https://elevateorganic.com",
    logoUrl: "/brands/elevate-organic.svg",
  },
  {
    id: "c1520",
    slug: "2-sisters-pure-goods",
    name: "2 Sisters Pure Goods",
    tagline: "Tallow mineral sun cream, dry shampoo for light or dark hair, lamb-tallow lip nectar",
    story:
      "Two sisters got tired of a lotion that still read like a lab. 2 Sisters Pure Goods is the tallow they poured instead: a mineral sun cream with non-nano zinc as the only filter, a dry shampoo powder for light or dark hair, a lamb-tallow lip in clear or beet tint, an orange-lavender or lemongrass-bergamot lotion, a tea-tree charcoal soap. No pet balm, no 128-ounce massage drum: the jars they still make.",
    location: "United States",
    founded: 2020,
    categories: ["sunscreen", "skincare", "hair"],
    accent: "#7A5A38",
    rating: 4.8,
    reviewCount: 290,
    followerCount: 4100,
    websiteUrl: "https://2sisterspuregoods.com",
    logoUrl: "/brands/2-sisters-pure-goods.svg",
  },
  {
    id: "c1521",
    slug: "powdr",
    name: "POWDR",
    tagline: "Coconut-water electrolytes, grass-fed whey, unflavored collagen peptides — rip, swirl, sip",
    story:
      "POWDR is the packet you rip on a counter, not a tub with a scoop mystery. Electrolyte Hydration is organic coconut water, pink Himalayan salt, and ConcenTrace minerals — LemonBerry Twist already on the title. A grass-fed whey. Unflavored collagen peptides. A cocoa collagen shake. No $0 glass bottle, no glow bundle, no hydration-plus-recovery stack: the packets you actually tear.",
    location: "United States",
    founded: 2023,
    categories: ["electrolytes", "protein", "supplements"],
    accent: "#2A4A6B",
    rating: 4.5,
    reviewCount: 156,
    followerCount: 2800,
    websiteUrl: "https://drinkpowdr.com",
    logoUrl: "/brands/powdr.svg",
  },
  {
    id: "c1522",
    slug: "bloomcap-naturals",
    name: "Bloomcap Naturals",
    tagline: "Organic fruiting-body Lion's Mane and Reishi — powder or dual-extract tincture, no grain filler",
    story:
      "Bloomcap Naturals bottles the fruiting body, not the grain it grew on. Lion's Mane as a powder and a dual-extract tincture. Reishi the same way. Single-batch harvest, organic, two ounces in the dropper. No starter kit, no mushroom chocolate, no greeting card: the powder or the tincture you actually take.",
    location: "United States",
    founded: 2024,
    categories: ["supplements"],
    accent: "#3A4A28",
    rating: 4.7,
    reviewCount: 88,
    followerCount: 1600,
    websiteUrl: "https://bloomcapnaturals.com",
    logoUrl: "/brands/bloomcap-naturals.svg",
  },
];
