import type { Brand } from "./types";

/** Wave 105: small organic / toxic-free brands across marketplace categories (c1499+). */
export const catalogBrandsWave105: Brand[] = [
  {
    id: "c1499",
    slug: "akamai",
    name: "Akamai",
    tagline: "Boulder mineral toothpowder — refill jars, oil pulling, clay deodorant, no fluoride tube",
    story:
      "Vincent and Marni left the Midwest for Boulder with one stubborn idea: personal care did not need a 12-step shelf of synthetics. Akamai is the refill-jar ritual they built — mineral toothpowder (original, essential-oil-free, and kids), oil-pulling mouthwash, infused black or silk floss, a tongue cleaner, and a bamboo bass brush. Plus a clay mineral deodorant, dry shampoo, Skin Fuel, and a 3-in-1 bar. No kits, no razors, no empty travel jars: the powders that live by the sink.",
    location: "Boulder, CO",
    founded: 2016,
    categories: ["oral", "deodorant", "hair", "skincare"],
    accent: "#3D5A4C",
    rating: 4.7,
    reviewCount: 1680,
    followerCount: 12400,
    websiteUrl: "https://akamaibasics.com",
    logoUrl: "/brands/akamai.png",
  },
  {
    id: "c1500",
    slug: "cure-hydration",
    name: "Cure Hydration",
    tagline: "NYC plant-based ORS sticks — coconut water, pink Himalayan salt, real fruit, no added sugar",
    story:
      "Lauren was training for a triathlon and every sports-drink stick tasted like a chemistry set. With Alex she built Cure in New York around the WHO oral-rehydration idea — coconut water, pink Himalayan salt, and real fruit, no added sugar. Lemonade, lime, watermelon, peach mango, berry pomegranate, ginger turmeric, and a dozen more title flavors. Stick count is size. No hats, no frothers, no sample sticks: the packets you actually tear open.",
    location: "New York, NY",
    founded: 2018,
    categories: ["electrolytes"],
    accent: "#E07A5F",
    rating: 4.6,
    reviewCount: 8420,
    followerCount: 48000,
    websiteUrl: "https://www.curehydration.com",
    logoUrl: "/brands/cure-hydration.svg",
  },
  {
    id: "c1501",
    slug: "mindful-crumb",
    name: "Mindful Crumb",
    tagline: "Porto one-ingredient grass-fed whey — Primal Core, unflavoured, no gums or sweetener",
    story:
      "William kept opening European whey bags that still hid ten ingredients behind 'clean.' Mindful Crumb is the Porto answer: Primal Core, a single-ingredient grass-fed whey concentrate from EU pasture milk, bagged in 450 g with nothing but whey. Unflavoured. No gums, no stevia, no 'natural flavour.' The brioche and protein balls stay in the bakery. This shelf is the pouch you scoop.",
    location: "Porto, Portugal",
    founded: 2024,
    categories: ["protein"],
    accent: "#6B4F3A",
    rating: 4.7,
    reviewCount: 86,
    followerCount: 2100,
    websiteUrl: "https://www.mindfulcrumb.com",
    logoUrl: "/brands/mindful-crumb.svg",
  },
  {
    id: "c1502",
    slug: "aelia-sun",
    name: "AELIA",
    tagline: "Denver pilot-built mineral SPF 50 — non-nano zinc, soft-matte, built for altitude",
    story:
      "Kayla flies a Boeing 777. At 35,000 feet the UV is harder and the cabin air is drier than the Sahara, and every sunscreen she packed either greases the yoke or smells like a melted piña colada. AELIA is the one-SKU mineral SPF 50 she mixed for the flight deck and then brought back to the ground in Denver: non-nano zinc, a soft-matte finish, fragrance-free. No second bottle. One formula for skin that actually lives outside — and above the clouds.",
    location: "Denver, CO",
    founded: 2023,
    categories: ["sunscreen"],
    accent: "#1B4F72",
    rating: 4.8,
    reviewCount: 64,
    followerCount: 1800,
    websiteUrl: "https://aeliasun.com",
    logoUrl: "/brands/aelia-sun.svg",
  },
  {
    id: "c1503",
    slug: "wild-crafted-kitchen",
    name: "Wild Crafted Kitchen",
    tagline: "Big Lake homestead tallow — aluminum-free deodorant, zinc sun balm, whipped butters Megan renders herself",
    story:
      "Megan started rendering suet from the family's steers in a Big Lake, Minnesota kitchen because every 'clean' cream still left her skin tight. Wild Crafted Kitchen is the homestead line that followed: grass-fed, hormone-free tallow dry-rendered in-house, never outsourced. Aluminum-free deodorant in lavender tea tree, bergamot lime, coconut lime, and unscented. A zinc tallow sun balm, whipped butters, lotions, lip balms, a shampoo-adjacent scalp oil, and a beard balm. No dish soap, no wood conditioner, no paw balm: the jars she still pours by hand.",
    location: "Big Lake, MN",
    founded: 2025,
    categories: ["deodorant", "skincare", "hair", "sunscreen"],
    accent: "#7A5C3A",
    rating: 4.8,
    reviewCount: 210,
    followerCount: 3400,
    websiteUrl: "https://wildcraftedkitchenmn.myshopify.com",
    logoUrl: "/brands/wild-crafted-kitchen.svg",
  },
  {
    id: "c1504",
    slug: "arbor-spring-farms",
    name: "Arbor Spring Farms",
    tagline: "Michigan farm Lion's Mane — fruiting-body tincture and powder, grown on the farm, no coffee",
    story:
      "Arbor Spring grows the Lion's Mane they bottle. Michigan soil, no imports, no mycelium-on-grain. A dual-extracted tincture for the people who want a dropper, and a fruiting-body powder for the people who want a scoop. Born-on dated. No mushroom coffee, no grow kit, no café blend. Two SKUs from the mushrooms they actually grew.",
    location: "Michigan",
    founded: 2022,
    categories: ["supplements"],
    accent: "#3A4F3A",
    rating: 4.7,
    reviewCount: 128,
    followerCount: 2600,
    websiteUrl: "https://arborspringfarms.com",
    logoUrl: "/brands/arbor-spring-farms.svg",
  },
];
