import type { Brand } from "./types";

/** Wave 44: small organic / toxic-free brands across marketplace categories (c1118+). */
export const catalogBrandsWave44: Brand[] = [
  {
    id: "c1118",
    slug: "primal-basics",
    name: "Primal Basics",
    tagline: "10% nano-hydroxyapatite toothpaste plus a short-list tallow kitchen",
    story: "A small U.S. oral-and-tallow house that puts a researched 10% nano-hydroxyapatite Sweet Mint paste on the brush, then keeps grass-fed lip balm, whipped tallow scents, and two clean serums instead of a fluoride-and-SLS aisle. Individual formulas stay. No merch wall.",
    location: "United States",
    founded: 2023,
    categories: ["oral","skincare"],
    accent: "#2C6E49",
    rating: 4.7,
    reviewCount: 86,
    followerCount: 1900,
    websiteUrl: "https://theprimalbasics.com",
    logoUrl: "/brands/primal-basics.svg",
  },
  {
    id: "c1119",
    slug: "sun-zapper",
    name: "Sun Zapper",
    tagline: "Non-nano zinc mineral lotions and colored surf sticks — no apparel aisle",
    story: "An unused mineral-SPF house built around non-nano zinc oxide: reef-safe pumps, kids and baby lotions, tinted face tubes, and colored zinc sticks for real outdoor days. Individual formulas stay. Beauty contour kits, mosquito-citronella hybrids, sample trials, and value multipacks stay out.",
    location: "United States / Australia",
    founded: 2014,
    categories: ["sunscreen"],
    accent: "#E07A3D",
    rating: 4.6,
    reviewCount: 420,
    followerCount: 8900,
    websiteUrl: "https://sunzapper.us",
    logoUrl: "/brands/sun-zapper.svg",
  },
  {
    id: "c1120",
    slug: "reef-safe-australia",
    name: "Reef Safe Australia",
    tagline: "Brisbane-made non-nano zinc SPF 50 — face and surf tubes only",
    story: "A Brisbane mineral house that uses Australian solar-made ZinClear non-nano zinc and skips chemical UV filters. Keep the 100g face and surf/snorkel tubes. Warehouse 1–2kg jugs and the mosquito-barrier hybrid stay out. AUD prices convert to USD.",
    location: "Brisbane, Australia",
    founded: 2021,
    categories: ["sunscreen"],
    accent: "#1B6B7A",
    rating: 4.7,
    reviewCount: 64,
    followerCount: 1400,
    websiteUrl: "https://www.reefsafeaustralia.com",
    logoUrl: "/brands/reef-safe-australia.svg",
  },
  {
    id: "c1121",
    slug: "thallo",
    name: "Thallo",
    tagline: "Tallow + zinc outdoor stick plus whipped ancestral balms",
    story: "A short-list tallow house: a zinc outdoor stick, whipped vanilla balm, manuka-chamomile body balm, intensive balm, and a milky oil cleanser. The copper-peptide serum stays out with the GHK-Cu shop. No merch.",
    location: "United States",
    founded: 2023,
    categories: ["sunscreen","skincare"],
    accent: "#8B5A2B",
    rating: 4.6,
    reviewCount: 51,
    followerCount: 1100,
    websiteUrl: "https://thalloskin.com",
    logoUrl: "/brands/thallo.svg",
  },
  {
    id: "c1122",
    slug: "naturalcare-nz",
    name: "NaturalCare",
    tagline: "Christchurch rice-water shampoo bars — plastic-free, no caddy wall",
    story: "A Christchurch kitchen that hand-pours rice-water, growth, purple-toning, and men's shampoo and conditioner bars, plus a leave-in bar, hair oil, serum, tallow balms, and soaps. Individual formulas stay. Combos, bundles, soap dishes, caddies, combs, brushes, massagers, and bar tins stay out. NZD prices convert to USD.",
    location: "Christchurch, New Zealand",
    founded: 2024,
    categories: ["hair","skincare"],
    accent: "#4A6741",
    rating: 4.8,
    reviewCount: 4100,
    followerCount: 12000,
    websiteUrl: "https://www.naturalcare.co.nz",
    logoUrl: "/brands/naturalcare-nz.svg",
  },
  {
    id: "c1123",
    slug: "stone-and-spear",
    name: "Stone & Spear",
    tagline: "Las Vegas tallow sun balm, deodorant scents, shampoo bars, tooth powder",
    story: "A Las Vegas tallow kitchen that keeps a zinc sun balm in coconut/cacao/unscented, aluminum-free deodorant scents, shampoo and conditioner bars, tooth powder flavors, soaps, and facial care instead of a makeup-and-candle shop. Individual formulas stay. Eyeshadow, lipstick, blush, perfume, cologne, hats, candles, discovery kits, and bug balm stay out.",
    location: "Las Vegas, Nevada",
    founded: 2022,
    categories: ["sunscreen","deodorant","hair","skincare","oral"],
    accent: "#6B4F2A",
    rating: 4.7,
    reviewCount: 180,
    followerCount: 4200,
    websiteUrl: "https://stoneandspear.co",
    logoUrl: "/brands/stone-and-spear.svg",
  },
  {
    id: "c1124",
    slug: "friendly-soap",
    name: "Friendly Soap",
    tagline: "UK cold-process shampoo and soap bars — no scrap bins or 126-packs",
    story: "A Yorkshire handmade house that cold-processes palm-free shampoo bars, shea cleansing bars, and short-list soap scents without SLS or parabens. Individual bars stay. Soapy scraps, 3–126 packs, totes, laundry powder, kitchen bars, dog shampoo, loofahs, soap racks, and toilet rolls stay in the warehouse. GBP prices convert to USD.",
    location: "United Kingdom",
    founded: 2011,
    categories: ["hair","skincare"],
    accent: "#2F6F5E",
    rating: 4.8,
    reviewCount: 3200,
    followerCount: 18000,
    websiteUrl: "https://friendlysoap.co.uk",
    logoUrl: "/brands/friendly-soap.svg",
  },
  {
    id: "c1125",
    slug: "good-intentions",
    name: "Good Intentions",
    tagline: "Sugar-free electrolyte powders — strawberry lemonade and raspberry, no tee wall",
    story: "A small hydration house that keeps sugar-free electrolyte flavors, unflavored and no-sodium tubs, fasting salts, and a low-sodium mix instead of a hoodie shop. Flavor options expand. Apparel and shipping protection stay out.",
    location: "United States",
    founded: 2022,
    categories: ["electrolytes"],
    accent: "#C45C26",
    rating: 4.5,
    reviewCount: 74,
    followerCount: 1600,
    websiteUrl: "https://thegoodintentionsclub.com",
    logoUrl: "/brands/good-intentions.svg",
  },
  {
    id: "c1126",
    slug: "elation-hydration",
    name: "Elation Hydration",
    tagline: "Zero-sugar household electrolytes — morning berry, moon berry, kids melon",
    story: "A focused unused electrolyte house: zero-sugar morning and evening berry mixes plus two kids melon flavors. No merch, no gadget wall. The $100 family bundle stays out so each flavor can live as its own listing.",
    location: "United States",
    founded: 2024,
    categories: ["electrolytes"],
    accent: "#5B3A8C",
    rating: 4.6,
    reviewCount: 58,
    followerCount: 1200,
    websiteUrl: "https://elationhydration.com",
    logoUrl: "/brands/elation-hydration.svg",
  },
  {
    id: "c1127",
    slug: "farmbody",
    name: "Farmbody",
    tagline: "Florida farm kitchen — magnesium deodorant scents and rice-water bars",
    story: "A Florida farm studio that pours aluminum-free cream and tube deodorant scents, fermented rice-water shampoo and conditioner bars, tallow balms, goat-milk soaps, and after-sun instead of a laundry-and-gift-set shop. Individual formulas and scent variants stay. Household cleaners, bug spray, workshops, and 4-piece gift sets stay out.",
    location: "Florida, New York, United States",
    founded: 2018,
    categories: ["deodorant","hair","skincare"],
    accent: "#7A5C3A",
    rating: 4.8,
    reviewCount: 640,
    followerCount: 9800,
    websiteUrl: "https://farmbodyskincare.com",
    logoUrl: "/brands/farmbody.svg",
  },
  {
    id: "c1128",
    slug: "pure-choice-farms",
    name: "Pure Choice Farms",
    tagline: "Wisconsin farm-direct whey isolate — vanilla, chocolate, peanut, unflavored",
    story: "A Wisconsin cheese-family whey house that cold-filters isolate from local farms and keeps vanilla, chocolate, peanut better, frosted marshmallow, and unflavored tubs plus a greens powder. Flavor listings stay. Hoodies, tanks, blender bottles, gift cards, 18–36 lb warehouse bags, and three-flavor combos stay in the barn.",
    location: "Wisconsin, United States",
    founded: 2019,
    categories: ["protein","supplements"],
    accent: "#1B4F72",
    rating: 4.7,
    reviewCount: 310,
    followerCount: 5400,
    websiteUrl: "https://www.purechoicefarms.com",
    logoUrl: "/brands/pure-choice-farms.svg",
  },
];
