import type { Brand } from "./types";

/** Wave 99: small organic / toxic-free brands across marketplace categories (c1463+). */
export const catalogBrandsWave99: Brand[] = [
  {
    id: "c1463",
    slug: "fygg",
    name: "Fygg",
    tagline: "Dentist-made nano-hydroxyapatite toothpaste with prebiotics — no foam, no fluoride",
    story:
      "The leftover unused dedicated multi-SKU n-HA house after wave4–98 shops ran out. Keep Mild Mint, Vanilla Vibes, Chocolate Swirl, Coconut Cream, NOX Wild Mint, Propolis silk floss, tongue scraper, oral probiotic mints, NOX mints, and pro varnish. Pack / travel / 3-pack is size. Stuffed toy, electric flosser, and family/routine kits stay boxed. Cart.js is USD. Pages are key-ingredient marketing (leave empty).",
    location: "United States",
    founded: 2022,
    categories: ["oral"],
    accent: "#3F6B4A",
    rating: 4.7,
    reviewCount: 420,
    followerCount: 18000,
    websiteUrl: "https://fygg.com",
    logoUrl: "/brands/fygg.svg",
  },
  {
    id: "c1464",
    slug: "tears-hydration",
    name: "Tears Hydration",
    tagline: "Muay Thai gym electrolytes — real fruit, ~1,000mg sodium, no stevia or sucralose",
    story:
      "Unused two-flavor fighter house after wave4–98. Keep Passionfruit Orange Guava and Yuzu Matcha. Stick count is size — pick the 5-stick. Cart.js is USD. Pages are flavor essays (leave empty).",
    location: "United States",
    founded: 2024,
    categories: ["electrolytes"],
    accent: "#E07A3D",
    rating: 4.6,
    reviewCount: 88,
    followerCount: 1400,
    websiteUrl: "https://www.drinktears.co",
    logoUrl: "/brands/tears-hydration.svg",
  },
  {
    id: "c1465",
    slug: "purishh",
    name: "PÜR-ISHH",
    tagline: "Grass-fed whey + collagen protein, real-fruit electrolytes, and tallow wash-day",
    story:
      "Unused clean-performance house. Flavor expands protein Vanilla / Chocolate and electrolytes Raspberry / Lemon Lime. Keep creatine, magnesium, D3+K2, shilajit, shampoo, conditioner, and lemongrass tallow soap. Stick packs vs tub is size — keep the tub. Hats, bundles, honey, guides, and $0 protocols stay boxed. Cart.js is USD. Pages are key-ingredient marketing (leave empty).",
    location: "United States",
    founded: 2023,
    categories: ["protein", "electrolytes", "supplements", "hair"],
    accent: "#5C4A3A",
    rating: 4.6,
    reviewCount: 112,
    followerCount: 2100,
    websiteUrl: "https://www.purishh.com",
    logoUrl: "/brands/purishh.svg",
  },
  {
    id: "c1466",
    slug: "lenus",
    name: "LENUS",
    tagline: "Encinitas small-batch numbered skin — mineral sunscreen, balms, and honey masks",
    story:
      "Leftover unused Encinitas mineral SPF + numbered skin house after wave4–98. Keep Nọ 43 mineral sunscreen and numbered singles (lotions, creams, oils, masks, toners, lips, hair oil). Samples, gift cards, sanitizer, respiratory/cold-sore oils, and cleansing-earth sets stay boxed. Cart.js is USD. Hardcode published Nọ 43 INCI; other pages are botanical essays unless a comma list lands.",
    location: "Encinitas, CA",
    founded: 2016,
    categories: ["sunscreen", "skincare", "hair"],
    accent: "#C45C26",
    rating: 4.8,
    reviewCount: 156,
    followerCount: 2400,
    websiteUrl: "https://shoplenus.com",
    logoUrl: "/brands/lenus.svg",
  },
  {
    id: "c1467",
    slug: "verdant-wild",
    name: "Verdant Wild",
    tagline: "Sulfate-free shampoo bars, magnesium deodorant, and zinc cream — low-waste botanicals",
    story:
      "Leftover unused shampoo/conditioner-bar + zinc cream + magnesium deodorant house after wave4–98 (candle-heavy). Scent expands magnesium deodorant; Hue expands shimmer balm; Formula expands hand cream; Scent expands beeswax lip. Keep wash-day bars, dry shampoo, hair oil, beard balm, SUNWISE zinc, and face/body singles. Candles, gift cards, samples, perfume, room mist, and subscription boxes stay boxed. Cart.js is USD. Pages are aromatherapy essays (leave empty unless a real INCI lands).",
    location: "United States",
    founded: 2018,
    categories: ["hair", "deodorant", "skincare", "sunscreen"],
    accent: "#2C5F4E",
    rating: 4.7,
    reviewCount: 210,
    followerCount: 3200,
    websiteUrl: "https://verdantwild.com",
    logoUrl: "/brands/verdant-wild.svg",
  },
  {
    id: "c1468",
    slug: "long-beach-mushrooms",
    name: "Long Beach Mushrooms",
    tagline: "Long Beach fruiting-body tinctures — lion's mane, reishi, cordyceps, turkey tail",
    story:
      "Leftover unused Long Beach extract house after wave4–98 (grow-kit/fresh-mix-heavy). Keep Lion's Mane, Cordyceps, Turkey Tail, Reishi, Triple Blend tinctures, and Lion's Mane capsules. Fresh culinary mix, grow kits, classes, and mushroom coffee stay boxed. Cart.js is USD. Hardcode published fruiting-body + cane alcohol + water lists.",
    location: "Long Beach, CA",
    founded: 2020,
    categories: ["supplements"],
    accent: "#4A3B2A",
    rating: 4.8,
    reviewCount: 64,
    followerCount: 980,
    websiteUrl: "https://longbeachmushrooms.com",
    logoUrl: "/brands/long-beach-mushrooms.svg",
  }
];
