import type { Brand } from "./types";

/** Wave 87: small organic / toxic-free brands across marketplace categories (c1391+). */
export const catalogBrandsWave87: Brand[] = [
  {
    id: "c1391",
    slug: "yafa-queen",
    name: "Yafa Queen",
    tagline: "California handmade herbal toothpaste, cream deodorant, and plant hair care",
    story: "The leftover unused herbal oral house after dedicated multi-SKU n-HA shops ran out — a woman-owned California maker pouring fluoride-free anise-clove toothpaste (tube + original jar), aluminum-free cream deodorants, peppermint and biotin hair care, shampoo bars, and goat-milk soaps. Pack count is size (keep Single Tube). Duos, rituals, collections, gift cards, bug spray, eyelash serum, Moroccan glove, and herbal drink stay boxed. Cart.js is USD. Pages are herbal-story marketing (leave empty when there is no comma formula).",
    location: "California",
    founded: 2020,
    categories: ["oral","deodorant","hair","skincare"],
    accent: "#7A3E2E",
    rating: 4.8,
    reviewCount: 210,
    followerCount: 2800,
    websiteUrl: "https://yafaqueen.com",
    logoUrl: "/brands/yafa-queen.svg",
  },
  {
    id: "c1392",
    slug: "sodii",
    name: "Sodii",
    tagline: "Australian lake-salt hydration salts with no sucralose and no fillers",
    story: "The unused Australian electrolyte leftover after wave4–86 — Everyday Hydration Salts from NASAA-certified Lake Deborah salt with magnesium gluconate and potassium chloride. Flavors already live on separate titles (Unflavoured / Citrus / Raspberry / Passionfruit / Mandarin / Kiwi / Grapefruit / Pineapple / Chocolate). Sachet vs tub and serving count are size. Drop parent Flavour expanders, the $0 bundle builder, sample packs, and raw electrolyte honey. Cart.js is AUD but Node products.json is already USD via Shopify Markets — do not apply AUD. Pages are formulation marketing (leave empty when there is no comma formula).",
    location: "Australia",
    founded: 2021,
    categories: ["electrolytes"],
    accent: "#C45C26",
    rating: 4.7,
    reviewCount: 890,
    followerCount: 12000,
    websiteUrl: "https://sodii.com.au",
    logoUrl: "/brands/sodii.svg",
  },
  {
    id: "c1393",
    slug: "madeof-life",
    name: "Made Of",
    tagline: "Small-batch New Zealand grass-fed whey isolate in three clean flavors",
    story: "The unused protein leftover after wave4–86 — three 1 lb NZ grass-fed whey isolates (Unflavored / Vanilla / Chocolate) made in small US batches with sunflower lecithin and a touch of organic stevia on the flavored tubs. Flavors already live on separate titles. Route shipping protection stays boxed. Not the Made Of oral-care house already on main. Cart.js is USD. Published formula is NZ whey isolate + sunflower lecithin (+ organic flavor and stevia on vanilla/chocolate).",
    location: "United States",
    founded: 2022,
    categories: ["protein"],
    accent: "#2F4A3C",
    rating: 4.6,
    reviewCount: 140,
    followerCount: 1600,
    websiteUrl: "https://madeof.life",
    logoUrl: "/brands/madeof-life.svg",
  },
  {
    id: "c1394",
    slug: "doos-naturals",
    name: "Doo's Naturals",
    tagline: "Small-batch tallow sun balm, mineral deodorant, and honey moisturizer",
    story: "The leftover unused tallow house after wave4–86 — a 5-ingredient zinc sun balm, aluminum-free mineral deodorant (Lavender Patchouli / Unscented / Citrus Cedarwood), rosemary dry shampoo (Dark / Light), tallow hair clay, honey moisturizer scents, eucalyptus soap, and beeswax lip. 2 oz vs 4 oz / Small vs Large / Single vs 3-pack is size. Bundles, insect repellent, and gift sets stay boxed. Cart.js is USD. Hardcode published zinc / tallow / honey lists when the page names them.",
    location: "United States",
    founded: 2023,
    categories: ["sunscreen","deodorant","hair","skincare"],
    accent: "#5A4632",
    rating: 4.8,
    reviewCount: 96,
    followerCount: 1100,
    websiteUrl: "https://doosnaturals.com",
    logoUrl: "/brands/doos-naturals.svg",
  },
  {
    id: "c1395",
    slug: "tallow-twins",
    name: "Tallow Twins",
    tagline: "Canadian farm-to-skin tallow sun care, deodorant, and hair oil",
    story: "The leftover unused Canadian tallow house after wave4–86 — Sun Proof / Sun Milk / Tallow Tan, four deodorant scents, hair oil, scalp mask, Cowlick balm vs stick, olive-oil soap scents, face creams, body butters, baby balm, and mint-chip / honey lips. ml / oz is size. Bundles, sample sets, hats, gift cards, gua sha, konjac, and tick spray stay boxed. Cart.js is CAD — convert × 0.73. Pages are farm-story marketing (leave empty when there is no comma formula).",
    location: "Canada",
    founded: 2022,
    categories: ["sunscreen","deodorant","hair","skincare"],
    accent: "#8B5A3C",
    rating: 4.8,
    reviewCount: 240,
    followerCount: 3400,
    websiteUrl: "https://tallowtwins.ca",
    logoUrl: "/brands/tallow-twins.png",
  },
  {
    id: "c1396",
    slug: "sunshine-fungi",
    name: "Sunshine Fungi",
    tagline: "Small-farm lion's mane, reishi, cordyceps, and turkey tail dual extracts",
    story: "The unused leftover mushroom house after wave4–86 — four dual-extract tinctures (Lion's Mane / Reishi / Cordyceps / Turkey Tail) plus dried reishi and lion's mane powders. Published formula is species + organic cane alcohol + distilled water. Fresh / dried culinary mushrooms, jerky, chef's mix, spawn, grain, and liquid culture stay boxed. Cart.js is USD.",
    location: "United States",
    founded: 2021,
    categories: ["supplements"],
    accent: "#3F5C2E",
    rating: 4.7,
    reviewCount: 72,
    followerCount: 890,
    websiteUrl: "https://sunshinefungifarms.com",
    logoUrl: "/brands/sunshine-fungi.svg",
  },
];
