import type { Brand } from "./types";

/** Wave 79: small organic / toxic-free brands across marketplace categories (c1343+). */
export const catalogBrandsWave79: Brand[] = [
  {
    id: "c1343",
    slug: "oh-care",
    name: "OH! Care",
    tagline: "Australian oral-skincare house with NanoXIM nano-hydroxyapatite toothpaste and hyaluronic acid mouthwash",
    story: "An Australian oral-skincare house pairing Fluidinova NanoXIM n-HA toothpaste with hyaluronic-acid mouthwash and HA-X gum serum. Tube and 320 ml rinse are size; travel 50 ml and triple packs stay boxed. Duos, trios, and the shot glass stay boxed. Cart.js is AUD × 0.65. Pages publish n-HA / hyaluronic lists when a real INCI is on the page.",
    location: "Australia",
    founded: 2022,
    categories: ["oral"],
    accent: "#3D7A8C",
    rating: 4.7,
    reviewCount: 420,
    followerCount: 6800,
    websiteUrl: "https://ohcaredental.com",
    logoUrl: "/brands/oh-care.svg",
  },
  {
    id: "c1344",
    slug: "evolve-essentials",
    name: "Evolve Essentials",
    tagline: "Canadian stevia-free monk-fruit electrolytes with real fruit, coconut water, and 70+ trace minerals",
    story: "A Canadian hydration house from Natasha and Hari — stevia-free Salted Lemonade, Salted Watermelon, and Salted Tropical (passionfruit orange guava) mixed with coconut water, real fruit juice powders, premium minerals, and monk fruit. Flavors already live on separate titles; 28-serving scoop bags are size. Cart.js is CAD × 0.73. Pages publish the mineral + fruit list when a real formula is on the page.",
    location: "Canada",
    founded: 2023,
    categories: ["electrolytes"],
    accent: "#C45A3A",
    rating: 4.7,
    reviewCount: 380,
    followerCount: 5400,
    websiteUrl: "https://evolveessentials.ca",
    logoUrl: "/brands/evolve-essentials.svg",
  },
  {
    id: "c1345",
    slug: "bodi-blends",
    name: "Bodi Blends",
    tagline: "Australian whey isolate with collagen, Kakadu plum, MCT, and monk fruit in Vanilla and Chocolate",
    story: "A small Australian protein house blending whey isolate with hydrolysed collagen, Kakadu plum, MCT, and monk fruit — Vanilla WPI and Chocolate WPI already live on separate titles. 1 kg is size. Creatine monohydrate stays supplements. The performance cap stays boxed. Cart.js is AUD × 0.65. Pages publish the short whey + collagen list when a real formula is on the page.",
    location: "Australia",
    founded: 2022,
    categories: ["protein","supplements"],
    accent: "#6B4A32",
    rating: 4.6,
    reviewCount: 210,
    followerCount: 3200,
    websiteUrl: "https://bodiblends.com.au",
    logoUrl: "/brands/bodi-blends.svg",
  },
  {
    id: "c1346",
    slug: "skin-candy",
    name: "The Skin Candy",
    tagline: "Small-batch tallow rice-water shampoo and conditioner bars, goat-milk soaps, and homestead body care",
    story: "A handmade US soap-and-hair house pouring tallow rice-water shampoo bars, matching conditioner bars, goat-milk and coconut-milk artisan soaps, whipped soap, lotion, scrubs, and tallow lip balm. Lotion / whipped-soap / scrub Scent and lip Flavor expand; jar oz and lip quantity are size. Laundry, dish soap, candles, wax melts, room spray, bath bombs, shower steamers, toilet fizzies, kits, mystery grab bags, and soap-end samplers stay boxed. Cart.js is USD.",
    location: "United States",
    founded: 2020,
    categories: ["hair","skincare"],
    accent: "#8B5A6B",
    rating: 4.8,
    reviewCount: 890,
    followerCount: 14000,
    websiteUrl: "https://theskincandyllc.com",
    logoUrl: "/brands/skin-candy.svg",
  },
  {
    id: "c1347",
    slug: "florida-mushroom-company",
    name: "Florida Mushroom Company",
    tagline: "Lake Wales, Florida fruiting-body lion's mane, reishi, cordyceps, and turkey tail dual extracts",
    story: "A Lake Wales indoor farm from founders Deeley and Patrick making dual-extracted fruiting-body tinctures — lion's mane, reishi, cordyceps, and turkey tail. Bottle size is size. Tees, tanks, trucker caps, shiitake seasonings, and extract bundles stay boxed. Tincture pages publish fruiting-body + cane alcohol + spring water when a real formula is listed.",
    location: "Lake Wales, FL",
    founded: 2021,
    categories: ["supplements"],
    accent: "#3F5C32",
    rating: 4.8,
    reviewCount: 260,
    followerCount: 4100,
    websiteUrl: "https://flmushroomco.com",
    logoUrl: "/brands/florida-mushroom-company.svg",
  },
  {
    id: "c1348",
    slug: "florida-shroom-king",
    name: "Florida Shroom King",
    tagline: "New Smyrna Beach farm-made alcohol-free triple extracts of lion's mane, reishi, turkey tail, and chaga",
    story: "A Central Florida farm making solvent-free triple extracts from fruiting bodies — lion's mane grown in New Smyrna, plus reishi, turkey tail, chaga, and a Trifecta blend. 2 oz vs 1 oz is size. Market Friends duplicate titles, fresh culinary mushrooms, AM/PM stacks, athletic stacks, and super-stack bundles stay boxed. Pages publish the fruiting-body extract list when a real formula is on the page.",
    location: "New Smyrna Beach, FL",
    founded: 2022,
    categories: ["supplements"],
    accent: "#5A4632",
    rating: 4.8,
    reviewCount: 340,
    followerCount: 5600,
    websiteUrl: "https://floridashroomking.com",
    logoUrl: "/brands/florida-shroom-king.svg",
  },
];
