import type { Brand } from "./types";

/** Wave 89: small organic / toxic-free brands across marketplace categories (c1403+). */
export const catalogBrandsWave89: Brand[] = [
  {
    id: "c1403",
    slug: "revive-homestead",
    name: "Revive Homestead",
    tagline: "Homestead hydroxyapatite tooth powder, tallow deodorant, and mineral rinse",
    story: "The leftover unused multi-SKU micro-hydroxyapatite oral house after dedicated n-HA shops ran out — a homestead tooth powder with 10% non-nano hydroxyapatite, a mint oral rinse, neem oil-pulling, tallow deodorant scents, and whipped tallow butter. Flavor expands the powder (prefer xylitol). Scent expands deodorant and body butter. 2 oz vs 4 oz / jar count is size. DIY clays, flavor packets, applicators, scoops, travel cases, electric heads, and extra toothbrush colors stay boxed. Cart.js is USD. Hardcode the published clay / hydroxyapatite powder and tallow deodorant lists.",
    location: "United States",
    founded: 2022,
    categories: ["oral","deodorant","skincare"],
    accent: "#5A6B3E",
    rating: 4.8,
    reviewCount: 210,
    followerCount: 3400,
    websiteUrl: "https://revivehomestead.com",
    logoUrl: "/brands/revive-homestead.svg",
  },
  {
    id: "c1404",
    slug: "untammed",
    name: "UNTAMMED",
    tagline: "Real-food electrolyte powder with coconut water, sea salt, and fruit — no sucralose",
    story: "The unused electrolyte leftover after wave4–88 — Mineral Mist is a four-ingredient hydration mix (coconut water, sea salt, magnesium chloride, real fruit) with no stevia, monk fruit, sucralose, or natural-flavor labs. Flavor expands Berry Sweet / Lemon Squeeze / Grapefruit Lime / Elemental Coconut / Strawberry Sunrise. Serving count is size. Totes, free teas, and gift extras stay boxed. Tummy Peace, Nettle & Bloom, and Wild Nectar stay supplements. Cart.js is USD. Hardcode the published coconut-water / sea-salt list.",
    location: "United States",
    founded: 2023,
    categories: ["electrolytes","supplements"],
    accent: "#2F5E4A",
    rating: 4.7,
    reviewCount: 86,
    followerCount: 1900,
    websiteUrl: "https://untammed.co",
    logoUrl: "/brands/untammed.svg",
  },
  {
    id: "c1405",
    slug: "pure-choice-farms",
    name: "Pure Choice Farms",
    tagline: "Wisconsin farm-family whey isolate with organic vanilla, cocoa, and peanut",
    story: "The unused protein leftover after wave4–88 — cold-filtered whey isolate from Wisconsin family dairy farms (28g, virtually zero lactose) in Organic Vanilla, Chocolate, Unflavored, Peanut Better, and Frosted Marshmallow. Flavors already live on separate titles. 2 lb is size (drop 4/6/18/36 lb and 12 oz). Combos, flights, hoodies, tanks, shakers, and gift cards stay boxed. Sweet greens and tropics stay supplements. Cart.js is USD. Pages are farm-story marketing (hardcode isolate + flavor when published).",
    location: "Wisconsin",
    founded: 2019,
    categories: ["protein","supplements"],
    accent: "#3B5A7A",
    rating: 4.7,
    reviewCount: 420,
    followerCount: 6100,
    websiteUrl: "https://www.purechoicefarms.com",
    logoUrl: "/brands/pure-choice-farms.svg",
  },
  {
    id: "c1406",
    slug: "little-pasture",
    name: "Little Pasture",
    tagline: "California reef-safe tallow mineral SPF 50 with manuka honey balms",
    story: "The leftover unused tallow mineral-sun house after wave4–88 — a jojoba-coated non-nano zinc SPF 50, after-sun repair, infused tallow balms, and fruit lip tins. Flavors already live on lip titles; 2 oz vs 4 oz is size. Variety packs, DIY kits, wholesale tallow, $1 trials, and 4-piece sun kits stay boxed. Cart.js is USD. Hardcode the published zinc / tallow / jojoba sunscreen list.",
    location: "California",
    founded: 2021,
    categories: ["sunscreen","skincare"],
    accent: "#7A5A2E",
    rating: 4.8,
    reviewCount: 640,
    followerCount: 8200,
    websiteUrl: "https://thelittlepasture.com",
    logoUrl: "/brands/little-pasture.svg",
  },
  {
    id: "c1407",
    slug: "purely-wild",
    name: "Purely Wild Skin Co.",
    tagline: "Magnesium tallow deodorant, whipped balm, and plastic-free lip tin",
    story: "The leftover unused tallow deodorant house after wave4–88 — magnesium tallow deodorant (Unscented / Eucalyptus Orange), whipped balms, facial soaps, serums, and lip flavors. Scent / Flavor expand; 2 oz vs 4 oz / 8 oz is size. Bundles, gift cards, and Pick 3 lip extras stay boxed. Cart.js is USD. Pages are key-ingredient marketing (leave empty when there is no comma formula).",
    location: "United States",
    founded: 2023,
    categories: ["deodorant","skincare"],
    accent: "#6B4A38",
    rating: 4.8,
    reviewCount: 154,
    followerCount: 2700,
    websiteUrl: "https://purelywildskinco.com",
    logoUrl: "/brands/purely-wild.svg",
  },
  {
    id: "c1408",
    slug: "inahsi",
    name: "Inahsi Naturals",
    tagline: "Chemist-made plant curl care for waves, coils, and textured hair",
    story: "The leftover unused curl-hair house after wave4–88 — Warrenville, Illinois chemist Rhonda Marshall's plant-based shampoos, leave-ins, masques, and gels for wavy-to-coily hair, made in-house since 2014. Size expands to 12 oz retail (8 oz for foam and whipped butter); 2 oz is travel and 33/64 oz is wholesale. Holiday collections, salon-pro, wholesale cases, sample packs, gift wrap, and memberships stay boxed. Cart.js is USD. Pages publish comma INCI on several wash-day SKUs.",
    location: "Warrenville, IL",
    founded: 2014,
    categories: ["hair"],
    accent: "#2C6B5A",
    rating: 4.7,
    reviewCount: 2800,
    followerCount: 24000,
    websiteUrl: "https://inahsi.com",
    logoUrl: "/brands/inahsi.svg",
  },
];
