import type { Brand } from "./types";

/** Wave 110: small organic / toxic-free brands across marketplace categories (c1529+). */
export const catalogBrandsWave110: Brand[] = [
  {
    id: "c1529",
    slug: "zing-toothpaste",
    name: "ZING",
    tagline: "Yorkshire hydroxyapatite toothpaste — mint, peach, lemon, apple-kiwi, no SLS, no titanium dioxide",
    story:
      "ZING mixed toothpaste in Yorkshire and refused the cheap-tube dye aisle. Hydroxyapatite — the mineral enamel already is — plus fluoride at 1450 ppm in the everyday mint, peach, lemon, and apple-kiwi. A fluoride-free mint when you want the mineral without the ion. No SLS. No titanium dioxide. Recyclable tubes. A mint floss and a watermelon floss when the tube is not the whole sink. No four-pack, no starter bundle, no charity case: the single tube you squeeze.",
    location: "Covent Garden, London",
    founded: 2021,
    categories: ["oral"],
    accent: "#E23B2C",
    rating: 4.7,
    reviewCount: 1860,
    followerCount: 24000,
    websiteUrl: "https://zingtoothpaste.com",
    logoUrl: "/brands/zing-toothpaste.svg",
  },
  {
    id: "c1530",
    slug: "hydro-trapp",
    name: "Hydro Trapp",
    tagline: "Phoenix zero-sugar electrolytes — Kiwi Chill, Trap Sandia, Blue Oasis, Trap Nectar",
    story:
      "Hydro Trapp mixed hydration for Phoenix heat, not for a flavor lab. Three thousand milligrams of electrolytes in a scoop. Zero sugar. No stevia lecture. Kiwi Chill is kiwi-pineapple-mint. Trap Sandia is watermelon-lime. Blue Oasis is blue raspberry coconut lime. Trap Nectar is peach mango. Already on the title. No care-package upsell, no flask, no tee: the tub you scoop when the desert is the day.",
    location: "Phoenix, AZ",
    founded: 2023,
    categories: ["electrolytes"],
    accent: "#1A6B4A",
    rating: 4.6,
    reviewCount: 280,
    followerCount: 4100,
    websiteUrl: "https://hydrotrapp.com",
    logoUrl: "/brands/hydro-trapp.svg",
  },
  {
    id: "c1531",
    slug: "stomp-nutrition",
    name: "Stomp Nutrition",
    tagline: "Grass-fed whey that tastes like fudge brownie — plus a cookie-dough vegan pouch, no artificial sweeteners",
    story:
      "Stomp started on a snowboard, not in a supplement aisle. Founder Adam wanted protein for people who still play outside. Twenty-five grams of grass-fed whey in Chocolate Fudge Brownie — real cocoa, no artificial sweetener, no scoop upsell. A Chocolate Chip Cookie Dough vegan pouch when dairy is not the day. No travel pack, no hoodie, no shaker: the bag you actually mix.",
    location: "United States",
    founded: 2022,
    categories: ["protein"],
    accent: "#2B4C6F",
    rating: 4.6,
    reviewCount: 190,
    followerCount: 3200,
    websiteUrl: "https://stomp-nutrition.com",
    logoUrl: "/brands/stomp-nutrition.svg",
  },
  {
    id: "c1532",
    slug: "solara-suncare",
    name: "Solara Suncare",
    tagline: "Mineral SPF that actually lives outside — Go! sport face and body, Guardian Angel milk, Fortune Teller tint",
    story:
      "Solara built mineral sunscreen for the day that is not a beach photoshoot. Go! Daily Defense is the soothing SPF 30 face. Go! Sport is the superfruit body and the antioxidant face at SPF 50. A sheer aloe mist when you do not want a cream. Guardian Angel is the peptide milk at SPF 50. Fortune Teller is the tinted serum — MicroTint 1 or 2, already on the option. Good Karma is the body-oil SPF 30. No luggage tag, no vacation edit, no brush upsell: the bottle you put on before the door.",
    location: "United States",
    founded: 2018,
    categories: ["sunscreen", "skincare"],
    accent: "#D4A017",
    rating: 4.7,
    reviewCount: 1240,
    followerCount: 18000,
    websiteUrl: "https://www.solarasuncare.com",
    logoUrl: "/brands/solara-suncare.svg",
  },
  {
    id: "c1533",
    slug: "haus-of-sage",
    name: "Haus of Sage",
    tagline: "Florida grass-fed tallow deodorant and whipped balm — Grapefruit Basil to Lavender Citrus, no aluminum",
    story:
      "Haus of Sage renders grass-fed tallow in Florida and stops before the aluminum stick. The deodorant cream is baking-soda-free — Grapefruit Basil, Yuzu Mint, Vanilla Neroli, Activated Charcoal Mint, Lavender Citrus — already on the scent option. A whipped tallow in unscented through rose. A sun balm. A honey soap. A lip. No 48-pack, no white-label gallon, no sample drawer: the jar you open.",
    location: "Florida, United States",
    founded: 2021,
    categories: ["deodorant", "skincare", "sunscreen"],
    accent: "#8B6B4A",
    rating: 4.8,
    reviewCount: 640,
    followerCount: 9800,
    websiteUrl: "https://thehausofsage.com",
    logoUrl: "/brands/haus-of-sage.svg",
  },
  {
    id: "c1534",
    slug: "sugarshack-mushrooms",
    name: "Sugarshack Mushrooms",
    tagline: "Hudson Valley fruiting-body tinctures — Lion's Mane, Reishi, Chaga, Cordyceps, Turkey Tail, grown since 2018",
    story:
      "Sugarshack is a family farm in New Paltz that grows Lion's Mane and Reishi in a barn and a passive-solar greenhouse, then bottles the fruiting body. Dual extract: mushroom, organic cane alcohol, carbon-filtered water. Chaga, turkey tail, and cordyceps come from New York woods they trust. One-ounce bottles. No grow kit, no trio, no full-collection crate: the dropper that came off the farm.",
    location: "New Paltz, NY",
    founded: 2018,
    categories: ["supplements"],
    accent: "#4A5A28",
    rating: 4.8,
    reviewCount: 420,
    followerCount: 7600,
    websiteUrl: "https://sugarshackmushrooms.com",
    logoUrl: "/brands/sugarshack-mushrooms.svg",
  },
];
