import type { Brand } from "./types";

/** Wave 13: small organic / toxic-free brands across marketplace categories (c641+). */
export const catalogBrandsWave13: Brand[] = [
  {
    id: "c641",
    slug: "eco-by-sonya",
    name: "Eco by Sonya",
    tagline: "Australian organic body milk, hemp glow, and mineral-minded sun ritual",
    story: "Sonya Driver’s Byron-born organic house: hemp seed, rosehip, and certified-organic botanicals in body milk, face oils, and sun-care that skip the chemical-filter drawer. Cruelty-free, vegan, and built for skin that lives outside without a drugstore burn.",
    location: "Byron Bay, Australia",
    founded: 2008,
    categories: ["sunscreen","skincare"],
    accent: "#C4A35A",
    rating: 4.7,
    reviewCount: 4200,
    followerCount: 86000,
    websiteUrl: "https://ecobysonyadriver.com",
    logoUrl: "/brands/eco-by-sonya.svg",
  },
  {
    id: "c642",
    slug: "miyazaki-tallow",
    name: "Miyazaki Tallow",
    tagline: "A5 Wagyu tallow balms and non-nano zinc mineral sunscreen",
    story: "A tiny tallow kitchen wrapping Japanese-inspired botanicals — Kyoto green tea, yuzu, lavender — around grass-fed A5 Wagyu fat and uncoated non-nano zinc. No oxybenzone, no octinoxate, no petroleum lotion. Ancestral fat plus mineral UV for skin that wants food-grade, not fragrance theater.",
    location: "United States",
    founded: 2023,
    categories: ["sunscreen","skincare"],
    accent: "#6B3E26",
    rating: 4.8,
    reviewCount: 140,
    followerCount: 3200,
    websiteUrl: "https://miyazakitallow.com",
    logoUrl: "/brands/miyazaki-tallow.svg",
  },
  {
    id: "c643",
    slug: "new-day-organics",
    name: "New Day Organics",
    tagline: "Baking-soda-free deodorant and mineral sun sticks in compostable tubes",
    story: "Small-batch Vermont-minded care: magnesium and zinc deodorant without aluminum or baking soda, plus a mineral sun stick you can toss in the compost pile. Essential-oil scents or unscented, poured by hand, no propylene glycol, no synthetic fragrance fog.",
    location: "United States",
    founded: 2016,
    categories: ["deodorant","sunscreen"],
    accent: "#4A7C59",
    rating: 4.7,
    reviewCount: 890,
    followerCount: 14000,
    websiteUrl: "https://newdayorganics.com",
    logoUrl: "/brands/new-day-organics.svg",
  },
  {
    id: "c644",
    slug: "precision-hydration",
    name: "Precision Hydration",
    tagline: "Sweat-tested electrolyte drinks and chews without the neon sports-drink stack",
    story: "A UK sports-science kitchen that actually measures how you sweat. Sodium-forward electrolyte drinks, gels, and chews in real fruit flavors — no mystery dye circus, no locker-room candy syrup. Built for long days outside, not another convenience-store packet.",
    location: "United Kingdom",
    founded: 2011,
    categories: ["electrolytes"],
    accent: "#1B4F72",
    rating: 4.7,
    reviewCount: 3100,
    followerCount: 48000,
    websiteUrl: "https://us.precisionhydration.com",
    logoUrl: "/brands/precision-hydration.svg",
  },
  {
    id: "c645",
    slug: "halo-hydration",
    name: "HALO",
    tagline: "Clean lemonade-and-tea hydration without the sports-drink sticky sweet",
    story: "A small hydration house making half-tea, lemonade, and sweet-tea drinks that read like a picnic, not a lab. Everyday electrolytes for people who want flavor they recognize and minerals in the bottle — no neon powder, no candy-syrup aftertaste.",
    location: "United States",
    founded: 2021,
    categories: ["electrolytes"],
    accent: "#E8A317",
    rating: 4.5,
    reviewCount: 420,
    followerCount: 12000,
    websiteUrl: "https://drinkhalo.com",
    logoUrl: "/brands/halo-hydration.svg",
  },
  {
    id: "c646",
    slug: "earthchimp",
    name: "EarthChimp",
    tagline: "Organic pea-pumpkin-sunflower protein with probiotics — no nasties",
    story: "A tiny organic kitchen blending pea, pumpkin, coconut, and sunflower proteins with digestive enzymes and probiotics. USDA-minded ingredients, monk fruit instead of a sugar-alcohol pile, and flavors that taste like food. The opposite of a 19-ingredient bro tub.",
    location: "United Kingdom",
    founded: 2020,
    categories: ["protein"],
    accent: "#3D7A4A",
    rating: 4.6,
    reviewCount: 680,
    followerCount: 19000,
    websiteUrl: "https://earthchimp.com",
    logoUrl: "/brands/earthchimp.svg",
  },
  {
    id: "c647",
    slug: "eat-superplants",
    name: "Eat SuperPlants",
    tagline: "Sacha inchi and seed-protein blends without gums or flavor theater",
    story: "Plant protein built from sacha inchi, pea, sunflower, and pumpkin seed — no gums, no “natural flavors,” no chalky masking agents. Functional cacao and hormone-support capsules for people who want a pantry list, not a lab novel.",
    location: "United States",
    founded: 2021,
    categories: ["protein","supplements"],
    accent: "#5B7A3A",
    rating: 4.6,
    reviewCount: 210,
    followerCount: 5400,
    websiteUrl: "https://eatsuperplants.com",
    logoUrl: "/brands/eat-superplants.svg",
  },
  {
    id: "c648",
    slug: "plenti",
    name: "Plenti",
    tagline: "Organic pea and pumpkin protein with probiotics — short labels, real training",
    story: "A small US performance kitchen: organic pea and pumpkin seed protein, unflavored creatine, and stacks that skip the pre-workout neon. Probiotics and enzymes in the scoop, no artificial sweetener fog — just the few things a training day actually needs.",
    location: "United States",
    founded: 2022,
    categories: ["protein","supplements"],
    accent: "#6B4F3A",
    rating: 4.6,
    reviewCount: 180,
    followerCount: 4100,
    websiteUrl: "https://plentisupps.com",
    logoUrl: "/brands/plenti.svg",
  },
  {
    id: "c649",
    slug: "jl-naturals",
    name: "J&L Naturals",
    tagline: "North Carolina small-batch deodorant and shampoo bars — zero waste, vegan",
    story: "A family studio in Mooresville pouring mineral deodorant (baking-soda-free) and sulfate-free hair bars by hand. Carbon-neutral shipping, plastic-light tubes, ingredients they’d use on their own kids. No aluminum, no harsh detergent theater.",
    location: "Mooresville, NC",
    founded: 2018,
    categories: ["deodorant","hair"],
    accent: "#4A6741",
    rating: 4.8,
    reviewCount: 540,
    followerCount: 8900,
    websiteUrl: "https://www.jnlnaturals.com",
    logoUrl: "/brands/jl-naturals.svg",
  },
  {
    id: "c650",
    slug: "banbu",
    name: "Banbu",
    tagline: "Spanish ECO cream and solid deodorant for sensitive skin — plastic-light",
    story: "A Madrid-minded eco house making cream and solid deodorants certified for sensitive skin. Aluminum-free, baking-soda-aware, and packaged to leave the plastic stick in the past. Soft Touch and Silver Touch formulas that treat underarms like skin, not a locker room.",
    location: "Spain",
    founded: 2019,
    categories: ["deodorant"],
    accent: "#2E8B6A",
    rating: 4.7,
    reviewCount: 760,
    followerCount: 22000,
    websiteUrl: "https://banbu.es",
    logoUrl: "/brands/banbu.svg",
  },
  {
    id: "c651",
    slug: "lovett-sundries",
    name: "Lovett Sundries",
    tagline: "Pittsburgh handmade deodorant and organic body oil — aluminum-free, short lists",
    story: "A Pittsburgh sundries shop pouring aluminum-free sticks and organic body oils in small batches. Arrowroot, coconut oil, and essential-oil scents — no mystery antiperspirant salts, no fragrance-house fog. Old-fashioned care that still works after a shift.",
    location: "Pittsburgh, PA",
    founded: 2014,
    categories: ["deodorant","skincare"],
    accent: "#8B5A2B",
    rating: 4.8,
    reviewCount: 1200,
    followerCount: 16000,
    websiteUrl: "https://lovettsundries.com",
    logoUrl: "/brands/lovett-sundries.svg",
  },
  {
    id: "c652",
    slug: "naturallow",
    name: "Naturallow",
    tagline: "Tallow-first skin rituals and magnesium deodorant without the itch",
    story: "Handcrafted tallow balms, barrier oils, and a magnesium-plus-probiotic deodorant that skips aluminum and baking soda. Built for reactive skin that tried “natural” and got the rash — short labels, no endocrine-disruptor cocktail, no fake vanilla fog.",
    location: "United States",
    founded: 2020,
    categories: ["skincare","deodorant"],
    accent: "#B08968",
    rating: 4.7,
    reviewCount: 380,
    followerCount: 7200,
    websiteUrl: "https://www.naturallow.com",
    logoUrl: "/brands/naturallow.svg",
  },
  {
    id: "c653",
    slug: "huppy",
    name: "Huppy",
    tagline: "Plastic-free n-Ha toothpaste tablets and refill floss — no tube, no fluoride circus",
    story: "Chew-and-brush tablets with nano-hydroxyapatite, xylitol, and organic mint oils — fluoride-free, plastic-tube-free, and built to leave the drugstore squeeze in the past. Bamboo brushes and refill floss for a bathroom that doesn’t ship water in plastic.",
    location: "United States",
    founded: 2019,
    categories: ["oral"],
    accent: "#2C5F4E",
    rating: 4.6,
    reviewCount: 2100,
    followerCount: 34000,
    websiteUrl: "https://www.behuppy.com",
    logoUrl: "/brands/huppy.svg",
  },
  {
    id: "c654",
    slug: "stella-naturals",
    name: "Stella Naturals",
    tagline: "New Zealand hydroxyapatite toothpaste and mineral tooth putty — fluoride-free",
    story: "A Kiwi oral studio making fluoride-free hydroxyapatite paste and a 20% non-nano mineral tooth putty. Grape, lemon, vanilla, strong mint, or no menthol at all — enamel-matching mineral without SLS foam circus or drugstore dye.",
    location: "New Zealand",
    founded: 2021,
    categories: ["oral"],
    accent: "#1A4A6B",
    rating: 4.8,
    reviewCount: 640,
    followerCount: 9800,
    websiteUrl: "https://stellanaturals.co.nz",
    logoUrl: "/brands/stella-naturals.svg",
  },
  {
    id: "c655",
    slug: "revive-homestead",
    name: "Revive Homestead",
    tagline: "Homestead tooth powder with 10% micro-hydroxyapatite and tallow deodorant",
    story: "Earth-based oral care: calcium, clays, and 10% micro-hydroxyapatite in a fluoride-free, glycerin-free powder — plus tallow deodorant without the zinc-oxide itch. No SLS, no tube of water, no synthetic mint burn. Homestead formulas for mouths and pits that want minerals.",
    location: "United States",
    founded: 2020,
    categories: ["oral","deodorant"],
    accent: "#7A6A4F",
    rating: 4.7,
    reviewCount: 290,
    followerCount: 6100,
    websiteUrl: "https://revivehomestead.com",
    logoUrl: "/brands/revive-homestead.svg",
  },
  {
    id: "c656",
    slug: "naedlae",
    name: "Naedlae",
    tagline: "Kent-made wild-nettle leave-in spray — 99% natural origin, silicone-free",
    story: "A one-studio hair house in Kent: wild-harvested nettle from a biodynamic vineyard, vegan keratin, organic grapeseed, and olive squalane in a leave-in that treats scalp like skin. Handmade, silicone-free, no sulfate strip-and-compensate cycle.",
    location: "Kent, United Kingdom",
    founded: 2022,
    categories: ["hair"],
    accent: "#3F6B4B",
    rating: 4.8,
    reviewCount: 90,
    followerCount: 2400,
    websiteUrl: "https://naedlae.com",
    logoUrl: "/brands/naedlae.svg",
  },
  {
    id: "c657",
    slug: "armra",
    name: "ARMRA",
    tagline: "Grass-fed colostrum for gut, immunity, and skin — short label, real dairy first food",
    story: "Bovine colostrum from grass-fed dairies, concentrated into an unflavored jar and a small soda lineup. No neon immunity gummy, no 40-ingredient blend — just the first-food proteins people actually talk about for gut lining and recovery.",
    location: "United States",
    founded: 2020,
    categories: ["supplements"],
    accent: "#8B3A2A",
    rating: 4.5,
    reviewCount: 3800,
    followerCount: 72000,
    websiteUrl: "https://tryarmra.com",
    logoUrl: "/brands/armra.svg",
  },
  {
    id: "c658",
    slug: "gaia-herbs",
    name: "Gaia Herbs",
    tagline: "Certified organic herbs from a North Carolina farm — meet-your-maker supplements",
    story: "A Brevard farm that grows, extracts, and bottles its own herbs: milky oats, valerian, mushrooms, and daily tonics with a purity panel you can look up. Organic, identity-tested, and stubborn about the plant actually showing up in the capsule.",
    location: "Brevard, NC",
    founded: 1987,
    categories: ["supplements"],
    accent: "#2C5F4E",
    rating: 4.7,
    reviewCount: 8900,
    followerCount: 110000,
    websiteUrl: "https://www.gaiaherbs.com",
    logoUrl: "/brands/gaia-herbs.png",
  },
  {
    id: "c659",
    slug: "herb-pharm",
    name: "Herb Pharm",
    tagline: "Oregon-grown liquid herbal extracts since 1979 — organic, potent, no junk",
    story: "A Williams, Oregon herb house making liquid extracts from certified-organic and conscientiously wildcrafted plants. Oil of oregano, kava, throat sprays — short formulas, no mystery fillers, the kind of tincture cabinet that still feels like a farm.",
    location: "Williams, OR",
    founded: 1979,
    categories: ["supplements"],
    accent: "#5B3A7A",
    rating: 4.8,
    reviewCount: 5400,
    followerCount: 64000,
    websiteUrl: "https://www.herb-pharm.com",
    logoUrl: "/brands/herb-pharm.png",
  },
  {
    id: "c660",
    slug: "beekeepers-naturals",
    name: "Beekeeper's Naturals",
    tagline: "Propolis, bee pollen, and B.Powered — hive-first wellness without the candy gummy",
    story: "A bee-minded wellness house: propolis cough syrups, kids’ sinus kits, and daily hive foods instead of another dye-and-maltodextrin immunity stick. Traceable apiary ingredients for throats, sinuses, and the kind of winter that actually needs a hive.",
    location: "Toronto, Canada",
    founded: 2016,
    categories: ["supplements"],
    accent: "#C47A2C",
    rating: 4.6,
    reviewCount: 4200,
    followerCount: 89000,
    websiteUrl: "https://www.beekeepersnaturals.com",
    logoUrl: "/brands/beekeepers-naturals.png",
  },
];
