import type { Brand } from "./types";

/** Wave 51: small organic / toxic-free brands across marketplace categories (c1171+). */
export const catalogBrandsWave51: Brand[] = [
  {
    id: "c1171",
    slug: "dakota-tallow",
    name: "Dakota Tallow",
    tagline: "Grass-fed tallow facial creams, remineralizing tooth powder, and after-sun butter",
    story: "A small-batch Dakota house that renders local grass-fed tallow into unscented and rosehip facial creams, eczema butters, belly and diaper balms, then mills a remineralizing tooth powder in citrus-mint through clove-orange and pours an after-sun butter. Flavor and scent options expand. Jar size stays one listing. Candles, seasoning rubs, and gift cards stay in the pantry.",
    location: "South Dakota",
    founded: 2021,
    categories: ["oral","skincare","sunscreen"],
    accent: "#7A4E2B",
    rating: 4.8,
    reviewCount: 186,
    followerCount: 4200,
    websiteUrl: "https://dakotatallow.com",
    logoUrl: "/brands/dakota-tallow.svg",
  },
  {
    id: "c1172",
    slug: "black-ivy-apothecary",
    name: "Black Ivy Apothecary",
    tagline: "Small-batch tallow SPF 30 sun cream, honey face cream, and herbal serums",
    story: "A handcrafted apothecary that blends 20% non-nano zinc into a tallow sun cream, then pours a tallow-and-honey face cream, enzyme cleansing oil, rose toner, eye oils, magnesium spray, and a soursop tincture. Individual formulas stay. Detox teas, elderberry syrup, and fire cider stay in the kitchen. Size stays one listing.",
    location: "United States",
    founded: 2020,
    categories: ["sunscreen","skincare","supplements"],
    accent: "#2F4A3A",
    rating: 4.7,
    reviewCount: 94,
    followerCount: 2100,
    websiteUrl: "https://www.blackivyapothecary.com",
    logoUrl: "/brands/black-ivy-apothecary.svg",
  },
  {
    id: "c1173",
    slug: "sun-and-honey",
    name: "Sun and Honey",
    tagline: "Waterless tallow mineral SPF 30 and a single restoration balm",
    story: "A two-SKU US tallow house: 25% zinc mineral sunscreen with grass-fed tallow, olive, shea, beeswax, and propolis, plus one unscented restoration balm. Individual formulas stay. The AM + PM ritual duo stays boxed.",
    location: "United States",
    founded: 2023,
    categories: ["sunscreen","skincare"],
    accent: "#C48A2B",
    rating: 4.6,
    reviewCount: 48,
    followerCount: 1600,
    websiteUrl: "https://sunandhoney.co",
    logoUrl: "/brands/sun-and-honey.svg",
  },
  {
    id: "c1174",
    slug: "harley-and-quinn",
    name: "Harley & Quinn Luxury Soap Co",
    tagline: "Tallow soap bars, Strand Theory shampoo bars, and aluminum-free cream deodorant",
    story: "A small luxury soap studio that pours tallow and plant-oil bars (Rose, Leather & Suede, Perfect Man), Strand Theory shampoo and conditioner bars, aluminum-free cream deodorant in grapefruit-lemon through sandalwood, magnesium creams, and a honey-tea lip. Scent options expand. Soap dishes, sisal pouches, room sprays, foaming hand wash, gift cards, and cream applicators stay on the shelf.",
    location: "United States",
    founded: 2019,
    categories: ["skincare","hair","deodorant"],
    accent: "#5C3A6E",
    rating: 4.7,
    reviewCount: 220,
    followerCount: 5400,
    websiteUrl: "https://harleyquinnsoap.com",
    logoUrl: "/brands/harley-and-quinn.svg",
  },
  {
    id: "c1175",
    slug: "vaya",
    name: "Vaya",
    tagline: "Sugar-free electrolyte stick packs in watermelon, lemon lime, raspberry, and grape",
    story: "A clean hydration house that mixes 1,500 mg of balanced electrolytes with vitamin C, zinc, plant colors, and organic sweeteners — zero sugar, four dedicated 30-pack flavors. Individual flavor pouches stay. Bottles, 100%-off gifts, intro packs, discovery packs, sample packs, and mixed variety boxes stay boxed.",
    location: "United States",
    founded: 2022,
    categories: ["electrolytes"],
    accent: "#2E6B8A",
    rating: 4.6,
    reviewCount: 310,
    followerCount: 7800,
    websiteUrl: "https://drinkvaya.com",
    logoUrl: "/brands/vaya.svg",
  },
  {
    id: "c1176",
    slug: "garage-brand-soap",
    name: "Garage Brand Soap",
    tagline: "Small-batch bar soaps and one magnesium-zinc aluminum-free deodorant",
    story: "A garage-poured soap house with barbershop, leather-and-brandy, charcoal tea-tree, and cedar-lavender bars, plus one orange-pepper-patchouli aluminum-free deodorant powered by magnesium and zinc. Individual bars and the deodorant stay. Gift sets, hats, tees, engraved dishes, and sisal bags stay in the shop.",
    location: "Florida",
    founded: 2018,
    categories: ["skincare","deodorant"],
    accent: "#3D4A38",
    rating: 4.8,
    reviewCount: 340,
    followerCount: 6100,
    websiteUrl: "https://garagebrandsoap.com",
    logoUrl: "/brands/garage-brand-soap.svg",
  },
  {
    id: "c1177",
    slug: "tallow-and-honey",
    name: "Tallow and Honey",
    tagline: "Bee-named tallow balms, Solar Bee sun balm, and Mane Bee hair treatment",
    story: "A honey-and-tallow studio that names every jar after the hive: Solar Bee sun balm, Bee Smooth hair balm, Nectar serum, Worker Bee, Queen Bee, Busy Bee collagen, and a beeswax lip. Individual formulas stay. Duos, trios, XL rituals, starter kits, and gift cards stay in the hive. Jar size stays one listing.",
    location: "United States",
    founded: 2021,
    categories: ["sunscreen","skincare","hair"],
    accent: "#B8860B",
    rating: 4.7,
    reviewCount: 128,
    followerCount: 2900,
    websiteUrl: "https://tallowandhoney.co",
    logoUrl: "/brands/tallow-and-honey.svg",
  },
  {
    id: "c1178",
    slug: "net-hydrate",
    name: "Net Hydrate",
    tagline: "Himalayan-salt electrolyte sticks in mixed berry and orange lemon",
    story: "A performance hydration house that blends Himalayan salt, coconut water powder, BCAAs, taurine, and trace minerals into 1 g sugar sticks sweetened with monk fruit and stevia. Mixed Berry and Orange Lemon stay. Wholesale WS cartons, variety pouches, towels, bottles, and POS displays stay at the club shop.",
    location: "United States",
    founded: 2023,
    categories: ["electrolytes"],
    accent: "#1F6B4A",
    rating: 4.5,
    reviewCount: 76,
    followerCount: 1800,
    websiteUrl: "https://nethydrate.com",
    logoUrl: "/brands/net-hydrate.svg",
  },
];
