import type { Brand } from "./types";

/** Wave 33: small organic / toxic-free brands across marketplace categories (c999+). */
export const catalogBrandsWave33: Brand[] = [
  {
    id: "c999",
    slug: "ohmygaia",
    name: "OHMYGAIA",
    tagline: "Spokane aluminum-free deodorant — organic coconut-shea sticks, 27 scents, no paraben aisle",
    story: "A runner-founded kitchen in Spokane that still pours aluminum-free, paraben-free deodorant from organic coconut oil and shea instead of a drugstore antiperspirant wall. Each scent stays as its own listing. Fragrance-oil rollers and gift cards stay on the perfume shelf.",
    location: "Spokane, Washington",
    founded: 2018,
    categories: ["deodorant","hair"],
    accent: "#5B7A3A",
    rating: 4.8,
    reviewCount: 890,
    followerCount: 14000,
    websiteUrl: "https://www.ohmygaia.com",
    logoUrl: "/brands/ohmygaia.png",
  },
  {
    id: "c1000",
    slug: "raised",
    name: "Raised",
    tagline: "Celtic-salt electrolytes plus magnesium glycinate — no sugar, no neon sports-drink stick",
    story: "A three-SKU hydration house that seasons water with Celtic salt, magnesium glycinate, and vitamins C and D instead of a maltodextrin packet. The electrolyte pouch stays. The nootropic energy powders stay as supplements. Empty bottles stay out.",
    location: "United States",
    founded: 2023,
    categories: ["electrolytes","supplements"],
    accent: "#1B4F72",
    rating: 4.6,
    reviewCount: 80,
    followerCount: 1200,
    websiteUrl: "https://drinkraised.com",
    logoUrl: "/brands/raised.svg",
  },
  {
    id: "c1001",
    slug: "norcal-organic",
    name: "NorCal Organic",
    tagline: "Northern California grass-fed organic whey — Jersey-cow concentrate, no isolate strip, no soy lecithin",
    story: "A farm-to-bag protein house that starts with organic milk from grass-fed Jersey cows on Rumiano pastures, then cold-filters a non-denatured whey instead of an acid-stripped isolate. Flavor variants stay as their own listings. Peanut-butter pantry jars, oat milk, and cashback widgets stay in the pantry.",
    location: "Northern California",
    founded: 2014,
    categories: ["protein","supplements"],
    accent: "#6B3E26",
    rating: 4.7,
    reviewCount: 640,
    followerCount: 8900,
    websiteUrl: "https://norcal-organic.com",
    logoUrl: "/brands/norcal-organic.svg",
  },
  {
    id: "c1002",
    slug: "impact-everyday",
    name: "Impact Everyday",
    tagline: "Canadian grass-fed whey and plant protein — monk fruit only, no hormone dairy, no gum shake",
    story: "A four-SKU Canadian kitchen that keeps protein as grass-fed whey or a plant blend, sweetened with monk fruit instead of a sugar-alcohol tub. Vanilla and chocolate stay as their own listings. Shaker cups stay in the cupboard.",
    location: "Canada",
    founded: 2022,
    categories: ["protein"],
    accent: "#2C5F4E",
    rating: 4.6,
    reviewCount: 70,
    followerCount: 1100,
    websiteUrl: "https://impacteveryday.ca",
    logoUrl: "/brands/impact-everyday.svg",
  },
  {
    id: "c1003",
    slug: "made-of",
    name: "Made Of",
    tagline: "Three-SKU New Zealand whey isolate — organic flavor, sunflower lecithin, no candy-protein aisle",
    story: "A tiny US house that only needed three jars: unflavored, vanilla, and chocolate New Zealand grass-fed whey isolate with organic flavor and a touch of sunflower lecithin. All three stay. Route shipping-protection widgets stay at checkout.",
    location: "United States",
    founded: 2021,
    categories: ["protein"],
    accent: "#3D6B5A",
    rating: 4.7,
    reviewCount: 120,
    followerCount: 1800,
    websiteUrl: "https://madeof.life",
    logoUrl: "/brands/made-of.svg",
  },
  {
    id: "c1004",
    slug: "thirsty-donkey",
    name: "Thirsty Donkey Skin Co",
    tagline: "Handcrafted mineral sun butter and eczema tallow care — non-nano zinc, no chemical-filter aisle",
    story: "A small US kitchen that makes a non-nano zinc mineral sun butter plus short-list soaps, body butters, and beard oil for eczema-prone skin instead of a fragrance-heavy cream wall. Scent variants stay as their own listings. Dog balm, bug spray, soap dishes, and yoni bars stay out.",
    location: "United States",
    founded: 2021,
    categories: ["sunscreen","skincare","hair"],
    accent: "#C45C26",
    rating: 4.7,
    reviewCount: 210,
    followerCount: 3400,
    websiteUrl: "https://thirstydonkeyskinco.com",
    logoUrl: "/brands/thirsty-donkey.svg",
  },
  {
    id: "c1005",
    slug: "dr-jen",
    name: "Dr. Jen Natural",
    tagline: "Dentist-made 10% nano-hydroxyapatite toothpaste — eggshell nHAp, no gadget whitening tray",
    story: "A dentist-formulated oral house that puts a full 10% nano-hydroxyapatite — including an eggshell-derived nHAp — into fluoride-free and Super Paste tubes instead of a charcoal-gadget aisle. Flavor variants stay as their own listings. Empty merch stays out.",
    location: "United States",
    founded: 2019,
    categories: ["oral"],
    accent: "#1565C0",
    rating: 4.8,
    reviewCount: 720,
    followerCount: 11000,
    websiteUrl: "https://drjennatural.com",
    logoUrl: "/brands/dr-jen.svg",
  },
  {
    id: "c1006",
    slug: "hair-fuel",
    name: "The Hair Fuel",
    tagline: "Botanical scalp serums and growth oils — no sulfate shampoo wall, no microneedle gadget kit",
    story: "A small botanical hair house that builds scalp serums, a growth mask, and an activating root oil instead of a silicone shampoo aisle. Finishing-mist scents stay as their own listings. Dermastamps, applicator bottles, and shower caps stay in the tool drawer.",
    location: "United States",
    founded: 2022,
    categories: ["hair"],
    accent: "#6B4F3A",
    rating: 4.7,
    reviewCount: 180,
    followerCount: 4200,
    websiteUrl: "https://thehairfuel.com",
    logoUrl: "/brands/hair-fuel.svg",
  },
  {
    id: "c1007",
    slug: "nurture-glow",
    name: "Nurture Glow Tallow",
    tagline: "Grass-fed tallow zinc balm and whipped creams — non-nano shield, no makeup-stick aisle",
    story: "A small tallow kitchen that pours a non-nano zinc sun balm and unscented or essential-oil whipped creams instead of a 40-ingredient lotion wall. Scent and whipped-vs-solid variants stay as their own listings. Cheek tints, glow sticks, gift cards, and shipping SKUs stay out.",
    location: "United States",
    founded: 2023,
    categories: ["sunscreen","skincare"],
    accent: "#8B6914",
    rating: 4.7,
    reviewCount: 150,
    followerCount: 2600,
    websiteUrl: "https://www.nurtureglowtallow.com",
    logoUrl: "/brands/nurture-glow.svg",
  },
];
