import type { Brand } from "./types";

/** Wave 42: small organic / toxic-free brands across marketplace categories (c1098+). */
export const catalogBrandsWave42: Brand[] = [
  {
    id: "c1098",
    slug: "tiffs-tallow",
    name: "Tiff's Tallow",
    tagline: "Utah mountain animal-based tallow — mineral barrier balm, whipped jars, aluminum-free deodorant",
    story: "A Utah mountain kitchen that whips grass-fed tallow into cosmetic-grade face-and-body jars, a mineral barrier balm for Texas-sun days, and an aluminum-free deodorant instead of a petroleum cream aisle. Individual whipped formulas, soaps, scrubs, and the sun balm stay. Ritual bundles, soap dishes, and shipping protection stay out.",
    location: "Utah, United States",
    founded: 2021,
    categories: ["sunscreen","skincare","deodorant"],
    accent: "#8B5A2B",
    rating: 4.8,
    reviewCount: 142,
    followerCount: 3200,
    websiteUrl: "https://tiffstallow.com",
    logoUrl: "/brands/tiffs-tallow.svg",
  },
  {
    id: "c1099",
    slug: "wild-prairie",
    name: "Wild Prairie Organics",
    tagline: "Four-ingredient organic tallow sun balm — 20% non-nano zinc, whipped jars, no wax-melt shop",
    story: "A prairie tallow house that keeps a 20% non-nano zinc sun balm and short-list whipped and solid tallows instead of a chemical-filter lotion wall. Blue tansy, frankincense, orange-vanilla, and lip scents stay as their own listings. Seven-pound cooking buckets, wax melts, and pamper bundles stay on the farm.",
    location: "United States",
    founded: 2023,
    categories: ["sunscreen","skincare"],
    accent: "#4A6741",
    rating: 4.7,
    reviewCount: 88,
    followerCount: 1900,
    websiteUrl: "https://wildprairieorganics.com",
    logoUrl: "/brands/wild-prairie.svg",
  },
  {
    id: "c1100",
    slug: "tallow-and-bloom",
    name: "Tallow and Bloom",
    tagline: "Whipped tallow scent jars plus a tinted zinc sun stick — vanilla, rose, beard balms, no pair wall",
    story: "A small tallow kitchen that whips vanilla, marshmallow, rose, lavender, and unscented jars and pours a cocoa-tinted non-nano zinc sun stick instead of a silicone SPF aisle. Individual whipped formulas, lips, and beard balms stay. Zero-price pair listings stay out.",
    location: "United States",
    founded: 2024,
    categories: ["sunscreen","skincare","hair"],
    accent: "#C4A484",
    rating: 4.6,
    reviewCount: 54,
    followerCount: 1100,
    websiteUrl: "https://tallowandbloom.myshopify.com",
    logoUrl: "/brands/tallow-and-bloom.svg",
  },
  {
    id: "c1101",
    slug: "pasture-and-posies",
    name: "Pasture & Posies",
    tagline: "Xenia, Ohio farm-to-skin tallow — Little Posies sun stick, Sun Shield whip, deodorant scents",
    story: "Seven Arrows Farm's Pasture & Posies line renders the same Ohio pasture tallow it raises into a kids sun stick, Sun Shield whipped tallow, lotion and deodorant scents, and short-list serums instead of a synthetic-moisturizer wall. Individual formulas stay. Empty roller bottles stay in the barn.",
    location: "Xenia, Ohio",
    founded: 2022,
    categories: ["sunscreen","skincare","deodorant"],
    accent: "#6B4F2A",
    rating: 4.7,
    reviewCount: 70,
    followerCount: 1400,
    websiteUrl: "https://7arrowsfarm.com",
    logoUrl: "/brands/pasture-and-posies.svg",
  },
  {
    id: "c1102",
    slug: "bloom-tallow",
    name: "Bloom Tallow Co",
    tagline: "Organic grass-fed tallow — Bare, Meadowflower, deodorant scents, no merch wall",
    story: "A grass-fed tallow house that keeps Bare, Original, Meadowflower, Coconut Cloud, and Herbal Harmony creams plus aluminum-free deodorant and lip scents instead of a fragrance-lotion aisle. Individual formulas stay. No merch, no gift cards.",
    location: "United States",
    founded: 2023,
    categories: ["skincare","deodorant"],
    accent: "#C45C7A",
    rating: 4.6,
    reviewCount: 95,
    followerCount: 2100,
    websiteUrl: "https://bloomtallow.com",
    logoUrl: "/brands/bloom-tallow.svg",
  },
  {
    id: "c1103",
    slug: "bloom-and-branch",
    name: "Bloom and Branch Naturals",
    tagline: "Tallow and non-nano zinc sunblock plus whipped cream and soap scents — no candle shop",
    story: "A small naturals kitchen that pours grass-fed tallow with non-nano zinc into a tinted sunblock, then keeps whipped cream, body butter, soap, chapstick, beard butter, and a healing salve. Individual scent formulas stay. Bug spray, room spray, candles, wax melts, and beeswax wraps stay out.",
    location: "United States",
    founded: 2023,
    categories: ["sunscreen","skincare","hair"],
    accent: "#3D5A3A",
    rating: 4.6,
    reviewCount: 48,
    followerCount: 900,
    websiteUrl: "https://bloomandbranchnaturals.com",
    logoUrl: "/brands/bloom-and-branch.svg",
  },
  {
    id: "c1104",
    slug: "soulful-bloom",
    name: "Soulful Bloom",
    tagline: "Gigi's Natural Sun tallow zinc plus whipped tallow scents — no inhaler shop",
    story: "A Gigi-named tallow apothecary that blends tallow, non-nano zinc, carrot seed, and raspberry seed into Natural Sun, then keeps tinted face tallow, vanilla-coconut, lavender, peppermint, and face serums. Tallows, sun, lips, and bum butter stay. Nasal inhalers, migraine rollers, sampler bags, and bug tallow stay out.",
    location: "United States",
    founded: 2023,
    categories: ["sunscreen","skincare"],
    accent: "#7A5C3A",
    rating: 4.6,
    reviewCount: 62,
    followerCount: 1300,
    websiteUrl: "https://shopsoulfulbloom.com",
    logoUrl: "/brands/soulful-bloom.svg",
  },
  {
    id: "c1105",
    slug: "danyelli-laurette",
    name: "Danyelli Laurette",
    tagline: "Scarsdale plastic-free shampoo and conditioner bars — Radiant Rescue, Naturally Nourished, no candle shop",
    story: "A Scarsdale hairstylist house that pours organic shampoo and conditioner bars plus bottle infusions instead of a sulfate-and-silicone salon wall. Radiant Rescue, Naturally Nourished, Sleek Solution, Zen Combo, and body soaps stay. Candles stay out.",
    location: "Scarsdale, New York",
    founded: 2020,
    categories: ["hair","skincare"],
    accent: "#2C5F4E",
    rating: 4.7,
    reviewCount: 180,
    followerCount: 4200,
    websiteUrl: "https://danyellilaurette.com",
    logoUrl: "/brands/danyelli-laurette.svg",
  },
  {
    id: "c1106",
    slug: "ceelike",
    name: "CEELIKE",
    tagline: "Nano-hydroxyapatite toothpaste, tablets, and mouthwash — mint, pineapple, camellia, no gadget wall",
    story: "A dedicated unused n-HA oral house that keeps fluoride-free pastes, 5% tablets, tooth powder, mouthwash, and smile-mist flavors instead of a whitening-gadget aisle. Individual formulas stay. Orthodontic wax, breath pearls, color-correcting sticks, whitening strips, nasal sticks, and kit stacks stay out.",
    location: "Independent / DTC",
    founded: 2023,
    categories: ["oral"],
    accent: "#2C6E49",
    rating: 4.5,
    reviewCount: 210,
    followerCount: 5600,
    websiteUrl: "https://ceelike.com",
    logoUrl: "/brands/ceelike.svg",
  },
  {
    id: "c1107",
    slug: "farm-to-skin",
    name: "Farm to Skin",
    tagline: "Farm botanicals plus zinc Sun Prime — individual cleansers and serums, no $200 routine wall",
    story: "A farm-botanical house that keeps Sun Prime with zinc oxide and individual cleansers, essences, serums, and moisturizers instead of a chemical-filter spa kit wall. Single formulas stay. Two-hundred-dollar routines, gua sha, dry brushes, candles, gift cards, and empty pouches stay out.",
    location: "United States",
    founded: 2019,
    categories: ["skincare","sunscreen"],
    accent: "#1F6B5B",
    rating: 4.6,
    reviewCount: 130,
    followerCount: 2800,
    websiteUrl: "https://farmtoskin.com",
    logoUrl: "/brands/farm-to-skin.svg",
  },
];
