import type { Brand } from "./types";

/** Wave 93: small organic / toxic-free brands across marketplace categories (c1427+). */
export const catalogBrandsWave93: Brand[] = [
  {
    id: "c1427",
    slug: "zoobalab",
    name: "ZOOBA Lab",
    tagline: "Fluoride-free mineralizing toothpaste with 5% nano-hydroxyapatite",
    story:
      "The leftover unused one-SKU n-HA oral house after dedicated multi-SKU shops ran out — a single fluoride-free mineralizing paste with 5% nano-hydroxyapatite and bentonite clay. Pack count is size. Cart.js is USD. The page is a key-ingredient essay (leave empty).",
    location: "United States",
    founded: 2022,
    categories: ["oral"],
    accent: "#2C5F4E",
    rating: 4.6,
    reviewCount: 48,
    followerCount: 900,
    websiteUrl: "https://zoobalab.com",
    logoUrl: "/brands/zoobalab.svg",
  },
  {
    id: "c1428",
    slug: "island-butter",
    name: "Island Butter",
    tagline: "Tampa mineral sun butter — reef-safe non-nano zinc, no white cast",
    story:
      "The leftover unused one-SKU mineral sun house after wave4–92 — all-natural reef-safe sun butter from Tampa. 3.4 oz vs 5 oz is size — keep the 5 oz everyday jar. Cart.js is USD. The page is a benefit essay (leave empty).",
    location: "Tampa, FL",
    founded: 2023,
    categories: ["sunscreen"],
    accent: "#C45C26",
    rating: 4.7,
    reviewCount: 86,
    followerCount: 1800,
    websiteUrl: "https://islandbutter.co",
    logoUrl: "/brands/island-butter.svg",
  },
  {
    id: "c1429",
    slug: "blueshift",
    name: "Blueshift Nutrition",
    tagline: "Himalayan-salt electrolytes and real-fruit daily powders — no sucralose",
    story:
      "The unused clean hydration leftover after wave4–92 — Lemon Raspberry electrolytes powered by Himalayan pink salt plus daily powders (sleep, calm, turmeric, immune, joint, skin, energy, recover, pre-workout). Flavors already live on titles. Stick-pack count is size — keep 10-count. Bottles, caps, and gift cards stay boxed. Cart.js is USD. Pages are performance-copy marketing (leave empty).",
    location: "United States",
    founded: 2018,
    categories: ["electrolytes", "supplements"],
    accent: "#1B4F72",
    rating: 4.6,
    reviewCount: 420,
    followerCount: 6400,
    websiteUrl: "https://blueshiftnutrition.com",
    logoUrl: "/brands/blueshift.svg",
  },
  {
    id: "c1430",
    slug: "natural-force",
    name: "Natural Force",
    tagline: "Organic California grass-fed whey, collagen, and bone-broth protein",
    story:
      "The unused organic protein leftover after wave4–92 — Certified Organic grass-fed whey from California Jersey herds (Flavor expands Unflavored / Vanilla Bean / Cacao Bean), plus one-ingredient collagen, marine collagen, and organic bone-broth protein. 1 lb vs 5 lb / serving count is size. MCT oils and coffee stay boxed. Cart.js is USD. Pages are clean-label marketing (leave empty); hardcode the published one-ingredient unflavored whey, collagen, marine collagen, and bone-broth lists.",
    location: "United States",
    founded: 2014,
    categories: ["protein", "supplements"],
    accent: "#3D5A2C",
    rating: 4.7,
    reviewCount: 2100,
    followerCount: 28000,
    websiteUrl: "https://naturalforce.com",
    logoUrl: "/brands/natural-force.png",
  },
  {
    id: "c1431",
    slug: "tiffs-tallow",
    name: "Tiff's Tallow",
    tagline: "Utah garden tallow — mineral sun balm, aluminum-free deodorant, and whipped creams",
    story:
      "The unused Morgan, Utah tallow leftover after wave4–92 — baking-soda-free deodorant, Fun In The Sun mineral barrier balm, whipped tallows, goat-milk soaps, and garden sugar scrubs. Size / 2 oz vs 4 oz is size. Rituals, bundles, shipping protection, and soap dishes stay boxed. Cart.js is USD. Hardcode the published deodorant, soap, and Garden Goddess lists — sun-balm and most whipped pages are farm-story marketing (leave empty).",
    location: "Morgan, UT",
    founded: 2021,
    categories: ["deodorant", "sunscreen", "skincare"],
    accent: "#8B5A3C",
    rating: 4.8,
    reviewCount: 310,
    followerCount: 5200,
    websiteUrl: "https://tiffstallow.com",
    logoUrl: "/brands/tiffs-tallow.svg",
  },
  {
    id: "c1432",
    slug: "josh-rosebrook",
    name: "Josh Rosebrook",
    tagline: "Organic herbal hair and skin — mineral SPF 30 day cream, nourish shampoo, vital balm",
    story:
      "The unused organic herbal leftover after wave4–92 — Nourish and Balance wash-day, firm-hold spray, Lift, hair cream, plus farm-botanical skincare and non-nano zinc Nutrient Day Cream SPF 30 (untinted and tinted). 8 oz / 1.7 oz is size; 16 oz and refill cartridges stay boxed. Samples, kits, trios, gift cards, brushes, and cotton rounds stay boxed. Cart.js is USD. Pages publish long comma INCI.",
    location: "United States",
    founded: 2010,
    categories: ["hair", "skincare", "sunscreen"],
    accent: "#5B7A3A",
    rating: 4.7,
    reviewCount: 890,
    followerCount: 18000,
    websiteUrl: "https://joshrosebrook.com",
    logoUrl: "/brands/josh-rosebrook.png",
  },
];
