import type { Brand } from "./types";

/** Wave 7: small organic / toxic-free brands across marketplace categories (c521+). */
export const catalogBrandsWave7: Brand[] = [
  {
    id: "c521",
    slug: "little-hands-hawaii",
    name: "Little Hands Hawaii",
    tagline: "Maui-made mineral sunscreen for keiki and saltwater days",
    story: "A Maui mama brand that started with reef-minded zinc for little hands — non-nano mineral sunscreen, whipped butters, and baby balms without chemical filters or a greasy white cast.",
    location: "Maui, HI",
    founded: 2016,
    categories: ["sunscreen","skincare"],
    accent: "#E8A54B",
    rating: 4.8,
    reviewCount: 640,
    followerCount: 8900,
    websiteUrl: "https://littlehandshawaii.com",
    logoUrl: "/brands/little-hands-hawaii.svg",
  },
  {
    id: "c522",
    slug: "the-rising",
    name: "The Rising",
    tagline: "Mediterranean mineral SPF that wears like skincare",
    story: "100% mineral, fragrance-free SPF 50 from the Mediterranean — non-nano zinc, organic botanicals, and a fermented pomegranate complex instead of the chemical-filter cocktail.",
    location: "Spain / Mediterranean",
    founded: 2023,
    categories: ["sunscreen","skincare"],
    accent: "#C45C26",
    rating: 4.7,
    reviewCount: 180,
    followerCount: 4100,
    websiteUrl: "https://therisingspf.com",
    logoUrl: "/brands/the-rising.svg",
  },
  {
    id: "c523",
    slug: "we-are-feel-good",
    name: "We Are Feel Good Inc",
    tagline: "Australian sun care for sport, salt, and sensitive skin",
    story: "Gold Coast formulas built for the kind of sun that actually burns — mineral and hybrid SPF 50+, baby options, and sport lotions that skip the greasy drugstore finish.",
    location: "Gold Coast, Australia",
    founded: 2018,
    categories: ["sunscreen"],
    accent: "#0E7490",
    rating: 4.7,
    reviewCount: 2100,
    followerCount: 34000,
    websiteUrl: "https://wearefeelgoodinc.com.au",
    logoUrl: "/brands/we-are-feel-good.svg",
  },
  {
    id: "c524",
    slug: "key-nutrients",
    name: "Key Nutrients",
    tagline: "Sugar-free electrolyte powder without the candy-aisle junk",
    story: "A short-list hydration powder — potassium, magnesium, and sodium without sugar, dyes, or a mystery flavor lab. Stick packs and tubs for people who want the salts and nothing else.",
    location: "United States",
    founded: 2015,
    categories: ["electrolytes"],
    accent: "#1B4F72",
    rating: 4.6,
    reviewCount: 4800,
    followerCount: 16000,
    websiteUrl: "https://keynutrients.com",
    logoUrl: "/brands/key-nutrients.png",
  },
  {
    id: "c525",
    slug: "tailwind",
    name: "Tailwind Nutrition",
    tagline: "Endurance fuel and electrolytes from Durango dirtbags",
    story: "Born in Colorado for all-day efforts — complete electrolytes plus easy carbs in a bottle, no gut bombs, no weird gums. Mixes that taste like a trail snack, not a chemistry set.",
    location: "Durango, CO",
    founded: 2012,
    categories: ["electrolytes"],
    accent: "#365314",
    rating: 4.7,
    reviewCount: 6200,
    followerCount: 28000,
    websiteUrl: "https://tailwindnutrition.com",
    logoUrl: "/brands/tailwind.png",
  },
  {
    id: "c526",
    slug: "gomacro",
    name: "GoMacro",
    tagline: "USDA organic plant protein bars from a Wisconsin farm family",
    story: "MacroBars made on a family farm — organic plant protein, real food you can pronounce, and flavors that skip stevia aftertaste, sugar alcohols, and soy-isolate sludge.",
    location: "Viola, WI",
    founded: 2004,
    categories: ["protein"],
    accent: "#16A34A",
    rating: 4.6,
    reviewCount: 9800,
    followerCount: 72000,
    websiteUrl: "https://gomacro.com",
    logoUrl: "/brands/gomacro.png",
  },
  {
    id: "c527",
    slug: "iqbar",
    name: "IQBAR",
    tagline: "Plant protein bars with brain nutrients, no junk fillers",
    story: "A Boston-born bar that treats protein like brain food — plant protein, MCTs, lion’s mane and lion’s-share flavor, without a candy-bar ingredient list.",
    location: "Boston, MA",
    founded: 2017,
    categories: ["protein"],
    accent: "#5B21B6",
    rating: 4.5,
    reviewCount: 7400,
    followerCount: 41000,
    websiteUrl: "https://eatiqbar.com",
    logoUrl: "/brands/iqbar.png",
  },
  {
    id: "c528",
    slug: "nu-deo",
    name: "NU-DEO",
    tagline: "Baking-soda-free, wax-free deodorant from Quebec",
    story: "Handcrafted in Saint-Lazare — shea, magnesium, and essential-oil blends without aluminum, bicarb rash, or the waxy stick that stains your shirts.",
    location: "Saint-Lazare, QC",
    founded: 2021,
    categories: ["deodorant"],
    accent: "#2C5F4E",
    rating: 4.8,
    reviewCount: 210,
    followerCount: 2400,
    websiteUrl: "https://www.nu-deo.ca",
    logoUrl: "/brands/nu-deo.svg",
  },
  {
    id: "c529",
    slug: "twisted-duo",
    name: "Twisted Duo",
    tagline: "Singapore cream deodorant that survives humidity",
    story: "Small-batch cream deodorant built for tropical heat — plant-based, aluminum-free, and tested in Singapore humidity instead of a temperate lab.",
    location: "Singapore",
    founded: 2019,
    categories: ["deodorant"],
    accent: "#BE185D",
    rating: 4.7,
    reviewCount: 860,
    followerCount: 12000,
    websiteUrl: "https://www.twstdduo.com",
    logoUrl: "/brands/twisted-duo.svg",
  },
  {
    id: "c530",
    slug: "willow-valley",
    name: "Willow Valley Wellness",
    tagline: "Ontario small-batch deodorant paste, no aluminum or wax",
    story: "Hand-poured in Ontario — coconut oil, shea, mango butter, and clay in a paste that skips aluminum, wax fillers, and synthetic fragrance.",
    location: "Ontario, Canada",
    founded: 2020,
    categories: ["deodorant","skincare"],
    accent: "#6B3E26",
    rating: 4.8,
    reviewCount: 340,
    followerCount: 3800,
    websiteUrl: "https://willowvalleywellness.com",
    logoUrl: "/brands/willow-valley.svg",
  },
  {
    id: "c531",
    slug: "livfresh",
    name: "LivFresh",
    tagline: "Dentist-developed gel toothpaste without the foam circus",
    story: "A periodontist’s gel that ditches SLS foam for a short, enamel-first formula — mint pastes and mouthwash for people who actually read the oral-care label.",
    location: "United States",
    founded: 2018,
    categories: ["oral"],
    accent: "#0E7490",
    rating: 4.6,
    reviewCount: 1900,
    followerCount: 14000,
    websiteUrl: "https://getlivfresh.com",
    logoUrl: "/brands/livfresh.svg",
  },
  {
    id: "c532",
    slug: "desert-essence",
    name: "Desert Essence",
    tagline: "Tea tree oral care and plant formulas since 1978",
    story: "Long Island–born tea tree toothpaste, oils, and wash-day basics — naturally sourced, cruelty-free, and still skipping the usual oral-care junk drawer.",
    location: "Hauppauge, NY",
    founded: 1978,
    categories: ["oral","skincare","hair"],
    accent: "#4D7C0F",
    rating: 4.6,
    reviewCount: 8200,
    followerCount: 38000,
    websiteUrl: "https://desertessence.com",
    logoUrl: "/brands/desert-essence.png",
  },
  {
    id: "c533",
    slug: "upcircle",
    name: "UpCircle",
    tagline: "London upcycled skincare from coffee, fruit, and leftover botanicals",
    story: "Founded on a coffee-ground scrub and a stubborn idea — waste is an ingredient. Certified organic-leaning formulas that turn leftover botanicals into face care, not landfill.",
    location: "London, United Kingdom",
    founded: 2016,
    categories: ["skincare"],
    accent: "#2F4F4F",
    rating: 4.7,
    reviewCount: 5600,
    followerCount: 89000,
    websiteUrl: "https://upcirclebeauty.com",
    logoUrl: "/brands/upcircle.svg",
  },
  {
    id: "c534",
    slug: "kypris",
    name: "Kypris",
    tagline: "Alchemist-clean serums with a short, potent INCI list",
    story: "Small-batch US formulas that treat botanicals like actives — antioxidant serums, creams, and oils without the fragrance circus or a 40-ingredient filler list.",
    location: "United States",
    founded: 2014,
    categories: ["skincare"],
    accent: "#7A6A53",
    rating: 4.7,
    reviewCount: 2100,
    followerCount: 18000,
    websiteUrl: "https://kyprisbeauty.com",
    logoUrl: "/brands/kypris.png",
  },
  {
    id: "c535",
    slug: "in-fiore",
    name: "In Fiore",
    tagline: "San Francisco botanical balms, no synthetic perfume fog",
    story: "Julie Elliott’s atelier of plant essences — concentrated balms and oils distilled like perfume, without the usual synthetic fragrance pile-on.",
    location: "San Francisco, CA",
    founded: 2003,
    categories: ["skincare"],
    accent: "#9A3412",
    rating: 4.8,
    reviewCount: 740,
    followerCount: 22000,
    websiteUrl: "https://infiore.net",
    logoUrl: "/brands/in-fiore.png",
  },
  {
    id: "c536",
    slug: "unscented-co",
    name: "The Unscented Company",
    tagline: "Fragrance-free refillable wash-day basics from Montreal",
    story: "Montreal formulas for people who are done with perfume in shampoo — fragrance-free, refillable bottles, and a short free-from list that actually means unscented.",
    location: "Montreal, QC",
    founded: 2018,
    categories: ["hair","skincare"],
    accent: "#1A1A1A",
    rating: 4.6,
    reviewCount: 2800,
    followerCount: 19000,
    websiteUrl: "https://unscentedco.com",
    logoUrl: "/brands/unscented-co.svg",
  },
  {
    id: "c537",
    slug: "oway",
    name: "Oway",
    tagline: "Organic Italian haircare from a Bolognese farm",
    story: "Bologna-born organic professional haircare — biodynamic botanicals, no silicones or sulfates, and farm-grown extracts instead of a salon chemical fog.",
    location: "Bologna, Italy",
    founded: 1997,
    categories: ["hair"],
    accent: "#365314",
    rating: 4.7,
    reviewCount: 1600,
    followerCount: 31000,
    websiteUrl: "https://oway.com",
    logoUrl: "/brands/oway.svg",
  },
  {
    id: "c538",
    slug: "hairstory",
    name: "Hairstory",
    tagline: "New Wash cleanser that skips daily shampoo damage",
    story: "A New York hair-care house that asked why we shampoo every day — New Wash, a milk-like cleanser that skips sulfates, silicones, and the usual foam-and-strip cycle.",
    location: "New York, NY",
    founded: 2016,
    categories: ["hair"],
    accent: "#BE185D",
    rating: 4.6,
    reviewCount: 4200,
    followerCount: 56000,
    websiteUrl: "https://hairstory.com",
    logoUrl: "/brands/hairstory.png",
  },
  {
    id: "c539",
    slug: "perelel",
    name: "Perelel",
    tagline: "Trimester-specific prenatal, no gummy junk",
    story: "OB-GYN-built daily packs that change with the trimester — methylated B vitamins, mineral forms you can absorb, and a formula that skips the candy-aisle prenatal.",
    location: "Los Angeles, CA",
    founded: 2020,
    categories: ["supplements"],
    accent: "#BE185D",
    rating: 4.8,
    reviewCount: 3800,
    followerCount: 64000,
    websiteUrl: "https://perelelhealth.com",
    logoUrl: "/brands/perelel.svg",
  },
  {
    id: "c540",
    slug: "om-mushrooms",
    name: "OM Mushroom Superfood",
    tagline: "USDA organic mushroom powders grown in California",
    story: "Carlsbad-grown organic mushrooms — lion’s mane, reishi, cordyceps, and blends you stir into coffee instead of swallowing a mystery capsule from a warehouse.",
    location: "Carlsbad, CA",
    founded: 2013,
    categories: ["supplements"],
    accent: "#6B3E26",
    rating: 4.6,
    reviewCount: 5400,
    followerCount: 48000,
    websiteUrl: "https://ommushrooms.com",
    logoUrl: "/brands/om-mushrooms.png",
  },
];
