import type { Brand } from "./types";

/** Wave 65: small organic / toxic-free brands across marketplace categories (c1261+). */
export const catalogBrandsWave65: Brand[] = [
  {
    id: "c1261",
    slug: "mineral-daily",
    name: "Mineral Daily",
    tagline: "Four-flavor nano-hydroxyapatite chewing gum for the hours between brushing",
    story: "A small US oral house that puts published nano-hydroxyapatite into a xylitol gum you chew after coffee, not only at the sink. Wild Orange, Spearmint, Blackcurrant, and Cinnamon Bark stay as separate titles. 2/4/8-pack counts are size, not flavor. There is no merch aisle.",
    location: "United States",
    founded: 2024,
    categories: ["oral"],
    accent: "#3D6B5A",
    rating: 4.6,
    reviewCount: 48,
    followerCount: 900,
    websiteUrl: "https://mineraldaily.com",
    logoUrl: "/brands/mineral-daily.svg",
  },
  {
    id: "c1262",
    slug: "aura-glow-tallow",
    name: "Aura Glow Tallow",
    tagline: "Ancestral tallow mineral SPF, aluminum-free deodorant, and whipped farm lotions",
    story: "A small-batch ancestral beauty house that pours grass-fed tallow into a mineral SPF balm, grapefruit-cedar deodorant, whipped lotions, a 3-in-1 soap, and a bergamot beard balm. Jar size is not a flavor. The dog paw balm stays boxed.",
    location: "United States",
    founded: 2023,
    categories: ["sunscreen","skincare","deodorant","hair"],
    accent: "#C4A35A",
    rating: 4.7,
    reviewCount: 62,
    followerCount: 1400,
    websiteUrl: "https://auraglowtallow.com",
    logoUrl: "/brands/aura-glow-tallow.svg",
  },
  {
    id: "c1263",
    slug: "ofp-farms",
    name: "OFP Farms",
    tagline: "California goat-milk and grass-fed tallow soaps, lotions, deodorant, and a shampoo bar",
    story: "Denise and Cory left hospice and auto-electric work for seven acres in the Sierra foothills, then started rendering tallow and milking goats for bars, lotions, aluminum-free deodorant, a rosemary-tea-tree shampoo bar, and Goat Kisses lip balms. Deodorant, lip, beard, and magnesium-lotion scents expand. Bundles, gift boxes, 4-pack smack packs, soap sacks, solid perfume, and wooden combs stay boxed. Bar size is not a flavor.",
    location: "West Point, CA",
    founded: 2018,
    categories: ["skincare","deodorant","hair"],
    accent: "#6B8F4E",
    rating: 4.8,
    reviewCount: 186,
    followerCount: 4200,
    websiteUrl: "https://ofpfarms.com",
    logoUrl: "/brands/ofp-farms.svg",
  },
  {
    id: "c1264",
    slug: "untamed-mother",
    name: "Untamed Mother Co.",
    tagline: "Grass-fed tallow sun sticks, goat-milk lotions, and homestead soap bars",
    story: "A homestead tallow shop that pairs goat milk with grass-fed suet for sun sticks, whipped jars, everyday balms, drawing salve, and named soap bars. Soap-name, infusion, lotion, and lip scents expand. Bug spray, dog paw balm, dish soap, gua sha, soap savers, and ritual bundles stay boxed. Jar size is not a flavor.",
    location: "United States",
    founded: 2022,
    categories: ["skincare","sunscreen"],
    accent: "#8B5A3A",
    rating: 4.7,
    reviewCount: 94,
    followerCount: 2100,
    websiteUrl: "https://untamedmotherco.com",
    logoUrl: "/brands/untamed-mother.svg",
  },
  {
    id: "c1265",
    slug: "tallow-and-hive",
    name: "Tallow and Hive",
    tagline: "Bison tallow and raw-honey balms, whips, and oatmeal-lavender bars",
    story: "A tiny bison-tallow house that blends rendered fat with raw honey into unscented and scented balms and whips, plus oatmeal-lavender and honey-castor bars. Scented vs unscented already live on separate titles. Mini jars are size, not flavor, and stay boxed so the full jar is the listing.",
    location: "United States",
    founded: 2023,
    categories: ["skincare"],
    accent: "#A67C4E",
    rating: 4.6,
    reviewCount: 38,
    followerCount: 700,
    websiteUrl: "https://tallowandhive.com",
    logoUrl: "/brands/tallow-and-hive.svg",
  },
];
