import type { Brand } from "./types";

/** Wave 18: small organic / toxic-free brands across marketplace categories (c738+). */
export const catalogBrandsWave18: Brand[] = [
  {
    id: "c738",
    slug: "sol-sista",
    name: "Sol Sista Collective",
    tagline: "Australian mineral SPF 50+ balms — non-nano zinc that wears like a tinted butter, not a grease slick",
    story: "Britt James built Sol Sista for wave-chasers who were done choosing between reef-minded zinc and something you'd actually wear. BUTTA BLOCK™ is TGA-listed SPF 50+, 100% mineral, four-hour water resistant, and tinted like a BB cream — no chemical filters, no ghost cast. Outdoor beauty from Australia, packed in recycled tubes.",
    location: "Australia",
    founded: 2021,
    categories: ["sunscreen","skincare"],
    accent: "#C45C26",
    rating: 4.8,
    reviewCount: 840,
    followerCount: 22000,
    websiteUrl: "https://solsistacollective.com",
    logoUrl: "/brands/sol-sista.svg",
  },
  {
    id: "c739",
    slug: "project-reef",
    name: "Project Reef",
    tagline: "Reef-safe SPF 30 and 50 plus after-sun — mineral protection that actually funds the reef",
    story: "A sun-care studio that treats the ocean as a customer. Reef-safe SPF 30 and 50, a sunstick for faces that hate lotion, and after-sun cooling that skips the chemical-filter fog. Buy sunscreen, help the reef — short mineral lists instead of a drugstore UV cocktail.",
    location: "United States",
    founded: 2020,
    categories: ["sunscreen","skincare"],
    accent: "#1A7A8C",
    rating: 4.7,
    reviewCount: 310,
    followerCount: 8600,
    websiteUrl: "https://projectreef.com",
    logoUrl: "/brands/project-reef.svg",
  },
  {
    id: "c740",
    slug: "sifa",
    name: "Sifa Natural Skin",
    tagline: "Grass-fed tallow sunblock and whipped creams — mineral zinc, no synthetic fragrance fog",
    story: "A small kitchen that renders grass-fed tallow into sunblock, vegan mineral backup, whipped face cream, and a moist hair-and-body wash. Short organic oil lists, magnesium for nights that won't quit, and zinc that sits on skin instead of a chemical-filter stack. Ancestral care without a 40-ingredient label.",
    location: "United States",
    founded: 2021,
    categories: ["sunscreen","skincare","hair"],
    accent: "#6B3E26",
    rating: 4.8,
    reviewCount: 190,
    followerCount: 4200,
    websiteUrl: "https://sifaorganicskin.myshopify.com",
    logoUrl: "/brands/sifa.svg",
  },
  {
    id: "c741",
    slug: "cleonse",
    name: "Cleonse",
    tagline: "Three-ingredient organic electrolytes — real fruit, cane sugar, French grey sea salt",
    story: "The anti-sports-drink. Cleonse is organic fruit powder, organic cane sugar, and French grey sea salt — 500mg sodium and 85+ trace minerals with nothing artificial to apologize for. No stevia aftertaste, no dye circus, no 15-line flavor system. Hydration that still tastes like fruit and salt.",
    location: "United States",
    founded: 2023,
    categories: ["electrolytes"],
    accent: "#E27D60",
    rating: 4.7,
    reviewCount: 160,
    followerCount: 5100,
    websiteUrl: "https://cleonse.com",
    logoUrl: "/brands/cleonse.svg",
  },
  {
    id: "c742",
    slug: "doingwell",
    name: "doingwell",
    tagline: "Zero-sugar daily hydration sticks — monk fruit, Himalayan salt, no stevia or maltodextrin",
    story: "High-sodium stick packs for people who sweat and still want a readable label. Organic coconut water, Himalayan pink salt, and organic monk fruit — no stevia, no sugar alcohols, no maltodextrin flavor fog. Mango daily hydration without a locker-room candy aisle.",
    location: "United States",
    founded: 2022,
    categories: ["electrolytes"],
    accent: "#2A9D8F",
    rating: 4.6,
    reviewCount: 220,
    followerCount: 7400,
    websiteUrl: "https://doingwell.health",
    logoUrl: "/brands/doingwell.svg",
  },
  {
    id: "c743",
    slug: "stay-wyld",
    name: "Stay Wyld Organics",
    tagline: "Pemberton-grown fruiting bodies — doctor-formulated mushrooms, peach electrolytes, no China grain bags",
    story: "They grow it in Pemberton, BC: substrate to fruiting body, harvest to extract, under one roof. Third-party tested in Canada, no mycelium-on-grain shortcuts, plus Just Peachy electrolytes cut with lion's mane. Functional mushrooms from a working Canadian farm, not a rebranded import sack.",
    location: "Pemberton, BC, Canada",
    founded: 2019,
    categories: ["supplements","electrolytes"],
    accent: "#3E2723",
    rating: 4.8,
    reviewCount: 640,
    followerCount: 18000,
    websiteUrl: "https://staywyldorganics.com",
    logoUrl: "/brands/stay-wyld.svg",
  },
  {
    id: "c744",
    slug: "happy-way",
    name: "Happy Way",
    tagline: "Australian whey and vegan protein — real-food flavors, hydration sachets, no neon gym stack",
    story: "A family protein kitchen from Australia that treats flavor like food: tiramisu, choc banana, mango cream — whey and plant options without a candy-aisle sweetener drawer. Plus daily hydration sachets for the days you actually sweat. Protein powder you'd let a kid taste.",
    location: "Australia",
    founded: 2016,
    categories: ["protein","electrolytes"],
    accent: "#E8A0BF",
    rating: 4.7,
    reviewCount: 2100,
    followerCount: 45000,
    websiteUrl: "https://happyway.com.au",
    logoUrl: "/brands/happy-way.svg",
  },
  {
    id: "c745",
    slug: "talgh",
    name: "Talgh",
    tagline: "Certified-organic grass-fed tallow deodorant — magnesium, no aluminum, no baking soda",
    story: "Tallow as the base, not a gimmick. Talgh pours certified-organic, 100% grass-fed American tallow with arrowroot, kaolin, and magnesium hydroxide — no aluminum, no bicarbonate rash, no seed-oil pile. Essential oils that actually scored EWG 1–2, packed in FSC paper with algae ink. Underarm care that reads like a kitchen recipe.",
    location: "United States",
    founded: 2023,
    categories: ["deodorant"],
    accent: "#5B7C6A",
    rating: 4.8,
    reviewCount: 140,
    followerCount: 3800,
    websiteUrl: "https://talgh.co",
    logoUrl: "/brands/talgh.svg",
  },
  {
    id: "c746",
    slug: "carina-organics",
    name: "Carina Organics",
    tagline: "Canadian certified-organic shampoo, crystal deodorant, and baby wash — short lists, refill jugs",
    story: "A Vancouver-area organic house that still makes shampoo you'd recognize on a farm label: unscented baby wash, sweet pea cream, liquid crystal deodorant, and four-litre refill jugs so you're not buying another plastic mountain. Certified organic, family-run, no perfume-drawer fog.",
    location: "Canada",
    founded: 2003,
    categories: ["hair","deodorant","skincare"],
    accent: "#4A7C59",
    rating: 4.7,
    reviewCount: 980,
    followerCount: 16000,
    websiteUrl: "https://carinaorganics.com",
    logoUrl: "/brands/carina-organics.png",
  },
  {
    id: "c747",
    slug: "canary-clean",
    name: "Canary Clean Co",
    tagline: "Plastic-free nano-hydroxyapatite toothpaste tablets — xylitol, no fluoride, no tube guilt",
    story: "Handmade in Utah: chewable tablets with 5% nano-hydroxyapatite, xylitol, and calcium carbonate in a glass jar you refill from a compostable pouch. No plastic tube, no SLS foam show, no fluoride. Enamel care that ships without another squeeze-tube in the landfill.",
    location: "Utah, United States",
    founded: 2019,
    categories: ["oral"],
    accent: "#45B69C",
    rating: 4.7,
    reviewCount: 520,
    followerCount: 14000,
    websiteUrl: "https://www.canarycleanco.com",
    logoUrl: "/brands/canary-clean.svg",
  },
  {
    id: "c748",
    slug: "amber-tallow",
    name: "Amber Tallow",
    tagline: "Illinois family whipped tallow balms — grass-fed fat, calendula, manuka, no synthetic fragrance",
    story: "A family kitchen in Illinois whipping grass-fed tallow with calendula, manuka honey, lavender, or vanilla. Three-ingredient moisture that melts on contact — no water, no preservative circus, no perfume drawer. Traditional fat for modern dry skin, poured in small batches.",
    location: "Illinois, United States",
    founded: 2022,
    categories: ["skincare"],
    accent: "#C4A484",
    rating: 4.8,
    reviewCount: 210,
    followerCount: 5600,
    websiteUrl: "https://ambertallow.com",
    logoUrl: "/brands/amber-tallow.svg",
  },
  {
    id: "c749",
    slug: "lasso-tallow",
    name: "Lasso Co.",
    tagline: "Wisconsin grass-fed suet tallow with Manuka and frankincense — no whip fillers, no synthetic scent",
    story: "They don't whip air into the jar. Lasso blends grass-fed Wisconsin suet with New Zealand Manuka, local beeswax, and frankincense from Oman — then leaves it dense on purpose. Sensitive-skin tallow without harsh preservatives or a fragrance stack. Small-batch, limited, made in the USA.",
    location: "Wisconsin, United States",
    founded: 2022,
    categories: ["skincare"],
    accent: "#7A4E2D",
    rating: 4.8,
    reviewCount: 180,
    followerCount: 4900,
    websiteUrl: "https://lassotallow.us",
    logoUrl: "/brands/lasso-tallow.svg",
  },
  {
    id: "c750",
    slug: "kind-tallow",
    name: "KindTallow",
    tagline: "100% organic grass-finished tallow creams — two-ingredient unscented, no hormone or pesticide fog",
    story: "Certified organic, grass-fed and finished tallow with cold-pressed jojoba — or rosehip and vanilla lavender if you want a scent that still came from a plant. No antibiotics, no hormones, no pesticide residue dressed up as 'natural.' Barrier cream that looks like food because it almost is.",
    location: "United States",
    founded: 2021,
    categories: ["skincare"],
    accent: "#8B7355",
    rating: 4.7,
    reviewCount: 260,
    followerCount: 7200,
    websiteUrl: "https://www.kindtallow.com",
    logoUrl: "/brands/kind-tallow.svg",
  },
  {
    id: "c751",
    slug: "ranchers-render",
    name: "Ranchers Render",
    tagline: "Single-ranch whipped tallow, soap, and lip balm — farm fat, essential-oil scents, no mystery blend",
    story: "Render from a ranch you can actually name: whipped tallow for faces that hate water creams, a bar soap that still rinses, and a lip balm that isn't petroleum jelly. Citrus vanilla, lavender, unscented — small-batch fat with a short label and no synthetic fragrance fog.",
    location: "United States",
    founded: 2020,
    categories: ["skincare"],
    accent: "#6B4F2A",
    rating: 4.7,
    reviewCount: 150,
    followerCount: 3400,
    websiteUrl: "https://ranchersrender.com",
    logoUrl: "/brands/ranchers-render.svg",
  },
  {
    id: "c752",
    slug: "coastal-tallow",
    name: "Coastal Tallow Co.",
    tagline: "New Bern suet tallow face cream — local NC cattle, frankincense, pearl powder, no toxin pile",
    story: "Hand-chopped and hand-rendered in New Bern, North Carolina, from Eastern NC farms. Suet tallow with frankincense, organic castor, and pearl powder in a face cream that feels like the coast, plus whipped body butter. Local fat, small batches, no mystery supply chain.",
    location: "New Bern, NC",
    founded: 2023,
    categories: ["skincare"],
    accent: "#1B4F72",
    rating: 4.8,
    reviewCount: 170,
    followerCount: 4100,
    websiteUrl: "https://coastaltallowco.com",
    logoUrl: "/brands/coastal-tallow.svg",
  },
  {
    id: "c753",
    slug: "wildsett",
    name: "Wildsett",
    tagline: "Fermented rice-water shampoo bars and scalp serums — botanical, plastic-free, no sulphate fog",
    story: "Earth-born hair rituals in a bar: fermented rice water, marshmallow root, pumpkin seed, and rosemary — no sulfates, no silicones, no synthetic fragrance. Plus a scalp elixir for hair that's thinning and a mist for curls that hate oil. Small-batch botanicals, not a salon detergent.",
    location: "United States",
    founded: 2022,
    categories: ["hair"],
    accent: "#2F5D3A",
    rating: 4.8,
    reviewCount: 240,
    followerCount: 6800,
    websiteUrl: "https://wildsett.com",
    logoUrl: "/brands/wildsett.svg",
  },
  {
    id: "c754",
    slug: "jadu-beauty",
    name: "Jadu Beauty",
    tagline: "Clean shampoo and conditioner that actually rinse — short botanical lists, travel minis, no silicone pile",
    story: "A focused hair studio: shampoo, conditioner, and a cleanse-and-nourish pair without the 30-ingredient salon fog. Travel sizes for people who still want a readable label on the road. Gentle clean that doesn't strip, then nourish that doesn't coat your scalp in plastic shine.",
    location: "United States",
    founded: 2021,
    categories: ["hair"],
    accent: "#5B3A6E",
    rating: 4.6,
    reviewCount: 180,
    followerCount: 5200,
    websiteUrl: "https://jadubeauty.com",
    logoUrl: "/brands/jadu-beauty.svg",
  },
  {
    id: "c755",
    slug: "woodsy-earth",
    name: "Woodsy Earth",
    tagline: "Harrisburg handmade hair conditioners and tallow care — small-batch botanicals, no synthetic perfume stack",
    story: "Amanda poured this in Harrisburg, Illinois after getting tired of 'natural' labels that still hid fragrance. Woodsy Earth is small-batch hair conditioners, tallow balms, and outdoor essentials — magnesium pastes and botanical oils without parabens, dyes, or a perfume-chemical drawer. Family shop, real batches.",
    location: "Harrisburg, IL",
    founded: 2020,
    categories: ["hair","skincare"],
    accent: "#3D5A3A",
    rating: 4.7,
    reviewCount: 290,
    followerCount: 7800,
    websiteUrl: "https://woodsyearth.com",
    logoUrl: "/brands/woodsy-earth.svg",
  },
  {
    id: "c756",
    slug: "it-mush-be-good",
    name: "It Mush Be Good",
    tagline: "UK organic fruiting-body blends for focus, calm, and menopause — no mycelium filler, biochemist-made",
    story: "Roisin got tired of mushroom powders that were mostly grain. It Mush Be Good is 100% organic fruiting-body extract — Clarity, Unwind, Roar lion's mane, a menopause superblend — designed with biochemists for women's cycles, not a bro-stack. No binders, no bulking agents, made in the UK.",
    location: "United Kingdom",
    founded: 2022,
    categories: ["supplements"],
    accent: "#5B3A6E",
    rating: 4.8,
    reviewCount: 210,
    followerCount: 6400,
    websiteUrl: "https://www.itmushbegood.co.uk",
    logoUrl: "/brands/it-mush-be-good.svg",
  },
  {
    id: "c757",
    slug: "mushroom-mana",
    name: "Mushroom Mana",
    tagline: "Oregon small-batch organic mushroom honeys and cacao — hand-packed, no sweetener pile",
    story: "Mikaela hand-packs certified organic mushroom mixes in a Beaverton kitchen: cacao brain bliss, reishi and turkey-tail honey tonics, California-grown fruiting bodies with grass-fed collagen options. No hidden sugars, no caffeine circus, third-party tested mushrooms. Farmers-market energy, shipped.",
    location: "Beaverton, OR",
    founded: 2021,
    categories: ["supplements"],
    accent: "#6B3E26",
    rating: 4.8,
    reviewCount: 160,
    followerCount: 3900,
    websiteUrl: "https://mushroommana.com",
    logoUrl: "/brands/mushroom-mana.svg",
  },
];
