import type { Brand } from "./types";

/** Wave 86: small organic / toxic-free brands across marketplace categories (c1385+). */
export const catalogBrandsWave86: Brand[] = [
  {
    id: "c1385",
    slug: "ulyana-organics",
    name: "Ulyana Organics",
    tagline: "Grass-fed tallow skincare, probiotic deodorant, zinc sun cream, and remineralizing tooth powder",
    story: "A leftover unused multi-SKU house from Dunstable, MA (founded 2022) pouring grass-fed tallow face butter, body lotion, sun cream, probiotic deodorant, and a bentonite tooth powder — plus coconut shampoo bars and talc-free dry shampoo. Scent and hue expand; 2 oz vs 4 oz / jar vs refill / 1 vs 2–5 jars is size. Clay (bentonite vs kaolin) is formula, not a scent — pick bentonite. Drop ebooks, teas, candles, complimentary gifts, bundles, tools, bug spray, linen spray, rollers, and consultations. Cart.js is USD. Pages are key-ingredient essays except the tooth-powder and sun-cream lists.",
    location: "Dunstable, MA",
    founded: 2022,
    categories: ["oral","deodorant","sunscreen","skincare","hair"],
    accent: "#6B4A32",
    rating: 4.8,
    reviewCount: 280,
    followerCount: 4200,
    websiteUrl: "https://ulyanaorganics.com",
    logoUrl: "/brands/ulyana-organics.svg",
  },
  {
    id: "c1386",
    slug: "purelyte",
    name: "Purelyte",
    tagline: "Australian zero-sugar electrolyte powder with Himalayan salt and stevia, no sucralose",
    story: "The unused Australian electrolyte leftover after wave4–85 — a zero-sugar, no-maltodextrin drink mix with Himalayan salt, potassium citrate, magnesium lactate, and organic stevia. Flavour expands Lemon Lime / Pineapple / Raspberry / Blackcurrant. Serving count and wholesale cartons are size. Sample packs, $0 subscription gifts, bottles, and wholesale stay boxed. Cart.js is AUD — convert × 0.65. Not getpurelytes.com (wave 75). Pages are sweat-loss marketing; store the short published mineral list when a real formula is on the page.",
    location: "Australia",
    founded: 2023,
    categories: ["electrolytes"],
    accent: "#2E7D6F",
    rating: 4.6,
    reviewCount: 190,
    followerCount: 2100,
    websiteUrl: "https://purelyte.com.au",
    logoUrl: "/brands/purelyte.svg",
  },
  {
    id: "c1387",
    slug: "opportuniteas",
    name: "Opportuniteas",
    tagline: "New Zealand grass-fed whey isolate and concentrate, plus plant protein and collagen",
    story: "The unused protein leftover after wave4–85 — hormone-free New Zealand grass-fed whey isolate (Unflavored / Chocolate / Coffee / Vanilla) and concentrate (Unflavored / Vanilla / Chocolate), plus a chocolate vegan protein and hydrolyzed collagen. Flavor expands; 1 lb vs 2.5 lb / 5 lb is size. Teas, matcha, MCT, coffee creamers, inulin, wheatgrass, coconut milk, 2-packs, and joint bundles stay boxed. Cart.js is USD. Pages are farm-story marketing (leave empty when there is no comma formula).",
    location: "United States",
    founded: 2018,
    categories: ["protein","supplements"],
    accent: "#3D5A3A",
    rating: 4.5,
    reviewCount: 320,
    followerCount: 5400,
    websiteUrl: "https://opportuniteas.com",
    logoUrl: "/brands/opportuniteas.svg",
  },
  {
    id: "c1388",
    slug: "seaker-sun",
    name: "Seaker Sun Co",
    tagline: "Four-ingredient non-nano zinc sun balm from Laguna Beach",
    story: "The unused one-SKU leftover after wave4–85 — a 2 oz metal-tin mineral balm with non-nano zinc oxide, beeswax, jojoba, and vitamin E. Single tin vs two-pack is size. Cart.js is USD. Hardcode the four-ingredient list published on the page.",
    location: "Laguna Beach, CA",
    founded: 2024,
    categories: ["sunscreen"],
    accent: "#C4A35A",
    rating: 4.7,
    reviewCount: 64,
    followerCount: 890,
    websiteUrl: "https://seakersunco.com",
    logoUrl: "/brands/seaker-sun.svg",
  },
  {
    id: "c1389",
    slug: "made-new-naturals",
    name: "Made New Naturals",
    tagline: "Small-batch shampoo-bar formulas, tallow deodorant, and rendered tallow balm",
    story: "The unused leftover after wave4–85 — shampoo bars expand Sensitive Scalp / Rice Water / All-Around, plus a conditioner bar, aluminum-free tallow deodorant (Lavender / Calendula / Cedarwood), tallow balm and on-the-go stick scents, and a four-flavor lip balm. Full vs Small is size. Books, gift cards, sisal bags, soap dishes, trios, and sponsorships stay boxed. Cart.js is USD. Pages are founder-story marketing (leave empty when there is no comma formula).",
    location: "United States",
    founded: 2023,
    categories: ["hair","deodorant","skincare"],
    accent: "#5C1F16",
    rating: 4.8,
    reviewCount: 150,
    followerCount: 1600,
    websiteUrl: "https://madenewnaturals.com",
    logoUrl: "/brands/made-new-naturals.svg",
  },
  {
    id: "c1390",
    slug: "tilted-cap",
    name: "Tilted Cap",
    tagline: "Eastern North Carolina dual-extract lion's mane, reishi, and turkey tail tinctures",
    story: "The unused leftover three-SKU mushroom house after wave4–85 — Lion's Mane, Reishi, and Turkey Tail dual extracts made in small batches in Eastern North Carolina. The daily wellness bundle stays boxed. 59 mL is size. Cart.js is USD. Pages are dual-extract how-to (leave empty).",
    location: "Eastern North Carolina",
    founded: 2022,
    categories: ["supplements"],
    accent: "#4A3F2F",
    rating: 4.7,
    reviewCount: 88,
    followerCount: 740,
    websiteUrl: "https://tiltedcapllc.com",
    logoUrl: "/brands/tilted-cap.svg",
  },
];
