import type { Brand } from "./types";

/** Wave 21: small organic / toxic-free brands across marketplace categories (c795+). */
export const catalogBrandsWave21: Brand[] = [
  {
    id: "c795",
    slug: "birchbabe",
    name: "Birch Babe",
    tagline: "Ontario-made certified all-natural mineral SPF 40, deodorant, and low-waste bathroom staples",
    story: "A women- and family-led shop in Ontario that keeps the bathroom short-list: Health Canada–registered non-nano zinc SPF 40, plastic-free deodorant, shampoo bars, and a refreshing mouthwash. Certified all-natural, vegan, and cruelty-free — no chemical filters, no aluminum, no junk foam.",
    location: "Ontario, Canada",
    founded: 2018,
    categories: ["sunscreen","deodorant","skincare","hair","oral"],
    accent: "#3D6B4F",
    rating: 4.8,
    reviewCount: 2100,
    followerCount: 28000,
    websiteUrl: "https://birchbabe.com",
    logoUrl: "/brands/birchbabe.svg",
  },
  {
    id: "c796",
    slug: "coconut-joes",
    name: "Coconut Joe's",
    tagline: "Reef-safe mineral SPF 15–50 with non-nano zinc, virgin coconut, and an 8oz bottle that actually lasts",
    story: "Born from island days that needed sunscreen without oxybenzone. Coconut Joe's pours mineral lotions and a zinc sun butter with virgin coconut, calendula, aloe, and shea — no chemical filters, no reef-killing cocktail. After-sun gel and coconut lip balm stay in the same short, beach-bag register.",
    location: "United States",
    founded: 2014,
    categories: ["sunscreen","skincare"],
    accent: "#C45C26",
    rating: 4.7,
    reviewCount: 860,
    followerCount: 12000,
    websiteUrl: "https://coconutjoessunproducts.com",
    logoUrl: "/brands/coconut-joes.svg",
  },
  {
    id: "c797",
    slug: "magnolia-crow",
    name: "Magnolia Crow Soap Co.",
    tagline: "Littleton, CO tallow kitchen — grass-fed shampoo bars, hair oil, and small-batch skin care",
    story: "Handcrafted in Littleton, Colorado around 100% organic grass-fed tallow. The shampoo bar cleans without a sulfate circus; hair oil and balms stay short-list. No silicones-for-shine, no paraben stack — ranch fat and plant oils for people who want a bathroom they can pronounce.",
    location: "Littleton, Colorado",
    founded: 2021,
    categories: ["hair","skincare","deodorant"],
    accent: "#6B3E26",
    rating: 4.8,
    reviewCount: 340,
    followerCount: 5600,
    websiteUrl: "https://magnoliacrowsoapco.com",
    logoUrl: "/brands/magnolia-crow.svg",
  },
  {
    id: "c798",
    slug: "oak-prairie",
    name: "Oak & Prairie",
    tagline: "Grass-fed tallow lotions, lip balms, and rosemary-cedar conditioner bars — no seed-oil filler stack",
    story: "A small tallow house that renders grass-fed fat and blends it with organic oils. Whipped lotions, lip balm, goat-milk bars, and a rosemary-cedar conditioner bar skip synthetic fragrance and detergent shampoo. Dish-soap merch stays off this marketplace shelf.",
    location: "United States",
    founded: 2022,
    categories: ["skincare","hair"],
    accent: "#5B7A3A",
    rating: 4.7,
    reviewCount: 180,
    followerCount: 2900,
    websiteUrl: "https://oakandprairiellc.com",
    logoUrl: "/brands/oak-prairie.svg",
  },
  {
    id: "c799",
    slug: "heey",
    name: "Heey!",
    tagline: "Swedish hydration sticks with lion's mane, rhodiola, and creatine — clean drink mixes, no candy-aisle dyes",
    story: "Made in Sweden for people who want electrolytes and a nootropic in the same glass. Hydrate & Focus pairs sodium, magnesium, and potassium with lion's mane, rhodiola, and brahmi. Protein & biotics and unflavoured creatine stay in the same short, vegan register — merch bottles stay off the shelf.",
    location: "Sweden",
    founded: 2022,
    categories: ["electrolytes","protein","supplements"],
    accent: "#E27D60",
    rating: 4.6,
    reviewCount: 420,
    followerCount: 8900,
    websiteUrl: "https://itsheey.com",
    logoUrl: "/brands/heey.svg",
  },
  {
    id: "c800",
    slug: "hiro",
    name: "HIRO",
    tagline: "UK hydration tablets with six electrolytes — BBC Good Food winner, no mystery powder pile",
    story: "A London wellness house that treats hydration like daily nutrition, not a neon sports drink. Tablets restore sodium, potassium, magnesium, calcium, chloride, and phosphate without a candy aftertaste. Clean creatine and a nootropic stack sit beside the tubes — no proprietary-blend fog.",
    location: "United Kingdom",
    founded: 2021,
    categories: ["electrolytes","supplements"],
    accent: "#1D6A8A",
    rating: 4.7,
    reviewCount: 1100,
    followerCount: 16000,
    websiteUrl: "https://dailyhiro.com",
    logoUrl: "/brands/hiro.svg",
  },
  {
    id: "c801",
    slug: "ndc",
    name: "NDC Supplements",
    tagline: "Grass-fed whey plus collagen and organic maca — monk fruit, no sugar, no flavor-system fog",
    story: "A small US formula shop that keeps protein to four ingredients: grass-fed whey concentrate, bovine collagen, organic maca, and organic monk fruit. Twenty-one grams a scoop without gums, refined sugar, or 'natural flavors.' Sleep, immune, and ginger-turmeric shots stay in the same short-list lane.",
    location: "United States",
    founded: 2020,
    categories: ["protein","supplements"],
    accent: "#2C5F4E",
    rating: 4.6,
    reviewCount: 210,
    followerCount: 3800,
    websiteUrl: "https://www.ndcsupplements.com",
    logoUrl: "/brands/ndc.svg",
  },
  {
    id: "c802",
    slug: "unicorn-co",
    name: "The Unicorn Co.",
    tagline: "USDA organic A2 grass-fed whey from Jersey and Guernsey herds — no fillers, no natural flavors",
    story: "Whey from heritage A2-dominant dairy breeds, certified organic and grass-fed, third-party tested. Unflavored collagen blends and real-food protein bars (mocha almond, matcha pistachio) skip the isolate-and-gum playbook. If it is not in the pouch, it is not on the label.",
    location: "United States",
    founded: 2021,
    categories: ["protein"],
    accent: "#8B5A2B",
    rating: 4.8,
    reviewCount: 160,
    followerCount: 4200,
    websiteUrl: "https://www.the-unicornco.com",
    logoUrl: "/brands/unicorn-co.svg",
  },
  {
    id: "c803",
    slug: "organic-burst",
    name: "Organic Burst",
    tagline: "London-born organic superfoods — baobab, spirulina, wheatgrass, single-ingredient powders",
    story: "A UK house that treats superfoods like groceries, not candy. Organic baobab, spirulina, wheatgrass, and targeted stacks (hair, fertility, perimenopause, magnesium) stay USDA/EU organic and additive-light. No proprietary-blend mystery, no neon gummies pretending to be plants.",
    location: "London, United Kingdom",
    founded: 2013,
    categories: ["supplements"],
    accent: "#3D8B6E",
    rating: 4.7,
    reviewCount: 3400,
    followerCount: 42000,
    websiteUrl: "https://www.organicburst.com",
    logoUrl: "/brands/organic-burst.svg",
  },
  {
    id: "c804",
    slug: "booheads",
    name: "Booheads",
    tagline: "UK hydroxyapatite toothpaste and plant-based brush heads — fluoride-free, SLS-free, enamel-first",
    story: "A small UK oral-care shop that swapped fluoride for hydroxyapatite and plastic brush heads for bamboo and wheat straw. Spearmint paste is SLS-free and peroxide-free; PAP+ mouthwash drops stay enamel-supporting. Replacement heads fit the brushes people already own — no gadget aisle.",
    location: "United Kingdom",
    founded: 2020,
    categories: ["oral"],
    accent: "#2A9D8F",
    rating: 4.6,
    reviewCount: 890,
    followerCount: 14000,
    websiteUrl: "https://www.booheads.com",
    logoUrl: "/brands/booheads.svg",
  },
  {
    id: "c805",
    slug: "electric-shrooms",
    name: "Electric Shrooms",
    tagline: "Mushroom-powered electrolyte mix — organic cordyceps, fruit powders, no sugar or dyes",
    story: "Hydration that reads like a forest floor, not a gas-station cooler. Organic cordyceps plus magnesium malate, potassium, sodium, and real fruit powders. Sugar-free, vegan, no colors or dyes. Three mixes — Thirsty 30, The 6Mix, Trippy Tropical — and nothing else.",
    location: "United States",
    founded: 2023,
    categories: ["electrolytes"],
    accent: "#5B2C6F",
    rating: 4.7,
    reviewCount: 140,
    followerCount: 3100,
    websiteUrl: "https://drinkyourshrooms.com",
    logoUrl: "/brands/electric-shrooms.svg",
  },
  {
    id: "c806",
    slug: "primm-farms",
    name: "Primm Farms",
    tagline: "Farm-poured baking-soda-free deodorant and handmade hair-and-body bars — aluminum-free, essential-oil scented",
    story: "A US farm kitchen that pours deodorant without aluminum or baking soda, then cuts tea-tree and lavender bars for hair and body. Smooth cream sticks, real essential oils, no synthetic fragrance stack. Seconds soaps stay honest; merch stays off this shelf.",
    location: "United States",
    founded: 2019,
    categories: ["deodorant","skincare","hair"],
    accent: "#6B4A2A",
    rating: 4.8,
    reviewCount: 520,
    followerCount: 7800,
    websiteUrl: "https://primmfarms.com",
    logoUrl: "/brands/primm-farms.svg",
  },
  {
    id: "c807",
    slug: "moon-valley",
    name: "Moon Valley Organics",
    tagline: "Colville, WA farm organics — herbal hair therapy, beeswax lip balm, salves grown on their own land",
    story: "A family farm in Colville, Washington that grows the herbs that go into the jar. USDA organic hair oils with MCT, herbal lotion bars, beeswax lip balm, and eczema-minded body rubs. No synthetic fragrance, no detergent shampoo — farm plants, cold-pressed oils, and beeswax.",
    location: "Colville, Washington",
    founded: 1998,
    categories: ["hair","skincare"],
    accent: "#1B6B6A",
    rating: 4.8,
    reviewCount: 4200,
    followerCount: 38000,
    websiteUrl: "https://www.moonvalleyorganics.com",
    logoUrl: "/brands/moon-valley.png",
  },
  {
    id: "c808",
    slug: "wishgarden",
    name: "WishGarden Herbs",
    tagline: "Boulder herbal extracts since 1979 — alcohol-and-glycerin tinctures, no mystery proprietary fog",
    story: "A Colorado herb house that still tastes like an apothecary. WishGarden makes liquid extracts for sleep, digestion, hormones, and immunity with plants you can name. No gummy candy, no blend-that-hides-the-dose. Small-batch herbalism for people who want a dropper, not a marketing stack.",
    location: "Boulder, Colorado",
    founded: 1979,
    categories: ["supplements"],
    accent: "#4A6B3A",
    rating: 4.8,
    reviewCount: 5600,
    followerCount: 52000,
    websiteUrl: "https://www.wishgardenherbs.com",
    logoUrl: "/brands/wishgarden.png",
  },
  {
    id: "c809",
    slug: "banyan",
    name: "Banyan Botanicals",
    tagline: "Organic Ayurvedic herbs, oils, and hair care — USDA organic, fairly traded, no junk fillers",
    story: "An Albuquerque Ayurvedic house that sources organic herbs and cold-pressed oils for skin, scalp, and daily rasayanas. Hair oils, herbal tablets, and fertility-minded formulas stay USDA organic and fairly traded. No synthetic fragrance aisle, no candy-coated ashwagandha.",
    location: "Albuquerque, New Mexico",
    founded: 1996,
    categories: ["supplements","hair","skincare"],
    accent: "#C45C26",
    rating: 4.7,
    reviewCount: 8900,
    followerCount: 74000,
    websiteUrl: "https://www.banyanbotanicals.com",
    logoUrl: "/brands/banyan.png",
  },
  {
    id: "c810",
    slug: "urban-moonshine",
    name: "Urban Moonshine",
    tagline: "Vermont organic bitters and herbal tonics — digestive sprays, no neon wellness gummies",
    story: "A Burlington apothecary that brought back bitters as daily herbalism. Organic digestive sprays, liver-minded dandelion blends, and short-list tonics — certified organic herbs, no candy coating. Bandanas and merch stay off this marketplace shelf.",
    location: "Burlington, Vermont",
    founded: 2009,
    categories: ["supplements"],
    accent: "#7A3E1D",
    rating: 4.6,
    reviewCount: 1800,
    followerCount: 22000,
    websiteUrl: "https://www.urbanmoonshine.com",
    logoUrl: "/brands/urban-moonshine.png",
  },
];
