import type { Brand } from "./types";

/** Wave 83: small organic / toxic-free brands across marketplace categories (c1367+). */
export const catalogBrandsWave83: Brand[] = [
  {
    id: "c1367",
    slug: "uncle-harrys",
    name: "Uncle Harry's",
    tagline: "Redmond WA Ayurvedic toothpaste, mouthwash, and remineralizing powders since 1991",
    story: "A family-run Redmond, Washington house (founded 1991) hand-making fluoride-free toothpaste, Miracle Mouthwash, tooth powder, and enamel remineralizers from food-grade botanicals — now women-owned and NOP organic. Flavors already live on separate toothpaste and suds titles (Peppermint, Spearmint, Mild Mint, Cinnamon, Star Anise, Orange Blossom, Bliss Mint). Jar oz and 8 fl oz vs travel 3 fl oz are size (keep the 3 oz glass jar / 8 fl oz over gallon and 1.5 lb refills). Empty bottles, standalone essential oils, lice, mosquito, gift cards, and pins stay boxed. Cart.js is USD. Pages publish clay / xylitol / oil lists when a real INCI is on the page.",
    location: "Redmond, WA",
    founded: 1991,
    categories: ["oral","hair","deodorant","skincare"],
    accent: "#3D5A45",
    rating: 4.7,
    reviewCount: 2100,
    followerCount: 18000,
    websiteUrl: "https://uncleharrys.com",
    logoUrl: "/brands/uncle-harrys.png",
  },
  {
    id: "c1368",
    slug: "only-hydration",
    name: "ONLY Hydration",
    tagline: "Asian-inspired electrolyte sticks with real fruit powder and goji, no artificial sweeteners",
    story: "A US-made hydration house mixing 1,270 mg of six electrolytes with real Asian fruit powders and goji berry — Yuzu Citrus, Lychee, White Peach, and Asian Pear already live on separate titles. Stick count is size. Prefix ONLY so Lychee is not a bare flavor title. Starter kits, samplers, variety packs, holiday gift kits, and shaker bottles stay boxed. Cart.js is USD. Pages publish nutrition in photos (leave ingredients empty when the page is a flavor story).",
    location: "United States",
    founded: 2023,
    categories: ["electrolytes"],
    accent: "#C45C4A",
    rating: 4.6,
    reviewCount: 420,
    followerCount: 6400,
    websiteUrl: "https://onlyhydration.com",
    logoUrl: "/brands/only-hydration.svg",
  },
  {
    id: "c1369",
    slug: "norcal-organic",
    name: "NorCal Organic",
    tagline: "Humboldt grass-fed organic Jersey whey, pea, and collagen without soy lecithin",
    story: "A Northern California protein house cold-microfiltering USDA Organic whey from year-round pasture Jersey cows in Humboldt and Del Norte counties, plus pea, peanut-butter, oat-milk protein, and collagen peptides. Flavor expands whey Instant / Classic / Chocolate / Vanilla; 2 lb vs 4 lb is size. Prefix NorCal so Whey Protein is not a bare type title. Cashback SKUs stay boxed. Cart.js is USD. Pages publish the short whey / sunflower-lecithin list when a real formula is on the page.",
    location: "Humboldt County, CA",
    founded: 2014,
    categories: ["protein","supplements"],
    accent: "#2F5E3A",
    rating: 4.8,
    reviewCount: 890,
    followerCount: 9200,
    websiteUrl: "https://norcal-organic.com",
    logoUrl: "/brands/norcal-organic.svg",
  },
  {
    id: "c1370",
    slug: "bpm-deodorant",
    name: "BPM Deodorant",
    tagline: "Canadian baking-soda-free natural deodorant in a recyclable metal tube",
    story: "A Canada-made performance deodorant house pouring a baking-soda-free, wax-free formula into recyclable metal tubes — Bergamot & Lime and Unscented already live on separate titles. Tube grams are size. Two-track sets (Side A / Side B, Silent on Repeat, Citrus on Repeat), family packs, Four on the Floor, and 3/4 Time stay boxed. Cart.js may report CAD — convert × 0.73 when the cart is CAD. Pages publish the short magnesium / oil list when a real INCI is on the page.",
    location: "Canada",
    founded: 2024,
    categories: ["deodorant"],
    accent: "#4A3F35",
    rating: 4.6,
    reviewCount: 160,
    followerCount: 2100,
    websiteUrl: "https://bpmdeodorant.com",
    logoUrl: "/brands/bpm-deodorant.svg",
  },
  {
    id: "c1371",
    slug: "wild-gold-tallow",
    name: "Wild Gold Tallow",
    tagline: "North Carolina grass-fed colostrum tallow balm plus a four-ingredient zinc sun balm",
    story: "A rural North Carolina farm house blending 100% grass-fed tallow, first colostrum, and emu oil into a three-ingredient face balm, plus a four-ingredient non-nano zinc sun balm (tallow, zinc, jojoba, aloe butter). Colostrum Scent expands Unscented / Mountain Rose / Vanilla Cream — drop the named Mountain Rose duplicate; keep Lavender Mist as its own title. Jar count is size. The digital e-book stays boxed. Cart.js is USD. Pages publish tallow / colostrum / zinc lists when a real formula is on the page.",
    location: "North Carolina",
    founded: 2023,
    categories: ["sunscreen","skincare"],
    accent: "#8B6B3D",
    rating: 4.8,
    reviewCount: 1000,
    followerCount: 8500,
    websiteUrl: "https://wildgoldtallow.com",
    logoUrl: "/brands/wild-gold-tallow.svg",
  },
  {
    id: "c1372",
    slug: "baltispore",
    name: "BaltiSpore",
    tagline: "Baltimore dual-extract mushroom tinctures without the grow-kit merch wall",
    story: "A Baltimore mushroom house making dual-extract Lion's Mane, Reishi, Turkey Tail, Chaga, Cordyceps, Maitake, Tremella, and Poria tinctures plus Get Hyphae drink mixes and fire cider. Bottle oz is size. Grow kits, grain spawn, agar, monotubs, empty growlers, dog treats, tees, hoodies, beanies, and gift cards stay boxed. Cart.js is USD. Pages publish fruiting-body + alcohol + water lists when a real formula is on the page.",
    location: "Baltimore, MD",
    founded: 2020,
    categories: ["supplements"],
    accent: "#3A4A32",
    rating: 4.7,
    reviewCount: 340,
    followerCount: 5600,
    websiteUrl: "https://baltispore.com",
    logoUrl: "/brands/baltispore.svg",
  },
];
