import type { Brand } from "./types";

/** Wave 71: small organic / toxic-free brands across marketplace categories (c1295+). */
export const catalogBrandsWave71: Brand[] = [
  {
    id: "c1295",
    slug: "before",
    name: "Before",
    tagline: "Canadian n-HA and fluoride-free toothpaste in SuperMint, MellowMint, and citrus tubes",
    story: "A small Canadian oral house that puts nano-hydroxyapatite or clean fluoride into sugarcane plant-based tubes. SuperMint n-HA, fluoride-free MellowMint / Cinnamon Orange / Lemon Coconut, Classic, Sensitive, and Brilliant Breath mouthwash already live on separate titles. Travel size and multi-packs are size. Cart.js is CAD and converts at 0.73. Rituals, bathroom cups, and flavor packs stay boxed.",
    location: "Canada",
    founded: 2019,
    categories: ["oral"],
    accent: "#3A6A6A",
    rating: 4.6,
    reviewCount: 188,
    followerCount: 4200,
    websiteUrl: "https://beforecompany.com",
    logoUrl: "/brands/before.svg",
  },
  {
    id: "c1296",
    slug: "rival-sports-fuel",
    name: "Rival Sports Fuel",
    tagline: "UK zero-sugar unflavoured electrolytes plus creatine, collagen, and D-ribose",
    story: "A tiny UK hydration kitchen that has mixed unflavoured electrolytes since 2010 — zero sugar, zero sweeteners, zero fillers. Rival RAW Flavour expands Apple / Cherry / Raspberry / Watermelon; pouch grams and tub count are size. Creatine, creatine + electrolytes, creatine + collagen, and D-ribose stay supplements. Cart.js is GBP and converts at 1.27. Shakers and gift cards stay boxed.",
    location: "United Kingdom",
    founded: 2010,
    categories: ["electrolytes","supplements"],
    accent: "#1A3A5A",
    rating: 4.7,
    reviewCount: 96,
    followerCount: 1800,
    websiteUrl: "https://www.rivalsportsfuel.com",
    logoUrl: "/brands/rival-sports-fuel.svg",
  },
  {
    id: "c1297",
    slug: "farm-wife-tallow",
    name: "Farm Wife Tallow",
    tagline: "Six-farm tallow sun cream, whipped creams, and body butters without seed-oil fillers",
    story: "Six farm women across the US rendering grass-fed tallow into a mineral Sun Cream plus named whipped creams and body butters. Sun Cream Scent expands Unscented / Rosemary; jar ounces stay size. Culinary tallow and lard, skillet sticks, bath soaks, stickers, hoodies, and mini sets stay boxed.",
    location: "United States",
    founded: 2023,
    categories: ["sunscreen","skincare"],
    accent: "#8A5A2A",
    rating: 4.8,
    reviewCount: 74,
    followerCount: 1600,
    websiteUrl: "https://farmwifetallow.com",
    logoUrl: "/brands/farm-wife-tallow.svg",
  },
  {
    id: "c1298",
    slug: "brookies-tallow",
    name: "Brookie's Tallow",
    tagline: "Wyoming small-batch grass-fed tallow face cream, body butter, and coffee scrub",
    story: "A Diamondville, Wyoming kitchen that triple-clarifies grass-fed suet into Vanilla Latte and Hint of Vanilla face creams, Original and Vanilla body butters, plus a coffee scrub, sugar scrub, and hyaluronic vitamin C serum. Flavors already live on separate titles. Jar ounces stay size. Trio bundles stay boxed.",
    location: "Diamondville, WY",
    founded: 2026,
    categories: ["skincare"],
    accent: "#6A4A2A",
    rating: 4.7,
    reviewCount: 42,
    followerCount: 900,
    websiteUrl: "https://brookiestallow.com",
    logoUrl: "/brands/brookies-tallow.svg",
  },
  {
    id: "c1299",
    slug: "tawariki",
    name: "Tawariki",
    tagline: "Awakino farm goat-milk shampoo, conditioner, and soap bars made with undiluted herd milk",
    story: "A New Zealand goat farm in Awakino that milks its own herd and pours 100% undiluted goat milk into shampoo bars, conditioner bars, first-milk facial bars, a 30 g face cream, and named soap bars. Shaving-soap Scent expands; bar grams stay size. Gift rituals, novelty shapes, pet shampoo, candles, and imperfect seconds stay boxed. Cart.js is NZD and converts at 0.60.",
    location: "Awakino, New Zealand",
    founded: 2018,
    categories: ["hair","skincare"],
    accent: "#4A6A4A",
    rating: 4.8,
    reviewCount: 128,
    followerCount: 2100,
    websiteUrl: "https://tawarikigoats.com",
    logoUrl: "/brands/tawariki.svg",
  },
  {
    id: "c1300",
    slug: "mayberry-farms",
    name: "Mayberry Farms",
    tagline: "Wisconsin farm goat-milk shampoo bars, tallow balms, and honey lip balms",
    story: "A small Wisconsin farm rendering tallow and milking goats into an unscented shampoo bar, facial and body soaps, whipped shaving creams, lotion bars, working-hands salve, and tallow lip balms. Lip and whipped-soap Scent expand; jar ounces stay size. Culinary honey, beeswax melts, greeting cards, gift cards, soap savers, subscriptions, and bundles stay boxed.",
    location: "Wisconsin",
    founded: 2019,
    categories: ["hair","skincare"],
    accent: "#7A5A3A",
    rating: 4.8,
    reviewCount: 86,
    followerCount: 1500,
    websiteUrl: "https://mayberryfarmswi.com",
    logoUrl: "/brands/mayberry-farms.svg",
  },
];
