import type { Brand } from "./types";

/** Wave 102: small organic / toxic-free brands across marketplace categories (c1481+). */
export const catalogBrandsWave102: Brand[] = [
  {
    id: "c1481",
    slug: "great-oral-health",
    name: "Great Oral Health",
    tagline: "Dentist-formulated 11% nano + micro hydroxyapatite toothpaste and BLIS oral probiotics",
    story:
      "Encino holistic dentist Dr. Paul O'Malley built Great Oral Health after decades of watching fluoride tubes and drill-and-fill routines miss the microbiome. ProMineralizer toothpaste uses 11% nano and micro hydroxyapatite in Wintermint, Peppermint Wow, Citrus Blast, and kids' Yummy Orange — plus BLIS K12 & M18 chewable probiotics, CrystLCare enamel strips, OraRestore gum oil, and a bamboo brush. No patented-system kits: just the singles that earn a spot by the sink.",
    location: "Encino, CA",
    founded: 2011,
    categories: ["oral"],
    accent: "#1FB6D5",
    rating: 4.7,
    reviewCount: 1860,
    followerCount: 12400,
    websiteUrl: "https://www.greatoralhealth.com",
    logoUrl: "/brands/great-oral-health.svg",
  },
  {
    id: "c1482",
    slug: "fire-salt",
    name: "Fire Salt",
    tagline: "Zero-sugar firefighter electrolytes — sea salt, coconut water, magnesium, and real heat",
    story:
      "Started by wildland firefighters who needed hydration that survived 1,000-degree lines and long sauna recoveries — not another stevia-sweet sports drink. Fire Salt mixes mineral sea salt, coconut water, magnesium malate, and potassium into zero-sugar sticks from lemon-lime and watermelon to firecracker popsicle, plus a two-flavor Torched pre-workout. No hats, no sampler gimmicks: the 32-packs they actually throw in a pack.",
    location: "United States",
    founded: 2023,
    categories: ["electrolytes", "supplements"],
    accent: "#E85D04",
    rating: 4.8,
    reviewCount: 740,
    followerCount: 8900,
    websiteUrl: "https://drinkfiresalt.com",
    logoUrl: "/brands/fire-salt.svg",
  },
  {
    id: "c1483",
    slug: "chizfit",
    name: "Chizfit",
    tagline: "Lansdale small-batch pea-hemp-chia protein — vanilla or espresso cinnamon, plus hemp soaps",
    story:
      "Pennsylvania wellness coach Justin Chisholm got tired of chalky plant tubs and mixed his own small-batch pea, hemp, pumpkin, and chia protein in Lansdale. Vanilla stays simple; coffee gets real espresso, Saigon cinnamon, and lion's mane. The same clean-label habit shows up in castile wash, charcoal-hemp sports soap, and a hemp vitamin-E serum — no hoodies, no snack bars, no three-bag bundles.",
    location: "Lansdale, PA",
    founded: 2023,
    categories: ["protein", "skincare"],
    accent: "#3D5A3A",
    rating: 4.6,
    reviewCount: 128,
    followerCount: 2100,
    websiteUrl: "https://chizfitwell.com",
    logoUrl: "/brands/chizfit.svg",
  },
  {
    id: "c1484",
    slug: "kokua-sun-care",
    name: "Kōkua Sun Care",
    tagline: "Hawaiian non-nano zinc SPF 50 and tinted SPF 30 — kukui, macadamia, no eye sting",
    story:
      "Hawaii-made mineral sun that actually rubs in clear — 25% Australian non-nano zinc in the beach/sport/baby SPF 50, 18% zinc in the everyday tinted SPF 30, plus an aloe-hyaluronic aftersun serum. Kukui and macadamia replace the usual silicone smear. No towels, no gift bags: just reef-safer zinc they wanted for Hawaiian water days.",
    location: "Hawaii",
    founded: 2018,
    categories: ["sunscreen", "skincare"],
    accent: "#2A6F6A",
    rating: 4.8,
    reviewCount: 420,
    followerCount: 5600,
    websiteUrl: "https://kokua-sun-care.myshopify.com",
    logoUrl: "/brands/kokua-sun-care.svg",
  },
  {
    id: "c1485",
    slug: "creations-by-the-creek",
    name: "Creations by the Creek",
    tagline: "Mt. Clemens grass-fed tallow deodorant, mineral sun balm, and wash-day shampoo bars",
    story:
      "Small-batch tallow care from Mt. Clemens, Michigan — aluminum-free deodorant with magnesium and arrowroot, Made in the Shade mineral sun balm, whipped moisturizers, cold-process soaps, and shampoo bars for thinning, oily, dry, and everyday hair. New Moon and Full Moon lunar singles sit beside peppermint and rose lip balms. No sourdough pop-ups, no ritual kits: the jars and bars that actually live on the vanity.",
    location: "Mt. Clemens, MI",
    founded: 2020,
    categories: ["deodorant", "sunscreen", "skincare", "hair"],
    accent: "#7A4E3A",
    rating: 4.8,
    reviewCount: 310,
    followerCount: 4800,
    websiteUrl: "https://creationsbythecreek.com",
    logoUrl: "/brands/creations-by-the-creek.svg",
  },
  {
    id: "c1486",
    slug: "rooted-mushrooms",
    name: "Rooted Mushrooms",
    tagline: "Idaho fruiting-body tinctures and powders — lion's mane through turkey tail, no grow kits",
    story:
      "Idaho growers who extract the fruiting body only — Lion's Mane, reishi, chaga, cordyceps, turkey tail, and shiitake tinctures in 1 oz bottles, plus Daily Blend, Reishi, and Lion's Mane powders. They dry most of the mushrooms themselves and keep mycelium, coffee blends, and kitchen salts off this shelf.",
    location: "Idaho",
    founded: 2021,
    categories: ["supplements"],
    accent: "#4A3B2A",
    rating: 4.7,
    reviewCount: 96,
    followerCount: 1900,
    websiteUrl: "https://rootedmushrooms.com",
    logoUrl: "/brands/rooted-mushrooms.svg",
  },
];
