import type { Brand } from "./types";

/** Wave 90: small organic / toxic-free brands across marketplace categories (c1409+). */
export const catalogBrandsWave90: Brand[] = [
  {
    id: "c1409",
    slug: "primal-life-organics",
    name: "Primal Life Organics",
    tagline: "Ohio nano-hydroxyapatite tooth powder, mineral deodorant, and raspberry-seed sun stick",
    story: "The leftover unused multi-SKU n-HA oral house after dedicated shops ran out — clay + nano-hydroxyapatite tooth powders (Flavor expands Peppermint / Spearmint / Bubblegum / Cinnamon / Unflavored), toothpaste, oil-pulling, floss, a copper tongue scraper, Stick Up deodorant scents, and a red-raspberry-seed sun stick. 1 oz vs 4 oz / 0.75 oz vs 3 oz is size. LED whitening gadgets, sonic brushes, kits, bundles, testers, bug spray, and shipping protection stay boxed. Cart.js is USD. Hardcode the published clay / n-HA powder and tallow-free deodorant lists.",
    location: "Ohio",
    founded: 2012,
    categories: ["oral","deodorant","sunscreen","skincare"],
    accent: "#4A5A32",
    rating: 4.7,
    reviewCount: 4200,
    followerCount: 38000,
    websiteUrl: "https://primallifeorganics.com",
    logoUrl: "/brands/primal-life-organics.png",
  },
  {
    id: "c1410",
    slug: "adapt-electrolytes",
    name: "ADAPT Electrolytes",
    tagline: "Zero-sugar Informed-Sport electrolytes with sodium, potassium, magnesium, and calcium — no sucralose",
    story: "The unused electrolyte leftover after wave4–89 — Mixed-Berry, Orange, and Lemon-Lime drink mixes built around the minerals you actually sweat, with no added sugar, no stevia, and no sucralose. Flavors already live on separate titles; Style is not a flavor. Hats, bottles, and Elite / Essentials bundles stay boxed. Cart.js is USD. Pages are performance marketing (leave empty).",
    location: "United States",
    founded: 2022,
    categories: ["electrolytes"],
    accent: "#1F4E6B",
    rating: 4.6,
    reviewCount: 94,
    followerCount: 2100,
    websiteUrl: "https://adaptnutrition.co",
    logoUrl: "/brands/adapt-electrolytes.svg",
  },
  {
    id: "c1411",
    slug: "go-good",
    name: "Go Good",
    tagline: "New Zealand grass-fed whey isolate and organic-flavored concentrate — no sucralose",
    story: "The unused protein leftover after wave4–89 — pasture-raised NZ whey isolate (Unflavoured / Organic Vanilla / Organic Chocolate), whey concentrate (Unflavoured / Vanilla / Chocolate / Banana / Strawberry), and organic-flavored plant isolates, plus creatine. Flavors already live on separate titles. 500 g vs 1 kg / 2 kg is size. Shaker bundles, sample 10-packs, and merch stay boxed. Cart.js is **NZD** × 0.60 (NZ$65 → $39.00). Hardcode the published isolate + sunflower-lecithin list.",
    location: "New Zealand",
    founded: 2017,
    categories: ["protein","supplements"],
    accent: "#3D6B3A",
    rating: 4.8,
    reviewCount: 1800,
    followerCount: 12000,
    websiteUrl: "https://gogood.co.nz",
    logoUrl: "/brands/go-good.svg",
  },
  {
    id: "c1412",
    slug: "tallow-cosmetics",
    name: "Tallow Cosmetics",
    tagline: "Dutch tallow mineral SPF 30, magnesium deodorant, and ancestral cream",
    story: "The leftover unused EUR tallow sun house after wave4–89 — a tallow mineral SPF 30, two magnesium deodorant scents already on titles (Geranium & Vanilla / Lemongrass & Patchouli), original cream, zinc balm, herbal soap, and hair wax. Candles, gift cards, facial cups, travel soap boxes, and recovery kits stay boxed. Cart.js is **EUR** × 1.08 (€32.50 → $35.10). Pages are key-ingredient marketing (leave empty).",
    location: "Netherlands",
    founded: 2021,
    categories: ["sunscreen","deodorant","skincare","hair"],
    accent: "#7A4E2E",
    rating: 4.7,
    reviewCount: 210,
    followerCount: 3400,
    websiteUrl: "https://tallowcosmetics.com",
    logoUrl: "/brands/tallow-cosmetics.svg",
  },
  {
    id: "c1413",
    slug: "royal-tallow",
    name: "Royal Tallow",
    tagline: "Baking-soda-free tallow deodorant with magnesium, plus soap, balm, and lip tin",
    story: "The unused tallow deodorant leftover after wave4–89 — aluminum-free, baking-soda-free sticks in Unscented / Vanilla / Lavender & Cedarwood, plus saponified tallow soap and whipped balm. Scents expand deodorant, soap, lip, and balm. 2 oz vs 4 oz is size. Shipping protection stays boxed. Cart.js is USD. Hardcode the published tallow / arrowroot / magnesium deodorant list.",
    location: "United States",
    founded: 2023,
    categories: ["deodorant","skincare"],
    accent: "#6B3A2A",
    rating: 4.8,
    reviewCount: 68,
    followerCount: 1400,
    websiteUrl: "https://www.royaltallow.com",
    logoUrl: "/brands/royal-tallow.svg",
  },
  {
    id: "c1414",
    slug: "organicules",
    name: "Organicules",
    tagline: "Irish organic shampoo bars, conditioner bars, and aluminum-free deodorant",
    story: "The leftover unused curl-and-clean hair house after wave4–89 — pH-balanced Irish shampoo and conditioner bars (Dry / Normal / Greasy already on titles) plus plastic-free cardboard deodorant sticks. PACKAGING tin vs compostable bag is size. Bath bombs, shower steamers, and gift cards stay boxed. Cart.js is **EUR** × 1.08 (€10 → $10.80). Pages publish comma INCI on wash-day bars.",
    location: "Ireland",
    founded: 2018,
    categories: ["hair","deodorant","skincare"],
    accent: "#2F6B4A",
    rating: 4.7,
    reviewCount: 320,
    followerCount: 4800,
    websiteUrl: "https://organicules.ie",
    logoUrl: "/brands/organicules.svg",
  },
];
