import type { Brand } from "./types";

/** Wave 85: small organic / toxic-free brands across marketplace categories (c1379+). */
export const catalogBrandsWave85: Brand[] = [
  {
    id: "c1379",
    slug: "zebra",
    name: "ZEBRA",
    tagline: "Fluoride-free, hydroxyapatite-free toothpaste with xylitol and calcium carbonate",
    story: "A US clean oral house that skips both fluoride and hydroxyapatite — remineralizing with calcium carbonate, cacao butter, and xylitol in Mint, Coconut, and Birthday Cake pastes, plus mint tablets and floss. Flavors already live on separate titles. Mini tubes are size. Toothbrush color is merch (keep one). Sets, jet-set bundles, sweatshirts, hats, scrunchies, pillowcases, keychains, and shipping protection stay boxed. Aluminum-free deodorants Awake / Liberty / Bright stay deodorant. Cart.js is USD. Pages publish comma INCI on toothpaste; deodorant pages are benefit essays (leave empty).",
    location: "United States",
    founded: 2022,
    categories: ["oral","deodorant"],
    accent: "#1A1A1A",
    rating: 4.7,
    reviewCount: 420,
    followerCount: 6800,
    websiteUrl: "https://yayzebra.com",
    logoUrl: "/brands/zebra.svg",
  },
  {
    id: "c1380",
    slug: "nion-health",
    name: "NION Health",
    tagline: "Unflavored sweetener-free electrolyte powder plus bioelectric mineral capsules",
    story: "The unused one-SKU electrolyte leftover after wave4–84 — an unflavored, sugar-free, sweetener-free drink mix plus Bioelectric Nutrition capsules. Jar count is size (keep 60 Capsules; drop 2-jar and 4-jar people-packs). 30-day mix pack is size. Cart.js is USD. Pages publish key-ingredient marketing (leave empty when there is no comma formula).",
    location: "United States",
    founded: 2018,
    categories: ["electrolytes","supplements"],
    accent: "#2B4C7E",
    rating: 4.5,
    reviewCount: 260,
    followerCount: 3100,
    websiteUrl: "https://nionhealth.com",
    logoUrl: "/brands/nion-health.svg",
  },
  {
    id: "c1381",
    slug: "happy-way",
    name: "Happy Way",
    tagline: "Australian pasture-fed whey and plant protein sweetened with stevia, no sucralose",
    story: "A Gold Coast protein house mixing pasture-fed whey concentrate and pea / hemp plant powders with stevia and thaumatin — no sucralose. Flavors already live on separate 500 g titles (Vanilla, Top of the Choc, Berry, Salted Caramel, and the rest). 500 g vs 1 kg / 2 kg / 30 g / 60 g is size. Bars, oats, pancakes, gummies, hot chocolate, pre-workout, shakers, totes, sample packs, and bundles stay boxed. Daily Hydration powders stay electrolytes; collagen / creatine / magnesium stay supplements. Cart.js is AUD — convert × 0.65. Pages publish comma formulas when a real ingredient line is on the page.",
    location: "Gold Coast, Australia",
    founded: 2016,
    categories: ["protein","electrolytes","supplements"],
    accent: "#E39B3D",
    rating: 4.6,
    reviewCount: 3400,
    followerCount: 42000,
    websiteUrl: "https://happyway.com.au",
    logoUrl: "/brands/happy-way.svg",
  },
  {
    id: "c1382",
    slug: "icarus",
    name: "Icarus",
    tagline: "Zero-chemical non-nano zinc sunscreen in tins and tubes, with cacao-tinted or white",
    story: "A small US mineral house pouring 20% non-nano zinc with organic shea, coconut, avocado, jojoba, and beeswax — cacao-tinted tin, no-cacao white tin, and a smoother body squeeze tube. Aftersun mousse and the two-ingredient goat-milk soap stay skincare. Tanks, starter packs, and complete bundles stay boxed. Cart.js is USD. Pages publish the zinc / shea / cacao list when a real formula is on the page.",
    location: "United States",
    founded: 2021,
    categories: ["sunscreen","skincare"],
    accent: "#C4783A",
    rating: 4.8,
    reviewCount: 190,
    followerCount: 2400,
    websiteUrl: "https://icaruszerochemical.com",
    logoUrl: "/brands/icarus.svg",
  },
  {
    id: "c1383",
    slug: "tallowbourn",
    name: "Tallowbourn",
    tagline: "PhD-formulated grass-fed tallow deodorant, zinc sun balm, and short-list soaps",
    story: "A US tallow house (formulated by a PhD organic chemist) pouring grass-fed tallow deodorant with magnesium hydroxide — Extra Strength and Baking Soda Free each expand Vanilla & Sandalwood / Sweet Orange & Bergamot — plus a non-nano zinc sun balm, face-and-body balm, and scent-expanded soap bars. 2 oz vs 1 oz / 4 oz is size. Gift cards, kits, sample packs, and 3-pack lips stay boxed. Cart.js is USD. Pages publish comma INCI on the baking-soda-free deodorant; other pages are benefit essays unless a real formula is listed.",
    location: "United States",
    founded: 2023,
    categories: ["deodorant","skincare","sunscreen"],
    accent: "#8B5A2B",
    rating: 4.7,
    reviewCount: 210,
    followerCount: 1800,
    websiteUrl: "https://tallowbourn.com",
    logoUrl: "/brands/tallowbourn.svg",
  },
  {
    id: "c1384",
    slug: "hikakai",
    name: "Hikakai",
    tagline: "Ayurvedic shikakai shampoo bar with zero synthetic surfactants",
    story: "A small Ayurvedic hair house saponifying coconut, argan, and castor with shikakai, amla, neem, hibiscus, and nettle — zero SCI, SLS, or silicones. Keep one Shikakai Hairwash bar (the $22.99 original), plus Champi pre-wash oil and Keshasuddhi rinse. The neem comb is a tool. Two same-title hairwash SKUs are duplicates (keep shampoo-bar). Cart.js is USD. Pages publish the 11-ingredient edible list on the bar.",
    location: "United States",
    founded: 2023,
    categories: ["hair"],
    accent: "#3F6B4A",
    rating: 4.8,
    reviewCount: 140,
    followerCount: 2200,
    websiteUrl: "https://hikakai.com",
    logoUrl: "/brands/hikakai.svg",
  },
];
