import type { Brand } from "./types";

/** Wave 53: small organic / toxic-free brands across marketplace categories (c1184+). */
export const catalogBrandsWave53: Brand[] = [
  {
    id: "c1184",
    slug: "oh-gigi",
    name: "ohGiGi",
    tagline: "Australian hydroxyapatite tooth powder in refillable glass jars",
    story: "A small Australian house that hand-blends sweetener-free organic tooth powders with 10% micro-hydroxyapatite from pasture-fed bovine bone. Individual minty, fruity, native, and flavour-free jars, refill pouches, oil-pull washes, bamboo brushes, and a copper tongue scraper stay. Ritual kits, ceramic dishes, gua sha, and mouth tape stay boxed. Storefront already prices in USD.",
    location: "Australia",
    founded: 2019,
    categories: ["oral"],
    accent: "#3D6B4F",
    rating: 4.8,
    reviewCount: 312,
    followerCount: 8600,
    websiteUrl: "https://www.ohgigi.co",
    logoUrl: "/brands/oh-gigi.svg",
  },
  {
    id: "c1185",
    slug: "weluxia",
    name: "Weluxia",
    tagline: "UK 45% micro-hydroxyapatite tooth powder and oil-pulling washes",
    story: "A small British oral house that mills remineralising tooth powders at a published 45% micro-hydroxyapatite, plus miswak powders, fluoride-free toothpaste, tooth-soap drops, gum oils, and oil-pulling mouthwashes. Individual formulas stay. Kits, spatulas, cups, holders, and syringes stay in the tool drawer. GBP prices convert to USD.",
    location: "United Kingdom",
    founded: 2021,
    categories: ["oral","supplements"],
    accent: "#6B4A2A",
    rating: 4.7,
    reviewCount: 148,
    followerCount: 4200,
    websiteUrl: "https://www.weluxia.com",
    logoUrl: "/brands/weluxia.svg",
  },
  {
    id: "c1186",
    slug: "starling",
    name: "Starling Skincare",
    tagline: "Aluminum-free deodorant sticks and bakuchiol-forward face care",
    story: "A US clean-beauty studio with baking-soda and baking-soda-free deodorant sticks — charcoal, lavender vanilla, lemon bergamot, coconut, pink rose, unscented, kids birthday cake and Force Field — plus barrier cream, bakuchiol serum, squalane, and simple balms. Individual formulas stay. Sets, gua sha, jade rollers, bath soaks, and consults stay out.",
    location: "United States",
    founded: 2018,
    categories: ["deodorant","skincare"],
    accent: "#C47A6A",
    rating: 4.7,
    reviewCount: 540,
    followerCount: 11000,
    websiteUrl: "https://buystarling.com",
    logoUrl: "/brands/starling.svg",
  },
  {
    id: "c1187",
    slug: "pravi",
    name: "PRAVI Nutrition",
    tagline: "Grass-fed goat whey, hydrate sticks, and Creapure creatine",
    story: "A small US nutrition house built around A2 goat whey from pasture-raised herds — unflavored, vanilla, and chocolate tubs — plus Hydrate+ drink mix, electrolyte salts, and Creapure creatine. Dedicated flavor SKUs stay. Essentials bundles, bottles, snapbacks, hoodies, and drawstring bags stay in the merch bin.",
    location: "United States",
    founded: 2023,
    categories: ["protein","electrolytes","supplements"],
    accent: "#2F4A3C",
    rating: 4.6,
    reviewCount: 96,
    followerCount: 2800,
    websiteUrl: "https://pravinutrition.com",
    logoUrl: "/brands/pravi.svg",
  },
  {
    id: "c1188",
    slug: "hidrate-808",
    name: "HIdrate Electrolytes",
    tagline: "Hawaii-made zero-sugar electrolyte pouches in island flavors",
    story: "A woman-owned Honolulu house mixing small-batch zero-sugar electrolyte drink mix for humid training days. Passion Orange Guava, Lightning Liliko'i, Li Hing Lemon, Electro Mango, and Coconut Lime pouches stay. Tees, singlets, stickers, swim caps, and squeeze bottles stay on the merch rack.",
    location: "Honolulu, HI",
    founded: 2024,
    categories: ["electrolytes"],
    accent: "#E07A3D",
    rating: 4.8,
    reviewCount: 74,
    followerCount: 1900,
    websiteUrl: "https://hidrate808.com",
    logoUrl: "/brands/hidrate-808.svg",
  },
  {
    id: "c1189",
    slug: "surfyogis",
    name: "SURFYOGIS",
    tagline: "Bali-made reef-safe coconut-cocoa surf zinc",
    story: "A small Bali house that still hand-makes the original Surfscreen zinc — coconut, cocoa, coffee, vanilla, beeswax, castor oil, and non-nano zinc — plus a cold-climate formula for cooler water. The two zinc tins stay. The try-me bundle and corduroy hat stay boxed.",
    location: "Bali, Indonesia",
    founded: 2008,
    categories: ["sunscreen"],
    accent: "#1B4F6B",
    rating: 4.8,
    reviewCount: 220,
    followerCount: 15000,
    websiteUrl: "https://surfyogis.com",
    logoUrl: "/brands/surfyogis.svg",
  },
  {
    id: "c1190",
    slug: "marroomi",
    name: "Marroomi",
    tagline: "Grass-fed tallow balms with raw honey and a tallow lip tin",
    story: "A small US tallow studio that whips grass-fed beef tallow with raw honey or manuka, then pours a simple lip balm. Individual unscented, lavender, and honey balms plus the lip tin stay. Trios, collections, variety packs, Spanish duplicate listings, and shipping protection stay out.",
    location: "United States",
    founded: 2023,
    categories: ["skincare"],
    accent: "#8B5A2B",
    rating: 4.7,
    reviewCount: 88,
    followerCount: 2100,
    websiteUrl: "https://marroomi.com",
    logoUrl: "/brands/marroomi.svg",
  },
  {
    id: "c1191",
    slug: "tallow-company",
    name: "The Tallow Company",
    tagline: "Whipped tallow balms, tallow soaps, beard balm, and hair balm",
    story: "A small US tallow house pouring unscented and lavender whipped balms, eczema and stretch-mark jars, peppermint chapstick, tallow soaps, a beard balm, and a whipped hair balm. Individual formulas stay. Jar size stays one listing.",
    location: "United States",
    founded: 2022,
    categories: ["skincare","hair"],
    accent: "#6B3E26",
    rating: 4.7,
    reviewCount: 64,
    followerCount: 1400,
    websiteUrl: "https://thetallowcompany.com",
    logoUrl: "/brands/tallow-company.svg",
  },
  {
    id: "c1192",
    slug: "carolina-tallow",
    name: "Carolina Tallow",
    tagline: "Carolinas tallow-and-honey balms, travel tins, soaps, and lip",
    story: "A Carolina homestead that pours tallow-and-honey balms in sweet orange, peppermint, lavender, vanilla, and unscented, plus travel tins, tallow soaps, and beeswax lip. Scent options expand. Jar size stays one listing. Gift cards, soap savers, and variety-pack tins stay out.",
    location: "Carolinas, United States",
    founded: 2022,
    categories: ["skincare"],
    accent: "#4A6B3A",
    rating: 4.6,
    reviewCount: 52,
    followerCount: 980,
    websiteUrl: "https://carolinatallow.com",
    logoUrl: "/brands/carolina-tallow.svg",
  },
];
