import type { Brand } from "./types";

/** Wave 78: small organic / toxic-free brands across marketplace categories (c1337+). */
export const catalogBrandsWave78: Brand[] = [
  {
    id: "c1337",
    slug: "dr-jen",
    name: "Dr. Jen Natural",
    tagline: "Dentist-made 10% nano-hydroxyapatite toothpaste in Cool Mint, Strawberry, Watermelon, and eggshell Orange Mango",
    story: "A dentist-led oral house built around 10% premium n-HA — fluoride-free Cool Mint / Strawberry / Watermelon, eggshell Cool Mint / Orange Mango, Super Paste Cool Mint / Strawberry, plus rinse, dry-mouth gel, and silk floss. Flavor expands; pack count and travel size are size. Bundles, kits, family packs, 3-packs, summer mix, and toothbrush color stay boxed. Keep one gentle-bristle brush. Pages publish Water / glycerin / silica / xylitol / n-HA INCI when a real list is on the page.",
    location: "United States",
    founded: 2023,
    categories: ["oral"],
    accent: "#2F6F7A",
    rating: 4.7,
    reviewCount: 1840,
    followerCount: 28000,
    websiteUrl: "https://drjennatural.com",
    logoUrl: "/brands/dr-jen.svg",
  },
  {
    id: "c1338",
    slug: "doingwell",
    name: "doingwell",
    tagline: "Zero-sugar monk-fruit electrolytes in Mango daily, Coconut Lime, and Raspberry — no stevia, no sucralose",
    story: "A small US hydration house mixing Himalayan pink salt, potassium, magnesium malate, organic monk fruit, and coconut water powder. Mango Daily, Coconut Lime Performance, and Raspberry Performance already live on separate titles; stick count is size. Tees, totes, bottles, gift cards, sampler packs, and POG nootropic energy stay boxed. Cart.js is USD. Pages are key-ingredient marketing (leave empty unless a real formula is published).",
    location: "United States",
    founded: 2024,
    categories: ["electrolytes"],
    accent: "#C46A2A",
    rating: 4.6,
    reviewCount: 210,
    followerCount: 4200,
    websiteUrl: "https://doingwell.health",
    logoUrl: "/brands/doingwell.svg",
  },
  {
    id: "c1339",
    slug: "mt-capra",
    name: "Mt. Capra",
    tagline: "Chehalis, Washington grass-fed goat whey, casein, and whole-milk protein from a family farm",
    story: "A Chehalis goat-dairy house making Clean Whey (Unsweetened / Vanilla / Chocolate), Clean Casein (Unsweetened / Cinnamon Roll), Caprotein, Double Bonded, and DEEP 30 from their own herd. Pound count and handy packs are size. Creatine and minerals stay supplements; Clean Electrolytes stay electrolytes; goat-milk soap Scent expands. Hoodies, hats, shakers, coffee, ghee, cream, milk powder, gift cards, and sampler packs stay boxed. Cart.js is USD.",
    location: "Chehalis, WA",
    founded: 1928,
    categories: ["protein","supplements","electrolytes","skincare"],
    accent: "#3F5A32",
    rating: 4.8,
    reviewCount: 3200,
    followerCount: 19000,
    websiteUrl: "https://mtcapra.com",
    logoUrl: "/brands/mt-capra.png",
  },
  {
    id: "c1340",
    slug: "lasso",
    name: "LASSO",
    tagline: "Five-ingredient mineral tallow sun balm with non-nano zinc, grass-fed tallow, beeswax, and vanilla",
    story: "A small US tallow house pouring non-nano zinc with organic grass-fed tallow, beeswax, vitamin E, and vanilla — plus Manuka honey moisturizer and a copper-peptide tallow cream. Moisturizer Scent expands Frankincense Citrus / Unscented / Lavender. Variety packs and sun/skin kits stay boxed. Sun balm publishes the five-ingredient zinc list when a real formula is on the page.",
    location: "United States",
    founded: 2024,
    categories: ["sunscreen","skincare"],
    accent: "#C9A24A",
    rating: 4.8,
    reviewCount: 160,
    followerCount: 5400,
    websiteUrl: "https://lassotallow.us",
    logoUrl: "/brands/lasso.svg",
  },
  {
    id: "c1341",
    slug: "freo-living",
    name: "Freo Living",
    tagline: "Calgary plant-powered shampoo and conditioner bars, aluminum-free Pit Stop deodorant, and solid body care",
    story: "A woman-owned Calgary house making concentrated shampoo and conditioner bars (Nice Flow, Good Hair Day, Curl Boss, kids Tangles Beware), Pit Stop magnesium deodorant, everywhere soaps, and Soft Serve lotions. Scents already live on separate titles. Bundles stay boxed. Cart.js is CAD × 0.73. Pages are plant-powered marketing (leave empty unless a real INCI is published).",
    location: "Calgary, AB",
    founded: 2021,
    categories: ["hair","deodorant","skincare"],
    accent: "#5B7A6A",
    rating: 4.7,
    reviewCount: 380,
    followerCount: 8600,
    websiteUrl: "https://freoliving.com",
    logoUrl: "/brands/freo-living.svg",
  },
  {
    id: "c1342",
    slug: "half-hill-farm",
    name: "Half Hill Farm",
    tagline: "Woodbury, Tennessee USDA-organic fruiting-body lion's mane, reishi, turkey tail, chaga, and cordyceps dual extracts",
    story: "A seven-acre USDA-certified organic farm in Woodbury making farm-to-bottle dual extracts from fully mature US-grown fruiting bodies — lion's mane, red reishi, turkey tail, chaga, cordyceps, and a five-mushroom blend. Bottle size is size. Tees, hoodies, pet powders, bitters, ACV tonics, and merch stay boxed. Tincture pages publish fruiting-body + alcohol + water when a real formula is listed.",
    location: "Woodbury, TN",
    founded: 2012,
    categories: ["supplements"],
    accent: "#4A5E32",
    rating: 4.8,
    reviewCount: 640,
    followerCount: 12000,
    websiteUrl: "https://store.halfhillfarm.com",
    logoUrl: "/brands/half-hill-farm.svg",
  },
];
