import type { Brand } from "./types";

/** Curated small organic / grass-fed protein brands. */
export const catalogBrandsWhey: Brand[] = [
  {
    id: "c201",
    slug: "raw-organic-whey",
    name: "Raw Organic Whey",
    tagline: "Cold-processed organic grass-fed whey",
    story: "Single-ingredient USDA organic grass-fed whey — cold-processed, no gums, no sweetener circus. Just pasture protein with a hardcore simple flex.",
    location: "United States",
    founded: 2012,
    categories: ["protein"],
    accent: "#2F4F2F",
    rating: 4.5,
    reviewCount: 1200,
    followerCount: 8000,
    websiteUrl: "https://www.raworganicwhey.com",
    logoUrl: "/brands/raw-organic-whey.svg",
  },
  {
    id: "c202",
    slug: "levels-protein",
    name: "Levels",
    tagline: "100% grass-fed organic whey",
    story: "Organic grass-fed whey isolate and concentrate for lifters who read labels like PRs — clean macros, loud results, zero candy-chemical aftertaste.",
    location: "United States",
    founded: 2016,
    categories: ["protein"],
    accent: "#E74C3C",
    rating: 4.6,
    reviewCount: 2197,
    followerCount: 12099,
    websiteUrl: "https://levelsprotein.com",
    logoUrl: "/brands/levels-protein.png",
  },
  {
    id: "c203",
    slug: "natural-force",
    name: "Natural Force",
    tagline: "Organic grass-fed performance whey",
    story: "Organic grass-fed whey and MCT fuel for athletes who want clean horsepower — pasture-raised protein without the filler fog.",
    location: "United States",
    founded: 2015,
    categories: ["protein","supplements"],
    accent: "#1A5276",
    rating: 4.7,
    reviewCount: 3194,
    followerCount: 16198,
    websiteUrl: "https://naturalforce.com",
    logoUrl: "/brands/natural-force.png",
  },
  {
    id: "c204",
    slug: "promix",
    name: "Promix Nutrition",
    tagline: "No-BS grass-fed whey protein",
    story: "Transparent grass-fed whey with short labels and heavy training energy — athlete staples that skip the bro-science theater.",
    location: "Florida",
    founded: 2011,
    categories: ["protein","supplements"],
    accent: "#2C3E50",
    rating: 4.8,
    reviewCount: 4191,
    followerCount: 20297,
    websiteUrl: "https://promixnutrition.com",
    logoUrl: "/brands/promix.png",
  },
  {
    id: "c205",
    slug: "transparent-labs",
    name: "Transparent Labs",
    tagline: "Grass-fed whey, fully transparent",
    story: "Clinically dosed grass-fed whey with labels so honest they put the industry on notice — badass transparency in every scoop.",
    location: "United States",
    founded: 2015,
    categories: ["protein","supplements"],
    accent: "#1ABC9C",
    rating: 4.9,
    reviewCount: 5188,
    followerCount: 24396,
    websiteUrl: "https://www.transparentlabs.com",
    logoUrl: "/brands/transparent-labs.png",
  },
  {
    id: "c206",
    slug: "jay-robb",
    name: "Jay Robb",
    tagline: "OG clean whey and egg protein",
    story: "Legendary clean whey and egg white protein — reading labels before it was cool, still hitting hard in the gym bag.",
    location: "California",
    founded: 1988,
    categories: ["protein"],
    accent: "#F1C40F",
    rating: 4.5,
    reviewCount: 6185,
    followerCount: 28495,
    websiteUrl: "https://www.jayrobb.com",
    logoUrl: "/brands/jay-robb.png",
  },
  {
    id: "c207",
    slug: "kaizen",
    name: "Kaizen Naturals",
    tagline: "Canadian clean whey protein",
    story: "Canadian-made whey with a no-nonsense athlete ethos — clean formulas, serious training, cold-climate grit.",
    location: "Canada",
    founded: 2012,
    categories: ["protein"],
    accent: "#C0392B",
    rating: 4.6,
    reviewCount: 7182,
    followerCount: 32594,
    websiteUrl: "https://kaizennaturals.com",
    logoUrl: "/brands/kaizen.png",
  },
  {
    id: "c208",
    slug: "just-ingredients",
    name: "Just Ingredients",
    tagline: "Clean whey with real-food energy",
    story: "Functional whey protein powders with ingredient lists you can pronounce — clean fuel for busy, high-output lives.",
    location: "United States",
    founded: 2019,
    categories: ["protein","supplements"],
    accent: "#27AE60",
    rating: 4.7,
    reviewCount: 8179,
    followerCount: 36693,
    websiteUrl: "https://justingredients.us",
    logoUrl: "/brands/just-ingredients.png",
  },
  {
    id: "c209",
    slug: "flavcity",
    name: "FlavCity",
    tagline: "Bobby-approved clean whey protein",
    story: "Bobby Parrish’s flavor-first clean protein — organic-minded shakes for people who refuse boring chalk water.",
    location: "United States",
    founded: 2019,
    categories: ["protein","supplements"],
    accent: "#E74C3C",
    rating: 4.8,
    reviewCount: 9176,
    followerCount: 40792,
    websiteUrl: "https://flavcity.com",
    logoUrl: "/brands/flavcity.png",
  },
  {
    id: "c210",
    slug: "be-well-by-kelly",
    name: "Be Well by Kelly",
    tagline: "Clean protein by Kelly LeVeque",
    story: "Fab Four–friendly clean protein for blood-sugar-smart routines — soft branding, serious scoop quality.",
    location: "Los Angeles, CA",
    founded: 2018,
    categories: ["protein","supplements"],
    accent: "#F5CBA7",
    rating: 4.9,
    reviewCount: 10173,
    followerCount: 44891,
    websiteUrl: "https://bewellbykelly.com",
    logoUrl: "/brands/be-well-by-kelly.png",
  },
  {
    id: "c211",
    slug: "bulletproof",
    name: "Bulletproof",
    tagline: "Grass-fed protein for high performers",
    story: "Grass-fed collagen and protein for biohackers — MCT energy and clean macros with a sharp, high-performance edge.",
    location: "United States",
    founded: 2013,
    categories: ["protein","supplements"],
    accent: "#1A1A1A",
    rating: 4.5,
    reviewCount: 11170,
    followerCount: 48990,
    websiteUrl: "https://shop.bulletproof.com",
    logoUrl: "/brands/bulletproof.png",
  },
  {
    id: "c212",
    slug: "wild-foods",
    name: "Wild Foods Co",
    tagline: "Wildcrafted pantry protein",
    story: "Wild and regenerative pantry protein — cacao, whey-adjacent fuel, and adaptogens with frontiersman cool.",
    location: "Pacific Northwest",
    founded: 2015,
    categories: ["protein","supplements"],
    accent: "#3D2914",
    rating: 4.6,
    reviewCount: 12167,
    followerCount: 53089,
    websiteUrl: "https://www.wildfoods.co",
    logoUrl: "/brands/wild-foods.png",
  },
  {
    id: "c213",
    slug: "bubs-naturals",
    name: "BUBS Naturals",
    tagline: "Clean protein with purpose",
    story: "Veteran-honoring clean collagen and protein — simple ingredients, adventure energy, giveback baked into every tub.",
    location: "United States",
    founded: 2017,
    categories: ["protein","supplements"],
    accent: "#F39C12",
    rating: 4.7,
    reviewCount: 13164,
    followerCount: 57188,
    websiteUrl: "https://www.bubsnaturals.com",
    logoUrl: "/brands/bubs-naturals.png",
  },
  {
    id: "c214",
    slug: "equip-foods",
    name: "Equip Foods",
    tagline: "Prime animal protein, no dairy drama",
    story: "Nose-to-tail prime protein for primal athletes — beef-based muscle fuel that skips whey without skipping intensity.",
    location: "United States",
    founded: 2018,
    categories: ["protein"],
    accent: "#8B4513",
    rating: 4.8,
    reviewCount: 14161,
    followerCount: 61287,
    websiteUrl: "https://equipfoods.com",
    logoUrl: "/brands/equip-foods.png",
  },
  {
    id: "c215",
    slug: "paleopro",
    name: "PaleoPro",
    tagline: "Paleo protein without the junk",
    story: "Beef and egg protein for paleo athletes — dairy-free muscle fuel with a hardcore clean-eating spine.",
    location: "United States",
    founded: 2013,
    categories: ["protein"],
    accent: "#A0522D",
    rating: 4.9,
    reviewCount: 15158,
    followerCount: 65386,
    websiteUrl: "https://paleopro.com",
    logoUrl: "/brands/paleopro.svg",
  },
  {
    id: "c216",
    slug: "four-sigmatic",
    name: "Four Sigmatic",
    tagline: "Mushroom protein with cult energy",
    story: "Finnish-born mushroom protein and coffee rituals — functional fungi meets everyday performance cool.",
    location: "Los Angeles, CA",
    founded: 2012,
    categories: ["protein","supplements"],
    accent: "#6B3FA0",
    rating: 4.5,
    reviewCount: 16155,
    followerCount: 69485,
    websiteUrl: "https://foursigmatic.com",
    logoUrl: "/brands/four-sigmatic.png",
  },
  {
    id: "c217",
    slug: "gainful",
    name: "Gainful",
    tagline: "Custom whey, personalized",
    story: "Questionnaire-custom whey blends tuned to your goals — personalized protein without the one-tub-fits-all myth.",
    location: "United States",
    founded: 2018,
    categories: ["protein"],
    accent: "#5DADE2",
    rating: 4.6,
    reviewCount: 17152,
    followerCount: 73584,
    websiteUrl: "https://www.gainful.com",
    logoUrl: "/brands/gainful.png",
  },
  {
    id: "c218",
    slug: "native-path",
    name: "NativePath",
    tagline: "Grass-fed collagen protein",
    story: "Ancestral grass-fed collagen protein for modern joints and muscle — clean scoops with old-world nutrition logic.",
    location: "United States",
    founded: 2016,
    categories: ["protein","supplements"],
    accent: "#8B7355",
    rating: 4.7,
    reviewCount: 18149,
    followerCount: 77683,
    websiteUrl: "https://www.nativepath.com",
    logoUrl: "/brands/native-path.png",
  },
  {
    id: "c219",
    slug: "further-food",
    name: "Further Food",
    tagline: "Collagen protein that actually mixes",
    story: "Clean collagen peptides for coffee and training days — beauty-meets-athlete protein culture in one scoop.",
    location: "United States",
    founded: 2016,
    categories: ["protein","supplements"],
    accent: "#E8A0BF",
    rating: 4.8,
    reviewCount: 19146,
    followerCount: 81782,
    websiteUrl: "https://www.furtherfood.com",
    logoUrl: "/brands/further-food.png",
  },
  {
    id: "c220",
    slug: "hunter-gather",
    name: "Hunter & Gather",
    tagline: "Ancestral protein and clean fats",
    story: "UK ancestral collagen and protein for people who eat like hunters and train like modern athletes.",
    location: "United Kingdom",
    founded: 2016,
    categories: ["protein","supplements"],
    accent: "#5D4037",
    rating: 4.9,
    reviewCount: 20143,
    followerCount: 85881,
    websiteUrl: "https://hunterandgatherfoods.com",
    logoUrl: "/brands/hunter-gather.png",
  },
  {
    id: "c221",
    slug: "ancient-supplements",
    name: "Ancestral Supplements",
    tagline: "Nose-to-tail organ protein",
    story: "Desiccated organ supplements for nose-to-tail athletes — hardcore ancestral protein beyond the whey aisle.",
    location: "Texas",
    founded: 2014,
    categories: ["protein","supplements"],
    accent: "#4A3728",
    rating: 4.5,
    reviewCount: 21140,
    followerCount: 89980,
    websiteUrl: "https://ancestralsupplements.com",
    logoUrl: "/brands/ancient-supplements.png",
  },
  {
    id: "c222",
    slug: "heart-and-soil",
    name: "Heart & Soil",
    tagline: "Animal-based organ supplements",
    story: "Organ-based supplements with a renegade health streak — animal nutrition for people who don’t do lukewarm.",
    location: "United States",
    founded: 2020,
    categories: ["protein","supplements"],
    accent: "#8B0000",
    rating: 4.6,
    reviewCount: 22137,
    followerCount: 94079,
    websiteUrl: "https://shop.heartandsoil.co",
    logoUrl: "/brands/heart-and-soil.png",
  },
  {
    id: "c223",
    slug: "force-of-nature",
    name: "Force of Nature",
    tagline: "Regenerative meat protein",
    story: "Regenerative meats and animal protein for cooks who care about soil — wild flavor, climate-forward farms, badass dinners.",
    location: "Texas",
    founded: 2017,
    categories: ["protein"],
    accent: "#2E7D32",
    rating: 4.7,
    reviewCount: 23134,
    followerCount: 98178,
    websiteUrl: "https://forceofnature.com",
    logoUrl: "/brands/force-of-nature.png",
  },
  {
    id: "c224",
    slug: "peak-refuel",
    name: "Peak Refuel",
    tagline: "High-protein outdoor meals",
    story: "Freeze-dried high-protein meals for hunters and hikers — real meat energy for people who earn their appetite outside.",
    location: "Utah",
    founded: 2018,
    categories: ["protein"],
    accent: "#8B4513",
    rating: 4.8,
    reviewCount: 24131,
    followerCount: 102277,
    websiteUrl: "https://peakrefuel.com",
    logoUrl: "/brands/peak-refuel.png",
  },
  {
    id: "c225",
    slug: "good-protein",
    name: "Good Protein",
    tagline: "Canadian clean protein shakes",
    story: "Canadian protein shakes with dessert flavors and cleaner formulas — daily shake culture without the sketchy blend.",
    location: "Canada",
    founded: 2018,
    categories: ["protein"],
    accent: "#9B59B6",
    rating: 4.9,
    reviewCount: 25128,
    followerCount: 106376,
    websiteUrl: "https://goodprotein.ca",
    logoUrl: "/brands/good-protein.png",
  },
];
