import type { Brand } from "./types";

/** Wave 68: small organic / toxic-free brands across marketplace categories (c1278+). */
export const catalogBrandsWave68: Brand[] = [
  {
    id: "c1278",
    slug: "terra-and-co",
    name: "Terra & Co.",
    tagline: "Ayurvedic hydroxyapatite toothpaste, oil pulling, and charcoal floss without fluoride",
    story: "A small holistic oral house that pairs clinically studied hydroxyapatite with Ayurvedic oil pulling and bamboo-charcoal floss. Brilliant Black is the whitening charcoal paste; Gentle Green is the sensitive enamel tube. Travel vs 3.4 oz is size. Duos, family bundles, and the dog paste stay boxed.",
    location: "United States",
    founded: 2018,
    categories: ["oral"],
    accent: "#2F4A3C",
    rating: 4.6,
    reviewCount: 142,
    followerCount: 2600,
    websiteUrl: "https://terraandco.com",
    logoUrl: "/brands/terra-and-co.svg",
  },
  {
    id: "c1279",
    slug: "sealyte",
    name: "Sealyte",
    tagline: "Zero-sugar citrus electrolyte mix with 1,475 mg minerals and Solar Sea trace salts",
    story: "A tiny hydration house with one citrus drink mix: 1,000 mg sodium chloride, 400 mg potassium, 75 mg magnesium, Solar Sea trace minerals, and a refined stevia extract. 30 / 60 / 90 servings is size, not a flavor. Hats and variety packs stay boxed if they ever appear. Cart.js is USD.",
    location: "United States",
    founded: 2024,
    categories: ["electrolytes"],
    accent: "#2A6A7A",
    rating: 4.5,
    reviewCount: 38,
    followerCount: 700,
    websiteUrl: "https://drinksealyte.com",
    logoUrl: "/brands/sealyte.svg",
  },
  {
    id: "c1280",
    slug: "noble-origins",
    name: "Noble Origins",
    tagline: "Grass-fed beef protein isolate with collagen and colostrum in vanilla and chocolate",
    story: "A tiny nose-to-tail protein house that skips whey for regeneratively raised grass-fed beef isolate plus collagen and colostrum. Vanilla and Chocolate already live on separate titles. Serving-count size is not a flavor. The flavor-picker parent and the mixed bundle stay boxed.",
    location: "United States",
    founded: 2023,
    categories: ["protein"],
    accent: "#5A3A28",
    rating: 4.6,
    reviewCount: 64,
    followerCount: 1500,
    websiteUrl: "https://nobleorigins.com",
    logoUrl: "/brands/noble-origins.svg",
  },
  {
    id: "c1281",
    slug: "faithfully-natural",
    name: "Faithfully Natural Soap Co.",
    tagline: "Tennessee mineral sun butter, tallow magnesium deodorant, and seed-oil-free shampoo bars",
    story: "A small Tennessee soap kitchen that pours a mineral Sun Butter, baking-soda-free tallow deodorants (Powerhouse, Cedarwood & Rosemary, Lemon/Tea Tree, Unscented), pH-balanced shampoo and conditioner bars, and tallow goat-milk soaps. Deodorant scents already live on separate titles. Bug spray, ebooks, subscriptions, imperfect bars, pet soap, and dishes stay boxed.",
    location: "Tennessee",
    founded: 2021,
    categories: ["sunscreen","deodorant","hair","skincare"],
    accent: "#7A6B3A",
    rating: 4.7,
    reviewCount: 96,
    followerCount: 1200,
    websiteUrl: "https://faithfullynaturalsoapco.com",
    logoUrl: "/brands/faithfully-natural.svg",
  },
  {
    id: "c1282",
    slug: "lil-swatara",
    name: "Lil Swatara Soap",
    tagline: "Pennsylvania homestead goat-milk soaps, baking-soda-free deodorant, and XL shampoo bars",
    story: "A Nigerian Dwarf goat homestead in Pennsylvania that pours XL goat-milk soaps, aluminum-free Bright Citrus and Calm Clean deodorant, named shampoo bars, and goat-milk lotions. Deodorant Scent expands; shampoo Types expand; lotion scents expand and jar ounces stay size. Stamps, mugs, dishes, dog shampoo, cologne, dish soap, and outdoor bug spray stay boxed.",
    location: "Pennsylvania",
    founded: 2016,
    categories: ["deodorant","hair","skincare"],
    accent: "#8A6A3A",
    rating: 4.8,
    reviewCount: 210,
    followerCount: 2400,
    websiteUrl: "https://lilswatara.com",
    logoUrl: "/brands/lil-swatara.svg",
  },
];
