import type { Brand } from "./types";

/** Wave 34: small organic / toxic-free brands across marketplace categories (c1008+). */
export const catalogBrandsWave34: Brand[] = [
  {
    id: "c1008",
    slug: "zebra",
    name: "ZEBRA",
    tagline: "Hydroxyapatite-free toothpaste tablets plus baking-soda-free deodorant — short lists, no campus merch aisle",
    story: "A small US oral house that chews fluoride-free toothpaste into tablets with kaolin and calcium, then pours a baking-soda-free deodorant instead of a drugstore antiperspirant wall. Mint and coconut pastes, floss, and Awake / Liberty / Bright sticks stay as their own listings. Lip gloss, scrunchies, sweatshirts, travel puffs, and SavedBy shipping widgets stay out.",
    location: "United States",
    founded: 2021,
    categories: ["oral","deodorant"],
    accent: "#1A1A1A",
    rating: 4.7,
    reviewCount: 420,
    followerCount: 6800,
    websiteUrl: "https://yayzebra.com",
    logoUrl: "/brands/zebra.svg",
  },
  {
    id: "c1009",
    slug: "tuttofare",
    name: "TUTTOFARE",
    tagline: "Australian grass-fed tallow balms and magnesium deodorant — GMP kitchen, no chemical-filter cream wall",
    story: "Australia's first GMP tallow skincare kitchen pours grass-fed, grass-finished balms and a magnesium-zinc deodorant instead of a 40-ingredient lotion aisle. Holy Grail, Roman Blue, and Sicilian Citrus stay as their own listings. Caps, gua sha, gift cards, and shipping-protection SKUs stay in the merch drawer.",
    location: "Australia",
    founded: 2022,
    categories: ["deodorant","skincare"],
    accent: "#6B3E26",
    rating: 4.8,
    reviewCount: 2500,
    followerCount: 18000,
    websiteUrl: "https://tuttofare.com.au",
    logoUrl: "/brands/tuttofare.svg",
  },
  {
    id: "c1010",
    slug: "own-skin",
    name: "OWN Skin Co",
    tagline: "Canadian grass-fed tallow deodorant, after-sun oil, and dry shampoo — no gadget gua-sha shop",
    story: "A Canadian tallow kitchen that renders grass-fed suet into aluminum-free deodorant, whipped face-and-body creams, and a non-nano zinc after-sun oil instead of a fragrance-heavy cream wall. Scent and flavor variants stay as their own listings. Gua sha, spatulas, and gift cards stay in the tool drawer.",
    location: "Canada",
    founded: 2021,
    categories: ["deodorant","skincare","hair"],
    accent: "#8B6914",
    rating: 4.7,
    reviewCount: 380,
    followerCount: 5400,
    websiteUrl: "https://ownskinco.ca",
    logoUrl: "/brands/own-skin.svg",
  },
  {
    id: "c1011",
    slug: "boba-tea-protein",
    name: "Boba Tea Protein",
    tagline: "Grass-fed whey in milk-tea flavors — monk fruit, no candy-protein aisle, no boba-pearl pantry",
    story: "A small US protein house that seasons grass-fed whey isolate like a milk-tea counter — taro, jasmine, Thai tea, matcha mushroom latte — instead of a cookie-dough tub wall. Each flavor stays as its own listing. T-shirts, hats, tumblers, shakers, frothers, and instant boba pearls stay in the snack cupboard.",
    location: "United States",
    founded: 2020,
    categories: ["protein"],
    accent: "#C45C26",
    rating: 4.6,
    reviewCount: 890,
    followerCount: 12000,
    websiteUrl: "https://bobateaprotein.com",
    logoUrl: "/brands/boba-tea-protein.svg",
  },
  {
    id: "c1012",
    slug: "earthling-co",
    name: "The Earthling Co",
    tagline: "Plastic-free shampoo and conditioner bars — scent variants, no soap-dish accessory wall",
    story: "A zero-waste hair kitchen that ships concentrated shampoo and conditioner bars instead of a water-heavy plastic bottle aisle. Sensitive, moisture, and volume bars plus dry shampoo stay, and scent variants stay as their own listings. Travel cases, soap dishes, shower caddies, sisal bags, and carbon-offset widgets stay out.",
    location: "United States",
    founded: 2018,
    categories: ["hair","skincare"],
    accent: "#2C5F4E",
    rating: 4.7,
    reviewCount: 2100,
    followerCount: 34000,
    websiteUrl: "https://www.theearthlingco.com",
    logoUrl: "/brands/earthling-co.svg",
  },
  {
    id: "c1013",
    slug: "only-hydration",
    name: "ONLY Hydration",
    tagline: "Art-directed electrolyte drink mixes — yuzu, lychee, white peach, no neon sports-drink stick",
    story: "A four-flavor hydration house that seasons water with yuzu citrus, lychee, white peach, and Asian pear instead of a maltodextrin packet. Each flavor stays as its own listing. Holiday gift kits, free shakers, and empty bottles stay at checkout.",
    location: "United States",
    founded: 2023,
    categories: ["electrolytes"],
    accent: "#1B4F72",
    rating: 4.6,
    reviewCount: 160,
    followerCount: 2400,
    websiteUrl: "https://onlyhydration.com",
    logoUrl: "/brands/only-hydration.svg",
  },
  {
    id: "c1014",
    slug: "elxr",
    name: "ELXR",
    tagline: "Canadian fully-dosed electrolytes — 1000mg sodium, monk fruit, no sucralose stick",
    story: "A two-SKU Canadian kitchen that doses 1000mg sodium, 400mg potassium, and magnesium with coconut water powder and monk fruit instead of a stevia-sports-drink wall. Lemon lime and watermelon stay as their own listings. Empty bottles stay out.",
    location: "Canada",
    founded: 2024,
    categories: ["electrolytes"],
    accent: "#1565C0",
    rating: 4.6,
    reviewCount: 90,
    followerCount: 1500,
    websiteUrl: "https://elxrpower.com",
    logoUrl: "/brands/elxr.svg",
  },
  {
    id: "c1015",
    slug: "lyt-hydration",
    name: "LYT Hydration",
    tagline: "One-SKU strawberry electrolytes with creatine — real fruit extract, no junk drink mix",
    story: "A one-SKU hydration house that folds creatine monohydrate into a strawberry electrolyte instead of a neon pre-workout tub. The strawberry pouch stays. Merch stays out.",
    location: "United States",
    founded: 2024,
    categories: ["electrolytes"],
    accent: "#C2185B",
    rating: 4.5,
    reviewCount: 40,
    followerCount: 600,
    websiteUrl: "https://lythydration.com",
    logoUrl: "/brands/lyt-hydration.svg",
  },
  {
    id: "c1016",
    slug: "denttabs",
    name: "Denttabs",
    tagline: "German toothpaste tablets — mint, strawberry, cinnamon, fluoride or fluoride-free, no gadget tray",
    story: "A Berlin oral house that compresses toothpaste into chewable tablets instead of a plastic-tube aisle. Mint, strawberry, and cinnamon stay as their own listings, with and without fluoride. The merch book and 1kg wholesale bags stay in the warehouse.",
    location: "Berlin, Germany",
    founded: 2009,
    categories: ["oral"],
    accent: "#2E7D32",
    rating: 4.7,
    reviewCount: 1800,
    followerCount: 22000,
    websiteUrl: "https://denttabs.com",
    logoUrl: "/brands/denttabs.svg",
  },
  {
    id: "c1017",
    slug: "first-curve",
    name: "First Curve Apothecary",
    tagline: "Chicago herbal mushroom extracts and short-list salves — fruiting-body tinctures, no tea-shop wall",
    story: "A Chicago apothecary that double-extracts lion's mane, reishi, chaga, and turkey tail from organically grown mushrooms instead of a myceliated-grain capsule aisle. Herb tincture variants stay as their own listings. Teas, custom formulas, wholesale tickets, and the zine stay on the reading table.",
    location: "Chicago, Illinois",
    founded: 2019,
    categories: ["supplements","skincare"],
    accent: "#5B7A3A",
    rating: 4.8,
    reviewCount: 210,
    followerCount: 3200,
    websiteUrl: "https://firstcurveapothecary.com",
    logoUrl: "/brands/first-curve.svg",
  },
  {
    id: "c1018",
    slug: "shelter-skin",
    name: "Shelter Skin",
    tagline: "Tallow body butters and lanolin lip elixir — short lists, no perfume-oil or gua-sha tool wall",
    story: "A small tallow kitchen that pours vanilla, solar, and deep-end body butters plus a lanolin lip elixir instead of a 40-ingredient lotion wall. Shade and package variants stay as their own listings. Perfume oils, hair brushes, candles, gua sha, and silk scrunchies stay in the accessory drawer.",
    location: "United States",
    founded: 2022,
    categories: ["skincare"],
    accent: "#5E4B45",
    rating: 4.7,
    reviewCount: 280,
    followerCount: 4100,
    websiteUrl: "https://shelterskin.com",
    logoUrl: "/brands/shelter-skin.svg",
  },
];
