import type { Brand } from "./types";

/** Wave 31: small organic / toxic-free brands across marketplace categories (c970+). */
export const catalogBrandsWave31: Brand[] = [
  {
    id: "c970",
    slug: "oak-and-sage",
    name: "Oak & Sage",
    tagline: "Grass-fed tallow creams and balms — short farm lists, no 40-ingredient cream",
    story: "A US ancestral kitchen that whips grass-fed tallow into everywhere creams, eczema balm, and a scalp hair oil instead of a silicone moisturizer. Scent variants stay as their own listings. Beard balm and lip balm stay. Gift cards and self-tan oils stay out.",
    location: "United States",
    founded: 2023,
    categories: ["skincare","hair"],
    accent: "#6B8F71",
    rating: 4.8,
    reviewCount: 180,
    followerCount: 3200,
    websiteUrl: "https://oaksageskincare.com",
    logoUrl: "/brands/oak-and-sage.svg",
  },
  {
    id: "c971",
    slug: "skin-balm-apothecary",
    name: "Skin Balm Apothecary",
    tagline: "Coconut-free mineral sun balm — non-nano zinc, no industrial seed-oil dump",
    story: "A small apothecary that writes a mineral sun balm around babassu, raspberry seed, and non-nano zinc instead of coconut-heavy drugstore SPF. Shade variants stay as their own listings. Dry shampoo, cleansing oils, and baby balm stay. Merch stays out.",
    location: "United States",
    founded: 2021,
    categories: ["sunscreen","skincare","hair"],
    accent: "#C4A07A",
    rating: 4.7,
    reviewCount: 140,
    followerCount: 2600,
    websiteUrl: "https://www.skinbalmapothecary.com",
    logoUrl: "/brands/skin-balm-apothecary.svg",
  },
  {
    id: "c972",
    slug: "earth-herd-harvest",
    name: "Earth Herd Harvest",
    tagline: "Shire-made tallow zinc sunscreen — grass-finished fat, non-nano zinc, no chemical filter",
    story: "A Sutherland Shire family kitchen that renders 100% grass-finished tallow, then folds in local beeswax and non-nano zinc instead of a chemical beach cream. Mineral sunscreen, everyday balm, and baby zinc barrier stay. Room mists and lash serums stay on the shelf.",
    location: "Sutherland Shire, Australia",
    founded: 2024,
    categories: ["sunscreen","skincare"],
    accent: "#8B6914",
    rating: 4.8,
    reviewCount: 70,
    followerCount: 1100,
    websiteUrl: "https://earthherdharvest.com.au",
    logoUrl: "/brands/earth-herd-harvest.svg",
  },
  {
    id: "c973",
    slug: "pure-tallow-eu",
    name: "Pure Tallow",
    tagline: "European tallow sun balm and deodorant — short farm lists, no aluminum stick",
    story: "A European render house that pours an everyday tallow sun balm and an aluminum-free deodorant stick instead of a silicone cream aisle. Vanilla and unscented balm variants stay as their own listings. Soap and lip balm stay. Empty merch stays out.",
    location: "Europe",
    founded: 2022,
    categories: ["sunscreen","deodorant","skincare"],
    accent: "#5C4033",
    rating: 4.7,
    reviewCount: 120,
    followerCount: 2100,
    websiteUrl: "https://puretallow.eu",
    logoUrl: "/brands/pure-tallow-eu.svg",
  },
  {
    id: "c974",
    slug: "nala-care",
    name: "Nala Care",
    tagline: "Vancouver small-batch deodorant — aluminum-free, phthalate-free, scent variants kept honest",
    story: "A Vancouver house that pours aluminum-free deodorant in sensitive and extra-strength formulas instead of a drugstore antiperspirant. Scent variants stay as their own listings. Pregnancy and postpartum formulas stay. Hats, tester-only kits, and merch stay out.",
    location: "Vancouver, Canada",
    founded: 2018,
    categories: ["deodorant"],
    accent: "#3D4A3D",
    rating: 4.8,
    reviewCount: 2100,
    followerCount: 18000,
    websiteUrl: "https://nalacare.com",
    logoUrl: "/brands/nala-care.svg",
  },
  {
    id: "c975",
    slug: "black-chicken",
    name: "Black Chicken Remedies",
    tagline: "Axilla paste — Australia's plastic-tin deodorant, no aluminum, no synthetic fragrance dump",
    story: "An Australian kitchen that still sells deodorant as a hand-applied paste in a recyclable tin instead of a plastic stick. Original, barrier-booster, and spray scent variants stay as their own listings. Skin-rescue mist stays. Six-pack wholesale cartons stay in the warehouse.",
    location: "Australia",
    founded: 2012,
    categories: ["deodorant","skincare"],
    accent: "#2C5F4E",
    rating: 4.8,
    reviewCount: 860,
    followerCount: 14000,
    websiteUrl: "https://blackchicken.com.au",
    logoUrl: "/brands/black-chicken.svg",
  },
  {
    id: "c976",
    slug: "pure-press-oils",
    name: "Pure Press Oils",
    tagline: "Vancouver Island seed proteins — single-ingredient, cold-pressed, no gum-thickened shake",
    story: "A Vancouver Island press that mills pumpkin, sunflower, hemp, and almond protein from the cake left after cold-pressing oil — one ingredient, no sweetener aisle. Protein powders stay. Finishing-oil gift sets and pantry bottles stay in the mill.",
    location: "Vancouver Island, Canada",
    founded: 2019,
    categories: ["protein"],
    accent: "#B86B3A",
    rating: 4.7,
    reviewCount: 90,
    followerCount: 1600,
    websiteUrl: "https://purepressoils.com",
    logoUrl: "/brands/pure-press-oils.svg",
  },
  {
    id: "c977",
    slug: "rockin-wellness",
    name: "Rockin Wellness",
    tagline: "Small-batch vegan protein and greens — organic seeds, no gluten, no dairy filler",
    story: "A US woman-owned kitchen that has blended organic cacao, hemp, flax, and plant protein since 2011 instead of a chalky gum shake. Vanilla protein, mocha cacao, and greens stay. Ice-cream machines and appliance merch stay out.",
    location: "United States",
    founded: 2011,
    categories: ["protein","supplements"],
    accent: "#6B3E26",
    rating: 4.6,
    reviewCount: 340,
    followerCount: 5200,
    websiteUrl: "https://rockinwellness.com",
    logoUrl: "/brands/rockin-wellness.png",
  },
  {
    id: "c978",
    slug: "pirouette-beauty",
    name: "Pirouette Beauty",
    tagline: "Two-SKU botanical hair — organic aloe shampoo and conditioner, no sulfate strip",
    story: "A tiny hair house that only needed two formulas: a sulfate-free aloe shampoo and a matching conditioner, slow-batched instead of a 40-SKU salon wall. Shampoo and conditioner stay. Sets stay when they are the same formulas. Tools stay out.",
    location: "United States",
    founded: 2022,
    categories: ["hair"],
    accent: "#7A9E7E",
    rating: 4.7,
    reviewCount: 60,
    followerCount: 900,
    websiteUrl: "https://www.pirouettebeauty.com",
    logoUrl: "/brands/pirouette-beauty.svg",
  },
  {
    id: "c979",
    slug: "sage-tallow",
    name: "Sage Tallow",
    tagline: "Tallow hair mask and scalp serum — farm fat for length, no silicone coat",
    story: "A small hair kitchen that writes a deep-conditioning mask and a scalp serum from tallow instead of a dimethicone bottle. The mask, serum, and restoration duo stay. Empty merch stays out.",
    location: "United States",
    founded: 2023,
    categories: ["hair"],
    accent: "#5B7A3A",
    rating: 4.6,
    reviewCount: 50,
    followerCount: 800,
    websiteUrl: "https://sagetallow.com",
    logoUrl: "/brands/sage-tallow.svg",
  },
  {
    id: "c980",
    slug: "mushrooms-for-life",
    name: "Mushrooms for Life",
    tagline: "Organic lion's mane, cordyceps, and reishi extracts — fruiting body, no grain mycelium filler",
    story: "A mushroom house that extracts lion's mane, cordyceps, and reishi from organic fruiting bodies instead of mycelium-on-oat powder. Single extracts and focus blends stay. Coffee-lover merch stacks stay when they are still mushroom formulas. Apparel stays out.",
    location: "United Kingdom",
    founded: 2016,
    categories: ["supplements"],
    accent: "#6B4F3A",
    rating: 4.8,
    reviewCount: 420,
    followerCount: 8900,
    websiteUrl: "https://mushroomsforlife.com",
    logoUrl: "/brands/mushrooms-for-life.svg",
  },
  {
    id: "c981",
    slug: "happy-dragonfly",
    name: "Happy Dragonfly Homestead",
    tagline: "Florida homestead lion's mane — USDA organic, alcohol-free, grown and bottled on the farm",
    story: "A Florida homestead that grows lion's mane, then bottles an alcohol-free USDA organic extract on the same farm instead of an imported capsule. The lion's mane tincture stays. Fresh culinary mushrooms, turkey deposits, and laying hens stay in the barn.",
    location: "Florida, United States",
    founded: 2020,
    categories: ["supplements"],
    accent: "#3D6B5A",
    rating: 4.8,
    reviewCount: 80,
    followerCount: 1400,
    websiteUrl: "https://happydragonflyhomestead.com",
    logoUrl: "/brands/happy-dragonfly.svg",
  },
  {
    id: "c982",
    slug: "pasture-and-petal",
    name: "Pasture and Petal",
    tagline: "Farm-to-face bars and lip butters — short botanical lists, no 40-ingredient cream",
    story: "A small farm kitchen that cuts clarifying facial bars and seasonal lip butters from pasture fats and petals instead of a silicone moisturizer. Lip-butter scent variants stay as their own listings. Serum, mask, and eye cream stay. Merch stays out.",
    location: "United States",
    founded: 2022,
    categories: ["skincare"],
    accent: "#C45C26",
    rating: 4.7,
    reviewCount: 90,
    followerCount: 1500,
    websiteUrl: "https://pastureandpetal.com",
    logoUrl: "/brands/pasture-and-petal.svg",
  },
  {
    id: "c983",
    slug: "nz-tallow",
    name: "NZ Tallow",
    tagline: "Aotearoa tallow balms — chamomile, lavender, rose vanilla, no filler jar",
    story: "A New Zealand render house that pours grass-fed tallow balms in chamomile, lavender, rose vanilla, and original instead of a drugstore cream. Scent variants stay as their own listings. Lip balm stays. Wholesale cartons stay out.",
    location: "New Zealand",
    founded: 2023,
    categories: ["skincare"],
    accent: "#1B4F72",
    rating: 4.7,
    reviewCount: 60,
    followerCount: 900,
    websiteUrl: "https://nztallow.co.nz",
    logoUrl: "/brands/nz-tallow.svg",
  },
  {
    id: "c984",
    slug: "sun-tallow",
    name: "Sun Tallow",
    tagline: "Day-and-night tallow balms — classic sun balm, moon night balm, no perfume-oil cream",
    story: "A two-jar house that keeps daytime sun tallow and a night moon balm to a short farm list instead of a 40-ingredient cream. Both balms stay. The pair bundle stays when it is the same formulas. Merch stays out.",
    location: "United States",
    founded: 2023,
    categories: ["skincare"],
    accent: "#C4A35A",
    rating: 4.6,
    reviewCount: 40,
    followerCount: 700,
    websiteUrl: "https://suntallow.com",
    logoUrl: "/brands/sun-tallow.svg",
  },
];
