import type { Brand } from "./types";

/** Wave 94: small organic / toxic-free brands across marketplace categories (c1433+). */
export const catalogBrandsWave94: Brand[] = [
  {
    id: "c1433",
    slug: "elims",
    name: "ELIMS",
    tagline: "10% nano-hydroxyapatite toothpaste in lavender vanilla and pineapple orange mint",
    story:
      "The leftover unused multi-SKU 10% n-HA oral house after wave4–93 — keep the 4 oz Lavender Vanilla Mint and Pineapple Orange Mint singles plus one bamboo toothbrush. Pack count, travel 1 oz, 2/3/5-packs, Home & Away, sample 50-packs, whitening masks, electric heads, and ritual sets stay boxed. Cart.js is USD. Pages are key-ingredient marketing (leave empty).",
    location: "United States",
    founded: 2019,
    categories: ["oral"],
    accent: "#6B4C7A",
    rating: 4.6,
    reviewCount: 740,
    followerCount: 12000,
    websiteUrl: "https://elims.co",
    logoUrl: "/brands/elims.svg",
  },
  {
    id: "c1434",
    slug: "clean-kind",
    name: "Clean + Kind",
    tagline: "Grass-fed tallow mineral SPF — reef-safe zinc, unscented or vanilla",
    story:
      "The unused tallow mineral-sun house after wave4–93 — SPF 25, SPF 50 (Scent expands Unscented / Vanilla), kids SPF 40, daily SPF 40 (Tint expands Untinted / Tinted), plus tallow lotion, whipped balm, baby balm, and two face serums. Cart.js is USD. Pages are benefit essays (leave empty).",
    location: "United States",
    founded: 2023,
    categories: ["sunscreen", "skincare"],
    accent: "#C4A35A",
    rating: 4.7,
    reviewCount: 210,
    followerCount: 3400,
    websiteUrl: "https://shopcleankind.com",
    logoUrl: "/brands/clean-kind.svg",
  },
  {
    id: "c1435",
    slug: "suprey",
    name: "Suprey Life",
    tagline: "Zero-sugar HYDUST electrolytes — stevia, no sucralose",
    story:
      "The unused European hydration leftover after wave4–93 — HYDUST Flavour expands Lemon / Orange / Green Apple / Peach / Strawberry (Mix is a variety pack and stays boxed). SWEETPEACE recovery drinks stay boxed. Cart.js is EUR × 1.08 (€24.95 → $26.95). Stevia, no sucralose. The page is a mineral-ratio essay (leave empty).",
    location: "Europe",
    founded: 2024,
    categories: ["electrolytes"],
    accent: "#1F6B6B",
    rating: 4.5,
    reviewCount: 64,
    followerCount: 1100,
    websiteUrl: "https://shop.suprey.life",
    logoUrl: "/brands/suprey.svg",
  },
  {
    id: "c1436",
    slug: "muscle-feast",
    name: "Muscle Feast",
    tagline: "Pasture-raised grass-fed whey isolate, concentrate, and casein — sunflower lecithin, no sucralose",
    story:
      "The unused pasture-raised protein leftover after wave4–93 — Flavor expands hydrolyzed whey, isolate, 100% whey, concentrate, and casein. 2 lb is size (5 lb drops). Creatine stays supplements. Bottles, tees, oat powder, and cyclic dextrin stay boxed. Cart.js is USD. Pages are farm-sourcing essays (leave empty).",
    location: "United States",
    founded: 2011,
    categories: ["protein", "supplements"],
    accent: "#2F4A3C",
    rating: 4.7,
    reviewCount: 1800,
    followerCount: 22000,
    websiteUrl: "https://musclefeast.com",
    logoUrl: "/brands/muscle-feast.png",
  },
  {
    id: "c1437",
    slug: "willow-valley",
    name: "Willow Valley Wellness",
    tagline: "Ontario aluminum-free deodorant paste, botanical shampoo bars, and cold-process soaps",
    story:
      "The unused Ontario studio leftover after wave4–93 — Perfectly Neutral deodorant paste (4 oz; 1/2 oz is size), three botanical shampoo bars, and named soaps. Gift sets, roll-ons, ritual mists, bug spray, and soap savers stay boxed. Cart.js is CAD × 0.73 (C$26.99 → $19.70). Pages publish full INCI.",
    location: "Ontario, Canada",
    founded: 2021,
    categories: ["deodorant", "hair", "skincare"],
    accent: "#5C6B3A",
    rating: 4.8,
    reviewCount: 190,
    followerCount: 2800,
    websiteUrl: "https://willowvalleywellness.com",
    logoUrl: "/brands/willow-valley.svg",
  },
  {
    id: "c1438",
    slug: "malama-mushrooms",
    name: "Mālama Mushrooms",
    tagline: "Hawai‘i-grown dual-extract tinctures and fruiting-body mushroom powders",
    story:
      "The unused Hawai‘i mushroom leftover after wave4–93 — keep dual-extract tinctures (30 ml) and 3.5 oz fruiting-body powders plus the 8-mushroom mix. 16 oz / 60 ml is size. Coffee, cacao, matcha, grow kits, merch, books, pets, and bundles stay boxed. Cart.js is USD. Hardcode the published one-ingredient powder lists — tincture pages are farm-story marketing (leave empty).",
    location: "Hawai‘i",
    founded: 2018,
    categories: ["supplements"],
    accent: "#3D5A2C",
    rating: 4.7,
    reviewCount: 420,
    followerCount: 8900,
    websiteUrl: "https://www.malamamushrooms.com",
    logoUrl: "/brands/malama-mushrooms.svg",
  }
];
