import type { Brand } from "./types";

/** Second wave of curated small / indie brands. */
export const catalogBrandsBatch2: Brand[] = [
  {
    id: "c101",
    slug: "about-face",
    name: "About-Face",
    tagline: "Halsey’s experimental color",
    story: "Playful, experimental makeup from Halsey — color that doesn’t take itself too seriously.",
    location: "United States",
    founded: 2021,
    categories: ["skincare"],
    accent: "#E74C3C",
    rating: 4.4,
    reviewCount: 4839,
    followerCount: 61287,
    websiteUrl: "https://www.aboutface.com",
    logoUrl: "/brands/about-face.png",
  },
  {
    id: "c102",
    slug: "amika",
    name: "amika",
    tagline: "Born in Brooklyn hair energy",
    story: "Playful, performance hair care from Brooklyn — sea buckthorn formulas with serious range.",
    location: "Brooklyn, NY",
    founded: 2008,
    categories: ["hair"],
    accent: "#FF6B9D",
    rating: 4.5,
    reviewCount: 21601,
    followerCount: 8413,
    websiteUrl: "https://www.loveamika.com",
    logoUrl: "/brands/amika.png",
  },
  {
    id: "c103",
    slug: "annmarie",
    name: "Annmarie Skin Care",
    tagline: "Wildcrafted organic skincare",
    story: "Small-batch organic formulas with wildcrafted botanicals — pure, potent, and intentionally made.",
    location: "California",
    founded: 2008,
    categories: ["skincare"],
    accent: "#A67C52",
    rating: 4.6,
    reviewCount: 9131,
    followerCount: 42865,
    websiteUrl: "https://shop.annmariegianni.com",
    logoUrl: "/brands/annmarie.png",
  },
  {
    id: "c104",
    slug: "athena-club",
    name: "Athena Club",
    tagline: "Shave kit with a kit bag",
    story: "Women’s shave kits that feel designed — blades, cream, and a kit that isn’t an afterthought.",
    location: "United States",
    founded: 2017,
    categories: ["skincare"],
    accent: "#5DADE2",
    rating: 4.7,
    reviewCount: 10543,
    followerCount: 103691,
    websiteUrl: "https://athenaclub.com",
    logoUrl: "/brands/athena-club.svg",
  },
  {
    id: "c105",
    slug: "axis-y",
    name: "AXIS-Y",
    tagline: "Vegan K-beauty for uneven tone",
    story: "Vegan Korean skincare for dullness and uneven tone — dark spot care with a soft finish.",
    location: "South Korea",
    founded: 2018,
    categories: ["skincare"],
    accent: "#6B5B95",
    rating: 4.8,
    reviewCount: 6964,
    followerCount: 71573,
    websiteUrl: "https://axis-y.com",
    logoUrl: "/brands/axis-y.png",
  },
  {
    id: "c106",
    slug: "bag-balm",
    name: "Bag Balm",
    tagline: "Vermont farmstead ointment",
    story: "The green tin classic — farm-born ointment for cracked skin that’s been in cabinets for generations.",
    location: "Vermont",
    founded: 1899,
    categories: ["skincare"],
    accent: "#228B22",
    rating: 4.9,
    reviewCount: 24174,
    followerCount: 10274,
    websiteUrl: "https://www.bagbalm.com",
    logoUrl: "/brands/bag-balm.png",
  },
  {
    id: "c107",
    slug: "beam",
    name: "BEAM",
    tagline: "Wellness powders that taste good",
    story: "Functional mushroom and wellness blends for calm, focus, and recovery.",
    location: "United States",
    founded: 2018,
    categories: ["supplements"],
    accent: "#F39C12",
    rating: 4.4,
    reviewCount: 11809,
    followerCount: 30358,
    websiteUrl: "https://beamorganics.com",
    logoUrl: "/brands/beam.png",
  },
  {
    id: "c108",
    slug: "beardo",
    name: "Beardo",
    tagline: "Beard and men’s grooming",
    story: "Beard oils and men’s grooming from India — bold scents and grooming kits.",
    location: "India",
    founded: 2015,
    categories: ["hair","skincare"],
    accent: "#1A1A1A",
    rating: 4.5,
    reviewCount: 12464,
    followerCount: 20330,
    websiteUrl: "https://beardo.in",
    logoUrl: "/brands/beardo.png",
  },
  {
    id: "c109",
    slug: "beauty-of-joseon",
    name: "Beauty of Joseon",
    tagline: "Hanbang meets modern skin science",
    story: "Korean heritage botanicals in modern textures — ginseng, rice, and SPF with a cult following.",
    location: "South Korea",
    founded: 2017,
    categories: ["skincare","sunscreen"],
    accent: "#E8D5B7",
    rating: 4.6,
    reviewCount: 7710,
    followerCount: 74213,
    websiteUrl: "https://beautyofjoseon.com",
    logoUrl: "/brands/beauty-of-joseon.png",
  },
  {
    id: "c110",
    slug: "billie",
    name: "Billie",
    tagline: "Razors without the pink tax",
    story: "Women’s shave care that refused the pink tax — clean design, fair prices, sharp blades.",
    location: "New York, NY",
    founded: 2017,
    categories: ["skincare"],
    accent: "#F5B7B1",
    rating: 4.7,
    reviewCount: 26823,
    followerCount: 57254,
    websiteUrl: "https://shop.mybillie.com",
    logoUrl: "/brands/billie.png",
  },
  {
    id: "c111",
    slug: "blind-barber",
    name: "Blind Barber",
    tagline: "Barbershop grooming co.",
    story: "NYC barbershop-born grooming — hair, shave, and scent with speakeasy cool.",
    location: "New York, NY",
    founded: 2009,
    categories: ["skincare","hair"],
    accent: "#2C3E50",
    rating: 4.8,
    reviewCount: 18948,
    followerCount: 76463,
    websiteUrl: "https://blindbarber.com",
    logoUrl: "/brands/blind-barber.png",
  },
  {
    id: "c112",
    slug: "blueland",
    name: "Blueland",
    tagline: "Cleaners without plastic bottles",
    story: "Tablet cleaners and hand soap tablets — same clean, endlessly less plastic.",
    location: "New York, NY",
    founded: 2019,
    categories: ["skincare"],
    accent: "#3498DB",
    rating: 4.9,
    reviewCount: 22000,
    followerCount: 88756,
    websiteUrl: "https://blueland.com",
    logoUrl: "/brands/blueland.png",
  },
  {
    id: "c113",
    slug: "bondi-boost",
    name: "BondiBoost",
    tagline: "Australian hair growth care",
    story: "Aussie hair care aimed at thinning and growth goals — clean-leaning with beachy energy.",
    location: "Australia",
    founded: 2015,
    categories: ["hair"],
    accent: "#00A8E8",
    rating: 4.4,
    reviewCount: 14588,
    followerCount: 129305,
    websiteUrl: "https://bondiboost.com",
    logoUrl: "/brands/bondi-boost.png",
  },
  {
    id: "c114",
    slug: "boy-smells",
    name: "Boy Smells",
    tagline: "Genderful fragrance candles",
    story: "Genderful candles and perfume — coconut wax, queer joy, and unexpected scent pairings.",
    location: "Los Angeles, CA",
    founded: 2016,
    categories: ["skincare"],
    accent: "#F5CBA7",
    rating: 4.5,
    reviewCount: 22313,
    followerCount: 43644,
    websiteUrl: "https://boysmells.com",
    logoUrl: "/brands/boy-smells.png",
  },
  {
    id: "c115",
    slug: "branch-basics",
    name: "Branch Basics",
    tagline: "Human-safe Concentrate",
    story: "One human-safe concentrate for home and body — toss the toxic cabinet alphabet.",
    location: "United States",
    founded: 2012,
    categories: ["skincare"],
    accent: "#F5CBA7",
    rating: 4.6,
    reviewCount: 25862,
    followerCount: 124520,
    websiteUrl: "https://branchbasics.com",
    logoUrl: "/brands/branch-basics.png",
  },
  {
    id: "c116",
    slug: "brush-on-block",
    name: "Brush On Block",
    tagline: "Powder sunscreen on the go",
    story: "Mineral powder SPF in a brush — touch-up protection that lives in your bag.",
    location: "United States",
    founded: 2013,
    categories: ["sunscreen"],
    accent: "#F5DEB3",
    rating: 4.7,
    reviewCount: 8514,
    followerCount: 25203,
    websiteUrl: "https://brushonblock.com",
    logoUrl: "/brands/brush-on-block.png",
  },
  {
    id: "c117",
    slug: "burst",
    name: "BURST",
    tagline: "Hygienist-founded electric care",
    story: "Sonic brushes and oral care built with dental hygienists — performance cleaning.",
    location: "United States",
    founded: 2017,
    categories: ["oral"],
    accent: "#9B59B6",
    rating: 4.8,
    reviewCount: 24496,
    followerCount: 150614,
    websiteUrl: "https://www.burstoralcare.com",
    logoUrl: "/brands/burst.png",
  },
  {
    id: "c118",
    slug: "camille-rose",
    name: "Camille Rose",
    tagline: "Natural curls, rich botanicals",
    story: "Curl care with honey, cocoa, and botanicals — moisture-forward formulas for textured hair.",
    location: "Atlanta, GA",
    founded: 2008,
    categories: ["hair"],
    accent: "#A0522D",
    rating: 4.9,
    reviewCount: 20961,
    followerCount: 176383,
    websiteUrl: "https://camillerose.com",
    logoUrl: "/brands/camille-rose.png",
  },
  {
    id: "c119",
    slug: "cosrx",
    name: "COSRX",
    tagline: "Simple, effective K-beauty",
    story: "Short formulas, big results — snail mucin, actives, and barrier care that became a staple.",
    location: "South Korea",
    founded: 2013,
    categories: ["skincare"],
    accent: "#2C2C2C",
    rating: 4.4,
    reviewCount: 16416,
    followerCount: 101559,
    websiteUrl: "https://www.cosrx.com",
    logoUrl: "/brands/cosrx.png",
  },
  {
    id: "c120",
    slug: "crown-affair",
    name: "Crown Affair",
    tagline: "Hair care as daily ritual",
    story: "Elevated brushes, mists, and oils for hair that wants a ritual — not just another shampoo.",
    location: "New York, NY",
    founded: 2019,
    categories: ["hair"],
    accent: "#F5F0E6",
    rating: 4.5,
    reviewCount: 23369,
    followerCount: 119468,
    websiteUrl: "https://www.crownaffair.com",
    logoUrl: "/brands/crown-affair.png",
  },
  {
    id: "c121",
    slug: "cymbiotika",
    name: "Cymbiotika",
    tagline: "Bioavailable clean supplements",
    story: "Liposomal and clean-label supplements for people who care how nutrients absorb.",
    location: "San Diego, CA",
    founded: 2018,
    categories: ["supplements"],
    accent: "#1ABC9C",
    rating: 4.6,
    reviewCount: 15412,
    followerCount: 100697,
    websiteUrl: "https://cymbiotika.com",
    logoUrl: "/brands/cymbiotika.png",
  },
  {
    id: "c122",
    slug: "danessa-myricks",
    name: "Danessa Myricks Beauty",
    tagline: "Artist-built color craft",
    story: "Pro artist color with grounding and blurring cult products — makeup as craft.",
    location: "United States",
    founded: 2017,
    categories: ["skincare"],
    accent: "#6C3483",
    rating: 4.7,
    reviewCount: 11742,
    followerCount: 90769,
    websiteUrl: "https://danessamyricksbeauty.com",
    logoUrl: "/brands/danessa-myricks.png",
  },
  {
    id: "c123",
    slug: "davids",
    name: "Davids",
    tagline: "Premium natural toothpaste",
    story: "Metal-tube natural toothpaste with a design-forward bathroom presence.",
    location: "Los Angeles, CA",
    founded: 2015,
    categories: ["oral"],
    accent: "#2C3E50",
    rating: 4.8,
    reviewCount: 13242,
    followerCount: 78263,
    websiteUrl: "https://davids-usa.com",
    logoUrl: "/brands/davids.png",
  },
  {
    id: "c124",
    slug: "dedcool",
    name: "DedCool",
    tagline: "Genderless cult fragrance",
    story: "LA fragrance for everyone — milky, clean, and weird-in-a-good-way scents with body care.",
    location: "Los Angeles, CA",
    founded: 2015,
    categories: ["skincare"],
    accent: "#E8E8E8",
    rating: 4.9,
    reviewCount: 9732,
    followerCount: 67836,
    websiteUrl: "https://dedcool.com",
    logoUrl: "/brands/dedcool.png",
  },
  {
    id: "c125",
    slug: "eadem",
    name: "Eadem",
    tagline: "Melanin-aware clean skincare",
    story: "Skincare designed with melanin-rich skin in mind — brightening and barrier care without one-shade myths.",
    location: "New York, NY",
    founded: 2020,
    categories: ["skincare"],
    accent: "#B8956C",
    rating: 4.4,
    reviewCount: 14256,
    followerCount: 154156,
    websiteUrl: "https://eadem.co",
    logoUrl: "/brands/eadem.png",
  },
  {
    id: "c126",
    slug: "ellis-brooklyn",
    name: "Ellis Brooklyn",
    tagline: "Clean fine fragrance",
    story: "Clean fragrance with literary names and serious scent architecture.",
    location: "New York, NY",
    founded: 2016,
    categories: ["skincare"],
    accent: "#4A3728",
    rating: 4.5,
    reviewCount: 7694,
    followerCount: 80640,
    websiteUrl: "https://ellisbrooklyn.com",
    logoUrl: "/brands/ellis-brooklyn.png",
  },
  {
    id: "c127",
    slug: "evan-healy",
    name: "evan healy",
    tagline: "Holistic plant skincare",
    story: "Holistic facial care built around plant hydrosols and oils that respect skin’s own intelligence.",
    location: "United States",
    founded: 1999,
    categories: ["skincare"],
    accent: "#9CAF88",
    rating: 4.6,
    reviewCount: 6304,
    followerCount: 131171,
    websiteUrl: "https://evanhealy.com",
    logoUrl: "/brands/evan-healy.png",
  },
  {
    id: "c128",
    slug: "every-man-jack",
    name: "Every Man Jack",
    tagline: "Simple men’s grooming",
    story: "Approachable men’s body, hair, and face care — straightforward formulas without the fuss.",
    location: "California",
    founded: 2008,
    categories: ["skincare","hair","deodorant"],
    accent: "#2980B9",
    rating: 4.7,
    reviewCount: 15823,
    followerCount: 116833,
    websiteUrl: "https://www.everymanjack.com",
    logoUrl: "/brands/every-man-jack.png",
  },
  {
    id: "c129",
    slug: "fable-mane",
    name: "Fable & Mane",
    tagline: "Ayurvedic hair rituals",
    story: "Modern Ayurvedic hair care with hollis oil and scalp rituals — growth-minded and scent-obsessed.",
    location: "London / US",
    founded: 2019,
    categories: ["hair"],
    accent: "#8B4513",
    rating: 4.8,
    reviewCount: 9276,
    followerCount: 121996,
    websiteUrl: "https://www.fableandmane.com",
    logoUrl: "/brands/fable-mane.png",
  },
  {
    id: "c130",
    slug: "farmaesthetics",
    name: "Farmaesthetics",
    tagline: "Heirloom farm botanicals",
    story: "Rhode Island farm botanicals in small-batch skin rituals — heirloom herbs for modern skin.",
    location: "Rhode Island",
    founded: 1999,
    categories: ["skincare"],
    accent: "#9A7B4F",
    rating: 4.9,
    reviewCount: 10341,
    followerCount: 108675,
    websiteUrl: "https://farmaesthetics.com",
    logoUrl: "/brands/farmaesthetics.png",
  },
  {
    id: "c131",
    slug: "fatco",
    name: "FATCO",
    tagline: "Ancestral fat-based body care",
    story: "Tallow-based balms and deodorant for skin that likes ancestral ingredients over petroleum.",
    location: "United States",
    founded: 2013,
    categories: ["deodorant","skincare"],
    accent: "#8B7355",
    rating: 4.4,
    reviewCount: 12387,
    followerCount: 85740,
    websiteUrl: "https://www.fatco.com",
    logoUrl: "/brands/fatco.png",
  },
  {
    id: "c132",
    slug: "first-aid-beauty",
    name: "First Aid Beauty",
    tagline: "Skin first aid that actually soothes",
    story: "Ultra Repair and friends — sensitive-skin staples that calm dryness and irritation fast.",
    location: "Boston, MA",
    founded: 2009,
    categories: ["skincare"],
    accent: "#E74C3C",
    rating: 4.5,
    reviewCount: 1252,
    followerCount: 32260,
    websiteUrl: "https://firstaidbeauty.com",
    logoUrl: "/brands/first-aid-beauty.png",
  },
  {
    id: "c133",
    slug: "flamingo",
    name: "Flamingo",
    tagline: "Harry’s for her shave line",
    story: "Thoughtful women’s shave care from the Harry’s team — soft design, serious blades.",
    location: "United States",
    founded: 2018,
    categories: ["skincare"],
    accent: "#FF8FA3",
    rating: 4.6,
    reviewCount: 21734,
    followerCount: 98424,
    websiteUrl: "https://shopflamingo.com",
    logoUrl: "/brands/flamingo.png",
  },
  {
    id: "c134",
    slug: "gisou",
    name: "Gisou",
    tagline: "Honey-infused hair care",
    story: "Mirsalehi honey hair care from a beekeeping family — shine, scent, and soft hair.",
    location: "Amsterdam",
    founded: 2015,
    categories: ["hair"],
    accent: "#F4C430",
    rating: 4.7,
    reviewCount: 18353,
    followerCount: 112841,
    websiteUrl: "https://www.gisou.com",
    logoUrl: "/brands/gisou.png",
  },
  {
    id: "c135",
    slug: "grown-alchemist",
    name: "Grown Alchemist",
    tagline: "Botanical laboratory beauty",
    story: "Melbourne botanical formulations with a lab-apothecary aesthetic — skin and hair with plant precision.",
    location: "Melbourne, Australia",
    founded: 2009,
    categories: ["skincare","hair"],
    accent: "#5D6D7E",
    rating: 4.8,
    reviewCount: 7651,
    followerCount: 135138,
    websiteUrl: "https://grownalchemist.com",
    logoUrl: "/brands/grown-alchemist.png",
  },
  {
    id: "c136",
    slug: "haeckels",
    name: "Haeckels",
    tagline: "Coastal foraging skincare",
    story: "Margate seaweed and coastal botanicals — experimental British skincare with shoreline soul.",
    location: "Margate, UK",
    founded: 2012,
    categories: ["skincare"],
    accent: "#1ABC9C",
    rating: 4.9,
    reviewCount: 9924,
    followerCount: 166581,
    websiteUrl: "https://haeckels.co.uk",
    logoUrl: "/brands/haeckels.png",
  },
  {
    id: "c137",
    slug: "hanz-de-fuko",
    name: "Hanz de Fuko",
    tagline: "Anti-everything hair care",
    story: "Gravity-defying men’s hair products with a rebellious streak — texture, hold, and clean formulas.",
    location: "Los Angeles, CA",
    founded: 2010,
    categories: ["hair"],
    accent: "#1A1A1A",
    rating: 4.4,
    reviewCount: 21989,
    followerCount: 148940,
    websiteUrl: "https://hanzdefuko.com",
    logoUrl: "/brands/hanz-de-fuko.png",
  },
  {
    id: "c138",
    slug: "haruharu",
    name: "Haruharu Wonder",
    tagline: "Black rice wonder skincare",
    story: "Black rice and gentle ferment formulas from Korea — soothing and fragrance-mindful.",
    location: "South Korea",
    founded: 2016,
    categories: ["skincare"],
    accent: "#4A3728",
    rating: 4.5,
    reviewCount: 20078,
    followerCount: 20883,
    websiteUrl: "https://haruharuwonder.com",
    logoUrl: "/brands/haruharu.png",
  },
  {
    id: "c139",
    slug: "hero-cosmetics",
    name: "Hero Cosmetics",
    tagline: "Mighty patches for breakouts",
    story: "The Mighty Patch people — hydrocolloid heroes and gentle skin helpers for breakout days.",
    location: "United States",
    founded: 2017,
    categories: ["skincare"],
    accent: "#FF6B6B",
    rating: 4.6,
    reviewCount: 19013,
    followerCount: 163999,
    websiteUrl: "https://herocosmetics.us",
    logoUrl: "/brands/hero-cosmetics.png",
  },
  {
    id: "c140",
    slug: "homesick",
    name: "Homesick",
    tagline: "Place-scented candles",
    story: "Candles that smell like places you miss — cities, seasons, and memory in wax.",
    location: "United States",
    founded: 2016,
    categories: ["skincare"],
    accent: "#85C1E9",
    rating: 4.7,
    reviewCount: 9959,
    followerCount: 26675,
    websiteUrl: "https://homesick.com",
    logoUrl: "/brands/homesick.png",
  },
  {
    id: "c141",
    slug: "indie-lee",
    name: "Indie Lee",
    tagline: "Clean clinical skincare that works",
    story: "Founded after a health wake-up call — results-driven clean formulas with transparent ingredients.",
    location: "New York",
    founded: 2010,
    categories: ["skincare"],
    accent: "#C4B7A6",
    rating: 4.8,
    reviewCount: 23321,
    followerCount: 119216,
    websiteUrl: "https://indielee.com",
    logoUrl: "/brands/indie-lee.png",
  },
  {
    id: "c142",
    slug: "inkey-list",
    name: "The Inkey List",
    tagline: "Key ingredients, clear prices",
    story: "Demystified actives with honest pricing — know what you’re putting on and why it costs that.",
    location: "United Kingdom",
    founded: 2018,
    categories: ["skincare"],
    accent: "#1A1A1A",
    rating: 4.9,
    reviewCount: 21229,
    followerCount: 94646,
    websiteUrl: "https://www.theinkeylist.com",
    logoUrl: "/brands/inkey-list.png",
  },
  {
    id: "c143",
    slug: "innersense",
    name: "Innersense Organic Beauty",
    tagline: "Organic salon hair care",
    story: "Certified organic hair care used in salons — essential oils, clean formulas, pro results.",
    location: "California",
    founded: 2007,
    categories: ["hair"],
    accent: "#C4A484",
    rating: 4.4,
    reviewCount: 20052,
    followerCount: 131622,
    websiteUrl: "https://www.innersensebeauty.com",
    logoUrl: "/brands/innersense.png",
  },
  {
    id: "c144",
    slug: "jones-road",
    name: "Jones Road",
    tagline: "No-makeup makeup essentials",
    story: "Bobbi Brown’s clean-leaning color line — Miracle Balm energy for effortless skin-first makeup.",
    location: "New York, NY",
    founded: 2020,
    categories: ["skincare"],
    accent: "#C4A484",
    rating: 4.5,
    reviewCount: 24925,
    followerCount: 27152,
    websiteUrl: "https://jonesroadbeauty.com",
    logoUrl: "/brands/jones-road.png",
  },
  {
    id: "c145",
    slug: "josh-rosebrook",
    name: "Josh Rosebrook",
    tagline: "Vital nutrient herbal skincare",
    story: "Herbalist-made nutrient skincare from the California coast — botanicals and hydration without synthetic overload.",
    location: "California",
    founded: 2013,
    categories: ["skincare"],
    accent: "#8B6B4A",
    rating: 4.6,
    reviewCount: 17118,
    followerCount: 90290,
    websiteUrl: "https://joshrosebrook.com",
    logoUrl: "/brands/josh-rosebrook.png",
  },
  {
    id: "c146",
    slug: "juice-beauty",
    name: "Juice Beauty",
    tagline: "Organic boutique skincare",
    story: "Sonoma-made organic skincare rooted in antioxidant fruit juices and certified organic botanicals.",
    location: "Sonoma, CA",
    founded: 2005,
    categories: ["skincare"],
    accent: "#C45C26",
    rating: 4.7,
    reviewCount: 3965,
    followerCount: 178359,
    websiteUrl: "https://juicebeauty.com",
    logoUrl: "/brands/juice-beauty.png",
  },
  {
    id: "c147",
    slug: "k18",
    name: "K18",
    tagline: "Molecular repair hair mask",
    story: "Peptide-powered hair repair that changed the bleach-damage conversation.",
    location: "United States",
    founded: 2021,
    categories: ["hair"],
    accent: "#1A1A1A",
    rating: 4.8,
    reviewCount: 10369,
    followerCount: 27408,
    websiteUrl: "https://www.k18hair.com",
    logoUrl: "/brands/k18.png",
  },
  {
    id: "c148",
    slug: "kahina",
    name: "Kahina Giving Beauty",
    tagline: "Argan oil with impact",
    story: "Moroccan argan and giving-back beauty — luxurious oils tied to women’s cooperatives.",
    location: "New York / Morocco",
    founded: 2008,
    categories: ["skincare"],
    accent: "#C4A484",
    rating: 4.9,
    reviewCount: 3793,
    followerCount: 38037,
    websiteUrl: "https://kahina-givingbeauty.com",
    logoUrl: "/brands/kahina.png",
  },
  {
    id: "c149",
    slug: "kaia-naturals",
    name: "Kaia Naturals",
    tagline: "The take-it-all-off detox set",
    story: "Toronto natural deodorant famous for the charcoal detox reset — clean underarms without aluminum.",
    location: "Toronto, Canada",
    founded: 2012,
    categories: ["deodorant"],
    accent: "#4A4A4A",
    rating: 4.4,
    reviewCount: 4163,
    followerCount: 131412,
    websiteUrl: "https://kaianaturals.com",
    logoUrl: "/brands/kaia-naturals.png",
  },
  {
    id: "c150",
    slug: "kinship",
    name: "Kinship",
    tagline: "Probiotic skincare for sensitive skin",
    story: "Brooklyn-born probiotic formulas that calm sensitive, reactive skin without the harsh actives parade.",
    location: "Brooklyn, NY",
    founded: 2018,
    categories: ["skincare"],
    accent: "#E8A598",
    rating: 4.5,
    reviewCount: 4032,
    followerCount: 92702,
    websiteUrl: "https://lovekinship.com",
    logoUrl: "/brands/kinship.png",
  },
  {
    id: "c151",
    slug: "lanolips",
    name: "Lanolips",
    tagline: "101 ointment cult balm",
    story: "Australian lanolin balms for lips, cuticles, and dry patches — one tube, many emergencies.",
    location: "Australia",
    founded: 2010,
    categories: ["skincare"],
    accent: "#F4A6C4",
    rating: 4.6,
    reviewCount: 15549,
    followerCount: 95730,
    websiteUrl: "https://lanolips.com",
    logoUrl: "/brands/lanolips.png",
  },
  {
    id: "c152",
    slug: "little-seed-farm",
    name: "Little Seed Farm",
    tagline: "Farm-made natural deodorant",
    story: "Tennessee farmstead deodorant and balms — simple ingredients, small batches, serious odor control.",
    location: "Tennessee",
    founded: 2015,
    categories: ["deodorant","skincare"],
    accent: "#8FBC8F",
    rating: 4.7,
    reviewCount: 11927,
    followerCount: 79129,
    websiteUrl: "https://littleseedfarm.com",
    logoUrl: "/brands/little-seed-farm.png",
  },
  {
    id: "c153",
    slug: "living-libations",
    name: "Living Libations",
    tagline: "Beyond organic botanical beauty",
    story: "Canadian botanical apothecary with wildcrafted oils for skin, smile, and hair.",
    location: "Ontario, Canada",
    founded: 2000,
    categories: ["skincare","oral","hair"],
    accent: "#6B4F3A",
    rating: 4.8,
    reviewCount: 15908,
    followerCount: 78404,
    websiteUrl: "https://www.livinglibations.com",
    logoUrl: "/brands/living-libations.png",
  },
  {
    id: "c154",
    slug: "lume",
    name: "Lume",
    tagline: "Whole-body odor control",
    story: "Acidified deodorant for underarms and everywhere else odor shows up — clinical and cult.",
    location: "Minnesota",
    founded: 2017,
    categories: ["deodorant"],
    accent: "#E91E8C",
    rating: 4.9,
    reviewCount: 21122,
    followerCount: 167510,
    websiteUrl: "https://shop.lumedeodorant.com",
    logoUrl: "/brands/lume.png",
  },
  {
    id: "c155",
    slug: "makeup-by-mario",
    name: "Makeup By Mario",
    tagline: "Pro makeup for everyone",
    story: "Mario Dedivanovic’s pro makeup line — soft sculpts and everyday glam tools.",
    location: "New York, NY",
    founded: 2020,
    categories: ["skincare"],
    accent: "#F5CBA7",
    rating: 4.4,
    reviewCount: 10530,
    followerCount: 169797,
    websiteUrl: "https://makeupbymario.com",
    logoUrl: "/brands/makeup-by-mario.png",
  },
  {
    id: "c156",
    slug: "may-lindstrom",
    name: "May Lindstrom Skin",
    tagline: "Sensorial botanical skincare",
    story: "Handcrafted botanical rituals that feel like a spa in a jar — rich oils, masks, and cleansers.",
    location: "Los Angeles, CA",
    founded: 2010,
    categories: ["skincare"],
    accent: "#C9A9A6",
    rating: 4.5,
    reviewCount: 21217,
    followerCount: 121838,
    websiteUrl: "https://www.maylindstrom.com",
    logoUrl: "/brands/may-lindstrom.png",
  },
  {
    id: "c157",
    slug: "meliora",
    name: "Meliora",
    tagline: "Plastic-free laundry and soap",
    story: "Chicago-made plastic-free laundry and cleaning — better means better for home and planet.",
    location: "Chicago, IL",
    founded: 2016,
    categories: ["skincare"],
    accent: "#E67E22",
    rating: 4.6,
    reviewCount: 3798,
    followerCount: 75273,
    websiteUrl: "https://meliorameansbetter.com",
    logoUrl: "/brands/meliora.png",
  },
  {
    id: "c158",
    slug: "mielle",
    name: "Mielle Organics",
    tagline: "Rosemary and organics for curls",
    story: "Rosemary mint fame and organic-inspired curl care for growth, moisture, and definition.",
    location: "United States",
    founded: 2014,
    categories: ["hair"],
    accent: "#228B22",
    rating: 4.7,
    reviewCount: 11388,
    followerCount: 87613,
    websiteUrl: "https://mielleorganics.com",
    logoUrl: "/brands/mielle.png",
  },
  {
    id: "c159",
    slug: "momentous",
    name: "Momentous",
    tagline: "NSF-certified performance nutrition",
    story: "Athlete-trusted supplements with serious testing — protein, creatine, and recovery.",
    location: "United States",
    founded: 2016,
    categories: ["supplements","protein"],
    accent: "#1A5276",
    rating: 4.8,
    reviewCount: 6013,
    followerCount: 98971,
    websiteUrl: "https://www.livemomentous.com",
    logoUrl: "/brands/momentous.png",
  },
  {
    id: "c160",
    slug: "moon-oral",
    name: "MOON",
    tagline: "Oral beauty, elevated",
    story: "Whitening and oral care with a beauty-shelf vibe — clean aesthetic, everyday brightening.",
    location: "United States",
    founded: 2018,
    categories: ["oral"],
    accent: "#F8F1E3",
    rating: 4.9,
    reviewCount: 10100,
    followerCount: 95372,
    websiteUrl: "https://www.moonoralbeauty.com",
    logoUrl: "/brands/moon-oral.png",
  },
  {
    id: "c161",
    slug: "naturium",
    name: "Naturium",
    tagline: "Science-backed accessible skincare",
    story: "Dermatologist-loved actives at approachable prices — serums and treatments that punch up.",
    location: "United States",
    founded: 2020,
    categories: ["skincare"],
    accent: "#4A7C59",
    rating: 4.4,
    reviewCount: 1448,
    followerCount: 31362,
    websiteUrl: "https://naturium.com",
    logoUrl: "/brands/naturium.png",
  },
  {
    id: "c162",
    slug: "nest-new-york",
    name: "NEST New York",
    tagline: "Fragrance for home and body",
    story: "Luxe candles and body mists — layered scent stories for home and skin.",
    location: "New York, NY",
    founded: 2006,
    categories: ["skincare"],
    accent: "#F5EEE6",
    rating: 4.5,
    reviewCount: 12718,
    followerCount: 168332,
    websiteUrl: "https://www.nestnewyork.com",
    logoUrl: "/brands/nest-new-york.png",
  },
  {
    id: "c163",
    slug: "odacite",
    name: "Odacité",
    tagline: "Synergy blends of pure plant oils",
    story: "Paris-meets-LA botanical skincare built around cold-pressed oils and concentrated plant actives.",
    location: "Los Angeles, CA",
    founded: 2009,
    categories: ["skincare"],
    accent: "#7A9E7E",
    rating: 4.6,
    reviewCount: 15732,
    followerCount: 113567,
    websiteUrl: "https://odacite.com",
    logoUrl: "/brands/odacite.png",
  },
  {
    id: "c164",
    slug: "one-love-organics",
    name: "One Love Organics",
    tagline: "Island-born organic skincare",
    story: "Georgia sea island botanicals in cheerful organic skincare — vitamin B oil and glow staples.",
    location: "Georgia",
    founded: 2008,
    categories: ["skincare"],
    accent: "#E8A598",
    rating: 4.7,
    reviewCount: 19589,
    followerCount: 77044,
    websiteUrl: "https://oneloveorganics.com",
    logoUrl: "/brands/one-love-organics.png",
  },
  {
    id: "c165",
    slug: "otherland",
    name: "Otherland",
    tagline: "Design-forward clean candles",
    story: "Beautiful candles without the toxin cloud — design-first home fragrance.",
    location: "New York, NY",
    founded: 2016,
    categories: ["skincare"],
    accent: "#AED6F1",
    rating: 4.8,
    reviewCount: 13393,
    followerCount: 80484,
    websiteUrl: "https://www.otherland.com",
    logoUrl: "/brands/otherland.png",
  },
  {
    id: "c166",
    slug: "p-f-candle",
    name: "P.F. Candle Co.",
    tagline: "LA hand-poured candles",
    story: "Hand-poured soy candles from LA — amber jars and neighborhood scent nostalgia.",
    location: "Los Angeles, CA",
    founded: 2008,
    categories: ["skincare"],
    accent: "#C4A484",
    rating: 4.9,
    reviewCount: 1215,
    followerCount: 9201,
    websiteUrl: "https://pfcandleco.com",
    logoUrl: "/brands/p-f-candle.png",
  },
  {
    id: "c167",
    slug: "package-free",
    name: "Package Free",
    tagline: "Zero-waste daily swaps",
    story: "Lauren Singer’s zero-waste shop — refillable and plastic-light personal care swaps.",
    location: "Brooklyn, NY",
    founded: 2017,
    categories: ["skincare","oral"],
    accent: "#27AE60",
    rating: 4.4,
    reviewCount: 18311,
    followerCount: 176599,
    websiteUrl: "https://packagefreeshop.com",
    logoUrl: "/brands/package-free.png",
  },
  {
    id: "c168",
    slug: "pai-skincare",
    name: "Pai Skincare",
    tagline: "Sensitive-skin specialists",
    story: "London clean brand built for reactive skin — gentle plant formulas with serious patch-test energy.",
    location: "London, UK",
    founded: 2007,
    categories: ["skincare"],
    accent: "#D4A5A5",
    rating: 4.5,
    reviewCount: 25897,
    followerCount: 131507,
    websiteUrl: "https://www.paiskincare.com",
    logoUrl: "/brands/pai-skincare.png",
  },
  {
    id: "c169",
    slug: "phlur",
    name: "Phlur",
    tagline: "Conscious fragrance house",
    story: "Transparent fragrance with social impact baked in — modern scents and body mists.",
    location: "Austin, TX",
    founded: 2015,
    categories: ["skincare"],
    accent: "#E8D5C4",
    rating: 4.6,
    reviewCount: 21754,
    followerCount: 128960,
    websiteUrl: "https://www.phlur.com",
    logoUrl: "/brands/phlur.png",
  },
  {
    id: "c170",
    slug: "public-goods",
    name: "Public Goods",
    tagline: "Beautiful everyday essentials",
    story: "Membership essentials with a design-forward clean aesthetic — body, hair, and home.",
    location: "New York, NY",
    founded: 2017,
    categories: ["skincare","oral","hair"],
    accent: "#F5F5F0",
    rating: 4.7,
    reviewCount: 16243,
    followerCount: 142324,
    websiteUrl: "https://www.publicgoods.com",
    logoUrl: "/brands/public-goods.png",
  },
  {
    id: "c171",
    slug: "quip",
    name: "quip",
    tagline: "Electric brush subscription simple",
    story: "Sleek electric brushes and refill rituals that make oral care feel modern.",
    location: "New York, NY",
    founded: 2015,
    categories: ["oral"],
    accent: "#5DADE2",
    rating: 4.8,
    reviewCount: 1490,
    followerCount: 78885,
    websiteUrl: "https://www.getquip.com",
    logoUrl: "/brands/quip.png",
  },
  {
    id: "c172",
    slug: "rahua",
    name: "Rahua",
    tagline: "Amazon oil hair care",
    story: "Symbiotic Amazon oils in luxurious hair care — rainforest-sourced and salon-polished.",
    location: "New York, NY",
    founded: 2008,
    categories: ["hair"],
    accent: "#1B4D3E",
    rating: 4.9,
    reviewCount: 13916,
    followerCount: 54864,
    websiteUrl: "https://rahua.com",
    logoUrl: "/brands/rahua.png",
  },
  {
    id: "c173",
    slug: "raw-elements",
    name: "Raw Elements",
    tagline: "Reef-safe mineral sunscreen",
    story: "Certified natural mineral sunscreen for people who live outside — reef-conscious and water-ready.",
    location: "United States",
    founded: 2010,
    categories: ["sunscreen"],
    accent: "#2E8B57",
    rating: 4.4,
    reviewCount: 24508,
    followerCount: 69466,
    websiteUrl: "https://rawelementsusa.com",
    logoUrl: "/brands/raw-elements.png",
  },
  {
    id: "c174",
    slug: "recess",
    name: "Recess",
    tagline: "Calm in a can",
    story: "Adaptogen and magnesium drinks for modern nervous systems — soft focus without the crash.",
    location: "New York, NY",
    founded: 2019,
    categories: ["supplements","electrolytes"],
    accent: "#BB8FCE",
    rating: 4.5,
    reviewCount: 25426,
    followerCount: 106051,
    websiteUrl: "https://shop.takearecess.com",
    logoUrl: "/brands/recess.png",
  },
  {
    id: "c175",
    slug: "refy",
    name: "REFY",
    tagline: "Soft glam brow and lip",
    story: "Soft-sculpt brow and lip essentials from the UK — minimal kits, maximal definition.",
    location: "United Kingdom",
    founded: 2020,
    categories: ["skincare"],
    accent: "#D5D8DC",
    rating: 4.6,
    reviewCount: 15635,
    followerCount: 159936,
    websiteUrl: "https://refybeauty.com",
    logoUrl: "/brands/refy.png",
  },
  {
    id: "c176",
    slug: "revitin",
    name: "Revitin",
    tagline: "Prebiotic toothpaste",
    story: "Microbiome-minded toothpaste that supports oral balance instead of scorched-earth mint.",
    location: "United States",
    founded: 2016,
    categories: ["oral"],
    accent: "#27AE60",
    rating: 4.7,
    reviewCount: 10129,
    followerCount: 55567,
    websiteUrl: "https://revitin.com",
    logoUrl: "/brands/revitin.png",
  },
  {
    id: "c177",
    slug: "rose-inc",
    name: "Rose Inc",
    tagline: "Clean color, skin-first",
    story: "Rosie Huntington-Whiteley’s clean color line — skin tints and care with a soft-focus finish.",
    location: "United States",
    founded: 2021,
    categories: ["skincare"],
    accent: "#E6B0AA",
    rating: 4.8,
    reviewCount: 9701,
    followerCount: 171242,
    websiteUrl: "https://www.roseinc.com",
    logoUrl: "/brands/rose-inc.png",
  },
  {
    id: "c178",
    slug: "skin1004",
    name: "SKIN1004",
    tagline: "Centella from Madagascar",
    story: "Madagascar centella in calming serums and sunscreens — barrier care for sensitive days.",
    location: "South Korea",
    founded: 2016,
    categories: ["skincare","sunscreen"],
    accent: "#3D8B6E",
    rating: 4.9,
    reviewCount: 15189,
    followerCount: 152089,
    websiteUrl: "https://skin1004.com",
    logoUrl: "/brands/skin1004.png",
  },
  {
    id: "c179",
    slug: "spotlight-oral",
    name: "Spotlight Oral Care",
    tagline: "Dentist-designed oral care",
    story: "Irish dentist-founded whitening and oral care — clinical goals with a clean aesthetic.",
    location: "Ireland",
    founded: 2018,
    categories: ["oral"],
    accent: "#1ABC9C",
    rating: 4.4,
    reviewCount: 24019,
    followerCount: 56352,
    websiteUrl: "https://www.spotlightoralcare.com",
    logoUrl: "/brands/spotlight-oral.png",
  },
  {
    id: "c180",
    slug: "starface",
    name: "Starface",
    tagline: "Star-shaped pimple patches",
    story: "Playful hydrocolloid patches and skin care with a cosmic smile — breakouts, but make it cute.",
    location: "New York, NY",
    founded: 2019,
    categories: ["skincare"],
    accent: "#FFE66D",
    rating: 4.5,
    reviewCount: 13465,
    followerCount: 8625,
    websiteUrl: "https://starface.world",
    logoUrl: "/brands/starface.png",
  },
  {
    id: "c181",
    slug: "stream2sea",
    name: "Stream2Sea",
    tagline: "Reef-safe sun and swim care",
    story: "Dive-tested reef-safe sunscreen and hair care for oceans, lakes, and chlorinated weekends.",
    location: "Florida",
    founded: 2012,
    categories: ["sunscreen","hair"],
    accent: "#1E90FF",
    rating: 4.6,
    reviewCount: 10242,
    followerCount: 72866,
    websiteUrl: "https://www.stream2sea.com",
    logoUrl: "/brands/stream2sea.png",
  },
  {
    id: "c182",
    slug: "suavecito",
    name: "Suavecito",
    tagline: "Pomade culture originals",
    story: "Pomade and grooming with old-school barbershop energy and a modern cult following.",
    location: "California",
    founded: 2011,
    categories: ["hair"],
    accent: "#C0392B",
    rating: 4.7,
    reviewCount: 8449,
    followerCount: 8633,
    websiteUrl: "https://suavecito.com",
    logoUrl: "/brands/suavecito.png",
  },
  {
    id: "c183",
    slug: "susanne-kaufmann",
    name: "Susanne Kaufmann",
    tagline: "Alpine botanical spa care",
    story: "Austrian Alps botanicals in spa-grade formulas — calm, precise, and quietly luxurious.",
    location: "Austria",
    founded: 2003,
    categories: ["skincare"],
    accent: "#A9CCE3",
    rating: 4.8,
    reviewCount: 17080,
    followerCount: 168496,
    websiteUrl: "https://www.susannekaufmann.com",
    logoUrl: "/brands/susanne-kaufmann.png",
  },
  {
    id: "c184",
    slug: "the-nue-co",
    name: "The Nue Co",
    tagline: "Functional wellness, design-first",
    story: "London wellness for stress, gut, and skin — functional formulas with a design-forward ritual.",
    location: "London, UK",
    founded: 2017,
    categories: ["supplements","skincare"],
    accent: "#2C2C2C",
    rating: 4.9,
    reviewCount: 17832,
    followerCount: 82927,
    websiteUrl: "https://thenueco.com",
    logoUrl: "/brands/the-nue-co.png",
  },
  {
    id: "c185",
    slug: "three-ships",
    name: "Three Ships",
    tagline: "Plant-powered, proven clean beauty",
    story: "Toronto clean beauty with plant actives and clinical receipts — transparent formulas without the junk.",
    location: "Toronto, Canada",
    founded: 2017,
    categories: ["skincare"],
    accent: "#5B8C5A",
    rating: 4.4,
    reviewCount: 15733,
    followerCount: 10525,
    websiteUrl: "https://threeshipsbeauty.com",
    logoUrl: "/brands/three-ships.png",
  },
  {
    id: "c186",
    slug: "vegamour",
    name: "Vegamour",
    tagline: "Plant-based hair wellness",
    story: "Clean plant actives for thinning hair concerns — serums and systems with a clinical-clean vibe.",
    location: "Los Angeles, CA",
    founded: 2016,
    categories: ["hair"],
    accent: "#2E8B57",
    rating: 4.5,
    reviewCount: 23705,
    followerCount: 85616,
    websiteUrl: "https://vegamour.com",
    logoUrl: "/brands/vegamour.png",
  },
  {
    id: "c187",
    slug: "verb",
    name: "VERB",
    tagline: "Ghost oil and modern hair tools",
    story: "Accessible pro hair care with ghost oil fame — shiny results without heavy price panic.",
    location: "United States",
    founded: 2012,
    categories: ["hair"],
    accent: "#7F8C8D",
    rating: 4.6,
    reviewCount: 15968,
    followerCount: 97481,
    websiteUrl: "https://verbproducts.com",
    logoUrl: "/brands/verb.png",
  },
  {
    id: "c188",
    slug: "vintners-daughter",
    name: "Vintner's Daughter",
    tagline: "Active botanical face oil",
    story: "Napa-rooted botanical face oil with a devoted following — dense plant actives in one daily ritual.",
    location: "Napa, CA",
    founded: 2014,
    categories: ["skincare"],
    accent: "#8B4513",
    rating: 4.7,
    reviewCount: 11870,
    followerCount: 143917,
    websiteUrl: "https://www.vintnersdaughter.com",
    logoUrl: "/brands/vintners-daughter.png",
  },
  {
    id: "c189",
    slug: "voluspa",
    name: "Voluspa",
    tagline: "Japonica candle house",
    story: "Artisan candles in tin and glass — Japonica scents with a decorative cult following.",
    location: "California",
    founded: 1999,
    categories: ["skincare"],
    accent: "#D5A6E6",
    rating: 4.8,
    reviewCount: 15021,
    followerCount: 45211,
    websiteUrl: "https://voluspa.com",
    logoUrl: "/brands/voluspa.png",
  },
  {
    id: "c190",
    slug: "well-people",
    name: "W3LL PEOPLE",
    tagline: "Clean makeup and skin that behaves",
    story: "Austin clean beauty for everyday makeup and skin — plant-powered formulas that skip the suspect stuff.",
    location: "Austin, TX",
    founded: 2008,
    categories: ["skincare"],
    accent: "#6B8F71",
    rating: 4.9,
    reviewCount: 16523,
    followerCount: 160560,
    websiteUrl: "https://wellpeople.com",
    logoUrl: "/brands/well-people.png",
  },
  {
    id: "c191",
    slug: "american-crew",
    name: "American Crew",
    tagline: "Salon men’s grooming",
    story: "Classic men’s salon hair care — pomades, shampoos, and grooming staples.",
    location: "United States",
    founded: 1994,
    categories: ["hair"],
    accent: "#8B0000",
    rating: 4.4,
    reviewCount: 10020,
    followerCount: 150083,
    websiteUrl: "https://www.americancrew.com",
    logoUrl: "/brands/american-crew.png",
  },
  {
    id: "c192",
    slug: "diptyque",
    name: "Diptyque",
    tagline: "Parisian scent icons",
    story: "Paris fragrance house of candles and eaux — oval labels and olfactory landmarks.",
    location: "Paris, France",
    founded: 1961,
    categories: ["skincare"],
    accent: "#145A32",
    rating: 4.5,
    reviewCount: 6919,
    followerCount: 84837,
    websiteUrl: "https://www.diptyqueparis.com",
    logoUrl: "/brands/diptyque.png",
  },
  {
    id: "c193",
    slug: "dollar-shave",
    name: "Dollar Shave Club",
    tagline: "Shave and body basics",
    story: "The club that made razors funny — shave, body wash, and grooming essentials.",
    location: "United States",
    founded: 2011,
    categories: ["skincare"],
    accent: "#27AE60",
    rating: 4.6,
    reviewCount: 18062,
    followerCount: 96474,
    websiteUrl: "https://www.dollarshaveclub.com",
    logoUrl: "/brands/dollar-shave.png",
  },
  {
    id: "c194",
    slug: "fenty-skin",
    name: "Fenty Skin",
    tagline: "Inclusive skin essentials",
    story: "Rihanna’s skin line for real routines — cleansers, moisturizers, and SPF built for all tones.",
    location: "United States",
    founded: 2020,
    categories: ["skincare"],
    accent: "#8B0000",
    rating: 4.7,
    reviewCount: 15947,
    followerCount: 124057,
    websiteUrl: "https://fentybeauty.com",
    logoUrl: "/brands/fenty-skin.png",
  },
  {
    id: "c195",
    slug: "glossier",
    name: "Glossier",
    tagline: "Skin first, makeup second",
    story: "The millennial skin-first beauty brand — cloud textures, pink packaging, cult classics.",
    location: "New York, NY",
    founded: 2014,
    categories: ["skincare"],
    accent: "#F7CAC9",
    rating: 4.8,
    reviewCount: 5098,
    followerCount: 102744,
    websiteUrl: "https://www.glossier.com",
    logoUrl: "/brands/glossier.png",
  },
  {
    id: "c196",
    slug: "harry-s",
    name: "Harry's",
    tagline: "Quality men’s shave gear",
    story: "Thoughtful razors and shave care — factory-owned quality without department-store markup.",
    location: "New York, NY",
    founded: 2013,
    categories: ["skincare"],
    accent: "#F39C12",
    rating: 4.9,
    reviewCount: 18619,
    followerCount: 85160,
    websiteUrl: "https://harrys.com",
    logoUrl: "/brands/harry-s.png",
  },
  {
    id: "c197",
    slug: "haus-labs",
    name: "HAUS LABS",
    tagline: "Cleanish color by Lady Gaga",
    story: "Lady Gaga’s artistry-minded makeup — pigment, performance, and inclusive shades.",
    location: "United States",
    founded: 2019,
    categories: ["skincare"],
    accent: "#000000",
    rating: 4.4,
    reviewCount: 9013,
    followerCount: 162641,
    websiteUrl: "https://www.hauslabs.com",
    logoUrl: "/brands/haus-labs.png",
  },
  {
    id: "c198",
    slug: "milk-makeup",
    name: "Milk Makeup",
    tagline: "Live your look, NYC",
    story: "Cool-girl makeup sticks and skin hybrids born in NYC — fast, fun, and camera-ready.",
    location: "New York, NY",
    founded: 2016,
    categories: ["skincare"],
    accent: "#FFFFFF",
    rating: 4.5,
    reviewCount: 23758,
    followerCount: 178036,
    websiteUrl: "https://www.milkmakeup.com",
    logoUrl: "/brands/milk-makeup.png",
  },
  {
    id: "c199",
    slug: "olaplex",
    name: "Olaplex",
    tagline: "Bond-building hair repair",
    story: "The bond-building system that changed color damage recovery — science-first hair repair.",
    location: "United States",
    founded: 2014,
    categories: ["hair"],
    accent: "#000000",
    rating: 4.6,
    reviewCount: 26491,
    followerCount: 85828,
    websiteUrl: "https://olaplex.com",
    logoUrl: "/brands/olaplex.png",
  },
  {
    id: "c200",
    slug: "rare-beauty",
    name: "Rare Beauty",
    tagline: "Mental health–minded beauty",
    story: "Selena’s inclusive beauty brand with mental health at the center — soft pigments and kind formulas.",
    location: "United States",
    founded: 2020,
    categories: ["skincare"],
    accent: "#C39BD3",
    rating: 4.7,
    reviewCount: 18144,
    followerCount: 125282,
    websiteUrl: "https://www.rarebeauty.com",
    logoUrl: "/brands/rare-beauty.png",
  },
];
