import type { Brand } from "./types";

/** Wave 109: small organic / toxic-free brands across marketplace categories (c1523+). */
export const catalogBrandsWave109: Brand[] = [
  {
    id: "c1523",
    slug: "theodent",
    name: "Theodent",
    tagline: "Cacao theobromine toothpaste — fluoride-free Classic, Kids, and clinical 300",
    story:
      "Theodent started in a New Orleans lab that asked what cacao already knew. Theobromine — Rennou, patented, only in this tube — instead of fluoride. Classic is Crystal Mint for the adult sink. Kids is Chocolate Chip so the tube does not have to hide. 300 is the clinical-strength mint when the enamel wants more. No thirty-tube case, no family pack: the three tubes you actually squeeze.",
    location: "New Orleans, LA",
    founded: 2007,
    categories: ["oral"],
    accent: "#5C3A2A",
    rating: 4.7,
    reviewCount: 1840,
    followerCount: 22000,
    websiteUrl: "https://www.theodent.com",
    logoUrl: "/brands/theodent.png",
  },
  {
    id: "c1524",
    slug: "voli-wellness",
    name: "Voli",
    tagline: "Coconut water, pink Himalayan salt, Irish sea moss — five 15-stick flavors, zero added sugar",
    story:
      "Voli mixed hydration from food, not from a lab salt rack. Coconut water. Pink Himalayan salt. Irish sea moss. Aquamin from the sea. Five hundred milligrams of sodium in a 15-stick carton — Riptide Raspberry, Sunset Strawberry Lemonade, Paradise Passionfruit, Pali Piña Colada, Hillside Honeydew — already on the title. No energy drink, no marathon bundle, no dad hat: the stick you tear for the bottle.",
    location: "California, United States",
    founded: 2023,
    categories: ["electrolytes"],
    accent: "#1F6B6B",
    rating: 4.6,
    reviewCount: 420,
    followerCount: 6800,
    websiteUrl: "https://voliwellness.com",
    logoUrl: "/brands/voli-wellness.svg",
  },
  {
    id: "c1525",
    slug: "hela-nutrition",
    name: "HeLa Nutrition",
    tagline: "Organic pea-hemp-pumpkin plant protein — Chocolate, Vanilla, or Natural — plus Nova Scotia marine collagen",
    story:
      "HeLa Nutrition is a Toronto kitchen that refused gums and a sweetener aisle. Organic pea, hemp, pumpkin, basil seed, and chia — Chocolate, Vanilla, or Natural, already on the flavor option. Twenty-two grams in a scoop, no aftertaste lecture. Unflavored marine collagen from wild-caught North Atlantic fish, bottled in Nova Scotia. No frother, no shaker upsell, no wellness pack: the bag you scoop.",
    location: "Toronto, Canada",
    founded: 2021,
    categories: ["protein", "supplements"],
    accent: "#3D5A2A",
    rating: 4.7,
    reviewCount: 310,
    followerCount: 5400,
    websiteUrl: "https://helanutrition.com",
    logoUrl: "/brands/hela-nutrition.svg",
  },
  {
    id: "c1526",
    slug: "indie-paradiso",
    name: "Indie Paradiso",
    tagline: "Australian mineral SPF 50+ — fragrance-free non-nano zinc, clear or tinted for the face",
    story:
      "Indie Paradiso is named for a beach-loving daughter and mixed in Australia for skin that actually burns. Non-nano zinc. Fragrance-free. Four-hour water resistance. Dermatologist-tested for sensitive skin. The original mineral SPF 50+ for the body. A tinted daily face that skips the white cast. No household set, no trio: the two tubes you put on before the sand.",
    location: "Australia",
    founded: 2023,
    categories: ["sunscreen"],
    accent: "#C45C26",
    rating: 4.8,
    reviewCount: 160,
    followerCount: 3200,
    websiteUrl: "https://indieparadiso.com",
    logoUrl: "/brands/indie-paradiso.svg",
  },
  {
    id: "c1527",
    slug: "ancestral-cosmetics",
    name: "Ancestral Cosmetics",
    tagline: "Irish grass-fed tallow deodorant, sun balm, and honey lip — Mountain Spring to Velvet Dust",
    story:
      "Ancestral Cosmetics renders Irish grass-fed suet in-house and stops there. The deodorant is tallow, cocoa butter, castor oil, magnesium, and arrowroot — Mountain Spring, Pine Forest, Sweet Meadow, unscented, Velvet Dust — already on the title, one jar not a three-pack. A tallow sun balm. A honey lip in peppermint, orange, or vanilla. A charcoal cleanse. A beard oil. No dog balm, no shipping protection, no winter set: the jar you open.",
    location: "Ireland",
    founded: 2022,
    categories: ["deodorant", "skincare", "sunscreen", "hair"],
    accent: "#7A5A38",
    rating: 4.8,
    reviewCount: 890,
    followerCount: 14000,
    websiteUrl: "https://ancestralcosmetics.com",
    logoUrl: "/brands/ancestral-cosmetics.svg",
  },
  {
    id: "c1528",
    slug: "yamabushi-farms",
    name: "Yamabushi Farms",
    tagline: "Los Angeles fruiting-body Lion's Mane — MEZAME tincture, powder, capsules, no grain filler",
    story:
      "Yamabushi Farms grows Lion's Mane for Michelin kitchens in Los Angeles, then bottles the same fruiting body. MEZAME is the dual-extract tincture — mushroom, ethanol, water. A sub-critical powder for the coffee. Capsules when the dropper is not the day. MAMORU is turkey tail, maitake, and shiitake. IBUKI is cordyceps, guayusa, and Lion's Mane. No bandana, no farmer tee, no tulsi-rose tea bag: the bottle that came off the farm.",
    location: "Los Angeles, CA",
    founded: 2022,
    categories: ["supplements"],
    accent: "#3A4A28",
    rating: 4.7,
    reviewCount: 140,
    followerCount: 2800,
    websiteUrl: "https://yamabushifarms.com",
    logoUrl: "/brands/yamabushi-farms.svg",
  },
];
