import type { Brand } from "./types";

/** Wave 100: small organic / toxic-free brands across marketplace categories (c1469+). */
export const catalogBrandsWave100: Brand[] = [
  {
    id: "c1469",
    slug: "nudge",
    name: "nudge",
    tagline: "10% nano-hydroxyapatite toothpaste — fluoride-free, SLS-free, lab-tested",
    story:
      "Harrisburg-born oral care built around 10% rod-shaped nano-hydroxyapatite — fluoride-free, SLS-free toothpaste and tablets in real flavors, plus silk floss, bamboo brushes, and probiotic gum. Third-party lab tested, made in small batches for people who want enamel care without the junk.",
    location: "Harrisburg, PA",
    founded: 2023,
    categories: ["oral"],
    accent: "#2F6B4F",
    rating: 4.7,
    reviewCount: 186,
    followerCount: 4200,
    websiteUrl: "https://shopnudge.com",
    logoUrl: "/brands/nudge.svg",
  },
  {
    id: "c1470",
    slug: "cocobana",
    name: "CocoBana",
    tagline: "Five-ingredient electrolytes — coconut, banana, lemon, sea salt, marine magnesium",
    story:
      "Five real ingredients, nothing else — organic coconut water, banana, and lemon powders with sea salt and marine magnesium. No stevia, no monk fruit, no natural flavors. Stick packs for tennis, travel, and everyday sweat.",
    location: "United States",
    founded: 2024,
    categories: ["electrolytes"],
    accent: "#E8B84A",
    rating: 4.6,
    reviewCount: 74,
    followerCount: 1100,
    websiteUrl: "https://drinkcocobana.com",
    logoUrl: "/brands/cocobana.svg",
  },
  {
    id: "c1471",
    slug: "rare-forms",
    name: "Rare Forms",
    tagline: "UK all-in-one whey isolate — creatine, collagen, and daily minerals in one scoop",
    story:
      "London all-in-one whey isolate — one scoop covers protein, creatine, collagen, and daily minerals without a cabinet of tubs. Vanilla only, short labels, built for people who want the stack without the merch.",
    location: "United Kingdom",
    founded: 2023,
    categories: ["protein", "supplements"],
    accent: "#1F3A4D",
    rating: 4.6,
    reviewCount: 92,
    followerCount: 1600,
    websiteUrl: "https://rareforms.co",
    logoUrl: "/brands/rare-forms.svg",
  },
  {
    id: "c1472",
    slug: "birch-babe",
    name: "Birch Babe",
    tagline: "Canadian mineral SPF 40, CertClean skin, and sulfate-free shampoo bars",
    story:
      "Ontario-made CertClean botanicals — 100% mineral SPF 40 in a compostable tube, sulfate-free shampoo and body bars, and short-list face care. Vegan, cruelty-free, and packaged for people who want reef-safe sun and wash-day without the megastore list.",
    location: "Ontario, Canada",
    founded: 2016,
    categories: ["sunscreen", "skincare", "hair", "oral"],
    accent: "#3D6B4F",
    rating: 4.8,
    reviewCount: 640,
    followerCount: 18000,
    websiteUrl: "https://birchbabe.com",
    logoUrl: "/brands/birch-babe.svg",
  },
  {
    id: "c1473",
    slug: "magic-moo-tallow",
    name: "Magic Moo Tallow",
    tagline: "Grass-fed tallow deodorant, mineral sun protectant, and whipped ancestral balms",
    story:
      "Grass-fed tallow from pasture to pit — aluminum-free deodorant in lavender mint, cedar spruce, and cocoa clementine, plus a mineral sun protectant and whipped ancestral balms. Short labels you could read at the farm stand.",
    location: "United States",
    founded: 2022,
    categories: ["deodorant", "sunscreen", "skincare"],
    accent: "#C4A574",
    rating: 4.8,
    reviewCount: 210,
    followerCount: 5400,
    websiteUrl: "https://magicmootallow.com",
    logoUrl: "/brands/magic-moo-tallow.svg",
  },
  {
    id: "c1474",
    slug: "mogo-farm",
    name: "Mogo Farm",
    tagline: "Derbyshire fruiting-body tinctures — grown, extracted, and bottled on the farm",
    story:
      "Derbyshire farm tinctures grown, extracted, and bottled on the same Peak District land — 100% fruiting bodies, 1:3 dual extract, no grain filler. Lion's Mane through Birch Polypore, plus a five-mushroom blend, third-party tested from farm to bottle.",
    location: "Derbyshire, United Kingdom",
    founded: 2021,
    categories: ["supplements"],
    accent: "#5A3D2B",
    rating: 4.8,
    reviewCount: 980,
    followerCount: 7200,
    websiteUrl: "https://mogofarm.co.uk",
    logoUrl: "/brands/mogo-farm.svg",
  }
];
