import type { Brand } from "./types";

/** Wave 72: small organic / toxic-free brands across marketplace categories (c1301+). */
export const catalogBrandsWave72: Brand[] = [
  {
    id: "c1301",
    slug: "vivi",
    name: "vivi",
    tagline: "One-tube mint n-HA toothpaste that whitens without fluoride or peroxide burn",
    story: "A tiny fluoride-free oral house that puts nano-hydroxyapatite plus peroxide-free PAP into a mint tube. Pack count is size — keep the single tube. The product page is key-ingredient marketing, so leave ingredients empty unless a full INCI is published.",
    location: "United States",
    founded: 2025,
    categories: ["oral"],
    accent: "#3A6B6A",
    rating: 4.6,
    reviewCount: 48,
    followerCount: 1100,
    websiteUrl: "https://www.viviteeth.com",
    logoUrl: "/brands/vivi.svg",
  },
  {
    id: "c1302",
    slug: "keto-vitals",
    name: "KetoVitals",
    tagline: "Zero-sugar keto electrolyte tubs in named flavors plus mineral capsules",
    story: "A small US hydration kitchen mixing unflavored, lemonade, fruit punch, mango, cherry limeade, pineapple coconut, and raspberry lemonade electrolytes without sugar. Flavors already live on separate titles. Variety / assorted / coffee packs stay boxed. Electrolyte capsules stay supplements. Serving count is size.",
    location: "United States",
    founded: 2018,
    categories: ["electrolytes","supplements"],
    accent: "#1B4F6B",
    rating: 4.7,
    reviewCount: 212,
    followerCount: 3800,
    websiteUrl: "https://www.ketovitals.com",
    logoUrl: "/brands/keto-vitals.svg",
  },
  {
    id: "c1303",
    slug: "iconic-protein",
    name: "Iconic Protein",
    tagline: "Grass-fed whey protein powder and ready-to-drink shakes without artificial junk",
    story: "A clean US whey house that keeps Vanilla Bean, Chocolate Truffle, Café Latte, and Cacao + Greens on separate titles. Tub pounds and RTD pack count are size. Creatine stays supplements. Sample packs and flavor bundles stay boxed.",
    location: "United States",
    founded: 2016,
    categories: ["protein","supplements"],
    accent: "#2C4A3E",
    rating: 4.6,
    reviewCount: 640,
    followerCount: 9200,
    websiteUrl: "https://www.drinkiconic.com",
    logoUrl: "/brands/iconic-protein.png",
  },
  {
    id: "c1304",
    slug: "moose-haven-farm",
    name: "Moose Haven Farm",
    tagline: "Tustin homestead mineral sun balm, whipped tallow, and magnesium lotion",
    story: "A small Tustin, California homestead rendering grass-fed tallow into Sun Haven mineral balm plus whipped creams, lip balms, and a magnesium lotion. Lip and Moose Whip Scent expand; jar ounces stay size. Hats, sunglasses, candles, gift cards, and bundles stay boxed. Sun Haven publishes a real zinc / tallow / shea / beeswax list.",
    location: "Tustin, CA",
    founded: 2023,
    categories: ["sunscreen","skincare"],
    accent: "#6B4A2A",
    rating: 4.8,
    reviewCount: 56,
    followerCount: 1400,
    websiteUrl: "https://www.moosehavenfarm.com",
    logoUrl: "/brands/moose-haven-farm.svg",
  },
  {
    id: "c1305",
    slug: "vivelle-la",
    name: "Vivelle LA",
    tagline: "Los Angeles five-ingredient grass-fed suet tallow creams without water or olive oil",
    story: "A 2026 Los Angeles kitchen that double-whips 100% grass-fed suet into Signature, Honey, Whipped, and Gentleman's tallow creams. Flavors already live on separate titles. Gua sha tools stay boxed. Published formula is suet tallow / jojoba / sweet almond / frankincense / raw honey.",
    location: "Los Angeles, CA",
    founded: 2026,
    categories: ["skincare"],
    accent: "#8A5A3A",
    rating: 4.7,
    reviewCount: 38,
    followerCount: 900,
    websiteUrl: "https://www.vivellela.com",
    logoUrl: "/brands/vivelle-la.svg",
  },
  {
    id: "c1306",
    slug: "sb-botanicals",
    name: "S&B Botanicals",
    tagline: "Washington herbal tallow soaps, aluminum-free deodorant, and calendula butters",
    story: "Belinda's Washington herbal kitchen pouring calendula, chamomile, and tallow into an aluminum-free deodorant, named soap bars, whipped butters, salves, serums, and a rosemary peppermint hair oil. Lotion / oil / salve / butter / cream Scent expand; jar ounces stay size. Ebooks, ingredient directories, room sprays, and gift cards stay boxed.",
    location: "Washington",
    founded: 2022,
    categories: ["deodorant","skincare","hair"],
    accent: "#4A6A3A",
    rating: 4.8,
    reviewCount: 94,
    followerCount: 2100,
    websiteUrl: "https://sbbotanicalproducts.com",
    logoUrl: "/brands/sb-botanicals.svg",
  },
];
