import type { Brand } from "./types";

/** Wave 6: small organic / toxic-free brands across marketplace categories (c501+). */
export const catalogBrandsWave6: Brand[] = [
  {
    id: "c501",
    slug: "fango",
    name: "FANGO",
    tagline: "Puerto Rico–made mineral balm with five ingredients",
    story: "Handcrafted on the beaches of Puerto Rico — non-nano zinc, coconut, shea, beeswax, and raspberry seed oil. No chemical filters, no reef junk, just a balm built for Caribbean sun.",
    location: "Puerto Rico",
    founded: 2021,
    categories: ["sunscreen"],
    accent: "#C45C26",
    rating: 4.8,
    reviewCount: 280,
    followerCount: 4200,
    websiteUrl: "https://fangospf.com",
    logoUrl: "/brands/fango.svg",
  },
  {
    id: "c502",
    slug: "indie-paradiso",
    name: "Indie Paradiso",
    tagline: "Australian mineral SPF 50+ for sensitive, saltwater skin",
    story: "Named for a beach-loving daughter who needed sunscreen that didn’t sting — fragrance-free, non-nano zinc, dermatologist-tested, and made in Australia for messy, sandy days.",
    location: "Australia",
    founded: 2022,
    categories: ["sunscreen","skincare"],
    accent: "#E8A54B",
    rating: 4.7,
    reviewCount: 190,
    followerCount: 3100,
    websiteUrl: "https://indieparadiso.com",
    logoUrl: "/brands/indie-paradiso.svg",
  },
  {
    id: "c503",
    slug: "suntribe",
    name: "Suntribe",
    tagline: "Certified organic mineral sun care from Sweden",
    story: "Stockholm-born plastic-free sun care — certified organic mineral formulas in tins and sticks, short ingredient lists, and reef-minded zinc instead of a chemical cocktail.",
    location: "Stockholm, Sweden",
    founded: 2016,
    categories: ["sunscreen","skincare"],
    accent: "#D97706",
    rating: 4.6,
    reviewCount: 2100,
    followerCount: 28000,
    websiteUrl: "https://suntribesunscreen.com",
    logoUrl: "/brands/suntribe.svg",
  },
  {
    id: "c504",
    slug: "sunbutter",
    name: "SunButter",
    tagline: "Reef-safe mineral sun butter from Australia",
    story: "Gold Coast mineral sun care that spreads like a butter, not a paste — non-nano zinc, botanicals, and tinted lip zinc for faces that actually live outside.",
    location: "Gold Coast, Australia",
    founded: 2018,
    categories: ["sunscreen","skincare"],
    accent: "#B45309",
    rating: 4.7,
    reviewCount: 860,
    followerCount: 14000,
    websiteUrl: "https://sunbutter.com.au",
    logoUrl: "/brands/sunbutter.svg",
  },
  {
    id: "c505",
    slug: "saltt",
    name: "SALTT",
    tagline: "Clean-label electrolytes with real-fruit energy",
    story: "Sodium, potassium, and magnesium without the candy-aisle aftertaste — short-list hydration packets in flavors that read like a snack, not a lab.",
    location: "United States",
    founded: 2021,
    categories: ["electrolytes"],
    accent: "#0E7490",
    rating: 4.6,
    reviewCount: 540,
    followerCount: 7800,
    websiteUrl: "https://drinksaltt.com",
    logoUrl: "/brands/saltt.svg",
  },
  {
    id: "c506",
    slug: "lyteshow",
    name: "LyteShow",
    tagline: "Sugar-free ionic electrolyte drops",
    story: "A few drops in water — ionic minerals without sugar, dyes, or mystery flavors. Hydration for people who want the salts and nothing else.",
    location: "United States",
    founded: 2014,
    categories: ["electrolytes"],
    accent: "#1B4F72",
    rating: 4.5,
    reviewCount: 1900,
    followerCount: 12000,
    websiteUrl: "https://lyteline.com",
    logoUrl: "/brands/lyteshow.svg",
  },
  {
    id: "c507",
    slug: "sos-hydration",
    name: "SOS Hydration",
    tagline: "Clinically studied rapid-hydration packets",
    story: "Oral-rehydration science in a stick — the World Health Organization–style electrolyte ratio, less sugar than a sports drink, and flavors you can actually finish.",
    location: "United States / United Kingdom",
    founded: 2018,
    categories: ["electrolytes"],
    accent: "#2563EB",
    rating: 4.6,
    reviewCount: 3200,
    followerCount: 22000,
    websiteUrl: "https://soshydration.com",
    logoUrl: "/brands/sos-hydration.svg",
  },
  {
    id: "c508",
    slug: "moonvalley",
    name: "Moonvalley",
    tagline: "Organic Swedish protein bars from pro cyclists",
    story: "Founded by three WorldTour cyclists who wanted fuel they could pronounce — EU-organic oats, dates, and plant protein, wrapped without the usual bar junk.",
    location: "Sweden",
    founded: 2016,
    categories: ["protein"],
    accent: "#365314",
    rating: 4.7,
    reviewCount: 740,
    followerCount: 9600,
    websiteUrl: "https://moonvalley.me",
    logoUrl: "/brands/moonvalley.svg",
  },
  {
    id: "c509",
    slug: "aloha",
    name: "ALOHA",
    tagline: "USDA organic plant protein bars, nothing weird",
    story: "Organic plant protein that skips stevia, sugar alcohols, and soy isolates — bars and powders with ingredients you’d pack for a hike, not a chemistry set.",
    location: "United States",
    founded: 2011,
    categories: ["protein"],
    accent: "#16A34A",
    rating: 4.5,
    reviewCount: 8900,
    followerCount: 54000,
    websiteUrl: "https://aloha.com",
    logoUrl: "/brands/aloha.png",
  },
  {
    id: "c510",
    slug: "saavy-naturals",
    name: "Saavy Naturals",
    tagline: "Probiotic deodorant and plant-oil body care",
    story: "Small-batch Texas formulas — probiotic deodorant, oil cleansers, and body butters with a short botanical list and no aluminum, parabens, or synthetic fragrance pile-on.",
    location: "Texas",
    founded: 2013,
    categories: ["deodorant","skincare"],
    accent: "#2C5F4E",
    rating: 4.7,
    reviewCount: 1600,
    followerCount: 11000,
    websiteUrl: "https://saavynaturals.com",
    logoUrl: "/brands/saavy-naturals.png",
  },
  {
    id: "c511",
    slug: "naturallow",
    name: "NaturalLow",
    tagline: "Grass-fed tallow deodorant and barrier skincare",
    story: "Tallow-first formulas for people who want skin food, not filler — grass-fed fat, simple butters, and an aluminum-free deodorant that skips the baking-soda burn.",
    location: "United States",
    founded: 2020,
    categories: ["deodorant","skincare"],
    accent: "#6B3E26",
    rating: 4.8,
    reviewCount: 420,
    followerCount: 5600,
    websiteUrl: "https://www.naturallow.com",
    logoUrl: "/brands/naturallow.svg",
  },
  {
    id: "c512",
    slug: "primal-life",
    name: "Primal Life Organics",
    tagline: "Hydroxyapatite tooth powder from a dentist’s kitchen",
    story: "Dr. Shawn Wehe started with a jar of mineral tooth powder — nano-hydroxyapatite, clay, and botanicals, fluoride-free, in glass, for people who read the oral-care label twice.",
    location: "Ohio",
    founded: 2013,
    categories: ["oral"],
    accent: "#4D7C0F",
    rating: 4.6,
    reviewCount: 4100,
    followerCount: 19000,
    websiteUrl: "https://primallifeorganics.com",
    logoUrl: "/brands/primal-life.png",
  },
  {
    id: "c513",
    slug: "happier-beauty",
    name: "Happier Beauty",
    tagline: "Natural toothpaste in glass, made in the UK",
    story: "London oral care that ditched the plastic tube — mineral toothpaste in refillable glass, hydroxyapatite options, and a bamboo brush that doesn’t look like a science experiment.",
    location: "London, United Kingdom",
    founded: 2019,
    categories: ["oral"],
    accent: "#0E7490",
    rating: 4.6,
    reviewCount: 680,
    followerCount: 8400,
    websiteUrl: "https://happierbeauty.com",
    logoUrl: "/brands/happier-beauty.svg",
  },
  {
    id: "c514",
    slug: "great-oral-health",
    name: "Great Oral Health",
    tagline: "Hydroxyapatite toothpaste with a dentist’s checklist",
    story: "Remineralizing pastes and a gum that actually does something — nano-hydroxyapatite, xylitol, and a short free-from list for people rebuilding enamel without fluoride.",
    location: "United States",
    founded: 2016,
    categories: ["oral"],
    accent: "#1A5276",
    rating: 4.7,
    reviewCount: 1500,
    followerCount: 9200,
    websiteUrl: "https://www.greatoralhealth.com",
    logoUrl: "/brands/great-oral-health.svg",
  },
  {
    id: "c515",
    slug: "mychelle",
    name: "MyChelle",
    tagline: "Colorado clean clinicals with a short INCI list",
    story: "High-altitude clean skincare from Louisville, Colorado — vegan, cruelty-free serums and creams that put the active first and leave the fragrance circus out.",
    location: "Louisville, CO",
    founded: 2001,
    categories: ["skincare"],
    accent: "#7A6A53",
    rating: 4.6,
    reviewCount: 5400,
    followerCount: 31000,
    websiteUrl: "https://mychelle.com",
    logoUrl: "/brands/mychelle.png",
  },
  {
    id: "c516",
    slug: "roz",
    name: "ROZ",
    tagline: "Milk-powered clean haircare for every texture",
    story: "Founded by a chemist who treated hair like skin — milk proteins, plant oils, and a wash-day system that skips silicones, sulfates, and the usual salon fog.",
    location: "United States",
    founded: 2020,
    categories: ["hair"],
    accent: "#5B21B6",
    rating: 4.7,
    reviewCount: 890,
    followerCount: 15000,
    websiteUrl: "https://rozhair.com",
    logoUrl: "/brands/roz.svg",
  },
  {
    id: "c517",
    slug: "plaine-products",
    name: "Plaine Products",
    tagline: "Refillable aluminum bottles, clean wash-day basics",
    story: "Ohio-made shampoo, conditioner, and body care in aluminum you send back — plant-based formulas, no parabens or phthalates, and a refill loop that keeps plastic out of the shower.",
    location: "Ohio",
    founded: 2017,
    categories: ["hair","skincare"],
    accent: "#2F4F4F",
    rating: 4.6,
    reviewCount: 2200,
    followerCount: 18000,
    websiteUrl: "https://plaineproducts.com",
    logoUrl: "/brands/plaine-products.svg",
  },
  {
    id: "c518",
    slug: "seen",
    name: "SEEN",
    tagline: "Dermatologist-founded, non-comedogenic haircare",
    story: "Harvard dermatologist Iris Rubin built haircare that won’t wreck skin — fragrance-free options, no pore-clogging junk, and formulas tested for people who break out from their shampoo.",
    location: "Boston, MA",
    founded: 2018,
    categories: ["hair"],
    accent: "#BE185D",
    rating: 4.6,
    reviewCount: 3800,
    followerCount: 42000,
    websiteUrl: "https://helloseen.com",
    logoUrl: "/brands/seen.svg",
  },
  {
    id: "c519",
    slug: "wenatal",
    name: "WeNatal",
    tagline: "Practitioner-built prenatal for both parents",
    story: "A prenatal that includes the other half of the equation — methylated B vitamins, mineral forms you can absorb, and a his-and-hers formula written by practitioners who were tired of gummy junk.",
    location: "United States",
    founded: 2021,
    categories: ["supplements"],
    accent: "#BE185D",
    rating: 4.8,
    reviewCount: 2100,
    followerCount: 29000,
    websiteUrl: "https://wenatal.com",
    logoUrl: "/brands/wenatal.svg",
  },
  {
    id: "c520",
    slug: "beauty-chef",
    name: "The Beauty Chef",
    tagline: "Australian fermented inner beauty, no filler dust",
    story: "Carla Oates started with a kitchen ferment and a stubborn idea — glow from the gut. Organic botanicals, probiotics, and inner-beauty powders that skip the synthetic vitamin pile-on.",
    location: "Sydney, Australia",
    founded: 2009,
    categories: ["supplements","skincare"],
    accent: "#9A3412",
    rating: 4.7,
    reviewCount: 4600,
    followerCount: 38000,
    websiteUrl: "https://thebeautychef.com",
    logoUrl: "/brands/beauty-chef.png",
  },
];
