import type { Brand } from "./types";

/** Wave 43: small organic / toxic-free brands across marketplace categories (c1108+). */
export const catalogBrandsWave43: Brand[] = [
  {
    id: "c1108",
    slug: "peg-paste",
    name: "Peg Paste",
    tagline: "Australian micro-hydroxyapatite toothpaste — mint, clove, kids tubes, no bundle wall",
    story: "A family-owned Australian oral house that puts Portuguese micro-hydroxyapatite back into enamel instead of a fluoride-and-SLS aisle. Individual kids and adult tubes, pumps, and toothbrushes stay. Bundle stacks, rituals, and family multipacks stay out. AUD prices convert to USD.",
    location: "Australia",
    founded: 2021,
    categories: ["oral"],
    accent: "#2C6E49",
    rating: 4.7,
    reviewCount: 240,
    followerCount: 5100,
    websiteUrl: "https://pegpaste.com.au",
    logoUrl: "/brands/peg-paste.svg",
  },
  {
    id: "c1109",
    slug: "sunkissed-by-heaven",
    name: "Sunkissed by Heaven",
    tagline: "Two-SKU grass-fed tallow house — fragrance-free mineral SPF 50 plus a daily moisturizer",
    story: "A focused unused mineral-SPF tallow house: one fragrance-free non-nano zinc SPF 50 and one grass-fed tallow moisturizer. No merch, no gadget wall, no chemical-filter lotion aisle.",
    location: "United States",
    founded: 2024,
    categories: ["sunscreen","skincare"],
    accent: "#C4A35A",
    rating: 4.6,
    reviewCount: 42,
    followerCount: 800,
    websiteUrl: "https://sunkissedbyheaven.com",
    logoUrl: "/brands/sunkissed-by-heaven.svg",
  },
  {
    id: "c1110",
    slug: "grass-fed-beauty",
    name: "Grass-Fed Beauty",
    tagline: "Homegrown tallow sun balm plus whipped jar scents — no methylene-blue shop",
    story: "A small tallow kitchen that keeps a zinc sun balm and short-list whipped jars, face balm, scrub, and lip scents instead of a chemical-filter cream wall. Vanilla, citrus, lavender, bare, and raw shea stay. Methylene-blue balms stay out.",
    location: "United States",
    founded: 2023,
    categories: ["sunscreen","skincare"],
    accent: "#6B4F2A",
    rating: 4.6,
    reviewCount: 68,
    followerCount: 1400,
    websiteUrl: "https://grassfedbeauty.com",
    logoUrl: "/brands/grass-fed-beauty.svg",
  },
  {
    id: "c1111",
    slug: "tallowl",
    name: "Tallowl",
    tagline: "Short-list tallow balms with scent variants — baby, body, whipped jars, no trio wall",
    story: "A small tallow house that keeps baby balm, freedom balm, body balm, whipped jars, lip, oil, and eye serum instead of a synthetic-moisturizer aisle. Lavender, vanilla-orange, cedarwood, citrus, and unscented stay as their own listings. Trio bundles stay out.",
    location: "United States",
    founded: 2023,
    categories: ["skincare"],
    accent: "#8B5A2B",
    rating: 4.6,
    reviewCount: 55,
    followerCount: 1100,
    websiteUrl: "https://tallowlskincare.com",
    logoUrl: "/brands/tallowl.svg",
  },
  {
    id: "c1112",
    slug: "hallowed-homestead",
    name: "Hallowed Homestead",
    tagline: "Shenandoah Valley tallow — Summer Balm sun block, deodorant scents, whipped jars",
    story: "A fourth-generation Shenandoah Valley farm that renders tallow into a Summer Balm sun block, aluminum-free deodorant scents, whipped jars, soaps, and lips instead of a petroleum cream aisle. Individual formulas stay. Sample boxes, cooking tallow, and trio stacks stay in the barn.",
    location: "Shenandoah Valley, Virginia",
    founded: 2022,
    categories: ["sunscreen","skincare","deodorant"],
    accent: "#3D5A3A",
    rating: 4.8,
    reviewCount: 96,
    followerCount: 2200,
    websiteUrl: "https://hallowedhomestead.shop",
    logoUrl: "/brands/hallowed-homestead.svg",
  },
  {
    id: "c1113",
    slug: "desert-light-farm",
    name: "Desert Light Farm",
    tagline: "Arizona desert tallow — whipped scents, extra-strength deodorant, no $189 facial set",
    story: "A desert farm kitchen that keeps whipped tallow scents, rescue balms, facial balms, cleanser, toner, serum, soaps, lips, and aluminum-free deodorant instead of a synthetic spa-kit wall. Individual formulas stay. The $189 full facial set stays out.",
    location: "Arizona, United States",
    founded: 2022,
    categories: ["skincare","deodorant"],
    accent: "#C45C26",
    rating: 4.7,
    reviewCount: 74,
    followerCount: 1600,
    websiteUrl: "https://desertlightfarm.com",
    logoUrl: "/brands/desert-light-farm.svg",
  },
  {
    id: "c1114",
    slug: "kruger-farm",
    name: "Kruger Farm FL",
    tagline: "Florida grass-fed tallow — SPF 50 zinc sunblock plus whipped scent jars",
    story: "A Florida farm kitchen that pours locally rendered tallow with non-nano zinc into an SPF 50 sunblock stick, then keeps herbal balms and whipped moisturizer scents instead of a chemical-filter lotion wall. Individual formulas and lip flavors stay. Before-and-after bundles, trios, and lip-balm gift sets stay out.",
    location: "Florida, United States",
    founded: 2023,
    categories: ["sunscreen","skincare"],
    accent: "#2F6F5E",
    rating: 4.6,
    reviewCount: 51,
    followerCount: 900,
    websiteUrl: "https://nbsq3j-mu.myshopify.com",
    logoUrl: "/brands/kruger-farm.svg",
  },
  {
    id: "c1115",
    slug: "gaia-organics-tallow",
    name: "Gaia Organics",
    tagline: "Five-SKU organic tallow house — zinc sunblock, SPF 30 lip, honey balm scents",
    story: "A short-list organic tallow kitchen: zinc sunblock in fragrance-free or lightly scented, an SPF 30 beeswax lip in mint/lemon/mojito, magnesium body butter, unscented whip, and honey balm scents. No merch, no chemical filters.",
    location: "United States",
    founded: 2023,
    categories: ["sunscreen","skincare"],
    accent: "#4A6741",
    rating: 4.5,
    reviewCount: 38,
    followerCount: 700,
    websiteUrl: "https://393dc1-1e.myshopify.com",
    logoUrl: "/brands/gaia-organics-tallow.svg",
  },
  {
    id: "c1116",
    slug: "luxe-tallow",
    name: "Luxe",
    tagline: "Tallow zinc sun stick, edible sun balm, and aluminum-free deodorant — no $197 set wall",
    story: "A small tallow-and-mineral house that keeps a zinc sun stick, edible sun balm, tallow deodorant, whipped tallow, body oil, cleanser, eye serum, and cream instead of a chemical-filter kit aisle. Individual formulas stay. $97–$197 sets stay out.",
    location: "United States",
    founded: 2024,
    categories: ["sunscreen","skincare","deodorant"],
    accent: "#8B7355",
    rating: 4.5,
    reviewCount: 47,
    followerCount: 850,
    websiteUrl: "https://6pra2y-zd.myshopify.com",
    logoUrl: "/brands/luxe-tallow.svg",
  },
  {
    id: "c1117",
    slug: "kris-organics",
    name: "Kris Organics",
    tagline: "Tallow sun block plus magnesium deodorant scents, body butters, and a shampoo/shave bar",
    story: "A small organic kitchen that keeps tallow sun block, magnesium deodorant scents, whipped butters, face care, soaps, a tallow shampoo/shave bar, and lip flavors instead of a dish-soap-and-gift-crate shop. Individual formulas stay. Bundles, rituals, bug spray, soap dishes, kitchen blocks, and gift cards stay out.",
    location: "United States",
    founded: 2018,
    categories: ["sunscreen","skincare","deodorant","hair"],
    accent: "#7A5C3A",
    rating: 4.7,
    reviewCount: 210,
    followerCount: 4800,
    websiteUrl: "https://krisorganics.com",
    logoUrl: "/brands/kris-organics.svg",
  },
];
