import type { Brand } from "./types";

/** Wave 19: small organic / toxic-free brands across marketplace categories (c758+). */
export const catalogBrandsWave19: Brand[] = [
  {
    id: "c758",
    slug: "3rd-rock",
    name: "3rd Rock Essentials",
    tagline: "Food-grade zinc sunblock in organic glycerin — no water, no chemical-filter cocktail",
    story: "Dr. Guerry Grune built 3rd Rock because most 'mineral' lotions were still water emulsions stuffed with preservatives. The sunblock is 70% organic kosher glycerin plus non-nano zinc — warm a drop, spread thin, and it actually stays put. Reef-minded, infant-safe, and short enough to read out loud.",
    location: "United States",
    founded: 2012,
    categories: ["sunscreen","skincare"],
    accent: "#C45C26",
    rating: 4.8,
    reviewCount: 920,
    followerCount: 14000,
    websiteUrl: "https://3rdrockessentials.com",
    logoUrl: "/brands/3rd-rock.svg",
  },
  {
    id: "c759",
    slug: "kinesys",
    name: "KINeSYS",
    tagline: "Vancouver-made sport spray SPF — oil-free, alcohol-free, family-owned since 1995",
    story: "Born for people who actually sweat. KINeSYS is still mixed in Vancouver by the Heggie family after they refused to let the formula die — oil-free sprays and clear zinc sticks that skip the alcohol sting and the greasy film. Sport sunscreen that reads like a performance product, not a perfume aisle.",
    location: "Vancouver, Canada",
    founded: 1995,
    categories: ["sunscreen"],
    accent: "#1B4F72",
    rating: 4.7,
    reviewCount: 1400,
    followerCount: 18000,
    websiteUrl: "https://kinesyssunscreen.com",
    logoUrl: "/brands/kinesys.svg",
  },
  {
    id: "c760",
    slug: "beauty-by-earth",
    name: "Beauty by Earth",
    tagline: "Non-nano zinc SPF 30 and 50 — ceramide serums and body lotion without chemical filters",
    story: "A clean-beauty house that treats sunscreen like skincare, not a chalky afterthought. Non-nano zinc face serums and body lotions sit on the barrier instead of a chemical-filter stack — no oxybenzone, no octinoxate, no white-cast panic if you take your time. Everyday mineral SPF from a brand that still publishes the INCI.",
    location: "United States",
    founded: 2013,
    categories: ["sunscreen","skincare"],
    accent: "#2A9D8F",
    rating: 4.6,
    reviewCount: 2100,
    followerCount: 42000,
    websiteUrl: "https://beautybyearth.com",
    logoUrl: "/brands/beauty-by-earth.png",
  },
  {
    id: "c761",
    slug: "poofy-organics",
    name: "Poofy Organics",
    tagline: "Pennsylvania organic apothecary — mineral SPF, hydroxyapatite toothpaste, aluminum-free deo",
    story: "A family kitchen that grew into a full clean-apothecary: 20% non-nano zinc sunscreen, Happy Teeth hydroxyapatite paste, Max Deo without aluminum, and lip balms that still list the oils. Organic when it matters, fragrance-honest, and the kind of label you'd let a kid put in their mouth.",
    location: "Pennsylvania, United States",
    founded: 2006,
    categories: ["sunscreen","oral","deodorant","skincare","hair"],
    accent: "#E27D60",
    rating: 4.8,
    reviewCount: 3600,
    followerCount: 28000,
    websiteUrl: "https://poofyorganics.com",
    logoUrl: "/brands/poofy-organics.png",
  },
  {
    id: "c762",
    slug: "green-hydration",
    name: "GREEN Organic Hydration",
    tagline: "USDA Organic electrolytes with green-coffee caffeine — coconut water, cane juice, Himalayan salt",
    story: "The only USDA Organic electrolyte mix that also replaces the second coffee. Coconut water, pressed cane juice, and pink Himalayan salt in an ORT salt-to-sugar ratio, plus 180mg caffeine from green coffee bean — no maltodextrin, no sucralose, no dye circus. Hot cacao mornings and tropical cold afternoons.",
    location: "United States",
    founded: 2022,
    categories: ["electrolytes"],
    accent: "#3D6B4F",
    rating: 4.6,
    reviewCount: 480,
    followerCount: 12000,
    websiteUrl: "https://drinkgreendaily.com",
    logoUrl: "/brands/green-hydration.svg",
  },
  {
    id: "c763",
    slug: "normalyte",
    name: "NormaLyte",
    tagline: "WHO-style oral rehydration powder — real electrolytes, real flavors, no sports-drink fog",
    story: "Medical-grade hydration that still tastes like fruit, not a locker-room candy aisle. NormaLyte follows oral-rehydration science — sodium, potassium, glucose — in strawberry lemonade, lemon-lime, watermelon, and a pure unsweetened packet. For days you actually depleted something, not a lifestyle flavor system.",
    location: "United States",
    founded: 2016,
    categories: ["electrolytes"],
    accent: "#4A90A4",
    rating: 4.7,
    reviewCount: 890,
    followerCount: 16000,
    websiteUrl: "https://normalyte.com",
    logoUrl: "/brands/normalyte.png",
  },
  {
    id: "c764",
    slug: "aphina",
    name: "Aphina",
    tagline: "Regenerative pea protein plus pearl electrolytes — no gums, no fake flavor systems",
    story: "Beauty-from-within that still reads like food. Regenerative North American pea protein with a full 1500mg mushroom dose per flavor, liquid marine collagen, and Electric Beauty electrolytes built on coconut water and freshwater pearl — not a sodium dump. No xanthan, no guar, no 'natural flavors' drawer.",
    location: "United States",
    founded: 2021,
    categories: ["protein","electrolytes","supplements"],
    accent: "#C4786A",
    rating: 4.7,
    reviewCount: 340,
    followerCount: 9800,
    websiteUrl: "https://aphina.co",
    logoUrl: "/brands/aphina.svg",
  },
  {
    id: "c765",
    slug: "organic-protein-co",
    name: "The Organic Protein Company",
    tagline: "British organic whey — cacao and maca, banana lucuma, cookies and cream, no junk drawer",
    story: "A UK whey kitchen that treats flavor like food: organic cacao and maca, Madagascan vanilla, banana and lucuma, plus a pure unflavoured tub for people who just want milk. Grass-fed organic whey without the neon gym stack or a 20-line sweetener system. Protein you'd actually bake with.",
    location: "United Kingdom",
    founded: 2015,
    categories: ["protein"],
    accent: "#6B3E26",
    rating: 4.8,
    reviewCount: 1200,
    followerCount: 19000,
    websiteUrl: "https://www.theorganicproteincompany.co.uk",
    logoUrl: "/brands/organic-protein-co.svg",
  },
  {
    id: "c766",
    slug: "nothing-naughty",
    name: "Nothing Naughty",
    tagline: "New Zealand whey, egg, and collagen — compostable scoops, refill bags, readable labels",
    story: "A Kiwi protein house that named itself after the ingredient list. Whey isolate, cage-free egg protein, and marine collagen in refill bags — compostable scoops, no mystery blends, flavors that still sound like food. Clean protein from New Zealand without importing a candy aisle.",
    location: "New Zealand",
    founded: 2014,
    categories: ["protein","supplements"],
    accent: "#2C5F4E",
    rating: 4.7,
    reviewCount: 760,
    followerCount: 11000,
    websiteUrl: "https://www.nothingnaughty.co.nz",
    logoUrl: "/brands/nothing-naughty.svg",
  },
  {
    id: "c767",
    slug: "valor-organics",
    name: "Valor Organics",
    tagline: "Byron Bay natural deodorant tins — Original, Wategos, unscented, no aluminum theater",
    story: "Started as a Sea Shepherd fundraiser on a folding table in the Byron hinterland. Pit Stop deodorant still comes in a tin — Original, coastal Wategos, and a truly unscented — plus castile washes and a chemist-made face balm. Australian-made underarm care that never needed a plastic stick.",
    location: "Byron Bay, Australia",
    founded: 2014,
    categories: ["deodorant","skincare"],
    accent: "#5B7C6A",
    rating: 4.7,
    reviewCount: 540,
    followerCount: 8700,
    websiteUrl: "https://valororganics.com",
    logoUrl: "/brands/valor-organics.svg",
  },
  {
    id: "c768",
    slug: "simply-tallow",
    name: "Simply Tallow",
    tagline: "Grass-fed tallow cream and sensitive deodorant — short ancestral lists, no perfume fog",
    story: "A small tallow kitchen that stopped at the ingredients that earn a place: rendered suet cream for dry skin, plus Simply Delicate and Simply Confident deodorants that skip the aluminum and the baking-soda rash. Ancestral moisture without a 40-line label or a merch drawer.",
    location: "United States",
    founded: 2021,
    categories: ["deodorant","skincare"],
    accent: "#C4A484",
    rating: 4.8,
    reviewCount: 210,
    followerCount: 4600,
    websiteUrl: "https://simplytallow.com",
    logoUrl: "/brands/simply-tallow.svg",
  },
  {
    id: "c769",
    slug: "tallow-skin-co",
    name: "Tallow Skin Co.",
    tagline: "Colorado organic grass-fed tallow — weekly batches, deodorant, shampoo bars, facial oils",
    story: "Handmade in Colorado from organic, grass-fed and finished suet. Whipped tallows, CoQ10 facial oil, oat-and-chamomile baby bars, and underarm care that still starts with tallow instead of a synthetic gel. Weekly small batches — no MRNA-era ranch mystery, no filler cream.",
    location: "Colorado, United States",
    founded: 2022,
    categories: ["skincare","deodorant","hair"],
    accent: "#8B5A2B",
    rating: 4.8,
    reviewCount: 380,
    followerCount: 7200,
    websiteUrl: "https://www.thetallowskinco.com",
    logoUrl: "/brands/tallow-skin-co.svg",
  },
  {
    id: "c770",
    slug: "simply-sooney",
    name: "Simply Sooney",
    tagline: "Woman-owned hydroxyapatite tooth powder — glass jars, organic xylitol, zero fluoride foam",
    story: "Since 2013, ultra-small-batch tooth powders in glass: 10–15% hydroxyapatite, organic birch xylitol, bentonite, and peppermint that doesn't need SLS to feel clean. Refill pouches, bamboo charcoal floss, and a formula gentle enough that swallowing it isn't a panic. Oral care without a toothpaste tube circus.",
    location: "United States",
    founded: 2013,
    categories: ["oral"],
    accent: "#7EB8A2",
    rating: 4.8,
    reviewCount: 640,
    followerCount: 9100,
    websiteUrl: "https://simplysooney.com",
    logoUrl: "/brands/simply-sooney.svg",
  },
  {
    id: "c771",
    slug: "sawyer-scout",
    name: "Sawyer & Scout",
    tagline: "Whipped grass-fed tallow balms — manuka, lavender frankincense, vanilla bean, nothing else",
    story: "Five balms, that's the shop. Grass-fed and finished suet whipped with organic botanicals: manuka honey, lavender and frankincense, vanilla bean, and a daily signature. No serum ladder, no 12-step ritual — ancestral fat that melts on contact and leaves vitamins A, D, E, and K on the skin.",
    location: "United States",
    founded: 2023,
    categories: ["skincare"],
    accent: "#A67C52",
    rating: 4.9,
    reviewCount: 160,
    followerCount: 3400,
    websiteUrl: "https://sawyerandscout.com",
    logoUrl: "/brands/sawyer-scout.svg",
  },
  {
    id: "c772",
    slug: "ocasa-botanica",
    name: "Ocasa Botanica",
    tagline: "Tallow creams, rosemary hair elixirs, and mineral toothpaste — farm botanicals, short INCI",
    story: "A botanical house that still cooks like a farm apothecary: calendula- and lavender-infused tallow, hop-and-rosemary scalp serum, charcoal cleanser, and mineral toothpaste. Plant extracts and ancestral fats instead of a fragrance lab. Hair, face, and teeth from the same short-ingredient kitchen.",
    location: "United States",
    founded: 2020,
    categories: ["skincare","hair","oral","supplements"],
    accent: "#6B4F3A",
    rating: 4.7,
    reviewCount: 420,
    followerCount: 6800,
    websiteUrl: "https://ocasabotanica.com",
    logoUrl: "/brands/ocasa-botanica.svg",
  },
  {
    id: "c773",
    slug: "nature-sustained",
    name: "Nature Sustained",
    tagline: "Raw Thai soapnut shampoo — wildcrafted, probiotic, never heat-processed, no coconut detergents",
    story: "Most 'natural' shampoo is still a coconut surfactant with a botanical sticker. Nature Sustained ferments wild-harvested soapnut and jungle fruit from Thailand with live vegan probiotics — no heat, no synthetic fragrance, no detergent foam show. Shampoo, conditioner, and body wash that still taste like plants if you were reckless enough to try.",
    location: "United States",
    founded: 2021,
    categories: ["hair","skincare"],
    accent: "#2F6F5E",
    rating: 4.7,
    reviewCount: 190,
    followerCount: 5200,
    websiteUrl: "https://naturesustained.com",
    logoUrl: "/brands/nature-sustained.svg",
  },
  {
    id: "c774",
    slug: "living-water",
    name: "Living Water Organics",
    tagline: "Poughkeepsie-made tallow curl care — rosemary shampoo, dry shampoo, whipped tallow",
    story: "Handcrafted in Poughkeepsie, NY: aloe-and-tallow shampoo, rosemary curl gel, dry shampoo for light or dark hair, and whipped grass-fed tallow for face and ends. Low-plastic, slow batches, formulas you'd recognize on a homestead label. Curl care that skipped the silicone coating.",
    location: "Poughkeepsie, NY",
    founded: 2020,
    categories: ["hair","skincare"],
    accent: "#4A7C59",
    rating: 4.8,
    reviewCount: 280,
    followerCount: 6100,
    websiteUrl: "https://www.livingwaterorganics.com",
    logoUrl: "/brands/living-water.svg",
  },
  {
    id: "c775",
    slug: "atlas-haircare",
    name: "Atlas Haircare",
    tagline: "Organic regrowth shampoo and co-wash — clean, vegan, heritage recipes without the salon fog",
    story: "Porsha built Atlas from family hair recipes and a refusal to put a perfume drawer on the scalp. Moisturizing regrowth shampoo, 3-in-1 co-wash, root-strengthening oil, and beard oil — organic, vegan-friendly, cruelty-free. Haircare that treats the crown like skin, not a fragrance launch.",
    location: "United States",
    founded: 2021,
    categories: ["hair"],
    accent: "#5E4B45",
    rating: 4.6,
    reviewCount: 150,
    followerCount: 4400,
    websiteUrl: "https://atlashaircare.com",
    logoUrl: "/brands/atlas-haircare.svg",
  },
  {
    id: "c776",
    slug: "mycogenius",
    name: "Mycogenius",
    tagline: "100% fruiting-body extracts — Lion's Mane, chaga, cordyceps, published batch COAs",
    story: "No grain, no mycelium-on-oats trick. Mycogenius extracts 100% organic fruiting bodies — 1:1 hot water, ISO 17025 labs, a QR code to the batch COA. Lion's Mane, chaga, cordyceps, and daily complexes without flow agents. Functional mushrooms that still look like mushrooms on the label.",
    location: "United States",
    founded: 2022,
    categories: ["supplements"],
    accent: "#3E2723",
    rating: 4.8,
    reviewCount: 220,
    followerCount: 5800,
    websiteUrl: "https://mycogenius.com",
    logoUrl: "/brands/mycogenius.svg",
  },
  {
    id: "c777",
    slug: "mogu-mushrooms",
    name: "Mógū",
    tagline: "Organic 12:1 dual extracts — Lion's Mane, snow fungus, synergy blends, no fillers",
    story: "Dual extraction the long way: hot water for beta-glucans, alcohol for the compounds water misses. Organic Lion's Mane, cordyceps, maitake, snow fungus, and a six-mushroom synergy — no flow agents, no grain starch. A small mushroom house that still prints the extract ratio on the pouch.",
    location: "United States",
    founded: 2021,
    categories: ["supplements","skincare"],
    accent: "#6B3E26",
    rating: 4.7,
    reviewCount: 180,
    followerCount: 4900,
    websiteUrl: "https://mogumushrooms.com",
    logoUrl: "/brands/mogu-mushrooms.svg",
  },
];
