import type { Brand } from "./types";

/** Wave 14: small organic / toxic-free brands across marketplace categories (c661+). */
export const catalogBrandsWave14: Brand[] = [
  {
    id: "c661",
    slug: "waxhead",
    name: "Waxhead",
    tagline: "Non-nano zinc sunscreens for kids, sport, and post-treatment skin",
    story: "A reef-minded zinc house that treats mineral SPF like outdoor gear, not a drugstore afterthought. Uncoated non-nano zinc, tinted pastes, baby formulas, and sport sticks — no oxybenzone, no octinoxate, no chemical-filter cocktail. Built for guides, parents, and anyone who actually lives in the sun.",
    location: "United States",
    founded: 2015,
    categories: ["sunscreen"],
    accent: "#C45C26",
    rating: 4.7,
    reviewCount: 2100,
    followerCount: 28000,
    websiteUrl: "https://gowaxhead.com",
    logoUrl: "/brands/waxhead.png",
  },
  {
    id: "c662",
    slug: "hawaiian-healing",
    name: "Hawaiian Healing",
    tagline: "Island botanicals, plumeria, and coconut silk for sun-worn skin",
    story: "A Hawaii-born kitchen of plumeria, coconut, and kukui that treats sun-exposed skin like something you feed, not something you coat in plastic lotion. Face washes, body silk, and mineral-minded island care without the tourist-shop fragrance fog.",
    location: "Hawaii",
    founded: 2012,
    categories: ["sunscreen","skincare"],
    accent: "#2A9D8F",
    rating: 4.6,
    reviewCount: 980,
    followerCount: 19000,
    websiteUrl: "https://hawaiianhealing.com",
    logoUrl: "/brands/hawaiian-healing.png",
  },
  {
    id: "c663",
    slug: "colorescience",
    name: "Colorescience",
    tagline: "All-mineral Total Protection SPF for face and body, minus the white cast circus",
    story: "A dermatology-adjacent mineral SPF studio: zinc-and-titanium body shields, glow finishes, and no-show formulas that skip chemical filters. Built for people who want broad-spectrum coverage that actually sits on skin, not a neon beach lotion.",
    location: "Carlsbad, CA",
    founded: 2000,
    categories: ["sunscreen","skincare"],
    accent: "#1B4F72",
    rating: 4.7,
    reviewCount: 6400,
    followerCount: 72000,
    websiteUrl: "https://colorescience.com",
    logoUrl: "/brands/colorescience.png",
  },
  {
    id: "c664",
    slug: "circular-bodies",
    name: "Circular Bodies",
    tagline: "Small-batch organic soaps, rose kits, and plastic-free body care",
    story: "A circular-economy body-care shop pouring organic bars and rose-forward kits for sensitive and mature skin. Compostable thinking, garden botanicals, and formulas that skip the petroleum lotion aisle — made in small batches, not a megastore refill wall.",
    location: "Canada",
    founded: 2018,
    categories: ["skincare"],
    accent: "#4A7C59",
    rating: 4.8,
    reviewCount: 320,
    followerCount: 5400,
    websiteUrl: "https://circularbodies.com",
    logoUrl: "/brands/circular-bodies.svg",
  },
  {
    id: "c665",
    slug: "lenus",
    name: "LENUS",
    tagline: "Encinitas-made mineral sunscreen and botanical balms in numbered batches",
    story: "Small-batch Encinitas botanicals: non-nano zinc and titanium sunscreen cut with raspberry and carrot-seed oils, plus numbered skin balms and herb blends. Handmade, biodegradable-minded, and built for sunny California days without the chemical-filter drawer.",
    location: "Encinitas, CA",
    founded: 2016,
    categories: ["sunscreen","skincare"],
    accent: "#C4A35A",
    rating: 4.7,
    reviewCount: 410,
    followerCount: 8900,
    websiteUrl: "https://shoplenus.com",
    logoUrl: "/brands/lenus.svg",
  },
  {
    id: "c666",
    slug: "nazareth-organics",
    name: "Nazareth Organics",
    tagline: "Grass-fed tallow sun sticks, cleansing oils, and mom balms",
    story: "A tallow apothecary wrapping organic grass-fed fat, jojoba, cacao, and non-nano zinc into sun sticks and everyday balms. Food-grade fats instead of petroleum lotion. Portable mineral coverage for people who want ancestral fat plus reef-safer zinc.",
    location: "United States",
    founded: 2020,
    categories: ["sunscreen","skincare"],
    accent: "#6B3E26",
    rating: 4.8,
    reviewCount: 280,
    followerCount: 6100,
    websiteUrl: "https://nazareth-organics.com",
    logoUrl: "/brands/nazareth-organics.svg",
  },
  {
    id: "c667",
    slug: "stone-grace",
    name: "Stone & Grace",
    tagline: "Lynchburg tallow sun cream, lip balms, and whipped butters",
    story: "Handcrafted in Lynchburg from local butcher tallow, jojoba, and non-nano zinc. A postpartum-acne origin story that turned into simple sun cream, lip balms, and whipped tallow — no emulsifying-wax theater, no luxury markup, just fat-and-mineral care.",
    location: "Lynchburg, VA",
    founded: 2021,
    categories: ["sunscreen","skincare"],
    accent: "#8B7355",
    rating: 4.8,
    reviewCount: 190,
    followerCount: 4200,
    websiteUrl: "https://stonegraceco.com",
    logoUrl: "/brands/stone-grace.svg",
  },
  {
    id: "c668",
    slug: "ohso-bare",
    name: "OhSo Bare",
    tagline: "Organic grass-fed tallow suncream and SkinDays face balms",
    story: "A UK tallow kitchen using locally sourced organic grass-fed fat, raspberry seed, cacao, and non-nano zinc. SunRays body suncream and SkinDays face balms for people who want food-grade sun care, not a chemical-filter bottle from the pharmacy.",
    location: "United Kingdom",
    founded: 2019,
    categories: ["sunscreen","skincare"],
    accent: "#C4A484",
    rating: 4.7,
    reviewCount: 360,
    followerCount: 7800,
    websiteUrl: "https://ohsobare.com",
    logoUrl: "/brands/ohso-bare.svg",
  },
  {
    id: "c669",
    slug: "tallow-cosmetics",
    name: "Tallow Cosmetics",
    tagline: "Halal tallow creams, hair wax, and SPF 30 mineral sunscreen",
    story: "A tallow-first cosmetics shop: unscented creams, natural hair wax, and an SPF 30 mineral sunscreen that starts with fat, not petroleum. Simple labels, ancestral ingredients, and formulas that skip the synthetic fragrance fog.",
    location: "United States",
    founded: 2018,
    categories: ["sunscreen","skincare","hair"],
    accent: "#6B3E26",
    rating: 4.6,
    reviewCount: 240,
    followerCount: 5100,
    websiteUrl: "https://tallowcosmetics.com",
    logoUrl: "/brands/tallow-cosmetics.svg",
  },
  {
    id: "c670",
    slug: "clean-simple-eats",
    name: "Clean Simple Eats",
    tagline: "Whey protein and clear protein water in real-food flavors, no junk-drawer sweetener stack",
    story: "A flavor-first protein kitchen: pumpkin pie, lemonade, unflavored, and seasonal bags without the neon sports-drink aftertaste. Built for people who want a shake that tastes like food, not a gas-station candy packet.",
    location: "United States",
    founded: 2018,
    categories: ["protein"],
    accent: "#E8A317",
    rating: 4.8,
    reviewCount: 8900,
    followerCount: 210000,
    websiteUrl: "https://cleansimpleeats.com",
    logoUrl: "/brands/clean-simple-eats.svg",
  },
  {
    id: "c671",
    slug: "raw-sport",
    name: "Raw Sport",
    tagline: "Informed Sport plant protein, creatine, and clean performance stacks",
    story: "A UK performance kitchen that batch-tests for athletes: organic-leaning plant protein, creatine, and women’s multis without the mystery-dye circus. Independently screened for heavy metals and pesticides — built for people who train, not for a convenience-store shelf.",
    location: "United Kingdom",
    founded: 2016,
    categories: ["protein","supplements"],
    accent: "#2C5F4E",
    rating: 4.7,
    reviewCount: 1800,
    followerCount: 34000,
    websiteUrl: "https://www.revolution-foods.com",
    logoUrl: "/brands/raw-sport.png",
  },
  {
    id: "c672",
    slug: "amazing-grass",
    name: "Amazing Grass",
    tagline: "Organic greens-plus-protein powders in chocolate, vanilla, and fruit",
    story: "Farm-grown greens that actually show up in the scoop: wheatgrass, alfalfa, and plant protein in chocolate, vanilla, and tropical blends. A cleaner greens ritual than the candy-sweet superfood aisle — no neon, no mystery blend you can’t pronounce.",
    location: "United States",
    founded: 2002,
    categories: ["protein","supplements"],
    accent: "#3D8B6E",
    rating: 4.6,
    reviewCount: 12000,
    followerCount: 180000,
    websiteUrl: "https://amazinggrass.com",
    logoUrl: "/brands/amazing-grass.png",
  },
  {
    id: "c673",
    slug: "hiya",
    name: "Hiya",
    tagline: "Sugar-free kids hydration, fiber, and daily vitamins without the gummy candy trick",
    story: "A kids-first supplement shop that skipped the sugar gummy aisle: daily hydration, fiber, growth protein, and teen multis with zero added sugar. Built for parents who want electrolytes and vitamins that don’t look like dessert.",
    location: "United States",
    founded: 2019,
    categories: ["electrolytes","supplements"],
    accent: "#F2C94C",
    rating: 4.8,
    reviewCount: 5400,
    followerCount: 96000,
    websiteUrl: "https://hiyahealth.com",
    logoUrl: "/brands/hiya.svg",
  },
  {
    id: "c674",
    slug: "stay-poised",
    name: "Stay Poised Naturals",
    tagline: "Clean electrolyte stick packs in strawberry lemonade, no sports-drink dye stack",
    story: "A tiny hydration kitchen packing electrolyte sticks without the neon locker-room syrup. Strawberry lemonade and simple minerals for people who want to drink water that tastes like fruit, not a convenience-store packet.",
    location: "United States",
    founded: 2021,
    categories: ["electrolytes"],
    accent: "#E27D60",
    rating: 4.7,
    reviewCount: 160,
    followerCount: 2800,
    websiteUrl: "https://staypoisednaturals.com",
    logoUrl: "/brands/stay-poised.svg",
  },
  {
    id: "c675",
    slug: "wellbel",
    name: "Wellbel",
    tagline: "Physician-formulated hair supplements plus detox shampoo and restorer",
    story: "A hair-first wellness house: vegan, non-GMO supplements for thinning hair, plus a detox shampoo and restorer that skip the salon chemical fog. Built for people who want growth support without a mystery-pill bottle.",
    location: "United States",
    founded: 2018,
    categories: ["hair","supplements"],
    accent: "#7EB8A2",
    rating: 4.6,
    reviewCount: 3200,
    followerCount: 54000,
    websiteUrl: "https://wellbel.com",
    logoUrl: "/brands/wellbel.svg",
  },
  {
    id: "c676",
    slug: "ancestral-cosmetics",
    name: "Ancestral Cosmetics",
    tagline: "Tallow body cream, beard oil, and ancestral grooming without the fragrance fog",
    story: "A tallow-and-beard kitchen: body cream, beard oil, and brushes for people who want fat-soluble vitamins on skin, not a drugstore aftershave. Simple ancestral formulas, no petroleum lotion, no synthetic cologne cloud.",
    location: "United States",
    founded: 2022,
    categories: ["hair","skincare"],
    accent: "#6B3E26",
    rating: 4.7,
    reviewCount: 120,
    followerCount: 2100,
    websiteUrl: "https://ancestralcosmetics.com",
    logoUrl: "/brands/ancestral-cosmetics.svg",
  },
  {
    id: "c677",
    slug: "blume",
    name: "Blume",
    tagline: "Clean acne oils, clear-skin edits, and teen-friendly formulas without the harsh drugstore stack",
    story: "A clean-acne house for people who are tired of stripping benzoyl theater. Meltdown oil treatments, glow kits, and back-to-school edits with short, readable labels — plant-forward, teen-friendly, and built to calm skin without a chemical peel in a bottle.",
    location: "Canada",
    founded: 2017,
    categories: ["skincare"],
    accent: "#E27D60",
    rating: 4.7,
    reviewCount: 4100,
    followerCount: 88000,
    websiteUrl: "https://www.meetblume.com",
    logoUrl: "/brands/blume.svg",
  },
  {
    id: "c678",
    slug: "akamai",
    name: "Akamai",
    tagline: "Mineral toothpowder, 3-in-1 wash bars, and fulvic skin fuel",
    story: "Personal care, radically simplified: refillable mineral toothpowder with clays and fulvic minerals, an organic 3-in-1 bar for wash/shave/shampoo, and a six-ingredient skin-and-hair oil. Fewer bottles, no plastic toothpaste tube, no 40-ingredient mystery paste.",
    location: "United States",
    founded: 2016,
    categories: ["oral","hair","skincare"],
    accent: "#2C5F4E",
    rating: 4.8,
    reviewCount: 2700,
    followerCount: 41000,
    websiteUrl: "https://akamaibasics.com",
    logoUrl: "/brands/akamai.png",
  },
  {
    id: "c679",
    slug: "holos",
    name: "HOLOS",
    tagline: "Organic plant-protein muesli bars and jars, made in Canada",
    story: "A Montreal kitchen of whole-grain muesli, plant protein, seeds, and probiotics in crunchy peanut-butter bars and jars. Gluten-free, recyclable packaging, and a breakfast-as-fuel ritual that skips the candy-bar protein aisle.",
    location: "Montreal, Canada",
    founded: 2016,
    categories: ["protein"],
    accent: "#C45C26",
    rating: 4.7,
    reviewCount: 1900,
    followerCount: 32000,
    websiteUrl: "https://liveholos.com",
    logoUrl: "/brands/holos.svg",
  },
  {
    id: "c680",
    slug: "mineral-fusion",
    name: "Mineral Fusion",
    tagline: "Mineral-forward skincare and sun care from a clean-color house",
    story: "A mineral-cosmetics kitchen that also pours skincare and sun care with short, readable labels. Less drugstore chemical theater, more zinc-and-botanical thinking for skin that wants minerals, not a 40-ingredient foundation fog.",
    location: "United States",
    founded: 2003,
    categories: ["skincare","sunscreen"],
    accent: "#8B7355",
    rating: 4.5,
    reviewCount: 2800,
    followerCount: 45000,
    websiteUrl: "https://www.mineralfusion.com",
    logoUrl: "/brands/mineral-fusion.png",
  },
];
