import type { Brand, CommunityPost, Product, Review } from "./types";

export const categories = [
  { id: "sunscreen", label: "Sunscreen", mark: "☀" },
  { id: "deodorant", label: "Deodorant", mark: "✦" },
  { id: "protein", label: "Protein", mark: "◎" },
  { id: "electrolytes", label: "Electrolytes", mark: "⬡" },
  { id: "skincare", label: "Skincare", mark: "◇" },
  { id: "hair", label: "Hair care", mark: "∿" },
  { id: "oral", label: "Oral care", mark: "○" },
] as const;

export const brands: Brand[] = [
  {
    id: "b0",
    slug: "freaks-of-nature",
    name: "Freaks of Nature",
    tagline: "Mineral protection for skin that actually lives outside",
    story:
      "Clean, 100% mineral formulas built for real life outside — sunscreen, barrier care, and everyday essentials without chemical filters or greasy residue.",
    location: "United States",
    founded: 2020,
    categories: ["sunscreen","deodorant","skincare"],
    accent: "#2F6F5E",
    rating: 4.8,
    reviewCount: 444,
    followerCount: 0,
  },
  {
    id: "b7",
    slug: "humble-brands",
    name: "Humble Brands",
    tagline: "Aluminum-free deodorant with real essential oil scents",
    story:
      "Santa Fe-born clean deodorant built around essential oils, baking soda and baking-soda-free formulas, plus plastic-free paperboard options - everyday odor protection without aluminum.",
    location: "Santa Fe, NM",
    founded: 2015,
    categories: ["deodorant", "skincare"],
    accent: "#6A7F5C",
    rating: 4.7,
    reviewCount: 6756,
    followerCount: 0,
  },
  {
    id: "b1",
    slug: "solara-lab",
    name: "Solara Lab",
    tagline: "SPF that feels like a second skin",
    story:
      "Two surfers in San Diego got tired of sticky, chalky sunscreen. Solara Lab makes mineral formulas that disappear into skin and still hold up after a full day outside",
    location: "San Diego, CA",
    founded: 2019,
    categories: ["sunscreen", "skincare"],
    accent: "#F4A261",
    rating: 4.8,
    reviewCount: 312,
    followerCount: 1840,
  },
  {
    id: "b2",
    slug: "pine-and-alum",
    name: "Pine & Alum",
    tagline: "Deodorant that actually lasts",
    story:
      "Born in a Portland garage after one too many aluminum-free fails. Pine & Alum blends botanicals with smart mineral salts — no white cast, no mystery chemicals",
    location: "Portland, OR",
    founded: 2021,
    categories: ["deodorant"],
    accent: "#2A9D8F",
    rating: 4.6,
    reviewCount: 528,
    followerCount: 3201,
  },
  {
    id: "b3",
    slug: "nourish-co",
    name: "Nourish Co",
    tagline: "Clean protein, zero chalk",
    story:
      "A small batch protein brand that sources pea and hemp from regenerative farms. Smooth shakes, transparent labels, flavors that taste like food — not candy",
    location: "Boulder, CO",
    founded: 2020,
    categories: ["protein"],
    accent: "#E76F51",
    rating: 4.7,
    reviewCount: 891,
    followerCount: 5120,
  },
  {
    id: "b4",
    slug: "dewdrop",
    name: "Dewdrop",
    tagline: "Skin that drinks water",
    story:
      "Minimalist skincare from a Brooklyn chemist who believes fewer ingredients done right beat a 40-step routine. Hydration-first, fragrance-free options galore",
    location: "Brooklyn, NY",
    founded: 2018,
    categories: ["skincare"],
    accent: "#7EB8D4",
    rating: 4.9,
    reviewCount: 1204,
    followerCount: 8900,
  },
  {
    id: "b5",
    slug: "root-ritual",
    name: "Root Ritual",
    tagline: "Hair care rooted in botanicals",
    story:
      "Scalp-first hair care using cold-pressed oils and fermented botanicals. Made in small batches on a family farm outside Asheville",
    location: "Asheville, NC",
    founded: 2022,
    categories: ["hair"],
    accent: "#9B7EBD",
    rating: 4.5,
    reviewCount: 267,
    followerCount: 1450,
  },
  {
    id: "b6",
    slug: "mint-theory",
    name: "Mint Theory",
    tagline: "Toothpaste you can pronounce",
    story:
      "Hydroxyapatite toothpaste without the plastic tube guilt. Refillable glass jars, gentle whitening, flavors that feel grown-up",
    location: "Austin, TX",
    founded: 2023,
    categories: ["oral"],
    accent: "#45B69C",
    rating: 4.4,
    reviewCount: 189,
    followerCount: 980,
  },
];

export const products: Product[] = [
  {
    id: "fon1",
    slug: "solar-shield-spray",
    brandId: "b0",
    name: "Solar Shield SPF 30 Spray",
    category: "sunscreen",
    price: 26,
    description:
      "Full-body mineral protection",
    ingredients: [
      "Zinc Oxide",
      "Aloe Barbendensis Leaf Juice",
      "Aqua / Water",
      "Bambusa Arundinacea (Bamboo) Stem Extract",
      "Camellia Sinensis (Japanese Green Tea) Leaf Extract",
      "Caprylic / Capric Triglyceride",
      "Dilauryl Citrate",
      "Ethylhexylglycerin",
      "Gluconolactone",
      "Glycerin",
      "Hydrogenated Methyl Abietate",
      "Isopropyl Palmitate",
      "Lauryl Glucoside",
      "Leuconostoc / Radish Root Ferment Filtrate",
      "Lonicera Caprifolium (Honeysuckle) Flower Extract",
      "Lonicera Japonica (Honeysuckle) Flower Extract",
      "Methylcellulose",
      "Octyldodecyl Citrate Crosspolymer",
      "Phenoxyethanol",
      "Polyglyceryl-4 Laurate",
      "Populus Tremuloides Bark Extract",
      "Simmondsia Chinensis (Jojoba) Seed Oil",
      "Sodium Lauryl Glucose Carboxylate",
      "Sodium Phytate",
      "Sodium Stearoyl Glutamate",
      "Sorbitan Laurate",
      "Tocopherol",
      "Xanthan Gum"
    ],
    freeFrom: ["Fragrance","Oxybenzone","Octinoxate"],
    rating: 4.9,
    reviewCount: 117,
    accent: "#2F6F5E",
    badge: "New",
    imageUrl: "https://freaksofnature.com/cdn/shop/files/3D_SPRAY_E-COMM.png?v=1777037746&width=1920",
  },
  {
    id: "fon2",
    slug: "sun-stick-spf50",
    brandId: "b0",
    name: "Peak Performance Sun Stick SPF50",
    category: "sunscreen",
    price: 24,
    description:
      "100% Mineral Sunscreen High-performance, lightweight non-greasy, broad spectrum protection for the long haul.",
    ingredients: [
      "Zinc Oxide",
      "Helianthus Annuus (Sunflower) Seed Wax",
      "Isoamyl Laurate",
      "Ethylhexyl Olivate",
      "Caprylic/Capric Triglyceride",
      "C13-15 Alkane",
      "Polyhydroxystearic Acid",
      "Oryza Sativa (Rice Bran) Oil",
      "Quaternium-90 Bentonite",
      "Capryloyl Glycerin/Sebacic Acid Copolymer",
      "Prototheca Moriformis (Microalgae) Oil",
      "Theobroma Cacao (Cocoa) Seed Butter",
      "Isostearic Acid",
      "Lecithin",
      "Polyglyceryl-3 Polyricinoleate",
      "Triethyl Citrate",
      "Squalane",
      "Physalis Angulata (Ground Cherry) Extract",
      "Rhododendron Ferrugineum (Alpenrose) Extract",
      "Undaria Pinnatifida (Wakame) Extract",
      "Saccharomyces Ferment",
      "Laurel Lysine",
      "Tocopherol Acetate",
      "Tocopherol"
    ],
    freeFrom: ["Fragrance","Oxybenzone","Octinoxate"],
    rating: 4.9,
    reviewCount: 189,
    accent: "#2F6F5E",
    imageUrl: "https://freaksofnature.com/cdn/shop/files/STICK-web-optimized-transparent.png?v=1775474333&width=1920",
  },
  {
    id: "fon3",
    slug: "everyday-endurance-deodorant",
    brandId: "b0",
    name: "Everyday Endurance Deodorant",
    category: "deodorant",
    price: 20,
    description:
      "All natural with 48-hour odor protection",
    ingredients: [
      "Caprylic/Capric Triglyceride",
      "Maranta Arundinacea (Arrowroot) Root Extract",
      "Helianthus Annuus (Sunflower) Seed Oil",
      "Ethylhexyl Palmitate",
      "Myrica Pubescens (Laurel) Fruit Wax",
      "Theobroma Cacao (Cocoa) Seed Butter",
      "Triethyl Citrate",
      "Bambusa Arundinacea (Bamboo) Stem Extract",
      "Zinc Ricinoleate",
      "Bentonite",
      "Glyceryl Laurate",
      "Helianthus Annuus (Sunflower) Seed Wax",
      "Silica",
      "Oryza Sativa (Rice) Bran Wax",
      "Citronellyl Methylcrotonate",
      "Tocopheryl Acetate",
      "Fragrance (Parfum)",
      "Chromium Hydroxide Green (CI 77289)"
    ],
    freeFrom: [],
    rating: 4.2,
    reviewCount: 55,
    accent: "#2F6F5E",
    imageUrl: "https://freaksofnature.com/cdn/shop/files/Single_Deo.png?v=1776275794&width=1920",
  },
  {
    id: "fon4",
    slug: "jumbo-sun-stick",
    brandId: "b0",
    name: "Peak Performance Jumbo Sun Stick",
    category: "sunscreen",
    price: 44,
    description:
      "100% Mineral Sunscreen",
    ingredients: [
      "Zinc Oxide",
      "Helianthus Annuus (Sunflower) Seed Wax",
      "Isoamyl Laurate",
      "Ethylhexyl Olivate",
      "Caprylic/Capric Triglyceride",
      "C13-15 Alkane",
      "Polyhydroxystearic Acid",
      "Oryza Sativa (Rice Bran) Oil",
      "Quaternium-90 Bentonite",
      "Capryloyl Glycerin/Sebacic Acid Copolymer",
      "Prototheca Moriformis (Microalgae) Oil",
      "Theobroma Cacao (Cocoa) Seed Butter",
      "Isostearic Acid",
      "Lecithin",
      "Polyglyceryl-3 Polyricinoleate",
      "Triethyl Citrate",
      "Squalane",
      "Physalis Angulata (Ground Cherry) Extract",
      "Rhododendron Ferrugineum (Alpenrose) Extract",
      "Undaria Pinnatifida (Wakame) Extract",
      "Saccharomyces Ferment",
      "Laurel Lysine",
      "Tocopherol Acetate",
      "Tocopherol"
    ],
    freeFrom: ["Fragrance","Oxybenzone","Octinoxate"],
    rating: 4.9,
    reviewCount: 189,
    accent: "#2F6F5E",
    imageUrl: "https://freaksofnature.com/cdn/shop/files/3D_STICK-SPF50_L_E-COMM.png?v=1776776007&width=1920",
  },
  {
    id: "fon5",
    slug: "peak-performance-sunscreen",
    brandId: "b0",
    name: "Peak Performance SPF50",
    category: "sunscreen",
    price: 38,
    description:
      "100% Mineral Sunscreen High-performance, lightweight non-greasy, broad spectrum protection for the long haul.",
    ingredients: [
      "Zinc Oxide",
      "Titanium Dioxide",
      "Water",
      "Coco-Caprylate/Caprate",
      "Caprylic/Capric Triglyceride",
      "Maleated Soybean Oil Glyceryl/Octyldodecanol Esters",
      "Polyglyceryl-4 Diisostearate/Polyhydroxystearate/Sebacate",
      "Propanediol",
      "Stearyl/Octyldodecyl Citrate Crosspolymer",
      "Copernicia Cerifera (Carnauba) Wax",
      "Bentonite",
      "Methylheptylglycerin",
      "Squalane",
      "Sr-wasp spider polypeptide-1 oligopeptide-178",
      "Porphyra Umbilicalis Extract Aqua",
      "Cetearyl Olivate",
      "Sorbitan Olivate",
      "Polyhydroxystearic Acid",
      "Polyricinoleic acid",
      "Glycerin",
      "Xanthan Gum",
      "Cetyl Alcohol",
      "Pongamia Pinnata Seed Extract",
      "Caprylhydroxamic Acid",
      "Oryza Sativa (Rice) Bran Wax",
      "DL-Alpha Tocopherol",
      "Stearic Acid",
      "Sodium Phytate"
    ],
    freeFrom: ["Fragrance","Oxybenzone","Octinoxate"],
    rating: 4.8,
    reviewCount: 76,
    accent: "#2F6F5E",
    imageUrl: "https://freaksofnature.com/cdn/shop/files/SPF50-web-optimized-transparent.png?v=1743441572&width=1920",
  },
  {
    id: "fon6",
    slug: "deeper-dive-moisturizer",
    brandId: "b0",
    name: "Deeper Dive Hydrator",
    category: "skincare",
    price: 48,
    description:
      "Ultralight Moisturizer A deeper moisture that strengthens your skin barrier.",
    ingredients: [
      "Squalane",
      "Avena Sativa (Oat) Kernel Oil",
      "Dextrin Palmitate",
      "Plukenetia Volubilis (Sacha Inchi) Seed Oil",
      "Simmondsia Chinensis (Jojoba) Seed Oil",
      "Padina Pavonica Thallus Extract",
      "Bacillus Ferment",
      "Tocopherol"
    ],
    freeFrom: [],
    rating: 5,
    reviewCount: 62,
    accent: "#2F6F5E",
    imageUrl: "https://freaksofnature.com/cdn/shop/files/HYDRATOR-web-optimized_transparent.png?v=1743441773&width=1920",
  },
  {
    id: "fon7",
    slug: "daily-defender-sunscreen",
    brandId: "b0",
    name: "Daily Defender SPF30",
    category: "sunscreen",
    price: 35,
    description:
      "100% Mineral Sunscreen Lightweight, fast-absorbing, broad spectrum everyday protection.",
    ingredients: [
      "Zinc Oxide",
      "Water",
      "Coco-Caprylate/Caprate",
      "Caprylic/Capric Triglyceride",
      "Polyglyceryl-4 Diisostearate/Polyhydroxystearate/Sebacate",
      "Propanediol",
      "C13-15 Alkane",
      "Squalane",
      "Maleated Soybean Oil Glyceryl/Octyldodecanol Esters",
      "Copernicia Cerifera (Carnauba) Wax",
      "Methylheptylglycerin",
      "Sr-wasp spider polypeptide-1 oligopeptide-178",
      "Bentonite",
      "Polyricinoleic acid",
      "Polyhydroxystearic Acid",
      "Glycerin",
      "Pongamia Pinnata Seed Extract",
      "Xanthan Gum",
      "Caprylhydroxamic Acid",
      "Oryza Sativa (Rice) Bran Wax",
      "DL-Alpha Tocopherol",
      "Sodium Phytate"
    ],
    freeFrom: ["Fragrance","Oxybenzone","Octinoxate"],
    rating: 4.9,
    reviewCount: 99,
    accent: "#2F6F5E",
    imageUrl: "https://freaksofnature.com/cdn/shop/files/SPF30-web-optimized-transparent.png?v=1743441677&width=1920",
  },
  {
    id: "fon8",
    slug: "barrier-balancing-cleanser",
    brandId: "b0",
    name: "Barrier Balancing Face Wash",
    category: "skincare",
    price: 30,
    description:
      "Foaming Gel-to-Oil",
    ingredients: [
      "Glycerin",
      "Sodium Cocoyl Apple Amino Acids",
      "Sucrose Stearate",
      "Betaine",
      "Saccharomyces Ferment",
      "Aspergillus Ferment",
      "Vitis Vinifera (Grape) Seed Oil",
      "Oryza Sativa (Rice) Bran Oil",
      "Squalane",
      "Tocopherol",
      "Avena Sativa (Oat) Kernel Oil",
      "Camellia Oleifera Seed Oil",
      "Spirulina Platensis Extract",
      "Trehalose",
      "Sodium Citrate"
    ],
    freeFrom: ["Fragrance"],
    rating: 4.6,
    reviewCount: 25,
    accent: "#2F6F5E",
    imageUrl: "https://freaksofnature.com/cdn/shop/files/3D_CLEANSER_LIGHTBLUE_E-COMM.png?v=1748386004&width=1920",
  },
  {
    id: "fon9",
    slug: "freaks-full-coverage-bundle",
    brandId: "b0",
    name: "Freaks Full Coverage Bundle",
    category: "sunscreen",
    price: 84,
    description:
      "Jumbo + Original Sun Stick & SPF Spray",
    ingredients: [
      "Zinc Oxide",
      "Helianthus Annuus (Sunflower) Seed Wax",
      "Isoamyl Laurate",
      "Ethylhexyl Olivate",
      "Caprylic/Capric Triglyceride",
      "C13-15 Alkane",
      "Polyhydroxystearic Acid",
      "Oryza Sativa (Rice Bran) Oil",
      "Quaternium-90 Bentonite",
      "Capryloyl Glycerin/Sebacic Acid Copolymer",
      "Prototheca Moriformis (Microalgae) Oil",
      "Theobroma Cacao (Cocoa) Seed Butter",
      "Isostearic Acid",
      "Lecithin",
      "Polyglyceryl-3 Polyricinoleate",
      "Triethyl Citrate",
      "Squalane",
      "Physalis Angulata (Ground Cherry) Extract",
      "Rhododendron Ferrugineum (Alpenrose) Extract",
      "Undaria Pinnatifida (Wakame) Extract",
      "Saccharomyces Ferment",
      "Laurel Lysine",
      "Tocopherol Acetate",
      "Tocopherol",
      "Aloe Barbendensis Leaf Juice",
      "Aqua / Water",
      "Bambusa Arundinacea (Bamboo) Stem Extract",
      "Camellia Sinensis (Japanese Green Tea) Leaf Extract",
      "Caprylic / Capric Triglyceride",
      "Dilauryl Citrate",
      "Ethylhexylglycerin",
      "Gluconolactone",
      "Glycerin",
      "Hydrogenated Methyl Abietate",
      "Isopropyl Palmitate",
      "Lauryl Glucoside",
      "Leuconostoc / Radish Root Ferment Filtrate",
      "Lonicera Caprifolium (Honeysuckle) Flower Extract",
      "Lonicera Japonica (Honeysuckle) Flower Extract",
      "Methylcellulose",
      "Octyldodecyl Citrate Crosspolymer",
      "Phenoxyethanol",
      "Polyglyceryl-4 Laurate",
      "Populus Tremuloides Bark Extract",
      "Simmondsia Chinensis (Jojoba) Seed Oil",
      "Sodium Lauryl Glucose Carboxylate",
      "Sodium Phytate",
      "Sodium Stearoyl Glutamate",
      "Sorbitan Laurate",
      "Xanthan Gum"
    ],
    freeFrom: ["Fragrance","Oxybenzone","Octinoxate"],
    rating: 4.9,
    reviewCount: 301,
    accent: "#2F6F5E",
    imageUrl: "https://freaksofnature.com/cdn/shop/files/STICK_JUMBO_SPRAY_E-COMM-copy1.png?v=1777478755&width=1920",
  },
  {
    id: "fon10",
    slug: "sun-stick-set",
    brandId: "b0",
    name: "Sun Stick Set",
    category: "sunscreen",
    price: 61,
    description:
      "Jumbo + Original Sun Stick",
    ingredients: [
      "Zinc Oxide",
      "Helianthus Annuus (Sunflower) Seed Wax",
      "Isoamyl Laurate",
      "Ethylhexyl Olivate",
      "Caprylic/Capric Triglyceride",
      "C13-15 Alkane",
      "Polyhydroxystearic Acid",
      "Oryza Sativa (Rice Bran) Oil",
      "Quaternium-90 Bentonite",
      "Capryloyl Glycerin/Sebacic Acid Copolymer",
      "Prototheca Moriformis (Microalgae) Oil",
      "Theobroma Cacao (Cocoa) Seed Butter",
      "Isostearic Acid",
      "Lecithin",
      "Polyglyceryl-3 Polyricinoleate",
      "Triethyl Citrate",
      "Squalane",
      "Physalis Angulata (Ground Cherry) Extract",
      "Rhododendron Ferrugineum (Alpenrose) Extract",
      "Undaria Pinnatifida (Wakame) Extract",
      "Saccharomyces Ferment",
      "Laurel Lysine",
      "Tocopherol Acetate",
      "Tocopherol"
    ],
    freeFrom: ["Fragrance","Oxybenzone","Octinoxate"],
    rating: 4.9,
    reviewCount: 189,
    accent: "#2F6F5E",
    imageUrl: "https://freaksofnature.com/cdn/shop/files/STICK_JUMBO_E-COMM-copy.png?v=1777043493&width=1920",
  },
  {
    id: "fon11",
    slug: "body-by-freaks-bundle",
    brandId: "b0",
    name: "Body By Freaks Bundle",
    category: "sunscreen",
    price: 63,
    description:
      "Jumbo SPF50 Sun Stick + SPF 30 Spray",
    ingredients: [
      "Zinc Oxide",
      "Helianthus Annuus (Sunflower) Seed Wax",
      "Isoamyl Laurate",
      "Ethylhexyl Olivate",
      "Caprylic/Capric Triglyceride",
      "C13-15 Alkane",
      "Polyhydroxystearic Acid",
      "Oryza Sativa (Rice Bran) Oil",
      "Quaternium-90 Bentonite",
      "Capryloyl Glycerin/Sebacic Acid Copolymer",
      "Prototheca Moriformis (Microalgae) Oil",
      "Theobroma Cacao (Cocoa) Seed Butter",
      "Isostearic Acid",
      "Lecithin",
      "Polyglyceryl-3 Polyricinoleate",
      "Triethyl Citrate",
      "Squalane",
      "Physalis Angulata (Ground Cherry) Extract",
      "Rhododendron Ferrugineum (Alpenrose) Extract",
      "Undaria Pinnatifida (Wakame) Extract",
      "Saccharomyces Ferment",
      "Laurel Lysine",
      "Tocopherol Acetate",
      "Tocopherol",
      "Aloe Barbendensis Leaf Juice",
      "Aqua / Water",
      "Bambusa Arundinacea (Bamboo) Stem Extract",
      "Camellia Sinensis (Japanese Green Tea) Leaf Extract",
      "Caprylic / Capric Triglyceride",
      "Dilauryl Citrate",
      "Ethylhexylglycerin",
      "Gluconolactone",
      "Glycerin",
      "Hydrogenated Methyl Abietate",
      "Isopropyl Palmitate",
      "Lauryl Glucoside",
      "Leuconostoc / Radish Root Ferment Filtrate",
      "Lonicera Caprifolium (Honeysuckle) Flower Extract",
      "Lonicera Japonica (Honeysuckle) Flower Extract",
      "Methylcellulose",
      "Octyldodecyl Citrate Crosspolymer",
      "Phenoxyethanol",
      "Polyglyceryl-4 Laurate",
      "Populus Tremuloides Bark Extract",
      "Simmondsia Chinensis (Jojoba) Seed Oil",
      "Sodium Lauryl Glucose Carboxylate",
      "Sodium Phytate",
      "Sodium Stearoyl Glutamate",
      "Sorbitan Laurate",
      "Xanthan Gum"
    ],
    freeFrom: ["Fragrance","Oxybenzone","Octinoxate"],
    rating: 4.9,
    reviewCount: 163,
    accent: "#2F6F5E",
    imageUrl: "https://freaksofnature.com/cdn/shop/files/BODY_BY_FREAKS.png?v=1777478348&width=1920",
  },
  {
    id: "fon12",
    slug: "freak-family-pack-v3",
    brandId: "b0",
    name: "Freak Family Pack",
    category: "skincare",
    price: 193.5,
    description:
      "Full Freak Assortment Strengthen. Protect. Repair. Repeat.",
    ingredients: [
      "Zinc Oxide",
      "Water",
      "Coco-Caprylate/Caprate",
      "Caprylic/Capric Triglyceride",
      "Polyglyceryl-4 Diisostearate/Polyhydroxystearate/Sebacate",
      "Propanediol",
      "C13-15 Alkane",
      "Squalane",
      "Maleated Soybean Oil Glyceryl/Octyldodecanol Esters",
      "Copernicia Cerifera (Carnauba) Wax",
      "Methylheptylglycerin",
      "Sr-wasp spider polypeptide-1 oligopeptide-178",
      "Bentonite",
      "Polyricinoleic acid",
      "Polyhydroxystearic Acid",
      "Glycerin",
      "Pongamia Pinnata Seed Extract",
      "Xanthan Gum",
      "Caprylhydroxamic Acid",
      "Oryza Sativa (Rice) Bran Wax",
      "DL-Alpha Tocopherol",
      "Sodium Phytate",
      "Titanium Dioxide",
      "Stearyl/Octyldodecyl Citrate Crosspolymer",
      "Porphyra Umbilicalis Extract Aqua",
      "Cetearyl Olivate",
      "Sorbitan Olivate",
      "Cetyl Alcohol",
      "Stearic Acid",
      "Helianthus Annuus (Sunflower) Seed Wax",
      "Isoamyl Laurate",
      "Ethylhexyl Olivate",
      "Oryza Sativa (Rice Bran) Oil",
      "Quaternium-90 Bentonite",
      "Capryloyl Glycerin/Sebacic Acid Copolymer",
      "Prototheca Moriformis (Microalgae) Oil",
      "Theobroma Cacao (Cocoa) Seed Butter",
      "Isostearic Acid",
      "Lecithin",
      "Polyglyceryl-3 Polyricinoleate",
      "Triethyl Citrate",
      "Physalis Angulata (Ground Cherry) Extract",
      "Rhododendron Ferrugineum (Alpenrose) Extract",
      "Undaria Pinnatifida (Wakame) Extract",
      "Saccharomyces Ferment",
      "Laurel Lysine",
      "Tocopherol Acetate",
      "Tocopherol",
      "Avena Sativa (Oat) Kernel Oil",
      "Dextrin Palmitate",
      "Plukenetia Volubilis (Sacha Inchi) Seed Oil",
      "Simmondsia Chinensis (Jojoba) Seed Oil",
      "Padina Pavonica Thallus Extract",
      "Bacillus Ferment",
      "Sodium Cocoyl Apple Amino Acids",
      "Sucrose Stearate",
      "Betaine",
      "Aspergillus Ferment",
      "Vitis Vinifera (Grape) Seed Oil",
      "Oryza Sativa (Rice) Bran Oil",
      "Camellia Oleifera Seed Oil",
      "Spirulina Platensis Extract",
      "Trehalose",
      "Sodium Citrate",
      "Maranta Arundinacea (Arrowroot) Root Extract",
      "Helianthus Annuus (Sunflower) Seed Oil",
      "Ethylhexyl Palmitate",
      "Myrica Pubescens (Laurel) Fruit Wax",
      "Bambusa Arundinacea (Bamboo) Stem Extract",
      "Zinc Ricinoleate",
      "Glyceryl Laurate",
      "Silica",
      "Citronellyl Methylcrotonate",
      "Tocopheryl Acetate",
      "Fragrance (Parfum)",
      "Chromium Hydroxide Green (CI 77289)"
    ],
    freeFrom: ["Oxybenzone","Octinoxate"],
    rating: 4.8,
    reviewCount: 444,
    accent: "#2F6F5E",
    imageUrl: "https://freaksofnature.com/cdn/shop/files/FreakFamily_Transparent.png?v=1761686298&width=2400",
  },
  {
    id: "fon13",
    slug: "freak-trio",
    brandId: "b0",
    name: "Freak Trio",
    category: "sunscreen",
    price: 108.9,
    description:
      "SPF50 Sunscreen & SPF30 Sunscreen & Hydrator Strengthen. Protect. Repair. Repeat.",
    ingredients: [
      "Zinc Oxide",
      "Water",
      "Coco-Caprylate/Caprate",
      "Caprylic/Capric Triglyceride",
      "Polyglyceryl-4 Diisostearate/Polyhydroxystearate/Sebacate",
      "Propanediol",
      "C13-15 Alkane",
      "Squalane",
      "Maleated Soybean Oil Glyceryl/Octyldodecanol Esters",
      "Copernicia Cerifera (Carnauba) Wax",
      "Methylheptylglycerin",
      "Sr-wasp spider polypeptide-1 oligopeptide-178",
      "Bentonite",
      "Polyricinoleic acid",
      "Polyhydroxystearic Acid",
      "Glycerin",
      "Pongamia Pinnata Seed Extract",
      "Xanthan Gum",
      "Caprylhydroxamic Acid",
      "Oryza Sativa (Rice) Bran Wax",
      "DL-Alpha Tocopherol",
      "Sodium Phytate",
      "Titanium Dioxide",
      "Stearyl/Octyldodecyl Citrate Crosspolymer",
      "Porphyra Umbilicalis Extract Aqua",
      "Cetearyl Olivate",
      "Sorbitan Olivate",
      "Cetyl Alcohol",
      "Stearic Acid",
      "Avena Sativa (Oat) Kernel Oil",
      "Dextrin Palmitate",
      "Plukenetia Volubilis (Sacha Inchi) Seed Oil",
      "Simmondsia Chinensis (Jojoba) Seed Oil",
      "Padina Pavonica Thallus Extract",
      "Bacillus Ferment",
      "Tocopherol"
    ],
    freeFrom: ["Oxybenzone","Octinoxate"],
    rating: 4.9,
    reviewCount: 247,
    accent: "#2F6F5E",
    imageUrl: "https://freaksofnature.com/cdn/shop/files/SPF50-_-SPF30-_-HYDRATOR-web-optimized-transparent_2.png?v=1743566002&width=1920",
  },
  {
    id: "fon14",
    slug: "peak-performance-duo",
    brandId: "b0",
    name: "Peak Performance Duo",
    category: "sunscreen",
    price: 55.8,
    description:
      "SPF50 Sunscreen & SPF50 Stick High-performance, lightweight non-greasy, broad spectrum protection for the long haul.",
    ingredients: [
      "Zinc Oxide",
      "Titanium Dioxide",
      "Water",
      "Coco-Caprylate/Caprate",
      "Caprylic/Capric Triglyceride",
      "Maleated Soybean Oil Glyceryl/Octyldodecanol Esters",
      "Polyglyceryl-4 Diisostearate/Polyhydroxystearate/Sebacate",
      "Propanediol",
      "Stearyl/Octyldodecyl Citrate Crosspolymer",
      "Copernicia Cerifera (Carnauba) Wax",
      "Bentonite",
      "Methylheptylglycerin",
      "Squalane",
      "Sr-wasp spider polypeptide-1 oligopeptide-178",
      "Porphyra Umbilicalis Extract Aqua",
      "Cetearyl Olivate",
      "Sorbitan Olivate",
      "Polyhydroxystearic Acid",
      "Polyricinoleic acid",
      "Glycerin",
      "Xanthan Gum",
      "Cetyl Alcohol",
      "Pongamia Pinnata Seed Extract",
      "Caprylhydroxamic Acid",
      "Oryza Sativa (Rice) Bran Wax",
      "DL-Alpha Tocopherol",
      "Stearic Acid",
      "Sodium Phytate",
      "Helianthus Annuus (Sunflower) Seed Wax",
      "Isoamyl Laurate",
      "Ethylhexyl Olivate",
      "C13-15 Alkane",
      "Oryza Sativa (Rice Bran) Oil",
      "Quaternium-90 Bentonite",
      "Capryloyl Glycerin/Sebacic Acid Copolymer",
      "Prototheca Moriformis (Microalgae) Oil",
      "Theobroma Cacao (Cocoa) Seed Butter",
      "Isostearic Acid",
      "Lecithin",
      "Polyglyceryl-3 Polyricinoleate",
      "Triethyl Citrate",
      "Physalis Angulata (Ground Cherry) Extract",
      "Rhododendron Ferrugineum (Alpenrose) Extract",
      "Undaria Pinnatifida (Wakame) Extract",
      "Saccharomyces Ferment",
      "Laurel Lysine",
      "Tocopherol Acetate",
      "Tocopherol"
    ],
    freeFrom: ["Fragrance","Oxybenzone","Octinoxate"],
    rating: 4.8,
    reviewCount: 241,
    accent: "#2F6F5E",
    imageUrl: "https://freaksofnature.com/cdn/shop/files/SPF50-_-STICK-web-optimized-transparent_V2.png?v=1743565960&width=1920",
  },
  {
    id: "fon15",
    slug: "balanced-skin-set",
    brandId: "b0",
    name: "Balanced Skin Set",
    category: "skincare",
    price: 70,
    description:
      "Deeper Dive & Barrier Balancing Face Wash",
    ingredients: [
      "Squalane",
      "Avena Sativa (Oat) Kernel Oil",
      "Dextrin Palmitate",
      "Plukenetia Volubilis (Sacha Inchi) Seed Oil",
      "Simmondsia Chinensis (Jojoba) Seed Oil",
      "Padina Pavonica Thallus Extract",
      "Bacillus Ferment",
      "Tocopherol",
      "Glycerin",
      "Sodium Cocoyl Apple Amino Acids",
      "Sucrose Stearate",
      "Betaine",
      "Saccharomyces Ferment",
      "Aspergillus Ferment",
      "Vitis Vinifera (Grape) Seed Oil",
      "Oryza Sativa (Rice) Bran Oil",
      "Camellia Oleifera Seed Oil",
      "Spirulina Platensis Extract",
      "Trehalose",
      "Sodium Citrate"
    ],
    freeFrom: ["Fragrance"],
    rating: 4.9,
    reviewCount: 101,
    accent: "#2F6F5E",
    imageUrl: "https://freaksofnature.com/cdn/shop/files/3D_HYDRATOR_CLEANSER-LIGHTBLUE_E-COMM.png?v=1748543058&width=1920",
  },
  {
    id: "fon16",
    slug: "daily-system",
    brandId: "b0",
    name: "Daily System",
    category: "sunscreen",
    price: 74.7,
    description:
      "SPF30 Sunscreen & Hydrator Strengthen. Protect. Repair. Repeat.",
    ingredients: [
      "Zinc Oxide",
      "Water",
      "Coco-Caprylate/Caprate",
      "Caprylic/Capric Triglyceride",
      "Polyglyceryl-4 Diisostearate/Polyhydroxystearate/Sebacate",
      "Propanediol",
      "C13-15 Alkane",
      "Squalane",
      "Maleated Soybean Oil Glyceryl/Octyldodecanol Esters",
      "Copernicia Cerifera (Carnauba) Wax",
      "Methylheptylglycerin",
      "Sr-wasp spider polypeptide-1 oligopeptide-178",
      "Bentonite",
      "Polyricinoleic acid",
      "Polyhydroxystearic Acid",
      "Glycerin",
      "Pongamia Pinnata Seed Extract",
      "Xanthan Gum",
      "Caprylhydroxamic Acid",
      "Oryza Sativa (Rice) Bran Wax",
      "DL-Alpha Tocopherol",
      "Sodium Phytate",
      "Avena Sativa (Oat) Kernel Oil",
      "Dextrin Palmitate",
      "Plukenetia Volubilis (Sacha Inchi) Seed Oil",
      "Simmondsia Chinensis (Jojoba) Seed Oil",
      "Padina Pavonica Thallus Extract",
      "Bacillus Ferment",
      "Tocopherol"
    ],
    freeFrom: ["Oxybenzone","Octinoxate"],
    rating: 4.9,
    reviewCount: 191,
    accent: "#2F6F5E",
    imageUrl: "https://freaksofnature.com/cdn/shop/files/SPF30-_-HYDRATOR-web-optimized-transparent_V2.png?v=1743566064&width=1920",
  },
  {
    id: "fon17",
    slug: "endurance-system",
    brandId: "b0",
    name: "Endurance System",
    category: "sunscreen",
    price: 77.4,
    description:
      "SPF50 Sunscreen & Hydrator Strengthen. Protect. Repair. Repeat.",
    ingredients: [
      "Zinc Oxide",
      "Titanium Dioxide",
      "Water",
      "Coco-Caprylate/Caprate",
      "Caprylic/Capric Triglyceride",
      "Maleated Soybean Oil Glyceryl/Octyldodecanol Esters",
      "Polyglyceryl-4 Diisostearate/Polyhydroxystearate/Sebacate",
      "Propanediol",
      "Stearyl/Octyldodecyl Citrate Crosspolymer",
      "Copernicia Cerifera (Carnauba) Wax",
      "Bentonite",
      "Methylheptylglycerin",
      "Squalane",
      "Sr-wasp spider polypeptide-1 oligopeptide-178",
      "Porphyra Umbilicalis Extract Aqua",
      "Cetearyl Olivate",
      "Sorbitan Olivate",
      "Polyhydroxystearic Acid",
      "Polyricinoleic acid",
      "Glycerin",
      "Xanthan Gum",
      "Cetyl Alcohol",
      "Pongamia Pinnata Seed Extract",
      "Caprylhydroxamic Acid",
      "Oryza Sativa (Rice) Bran Wax",
      "DL-Alpha Tocopherol",
      "Stearic Acid",
      "Sodium Phytate",
      "Avena Sativa (Oat) Kernel Oil",
      "Dextrin Palmitate",
      "Plukenetia Volubilis (Sacha Inchi) Seed Oil",
      "Simmondsia Chinensis (Jojoba) Seed Oil",
      "Padina Pavonica Thallus Extract",
      "Bacillus Ferment",
      "Tocopherol"
    ],
    freeFrom: ["Oxybenzone","Octinoxate"],
    rating: 4.9,
    reviewCount: 150,
    accent: "#2F6F5E",
    imageUrl: "https://freaksofnature.com/cdn/shop/files/SPF50-_-HYDRATOR-web-optimized-transparent_V2.png?v=1743566045&width=1920",
  },
  {
    id: "fon18",
    slug: "endurance-system-sport-mode",
    brandId: "b0",
    name: "Endurance System -- Sport Mode",
    category: "sunscreen",
    price: 64.2,
    description:
      "SPF50 Stick & Hydrator Strengthen. Protect. Repair. Repeat.",
    ingredients: [
      "Zinc Oxide",
      "Helianthus Annuus (Sunflower) Seed Wax",
      "Isoamyl Laurate",
      "Ethylhexyl Olivate",
      "Caprylic/Capric Triglyceride",
      "C13-15 Alkane",
      "Polyhydroxystearic Acid",
      "Oryza Sativa (Rice Bran) Oil",
      "Quaternium-90 Bentonite",
      "Capryloyl Glycerin/Sebacic Acid Copolymer",
      "Prototheca Moriformis (Microalgae) Oil",
      "Theobroma Cacao (Cocoa) Seed Butter",
      "Isostearic Acid",
      "Lecithin",
      "Polyglyceryl-3 Polyricinoleate",
      "Triethyl Citrate",
      "Squalane",
      "Physalis Angulata (Ground Cherry) Extract",
      "Rhododendron Ferrugineum (Alpenrose) Extract",
      "Undaria Pinnatifida (Wakame) Extract",
      "Saccharomyces Ferment",
      "Laurel Lysine",
      "Tocopherol Acetate",
      "Tocopherol"
    ],
    freeFrom: ["Fragrance","Oxybenzone","Octinoxate"],
    rating: 4.9,
    reviewCount: 205,
    accent: "#2F6F5E",
    imageUrl: "https://freaksofnature.com/cdn/shop/files/HYDRATOR-_-STICK-web-optimized-transparent_V2.png?v=1743565980&width=1920",
  },
  {
    id: "fon19",
    slug: "deo-duo-bundle",
    brandId: "b0",
    name: "Everyday Endurance Duo",
    category: "deodorant",
    price: 36,
    description:
      "Two all natural scents with 48-hour odor protection",
    ingredients: [
      "Caprylic/Capric Triglyceride",
      "Maranta Arundinacea (Arrowroot) Root Extract",
      "Helianthus Annuus (Sunflower) Seed Oil",
      "Ethylhexyl Palmitate",
      "Myrica Pubescens (Laurel) Fruit Wax",
      "Theobroma Cacao (Cocoa) Seed Butter",
      "Triethyl Citrate",
      "Bambusa Arundinacea (Bamboo) Stem Extract",
      "Zinc Ricinoleate",
      "Bentonite",
      "Glyceryl Laurate",
      "Helianthus Annuus (Sunflower) Seed Wax",
      "Silica",
      "Oryza Sativa (Rice) Bran Wax",
      "Citronellyl Methylcrotonate",
      "Tocopheryl Acetate",
      "Fragrance (Parfum)",
      "Chromium Hydroxide Green (CI 77289)"
    ],
    freeFrom: [],
    rating: 4.2,
    reviewCount: 55,
    accent: "#2F6F5E",
    imageUrl: "https://freaksofnature.com/cdn/shop/files/Duo.png?v=1761526305&width=1920",
  },
  {
    id: "fon20",
    slug: "skin-support-electrolyte",
    brandId: "b0",
    name: "Skin Support Electrolyte",
    category: "skincare",
    price: 55,
    description:
      "Whole-body hydration and protection from the inside out",
    ingredients: [
      "Vitamin A",
      "Vitamin C",
      "Vitamin D",
      "Vitamin E",
      "Vitamin B3",
      "Calcium",
      "Magnesium",
      "Zinc",
      "Chloride",
      "Sodium",
      "Potassium",
      "Astaxanthin",
      "Polypodium leucotomos Leaf Extract",
      "Red Orange (Citrus sinensis) Fruit Extract",
      "Partially Hydrolyzed Guar Gum",
      "Ginger (Zingiber officinale) Root Extract",
      "and Sodium Hyaluronate",
      "Natural Flavors",
      "Citric Acid",
      "Malic Acid",
      "Rebaudioside A (Stevia Leaf Extract)"
    ],
    freeFrom: [],
    rating: 4.9,
    reviewCount: 42,
    accent: "#2F6F5E",
    imageUrl: "https://freaksofnature.com/cdn/shop/files/Update_ProductCard.png?v=1773719331&width=1920",
  },
  {
    id: "fon21",
    slug: "everyday-endurance-trio",
    brandId: "b0",
    name: "Everyday Endurance Trio",
    category: "deodorant",
    price: 51,
    description:
      "Three all natural scents with 48-hour odor protection",
    ingredients: [
      "Caprylic/Capric Triglyceride",
      "Maranta Arundinacea (Arrowroot) Root Extract",
      "Helianthus Annuus (Sunflower) Seed Oil",
      "Ethylhexyl Palmitate",
      "Myrica Pubescens (Laurel) Fruit Wax",
      "Theobroma Cacao (Cocoa) Seed Butter",
      "Triethyl Citrate",
      "Bambusa Arundinacea (Bamboo) Stem Extract",
      "Zinc Ricinoleate",
      "Bentonite",
      "Glyceryl Laurate",
      "Helianthus Annuus (Sunflower) Seed Wax",
      "Silica",
      "Oryza Sativa (Rice) Bran Wax",
      "Citronellyl Methylcrotonate",
      "Tocopheryl Acetate",
      "Fragrance (Parfum)",
      "Chromium Hydroxide Green (CI 77289)"
    ],
    freeFrom: [],
    rating: 4.2,
    reviewCount: 55,
    accent: "#2F6F5E",
    imageUrl: "https://freaksofnature.com/cdn/shop/files/Trio.png?v=1775849441&width=1920",
  },
  {
    id: "hb1",
    slug: "palo-santo-frankincense-deodorant",
    brandId: "b7",
    name: "Palo Santo & Frankincense Deodorant",
    category: "deodorant",
    price: 10.99,
    description:
      "Aluminum-free Deodorant. Scent intensity 5/5 - Bold Masculine.",
    ingredients: [
      "Caprylic/Capric Triglyceride (MCT)",
      "Non-GMO Zea Mays (Corn) Starch",
      "Sodium Bicarbonate (Baking Soda)",
      "Cera Alba (Beeswax)",
      "Dipteryx Odorata (Tonka Bean) Seed Extract",
      "Bursera Graveolens (Palo Santo) Wood Oil",
      "Boswellia Serrata (Frankincense) Oil",
      "Limonene",
      "Coumarin",
      "Linalool"
    ],
    freeFrom: ["Aluminum","Phthalates"],
    rating: 4.7,
    reviewCount: 672,
    accent: "#6A7F5C",
    badge: "Best seller",
    imageUrl: "https://humblebrands.com/cdn/shop/files/250919-Humble-OFFull-PaloSanto_Frankincense-Front-WEB.jpg?v=1762360667&width=800",
  },
  {
    id: "hb2",
    slug: "patchouli-copal-deodorant",
    brandId: "b7",
    name: "Patchouli & Copal Deodorant",
    category: "deodorant",
    price: 10.99,
    description:
      "Aluminum-free Deodorant. Scent intensity 4/5 - Full Gender-neutral.",
    ingredients: [
      "Caprylic/Capric Triglyceride (MCT)",
      "Non-GMO Zea Mays (Corn) Starch",
      "Sodium Bicarbonate (Baking Soda)",
      "Cera Alba (Beeswax)",
      "Dipteryx Odorata (Tonka Bean) Seed Extract",
      "Pogostemon Cablin (Patchouli) Leaf Oil",
      "Copaifera Species (Copal) Resin Oil",
      "Boswellia Serrata (Frankincense) Oil",
      "Limonene",
      "Linalool",
      "Coumarin",
      "Eugenol"
    ],
    freeFrom: ["Aluminum","Phthalates"],
    rating: 4.7,
    reviewCount: 329,
    accent: "#6A7F5C",
    imageUrl: "https://humblebrands.com/cdn/shop/files/250919-Humble-OFFull-Patchouli_Copal-Front-WEB.jpg?v=1762360667&width=800",
  },
  {
    id: "hb3",
    slug: "palo-santo-frankincense-plastic-free-deodorant",
    brandId: "b7",
    name: "Palo Santo & Frankincense Plastic-Free Deodorant",
    category: "deodorant",
    price: 12.99,
    description:
      "Plastic Free Deodorant. Scent intensity 5/5 - Bold Masculine.",
    ingredients: [
      "Caprylic/Capric Triglyceride (MCT)",
      "Non-GMO Zea Mays (Corn) Starch",
      "Sodium Bicarbonate (Baking Soda)",
      "Cera Alba (Beeswax)",
      "Dipteryx Odorata (Tonka Bean) Seed Extract",
      "Bursera Graveolens (Palo Santo) Wood Oil",
      "Boswellia Serrata (Frankincense) Oil",
      "Limonene",
      "Coumarin",
      "Linalool"
    ],
    freeFrom: ["Aluminum","Phthalates"],
    rating: 4.7,
    reviewCount: 668,
    accent: "#6A7F5C",
    badge: "Best seller",
    imageUrl: "https://humblebrands.com/cdn/shop/files/122222_Palo_Santo_Frankincense_Front_Web.jpg?v=1782335013&width=800",
  },
  {
    id: "hb4",
    slug: "moroccan-rose-deodorant",
    brandId: "b7",
    name: "Moroccan Rose Deodorant",
    category: "deodorant",
    price: 10.99,
    description:
      "Aluminum-free Deodorant. Scent intensity 3/5 - Balanced Feminine.",
    ingredients: [
      "Caprylic/Capric Triglyceride (MCT)",
      "Non-GMO Zea Mays (Corn) Starch",
      "Sodium Bicarbonate (Baking Soda)",
      "Cera Alba (Beeswax)",
      "Pelargonium Graveolens (Geranium) Oil",
      "Rosa Damascena (Rose) Extract",
      "Citrus Aurantium Bergamia (Bergamot, Bergaptene Free) Peel Oil",
      "Citral",
      "Citronellol",
      "Eugenol",
      "Geraniol",
      "Limonene",
      "Linalool"
    ],
    freeFrom: ["Aluminum","Phthalates"],
    rating: 4.5,
    reviewCount: 238,
    accent: "#6A7F5C",
    imageUrl: "https://humblebrands.com/cdn/shop/files/250919-Humble-OF_Full-Moroccan_Rose-Front-WEB.jpg?v=1762360667&width=800",
  },
  {
    id: "hb5",
    slug: "black-spruce-deodorant",
    brandId: "b7",
    name: "Black Spruce Deodorant",
    category: "deodorant",
    price: 10.99,
    description:
      "Aluminum-free Deodorant. Scent intensity 4/5 - Full Masculine.",
    ingredients: [
      "Caprylic/Capric Triglyceride (MCT)",
      "Non-GMO Zea Mays (Corn) Starch",
      "Sodium Bicarbonate (Baking Soda)",
      "Cera Alba (Beeswax)",
      "Cistus Ladaniferus (Labdanum) Extract",
      "Picea Mariana (Black Spruce) Oil",
      "Jasminum Grandiflorum (Jasmine) Flower Extract",
      "Limonene",
      "Linalool",
      "Citronellol",
      "Benzyl Benzoate",
      "Geraniol"
    ],
    freeFrom: ["Aluminum","Phthalates"],
    rating: 4.7,
    reviewCount: 145,
    accent: "#6A7F5C",
    imageUrl: "https://humblebrands.com/cdn/shop/files/250919-Humble-OFFull-BlackSpruce-Front-WEB.jpg?v=1762360667&width=800",
  },
  {
    id: "hb6",
    slug: "patchouli-copal-plastic-free-deodorant",
    brandId: "b7",
    name: "Patchouli & Copal Plastic-Free Deodorant",
    category: "deodorant",
    price: 12.99,
    description:
      "Plastic Free Deodorant. Scent intensity 4/5 - Full Gender-neutral.",
    ingredients: [
      "Caprylic/Capric Triglyceride (MCT)",
      "Non-GMO Zea Mays (Corn) Starch",
      "Sodium Bicarbonate (Baking Soda)",
      "Cera Alba (Beeswax)",
      "Dipteryx Odorata (Tonka Bean) Seed Extract",
      "Pogostemon Cablin (Patchouli) Leaf Oil",
      "Copaifera Species (Copal) Resin Oil",
      "Boswellia Serrata (Frankincense) Oil",
      "Limonene",
      "Linalool",
      "Coumarin",
      "Eugenol"
    ],
    freeFrom: ["Aluminum","Phthalates"],
    rating: 4.8,
    reviewCount: 182,
    accent: "#6A7F5C",
    badge: "Community fave",
    imageUrl: "https://humblebrands.com/cdn/shop/files/122222_Patchouli_Copal_Front_Web.jpg?v=1782335013&width=800",
  },
  {
    id: "hb7",
    slug: "mountain-lavender-deodorant",
    brandId: "b7",
    name: "Mountain Lavender Deodorant",
    category: "deodorant",
    price: 10.99,
    description:
      "Aluminum-free Deodorant. Scent intensity 2/5 - Light Feminine.",
    ingredients: [
      "Caprylic/Capric Triglyceride (MCT)",
      "Non-GMO Zea Mays (Corn) Starch",
      "Sodium Bicarbonate (Baking Soda)",
      "Cera Alba (Beeswax)",
      "Lavandula Officinalis (Lavender) Flower Oil",
      "Linalool",
      "Limonene",
      "Coumarin",
      "Geraniol"
    ],
    freeFrom: ["Aluminum","Phthalates"],
    rating: 4.6,
    reviewCount: 209,
    accent: "#6A7F5C",
    imageUrl: "https://humblebrands.com/cdn/shop/files/250919-Humble-OFFull-MountainLavender-Front-WEB.jpg?v=1775084023&width=800",
  },
  {
    id: "hb8",
    slug: "bergamot-ginger-deodorant",
    brandId: "b7",
    name: "Bergamot & Ginger Deodorant",
    category: "deodorant",
    price: 10.99,
    description:
      "Aluminum-free Deodorant. Scent intensity 2/5 - Light Gender-neutral.",
    ingredients: [
      "Caprylic/Capric Triglyceride (MCT)",
      "Non-GMO Zea Mays (Corn) Starch",
      "Sodium Bicarbonate (Baking Soda)",
      "Cera Alba (Beeswax)",
      "Lavandula Officinalis (Lavender) Flower Oil",
      "Linalool",
      "Limonene",
      "Coumarin",
      "Geraniol"
    ],
    freeFrom: ["Aluminum","Phthalates"],
    rating: 4.6,
    reviewCount: 180,
    accent: "#6A7F5C",
    imageUrl: "https://humblebrands.com/cdn/shop/files/250919-Humble-OFFull-Bergamot_Ginger-Front-WEB.jpg?v=1762298058&width=800",
  },
  {
    id: "hb9",
    slug: "rosemary-mint-deodorant",
    brandId: "b7",
    name: "Rosemary & Mint Deodorant",
    category: "deodorant",
    price: 10.99,
    description:
      "Aluminum-free Deodorant. Scent intensity 3/5 - Balanced Gender-neutral.",
    ingredients: [
      "Caprylic/Capric Triglyceride (MCT)",
      "Non-GMO Zea Mays (Corn) Starch",
      "Sodium Bicarbonate (Baking Soda)",
      "Cera Alba (Beeswax)",
      "Rosmarinus Officinalis (Rosemary) Leaf Oil",
      "Origanum Majorana (Marjoram) Flower Oil",
      "Mentha Piperita (Peppermint) Oil",
      "Mentha Spicata (Spearmint) Oil",
      "Cinnamomum Camphora (Ho Wood) Branch/Leaf Oil",
      "Lavandula Officinalis (Lavender) Flower Oil",
      "Geraniol",
      "Limonene",
      "Linalool"
    ],
    freeFrom: ["Aluminum","Phthalates"],
    rating: 4.7,
    reviewCount: 118,
    accent: "#6A7F5C",
    imageUrl: "https://humblebrands.com/cdn/shop/files/250919-Humble-OFFull-Rosemary_Mint-Front-WEB.jpg?v=1762360667&width=800",
  },
  {
    id: "hb10",
    slug: "moroccan-rose-plastic-free-deodorant",
    brandId: "b7",
    name: "Moroccan Rose Plastic-Free Deodorant",
    category: "deodorant",
    price: 12.99,
    description:
      "Plastic Free Deodorant. Scent intensity 3/5 - Balanced Feminine.",
    ingredients: [
      "Caprylic/Capric Triglyceride (MCT)",
      "Non-GMO Zea Mays (Corn) Starch",
      "Sodium Bicarbonate (Baking Soda)",
      "Cera Alba (Beeswax)",
      "Pelargonium Graveolens (Geranium) Oil",
      "Rosa Damascena (Rose) Extract",
      "Citrus Aurantium Bergamia (Bergamot, Bergaptene Free) Peel Oil",
      "Citral",
      "Citronellol",
      "Eugenol",
      "Geraniol",
      "Limonene",
      "Linalool"
    ],
    freeFrom: ["Aluminum","Phthalates"],
    rating: 4.7,
    reviewCount: 668,
    accent: "#6A7F5C",
    badge: "Best seller",
    imageUrl: "https://humblebrands.com/cdn/shop/files/122222_Moroccan_Rose_Front_Web_5a02bdaf-80e8-4bf2-a8ce-3662523d7ffc.jpg?v=1782335725&width=800",
  },
  {
    id: "hb11",
    slug: "bergamot-ginger-plastic-free-deodorant",
    brandId: "b7",
    name: "Bergamot & Ginger Plastic-Free Deodorant",
    category: "deodorant",
    price: 12.99,
    description:
      "Plastic Free Deodorant. Scent intensity 2/5 - Light Gender-neutral.",
    ingredients: [
      "Caprylic/Capric Triglyceride (MCT)",
      "Non-GMO Zea Mays (Corn) Starch",
      "Sodium Bicarbonate (Baking Soda)",
      "Cera Alba (Beeswax)",
      "Zingiber Officinale (Ginger) Root Oil",
      "Citrus Aurantium Bergamia (Bergamot, Bergaptene Free) Peel Oil",
      "Limonene",
      "Linalool",
      "Citral",
      "Geraniol"
    ],
    freeFrom: ["Aluminum","Phthalates"],
    rating: 4.7,
    reviewCount: 138,
    accent: "#6A7F5C",
    imageUrl: "https://humblebrands.com/cdn/shop/files/122222_Bergamont_Ginger_Front_Web.jpg?v=1782324071&width=800",
  },
  {
    id: "hb12",
    slug: "rockrose-cedar-plastic-free-deodorant",
    brandId: "b7",
    name: "Rockrose & Cedar Plastic-Free Deodorant",
    category: "deodorant",
    price: 12.99,
    description:
      "Plastic Free Deodorant. Scent intensity 5/5 - Bold Masculine.",
    ingredients: [
      "Caprylic/Capric Triglyceride (MCT)",
      "Zea Mays (Corn) Starch",
      "Sodium Bicarbonate (Baking Soda)",
      "Cera Alba (Beeswax)",
      "Essential Oil & Botanical Extract for Fragrance: Cistus Ladaniferus (Cistus) Oil",
      "Cedrus Atlantica (Cedarwood) Wood Oil",
      "Elettaria Cardamomum (Cardamom) Seed Oil",
      "Vetiveria Zizanoides (Vetiver) Root Oil",
      "Copaifera Species (Copal) Resin Oil",
      "Pogostemon Cablin (Patchouli) Leaf Oil",
      "Cananga Odorata (Ylang Ylang) Flower Oil",
      "Santalum Austrocaledonicum (Sandalwood) Wood Oil",
      "Piper Nigrum (Black Pepper) Fruit Oil",
      "Eugenia Caryophillus (Clove) Flower Oil",
      "Naturally Occurring in Essential Oils and Botanical Extracts: Limonene",
      "Linalool",
      "Eugenol",
      "Benzyl Benzoate Non-GMO"
    ],
    freeFrom: ["Aluminum","Phthalates"],
    rating: 4.7,
    reviewCount: 668,
    accent: "#6A7F5C",
    badge: "Best seller",
    imageUrl: "https://humblebrands.com/cdn/shop/files/082224_Rockrose_Cedar_Front_Web.jpg?v=1782331812&width=800",
  },
  {
    id: "hb13",
    slug: "lemongrass-sage-deodorant",
    brandId: "b7",
    name: "Lemongrass & Sage Deodorant",
    category: "deodorant",
    price: 10.99,
    description:
      "Aluminum-free Deodorant. Scent intensity 4/5 - Full Gender-neutral.",
    ingredients: [
      "Caprylic/Capric Triglyceride (MCT)",
      "Non-GMO Zea Mays (Corn) Starch",
      "Sodium Bicarbonate (Baking Soda)",
      "Cera Alba (Beeswax)",
      "Citrus Aurantium Bergamia (Bergamot, Bergaptene Free) Peel Oil",
      "Cymbopogon Flexuosus (Lemongrass) Oil",
      "Salvia Officinalis (Sage) Oil",
      "Cymbopogon Winterianus (Citronella) Leaf Oil",
      "Citral",
      "Citronellol",
      "Geraniol",
      "Limonene",
      "Linalool",
      "Eugenol"
    ],
    freeFrom: ["Aluminum","Phthalates"],
    rating: 4.7,
    reviewCount: 124,
    accent: "#6A7F5C",
    imageUrl: "https://humblebrands.com/cdn/shop/files/250919-Humble-OF_Full-Lemongrass_Sage-Front-WEB.jpg?v=1762360667&width=800",
  },
  {
    id: "hb14",
    slug: "sensitive-skin-mountain-lavender-plastic-free-deodorant",
    brandId: "b7",
    name: "Sensitive Skin Mountain Lavender Plastic-Free Deodorant",
    category: "deodorant",
    price: 12.99,
    description:
      "Plastic Free Deodorant. Scent intensity 2/5 - Light Feminine.",
    ingredients: [
      "Caprylic/Capric Triglyceride (MCT)",
      "Non-GMO Zea Mays (Corn) Starch",
      "Magnesium Hydroxide",
      "Euphorbia Cerifera (Candelilla) Wax",
      "Zingiber Officinale (Ginger) Root Oil",
      "Citrus Aurantium Bergamia (Bergamot, Bergaptene Free) Peel Oil",
      "Limonene",
      "Linalool",
      "Citral",
      "Geraniol"
    ],
    freeFrom: ["Aluminum","Baking Soda","Phthalates"],
    rating: 4.7,
    reviewCount: 122,
    accent: "#6A7F5C",
    imageUrl: "https://humblebrands.com/cdn/shop/files/122222_Vegan_Mountain_Lavender_Front_Web.jpg?v=1782336140&width=800",
  },
  {
    id: "hb15",
    slug: "palo-santo-frankincense-travel-size",
    brandId: "b7",
    name: "Palo Santo & Frankincense Travel Size",
    category: "deodorant",
    price: 3.99,
    description:
      "Travel Size Original. Scent intensity 5/5 - Bold Masculine.",
    ingredients: [
      "Caprylic/Capric Triglyceride (MCT)",
      "Non-GMO Zea Mays (Corn) Starch",
      "Sodium Bicarbonate (Baking Soda)",
      "Cera Alba (Beeswax)",
      "Dipteryx Odorata (Tonka Bean) Seed Extract",
      "Bursera Graveolens (Palo Santo) Wood Oil",
      "Boswellia Serrata (Frankincense) Oil",
      "Limonene",
      "Coumarin",
      "Linalool"
    ],
    freeFrom: ["Aluminum","Phthalates"],
    rating: 4.7,
    reviewCount: 672,
    accent: "#6A7F5C",
    badge: "Best seller",
    imageUrl: "https://humblebrands.com/cdn/shop/products/122722_Humble_OriginalDeodorant_PaloSantoFrankincenseTravel_Front_Web_93163f2e-2ad1-4a04-bccb-ee78f6015292.jpg?v=1762457415&width=800",
  },
  {
    id: "hb16",
    slug: "lavender-holy-basil-deodorant",
    brandId: "b7",
    name: "Lavender & Holy Basil Deodorant",
    category: "deodorant",
    price: 10.99,
    description:
      "Aluminum-free Deodorant. Scent intensity 3/5 - Balanced Gender-neutral.",
    ingredients: [
      "Caprylic/Capric Triglyceride (MCT)",
      "Non-GMO Zea Mays (Corn) Starch",
      "Sodium Bicarbonate (Baking Soda)",
      "Cera Alba (Beeswax)",
      "Lavandula Officinalis (Lavender) Flower Oil",
      "Ocimum Sanctum (Holy Basil) Oil",
      "Linalool",
      "Limonene",
      "Eugenol",
      "Geraniol",
      "Coumarin"
    ],
    freeFrom: ["Aluminum","Phthalates"],
    rating: 4.6,
    reviewCount: 104,
    accent: "#6A7F5C",
    imageUrl: "https://humblebrands.com/cdn/shop/files/250919-Humble-OFFull-Lavender_HolyBasil-Front-WEB.jpg?v=1762360667&width=800",
  },
  {
    id: "hb17",
    slug: "baking-soda-free-sensitive-skin-palo-santo-frankincense-deodorant",
    brandId: "b7",
    name: "Baking Soda-Free Sensitive Skin Palo Santo & Frankincense Deodorant",
    category: "deodorant",
    price: 10.99,
    description:
      "Sensitive Skin Deodorant. Scent intensity 5/5 - Bold Masculine.",
    ingredients: [
      "Caprylic/Capric Triglyceride (MCT)",
      "Non-GMO Zea Mays (Corn) Starch",
      "Magnesium Hydroxide",
      "Euphorbia Cerifera (Candelilla) Wax",
      "Zingiber Officinale (Ginger) Root Oil",
      "Citrus Aurantium Bergamia (Bergamot, Bergaptene Free) Peel Oil",
      "Limonene",
      "Linalool",
      "Citral",
      "Geraniol"
    ],
    freeFrom: ["Aluminum","Baking Soda","Phthalates"],
    rating: 4.8,
    reviewCount: 141,
    accent: "#6A7F5C",
    badge: "Community fave",
    imageUrl: "https://humblebrands.com/cdn/shop/files/250919-Humble-VSFull-PaloSanto_Frankincense-Front-WEB.jpg?v=1762360667&width=800",
  },
  {
    id: "hb18",
    slug: "patchouli-copal-soap",
    brandId: "b7",
    name: "Patchouli & Copal Soap",
    category: "skincare",
    price: 7.99,
    description:
      "Moisturizing bar soap - Deep earthy richness with smooth balsamic warmth and soft sweetness.",
    ingredients: [
      "Organic Helianthus Annuus (Sunflower) Seed Oil",
      "Organic Cocos Nucifera (Coconut) Oil",
      "Aqua",
      "Sodium Hydroxide",
      "Organic RSPO Certified Elaeis Guineensis (Palm) Oil",
      "Organic Fair Trade Certified Butyrospermum Parkii (Shea) Butter",
      "Organic Olea Europaea (Olive) Oil",
      "Rosmarinus Officinalis (Rosemary) Leaf Extract",
      "Pogostemon Cablin (Patchouli) Leaf Oil",
      "Boswellia Serrata (Frankincense) Oil",
      "Copaifera Species (Copal) Resin Oil",
      "Dipteryx Odorata (Tonka Bean) Seed Extract"
    ],
    freeFrom: ["Harsh Surfactants","Synthetic Fragrance"],
    rating: 4.7,
    reviewCount: 668,
    accent: "#6A7F5C",
    badge: "Best seller",
    imageUrl: "https://humblebrands.com/cdn/shop/files/250520_Humble_Bar_Soap_Box_Naked_Patchouli_Copal_Web.jpg?v=1762457418&width=800",
  },
  {
    id: "hb19",
    slug: "mountain-lavender-soap",
    brandId: "b7",
    name: "Mountain Lavender Soap",
    category: "skincare",
    price: 7.99,
    description:
      "Moisturizing bar soap - Clean herbal florals with gentle sweetness and green clarity",
    ingredients: [
      "Organic Helianthus Annuus (Sunflower) Seed Oil",
      "Organic Cocos Nucifera (Coconut) Oil",
      "Aqua",
      "Sodium Hydroxide",
      "Organic RSPO Certified Elaeis Guineensis (Palm) Oil",
      "Organic Fair Trade Certified Butyrospermum Parkii (Shea) Butter",
      "Organic Olea Europaea (Olive) Oil",
      "Rosmarinus Officinalis (Rosemary) Leaf Extract",
      "Lavandula Officinalis (Lavender) Flower Oil"
    ],
    freeFrom: ["Harsh Surfactants","Synthetic Fragrance"],
    rating: 4.7,
    reviewCount: 62,
    accent: "#6A7F5C",
    imageUrl: "https://humblebrands.com/cdn/shop/files/250520_Humble_Bar_Soap_Box_Naked_Mountain_Lavender_Web.jpg?v=1762457411&width=800",
  },
  {
    id: "hb20",
    slug: "unscented-deodorant",
    brandId: "b7",
    name: "Unscented Deodorant",
    category: "deodorant",
    price: 10.99,
    description:
      "Aluminum-free Deodorant. Scent intensity 1/5 - Unscented Gender-neutral.",
    ingredients: [
      "Caprylic/Capric Triglyceride (MCT)",
      "Non-GMO Zea Mays (Corn) Starch",
      "Sodium Bicarbonate (Baking Soda)",
      "Cera Alba (Beeswax)"
    ],
    freeFrom: ["Aluminum","Phthalates"],
    rating: 4.7,
    reviewCount: 104,
    accent: "#6A7F5C",
    imageUrl: "https://humblebrands.com/cdn/shop/files/250919-Humble-OFFull-SimplyUnscented-Front-WEB.jpg?v=1762360667&width=800",
  },
  {
    id: "hb21",
    slug: "lemongrass-sage-soap",
    brandId: "b7",
    name: "Lemongrass & Sage Soap",
    category: "skincare",
    price: 7.99,
    description:
      "Moisturizing bar soap from Humble Brands",
    ingredients: [
      "Organic Helianthus Annuus (Sunflower) Seed Oil",
      "Organic Cocos Nucifera (Coconut) Oil",
      "Aqua",
      "Sodium Hydroxide",
      "Organic RSPO Certified Elaeis Guineensis (Palm) Oil",
      "Organic Fair Trade Certified Butyrospermum Parkii (Shea) Butter",
      "Organic Olea Europaea (Olive) Oil",
      "Rosmarinus Officinalis (Rosemary) Leaf Extract",
      "Salvia Officinalis (Sage) Oil",
      "Cymbopogon Flexuosus (Lemongrass) Oil"
    ],
    freeFrom: ["Harsh Surfactants","Synthetic Fragrance"],
    rating: 4.7,
    reviewCount: 62,
    accent: "#6A7F5C",
    imageUrl: "https://humblebrands.com/cdn/shop/files/250520_Humble_Bar_Soap_Box_Naked_Lemongrass_and_Sage_Web.jpg?v=1775084023&width=800",
  },
  {
    id: "hb22",
    slug: "baking-soda-free-sensitive-skin-moroccan-rose-deodorant",
    brandId: "b7",
    name: "Baking Soda-Free Sensitive Skin Moroccan Rose Deodorant",
    category: "deodorant",
    price: 10.99,
    description:
      "Sensitive Skin Deodorant. Scent intensity 3/5 - Balanced Feminine.",
    ingredients: [
      "Caprylic/Capric Triglyceride (MCT)",
      "Non-GMO Zea Mays (Corn) Starch",
      "Magnesium Hydroxide",
      "Euphorbia Cerifera (Candelilla) Wax",
      "Zingiber Officinale (Ginger) Root Oil",
      "Citrus Aurantium Bergamia (Bergamot, Bergaptene Free) Peel Oil",
      "Limonene",
      "Linalool",
      "Citral",
      "Geraniol"
    ],
    freeFrom: ["Aluminum","Baking Soda","Phthalates"],
    rating: 4.4,
    reviewCount: 68,
    accent: "#6A7F5C",
    imageUrl: "https://humblebrands.com/cdn/shop/files/250919-Humble-VSFull-MoroccanRose-Front-WEB.jpg?v=1762360667&width=800",
  },
  {
    id: "hb23",
    slug: "baking-soda-free-sensitive-skin-mountain-lavender-deodorant",
    brandId: "b7",
    name: "Baking Soda-Free Sensitive Skin Mountain Lavender Deodorant",
    category: "deodorant",
    price: 10.99,
    description:
      "Sensitive Skin Deodorant. Scent intensity 2/5 - Light Feminine.",
    ingredients: [
      "Caprylic/Capric Triglyceride (MCT)",
      "Non-GMO Zea Mays (Corn) Starch",
      "Magnesium Hydroxide",
      "Euphorbia Cerifera (Candelilla) Wax",
      "Zingiber Officinale (Ginger) Root Oil",
      "Citrus Aurantium Bergamia (Bergamot, Bergaptene Free) Peel Oil",
      "Limonene",
      "Linalool",
      "Citral",
      "Geraniol"
    ],
    freeFrom: ["Aluminum","Baking Soda","Phthalates"],
    rating: 4.9,
    reviewCount: 81,
    accent: "#6A7F5C",
    imageUrl: "https://humblebrands.com/cdn/shop/files/250919-Humble-VSFull-MountainLavender-Front-WEB.jpg?v=1775083982&width=800",
  },
  {
    id: "hb24",
    slug: "baking-soda-free-sensitive-skin-bergamot-ginger-deodorant",
    brandId: "b7",
    name: "Baking Soda-Free Sensitive Skin Bergamot & Ginger Deodorant",
    category: "deodorant",
    price: 10.99,
    description:
      "Sensitive Skin Deodorant. Scent intensity 2/5 - Light Gender-neutral.",
    ingredients: [
      "Caprylic/Capric Triglyceride (MCT)",
      "Non-GMO Zea Mays (Corn) Starch",
      "Magnesium Hydroxide",
      "Euphorbia Cerifera (Candelilla) Wax",
      "Zingiber Officinale (Ginger) Root Oil",
      "Citrus Aurantium Bergamia (Bergamot, Bergaptene Free) Peel Oil",
      "Limonene",
      "Linalool",
      "Citral",
      "Geraniol"
    ],
    freeFrom: ["Aluminum","Baking Soda","Phthalates"],
    rating: 4.7,
    reviewCount: 80,
    accent: "#6A7F5C",
    imageUrl: "https://humblebrands.com/cdn/shop/files/Bergamot_Ginger_Senstive_Deodorant.png?v=1786120058&width=800",
  },
  {
    id: "hb25",
    slug: "baking-soda-free-sensitive-skin-unscented-deodorant",
    brandId: "b7",
    name: "Baking Soda-Free Sensitive Skin Unscented Deodorant",
    category: "deodorant",
    price: 10.99,
    description:
      "Sensitive Skin Deodorant. Scent intensity 1/5 - Unscented Gender-neutral.",
    ingredients: [
      "Caprylic/Capric Triglyceride (MCT)",
      "Non-GMO Zea Mays (Corn) Starch",
      "Magnesium Hydroxide",
      "Euphorbia Cerifera (Candelilla) Wax",
      "Zingiber Officinale (Ginger) Root Oil",
      "Citrus Aurantium Bergamia (Bergamot, Bergaptene Free) Peel Oil",
      "Limonene",
      "Linalool",
      "Citral",
      "Geraniol"
    ],
    freeFrom: ["Aluminum","Baking Soda","Phthalates"],
    rating: 4.6,
    reviewCount: 90,
    accent: "#6A7F5C",
    imageUrl: "https://humblebrands.com/cdn/shop/files/Energize_Kit_032b623d-8109-4d3d-a99a-c99e33eb4782.png?v=1786119632&width=800",
  },
  {
    id: "hb26",
    slug: "bergamot-ginger-travel-size",
    brandId: "b7",
    name: "Bergamot & Ginger Travel Size",
    category: "deodorant",
    price: 3.99,
    description:
      "Travel Size Original. Scent intensity 2/5 - Light Gender-neutral.",
    ingredients: [
      "Caprylic/Capric Triglyceride (MCT)",
      "Non-GMO Zea Mays (Corn) Starch",
      "Sodium Bicarbonate (Baking Soda)",
      "Cera Alba (Beeswax)",
      "Zingiber Officinale (Ginger) Root Oil",
      "Citrus Aurantium Bergamia (Bergamot, Bergaptene Free) Peel Oil",
      "Limonene",
      "Linalool",
      "Citral",
      "Geraniol"
    ],
    freeFrom: ["Aluminum","Phthalates"],
    rating: 5,
    reviewCount: 20,
    accent: "#6A7F5C",
    imageUrl: "https://humblebrands.com/cdn/shop/products/122722_Humble_OriginalDeodorant_BergamotandGingerTravel_Front_Web_61125dfa-1837-4db7-a851-c1f5573cd040.jpg?v=1762457397&width=800",
  },
  {
    id: "hb27",
    slug: "lemongrass-sage-travel-size",
    brandId: "b7",
    name: "Lemongrass & Sage Travel Size",
    category: "deodorant",
    price: 3.99,
    description:
      "Travel Size Original. Scent intensity 4/5 - Full Gender-neutral.",
    ingredients: [
      "Caprylic/Capric Triglyceride (MCT)",
      "Non-GMO Zea Mays (Corn) Starch",
      "Sodium Bicarbonate (Baking Soda)",
      "Cera Alba (Beeswax)",
      "Citrus Aurantium Bergamia (Bergamot, Bergaptene Free) Peel Oil",
      "Cymbopogon Flexuosus (Lemongrass) Oil",
      "Salvia Officinalis (Sage) Oil",
      "Cymbopogon Winterianus (Citronella) Leaf Oil",
      "Citral",
      "Citronellol",
      "Geraniol",
      "Limonene",
      "Linalool",
      "Eugenol"
    ],
    freeFrom: ["Aluminum","Phthalates"],
    rating: 4.2,
    reviewCount: 20,
    accent: "#6A7F5C",
    imageUrl: "https://humblebrands.com/cdn/shop/products/122722_Humble_OriginalDeodorant_LemongrassSageTravel_Front_Web_747d73e0-6c61-4a1d-8f45-fcad4d097194.jpg?v=1762457411&width=800",
  },
  {
    id: "hb28",
    slug: "black-spruce-plastic-free-deodorant",
    brandId: "b7",
    name: "Black Spruce Plastic-Free Deodorant",
    category: "deodorant",
    price: 12.99,
    description:
      "Plastic Free Deodorant. Scent intensity 4/5 - Full Masculine.",
    ingredients: [
      "Caprylic/Capric Triglyceride (MCT)",
      "Non-GMO Zea Mays (Corn) Starch",
      "Sodium Bicarbonate (Baking Soda)",
      "Cera Alba (Beeswax)",
      "Cistus Ladaniferus (Labdanum) Extract",
      "Picea Mariana (Black Spruce) Oil",
      "Jasminum Grandiflorum (Jasmine) Flower Extract",
      "Limonene",
      "Linalool",
      "Citronellol",
      "Benzyl Benzoate",
      "Geraniol"
    ],
    freeFrom: ["Aluminum","Phthalates"],
    rating: 4.3,
    reviewCount: 31,
    accent: "#6A7F5C",
    imageUrl: "https://humblebrands.com/cdn/shop/files/091624_Black_Spruce_Front_Web.jpg?v=1782335013&width=800",
  },
  {
    id: "hb29",
    slug: "rosemary-mint-plastic-free-deodorant",
    brandId: "b7",
    name: "Rosemary & Mint Plastic-Free Deodorant",
    category: "deodorant",
    price: 12.99,
    description:
      "Plastic Free Deodorant. Scent intensity 3/5 - Balanced Gender-neutral.",
    ingredients: [
      "Caprylic/Capric Triglyceride (MCT)",
      "Non-GMO Zea Mays (Corn) Starch",
      "Sodium Bicarbonate (Baking Soda)",
      "Cera Alba (Beeswax)",
      "Rosmarinus Officinalis (Rosemary) Leaf Oil",
      "Origanum Majorana (Marjoram) Flower Oil",
      "Mentha Piperita (Peppermint) Oil",
      "Mentha Spicata (Spearmint) Oil",
      "Cinnamomum Camphora (Ho Wood) Branch/Leaf Oil",
      "Lavandula Officinalis (Lavender) Flower Oil",
      "Geraniol",
      "Limonene",
      "Linalool"
    ],
    freeFrom: ["Aluminum","Phthalates"],
    rating: 4.6,
    reviewCount: 27,
    accent: "#6A7F5C",
    imageUrl: "https://humblebrands.com/cdn/shop/files/080624_Rosemary_Mint_Front_Web.jpg?v=1782324302&width=800",
  },
  {
    id: "hb30",
    slug: "moroccan-rose-travel-size",
    brandId: "b7",
    name: "Moroccan Rose Travel Size",
    category: "deodorant",
    price: 3.99,
    description:
      "Travel Size Original. Scent intensity 3/5 - Balanced Feminine.",
    ingredients: [
      "Caprylic/Capric Triglyceride (MCT)",
      "Non-GMO Zea Mays (Corn) Starch",
      "Sodium Bicarbonate (Baking Soda)",
      "Cera Alba (Beeswax)",
      "Pelargonium Graveolens (Geranium) Oil",
      "Rosa Damascena (Rose) Extract",
      "Citrus Aurantium Bergamia (Bergamot, Bergaptene Free) Peel Oil",
      "Citral",
      "Citronellol",
      "Eugenol",
      "Geraniol",
      "Limonene",
      "Linalool"
    ],
    freeFrom: ["Aluminum","Phthalates"],
    rating: 4.6,
    reviewCount: 25,
    accent: "#6A7F5C",
    imageUrl: "https://humblebrands.com/cdn/shop/products/122722_Humble_OriginalDeodorant_MoroccanRoseTravel_Front_Web_128e8903-86b2-4f7d-b60d-251c31d8ef9d.jpg?v=1762457452&width=800",
  },
  {
    id: "hb31",
    slug: "patchouli-copal-travel-size",
    brandId: "b7",
    name: "Patchouli & Copal Travel Size",
    category: "deodorant",
    price: 3.99,
    description:
      "Travel Size Original. Scent intensity 4/5 - Full Gender-neutral.",
    ingredients: [
      "Caprylic/Capric Triglyceride (MCT)",
      "Non-GMO Zea Mays (Corn) Starch",
      "Sodium Bicarbonate (Baking Soda)",
      "Cera Alba (Beeswax)",
      "Dipteryx Odorata (Tonka Bean) Seed Extract",
      "Pogostemon Cablin (Patchouli) Leaf Oil",
      "Copaifera Species (Copal) Resin Oil",
      "Boswellia Serrata (Frankincense) Oil",
      "Limonene",
      "Linalool",
      "Coumarin",
      "Eugenol"
    ],
    freeFrom: ["Aluminum","Phthalates"],
    rating: 4.8,
    reviewCount: 27,
    accent: "#6A7F5C",
    imageUrl: "https://humblebrands.com/cdn/shop/products/122722_Humble_OriginalDeodorant_PatchouliCopalTravel_Front_Web_ea71ab79-496a-42bf-8902-38e0e7f0b15e.jpg?v=1762457450&width=800",
  },
  {
    id: "hb32",
    slug: "rosemary-mint-travel-size",
    brandId: "b7",
    name: "Rosemary & Mint Travel Size",
    category: "deodorant",
    price: 3.99,
    description:
      "Travel Size Original. Scent intensity 3/5 - Balanced Gender-neutral.",
    ingredients: [
      "Caprylic/Capric Triglyceride (MCT)",
      "Non-GMO Zea Mays (Corn) Starch",
      "Sodium Bicarbonate (Baking Soda)",
      "Cera Alba (Beeswax)",
      "Rosmarinus Officinalis (Rosemary) Leaf Oil",
      "Origanum Majorana (Marjoram) Flower Oil",
      "Mentha Piperita (Peppermint) Oil",
      "Mentha Spicata (Spearmint) Oil",
      "Cinnamomum Camphora (Ho Wood) Branch/Leaf Oil",
      "Lavandula Officinalis (Lavender) Flower Oil",
      "Geraniol",
      "Limonene",
      "Linalool"
    ],
    freeFrom: ["Aluminum","Phthalates"],
    rating: 4.7,
    reviewCount: 13,
    accent: "#6A7F5C",
    imageUrl: "https://humblebrands.com/cdn/shop/products/122722_Humble_OriginalDeodorant_RosemaryMintTravel_Front_Web_ba8f8cbc-2e75-4e5f-9a7a-62d33a6bfc44.jpg?v=1762457777&width=800",
  },
  {
    id: "p1",
    slug: "daily-sheer-spf50",
    brandId: "b1",
    name: "Daily Sheer SPF 50",
    category: "sunscreen",
    price: 32,
    description:
      "A weightless mineral sunscreen with non-nano zinc oxide. No white cast, reef-conscious, and built for everyday wear under makeup or alone",
    ingredients: [
      "Zinc Oxide",
      "Squalane",
      "Niacinamide",
      "Hyaluronic Acid",
      "Vitamin E",
      "Coconut Alkanes",
    ],
    freeFrom: ["Oxybenzone", "Octinoxate", "Fragrance", "Parabens"],
    rating: 4.9,
    reviewCount: 214,
    accent: "#F4A261",
    badge: "Staff pick",
  },
  {
    id: "p2",
    slug: "sport-stick-spf40",
    brandId: "b1",
    name: "Sport Stick SPF 40",
    category: "sunscreen",
    price: 24,
    description:
      "Pocket-sized mineral stick for reapplying on the go. Melts on contact — great for runners, kids, and anyone who hates liquid SPF mid-hike",
    ingredients: [
      "Zinc Oxide",
      "Beeswax",
      "Jojoba Oil",
      "Shea Butter",
      "Tocopherol",
    ],
    freeFrom: ["Oxybenzone", "Octinoxate", "Parabens"],
    rating: 4.7,
    reviewCount: 98,
    accent: "#E9C46A",
  },
  {
    id: "p3",
    slug: "cedar-bergamot-deo",
    brandId: "b2",
    name: "Cedar + Bergamot Deo",
    category: "deodorant",
    price: 18,
    description:
      "Cream deodorant with magnesium and potassium alum. Fresh woody scent that stays put through workouts without clogging pores",
    ingredients: [
      "Magnesium Hydroxide",
      "Potassium Alum",
      "Arrowroot Powder",
      "Coconut Oil",
      "Bergamot Oil",
      "Cedarwood Oil",
      "Shea Butter",
    ],
    freeFrom: ["Aluminum Chlorohydrate", "Baking Soda", "Phthalates"],
    rating: 4.6,
    reviewCount: 341,
    accent: "#2A9D8F",
    badge: "Community fave",
  },
  {
    id: "p4",
    slug: "unscented-everyday",
    brandId: "b2",
    name: "Unscented Everyday",
    category: "deodorant",
    price: 16,
    description:
      "The same sweat-fighting formula, zero scent. Ideal for sensitive skin and anyone who wants their perfume to do the talking",
    ingredients: [
      "Magnesium Hydroxide",
      "Potassium Alum",
      "Arrowroot Powder",
      "Coconut Oil",
      "Shea Butter",
      "Vitamin E",
    ],
    freeFrom: ["Aluminum Chlorohydrate", "Baking Soda", "Fragrance"],
    rating: 4.5,
    reviewCount: 187,
    accent: "#264653",
  },
  {
    id: "p5",
    slug: "vanilla-hemp-protein",
    brandId: "b3",
    name: "Vanilla Hemp Protein",
    category: "protein",
    price: 42,
    description:
      "25g plant protein per scoop from hemp + pea. Naturally sweetened with monk fruit. Mixes smooth — no gritty aftertaste",
    ingredients: [
      "Hemp Protein",
      "Pea Protein Isolate",
      "Monk Fruit Extract",
      "Vanilla Bean",
      "Sunflower Lecithin",
      "Sea Salt",
    ],
    freeFrom: ["Dairy", "Soy", "Gluten", "Artificial Sweeteners"],
    rating: 4.8,
    reviewCount: 456,
    accent: "#E76F51",
    badge: "Best seller",
  },
  {
    id: "p6",
    slug: "cacao-recovery",
    brandId: "b3",
    name: "Cacao Recovery Blend",
    category: "protein",
    price: 46,
    description:
      "Post-workout blend with protein, magnesium glycinate, and real cacao. Tastes like a mocha, recovers like a pro",
    ingredients: [
      "Pea Protein Isolate",
      "Cacao Powder",
      "Magnesium Glycinate",
      "Hemp Protein",
      "Monk Fruit Extract",
      "Cinnamon",
    ],
    freeFrom: ["Dairy", "Soy", "Gluten", "Whey"],
    rating: 4.7,
    reviewCount: 203,
    accent: "#6D4C41",
  },
  {
    id: "p7",
    slug: "cloud-serum",
    brandId: "b4",
    name: "Cloud Serum",
    category: "skincare",
    price: 38,
    description:
      "A featherweight hyaluronic + ceramides serum that plumps without stickiness. Five ingredients. That's the whole story",
    ingredients: [
      "Hyaluronic Acid",
      "Ceramide NP",
      "Glycerin",
      "Panthenol",
      "Aqua",
    ],
    freeFrom: ["Fragrance", "Essential Oils", "Alcohol", "Silicones"],
    rating: 4.9,
    reviewCount: 672,
    accent: "#7EB8D4",
    badge: "Editor's love",
  },
  {
    id: "p8",
    slug: "barrier-balm",
    brandId: "b4",
    name: "Barrier Balm",
    category: "skincare",
    price: 28,
    description:
      "Nighttime balm for compromised barriers. Squalane, cholesterol, and fatty acids in a jar you will scrape clean",
    ingredients: [
      "Squalane",
      "Cholesterol",
      "Ceramide AP",
      "Shea Butter",
      "Jojoba Oil",
    ],
    freeFrom: ["Fragrance", "Essential Oils", "Parabens"],
    rating: 4.8,
    reviewCount: 389,
    accent: "#A8DADC",
  },
  {
    id: "p9",
    slug: "scalp-tonic",
    brandId: "b5",
    name: "Scalp Tonic",
    category: "hair",
    price: 34,
    description:
      "Leave-in tonic with rosemary, peppermint, and fermented rice water. Wakes up sleepy scalps without weighing hair down",
    ingredients: [
      "Rosemary Extract",
      "Peppermint Oil",
      "Fermented Rice Water",
      "Aloe Vera",
      "Niacinamide",
      "Witch Hazel",
    ],
    freeFrom: ["Sulfates", "Silicones", "Parabens"],
    rating: 4.5,
    reviewCount: 142,
    accent: "#9B7EBD",
  },
  {
    id: "p10",
    slug: "hap-toothpaste",
    brandId: "b6",
    name: "nHA Toothpaste",
    category: "oral",
    price: 22,
    description:
      "Nano-hydroxyapatite toothpaste in a refillable jar. Remineralizes enamel gently — no harsh whitening burn",
    ingredients: [
      "Hydroxyapatite",
      "Xylitol",
      "Calcium Carbonate",
      "Coconut Oil",
      "Spearmint Oil",
      "Bentonite Clay",
    ],
    freeFrom: ["Fluoride", "SLS", "Titanium Dioxide", "Plastic Tube"],
    rating: 4.4,
    reviewCount: 156,
    accent: "#45B69C",
  },
];

export const reviews: Review[] = [
  {
    id: "r1",
    productId: "p1",
    brandId: "b1",
    author: "Maya K",
    rating: 5,
    title: "Finally, SPF that doesn't pill",
    body: "I wear this under foundation every day. Zero white cast on my medium-deep skin and it plays nice with my Dewdrop serum. Solara gets it",
    helpful: 48,
    daysAgo: 3,
  },
  {
    id: "r2",
    productId: "p3",
    brandId: "b2",
    author: "Jordan T",
    rating: 5,
    title: "Survived a Texas summer",
    body: "I was skeptical of cream deodorants. This one made it through 90° days and a spin class. The cedar scent is subtle, not cologne-y",
    helpful: 72,
    daysAgo: 7,
  },
  {
    id: "r3",
    productId: "p5",
    brandId: "b3",
    author: "Sam R",
    rating: 4,
    title: "Actually mixes without a blender",
    body: "Shaken in a bottle with oat milk — smooth. Vanilla is real, not perfume. Wish the bag was a little bigger but quality over quantity",
    helpful: 31,
    daysAgo: 12,
  },
  {
    id: "r4",
    productId: "p7",
    brandId: "b4",
    author: "Priya N",
    rating: 5,
    title: "Five ingredients. Miraculous",
    body: "My reactive skin usually freaks out at new serums. Cloud Serum is the first thing that hydrated without a flare. Obsessed",
    helpful: 95,
    daysAgo: 2,
  },
  {
    id: "r5",
    brandId: "b2",
    author: "Chris L",
    rating: 4,
    title: "Solid brand, great people",
    body: "Reached out about a sensitive-skin swap and they sent samples of the unscented. Tiny brands that care like this are why I shop here",
    helpful: 22,
    daysAgo: 18,
  },
  {
    id: "r6",
    productId: "p10",
    brandId: "b6",
    author: "Alex M",
    rating: 5,
    title: "Glass jar > plastic tube",
    body: "Taste is clean spearmint. Teeth feel smoother after two weeks. Refill program is easy. Mint Theory is onto something",
    helpful: 19,
    daysAgo: 9,
  },
];

export const communityPosts: CommunityPost[] = [
  {
    id: "c1",
    author: "lena.shops.small",
    topic: "Finds",
    title: "Anyone else replace their whole bathroom with tiny brands?",
    body: "Started with Pine & Alum, now I'm fully Solara + Dewdrop + Mint Theory. Curious what your 'complete swap' looks like",
    replies: 34,
    likes: 128,
    hoursAgo: 4,
    tags: ["routine", "swap"],
  },
  {
    id: "c2",
    author: "zinc.or.bust",
    topic: "Ingredients",
    title: "Non-nano zinc: what % actually works for you?",
    body: "Solara's Daily Sheer is 20% and I don't burn. Curious if anyone's found a lower % that still holds for outdoor runs",
    replies: 21,
    likes: 67,
    hoursAgo: 11,
    tags: ["sunscreen", "zinc oxide"],
  },
  {
    id: "c3",
    author: "protein.nerd",
    topic: "Taste test",
    title: "Nourish Co. cacao vs. the big brands",
    body: "Blind tasted with roommates. Nourish won 3–1. The magnesium in the recovery blend is a quiet hero for my sleep",
    replies: 15,
    likes: 89,
    hoursAgo: 26,
    tags: ["protein", "review"],
  },
  {
    id: "c4",
    author: "sensitive.skin.club",
    topic: "Help",
    title: "Fragrance-free deodorant that doesn't itch?",
    body: "Baking soda wrecks me. Trying Pine & Alum Unscented next — any other free-from lists I should filter for?",
    replies: 42,
    likes: 156,
    hoursAgo: 8,
    tags: ["deodorant", "sensitive"],
  },
  {
    id: "c5",
    author: "apothecary.alex",
    topic: "Brands",
    title: "Root Ritual scalp tonic — week 3 update",
    body: "Less itch, more volume at the crown. Smells like a spa walk through a herb garden. Supporting Asheville feels good too",
    replies: 9,
    likes: 44,
    hoursAgo: 40,
    tags: ["hair", "update"],
  },
];

export const popularIngredients = [
  "Zinc Oxide",
  "Hyaluronic Acid",
  "Niacinamide",
  "Squalane",
  "Magnesium Hydroxide",
  "Hemp Protein",
  "Hydroxyapatite",
  "Ceramide NP",
  "Monk Fruit Extract",
  "Rosemary Extract",
  "Shea Butter",
  "Pea Protein Isolate",
];

export const avoidIngredients = [
  "Oxybenzone",
  "Octinoxate",
  "Aluminum Chlorohydrate",
  "Baking Soda",
  "Fragrance",
  "Parabens",
  "SLS",
  "Artificial Sweeteners",
];

export function getBrand(idOrSlug: string) {
  return brands.find((b) => b.id === idOrSlug || b.slug === idOrSlug);
}

export function getProduct(idOrSlug: string) {
  return products.find((p) => p.id === idOrSlug || p.slug === idOrSlug);
}

export function productsForBrand(brandId: string) {
  return products.filter((p) => p.brandId === brandId);
}

export function reviewsForProduct(productId: string) {
  return reviews.filter((r) => r.productId === productId);
}

export function reviewsForBrand(brandId: string) {
  return reviews.filter((r) => r.brandId === brandId);
}

export function searchByIngredient(query: string, mode: "contains" | "free-from" = "contains") {
  const q = query.trim().toLowerCase();
  if (!q) return products;
  if (mode === "free-from") {
    return products.filter(
      (p) =>
        p.freeFrom.some((i) => i.toLowerCase().includes(q)) ||
        !p.ingredients.some((i) => i.toLowerCase().includes(q)),
    );
  }
  return products.filter(
    (p) =>
      p.ingredients.some((i) => i.toLowerCase().includes(q)) ||
      p.name.toLowerCase().includes(q) ||
      p.description.toLowerCase().includes(q),
  );
}
