insert into public.products (
  id, slug, brand_id, name, category, category_id, price, description, accent,
  badge, affiliate_url, affiliate_network, image_url, rating, review_count,
  size, how_to_use, good_for, smells_like, finish, features, is_published, placed_by
) values
  (
    'c0000000-0000-0000-0000-000000000021',
    $tm$natural-fluoride-free-toddler-training-toothpaste$tm$,
    (select id from public.brands where slug = 'toms-of-maine'),
    $tm$Fluoride-Free Toddler Training Natural Toothpaste$tm$,
    'oral',
    (select id from public.categories where slug = 'oral'),
    4.99,
    $tm$Introduce your little one to good brushing habits with the Tom’s of Maine Fluoride Free Toddler Training Toothpaste.$tm$,
    $tm$#2D6A4F$tm$,
    null,
    $tm$https://www.tomsofmaine.com/products/natural-fluoride-free-toddler-training-toothpaste$tm$,
    'direct',
    $tm$https://www.tomsofmaine.com/cdn/shop/files/683435_primary_cbabcf4d-e577-42e7-b409-138700b1629f.jpg?v=1744048226&width=600$tm$,
    4.6,
    0,
    $tm$1.75 oz$tm$,
    $tm$$tm$,
    $tm$Gluten Free; No Artificial Sweeteners$tm$,
    $tm$$tm$,
    $tm$$tm$,
    array[$f$Gluten Free$f$, $f$No Artificial Sweeteners$f$]::text[],
    true,
    $tm$catoegy$tm$
  )
on conflict (slug) do update set
  brand_id = excluded.brand_id,
  name = excluded.name,
  category = excluded.category,
  category_id = excluded.category_id,
  price = excluded.price,
  description = excluded.description,
  accent = excluded.accent,
  badge = excluded.badge,
  affiliate_url = excluded.affiliate_url,
  affiliate_network = excluded.affiliate_network,
  image_url = excluded.image_url,
  rating = excluded.rating,
  review_count = excluded.review_count,
  size = excluded.size,
  how_to_use = excluded.how_to_use,
  good_for = excluded.good_for,
  features = excluded.features,
  is_published = excluded.is_published,
  placed_by = excluded.placed_by;
