insert into public.products (
  id, slug, brand_id, name, category, category_id, price, description, accent,
  badge, affiliate_url, affiliate_network, image_url, rating, review_count,
  size, how_to_use, good_for, smells_like, finish, features, is_published, placed_by
) values
  (
    'c0000000-0000-0000-0000-000000000016',
    $tm$grab-n-go-travel-size-anticavity-fresh-mint-toothpaste$tm$,
    (select id from public.brands where slug = 'toms-of-maine'),
    $tm$Grab n' Go Travel Size Anticavity Fresh Mint Natural Toothpaste$tm$,
    'oral',
    (select id from public.categories where slug = 'oral'),
    4.49,
    $tm$Take Tom's on the road. This great-tasting, everyday natural toothpaste whitens teeth with naturally sourced silicas, helps fight cavities with naturally derived fluoride, and freshens breath with pure peppermint leaf oil. Comes in a 3.$tm$,
    $tm$#2D6A4F$tm$,
    null,
    $tm$https://www.tomsofmaine.com/products/grab-n-go-travel-size-anticavity-fresh-mint-toothpaste$tm$,
    'direct',
    $tm$https://www.tomsofmaine.com/cdn/shop/files/683259_primary_8abf8ec3-b4a8-4223-b18e-4e15f3774995.jpg?v=1744048229&width=600$tm$,
    4.6,
    0,
    $tm$3 oz$tm$,
    $tm$$tm$,
    $tm$Anticavity$tm$,
    $tm$$tm$,
    $tm$$tm$,
    array[$f$Anticavity$f$]::text[],
    true,
    $tm$catoegy$tm$
  )
on conflict (slug) do update set
  brand_id = excluded.brand_id,
  name = excluded.name,
  category = excluded.category,
  category_id = excluded.category_id,
  price = excluded.price,
  description = excluded.description,
  accent = excluded.accent,
  badge = excluded.badge,
  affiliate_url = excluded.affiliate_url,
  affiliate_network = excluded.affiliate_network,
  image_url = excluded.image_url,
  rating = excluded.rating,
  review_count = excluded.review_count,
  size = excluded.size,
  how_to_use = excluded.how_to_use,
  good_for = excluded.good_for,
  features = excluded.features,
  is_published = excluded.is_published,
  placed_by = excluded.placed_by;
