insert into public.products (
  id, slug, brand_id, name, category, category_id, price, description, accent,
  badge, affiliate_url, affiliate_network, image_url, rating, review_count,
  size, how_to_use, good_for, smells_like, finish, features, is_published, placed_by
) values
  (
    'c0000000-0000-0000-0000-000000000017',
    $tm$wicked-fresh-spearmint-ice-natural-fluoride-toothpaste$tm$,
    (select id from public.brands where slug = 'toms-of-maine'),
    $tm$Wicked Fresh! Spearmint Ice Fluoride Natural Toothpaste$tm$,
    'oral',
    (select id from public.categories where slug = 'oral'),
    7.99,
    $tm$Fresh breath is only a brush away with Tom’s of Maine Wicked Fresh! Natural Fluoride Toothpaste. This natural toothpaste with fluoride is a bad breath toothpaste that is clinically proven to help freshen breath and comes in a refreshing Spearmint Ice flavor.$tm$,
    $tm$#2D6A4F$tm$,
    null,
    $tm$https://www.tomsofmaine.com/products/wicked-fresh-spearmint-ice-natural-fluoride-toothpaste$tm$,
    'direct',
    $tm$https://www.tomsofmaine.com/cdn/shop/files/61038013_primary_e7d8578b-32d6-4197-98e0-8a6f202577a7.jpg?v=1744048256&width=600$tm$,
    4.6,
    0,
    $tm$4 oz$tm$,
    $tm$$tm$,
    $tm$Contains Fluoride; Anticavity; Vegan$tm$,
    $tm$$tm$,
    $tm$$tm$,
    array[$f$Contains Fluoride$f$, $f$Anticavity$f$, $f$Vegan$f$]::text[],
    true,
    $tm$catoegy$tm$
  )
on conflict (slug) do update set
  brand_id = excluded.brand_id,
  name = excluded.name,
  category = excluded.category,
  category_id = excluded.category_id,
  price = excluded.price,
  description = excluded.description,
  accent = excluded.accent,
  badge = excluded.badge,
  affiliate_url = excluded.affiliate_url,
  affiliate_network = excluded.affiliate_network,
  image_url = excluded.image_url,
  rating = excluded.rating,
  review_count = excluded.review_count,
  size = excluded.size,
  how_to_use = excluded.how_to_use,
  good_for = excluded.good_for,
  features = excluded.features,
  is_published = excluded.is_published,
  placed_by = excluded.placed_by;
