insert into public.products (
  id, slug, brand_id, name, category, category_id, price, description, accent,
  badge, affiliate_url, affiliate_network, image_url, rating, review_count,
  size, how_to_use, good_for, smells_like, finish, features, is_published, placed_by
) values
  (
    'c0000000-0000-0000-0000-000000000023',
    $tm$watermelon-wiggle-kids-toothpaste-with-fluoride$tm$,
    (select id from public.brands where slug = 'toms-of-maine'),
    $tm$Watermelon Wiggle Natural Kids Toothpaste with Fluoride$tm$,
    'oral',
    (select id from public.categories where slug = 'oral'),
    6.49,
    $tm$Tom’s of Maine Watermelon Wiggle Kids Toothpaste is a natural kids toothpaste with fluoride for children ages 2 and up that makes brushing fun and helps fight cavities.$tm$,
    $tm$#2D6A4F$tm$,
    null,
    $tm$https://www.tomsofmaine.com/products/watermelon-wiggle-kids-toothpaste-with-fluoride$tm$,
    'direct',
    $tm$https://www.tomsofmaine.com/cdn/shop/files/61040113_primary_fab8dace-c537-4e7a-9b6f-ee1aa405b127.jpg?v=1744048276&width=600$tm$,
    4.6,
    0,
    $tm$5.1 oz$tm$,
    $tm$$tm$,
    $tm$WHAT YOU'LL GET; FIGHT CAVITIES; TASTE THEY LOVE$tm$,
    $tm$$tm$,
    $tm$$tm$,
    array[$f$WHAT YOU'LL GET$f$, $f$FIGHT CAVITIES$f$, $f$TASTE THEY LOVE$f$, $f$RECYCLABLE TUBE$f$, $f$TAKE CARE OF YOURSELF NATURALLY$f$, $f$Anticavity$f$]::text[],
    true,
    $tm$catoegy$tm$
  )
on conflict (slug) do update set
  brand_id = excluded.brand_id,
  name = excluded.name,
  category = excluded.category,
  category_id = excluded.category_id,
  price = excluded.price,
  description = excluded.description,
  accent = excluded.accent,
  badge = excluded.badge,
  affiliate_url = excluded.affiliate_url,
  affiliate_network = excluded.affiliate_network,
  image_url = excluded.image_url,
  rating = excluded.rating,
  review_count = excluded.review_count,
  size = excluded.size,
  how_to_use = excluded.how_to_use,
  good_for = excluded.good_for,
  features = excluded.features,
  is_published = excluded.is_published,
  placed_by = excluded.placed_by;
