insert into public.products (
  id, slug, brand_id, name, category, category_id, price, description, accent,
  badge, affiliate_url, affiliate_network, image_url, rating, review_count,
  size, how_to_use, good_for, smells_like, finish, features, is_published, placed_by
) values
  (
    'c0000000-0000-0000-0000-000000000003',
    $tm$whiten-plus-deep-clean-whitening-toothpaste-peppermint$tm$,
    (select id from public.brands where slug = 'toms-of-maine'),
    $tm$Whiten Plus Deep Clean Natural Whitening Peppermint Toothpaste$tm$,
    'oral',
    (select id from public.categories where slug = 'oral'),
    7.99,
    $tm$Discover a whiter smile with Tom’s of Maine Whiten Plus Deep Clean Whitening Toothpaste. This enamel safe whitening toothpaste helps whiten without causing sensitivity, removes up to 95% of surface stains* and doubles as an anticavity toothpaste.$tm$,
    $tm$#2D6A4F$tm$,
    null,
    $tm$https://www.amazon.com/Toms-Maine-Anticavity-Peppermint-Toothpaste/dp/B0D9BZR3P5?linkCode=ll2&tag=22258941-20&linkId=1be33af783eeae19d31151e794f7bac3&language=en_US&ref_=as_li_ss_tl$tm$,
    'amazon',
    $tm$https://www.tomsofmaine.com/cdn/shop/files/61046078_Packshot_Front_In_Package_8aaf5813-1ca7-49bd-b286-c5fcbba483c6.jpg?v=1744048285&width=800$tm$,
    4.6,
    0,
    $tm$4 oz$tm$,
    $tm$$tm$,
    $tm$Anticavity; Whitening$tm$,
    $tm$$tm$,
    $tm$$tm$,
    array[$f$Anticavity$f$, $f$Whitening$f$]::text[],
    true,
    $tm$catoegy$tm$
  )
on conflict (slug) do update set
  brand_id = excluded.brand_id,
  name = excluded.name,
  category = excluded.category,
  category_id = excluded.category_id,
  price = excluded.price,
  description = excluded.description,
  accent = excluded.accent,
  badge = excluded.badge,
  affiliate_url = excluded.affiliate_url,
  affiliate_network = excluded.affiliate_network,
  image_url = excluded.image_url,
  rating = excluded.rating,
  review_count = excluded.review_count,
  size = excluded.size,
  how_to_use = excluded.how_to_use,
  good_for = excluded.good_for,
  features = excluded.features,
  is_published = excluded.is_published,
  placed_by = excluded.placed_by;
