insert into public.products (
  id, slug, brand_id, name, category, category_id, price, description, accent,
  badge, affiliate_url, affiliate_network, image_url, rating, review_count,
  size, how_to_use, good_for, smells_like, finish, features, is_published, placed_by
) values
  (
    'c0000000-0000-0000-0000-000000000008',
    $tm$fresh-start-bundle$tm$,
    (select id from public.brands where slug = 'toms-of-maine'),
    $tm$Fresh Start Bundle$tm$,
    'oral',
    (select id from public.categories where slug = 'oral'),
    17.99,
    $tm$A fresh start from head to toe. This bundle brings together Clean Coast Deodorant, Lemon Bergamot Natural Beauty Bar, and Fluoride-Free Antiplaque & Whitening Peppermint Toothpaste—a collection designed to cleanse, refresh, and invigorate your daily routine.$tm$,
    $tm$#2D6A4F$tm$,
    null,
    $tm$https://www.tomsofmaine.com/products/fresh-start-bundle$tm$,
    'direct',
    $tm$https://www.tomsofmaine.com/cdn/shop/files/toms_pdp-hero_freshkit_april-2026-update.jpg?v=1775232646&width=800$tm$,
    4.6,
    0,
    $tm$4.5 oz, 3.25 oz, 5 oz$tm$,
    $tm$$tm$,
    $tm$Whitening$tm$,
    $tm$$tm$,
    $tm$$tm$,
    array[$f$Whitening$f$]::text[],
    true,
    $tm$catoegy$tm$
  )
on conflict (slug) do update set
  brand_id = excluded.brand_id,
  name = excluded.name,
  category = excluded.category,
  category_id = excluded.category_id,
  price = excluded.price,
  description = excluded.description,
  accent = excluded.accent,
  badge = excluded.badge,
  affiliate_url = excluded.affiliate_url,
  affiliate_network = excluded.affiliate_network,
  image_url = excluded.image_url,
  rating = excluded.rating,
  review_count = excluded.review_count,
  size = excluded.size,
  how_to_use = excluded.how_to_use,
  good_for = excluded.good_for,
  features = excluded.features,
  is_published = excluded.is_published,
  placed_by = excluded.placed_by;
