insert into public.products (
  id, slug, brand_id, name, category, category_id, price, description, accent,
  badge, affiliate_url, affiliate_network, image_url, rating, review_count,
  size, how_to_use, good_for, smells_like, finish, features, is_published, placed_by
) values
  (
    'c0000000-0000-0000-0000-000000000018',
    $tm$fluoride-free-antiplaque-whitening-spearmint-toothpaste-gel$tm$,
    (select id from public.brands where slug = 'toms-of-maine'),
    $tm$Fluoride-Free Antiplaque & Whitening Spearmint Natural Toothpaste Gel$tm$,
    'oral',
    (select id from public.categories where slug = 'oral'),
    7.99,
    $tm$Experience a bright smile using naturally derived and sourced ingredients with Tom’s of Maine Antiplaque and Whitening Fluoride Free Toothpaste Gel.$tm$,
    $tm$#2D6A4F$tm$,
    null,
    $tm$https://www.tomsofmaine.com/products/fluoride-free-antiplaque-whitening-spearmint-toothpaste-gel$tm$,
    'direct',
    $tm$https://www.tomsofmaine.com/cdn/shop/files/61038011_primary_72dd8366-1bad-42aa-aca1-cacbc8e801e2.jpg?v=1744048265&width=600$tm$,
    4.6,
    0,
    $tm$4 oz$tm$,
    $tm$$tm$,
    $tm$Whitening$tm$,
    $tm$$tm$,
    $tm$$tm$,
    array[$f$Whitening$f$]::text[],
    true,
    $tm$catoegy$tm$
  )
on conflict (slug) do update set
  brand_id = excluded.brand_id,
  name = excluded.name,
  category = excluded.category,
  category_id = excluded.category_id,
  price = excluded.price,
  description = excluded.description,
  accent = excluded.accent,
  badge = excluded.badge,
  affiliate_url = excluded.affiliate_url,
  affiliate_network = excluded.affiliate_network,
  image_url = excluded.image_url,
  rating = excluded.rating,
  review_count = excluded.review_count,
  size = excluded.size,
  how_to_use = excluded.how_to_use,
  good_for = excluded.good_for,
  features = excluded.features,
  is_published = excluded.is_published,
  placed_by = excluded.placed_by;
