insert into public.products (
  id, slug, brand_id, name, category, category_id, price, description, accent,
  badge, affiliate_url, affiliate_network, image_url, rating, review_count,
  size, how_to_use, good_for, smells_like, finish, features, is_published, placed_by
) values
  (
    'c0000000-0000-0000-0000-000000000007',
    $tm$best-sellers-toothpaste-trio$tm$,
    (select id from public.brands where slug = 'toms-of-maine'),
    $tm$Best Sellers Toothpaste Trio$tm$,
    'oral',
    (select id from public.categories where slug = 'oral'),
    16.99,
    $tm$Get a complete clean with this carefully curated toothpaste bundle. Featuring Whole Care, Antiplaque & Whitening, and Fluoride-Free formulas, this set is designed to support a healthy mouth with every brush.$tm$,
    $tm$#2D6A4F$tm$,
    null,
    $tm$https://www.tomsofmaine.com/products/best-sellers-toothpaste-trio$tm$,
    'direct',
    $tm$https://www.tomsofmaine.com/cdn/shop/files/toms_pdp-hero_pastekit_2026-update.jpg?v=1768587725&width=800$tm$,
    4.6,
    0,
    $tm$$tm$,
    $tm$$tm$,
    $tm$Anticavity; Whitening$tm$,
    $tm$$tm$,
    $tm$$tm$,
    array[$f$Anticavity$f$, $f$Whitening$f$]::text[],
    true,
    $tm$catoegy$tm$
  )
on conflict (slug) do update set
  brand_id = excluded.brand_id,
  name = excluded.name,
  category = excluded.category,
  category_id = excluded.category_id,
  price = excluded.price,
  description = excluded.description,
  accent = excluded.accent,
  badge = excluded.badge,
  affiliate_url = excluded.affiliate_url,
  affiliate_network = excluded.affiliate_network,
  image_url = excluded.image_url,
  rating = excluded.rating,
  review_count = excluded.review_count,
  size = excluded.size,
  how_to_use = excluded.how_to_use,
  good_for = excluded.good_for,
  features = excluded.features,
  is_published = excluded.is_published,
  placed_by = excluded.placed_by;
