insert into public.products (
  id, slug, brand_id, name, category, category_id, price, description, accent,
  badge, affiliate_url, affiliate_network, image_url, rating, review_count,
  size, how_to_use, good_for, smells_like, finish, features, is_published, placed_by
) values
  (
    'c0000000-0000-0000-0000-000000000012',
    $tm$whole-care-natural-peppermint-toothpaste-with-fluoride$tm$,
    (select id from public.brands where slug = 'toms-of-maine'),
    $tm$Whole Care Peppermint Natural Toothpaste with Fluoride$tm$,
    'oral',
    (select id from public.categories where slug = 'oral'),
    7.99,
    $tm$Promote a clean, bright, healthy smile with the Tom’s of Maine Whole Care Natural Toothpaste with Fluoride. The fluoride toothpaste prevents cavities, strengthens enamel, and whitens teeth by removing surface stains.$tm$,
    $tm$#2D6A4F$tm$,
    null,
    $tm$https://www.tomsofmaine.com/products/whole-care-natural-peppermint-toothpaste-with-fluoride$tm$,
    'direct',
    $tm$https://www.tomsofmaine.com/cdn/shop/files/US05800A_primary_68e21c98-e274-4cd1-87cd-a71f70e2807c.jpg?v=1744048214&width=600$tm$,
    4.6,
    0,
    $tm$4 oz$tm$,
    $tm$$tm$,
    $tm$Anticavity$tm$,
    $tm$$tm$,
    $tm$$tm$,
    array[$f$Anticavity$f$]::text[],
    true,
    $tm$catoegy$tm$
  )
on conflict (slug) do update set
  brand_id = excluded.brand_id,
  name = excluded.name,
  category = excluded.category,
  category_id = excluded.category_id,
  price = excluded.price,
  description = excluded.description,
  accent = excluded.accent,
  badge = excluded.badge,
  affiliate_url = excluded.affiliate_url,
  affiliate_network = excluded.affiliate_network,
  image_url = excluded.image_url,
  rating = excluded.rating,
  review_count = excluded.review_count,
  size = excluded.size,
  how_to_use = excluded.how_to_use,
  good_for = excluded.good_for,
  features = excluded.features,
  is_published = excluded.is_published,
  placed_by = excluded.placed_by;
