insert into public.products (
  id, slug, brand_id, name, category, category_id, price, description, accent,
  badge, affiliate_url, affiliate_network, image_url, rating, review_count,
  size, how_to_use, good_for, smells_like, finish, features, is_published, placed_by
) values
  (
    'c0000000-0000-0000-0000-000000000004',
    $tm$whiten-plus-deep-clean-whitening-toothpaste-spearmint$tm$,
    (select id from public.brands where slug = 'toms-of-maine'),
    $tm$Whiten Plus Deep Clean Whitening Spearmint Natural Toothpaste$tm$,
    'oral',
    (select id from public.categories where slug = 'oral'),
    7.99,
    $tm$Discover a whiter smile with Tom’s of Maine Whiten Plus Deep Clean Whitening Toothpaste. This enamel-safe whitening toothpaste helps whiten without causing sensitivity, removes up to 95% of surface stains*, and doubles as an anticavity toothpaste.$tm$,
    $tm$#2D6A4F$tm$,
    null,
    $tm$https://www.tomsofmaine.com/products/whiten-plus-deep-clean-whitening-toothpaste-spearmint$tm$,
    'direct',
    $tm$https://www.tomsofmaine.com/cdn/shop/files/61046077_Packshot_Front_In_Package_288df438-66ca-48c5-9f75-75d4d09e24a2.jpg?v=1744048284&width=800$tm$,
    4.6,
    0,
    $tm$4 oz$tm$,
    $tm$$tm$,
    $tm$Whitening; Removes Stains; Clinically Proven Whitening$tm$,
    $tm$$tm$,
    $tm$$tm$,
    array[$f$Whitening$f$, $f$Removes Stains$f$, $f$Clinically Proven Whitening$f$, $f$Natural Oral Care$f$, $f$Anticavity$f$]::text[],
    true,
    $tm$catoegy$tm$
  )
on conflict (slug) do update set
  brand_id = excluded.brand_id,
  name = excluded.name,
  category = excluded.category,
  category_id = excluded.category_id,
  price = excluded.price,
  description = excluded.description,
  accent = excluded.accent,
  badge = excluded.badge,
  affiliate_url = excluded.affiliate_url,
  affiliate_network = excluded.affiliate_network,
  image_url = excluded.image_url,
  rating = excluded.rating,
  review_count = excluded.review_count,
  size = excluded.size,
  how_to_use = excluded.how_to_use,
  good_for = excluded.good_for,
  features = excluded.features,
  is_published = excluded.is_published,
  placed_by = excluded.placed_by;
