insert into public.products (
  id, slug, brand_id, name, category, category_id, price, description, accent,
  badge, affiliate_url, affiliate_network, image_url, rating, review_count,
  size, how_to_use, good_for, smells_like, finish, features, is_published, placed_by
) values
  (
    'c0000000-0000-0000-0000-000000000033',
    $tm$wicked-fresh-cool-peppermint-fluoride-natural-toothpaste-new-sku$tm$,
    (select id from public.brands where slug = 'toms-of-maine'),
    $tm$Wicked Fresh! Cool Peppermint Fluoride Natural Toothpaste$tm$,
    'oral',
    (select id from public.categories where slug = 'oral'),
    7.99,
    $tm$Fresh breath is only a brush away with Tom’s of Maine Wicked Fresh! Natural Anticavity Toothpaste with Fluoride. The Toothpaste features an updated formula that tastes great and leaves your mouth clean and fresh with its Cool Peppermint flavor.$tm$,
    $tm$#2D6A4F$tm$,
    null,
    $tm$https://www.tomsofmaine.com/products/wicked-fresh-cool-peppermint-fluoride-natural-toothpaste-new-sku$tm$,
    'direct',
    $tm$https://www.tomsofmaine.com/cdn/shop/files/4y7UkF114qOtJnGiWtA3n.png?v=1772123177&width=800$tm$,
    4.6,
    0,
    $tm$4 oz$tm$,
    $tm$$tm$,
    $tm$$tm$,
    $tm$$tm$,
    $tm$$tm$,
    array[]::text[],
    true,
    $tm$catoegy$tm$
  )
on conflict (slug) do update set
  brand_id = excluded.brand_id,
  name = excluded.name,
  category = excluded.category,
  category_id = excluded.category_id,
  price = excluded.price,
  description = excluded.description,
  accent = excluded.accent,
  badge = excluded.badge,
  affiliate_url = excluded.affiliate_url,
  affiliate_network = excluded.affiliate_network,
  image_url = excluded.image_url,
  rating = excluded.rating,
  review_count = excluded.review_count,
  size = excluded.size,
  how_to_use = excluded.how_to_use,
  good_for = excluded.good_for,
  features = excluded.features,
  is_published = excluded.is_published,
  placed_by = excluded.placed_by;
