insert into public.products (
  id, slug, brand_id, name, category, category_id, price, description, accent,
  badge, affiliate_url, affiliate_network, image_url, rating, review_count,
  size, how_to_use, good_for, smells_like, finish, features, is_published, placed_by
) values
  (
    'c0000000-0000-0000-0000-000000000019',
    $tm$natural-activated-charcoal-peppermint-toothpaste-with-fluoride$tm$,
    (select id from public.brands where slug = 'toms-of-maine'),
    $tm$Activated Charcoal Peppermint Natural Toothpaste with Fluoride$tm$,
    'oral',
    (select id from public.categories where slug = 'oral'),
    7.99,
    $tm$Experience a bright smile and help prevent cavities with the Tom’s of Maine Natural Activated Charcoal Toothpaste with Fluoride. This fluoride toothpaste uses naturally sourced and derived ingredients and comes in a refreshing Peppermint flavor to keep your breath minty fresh.$tm$,
    $tm$#2D6A4F$tm$,
    null,
    $tm$https://www.tomsofmaine.com/products/natural-activated-charcoal-peppermint-toothpaste-with-fluoride$tm$,
    'direct',
    $tm$https://www.tomsofmaine.com/cdn/shop/files/61038016_primary_ce2e18f7-0547-413e-ad85-882c14106d39.jpg?v=1744048269&width=600$tm$,
    4.6,
    0,
    $tm$4 oz$tm$,
    $tm$$tm$,
    $tm$Contains Fluoride; Anticavity; Whitening$tm$,
    $tm$$tm$,
    $tm$$tm$,
    array[$f$Contains Fluoride$f$, $f$Anticavity$f$, $f$Whitening$f$, $f$<br />$f$, $f$Made with naturally sourced and derived ingredients$f$]::text[],
    true,
    $tm$catoegy$tm$
  )
on conflict (slug) do update set
  brand_id = excluded.brand_id,
  name = excluded.name,
  category = excluded.category,
  category_id = excluded.category_id,
  price = excluded.price,
  description = excluded.description,
  accent = excluded.accent,
  badge = excluded.badge,
  affiliate_url = excluded.affiliate_url,
  affiliate_network = excluded.affiliate_network,
  image_url = excluded.image_url,
  rating = excluded.rating,
  review_count = excluded.review_count,
  size = excluded.size,
  how_to_use = excluded.how_to_use,
  good_for = excluded.good_for,
  features = excluded.features,
  is_published = excluded.is_published,
  placed_by = excluded.placed_by;
