insert into public.products (
  id, slug, brand_id, name, category, category_id, price, description, accent,
  badge, affiliate_url, affiliate_network, image_url, rating, review_count,
  size, how_to_use, good_for, smells_like, finish, features, is_published, placed_by
) values
  (
    'c0000000-0000-0000-0000-000000000001',
    $tm$adult-holiday-brush-and-rinse-bundle$tm$,
    (select id from public.brands where slug = 'toms-of-maine'),
    $tm$Adult Holiday Brush & Rinse Bundle$tm$,
    'oral',
    (select id from public.categories where slug = 'oral'),
    17.99,
    $tm$1x Fluoride-Free Antiplaque & Whitening Fennel Toothpaste 1x Fresh Mint Whole Care Anticavity Natural Mouthwash 1x Naturally Clean Soft Toothbrush Twin Pack This set brings together three everyday essentials to help support a simple and consistent oral care routine during a busy…$tm$,
    $tm$#2D6A4F$tm$,
    null,
    $tm$https://www.tomsofmaine.com/products/adult-holiday-brush-and-rinse-bundle$tm$,
    'direct',
    $tm$https://www.tomsofmaine.com/cdn/shop/files/toms_pdp-hero_adult-holiday.jpg?v=1762891861&width=800$tm$,
    4.6,
    0,
    $tm$$tm$,
    $tm$$tm$,
    $tm$Anticavity; Whitening$tm$,
    $tm$$tm$,
    $tm$$tm$,
    array[$f$Anticavity$f$, $f$Whitening$f$]::text[],
    true,
    $tm$catoegy$tm$
  )
on conflict (slug) do update set
  brand_id = excluded.brand_id,
  name = excluded.name,
  category = excluded.category,
  category_id = excluded.category_id,
  price = excluded.price,
  description = excluded.description,
  accent = excluded.accent,
  badge = excluded.badge,
  affiliate_url = excluded.affiliate_url,
  affiliate_network = excluded.affiliate_network,
  image_url = excluded.image_url,
  rating = excluded.rating,
  review_count = excluded.review_count,
  size = excluded.size,
  how_to_use = excluded.how_to_use,
  good_for = excluded.good_for,
  features = excluded.features,
  is_published = excluded.is_published,
  placed_by = excluded.placed_by;
