insert into public.products (
  id, slug, brand_id, name, category, category_id, price, description, accent,
  badge, affiliate_url, affiliate_network, image_url, rating, review_count,
  size, how_to_use, good_for, smells_like, finish, features, is_published, placed_by
) values
  (
    'c0000000-0000-0000-0000-000000000011',
    $tm$wicked-cool-natural-mild-mint-toothpaste-for-kids-with-fluoride$tm$,
    (select id from public.brands where slug = 'toms-of-maine'),
    $tm$Wicked Cool! Natural Mild Mint Toothpaste for Kids with Fluoride$tm$,
    'oral',
    (select id from public.categories where slug = 'oral'),
    6.49,
    $tm$Too old for fruity flavors. Not ready for the strong taste of mint. Make one part of the transition to adulthood a little easier with Tom's of Maine Wicked Cool! Natural Toothpaste for Kids.$tm$,
    $tm$#2D6A4F$tm$,
    null,
    $tm$https://www.tomsofmaine.com/products/wicked-cool-natural-mild-mint-toothpaste-for-kids-with-fluoride$tm$,
    'direct',
    $tm$https://www.tomsofmaine.com/cdn/shop/files/US06382A_primary_4fc1ec06-2a0d-4ce4-a551-ddac10ebda3b.jpg?v=1774554889&width=600$tm$,
    4.6,
    0,
    $tm$5.1 oz$tm$,
    $tm$$tm$,
    $tm$Contains Fluoride; Anticavity; Recyclable/100% Recyclable$tm$,
    $tm$$tm$,
    $tm$$tm$,
    array[$f$Contains Fluoride$f$, $f$Anticavity$f$, $f$Recyclable/100% Recyclable$f$, $f$WHAT YOU'LL GET$f$, $f$FIGHT CAVITIES$f$, $f$TASTE THEY LOVE$f$]::text[],
    true,
    $tm$catoegy$tm$
  )
on conflict (slug) do update set
  brand_id = excluded.brand_id,
  name = excluded.name,
  category = excluded.category,
  category_id = excluded.category_id,
  price = excluded.price,
  description = excluded.description,
  accent = excluded.accent,
  badge = excluded.badge,
  affiliate_url = excluded.affiliate_url,
  affiliate_network = excluded.affiliate_network,
  image_url = excluded.image_url,
  rating = excluded.rating,
  review_count = excluded.review_count,
  size = excluded.size,
  how_to_use = excluded.how_to_use,
  good_for = excluded.good_for,
  features = excluded.features,
  is_published = excluded.is_published,
  placed_by = excluded.placed_by;
