insert into public.products (
  id, slug, brand_id, name, category, category_id, price, description, accent,
  badge, affiliate_url, affiliate_network, image_url, rating, review_count,
  size, how_to_use, good_for, smells_like, finish, features, is_published, placed_by
) values
  (
    'c0000000-0000-0000-0000-000000000015',
    $tm$grab-n-go-travel-size-fluoride-free-fresh-mint-toothpaste$tm$,
    (select id from public.brands where slug = 'toms-of-maine'),
    $tm$Grab n' Go Travel Size Fluoride-Free Fresh Mint Natural Toothpaste$tm$,
    'oral',
    (select id from public.categories where slug = 'oral'),
    4.49,
    $tm$Take Tom's on the road. This great-tasting, everyday natural toothpaste whitens teeth with naturally sourced silicas and freshens breath with pure peppermint leaf oil. And it's fluoride-free. Comes in a 3. ounce, TSA Accepted Travel size, making it the perfect travel companion.$tm$,
    $tm$#2D6A4F$tm$,
    null,
    $tm$https://www.tomsofmaine.com/products/grab-n-go-travel-size-fluoride-free-fresh-mint-toothpaste$tm$,
    'direct',
    $tm$https://www.tomsofmaine.com/cdn/shop/files/683260_primary_84b730af-012f-4750-9a6d-b76569bb78b0.jpg?v=1744048228&width=600$tm$,
    4.6,
    0,
    $tm$3 oz$tm$,
    $tm$$tm$,
    $tm$Travel Size/ TSA Accepted; Whitening; Vegan$tm$,
    $tm$$tm$,
    $tm$$tm$,
    array[$f$Travel Size/ TSA Accepted$f$, $f$Whitening$f$, $f$Vegan$f$, $f$Fluoride-free$f$, $f$No artificial flavors, colors, or preservatives$f$, $f$Vegan - no animal ingredient$f$]::text[],
    true,
    $tm$catoegy$tm$
  )
on conflict (slug) do update set
  brand_id = excluded.brand_id,
  name = excluded.name,
  category = excluded.category,
  category_id = excluded.category_id,
  price = excluded.price,
  description = excluded.description,
  accent = excluded.accent,
  badge = excluded.badge,
  affiliate_url = excluded.affiliate_url,
  affiliate_network = excluded.affiliate_network,
  image_url = excluded.image_url,
  rating = excluded.rating,
  review_count = excluded.review_count,
  size = excluded.size,
  how_to_use = excluded.how_to_use,
  good_for = excluded.good_for,
  features = excluded.features,
  is_published = excluded.is_published,
  placed_by = excluded.placed_by;
