insert into public.products (
  id, slug, brand_id, name, category, category_id, price, description, accent,
  affiliate_url, affiliate_network, image_url, rating, review_count,
  size, how_to_use, good_for, smells_like, finish, features, is_published
) values
  (
    'f0000000-0000-0000-0000-000000000001',
    'solar-shield-spray',
    (select id from public.brands where slug = 'freaks-of-nature'),
    'Solar Shield SPF 30 Spray',
    'sunscreen',
    (select id from public.categories where slug = 'sunscreen'),
    26,
    'Full-body mineral protection',
    '#2F6F5E',
    'https://freaksofnature.com/products/solar-shield-spray',
    'direct',
    'https://freaksofnature.com/cdn/shop/files/3D_SPRAY_E-COMM.png?v=1777037746&width=1920',
    4.9,
    117,
    '6 oz / 170 g',
    'Shake well before use. Hold container 4--6 inches from skin and spray liberally and evenly across the body. Rub into skin. Apply 15 minutes before sun exposure. Reapply after 40 minutes of swimming or sweating, immediately after towel drying, and at least every 2 hours.',
    'All skin types',
    'Nothing! Unlike the painfully nostalgic odor (i.e. harsh and chemically) of most sunscreens, ours is completely unscented.',
    'Lightweight, breathable, and nearly invisible on skin.',
    array['100% mineral protection', 'Air-powered continuous spray', 'Minimal white cast', 'Hydrates + soothes', 'Protects + strengthens skin barrier', 'No chemical filters', 'Water resistant (40 min)', 'Dermatologist tested', 'Broad spectrum UV protection', 'Reef safe', 'Fragrance free']::text[],
    true
  ),
  (
    'f0000000-0000-0000-0000-000000000002',
    'sun-stick-spf50',
    (select id from public.brands where slug = 'freaks-of-nature'),
    'Peak Performance Sun Stick SPF50',
    'sunscreen',
    (select id from public.categories where slug = 'sunscreen'),
    24,
    '100% Mineral Sunscreen High-performance, lightweight non-greasy, broad spectrum protection for the long haul.',
    '#2F6F5E',
    'https://freaksofnature.com/products/sun-stick-spf50',
    'direct',
    'https://freaksofnature.com/cdn/shop/files/STICK-web-optimized-transparent.png?v=1775474333&width=1920',
    4.9,
    189,
    '0.70 oz / 20 gr',
    '15 minutes before going in the sun liberally apply onto face, neck, chest and body if applicable. Reapply after 80 min of swimming or sweating, immediately after towel drying and at least every 2 hours when exposed to the sun. Product can be re-applied over or under makeup.',
    'All Skin Types',
    'Nothing! Unlike the painfully nostalgic odor (i.e. harsh and chemically) of most sunscreens, ours is completely unscented.',
    'Goes on silky smooth, clear, and easily with a bare skin feel that will not warp, slip or drip into the eyes.',
    array['100% mineral protection', 'Water resistant (40 min)', 'Protects + strengthens skin barrier', 'Broad spectrum UV protection', 'Fragrance free', 'Reef safe', 'Dermatologist tested', 'Minimal white cast']::text[],
    true
  ),
  (
    'f0000000-0000-0000-0000-000000000003',
    'everyday-endurance-deodorant',
    (select id from public.brands where slug = 'freaks-of-nature'),
    'Everyday Endurance Deodorant',
    'deodorant',
    (select id from public.categories where slug = 'deodorant'),
    20,
    'All natural with 48-hour odor protection',
    '#2F6F5E',
    'https://freaksofnature.com/products/everyday-endurance-deodorant',
    'direct',
    'https://freaksofnature.com/cdn/shop/files/Single_Deo.png?v=1776275794&width=1920',
    4.2,
    55,
    '75ml / 2.6 fl oz',
    '**Step 1:**Remove top and twist the bottom until formula begins to appear from perforated cap (Do not overtwist! A little goes a long way) **Step 2:**Apply formula directly on clean, dry underarms -- damp skin reduces effectiveness. **Step 3:**Apply formula directly on underarm For best results, keep deodorant at room temperature (68°F to 77°F / 20°C to 25°C)',
    'All skin types',
    'Warm amber and smooth santal finished with earthy spice.',
    'A creamy texture that dries within 30 seconds. Not sticky or wet and lasts for 48 hours. In our perception study 93% of users found that the deo did not leave stains or marks on clothing.',
    array['Dermatologist tested', 'Protects + strengthens skin barrier', 'Fragrance free']::text[],
    true
  ),
  (
    'f0000000-0000-0000-0000-000000000004',
    'jumbo-sun-stick',
    (select id from public.brands where slug = 'freaks-of-nature'),
    'Peak Performance Jumbo Sun Stick',
    'sunscreen',
    (select id from public.categories where slug = 'sunscreen'),
    44,
    '100% Mineral Sunscreen',
    '#2F6F5E',
    'https://freaksofnature.com/products/jumbo-sun-stick',
    'direct',
    'https://freaksofnature.com/cdn/shop/files/3D_STICK-SPF50_L_E-COMM.png?v=1776776007&width=1920',
    4.9,
    189,
    '2.60 oz / 75 gr',
    '15 minutes before going in the sun liberally apply onto face, neck, chest and body if applicable. Reapply after 80 min of swimming or sweating, immediately after towel drying and at least every 2 hours when exposed to the sun. Product can be re-applied over or under makeup.',
    'All Skin Types',
    'Nothing! Unlike the painfully nostalgic odor (i.e. harsh and chemically) of most sunscreens, ours is completely unscented.',
    'Goes on silky smooth, clear, and easily with a bare skin feel that will not warp, slip or drip into the eyes.',
    array['100% mineral protection', 'Water resistant (40 min)', 'Protects + strengthens skin barrier', 'Broad spectrum UV protection', 'Reef safe', 'Fragrance free', 'Dermatologist tested', 'Minimal white cast']::text[],
    true
  ),
  (
    'f0000000-0000-0000-0000-000000000005',
    'peak-performance-sunscreen',
    (select id from public.brands where slug = 'freaks-of-nature'),
    'Peak Performance SPF50',
    'sunscreen',
    (select id from public.categories where slug = 'sunscreen'),
    38,
    '100% Mineral Sunscreen High-performance, lightweight non-greasy, broad spectrum protection for the long haul.',
    '#2F6F5E',
    'https://freaksofnature.com/products/peak-performance-sunscreen',
    'direct',
    'https://freaksofnature.com/cdn/shop/files/SPF50-web-optimized-transparent.png?v=1743441572&width=1920',
    4.8,
    76,
    '50 ml / 1.7 fl oz',
    '**Step 1:**Complete the skincare routine. We recommend priming the skin with a pump of our Deeper Dive Moisturizer. **Step 2:**Apply Peak Performance SPF50 Sunscreen in the morning before you go outside, or 15 minutes before going in the sun, and as the final step in the daily skincare routine. Apply one pump amount or more of our Peak Performance SPF50 Sunscreen into hands and gently rub onto face, neck, chest and body if applicable. Reapply after 80 min of swimming or sweating, immediately after towel drying and at least every 2 hours when exposed to the sun.',
    'All Skin Types',
    'Nothing! Unlike the painfully nostalgic odor (i.e. harsh and chemically) of most sunscreens, ours is completely unscented.',
    'Cream like consistency to be applied as last step in routine and rubbed into skin.',
    array['100% mineral protection', 'Water resistant (40 min)', 'Dermatologist tested', 'Broad spectrum UV protection', 'Reef safe', 'Fragrance free', 'Minimal white cast', 'Protects + strengthens skin barrier']::text[],
    true
  ),
  (
    'f0000000-0000-0000-0000-000000000006',
    'deeper-dive-moisturizer',
    (select id from public.brands where slug = 'freaks-of-nature'),
    'Deeper Dive Hydrator',
    'skincare',
    (select id from public.categories where slug = 'skincare'),
    48,
    'Ultralight Moisturizer A deeper moisture that strengthens the skin barrier.',
    '#2F6F5E',
    'https://freaksofnature.com/products/deeper-dive-moisturizer',
    'direct',
    'https://freaksofnature.com/cdn/shop/files/HYDRATOR-web-optimized_transparent.png?v=1743441773&width=1920',
    5,
    62,
    '50 ml / 1.7 fl oz',
    '**Step 1:**After AM/PM cleansing, or when you wash yourself after a workout session, apply one pump amount into hands and gently rub onto face, neck and chest if applicable. For optimal results use in the AM and PM. **Step 2:**If heading outside apply Daily Defender SPF30 Sunscreen as the final step in the daily routine.',
    'All Skin Types',
    'Minerally with a slight nuttiness. Think of it like a crisp day near the lake!',
    'Natural oil color and texture for maximum hydration without the greasy look.',
    array['Hydrates + soothes', 'Protects + strengthens skin barrier', 'Dermatologist tested']::text[],
    true
  ),
  (
    'f0000000-0000-0000-0000-000000000007',
    'daily-defender-sunscreen',
    (select id from public.brands where slug = 'freaks-of-nature'),
    'Daily Defender SPF30',
    'sunscreen',
    (select id from public.categories where slug = 'sunscreen'),
    35,
    '100% Mineral Sunscreen Lightweight, fast-absorbing, broad spectrum everyday protection.',
    '#2F6F5E',
    'https://freaksofnature.com/products/daily-defender-sunscreen',
    'direct',
    'https://freaksofnature.com/cdn/shop/files/SPF30-web-optimized-transparent.png?v=1743441677&width=1920',
    4.9,
    99,
    '50 ml / 1.7 fl oz',
    '**Step 1:** Complete the skincare routine. We recommend priming the skin with a pump of our [Deeper Dive Moisturizer(Deeper Dive Moisturizer)](https://freaksofnature.com/products/deeper-dive-moisturizer). **Step 2:**Apply Daily Defender SPF30 Sunscreen in the morning before you go outside, or 15 minutes before going in the sun, and as the final step in the daily skincare routine. Apply one pump amount or more of our Daily Defender SPF30 Sunscreen into hands and gently rub onto face, neck, chest and body if applicable. Reapply after 40 min of swimming or sweating, immediately after towel drying and at least every 2 hours when exposed to the sun.',
    'All Skin Types',
    'Nothing! Unlike the painfully nostalgic odor (i.e. harsh and chemically) of most sunscreens, ours is completely unscented.',
    'Lightweight, breathable, and nearly invisible on skin.',
    array['100% mineral protection', 'Minimal white cast', 'Hydrates + soothes', 'Protects + strengthens skin barrier', 'No chemical filters', 'Water resistant (40 min)', 'Dermatologist tested', 'Broad spectrum UV protection', 'Reef safe', 'Fragrance free']::text[],
    true
  ),
  (
    'f0000000-0000-0000-0000-000000000008',
    'barrier-balancing-cleanser',
    (select id from public.brands where slug = 'freaks-of-nature'),
    'Barrier Balancing Face Wash',
    'skincare',
    (select id from public.categories where slug = 'skincare'),
    30,
    'Foaming Gel-to-Oil',
    '#2F6F5E',
    'https://freaksofnature.com/products/barrier-balancing-cleanser',
    'direct',
    'https://freaksofnature.com/cdn/shop/files/3D_CLEANSER_LIGHTBLUE_E-COMM.png?v=1748386004&width=1920',
    4.6,
    25,
    '100 ml / 3.4 fl oz',
    '**Step 1:**After a long day, sweat sesh, or time spent in the sun. Apply 1-2 pumps of barrier balancing cleanser to dry or wet face. Rub into skin to release grime. **Step 2:**Add water to skin as cleanser begins to froth into a milky texture, helping further cleanse and hydrate the skin. **Step 3:**Towel dry skin. For best results, apply Deeper Dive Hydrator post-cleanse',
    'All Skin Types',
    'Light mineral scent',
    'Luxe oil-gel in a light mint blue that transforms into a white frothy milk when activated with water',
    array['Hydrates + soothes', 'Protects + strengthens skin barrier', 'Dermatologist tested', 'Fragrance free']::text[],
    true
  ),
  (
    'f0000000-0000-0000-0000-000000000009',
    'freaks-full-coverage-bundle',
    (select id from public.brands where slug = 'freaks-of-nature'),
    'Freaks Full Coverage Bundle',
    'sunscreen',
    (select id from public.categories where slug = 'sunscreen'),
    84,
    'Jumbo + Original Sun Stick & SPF Spray',
    '#2F6F5E',
    'https://freaksofnature.com/products/freaks-full-coverage-bundle',
    'direct',
    'https://freaksofnature.com/cdn/shop/files/STICK_JUMBO_SPRAY_E-COMM-copy1.png?v=1777478755&width=1920',
    4.9,
    301,
    'Solar Shield SPF 30 Spray: 6 oz / 170 g; Peak Performance Jumbo Sun Stick: 2.60 oz / 75 gr; Peak Performance Sun Stick: 0.70 oz / 20 gr',
    '**Sun Stick SPF 50** 15 minutes before going in the sun liberally apply onto face, neck, chest and body if applicable. Reapply after 80 min of swimming or sweating, immediately after towel drying and at least every 2 hours when exposed to the sun. Product can be reapplied over or under makeup. **Solar Shield SPF 30 Spray** Shake well before use. Hold container 4--6 inches from skin and spray liberally and evenly across the body. Rub into skin. Apply 15 minutes before sun exposure. Reapply after 40 minutes of swimming or sweating, immediately after towel drying, and at least every 2 hours.',
    '',
    '',
    '',
    array['100% mineral protection', 'Air-powered continuous spray', 'Minimal white cast', 'Hydrates + soothes', 'Protects + strengthens skin barrier', 'No chemical filters', 'Water resistant (40 min)', 'Dermatologist tested', 'Broad spectrum UV protection', 'Reef safe', 'Fragrance free']::text[],
    true
  ),
  (
    'f0000000-0000-0000-0000-000000000010',
    'sun-stick-set',
    (select id from public.brands where slug = 'freaks-of-nature'),
    'Sun Stick Set',
    'sunscreen',
    (select id from public.categories where slug = 'sunscreen'),
    61,
    'Jumbo + Original Sun Stick',
    '#2F6F5E',
    'https://freaksofnature.com/products/sun-stick-set',
    'direct',
    'https://freaksofnature.com/cdn/shop/files/STICK_JUMBO_E-COMM-copy.png?v=1777043493&width=1920',
    4.9,
    189,
    'Original: 0.70 oz / 20 gr, Jumbo: 2.60 oz / 75 gr',
    '15 minutes before going in the sun liberally apply onto face, neck, chest and body if applicable. Reapply after 80 min of swimming or sweating, immediately after towel drying and at least every 2 hours when exposed to the sun. Product can be re-applied over or under makeup.',
    'All Skin Types',
    'Nothing! Unlike the painfully nostalgic odor (i.e. harsh and chemically) of most sunscreens, ours is completely unscented.',
    'Goes on silky smooth, clear, and easily with a bare skin feel that will not warp, slip or drip into the eyes.',
    array['100% mineral protection', 'Water resistant (40 min)', 'Dermatologist tested', 'Broad spectrum UV protection', 'Reef safe', 'Fragrance free', 'Minimal white cast', 'Protects + strengthens skin barrier']::text[],
    true
  ),
  (
    'f0000000-0000-0000-0000-000000000011',
    'body-by-freaks-bundle',
    (select id from public.brands where slug = 'freaks-of-nature'),
    'Body By Freaks Bundle',
    'sunscreen',
    (select id from public.categories where slug = 'sunscreen'),
    63,
    'Jumbo SPF50 Sun Stick + SPF 30 Spray',
    '#2F6F5E',
    'https://freaksofnature.com/products/body-by-freaks-bundle',
    'direct',
    'https://freaksofnature.com/cdn/shop/files/BODY_BY_FREAKS.png?v=1777478348&width=1920',
    4.9,
    163,
    '6 oz / 170 g (Spray) + 2.60 oz / 75 gr (Stick)',
    '**Sun Stick SPF 50** 15 minutes before going in the sun liberally apply onto face, neck, chest and body if applicable. Reapply after 80 min of swimming or sweating, immediately after towel drying and at least every 2 hours when exposed to the sun. Product can be reapplied over or under makeup. **Solar Shield SPF 30 Spray** Shake well before use. Hold container 4--6 inches from skin and spray liberally and evenly across the body. Rub into skin. Apply 15 minutes before sun exposure. Reapply after 40 minutes of swimming or sweating, immediately after towel drying, and at least every 2 hours.',
    '',
    'Fragrance-free',
    '',
    array['100% mineral protection', 'Air-powered continuous spray', 'Minimal white cast', 'Hydrates + soothes', 'Protects + strengthens skin barrier', 'No chemical filters', 'Water resistant (40 min)', 'Dermatologist tested', 'Broad spectrum UV protection', 'Reef safe', 'Fragrance free']::text[],
    true
  ),
  (
    'f0000000-0000-0000-0000-000000000012',
    'freak-family-pack-v3',
    (select id from public.brands where slug = 'freaks-of-nature'),
    'Freak Family Pack',
    'skincare',
    (select id from public.categories where slug = 'skincare'),
    193.5,
    'Full Freak Assortment Strengthen. Protect. Repair. Repeat.',
    '#2F6F5E',
    'https://freaksofnature.com/products/freak-family-pack-v3',
    'direct',
    'https://freaksofnature.com/cdn/shop/files/FreakFamily_Transparent.png?v=1761686298&width=2400',
    4.8,
    444,
    'Daily Defender SPF30: 50 ml / 1.7 fl oz; Deeper Dive Hydrator: 50 ml / 1.7 fl oz; Peak Performance SPF50: 50 ml / 1.7 fl oz; Peak Performance Sun Stick SPF50: 0.70 oz / 20 gr; Barrier Balancing Face Wash: 100 ml / 3.4 fl oz; Everyday Endurance Deodorant: 75ml / 2.6 fl oz',
    '**Deep Dive Hydrator** **Step 1:**After AM/PM cleansing, or when you wash yourself after a workout session, apply one pump amount into hands and gently rub onto face, neck and chest if applicable. For optimal results use in the AM and PM. **Step 2:**If heading outside apply Daily Defender SPF30 Sunscreen as the final step in the daily routine. **Daily Defender SPF30** **Step 1:**Complete the skincare routine. We recommend priming the skin with a pump of our Deep Dive Hydrator. **Step 2:**Apply Daily Defender SPF30 Sunscreen in the morning before you go outside, or 15 minutes before going in the sun, and as the final step in the daily skincare routine. Apply one pump amount or more of our Daily Defender SPF30 Sunscreen into hands and gently rub onto face, neck, chest and body if applicable. Reapply after 40 min of swimming or sweating, immediately after towel drying and at least every 2 hours when exposed to the sun. **Peak Performance SPF50** **Step 1:**Complete the skincare routine. We recommend priming the skin with a pump of our Deeper Dive Moisturizer. **Step 2:**Apply Peak Performance SPF50 Sunscreen in the morning before you go outside, or 15 minutes before going in the sun, and as the final step in the daily skincare routine. Apply one pump amount or more of our Peak Performance SPF50 Sunscreen into hands and gently rub onto face, neck, chest and body if applicable. Reapply after 80 min of swimming or sweating, immediately after towel drying and at least every 2 hours when exposed to the sun. **Peak Performance SPF50 Sun Stick** 15 minutes before going in the sun liberally apply onto face, neck, chest and body if applicable.Reapply after 80 min of swimming or sweating, immediately after towel drying and at least every 2 hours when exposed to the sun. Product can be re-applied over or under makeup. **Barrier Balancing Face Wash** **Step 1:**After a long day, sweat sesh, or time spent in the sun. Apply 1-2 pumps of barrier balancing face wash to dry or wet face. Rub into skin to release grime. **Step 2:**Add water to skin as face wash begins to froth into a milky texture, helping further cleanse and hydrate the skin. **Step 3:**Towel dry skin. For best results, apply Deeper Dive Hydrator post-cleanse **Everyday Endurance Deodorant** **Step 1:**Remove top and twist the bottom until formula begins to appear from perforated cap (Do not overtwist! A little goes a long way) **Step 2:**Apply formula directly on clean, dry underarms -- damp skin reduces effectiveness. **Step 3:**Store in a cool, dry place',
    'All Skin Types',
    '**Deeper Dive Hydrator:** Minerally with a slight nuttiness. Think of it like a crisp day near the lake! **Sun Stick & SPF30 & 50:** Nothing! Unlike the painfully nostalgic odor (i.e. harsh and chemically) of most sunscreens, ours is completely unscented. **Everyday Endurance Deodorant Scents:** **Santal Dune:** Warm amber and smooth santal finished with earthy spice. **Bergamot Canyon:** Bright citrus and neroli with a crisp oakmoss and bergamot finish',
    '**Deeper Dive Hydrator:** Natural oil color and texture for maximum hydration without the greasy look. **Daily Defender SPF30:** Silky smooth and white. But do not let the color fool you, this will not leave you looking like a ghost. **Peak Performance SPF50:** Cream like consistency to be applied as last step in routine and rubbed into skin. **Peak Performance Sun Stick:** Freakishly easy to apply. Goes on silky smooth with minimal whitecast. **Barrier Balancing Face Wash:** Luxe oil-gel in a light mint blue that transforms into a white frothy milk when activated with water. **Everyday Endurance Deodorant:** A creamy texture that dries within 30 seconds. Not sticky or wet and lasts for 48 hours.',
    array['100% mineral protection', 'Protects + strengthens skin barrier', 'Dermatologist tested', 'Broad spectrum UV protection', 'Reef safe', 'Fragrance free']::text[],
    true
  ),
  (
    'f0000000-0000-0000-0000-000000000013',
    'freak-trio',
    (select id from public.brands where slug = 'freaks-of-nature'),
    'Freak Trio',
    'sunscreen',
    (select id from public.categories where slug = 'sunscreen'),
    108.9,
    'SPF50 Sunscreen & SPF30 Sunscreen & Hydrator Strengthen. Protect. Repair. Repeat.',
    '#2F6F5E',
    'https://freaksofnature.com/products/freak-trio',
    'direct',
    'https://freaksofnature.com/cdn/shop/files/SPF50-_-SPF30-_-HYDRATOR-web-optimized-transparent_2.png?v=1743566002&width=1920',
    4.9,
    247,
    '50 ml / 1.7 fl oz per product',
    '**Daily Defender SPF30** **Step 1:**Complete the skincare routine. We recommend priming the skin with a pump of our Deep Dive Hydrator. **Step 2:**Apply Daily Defender SPF30 Sunscreen in the morning before you go outside, or 15 minutes before going in the sun, and as the final step in the daily skincare routine. Apply one pump amount or more of our Daily Defender SPF30 Sunscreen into hands and gently rub onto face, neck, chest and body if applicable. Reapply after 40 min of swimming or sweating, immediately after towel drying and at least every 2 hours when exposed to the sun. **Peak Performance SPF50** **Step 1:**Complete the skincare routine. We recommend priming the skin with a pump of our Deeper Dive Moisturizer. **Step 2:**Apply Peak Performance SPF50 Sunscreen in the morning before you go outside, or 15 minutes before going in the sun, and as the final step in the daily skincare routine. Apply one pump amount or more of our Peak Performance SPF50 Sunscreen into hands and gently rub onto face, neck, chest and body if applicable. Reapply after 80 min of swimming or sweating, immediately after towel drying and at least every 2 hours when exposed to the sun. **Deep Dive Hydrator** **Step 1:**After AM/PM cleansing, or when you wash yourself after a workout session, apply one pump amount into hands and gently rub onto face, neck and chest if applicable. For optimal results use in the AM and PM. **Step 2:**If heading outside apply Daily Defender SPF30 Sunscreen as the final step in the daily routine.',
    '',
    '',
    '',
    array['100% mineral protection', 'No chemical filters', 'Broad spectrum UV protection', 'Minimal white cast', 'Dermatologist tested']::text[],
    true
  ),
  (
    'f0000000-0000-0000-0000-000000000014',
    'peak-performance-duo',
    (select id from public.brands where slug = 'freaks-of-nature'),
    'Peak Performance Duo',
    'sunscreen',
    (select id from public.categories where slug = 'sunscreen'),
    55.8,
    'SPF50 Sunscreen & SPF50 Stick High-performance, lightweight non-greasy, broad spectrum protection for the long haul.',
    '#2F6F5E',
    'https://freaksofnature.com/products/peak-performance-duo',
    'direct',
    'https://freaksofnature.com/cdn/shop/files/SPF50-_-STICK-web-optimized-transparent_V2.png?v=1743565960&width=1920',
    4.8,
    241,
    'Stick: 0.70 oz / 20 gr || SPF: 50 ml / 1.7 fl oz',
    '**Peak Performance SPF50** **Step 1:**Complete the skincare routine. We recommend priming the skin with a pump of our Deeper Dive Moisturizer. **Step 2:**Apply Peak Performance SPF50 Sunscreen in the morning before you go outside, or 15 minutes before going in the sun, and as the final step in the daily skincare routine. Apply one pump amount or more of our Peak Performance SPF50 Sunscreen into hands and gently rub onto face, neck, chest and body if applicable. Reapply after 80 min of swimming or sweating, immediately after towel drying and at least every 2 hours when exposed to the sun. **Peak Performance SPF50 Sun Stick** Easy to bring with you on the go to be applied liberally onto face, neck, chest and body if applicable. Reapply after 80 min of swimming or sweating, immediately after towel drying and at least every 2 hours when exposed to the sun. Product can be re-applied over or under makeup.',
    'All Skin Types',
    'Nothing! Unlike the painfully nostalgic odor (i.e. harsh and chemically) of most sunscreens, ours is completely unscented.',
    'Peak Performance SPF50: Cream like consistency to be applied as last step in routine and rubbed into skin. Peak Performance Stick: Goes on silky smooth, clear, and easily with a bare skin feel that will not warp, slip or drip into the eyes.',
    array['Water resistant (40 min)', 'Protects + strengthens skin barrier', 'Broad spectrum UV protection', '100% mineral protection', 'Fragrance free', 'Reef safe', 'Dermatologist tested', 'Minimal white cast']::text[],
    true
  ),
  (
    'f0000000-0000-0000-0000-000000000015',
    'balanced-skin-set',
    (select id from public.brands where slug = 'freaks-of-nature'),
    'Balanced Skin Set',
    'skincare',
    (select id from public.categories where slug = 'skincare'),
    70,
    'Deeper Dive & Barrier Balancing Face Wash',
    '#2F6F5E',
    'https://freaksofnature.com/products/balanced-skin-set',
    'direct',
    'https://freaksofnature.com/cdn/shop/files/3D_HYDRATOR_CLEANSER-LIGHTBLUE_E-COMM.png?v=1748543058&width=1920',
    4.9,
    101,
    '100 ml / 3.4 fl oz (Face Wash), 50 ml / 1.7 fl oz (Hydrator)',
    '**Barrier Balancing Cleanser** **Step 1:**After a long day, sweat sesh, or time spent in the sun. Apply 1-2 pumps of barrier balancing face wash to dry or wet face. Rub into skin to release grime. **Step 2:**Add water to skin as face wash begins to froth into a milky texture, helping further cleanse and hydrate the skin. **Step 3:**Towel dry skin. For best results, apply Deeper Dive Hydrator post-cleanse. **Deep Dive Hydrator** **Step 1:**After AM/PM cleansing, or when you wash yourself after a workout session, apply one pump amount into hands and gently rub onto face, neck and chest if applicable. For optimal results use in the AM and PM. **Step 2:**If heading outside apply Daily Defender SPF30 Sunscreen as the final step in the daily routine.',
    'All skin types',
    'Fragrance free',
    'Firm, smooth, and clear',
    array['Fragrance free', 'Dermatologist tested', 'Protects + strengthens skin barrier']::text[],
    true
  ),
  (
    'f0000000-0000-0000-0000-000000000016',
    'daily-system',
    (select id from public.brands where slug = 'freaks-of-nature'),
    'Daily System',
    'sunscreen',
    (select id from public.categories where slug = 'sunscreen'),
    74.7,
    'SPF30 Sunscreen & Hydrator Strengthen. Protect. Repair. Repeat.',
    '#2F6F5E',
    'https://freaksofnature.com/products/daily-system',
    'direct',
    'https://freaksofnature.com/cdn/shop/files/SPF30-_-HYDRATOR-web-optimized-transparent_V2.png?v=1743566064&width=1920',
    4.9,
    191,
    '50 ml / 1.7 fl oz per product',
    '**Daily Defender SPF30** **Step 1:**Complete the skincare routine. We recommend priming the skin with a pump of our Deep Dive Hydrator. **Step 2:**Apply Daily Defender SPF30 Sunscreen in the morning before you go outside, or 15 minutes before going in the sun, and as the final step in the daily skincare routine. Apply one pump amount or more of our Daily Defender SPF30 Sunscreen into hands and gently rub onto face, neck, chest and body if applicable. Reapply after 40 min of swimming or sweating, immediately after towel drying and at least every 2 hours when exposed to the sun. **Deep Dive Hydrator** **Step 1:**After AM/PM cleansing, or when you wash yourself after a workout session, apply one pump amount into hands and gently rub onto face, neck and chest if applicable. For optimal results use in the AM and PM. **Step 2:**If heading outside apply Daily Defender SPF30 Sunscreen as the final step in the daily routine.',
    'All skin types',
    '',
    '',
    array['40 min water resistant', '100% mineral protection', 'No chemical filters', 'Minimal white cast', 'Broad spectrum UV protection', 'Dermatologist tested', 'Reef safe']::text[],
    true
  ),
  (
    'f0000000-0000-0000-0000-000000000017',
    'endurance-system',
    (select id from public.brands where slug = 'freaks-of-nature'),
    'Endurance System',
    'sunscreen',
    (select id from public.categories where slug = 'sunscreen'),
    77.4,
    'SPF50 Sunscreen & Hydrator Strengthen. Protect. Repair. Repeat.',
    '#2F6F5E',
    'https://freaksofnature.com/products/endurance-system',
    'direct',
    'https://freaksofnature.com/cdn/shop/files/SPF50-_-HYDRATOR-web-optimized-transparent_V2.png?v=1743566045&width=1920',
    4.9,
    150,
    '50 ml / 1.7 fl oz per product',
    '**Peak Performance SPF50** **Step 1:**Complete the skincare routine. We recommend priming the skin with a pump of our Deeper Dive Moisturizer. **Step 2:**Apply Peak Performance SPF50 Sunscreen in the morning before you go outside, or 15 minutes before going in the sun, and as the final step in the daily skincare routine. Apply one pump amount or more of our Peak Performance SPF50 Sunscreen into hands and gently rub onto face, neck, chest and body if applicable. Reapply after 80 min of swimming or sweating, immediately after towel drying and at least every 2 hours when exposed to the sun. **Deep Dive Hydrator** **Step 1:**After AM/PM cleansing, or when you wash yourself after a workout session, apply one pump amount into hands and gently rub onto face, neck and chest if applicable. For optimal results use in the AM and PM. **Step 2:**If heading outside apply Daily Defender SPF30 Sunscreen as the final step in the daily routine.',
    'all skin types',
    '',
    '',
    array['100% mineral protection', 'Water resistant (40 min)', 'No chemical filters', 'Broad spectrum UV protection', 'Minimal white cast', 'Dermatologist tested', 'Reef safe']::text[],
    true
  ),
  (
    'f0000000-0000-0000-0000-000000000018',
    'endurance-system-sport-mode',
    (select id from public.brands where slug = 'freaks-of-nature'),
    'Endurance System -- Sport Mode',
    'sunscreen',
    (select id from public.categories where slug = 'sunscreen'),
    64.2,
    'SPF50 Stick & Hydrator Strengthen. Protect. Repair. Repeat.',
    '#2F6F5E',
    'https://freaksofnature.com/products/endurance-system-sport-mode',
    'direct',
    'https://freaksofnature.com/cdn/shop/files/HYDRATOR-_-STICK-web-optimized-transparent_V2.png?v=1743565980&width=1920',
    4.9,
    205,
    'Stick: 0.70 oz / 20 gr || Moisturizer: 50 ml / 1.7 fl oz',
    '**Deeper Dive Moisturizer:** **Step 1:**After AM/PM cleansing, or when you wash yourself after a workout session, apply one pump amount into hands and gently rub onto face, neck and chest if applicable. For optimal results use in the AM and PM. **Step 2:**If heading outside apply Peak Performance SPF50 Sun Stick as the final step in the daily routine. Reapply after 80 min of swimming or sweating, immediately after towel drying and at least every 2 hours when exposed to the sun. Product can be re-applied over or under makeup.',
    'All Skin Types',
    'Deeper Dive Hydrator: Minerally with a slight nuttiness. Think of it like a crisp day near the lake! Peak Performance Sun Stick: Nothing! Unlike the painfully nostalgic odor (i.e. harsh and chemically) of most sunscreens, ours is completely unscented.',
    'Deeper Dive Hydrator: Natural oil color and texture for maximum hydration without the greasy look. Peak Performance Sun Stick: Goes on silky smooth, clear, and easily with a bare skin feel that will not warp, slip or drip into the eyes.',
    array['Water resistant (40 min)', '100% mineral protection', 'No chemical filters', 'Protects + strengthens skin barrier', 'Minimal white cast', 'Broad spectrum UV protection', 'Dermatologist tested', 'Reef safe']::text[],
    true
  ),
  (
    'f0000000-0000-0000-0000-000000000019',
    'deo-duo-bundle',
    (select id from public.brands where slug = 'freaks-of-nature'),
    'Everyday Endurance Duo',
    'deodorant',
    (select id from public.categories where slug = 'deodorant'),
    36,
    'Two all natural scents with 48-hour odor protection',
    '#2F6F5E',
    'https://freaksofnature.com/products/deo-duo-bundle',
    'direct',
    'https://freaksofnature.com/cdn/shop/files/Duo.png?v=1761526305&width=1920',
    4.2,
    55,
    '75ml / 2.6 fl oz (per stick)',
    '**Step 1:**Remove cap **Step 2:**Twist bottom of bottle until formula begins to appear from perforated cap (Do not overtwist! A little goes a long way) **Step 3:**Apply formula directly on underarm For best results, keep deodorant at room temperature (68°F to 77°F / 20°C to 25°C)',
    'All skin types',
    '**Santal Dune:** Warm amber and smooth santal finished with earthy spice. **Bergamot Canyon:** Bright citrus and neroli with a crisp oakmoss and bergamot finish',
    'A creamy texture that dries within 30 seconds. Not sticky or wet and lasts for 48 hours. In our perception study 93% of users found that the deo did not leave stains or marks on clothing.',
    array['Dermatologist tested', 'Protects + strengthens skin barrier', 'Fragrance free']::text[],
    true
  ),
  (
    'f0000000-0000-0000-0000-000000000020',
    'skin-support-electrolyte',
    (select id from public.brands where slug = 'freaks-of-nature'),
    'Skin Support Electrolyte',
    'skincare',
    (select id from public.categories where slug = 'skincare'),
    55,
    'Whole-body hydration and protection from the inside out',
    '#2F6F5E',
    'https://freaksofnature.com/products/skin-support-electrolyte',
    'direct',
    'https://freaksofnature.com/cdn/shop/files/Update_ProductCard.png?v=1773719331&width=1920',
    4.9,
    42,
    '1 sachet / 13.1 g',
    'Mix one sachet into 16--20 oz of cold water, shake or stir until dissolved, and drink daily. Best enjoyed whenever you want--before, during, or after training. The North Shore flavor makes it easy to stay consistent. Just mix and sip.',
    'All skin types.',
    'Tangy passionfruit, guava, and a hint of zesty lime.',
    '',
    array['Hydrates + soothes', 'Protects + strengthens skin barrier']::text[],
    true
  ),
  (
    'f0000000-0000-0000-0000-000000000021',
    'everyday-endurance-trio',
    (select id from public.brands where slug = 'freaks-of-nature'),
    'Everyday Endurance Trio',
    'deodorant',
    (select id from public.categories where slug = 'deodorant'),
    51,
    'Three all natural scents with 48-hour odor protection',
    '#2F6F5E',
    'https://freaksofnature.com/products/everyday-endurance-trio',
    'direct',
    'https://freaksofnature.com/cdn/shop/files/Trio.png?v=1775849441&width=1920',
    4.2,
    55,
    '75ml / 2.6 fl oz (per stick)',
    '**Step 1:**Remove cap **Step 2:**Twist bottom of bottle until formula begins to appear from perforated cap (Do not overtwist! A little goes a long way) **Step 3:**Apply formula directly on underarm For best results, keep deodorant at room temperature (68°F to 77°F / 20°C to 25°C)',
    'All skin types',
    '**Santal Dune:** Warm amber and smooth santal finished with earthy spice.**Bergamot Canyon:** Bright citrus and neroli with a crisp oakmoss and bergamot finish**Cedar Peak:** Cool and sharp. A crisp hit of eucalyptus and mint, layered with herbal lavandin and a sharp touch of geranium to wake up the senses.',
    'A creamy texture that dries within 30 seconds. Not sticky or wet and lasts for 48 hours. In our perception study 93% of users found that the deo did not leave stains or marks on clothing.',
    array['Dermatologist tested', 'Protects + strengthens skin barrier', 'Fragrance free']::text[],
    true
  )
on conflict (slug) do update set
  brand_id = excluded.brand_id,
  name = excluded.name,
  category = excluded.category,
  category_id = excluded.category_id,
  price = excluded.price,
  description = excluded.description,
  affiliate_url = excluded.affiliate_url,
  image_url = excluded.image_url,
  rating = excluded.rating,
  review_count = excluded.review_count,
  size = excluded.size,
  how_to_use = excluded.how_to_use,
  good_for = excluded.good_for,
  smells_like = excluded.smells_like,
  finish = excluded.finish,
  features = excluded.features,
  is_published = excluded.is_published;
