insert into public.ingredients (slug, name) values
  ('aloe-barbendensis-leaf-juice', 'Aloe Barbendensis Leaf Juice'),
  ('and-sodium-hyaluronate', 'and Sodium Hyaluronate'),
  ('aqua-water', 'Aqua / Water'),
  ('aspergillus-ferment', 'Aspergillus Ferment'),
  ('astaxanthin', 'Astaxanthin'),
  ('avena-sativa-oat-kernel-oil', 'Avena Sativa (Oat) Kernel Oil'),
  ('bacillus-ferment', 'Bacillus Ferment'),
  ('bambusa-arundinacea-bamboo-stem-extract', 'Bambusa Arundinacea (Bamboo) Stem Extract'),
  ('bentonite', 'Bentonite'),
  ('betaine', 'Betaine'),
  ('c13-15-alkane', 'C13-15 Alkane'),
  ('calcium', 'Calcium'),
  ('camellia-oleifera-seed-oil', 'Camellia Oleifera Seed Oil'),
  ('camellia-sinensis-japanese-green-tea-leaf-extract', 'Camellia Sinensis (Japanese Green Tea) Leaf Extract'),
  ('caprylhydroxamic-acid', 'Caprylhydroxamic Acid'),
  ('caprylic-capric-triglyceride', 'Caprylic / Capric Triglyceride'),
  ('capryliccapric-triglyceride', 'Caprylic/Capric Triglyceride'),
  ('capryloyl-glycerinsebacic-acid-copolymer', 'Capryloyl Glycerin/Sebacic Acid Copolymer'),
  ('cetearyl-olivate', 'Cetearyl Olivate'),
  ('cetyl-alcohol', 'Cetyl Alcohol'),
  ('chloride', 'Chloride'),
  ('chromium-hydroxide-green-ci-77289', 'Chromium Hydroxide Green (CI 77289)'),
  ('citric-acid', 'Citric Acid'),
  ('citronellyl-methylcrotonate', 'Citronellyl Methylcrotonate'),
  ('coco-caprylatecaprate', 'Coco-Caprylate/Caprate'),
  ('copernicia-cerifera-carnauba-wax', 'Copernicia Cerifera (Carnauba) Wax'),
  ('dextrin-palmitate', 'Dextrin Palmitate'),
  ('dilauryl-citrate', 'Dilauryl Citrate'),
  ('dl-alpha-tocopherol', 'DL-Alpha Tocopherol'),
  ('ethylhexyl-olivate', 'Ethylhexyl Olivate'),
  ('ethylhexyl-palmitate', 'Ethylhexyl Palmitate'),
  ('ethylhexylglycerin', 'Ethylhexylglycerin'),
  ('fragrance', 'Fragrance'),
  ('fragrance-parfum', 'Fragrance (Parfum)'),
  ('ginger-zingiber-officinale-root-extract', 'Ginger (Zingiber officinale) Root Extract'),
  ('gluconolactone', 'Gluconolactone'),
  ('glycerin', 'Glycerin'),
  ('glyceryl-laurate', 'Glyceryl Laurate'),
  ('helianthus-annuus-sunflower-seed-oil', 'Helianthus Annuus (Sunflower) Seed Oil'),
  ('helianthus-annuus-sunflower-seed-wax', 'Helianthus Annuus (Sunflower) Seed Wax'),
  ('hydrogenated-methyl-abietate', 'Hydrogenated Methyl Abietate'),
  ('isoamyl-laurate', 'Isoamyl Laurate'),
  ('isopropyl-palmitate', 'Isopropyl Palmitate'),
  ('isostearic-acid', 'Isostearic Acid'),
  ('laurel-lysine', 'Laurel Lysine'),
  ('lauryl-glucoside', 'Lauryl Glucoside'),
  ('lecithin', 'Lecithin'),
  ('leuconostoc-radish-root-ferment-filtrate', 'Leuconostoc / Radish Root Ferment Filtrate'),
  ('lonicera-caprifolium-honeysuckle-flower-extract', 'Lonicera Caprifolium (Honeysuckle) Flower Extract'),
  ('lonicera-japonica-honeysuckle-flower-extract', 'Lonicera Japonica (Honeysuckle) Flower Extract'),
  ('magnesium', 'Magnesium'),
  ('maleated-soybean-oil-glyceryloctyldodecanol-esters', 'Maleated Soybean Oil Glyceryl/Octyldodecanol Esters'),
  ('malic-acid', 'Malic Acid'),
  ('maranta-arundinacea-arrowroot-root-extract', 'Maranta Arundinacea (Arrowroot) Root Extract'),
  ('methylcellulose', 'Methylcellulose'),
  ('methylheptylglycerin', 'Methylheptylglycerin'),
  ('myrica-pubescens-laurel-fruit-wax', 'Myrica Pubescens (Laurel) Fruit Wax'),
  ('natural-flavors', 'Natural Flavors'),
  ('octinoxate', 'Octinoxate'),
  ('octyldodecyl-citrate-crosspolymer', 'Octyldodecyl Citrate Crosspolymer'),
  ('oryza-sativa-rice-bran-oil', 'Oryza Sativa (Rice Bran) Oil'),
  ('oryza-sativa-rice-bran-oil-2', 'Oryza Sativa (Rice) Bran Oil'),
  ('oryza-sativa-rice-bran-wax', 'Oryza Sativa (Rice) Bran Wax'),
  ('oxybenzone', 'Oxybenzone'),
  ('padina-pavonica-thallus-extract', 'Padina Pavonica Thallus Extract'),
  ('partially-hydrolyzed-guar-gum', 'Partially Hydrolyzed Guar Gum'),
  ('phenoxyethanol', 'Phenoxyethanol'),
  ('physalis-angulata-ground-cherry-extract', 'Physalis Angulata (Ground Cherry) Extract'),
  ('plukenetia-volubilis-sacha-inchi-seed-oil', 'Plukenetia Volubilis (Sacha Inchi) Seed Oil'),
  ('polyglyceryl-3-polyricinoleate', 'Polyglyceryl-3 Polyricinoleate'),
  ('polyglyceryl-4-diisostearatepolyhydroxystearatesebacate', 'Polyglyceryl-4 Diisostearate/Polyhydroxystearate/Sebacate'),
  ('polyglyceryl-4-laurate', 'Polyglyceryl-4 Laurate'),
  ('polyhydroxystearic-acid', 'Polyhydroxystearic Acid'),
  ('polypodium-leucotomos-leaf-extract', 'Polypodium leucotomos Leaf Extract'),
  ('polyricinoleic-acid', 'Polyricinoleic acid'),
  ('pongamia-pinnata-seed-extract', 'Pongamia Pinnata Seed Extract'),
  ('populus-tremuloides-bark-extract', 'Populus Tremuloides Bark Extract'),
  ('porphyra-umbilicalis-extract-aqua', 'Porphyra Umbilicalis Extract Aqua'),
  ('potassium', 'Potassium'),
  ('propanediol', 'Propanediol'),
  ('prototheca-moriformis-microalgae-oil', 'Prototheca Moriformis (Microalgae) Oil'),
  ('quaternium-90-bentonite', 'Quaternium-90 Bentonite'),
  ('rebaudioside-a-stevia-leaf-extract', 'Rebaudioside A (Stevia Leaf Extract)'),
  ('red-orange-citrus-sinensis-fruit-extract', 'Red Orange (Citrus sinensis) Fruit Extract'),
  ('rhododendron-ferrugineum-alpenrose-extract', 'Rhododendron Ferrugineum (Alpenrose) Extract'),
  ('saccharomyces-ferment', 'Saccharomyces Ferment'),
  ('silica', 'Silica'),
  ('simmondsia-chinensis-jojoba-seed-oil', 'Simmondsia Chinensis (Jojoba) Seed Oil'),
  ('sodium', 'Sodium'),
  ('sodium-citrate', 'Sodium Citrate'),
  ('sodium-cocoyl-apple-amino-acids', 'Sodium Cocoyl Apple Amino Acids'),
  ('sodium-lauryl-glucose-carboxylate', 'Sodium Lauryl Glucose Carboxylate'),
  ('sodium-phytate', 'Sodium Phytate'),
  ('sodium-stearoyl-glutamate', 'Sodium Stearoyl Glutamate'),
  ('sorbitan-laurate', 'Sorbitan Laurate'),
  ('sorbitan-olivate', 'Sorbitan Olivate'),
  ('spirulina-platensis-extract', 'Spirulina Platensis Extract'),
  ('squalane', 'Squalane'),
  ('sr-wasp-spider-polypeptide-1-oligopeptide-178', 'Sr-wasp spider polypeptide-1 oligopeptide-178'),
  ('stearic-acid', 'Stearic Acid'),
  ('stearyloctyldodecyl-citrate-crosspolymer', 'Stearyl/Octyldodecyl Citrate Crosspolymer'),
  ('sucrose-stearate', 'Sucrose Stearate'),
  ('theobroma-cacao-cocoa-seed-butter', 'Theobroma Cacao (Cocoa) Seed Butter'),
  ('titanium-dioxide', 'Titanium Dioxide'),
  ('tocopherol', 'Tocopherol'),
  ('tocopherol-acetate', 'Tocopherol Acetate'),
  ('tocopheryl-acetate', 'Tocopheryl Acetate'),
  ('trehalose', 'Trehalose'),
  ('triethyl-citrate', 'Triethyl Citrate'),
  ('undaria-pinnatifida-wakame-extract', 'Undaria Pinnatifida (Wakame) Extract'),
  ('vitamin-a', 'Vitamin A'),
  ('vitamin-b3', 'Vitamin B3'),
  ('vitamin-c', 'Vitamin C'),
  ('vitamin-d', 'Vitamin D'),
  ('vitamin-e', 'Vitamin E'),
  ('vitis-vinifera-grape-seed-oil', 'Vitis Vinifera (Grape) Seed Oil'),
  ('water', 'Water'),
  ('xanthan-gum', 'Xanthan Gum'),
  ('zinc', 'Zinc'),
  ('zinc-oxide', 'Zinc Oxide'),
  ('zinc-ricinoleate', 'Zinc Ricinoleate')
on conflict (name) do update set slug = excluded.slug;

with links(product_slug, ingredient_name, kind) as (
  values
  ('solar-shield-spray', 'Zinc Oxide', 'contains'),
  ('solar-shield-spray', 'Aloe Barbendensis Leaf Juice', 'contains'),
  ('solar-shield-spray', 'Aqua / Water', 'contains'),
  ('solar-shield-spray', 'Bambusa Arundinacea (Bamboo) Stem Extract', 'contains'),
  ('solar-shield-spray', 'Camellia Sinensis (Japanese Green Tea) Leaf Extract', 'contains'),
  ('solar-shield-spray', 'Caprylic / Capric Triglyceride', 'contains'),
  ('solar-shield-spray', 'Dilauryl Citrate', 'contains'),
  ('solar-shield-spray', 'Ethylhexylglycerin', 'contains'),
  ('solar-shield-spray', 'Gluconolactone', 'contains'),
  ('solar-shield-spray', 'Glycerin', 'contains'),
  ('solar-shield-spray', 'Hydrogenated Methyl Abietate', 'contains'),
  ('solar-shield-spray', 'Isopropyl Palmitate', 'contains'),
  ('solar-shield-spray', 'Lauryl Glucoside', 'contains'),
  ('solar-shield-spray', 'Leuconostoc / Radish Root Ferment Filtrate', 'contains'),
  ('solar-shield-spray', 'Lonicera Caprifolium (Honeysuckle) Flower Extract', 'contains'),
  ('solar-shield-spray', 'Lonicera Japonica (Honeysuckle) Flower Extract', 'contains'),
  ('solar-shield-spray', 'Methylcellulose', 'contains'),
  ('solar-shield-spray', 'Octyldodecyl Citrate Crosspolymer', 'contains'),
  ('solar-shield-spray', 'Phenoxyethanol', 'contains'),
  ('solar-shield-spray', 'Polyglyceryl-4 Laurate', 'contains'),
  ('solar-shield-spray', 'Populus Tremuloides Bark Extract', 'contains'),
  ('solar-shield-spray', 'Simmondsia Chinensis (Jojoba) Seed Oil', 'contains'),
  ('solar-shield-spray', 'Sodium Lauryl Glucose Carboxylate', 'contains'),
  ('solar-shield-spray', 'Sodium Phytate', 'contains'),
  ('solar-shield-spray', 'Sodium Stearoyl Glutamate', 'contains'),
  ('solar-shield-spray', 'Sorbitan Laurate', 'contains'),
  ('solar-shield-spray', 'Tocopherol', 'contains'),
  ('solar-shield-spray', 'Xanthan Gum', 'contains'),
  ('solar-shield-spray', 'Fragrance', 'free_from'),
  ('solar-shield-spray', 'Oxybenzone', 'free_from'),
  ('solar-shield-spray', 'Octinoxate', 'free_from'),
  ('sun-stick-spf50', 'Zinc Oxide', 'contains'),
  ('sun-stick-spf50', 'Helianthus Annuus (Sunflower) Seed Wax', 'contains'),
  ('sun-stick-spf50', 'Isoamyl Laurate', 'contains'),
  ('sun-stick-spf50', 'Ethylhexyl Olivate', 'contains'),
  ('sun-stick-spf50', 'Caprylic/Capric Triglyceride', 'contains'),
  ('sun-stick-spf50', 'C13-15 Alkane', 'contains'),
  ('sun-stick-spf50', 'Polyhydroxystearic Acid', 'contains'),
  ('sun-stick-spf50', 'Oryza Sativa (Rice Bran) Oil', 'contains'),
  ('sun-stick-spf50', 'Quaternium-90 Bentonite', 'contains'),
  ('sun-stick-spf50', 'Capryloyl Glycerin/Sebacic Acid Copolymer', 'contains'),
  ('sun-stick-spf50', 'Prototheca Moriformis (Microalgae) Oil', 'contains'),
  ('sun-stick-spf50', 'Theobroma Cacao (Cocoa) Seed Butter', 'contains'),
  ('sun-stick-spf50', 'Isostearic Acid', 'contains'),
  ('sun-stick-spf50', 'Lecithin', 'contains'),
  ('sun-stick-spf50', 'Polyglyceryl-3 Polyricinoleate', 'contains'),
  ('sun-stick-spf50', 'Triethyl Citrate', 'contains'),
  ('sun-stick-spf50', 'Squalane', 'contains'),
  ('sun-stick-spf50', 'Physalis Angulata (Ground Cherry) Extract', 'contains'),
  ('sun-stick-spf50', 'Rhododendron Ferrugineum (Alpenrose) Extract', 'contains'),
  ('sun-stick-spf50', 'Undaria Pinnatifida (Wakame) Extract', 'contains'),
  ('sun-stick-spf50', 'Saccharomyces Ferment', 'contains'),
  ('sun-stick-spf50', 'Laurel Lysine', 'contains'),
  ('sun-stick-spf50', 'Tocopherol Acetate', 'contains'),
  ('sun-stick-spf50', 'Tocopherol', 'contains'),
  ('sun-stick-spf50', 'Fragrance', 'free_from'),
  ('sun-stick-spf50', 'Oxybenzone', 'free_from'),
  ('sun-stick-spf50', 'Octinoxate', 'free_from'),
  ('everyday-endurance-deodorant', 'Caprylic/Capric Triglyceride', 'contains'),
  ('everyday-endurance-deodorant', 'Maranta Arundinacea (Arrowroot) Root Extract', 'contains'),
  ('everyday-endurance-deodorant', 'Helianthus Annuus (Sunflower) Seed Oil', 'contains'),
  ('everyday-endurance-deodorant', 'Ethylhexyl Palmitate', 'contains'),
  ('everyday-endurance-deodorant', 'Myrica Pubescens (Laurel) Fruit Wax', 'contains'),
  ('everyday-endurance-deodorant', 'Theobroma Cacao (Cocoa) Seed Butter', 'contains'),
  ('everyday-endurance-deodorant', 'Triethyl Citrate', 'contains'),
  ('everyday-endurance-deodorant', 'Bambusa Arundinacea (Bamboo) Stem Extract', 'contains'),
  ('everyday-endurance-deodorant', 'Zinc Ricinoleate', 'contains'),
  ('everyday-endurance-deodorant', 'Bentonite', 'contains'),
  ('everyday-endurance-deodorant', 'Glyceryl Laurate', 'contains'),
  ('everyday-endurance-deodorant', 'Helianthus Annuus (Sunflower) Seed Wax', 'contains'),
  ('everyday-endurance-deodorant', 'Silica', 'contains'),
  ('everyday-endurance-deodorant', 'Oryza Sativa (Rice) Bran Wax', 'contains'),
  ('everyday-endurance-deodorant', 'Citronellyl Methylcrotonate', 'contains'),
  ('everyday-endurance-deodorant', 'Tocopheryl Acetate', 'contains'),
  ('everyday-endurance-deodorant', 'Fragrance (Parfum)', 'contains'),
  ('everyday-endurance-deodorant', 'Chromium Hydroxide Green (CI 77289)', 'contains'),
  ('jumbo-sun-stick', 'Zinc Oxide', 'contains'),
  ('jumbo-sun-stick', 'Helianthus Annuus (Sunflower) Seed Wax', 'contains'),
  ('jumbo-sun-stick', 'Isoamyl Laurate', 'contains'),
  ('jumbo-sun-stick', 'Ethylhexyl Olivate', 'contains'),
  ('jumbo-sun-stick', 'Caprylic/Capric Triglyceride', 'contains'),
  ('jumbo-sun-stick', 'C13-15 Alkane', 'contains'),
  ('jumbo-sun-stick', 'Polyhydroxystearic Acid', 'contains'),
  ('jumbo-sun-stick', 'Oryza Sativa (Rice Bran) Oil', 'contains'),
  ('jumbo-sun-stick', 'Quaternium-90 Bentonite', 'contains'),
  ('jumbo-sun-stick', 'Capryloyl Glycerin/Sebacic Acid Copolymer', 'contains'),
  ('jumbo-sun-stick', 'Prototheca Moriformis (Microalgae) Oil', 'contains'),
  ('jumbo-sun-stick', 'Theobroma Cacao (Cocoa) Seed Butter', 'contains'),
  ('jumbo-sun-stick', 'Isostearic Acid', 'contains'),
  ('jumbo-sun-stick', 'Lecithin', 'contains'),
  ('jumbo-sun-stick', 'Polyglyceryl-3 Polyricinoleate', 'contains'),
  ('jumbo-sun-stick', 'Triethyl Citrate', 'contains'),
  ('jumbo-sun-stick', 'Squalane', 'contains'),
  ('jumbo-sun-stick', 'Physalis Angulata (Ground Cherry) Extract', 'contains'),
  ('jumbo-sun-stick', 'Rhododendron Ferrugineum (Alpenrose) Extract', 'contains'),
  ('jumbo-sun-stick', 'Undaria Pinnatifida (Wakame) Extract', 'contains'),
  ('jumbo-sun-stick', 'Saccharomyces Ferment', 'contains'),
  ('jumbo-sun-stick', 'Laurel Lysine', 'contains'),
  ('jumbo-sun-stick', 'Tocopherol Acetate', 'contains'),
  ('jumbo-sun-stick', 'Tocopherol', 'contains'),
  ('jumbo-sun-stick', 'Fragrance', 'free_from'),
  ('jumbo-sun-stick', 'Oxybenzone', 'free_from'),
  ('jumbo-sun-stick', 'Octinoxate', 'free_from'),
  ('peak-performance-sunscreen', 'Zinc Oxide', 'contains'),
  ('peak-performance-sunscreen', 'Titanium Dioxide', 'contains'),
  ('peak-performance-sunscreen', 'Water', 'contains'),
  ('peak-performance-sunscreen', 'Coco-Caprylate/Caprate', 'contains'),
  ('peak-performance-sunscreen', 'Caprylic/Capric Triglyceride', 'contains'),
  ('peak-performance-sunscreen', 'Maleated Soybean Oil Glyceryl/Octyldodecanol Esters', 'contains'),
  ('peak-performance-sunscreen', 'Polyglyceryl-4 Diisostearate/Polyhydroxystearate/Sebacate', 'contains'),
  ('peak-performance-sunscreen', 'Propanediol', 'contains'),
  ('peak-performance-sunscreen', 'Stearyl/Octyldodecyl Citrate Crosspolymer', 'contains'),
  ('peak-performance-sunscreen', 'Copernicia Cerifera (Carnauba) Wax', 'contains'),
  ('peak-performance-sunscreen', 'Bentonite', 'contains'),
  ('peak-performance-sunscreen', 'Methylheptylglycerin', 'contains'),
  ('peak-performance-sunscreen', 'Squalane', 'contains'),
  ('peak-performance-sunscreen', 'Sr-wasp spider polypeptide-1 oligopeptide-178', 'contains'),
  ('peak-performance-sunscreen', 'Porphyra Umbilicalis Extract Aqua', 'contains'),
  ('peak-performance-sunscreen', 'Cetearyl Olivate', 'contains'),
  ('peak-performance-sunscreen', 'Sorbitan Olivate', 'contains'),
  ('peak-performance-sunscreen', 'Polyhydroxystearic Acid', 'contains'),
  ('peak-performance-sunscreen', 'Polyricinoleic acid', 'contains'),
  ('peak-performance-sunscreen', 'Glycerin', 'contains'),
  ('peak-performance-sunscreen', 'Xanthan Gum', 'contains'),
  ('peak-performance-sunscreen', 'Cetyl Alcohol', 'contains'),
  ('peak-performance-sunscreen', 'Pongamia Pinnata Seed Extract', 'contains'),
  ('peak-performance-sunscreen', 'Caprylhydroxamic Acid', 'contains'),
  ('peak-performance-sunscreen', 'Oryza Sativa (Rice) Bran Wax', 'contains'),
  ('peak-performance-sunscreen', 'DL-Alpha Tocopherol', 'contains'),
  ('peak-performance-sunscreen', 'Stearic Acid', 'contains'),
  ('peak-performance-sunscreen', 'Sodium Phytate', 'contains'),
  ('peak-performance-sunscreen', 'Fragrance', 'free_from'),
  ('peak-performance-sunscreen', 'Oxybenzone', 'free_from'),
  ('peak-performance-sunscreen', 'Octinoxate', 'free_from'),
  ('deeper-dive-moisturizer', 'Squalane', 'contains'),
  ('deeper-dive-moisturizer', 'Avena Sativa (Oat) Kernel Oil', 'contains'),
  ('deeper-dive-moisturizer', 'Dextrin Palmitate', 'contains'),
  ('deeper-dive-moisturizer', 'Plukenetia Volubilis (Sacha Inchi) Seed Oil', 'contains'),
  ('deeper-dive-moisturizer', 'Simmondsia Chinensis (Jojoba) Seed Oil', 'contains'),
  ('deeper-dive-moisturizer', 'Padina Pavonica Thallus Extract', 'contains'),
  ('deeper-dive-moisturizer', 'Bacillus Ferment', 'contains'),
  ('deeper-dive-moisturizer', 'Tocopherol', 'contains'),
  ('daily-defender-sunscreen', 'Zinc Oxide', 'contains'),
  ('daily-defender-sunscreen', 'Water', 'contains'),
  ('daily-defender-sunscreen', 'Coco-Caprylate/Caprate', 'contains'),
  ('daily-defender-sunscreen', 'Caprylic/Capric Triglyceride', 'contains'),
  ('daily-defender-sunscreen', 'Polyglyceryl-4 Diisostearate/Polyhydroxystearate/Sebacate', 'contains'),
  ('daily-defender-sunscreen', 'Propanediol', 'contains'),
  ('daily-defender-sunscreen', 'C13-15 Alkane', 'contains'),
  ('daily-defender-sunscreen', 'Squalane', 'contains'),
  ('daily-defender-sunscreen', 'Maleated Soybean Oil Glyceryl/Octyldodecanol Esters', 'contains'),
  ('daily-defender-sunscreen', 'Copernicia Cerifera (Carnauba) Wax', 'contains'),
  ('daily-defender-sunscreen', 'Methylheptylglycerin', 'contains'),
  ('daily-defender-sunscreen', 'Sr-wasp spider polypeptide-1 oligopeptide-178', 'contains'),
  ('daily-defender-sunscreen', 'Bentonite', 'contains'),
  ('daily-defender-sunscreen', 'Polyricinoleic acid', 'contains'),
  ('daily-defender-sunscreen', 'Polyhydroxystearic Acid', 'contains'),
  ('daily-defender-sunscreen', 'Glycerin', 'contains'),
  ('daily-defender-sunscreen', 'Pongamia Pinnata Seed Extract', 'contains'),
  ('daily-defender-sunscreen', 'Xanthan Gum', 'contains'),
  ('daily-defender-sunscreen', 'Caprylhydroxamic Acid', 'contains'),
  ('daily-defender-sunscreen', 'Oryza Sativa (Rice) Bran Wax', 'contains'),
  ('daily-defender-sunscreen', 'DL-Alpha Tocopherol', 'contains'),
  ('daily-defender-sunscreen', 'Sodium Phytate', 'contains'),
  ('daily-defender-sunscreen', 'Fragrance', 'free_from'),
  ('daily-defender-sunscreen', 'Oxybenzone', 'free_from'),
  ('daily-defender-sunscreen', 'Octinoxate', 'free_from'),
  ('barrier-balancing-cleanser', 'Glycerin', 'contains'),
  ('barrier-balancing-cleanser', 'Sodium Cocoyl Apple Amino Acids', 'contains'),
  ('barrier-balancing-cleanser', 'Sucrose Stearate', 'contains'),
  ('barrier-balancing-cleanser', 'Betaine', 'contains'),
  ('barrier-balancing-cleanser', 'Saccharomyces Ferment', 'contains'),
  ('barrier-balancing-cleanser', 'Aspergillus Ferment', 'contains'),
  ('barrier-balancing-cleanser', 'Vitis Vinifera (Grape) Seed Oil', 'contains'),
  ('barrier-balancing-cleanser', 'Oryza Sativa (Rice) Bran Oil', 'contains'),
  ('barrier-balancing-cleanser', 'Squalane', 'contains'),
  ('barrier-balancing-cleanser', 'Tocopherol', 'contains'),
  ('barrier-balancing-cleanser', 'Avena Sativa (Oat) Kernel Oil', 'contains'),
  ('barrier-balancing-cleanser', 'Camellia Oleifera Seed Oil', 'contains'),
  ('barrier-balancing-cleanser', 'Spirulina Platensis Extract', 'contains'),
  ('barrier-balancing-cleanser', 'Trehalose', 'contains'),
  ('barrier-balancing-cleanser', 'Sodium Citrate', 'contains'),
  ('barrier-balancing-cleanser', 'Fragrance', 'free_from'),
  ('freaks-full-coverage-bundle', 'Zinc Oxide', 'contains'),
  ('freaks-full-coverage-bundle', 'Helianthus Annuus (Sunflower) Seed Wax', 'contains'),
  ('freaks-full-coverage-bundle', 'Isoamyl Laurate', 'contains'),
  ('freaks-full-coverage-bundle', 'Ethylhexyl Olivate', 'contains'),
  ('freaks-full-coverage-bundle', 'Caprylic/Capric Triglyceride', 'contains'),
  ('freaks-full-coverage-bundle', 'C13-15 Alkane', 'contains'),
  ('freaks-full-coverage-bundle', 'Polyhydroxystearic Acid', 'contains'),
  ('freaks-full-coverage-bundle', 'Oryza Sativa (Rice Bran) Oil', 'contains'),
  ('freaks-full-coverage-bundle', 'Quaternium-90 Bentonite', 'contains'),
  ('freaks-full-coverage-bundle', 'Capryloyl Glycerin/Sebacic Acid Copolymer', 'contains'),
  ('freaks-full-coverage-bundle', 'Prototheca Moriformis (Microalgae) Oil', 'contains'),
  ('freaks-full-coverage-bundle', 'Theobroma Cacao (Cocoa) Seed Butter', 'contains'),
  ('freaks-full-coverage-bundle', 'Isostearic Acid', 'contains'),
  ('freaks-full-coverage-bundle', 'Lecithin', 'contains'),
  ('freaks-full-coverage-bundle', 'Polyglyceryl-3 Polyricinoleate', 'contains'),
  ('freaks-full-coverage-bundle', 'Triethyl Citrate', 'contains'),
  ('freaks-full-coverage-bundle', 'Squalane', 'contains'),
  ('freaks-full-coverage-bundle', 'Physalis Angulata (Ground Cherry) Extract', 'contains'),
  ('freaks-full-coverage-bundle', 'Rhododendron Ferrugineum (Alpenrose) Extract', 'contains'),
  ('freaks-full-coverage-bundle', 'Undaria Pinnatifida (Wakame) Extract', 'contains'),
  ('freaks-full-coverage-bundle', 'Saccharomyces Ferment', 'contains'),
  ('freaks-full-coverage-bundle', 'Laurel Lysine', 'contains'),
  ('freaks-full-coverage-bundle', 'Tocopherol Acetate', 'contains'),
  ('freaks-full-coverage-bundle', 'Tocopherol', 'contains'),
  ('freaks-full-coverage-bundle', 'Aloe Barbendensis Leaf Juice', 'contains'),
  ('freaks-full-coverage-bundle', 'Aqua / Water', 'contains'),
  ('freaks-full-coverage-bundle', 'Bambusa Arundinacea (Bamboo) Stem Extract', 'contains'),
  ('freaks-full-coverage-bundle', 'Camellia Sinensis (Japanese Green Tea) Leaf Extract', 'contains'),
  ('freaks-full-coverage-bundle', 'Caprylic / Capric Triglyceride', 'contains'),
  ('freaks-full-coverage-bundle', 'Dilauryl Citrate', 'contains'),
  ('freaks-full-coverage-bundle', 'Ethylhexylglycerin', 'contains'),
  ('freaks-full-coverage-bundle', 'Gluconolactone', 'contains'),
  ('freaks-full-coverage-bundle', 'Glycerin', 'contains'),
  ('freaks-full-coverage-bundle', 'Hydrogenated Methyl Abietate', 'contains'),
  ('freaks-full-coverage-bundle', 'Isopropyl Palmitate', 'contains'),
  ('freaks-full-coverage-bundle', 'Lauryl Glucoside', 'contains'),
  ('freaks-full-coverage-bundle', 'Leuconostoc / Radish Root Ferment Filtrate', 'contains'),
  ('freaks-full-coverage-bundle', 'Lonicera Caprifolium (Honeysuckle) Flower Extract', 'contains'),
  ('freaks-full-coverage-bundle', 'Lonicera Japonica (Honeysuckle) Flower Extract', 'contains'),
  ('freaks-full-coverage-bundle', 'Methylcellulose', 'contains'),
  ('freaks-full-coverage-bundle', 'Octyldodecyl Citrate Crosspolymer', 'contains'),
  ('freaks-full-coverage-bundle', 'Phenoxyethanol', 'contains'),
  ('freaks-full-coverage-bundle', 'Polyglyceryl-4 Laurate', 'contains'),
  ('freaks-full-coverage-bundle', 'Populus Tremuloides Bark Extract', 'contains'),
  ('freaks-full-coverage-bundle', 'Simmondsia Chinensis (Jojoba) Seed Oil', 'contains'),
  ('freaks-full-coverage-bundle', 'Sodium Lauryl Glucose Carboxylate', 'contains'),
  ('freaks-full-coverage-bundle', 'Sodium Phytate', 'contains'),
  ('freaks-full-coverage-bundle', 'Sodium Stearoyl Glutamate', 'contains'),
  ('freaks-full-coverage-bundle', 'Sorbitan Laurate', 'contains'),
  ('freaks-full-coverage-bundle', 'Xanthan Gum', 'contains'),
  ('freaks-full-coverage-bundle', 'Fragrance', 'free_from'),
  ('freaks-full-coverage-bundle', 'Oxybenzone', 'free_from'),
  ('freaks-full-coverage-bundle', 'Octinoxate', 'free_from'),
  ('sun-stick-set', 'Zinc Oxide', 'contains'),
  ('sun-stick-set', 'Helianthus Annuus (Sunflower) Seed Wax', 'contains'),
  ('sun-stick-set', 'Isoamyl Laurate', 'contains'),
  ('sun-stick-set', 'Ethylhexyl Olivate', 'contains'),
  ('sun-stick-set', 'Caprylic/Capric Triglyceride', 'contains'),
  ('sun-stick-set', 'C13-15 Alkane', 'contains'),
  ('sun-stick-set', 'Polyhydroxystearic Acid', 'contains'),
  ('sun-stick-set', 'Oryza Sativa (Rice Bran) Oil', 'contains'),
  ('sun-stick-set', 'Quaternium-90 Bentonite', 'contains'),
  ('sun-stick-set', 'Capryloyl Glycerin/Sebacic Acid Copolymer', 'contains'),
  ('sun-stick-set', 'Prototheca Moriformis (Microalgae) Oil', 'contains'),
  ('sun-stick-set', 'Theobroma Cacao (Cocoa) Seed Butter', 'contains'),
  ('sun-stick-set', 'Isostearic Acid', 'contains'),
  ('sun-stick-set', 'Lecithin', 'contains'),
  ('sun-stick-set', 'Polyglyceryl-3 Polyricinoleate', 'contains'),
  ('sun-stick-set', 'Triethyl Citrate', 'contains'),
  ('sun-stick-set', 'Squalane', 'contains'),
  ('sun-stick-set', 'Physalis Angulata (Ground Cherry) Extract', 'contains'),
  ('sun-stick-set', 'Rhododendron Ferrugineum (Alpenrose) Extract', 'contains'),
  ('sun-stick-set', 'Undaria Pinnatifida (Wakame) Extract', 'contains'),
  ('sun-stick-set', 'Saccharomyces Ferment', 'contains'),
  ('sun-stick-set', 'Laurel Lysine', 'contains'),
  ('sun-stick-set', 'Tocopherol Acetate', 'contains'),
  ('sun-stick-set', 'Tocopherol', 'contains'),
  ('sun-stick-set', 'Fragrance', 'free_from'),
  ('sun-stick-set', 'Oxybenzone', 'free_from'),
  ('sun-stick-set', 'Octinoxate', 'free_from'),
  ('body-by-freaks-bundle', 'Zinc Oxide', 'contains'),
  ('body-by-freaks-bundle', 'Helianthus Annuus (Sunflower) Seed Wax', 'contains'),
  ('body-by-freaks-bundle', 'Isoamyl Laurate', 'contains'),
  ('body-by-freaks-bundle', 'Ethylhexyl Olivate', 'contains'),
  ('body-by-freaks-bundle', 'Caprylic/Capric Triglyceride', 'contains'),
  ('body-by-freaks-bundle', 'C13-15 Alkane', 'contains'),
  ('body-by-freaks-bundle', 'Polyhydroxystearic Acid', 'contains'),
  ('body-by-freaks-bundle', 'Oryza Sativa (Rice Bran) Oil', 'contains'),
  ('body-by-freaks-bundle', 'Quaternium-90 Bentonite', 'contains'),
  ('body-by-freaks-bundle', 'Capryloyl Glycerin/Sebacic Acid Copolymer', 'contains'),
  ('body-by-freaks-bundle', 'Prototheca Moriformis (Microalgae) Oil', 'contains'),
  ('body-by-freaks-bundle', 'Theobroma Cacao (Cocoa) Seed Butter', 'contains'),
  ('body-by-freaks-bundle', 'Isostearic Acid', 'contains'),
  ('body-by-freaks-bundle', 'Lecithin', 'contains'),
  ('body-by-freaks-bundle', 'Polyglyceryl-3 Polyricinoleate', 'contains'),
  ('body-by-freaks-bundle', 'Triethyl Citrate', 'contains'),
  ('body-by-freaks-bundle', 'Squalane', 'contains'),
  ('body-by-freaks-bundle', 'Physalis Angulata (Ground Cherry) Extract', 'contains'),
  ('body-by-freaks-bundle', 'Rhododendron Ferrugineum (Alpenrose) Extract', 'contains'),
  ('body-by-freaks-bundle', 'Undaria Pinnatifida (Wakame) Extract', 'contains'),
  ('body-by-freaks-bundle', 'Saccharomyces Ferment', 'contains'),
  ('body-by-freaks-bundle', 'Laurel Lysine', 'contains'),
  ('body-by-freaks-bundle', 'Tocopherol Acetate', 'contains'),
  ('body-by-freaks-bundle', 'Tocopherol', 'contains'),
  ('body-by-freaks-bundle', 'Aloe Barbendensis Leaf Juice', 'contains'),
  ('body-by-freaks-bundle', 'Aqua / Water', 'contains'),
  ('body-by-freaks-bundle', 'Bambusa Arundinacea (Bamboo) Stem Extract', 'contains'),
  ('body-by-freaks-bundle', 'Camellia Sinensis (Japanese Green Tea) Leaf Extract', 'contains'),
  ('body-by-freaks-bundle', 'Caprylic / Capric Triglyceride', 'contains'),
  ('body-by-freaks-bundle', 'Dilauryl Citrate', 'contains'),
  ('body-by-freaks-bundle', 'Ethylhexylglycerin', 'contains'),
  ('body-by-freaks-bundle', 'Gluconolactone', 'contains'),
  ('body-by-freaks-bundle', 'Glycerin', 'contains'),
  ('body-by-freaks-bundle', 'Hydrogenated Methyl Abietate', 'contains'),
  ('body-by-freaks-bundle', 'Isopropyl Palmitate', 'contains'),
  ('body-by-freaks-bundle', 'Lauryl Glucoside', 'contains'),
  ('body-by-freaks-bundle', 'Leuconostoc / Radish Root Ferment Filtrate', 'contains'),
  ('body-by-freaks-bundle', 'Lonicera Caprifolium (Honeysuckle) Flower Extract', 'contains'),
  ('body-by-freaks-bundle', 'Lonicera Japonica (Honeysuckle) Flower Extract', 'contains'),
  ('body-by-freaks-bundle', 'Methylcellulose', 'contains'),
  ('body-by-freaks-bundle', 'Octyldodecyl Citrate Crosspolymer', 'contains'),
  ('body-by-freaks-bundle', 'Phenoxyethanol', 'contains'),
  ('body-by-freaks-bundle', 'Polyglyceryl-4 Laurate', 'contains'),
  ('body-by-freaks-bundle', 'Populus Tremuloides Bark Extract', 'contains'),
  ('body-by-freaks-bundle', 'Simmondsia Chinensis (Jojoba) Seed Oil', 'contains'),
  ('body-by-freaks-bundle', 'Sodium Lauryl Glucose Carboxylate', 'contains'),
  ('body-by-freaks-bundle', 'Sodium Phytate', 'contains'),
  ('body-by-freaks-bundle', 'Sodium Stearoyl Glutamate', 'contains'),
  ('body-by-freaks-bundle', 'Sorbitan Laurate', 'contains'),
  ('body-by-freaks-bundle', 'Xanthan Gum', 'contains'),
  ('body-by-freaks-bundle', 'Fragrance', 'free_from'),
  ('body-by-freaks-bundle', 'Oxybenzone', 'free_from'),
  ('body-by-freaks-bundle', 'Octinoxate', 'free_from'),
  ('freak-family-pack-v3', 'Zinc Oxide', 'contains'),
  ('freak-family-pack-v3', 'Water', 'contains'),
  ('freak-family-pack-v3', 'Coco-Caprylate/Caprate', 'contains'),
  ('freak-family-pack-v3', 'Caprylic/Capric Triglyceride', 'contains'),
  ('freak-family-pack-v3', 'Polyglyceryl-4 Diisostearate/Polyhydroxystearate/Sebacate', 'contains'),
  ('freak-family-pack-v3', 'Propanediol', 'contains'),
  ('freak-family-pack-v3', 'C13-15 Alkane', 'contains'),
  ('freak-family-pack-v3', 'Squalane', 'contains'),
  ('freak-family-pack-v3', 'Maleated Soybean Oil Glyceryl/Octyldodecanol Esters', 'contains'),
  ('freak-family-pack-v3', 'Copernicia Cerifera (Carnauba) Wax', 'contains'),
  ('freak-family-pack-v3', 'Methylheptylglycerin', 'contains'),
  ('freak-family-pack-v3', 'Sr-wasp spider polypeptide-1 oligopeptide-178', 'contains'),
  ('freak-family-pack-v3', 'Bentonite', 'contains'),
  ('freak-family-pack-v3', 'Polyricinoleic acid', 'contains'),
  ('freak-family-pack-v3', 'Polyhydroxystearic Acid', 'contains'),
  ('freak-family-pack-v3', 'Glycerin', 'contains'),
  ('freak-family-pack-v3', 'Pongamia Pinnata Seed Extract', 'contains'),
  ('freak-family-pack-v3', 'Xanthan Gum', 'contains'),
  ('freak-family-pack-v3', 'Caprylhydroxamic Acid', 'contains'),
  ('freak-family-pack-v3', 'Oryza Sativa (Rice) Bran Wax', 'contains'),
  ('freak-family-pack-v3', 'DL-Alpha Tocopherol', 'contains'),
  ('freak-family-pack-v3', 'Sodium Phytate', 'contains'),
  ('freak-family-pack-v3', 'Titanium Dioxide', 'contains'),
  ('freak-family-pack-v3', 'Stearyl/Octyldodecyl Citrate Crosspolymer', 'contains'),
  ('freak-family-pack-v3', 'Porphyra Umbilicalis Extract Aqua', 'contains'),
  ('freak-family-pack-v3', 'Cetearyl Olivate', 'contains'),
  ('freak-family-pack-v3', 'Sorbitan Olivate', 'contains'),
  ('freak-family-pack-v3', 'Cetyl Alcohol', 'contains'),
  ('freak-family-pack-v3', 'Stearic Acid', 'contains'),
  ('freak-family-pack-v3', 'Helianthus Annuus (Sunflower) Seed Wax', 'contains'),
  ('freak-family-pack-v3', 'Isoamyl Laurate', 'contains'),
  ('freak-family-pack-v3', 'Ethylhexyl Olivate', 'contains'),
  ('freak-family-pack-v3', 'Oryza Sativa (Rice Bran) Oil', 'contains'),
  ('freak-family-pack-v3', 'Quaternium-90 Bentonite', 'contains'),
  ('freak-family-pack-v3', 'Capryloyl Glycerin/Sebacic Acid Copolymer', 'contains'),
  ('freak-family-pack-v3', 'Prototheca Moriformis (Microalgae) Oil', 'contains'),
  ('freak-family-pack-v3', 'Theobroma Cacao (Cocoa) Seed Butter', 'contains'),
  ('freak-family-pack-v3', 'Isostearic Acid', 'contains'),
  ('freak-family-pack-v3', 'Lecithin', 'contains'),
  ('freak-family-pack-v3', 'Polyglyceryl-3 Polyricinoleate', 'contains'),
  ('freak-family-pack-v3', 'Triethyl Citrate', 'contains'),
  ('freak-family-pack-v3', 'Physalis Angulata (Ground Cherry) Extract', 'contains'),
  ('freak-family-pack-v3', 'Rhododendron Ferrugineum (Alpenrose) Extract', 'contains'),
  ('freak-family-pack-v3', 'Undaria Pinnatifida (Wakame) Extract', 'contains'),
  ('freak-family-pack-v3', 'Saccharomyces Ferment', 'contains'),
  ('freak-family-pack-v3', 'Laurel Lysine', 'contains'),
  ('freak-family-pack-v3', 'Tocopherol Acetate', 'contains'),
  ('freak-family-pack-v3', 'Tocopherol', 'contains'),
  ('freak-family-pack-v3', 'Avena Sativa (Oat) Kernel Oil', 'contains'),
  ('freak-family-pack-v3', 'Dextrin Palmitate', 'contains'),
  ('freak-family-pack-v3', 'Plukenetia Volubilis (Sacha Inchi) Seed Oil', 'contains'),
  ('freak-family-pack-v3', 'Simmondsia Chinensis (Jojoba) Seed Oil', 'contains'),
  ('freak-family-pack-v3', 'Padina Pavonica Thallus Extract', 'contains'),
  ('freak-family-pack-v3', 'Bacillus Ferment', 'contains'),
  ('freak-family-pack-v3', 'Sodium Cocoyl Apple Amino Acids', 'contains'),
  ('freak-family-pack-v3', 'Sucrose Stearate', 'contains'),
  ('freak-family-pack-v3', 'Betaine', 'contains'),
  ('freak-family-pack-v3', 'Aspergillus Ferment', 'contains'),
  ('freak-family-pack-v3', 'Vitis Vinifera (Grape) Seed Oil', 'contains'),
  ('freak-family-pack-v3', 'Oryza Sativa (Rice) Bran Oil', 'contains'),
  ('freak-family-pack-v3', 'Camellia Oleifera Seed Oil', 'contains'),
  ('freak-family-pack-v3', 'Spirulina Platensis Extract', 'contains'),
  ('freak-family-pack-v3', 'Trehalose', 'contains'),
  ('freak-family-pack-v3', 'Sodium Citrate', 'contains'),
  ('freak-family-pack-v3', 'Maranta Arundinacea (Arrowroot) Root Extract', 'contains'),
  ('freak-family-pack-v3', 'Helianthus Annuus (Sunflower) Seed Oil', 'contains'),
  ('freak-family-pack-v3', 'Ethylhexyl Palmitate', 'contains'),
  ('freak-family-pack-v3', 'Myrica Pubescens (Laurel) Fruit Wax', 'contains'),
  ('freak-family-pack-v3', 'Bambusa Arundinacea (Bamboo) Stem Extract', 'contains'),
  ('freak-family-pack-v3', 'Zinc Ricinoleate', 'contains'),
  ('freak-family-pack-v3', 'Glyceryl Laurate', 'contains'),
  ('freak-family-pack-v3', 'Silica', 'contains'),
  ('freak-family-pack-v3', 'Citronellyl Methylcrotonate', 'contains'),
  ('freak-family-pack-v3', 'Tocopheryl Acetate', 'contains'),
  ('freak-family-pack-v3', 'Fragrance (Parfum)', 'contains'),
  ('freak-family-pack-v3', 'Chromium Hydroxide Green (CI 77289)', 'contains'),
  ('freak-family-pack-v3', 'Oxybenzone', 'free_from'),
  ('freak-family-pack-v3', 'Octinoxate', 'free_from'),
  ('freak-trio', 'Zinc Oxide', 'contains'),
  ('freak-trio', 'Water', 'contains'),
  ('freak-trio', 'Coco-Caprylate/Caprate', 'contains'),
  ('freak-trio', 'Caprylic/Capric Triglyceride', 'contains'),
  ('freak-trio', 'Polyglyceryl-4 Diisostearate/Polyhydroxystearate/Sebacate', 'contains'),
  ('freak-trio', 'Propanediol', 'contains'),
  ('freak-trio', 'C13-15 Alkane', 'contains'),
  ('freak-trio', 'Squalane', 'contains'),
  ('freak-trio', 'Maleated Soybean Oil Glyceryl/Octyldodecanol Esters', 'contains'),
  ('freak-trio', 'Copernicia Cerifera (Carnauba) Wax', 'contains'),
  ('freak-trio', 'Methylheptylglycerin', 'contains'),
  ('freak-trio', 'Sr-wasp spider polypeptide-1 oligopeptide-178', 'contains'),
  ('freak-trio', 'Bentonite', 'contains'),
  ('freak-trio', 'Polyricinoleic acid', 'contains'),
  ('freak-trio', 'Polyhydroxystearic Acid', 'contains'),
  ('freak-trio', 'Glycerin', 'contains'),
  ('freak-trio', 'Pongamia Pinnata Seed Extract', 'contains'),
  ('freak-trio', 'Xanthan Gum', 'contains'),
  ('freak-trio', 'Caprylhydroxamic Acid', 'contains'),
  ('freak-trio', 'Oryza Sativa (Rice) Bran Wax', 'contains'),
  ('freak-trio', 'DL-Alpha Tocopherol', 'contains'),
  ('freak-trio', 'Sodium Phytate', 'contains'),
  ('freak-trio', 'Titanium Dioxide', 'contains'),
  ('freak-trio', 'Stearyl/Octyldodecyl Citrate Crosspolymer', 'contains'),
  ('freak-trio', 'Porphyra Umbilicalis Extract Aqua', 'contains'),
  ('freak-trio', 'Cetearyl Olivate', 'contains'),
  ('freak-trio', 'Sorbitan Olivate', 'contains'),
  ('freak-trio', 'Cetyl Alcohol', 'contains'),
  ('freak-trio', 'Stearic Acid', 'contains'),
  ('freak-trio', 'Avena Sativa (Oat) Kernel Oil', 'contains'),
  ('freak-trio', 'Dextrin Palmitate', 'contains'),
  ('freak-trio', 'Plukenetia Volubilis (Sacha Inchi) Seed Oil', 'contains'),
  ('freak-trio', 'Simmondsia Chinensis (Jojoba) Seed Oil', 'contains'),
  ('freak-trio', 'Padina Pavonica Thallus Extract', 'contains'),
  ('freak-trio', 'Bacillus Ferment', 'contains'),
  ('freak-trio', 'Tocopherol', 'contains'),
  ('freak-trio', 'Oxybenzone', 'free_from'),
  ('freak-trio', 'Octinoxate', 'free_from'),
  ('peak-performance-duo', 'Zinc Oxide', 'contains'),
  ('peak-performance-duo', 'Titanium Dioxide', 'contains'),
  ('peak-performance-duo', 'Water', 'contains'),
  ('peak-performance-duo', 'Coco-Caprylate/Caprate', 'contains'),
  ('peak-performance-duo', 'Caprylic/Capric Triglyceride', 'contains'),
  ('peak-performance-duo', 'Maleated Soybean Oil Glyceryl/Octyldodecanol Esters', 'contains'),
  ('peak-performance-duo', 'Polyglyceryl-4 Diisostearate/Polyhydroxystearate/Sebacate', 'contains'),
  ('peak-performance-duo', 'Propanediol', 'contains'),
  ('peak-performance-duo', 'Stearyl/Octyldodecyl Citrate Crosspolymer', 'contains'),
  ('peak-performance-duo', 'Copernicia Cerifera (Carnauba) Wax', 'contains'),
  ('peak-performance-duo', 'Bentonite', 'contains'),
  ('peak-performance-duo', 'Methylheptylglycerin', 'contains'),
  ('peak-performance-duo', 'Squalane', 'contains'),
  ('peak-performance-duo', 'Sr-wasp spider polypeptide-1 oligopeptide-178', 'contains'),
  ('peak-performance-duo', 'Porphyra Umbilicalis Extract Aqua', 'contains'),
  ('peak-performance-duo', 'Cetearyl Olivate', 'contains'),
  ('peak-performance-duo', 'Sorbitan Olivate', 'contains'),
  ('peak-performance-duo', 'Polyhydroxystearic Acid', 'contains'),
  ('peak-performance-duo', 'Polyricinoleic acid', 'contains'),
  ('peak-performance-duo', 'Glycerin', 'contains'),
  ('peak-performance-duo', 'Xanthan Gum', 'contains'),
  ('peak-performance-duo', 'Cetyl Alcohol', 'contains'),
  ('peak-performance-duo', 'Pongamia Pinnata Seed Extract', 'contains'),
  ('peak-performance-duo', 'Caprylhydroxamic Acid', 'contains'),
  ('peak-performance-duo', 'Oryza Sativa (Rice) Bran Wax', 'contains'),
  ('peak-performance-duo', 'DL-Alpha Tocopherol', 'contains'),
  ('peak-performance-duo', 'Stearic Acid', 'contains'),
  ('peak-performance-duo', 'Sodium Phytate', 'contains'),
  ('peak-performance-duo', 'Helianthus Annuus (Sunflower) Seed Wax', 'contains'),
  ('peak-performance-duo', 'Isoamyl Laurate', 'contains'),
  ('peak-performance-duo', 'Ethylhexyl Olivate', 'contains'),
  ('peak-performance-duo', 'C13-15 Alkane', 'contains'),
  ('peak-performance-duo', 'Oryza Sativa (Rice Bran) Oil', 'contains'),
  ('peak-performance-duo', 'Quaternium-90 Bentonite', 'contains'),
  ('peak-performance-duo', 'Capryloyl Glycerin/Sebacic Acid Copolymer', 'contains'),
  ('peak-performance-duo', 'Prototheca Moriformis (Microalgae) Oil', 'contains'),
  ('peak-performance-duo', 'Theobroma Cacao (Cocoa) Seed Butter', 'contains'),
  ('peak-performance-duo', 'Isostearic Acid', 'contains'),
  ('peak-performance-duo', 'Lecithin', 'contains'),
  ('peak-performance-duo', 'Polyglyceryl-3 Polyricinoleate', 'contains'),
  ('peak-performance-duo', 'Triethyl Citrate', 'contains'),
  ('peak-performance-duo', 'Physalis Angulata (Ground Cherry) Extract', 'contains'),
  ('peak-performance-duo', 'Rhododendron Ferrugineum (Alpenrose) Extract', 'contains'),
  ('peak-performance-duo', 'Undaria Pinnatifida (Wakame) Extract', 'contains'),
  ('peak-performance-duo', 'Saccharomyces Ferment', 'contains'),
  ('peak-performance-duo', 'Laurel Lysine', 'contains'),
  ('peak-performance-duo', 'Tocopherol Acetate', 'contains'),
  ('peak-performance-duo', 'Tocopherol', 'contains'),
  ('peak-performance-duo', 'Fragrance', 'free_from'),
  ('peak-performance-duo', 'Oxybenzone', 'free_from'),
  ('peak-performance-duo', 'Octinoxate', 'free_from'),
  ('balanced-skin-set', 'Squalane', 'contains'),
  ('balanced-skin-set', 'Avena Sativa (Oat) Kernel Oil', 'contains'),
  ('balanced-skin-set', 'Dextrin Palmitate', 'contains'),
  ('balanced-skin-set', 'Plukenetia Volubilis (Sacha Inchi) Seed Oil', 'contains'),
  ('balanced-skin-set', 'Simmondsia Chinensis (Jojoba) Seed Oil', 'contains'),
  ('balanced-skin-set', 'Padina Pavonica Thallus Extract', 'contains'),
  ('balanced-skin-set', 'Bacillus Ferment', 'contains'),
  ('balanced-skin-set', 'Tocopherol', 'contains'),
  ('balanced-skin-set', 'Glycerin', 'contains'),
  ('balanced-skin-set', 'Sodium Cocoyl Apple Amino Acids', 'contains'),
  ('balanced-skin-set', 'Sucrose Stearate', 'contains'),
  ('balanced-skin-set', 'Betaine', 'contains'),
  ('balanced-skin-set', 'Saccharomyces Ferment', 'contains'),
  ('balanced-skin-set', 'Aspergillus Ferment', 'contains'),
  ('balanced-skin-set', 'Vitis Vinifera (Grape) Seed Oil', 'contains'),
  ('balanced-skin-set', 'Oryza Sativa (Rice) Bran Oil', 'contains'),
  ('balanced-skin-set', 'Camellia Oleifera Seed Oil', 'contains'),
  ('balanced-skin-set', 'Spirulina Platensis Extract', 'contains'),
  ('balanced-skin-set', 'Trehalose', 'contains'),
  ('balanced-skin-set', 'Sodium Citrate', 'contains'),
  ('balanced-skin-set', 'Fragrance', 'free_from'),
  ('daily-system', 'Zinc Oxide', 'contains'),
  ('daily-system', 'Water', 'contains'),
  ('daily-system', 'Coco-Caprylate/Caprate', 'contains'),
  ('daily-system', 'Caprylic/Capric Triglyceride', 'contains'),
  ('daily-system', 'Polyglyceryl-4 Diisostearate/Polyhydroxystearate/Sebacate', 'contains'),
  ('daily-system', 'Propanediol', 'contains'),
  ('daily-system', 'C13-15 Alkane', 'contains'),
  ('daily-system', 'Squalane', 'contains'),
  ('daily-system', 'Maleated Soybean Oil Glyceryl/Octyldodecanol Esters', 'contains'),
  ('daily-system', 'Copernicia Cerifera (Carnauba) Wax', 'contains'),
  ('daily-system', 'Methylheptylglycerin', 'contains'),
  ('daily-system', 'Sr-wasp spider polypeptide-1 oligopeptide-178', 'contains'),
  ('daily-system', 'Bentonite', 'contains'),
  ('daily-system', 'Polyricinoleic acid', 'contains'),
  ('daily-system', 'Polyhydroxystearic Acid', 'contains'),
  ('daily-system', 'Glycerin', 'contains'),
  ('daily-system', 'Pongamia Pinnata Seed Extract', 'contains'),
  ('daily-system', 'Xanthan Gum', 'contains'),
  ('daily-system', 'Caprylhydroxamic Acid', 'contains'),
  ('daily-system', 'Oryza Sativa (Rice) Bran Wax', 'contains'),
  ('daily-system', 'DL-Alpha Tocopherol', 'contains'),
  ('daily-system', 'Sodium Phytate', 'contains'),
  ('daily-system', 'Avena Sativa (Oat) Kernel Oil', 'contains'),
  ('daily-system', 'Dextrin Palmitate', 'contains'),
  ('daily-system', 'Plukenetia Volubilis (Sacha Inchi) Seed Oil', 'contains'),
  ('daily-system', 'Simmondsia Chinensis (Jojoba) Seed Oil', 'contains'),
  ('daily-system', 'Padina Pavonica Thallus Extract', 'contains'),
  ('daily-system', 'Bacillus Ferment', 'contains'),
  ('daily-system', 'Tocopherol', 'contains'),
  ('daily-system', 'Oxybenzone', 'free_from'),
  ('daily-system', 'Octinoxate', 'free_from'),
  ('endurance-system', 'Zinc Oxide', 'contains'),
  ('endurance-system', 'Titanium Dioxide', 'contains'),
  ('endurance-system', 'Water', 'contains'),
  ('endurance-system', 'Coco-Caprylate/Caprate', 'contains'),
  ('endurance-system', 'Caprylic/Capric Triglyceride', 'contains'),
  ('endurance-system', 'Maleated Soybean Oil Glyceryl/Octyldodecanol Esters', 'contains'),
  ('endurance-system', 'Polyglyceryl-4 Diisostearate/Polyhydroxystearate/Sebacate', 'contains'),
  ('endurance-system', 'Propanediol', 'contains'),
  ('endurance-system', 'Stearyl/Octyldodecyl Citrate Crosspolymer', 'contains'),
  ('endurance-system', 'Copernicia Cerifera (Carnauba) Wax', 'contains'),
  ('endurance-system', 'Bentonite', 'contains'),
  ('endurance-system', 'Methylheptylglycerin', 'contains'),
  ('endurance-system', 'Squalane', 'contains'),
  ('endurance-system', 'Sr-wasp spider polypeptide-1 oligopeptide-178', 'contains'),
  ('endurance-system', 'Porphyra Umbilicalis Extract Aqua', 'contains'),
  ('endurance-system', 'Cetearyl Olivate', 'contains'),
  ('endurance-system', 'Sorbitan Olivate', 'contains'),
  ('endurance-system', 'Polyhydroxystearic Acid', 'contains'),
  ('endurance-system', 'Polyricinoleic acid', 'contains'),
  ('endurance-system', 'Glycerin', 'contains'),
  ('endurance-system', 'Xanthan Gum', 'contains'),
  ('endurance-system', 'Cetyl Alcohol', 'contains'),
  ('endurance-system', 'Pongamia Pinnata Seed Extract', 'contains'),
  ('endurance-system', 'Caprylhydroxamic Acid', 'contains'),
  ('endurance-system', 'Oryza Sativa (Rice) Bran Wax', 'contains'),
  ('endurance-system', 'DL-Alpha Tocopherol', 'contains'),
  ('endurance-system', 'Stearic Acid', 'contains'),
  ('endurance-system', 'Sodium Phytate', 'contains'),
  ('endurance-system', 'Avena Sativa (Oat) Kernel Oil', 'contains'),
  ('endurance-system', 'Dextrin Palmitate', 'contains'),
  ('endurance-system', 'Plukenetia Volubilis (Sacha Inchi) Seed Oil', 'contains'),
  ('endurance-system', 'Simmondsia Chinensis (Jojoba) Seed Oil', 'contains'),
  ('endurance-system', 'Padina Pavonica Thallus Extract', 'contains'),
  ('endurance-system', 'Bacillus Ferment', 'contains'),
  ('endurance-system', 'Tocopherol', 'contains'),
  ('endurance-system', 'Oxybenzone', 'free_from'),
  ('endurance-system', 'Octinoxate', 'free_from'),
  ('endurance-system-sport-mode', 'Zinc Oxide', 'contains'),
  ('endurance-system-sport-mode', 'Helianthus Annuus (Sunflower) Seed Wax', 'contains'),
  ('endurance-system-sport-mode', 'Isoamyl Laurate', 'contains'),
  ('endurance-system-sport-mode', 'Ethylhexyl Olivate', 'contains'),
  ('endurance-system-sport-mode', 'Caprylic/Capric Triglyceride', 'contains'),
  ('endurance-system-sport-mode', 'C13-15 Alkane', 'contains'),
  ('endurance-system-sport-mode', 'Polyhydroxystearic Acid', 'contains'),
  ('endurance-system-sport-mode', 'Oryza Sativa (Rice Bran) Oil', 'contains'),
  ('endurance-system-sport-mode', 'Quaternium-90 Bentonite', 'contains'),
  ('endurance-system-sport-mode', 'Capryloyl Glycerin/Sebacic Acid Copolymer', 'contains'),
  ('endurance-system-sport-mode', 'Prototheca Moriformis (Microalgae) Oil', 'contains'),
  ('endurance-system-sport-mode', 'Theobroma Cacao (Cocoa) Seed Butter', 'contains'),
  ('endurance-system-sport-mode', 'Isostearic Acid', 'contains'),
  ('endurance-system-sport-mode', 'Lecithin', 'contains'),
  ('endurance-system-sport-mode', 'Polyglyceryl-3 Polyricinoleate', 'contains'),
  ('endurance-system-sport-mode', 'Triethyl Citrate', 'contains'),
  ('endurance-system-sport-mode', 'Squalane', 'contains'),
  ('endurance-system-sport-mode', 'Physalis Angulata (Ground Cherry) Extract', 'contains'),
  ('endurance-system-sport-mode', 'Rhododendron Ferrugineum (Alpenrose) Extract', 'contains'),
  ('endurance-system-sport-mode', 'Undaria Pinnatifida (Wakame) Extract', 'contains'),
  ('endurance-system-sport-mode', 'Saccharomyces Ferment', 'contains'),
  ('endurance-system-sport-mode', 'Laurel Lysine', 'contains'),
  ('endurance-system-sport-mode', 'Tocopherol Acetate', 'contains'),
  ('endurance-system-sport-mode', 'Tocopherol', 'contains'),
  ('endurance-system-sport-mode', 'Fragrance', 'free_from'),
  ('endurance-system-sport-mode', 'Oxybenzone', 'free_from'),
  ('endurance-system-sport-mode', 'Octinoxate', 'free_from'),
  ('deo-duo-bundle', 'Caprylic/Capric Triglyceride', 'contains'),
  ('deo-duo-bundle', 'Maranta Arundinacea (Arrowroot) Root Extract', 'contains'),
  ('deo-duo-bundle', 'Helianthus Annuus (Sunflower) Seed Oil', 'contains'),
  ('deo-duo-bundle', 'Ethylhexyl Palmitate', 'contains'),
  ('deo-duo-bundle', 'Myrica Pubescens (Laurel) Fruit Wax', 'contains'),
  ('deo-duo-bundle', 'Theobroma Cacao (Cocoa) Seed Butter', 'contains'),
  ('deo-duo-bundle', 'Triethyl Citrate', 'contains'),
  ('deo-duo-bundle', 'Bambusa Arundinacea (Bamboo) Stem Extract', 'contains'),
  ('deo-duo-bundle', 'Zinc Ricinoleate', 'contains'),
  ('deo-duo-bundle', 'Bentonite', 'contains'),
  ('deo-duo-bundle', 'Glyceryl Laurate', 'contains'),
  ('deo-duo-bundle', 'Helianthus Annuus (Sunflower) Seed Wax', 'contains'),
  ('deo-duo-bundle', 'Silica', 'contains'),
  ('deo-duo-bundle', 'Oryza Sativa (Rice) Bran Wax', 'contains'),
  ('deo-duo-bundle', 'Citronellyl Methylcrotonate', 'contains'),
  ('deo-duo-bundle', 'Tocopheryl Acetate', 'contains'),
  ('deo-duo-bundle', 'Fragrance (Parfum)', 'contains'),
  ('deo-duo-bundle', 'Chromium Hydroxide Green (CI 77289)', 'contains'),
  ('skin-support-electrolyte', 'Vitamin A', 'contains'),
  ('skin-support-electrolyte', 'Vitamin C', 'contains'),
  ('skin-support-electrolyte', 'Vitamin D', 'contains'),
  ('skin-support-electrolyte', 'Vitamin E', 'contains'),
  ('skin-support-electrolyte', 'Vitamin B3', 'contains'),
  ('skin-support-electrolyte', 'Calcium', 'contains'),
  ('skin-support-electrolyte', 'Magnesium', 'contains'),
  ('skin-support-electrolyte', 'Zinc', 'contains'),
  ('skin-support-electrolyte', 'Chloride', 'contains'),
  ('skin-support-electrolyte', 'Sodium', 'contains'),
  ('skin-support-electrolyte', 'Potassium', 'contains'),
  ('skin-support-electrolyte', 'Astaxanthin', 'contains'),
  ('skin-support-electrolyte', 'Polypodium leucotomos Leaf Extract', 'contains'),
  ('skin-support-electrolyte', 'Red Orange (Citrus sinensis) Fruit Extract', 'contains'),
  ('skin-support-electrolyte', 'Partially Hydrolyzed Guar Gum', 'contains'),
  ('skin-support-electrolyte', 'Ginger (Zingiber officinale) Root Extract', 'contains'),
  ('skin-support-electrolyte', 'and Sodium Hyaluronate', 'contains'),
  ('skin-support-electrolyte', 'Natural Flavors', 'contains'),
  ('skin-support-electrolyte', 'Citric Acid', 'contains'),
  ('skin-support-electrolyte', 'Malic Acid', 'contains'),
  ('skin-support-electrolyte', 'Rebaudioside A (Stevia Leaf Extract)', 'contains'),
  ('everyday-endurance-trio', 'Caprylic/Capric Triglyceride', 'contains'),
  ('everyday-endurance-trio', 'Maranta Arundinacea (Arrowroot) Root Extract', 'contains'),
  ('everyday-endurance-trio', 'Helianthus Annuus (Sunflower) Seed Oil', 'contains'),
  ('everyday-endurance-trio', 'Ethylhexyl Palmitate', 'contains'),
  ('everyday-endurance-trio', 'Myrica Pubescens (Laurel) Fruit Wax', 'contains'),
  ('everyday-endurance-trio', 'Theobroma Cacao (Cocoa) Seed Butter', 'contains'),
  ('everyday-endurance-trio', 'Triethyl Citrate', 'contains'),
  ('everyday-endurance-trio', 'Bambusa Arundinacea (Bamboo) Stem Extract', 'contains'),
  ('everyday-endurance-trio', 'Zinc Ricinoleate', 'contains'),
  ('everyday-endurance-trio', 'Bentonite', 'contains'),
  ('everyday-endurance-trio', 'Glyceryl Laurate', 'contains'),
  ('everyday-endurance-trio', 'Helianthus Annuus (Sunflower) Seed Wax', 'contains'),
  ('everyday-endurance-trio', 'Silica', 'contains'),
  ('everyday-endurance-trio', 'Oryza Sativa (Rice) Bran Wax', 'contains'),
  ('everyday-endurance-trio', 'Citronellyl Methylcrotonate', 'contains'),
  ('everyday-endurance-trio', 'Tocopheryl Acetate', 'contains'),
  ('everyday-endurance-trio', 'Fragrance (Parfum)', 'contains'),
  ('everyday-endurance-trio', 'Chromium Hydroxide Green (CI 77289)', 'contains')
)
insert into public.product_ingredients (product_id, ingredient_id, kind)
select p.id, i.id, l.kind::text
from links l
join public.products p on p.slug = l.product_slug
join public.ingredients i on i.name = l.ingredient_name
on conflict do nothing;

insert into public.brand_categories (brand_id, category_id)
select distinct p.brand_id, c.id
from public.products p
join public.categories c on c.slug = p.category::text
on conflict do nothing;

update public.products p
set category_id = c.id
from public.categories c
where c.slug = p.category::text
  and p.category_id is null;
