-- Freaks of Nature seed (editor-safe)
-- No apostrophes, editor-safe copy, no multi-line strings.
-- https://supabase.com/dashboard/project/crxvkpamidsnrezguntl/sql/new

create table if not exists public.categories (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  name text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.brand_categories (
  brand_id uuid not null references public.brands (id) on delete cascade,
  category_id uuid not null references public.categories (id) on delete cascade,
  primary key (brand_id, category_id)
);

create index if not exists brand_categories_category_id_idx on public.brand_categories (category_id);

alter table public.categories enable row level security;
alter table public.brand_categories enable row level security;

do $policy$ begin
  create policy "Public read categories" on public.categories for select using (true);
exception when duplicate_object then null; end $policy$;
do $policy$ begin
  create policy "Public read brand categories" on public.brand_categories for select using (true);
exception when duplicate_object then null; end $policy$;

insert into public.categories (id, slug, name) values
  ('c1000000-0000-0000-0000-000000000001', 'sunscreen', 'Sunscreen'),
  ('c1000000-0000-0000-0000-000000000002', 'deodorant', 'Deodorant'),
  ('c1000000-0000-0000-0000-000000000003', 'protein', 'Protein'),
  ('c1000000-0000-0000-0000-000000000004', 'skincare', 'Skincare'),
  ('c1000000-0000-0000-0000-000000000005', 'hair', 'Hair care'),
  ('c1000000-0000-0000-0000-000000000006', 'oral', 'Oral care'),
  ('c1000000-0000-0000-0000-000000000007', 'electrolytes', 'Electrolytes')
on conflict (slug) do nothing;

alter table public.products add column if not exists category_id uuid references public.categories (id);
alter table public.products add column if not exists size text;
alter table public.products add column if not exists how_to_use text not null default '';
alter table public.products add column if not exists good_for text not null default '';
alter table public.products add column if not exists smells_like text not null default '';
alter table public.products add column if not exists finish text not null default '';
alter table public.products add column if not exists features text[] not null default '{}';

insert into public.brands (id, slug, name, tagline, story, location, founded, accent, rating, review_count, follower_count, website_url) values (
  '00000000-0000-0000-0000-000000000001',
  'freaks-of-nature',
  'Freaks of Nature',
  'Mineral protection for skin that actually lives outside',
  'Clean, 100% mineral formulas built for real life outside — sunscreen, barrier care, and everyday essentials without chemical filters or greasy residue.',
  'United States',
  2020,
  '#2F6F5E',
  4.8,
  444,
  0,
  'https://freaksofnature.com'
)
on conflict (slug) do update set
  name = excluded.name,
  tagline = excluded.tagline,
  story = excluded.story,
  accent = excluded.accent,
  rating = excluded.rating,
  review_count = excluded.review_count,
  website_url = excluded.website_url;

insert into public.brand_categories (brand_id, category_id)
select b.id, c.id
from public.brands b
join public.categories c on c.slug in ('sunscreen', 'deodorant', 'skincare')
where b.slug = 'freaks-of-nature'
on conflict do nothing;

insert into public.products (
  id, slug, brand_id, name, category, category_id, price, description, accent,
  affiliate_url, affiliate_network, image_url, rating, review_count,
  size, how_to_use, good_for, smells_like, finish, features, is_published
) values
  (
    'f0000000-0000-0000-0000-000000000001',
    'solar-shield-spray',
    (select id from public.brands where slug = 'freaks-of-nature'),
    'Solar Shield SPF 30 Spray',
    'sunscreen',
    (select id from public.categories where slug = 'sunscreen'),
    26,
    'Full-body mineral protection',
    '#2F6F5E',
    'https://freaksofnature.com/products/solar-shield-spray',
    'direct',
    'https://freaksofnature.com/cdn/shop/files/3D_SPRAY_E-COMM.png?v=1777037746&width=1920',
    4.9,
    117,
    '6 oz / 170 g',
    'Shake well before use. Hold container 4--6 inches from skin and spray liberally and evenly across the body. Rub into skin. Apply 15 minutes before sun exposure. Reapply after 40 minutes of swimming or sweating, immediately after towel drying, and at least every 2 hours.',
    'All skin types',
    'Nothing! Unlike the painfully nostalgic odor (i.e. harsh and chemically) of most sunscreens, ours is completely unscented.',
    'Lightweight, breathable, and nearly invisible on skin.',
    array['100% mineral protection', 'Air-powered continuous spray', 'Minimal white cast', 'Hydrates + soothes', 'Protects + strengthens skin barrier', 'No chemical filters', 'Water resistant (40 min)', 'Dermatologist tested', 'Broad spectrum UV protection', 'Reef safe', 'Fragrance free']::text[],
    true
  ),
  (
    'f0000000-0000-0000-0000-000000000002',
    'sun-stick-spf50',
    (select id from public.brands where slug = 'freaks-of-nature'),
    'Peak Performance Sun Stick SPF50',
    'sunscreen',
    (select id from public.categories where slug = 'sunscreen'),
    24,
    '100% Mineral Sunscreen High-performance, lightweight non-greasy, broad spectrum protection for the long haul.',
    '#2F6F5E',
    'https://freaksofnature.com/products/sun-stick-spf50',
    'direct',
    'https://freaksofnature.com/cdn/shop/files/STICK-web-optimized-transparent.png?v=1775474333&width=1920',
    4.9,
    189,
    '0.70 oz / 20 gr',
    '15 minutes before going in the sun liberally apply onto face, neck, chest and body if applicable. Reapply after 80 min of swimming or sweating, immediately after towel drying and at least every 2 hours when exposed to the sun. Product can be re-applied over or under makeup.',
    'All Skin Types',
    'Nothing! Unlike the painfully nostalgic odor (i.e. harsh and chemically) of most sunscreens, ours is completely unscented.',
    'Goes on silky smooth, clear, and easily with a bare skin feel that will not warp, slip or drip into the eyes.',
    array['100% mineral protection', 'Water resistant (40 min)', 'Protects + strengthens skin barrier', 'Broad spectrum UV protection', 'Fragrance free', 'Reef safe', 'Dermatologist tested', 'Minimal white cast']::text[],
    true
  ),
  (
    'f0000000-0000-0000-0000-000000000003',
    'everyday-endurance-deodorant',
    (select id from public.brands where slug = 'freaks-of-nature'),
    'Everyday Endurance Deodorant',
    'deodorant',
    (select id from public.categories where slug = 'deodorant'),
    20,
    'All natural with 48-hour odor protection',
    '#2F6F5E',
    'https://freaksofnature.com/products/everyday-endurance-deodorant',
    'direct',
    'https://freaksofnature.com/cdn/shop/files/Single_Deo.png?v=1776275794&width=1920',
    4.2,
    55,
    '75ml / 2.6 fl oz',
    '**Step 1:**Remove top and twist the bottom until formula begins to appear from perforated cap (Do not overtwist! A little goes a long way) **Step 2:**Apply formula directly on clean, dry underarms -- damp skin reduces effectiveness. **Step 3:**Apply formula directly on underarm For best results, keep deodorant at room temperature (68°F to 77°F / 20°C to 25°C)',
    'All skin types',
    'Warm amber and smooth santal finished with earthy spice.',
    'A creamy texture that dries within 30 seconds. Not sticky or wet and lasts for 48 hours. In our perception study 93% of users found that the deo did not leave stains or marks on clothing.',
    array['Dermatologist tested', 'Protects + strengthens skin barrier', 'Fragrance free']::text[],
    true
  ),
  (
    'f0000000-0000-0000-0000-000000000004',
    'jumbo-sun-stick',
    (select id from public.brands where slug = 'freaks-of-nature'),
    'Peak Performance Jumbo Sun Stick',
    'sunscreen',
    (select id from public.categories where slug = 'sunscreen'),
    44,
    '100% Mineral Sunscreen',
    '#2F6F5E',
    'https://freaksofnature.com/products/jumbo-sun-stick',
    'direct',
    'https://freaksofnature.com/cdn/shop/files/3D_STICK-SPF50_L_E-COMM.png?v=1776776007&width=1920',
    4.9,
    189,
    '2.60 oz / 75 gr',
    '15 minutes before going in the sun liberally apply onto face, neck, chest and body if applicable. Reapply after 80 min of swimming or sweating, immediately after towel drying and at least every 2 hours when exposed to the sun. Product can be re-applied over or under makeup.',
    'All Skin Types',
    'Nothing! Unlike the painfully nostalgic odor (i.e. harsh and chemically) of most sunscreens, ours is completely unscented.',
    'Goes on silky smooth, clear, and easily with a bare skin feel that will not warp, slip or drip into the eyes.',
    array['100% mineral protection', 'Water resistant (40 min)', 'Protects + strengthens skin barrier', 'Broad spectrum UV protection', 'Reef safe', 'Fragrance free', 'Dermatologist tested', 'Minimal white cast']::text[],
    true
  ),
  (
    'f0000000-0000-0000-0000-000000000005',
    'peak-performance-sunscreen',
    (select id from public.brands where slug = 'freaks-of-nature'),
    'Peak Performance SPF50',
    'sunscreen',
    (select id from public.categories where slug = 'sunscreen'),
    38,
    '100% Mineral Sunscreen High-performance, lightweight non-greasy, broad spectrum protection for the long haul.',
    '#2F6F5E',
    'https://freaksofnature.com/products/peak-performance-sunscreen',
    'direct',
    'https://freaksofnature.com/cdn/shop/files/SPF50-web-optimized-transparent.png?v=1743441572&width=1920',
    4.8,
    76,
    '50 ml / 1.7 fl oz',
    '**Step 1:**Complete the skincare routine. We recommend priming the skin with a pump of our Deeper Dive Moisturizer. **Step 2:**Apply Peak Performance SPF50 Sunscreen in the morning before you go outside, or 15 minutes before going in the sun, and as the final step in the daily skincare routine. Apply one pump amount or more of our Peak Performance SPF50 Sunscreen into hands and gently rub onto face, neck, chest and body if applicable. Reapply after 80 min of swimming or sweating, immediately after towel drying and at least every 2 hours when exposed to the sun.',
    'All Skin Types',
    'Nothing! Unlike the painfully nostalgic odor (i.e. harsh and chemically) of most sunscreens, ours is completely unscented.',
    'Cream like consistency to be applied as last step in routine and rubbed into skin.',
    array['100% mineral protection', 'Water resistant (40 min)', 'Dermatologist tested', 'Broad spectrum UV protection', 'Reef safe', 'Fragrance free', 'Minimal white cast', 'Protects + strengthens skin barrier']::text[],
    true
  ),
  (
    'f0000000-0000-0000-0000-000000000006',
    'deeper-dive-moisturizer',
    (select id from public.brands where slug = 'freaks-of-nature'),
    'Deeper Dive Hydrator',
    'skincare',
    (select id from public.categories where slug = 'skincare'),
    48,
    'Ultralight Moisturizer A deeper moisture that strengthens the skin barrier.',
    '#2F6F5E',
    'https://freaksofnature.com/products/deeper-dive-moisturizer',
    'direct',
    'https://freaksofnature.com/cdn/shop/files/HYDRATOR-web-optimized_transparent.png?v=1743441773&width=1920',
    5,
    62,
    '50 ml / 1.7 fl oz',
    '**Step 1:**After AM/PM cleansing, or when you wash yourself after a workout session, apply one pump amount into hands and gently rub onto face, neck and chest if applicable. For optimal results use in the AM and PM. **Step 2:**If heading outside apply Daily Defender SPF30 Sunscreen as the final step in the daily routine.',
    'All Skin Types',
    'Minerally with a slight nuttiness. Think of it like a crisp day near the lake!',
    'Natural oil color and texture for maximum hydration without the greasy look.',
    array['Hydrates + soothes', 'Protects + strengthens skin barrier', 'Dermatologist tested']::text[],
    true
  ),
  (
    'f0000000-0000-0000-0000-000000000007',
    'daily-defender-sunscreen',
    (select id from public.brands where slug = 'freaks-of-nature'),
    'Daily Defender SPF30',
    'sunscreen',
    (select id from public.categories where slug = 'sunscreen'),
    35,
    '100% Mineral Sunscreen Lightweight, fast-absorbing, broad spectrum everyday protection.',
    '#2F6F5E',
    'https://freaksofnature.com/products/daily-defender-sunscreen',
    'direct',
    'https://freaksofnature.com/cdn/shop/files/SPF30-web-optimized-transparent.png?v=1743441677&width=1920',
    4.9,
    99,
    '50 ml / 1.7 fl oz',
    '**Step 1:** Complete the skincare routine. We recommend priming the skin with a pump of our [Deeper Dive Moisturizer(Deeper Dive Moisturizer)](https://freaksofnature.com/products/deeper-dive-moisturizer). **Step 2:**Apply Daily Defender SPF30 Sunscreen in the morning before you go outside, or 15 minutes before going in the sun, and as the final step in the daily skincare routine. Apply one pump amount or more of our Daily Defender SPF30 Sunscreen into hands and gently rub onto face, neck, chest and body if applicable. Reapply after 40 min of swimming or sweating, immediately after towel drying and at least every 2 hours when exposed to the sun.',
    'All Skin Types',
    'Nothing! Unlike the painfully nostalgic odor (i.e. harsh and chemically) of most sunscreens, ours is completely unscented.',
    'Lightweight, breathable, and nearly invisible on skin.',
    array['100% mineral protection', 'Minimal white cast', 'Hydrates + soothes', 'Protects + strengthens skin barrier', 'No chemical filters', 'Water resistant (40 min)', 'Dermatologist tested', 'Broad spectrum UV protection', 'Reef safe', 'Fragrance free']::text[],
    true
  ),
  (
    'f0000000-0000-0000-0000-000000000008',
    'barrier-balancing-cleanser',
    (select id from public.brands where slug = 'freaks-of-nature'),
    'Barrier Balancing Face Wash',
    'skincare',
    (select id from public.categories where slug = 'skincare'),
    30,
    'Foaming Gel-to-Oil',
    '#2F6F5E',
    'https://freaksofnature.com/products/barrier-balancing-cleanser',
    'direct',
    'https://freaksofnature.com/cdn/shop/files/3D_CLEANSER_LIGHTBLUE_E-COMM.png?v=1748386004&width=1920',
    4.6,
    25,
    '100 ml / 3.4 fl oz',
    '**Step 1:**After a long day, sweat sesh, or time spent in the sun. Apply 1-2 pumps of barrier balancing cleanser to dry or wet face. Rub into skin to release grime. **Step 2:**Add water to skin as cleanser begins to froth into a milky texture, helping further cleanse and hydrate the skin. **Step 3:**Towel dry skin. For best results, apply Deeper Dive Hydrator post-cleanse',
    'All Skin Types',
    'Light mineral scent',
    'Luxe oil-gel in a light mint blue that transforms into a white frothy milk when activated with water',
    array['Hydrates + soothes', 'Protects + strengthens skin barrier', 'Dermatologist tested', 'Fragrance free']::text[],
    true
  ),
  (
    'f0000000-0000-0000-0000-000000000009',
    'freaks-full-coverage-bundle',
    (select id from public.brands where slug = 'freaks-of-nature'),
    'Freaks Full Coverage Bundle',
    'sunscreen',
    (select id from public.categories where slug = 'sunscreen'),
    84,
    'Jumbo + Original Sun Stick & SPF Spray',
    '#2F6F5E',
    'https://freaksofnature.com/products/freaks-full-coverage-bundle',
    'direct',
    'https://freaksofnature.com/cdn/shop/files/STICK_JUMBO_SPRAY_E-COMM-copy1.png?v=1777478755&width=1920',
    4.9,
    301,
    'Solar Shield SPF 30 Spray: 6 oz / 170 g; Peak Performance Jumbo Sun Stick: 2.60 oz / 75 gr; Peak Performance Sun Stick: 0.70 oz / 20 gr',
    '**Sun Stick SPF 50** 15 minutes before going in the sun liberally apply onto face, neck, chest and body if applicable. Reapply after 80 min of swimming or sweating, immediately after towel drying and at least every 2 hours when exposed to the sun. Product can be reapplied over or under makeup. **Solar Shield SPF 30 Spray** Shake well before use. Hold container 4--6 inches from skin and spray liberally and evenly across the body. Rub into skin. Apply 15 minutes before sun exposure. Reapply after 40 minutes of swimming or sweating, immediately after towel drying, and at least every 2 hours.',
    '',
    '',
    '',
    array['100% mineral protection', 'Air-powered continuous spray', 'Minimal white cast', 'Hydrates + soothes', 'Protects + strengthens skin barrier', 'No chemical filters', 'Water resistant (40 min)', 'Dermatologist tested', 'Broad spectrum UV protection', 'Reef safe', 'Fragrance free']::text[],
    true
  ),
  (
    'f0000000-0000-0000-0000-000000000010',
    'sun-stick-set',
    (select id from public.brands where slug = 'freaks-of-nature'),
    'Sun Stick Set',
    'sunscreen',
    (select id from public.categories where slug = 'sunscreen'),
    61,
    'Jumbo + Original Sun Stick',
    '#2F6F5E',
    'https://freaksofnature.com/products/sun-stick-set',
    'direct',
    'https://freaksofnature.com/cdn/shop/files/STICK_JUMBO_E-COMM-copy.png?v=1777043493&width=1920',
    4.9,
    189,
    'Original: 0.70 oz / 20 gr, Jumbo: 2.60 oz / 75 gr',
    '15 minutes before going in the sun liberally apply onto face, neck, chest and body if applicable. Reapply after 80 min of swimming or sweating, immediately after towel drying and at least every 2 hours when exposed to the sun. Product can be re-applied over or under makeup.',
    'All Skin Types',
    'Nothing! Unlike the painfully nostalgic odor (i.e. harsh and chemically) of most sunscreens, ours is completely unscented.',
    'Goes on silky smooth, clear, and easily with a bare skin feel that will not warp, slip or drip into the eyes.',
    array['100% mineral protection', 'Water resistant (40 min)', 'Dermatologist tested', 'Broad spectrum UV protection', 'Reef safe', 'Fragrance free', 'Minimal white cast', 'Protects + strengthens skin barrier']::text[],
    true
  ),
  (
    'f0000000-0000-0000-0000-000000000011',
    'body-by-freaks-bundle',
    (select id from public.brands where slug = 'freaks-of-nature'),
    'Body By Freaks Bundle',
    'sunscreen',
    (select id from public.categories where slug = 'sunscreen'),
    63,
    'Jumbo SPF50 Sun Stick + SPF 30 Spray',
    '#2F6F5E',
    'https://freaksofnature.com/products/body-by-freaks-bundle',
    'direct',
    'https://freaksofnature.com/cdn/shop/files/BODY_BY_FREAKS.png?v=1777478348&width=1920',
    4.9,
    163,
    '6 oz / 170 g (Spray) + 2.60 oz / 75 gr (Stick)',
    '**Sun Stick SPF 50** 15 minutes before going in the sun liberally apply onto face, neck, chest and body if applicable. Reapply after 80 min of swimming or sweating, immediately after towel drying and at least every 2 hours when exposed to the sun. Product can be reapplied over or under makeup. **Solar Shield SPF 30 Spray** Shake well before use. Hold container 4--6 inches from skin and spray liberally and evenly across the body. Rub into skin. Apply 15 minutes before sun exposure. Reapply after 40 minutes of swimming or sweating, immediately after towel drying, and at least every 2 hours.',
    '',
    'Fragrance-free',
    '',
    array['100% mineral protection', 'Air-powered continuous spray', 'Minimal white cast', 'Hydrates + soothes', 'Protects + strengthens skin barrier', 'No chemical filters', 'Water resistant (40 min)', 'Dermatologist tested', 'Broad spectrum UV protection', 'Reef safe', 'Fragrance free']::text[],
    true
  ),
  (
    'f0000000-0000-0000-0000-000000000012',
    'freak-family-pack-v3',
    (select id from public.brands where slug = 'freaks-of-nature'),
    'Freak Family Pack',
    'skincare',
    (select id from public.categories where slug = 'skincare'),
    193.5,
    'Full Freak Assortment Strengthen. Protect. Repair. Repeat.',
    '#2F6F5E',
    'https://freaksofnature.com/products/freak-family-pack-v3',
    'direct',
    'https://freaksofnature.com/cdn/shop/files/FreakFamily_Transparent.png?v=1761686298&width=2400',
    4.8,
    444,
    'Daily Defender SPF30: 50 ml / 1.7 fl oz; Deeper Dive Hydrator: 50 ml / 1.7 fl oz; Peak Performance SPF50: 50 ml / 1.7 fl oz; Peak Performance Sun Stick SPF50: 0.70 oz / 20 gr; Barrier Balancing Face Wash: 100 ml / 3.4 fl oz; Everyday Endurance Deodorant: 75ml / 2.6 fl oz',
    '**Deep Dive Hydrator** **Step 1:**After AM/PM cleansing, or when you wash yourself after a workout session, apply one pump amount into hands and gently rub onto face, neck and chest if applicable. For optimal results use in the AM and PM. **Step 2:**If heading outside apply Daily Defender SPF30 Sunscreen as the final step in the daily routine. **Daily Defender SPF30** **Step 1:**Complete the skincare routine. We recommend priming the skin with a pump of our Deep Dive Hydrator. **Step 2:**Apply Daily Defender SPF30 Sunscreen in the morning before you go outside, or 15 minutes before going in the sun, and as the final step in the daily skincare routine. Apply one pump amount or more of our Daily Defender SPF30 Sunscreen into hands and gently rub onto face, neck, chest and body if applicable. Reapply after 40 min of swimming or sweating, immediately after towel drying and at least every 2 hours when exposed to the sun. **Peak Performance SPF50** **Step 1:**Complete the skincare routine. We recommend priming the skin with a pump of our Deeper Dive Moisturizer. **Step 2:**Apply Peak Performance SPF50 Sunscreen in the morning before you go outside, or 15 minutes before going in the sun, and as the final step in the daily skincare routine. Apply one pump amount or more of our Peak Performance SPF50 Sunscreen into hands and gently rub onto face, neck, chest and body if applicable. Reapply after 80 min of swimming or sweating, immediately after towel drying and at least every 2 hours when exposed to the sun. **Peak Performance SPF50 Sun Stick** 15 minutes before going in the sun liberally apply onto face, neck, chest and body if applicable.Reapply after 80 min of swimming or sweating, immediately after towel drying and at least every 2 hours when exposed to the sun. Product can be re-applied over or under makeup. **Barrier Balancing Face Wash** **Step 1:**After a long day, sweat sesh, or time spent in the sun. Apply 1-2 pumps of barrier balancing face wash to dry or wet face. Rub into skin to release grime. **Step 2:**Add water to skin as face wash begins to froth into a milky texture, helping further cleanse and hydrate the skin. **Step 3:**Towel dry skin. For best results, apply Deeper Dive Hydrator post-cleanse **Everyday Endurance Deodorant** **Step 1:**Remove top and twist the bottom until formula begins to appear from perforated cap (Do not overtwist! A little goes a long way) **Step 2:**Apply formula directly on clean, dry underarms -- damp skin reduces effectiveness. **Step 3:**Store in a cool, dry place',
    'All Skin Types',
    '**Deeper Dive Hydrator:** Minerally with a slight nuttiness. Think of it like a crisp day near the lake! **Sun Stick & SPF30 & 50:** Nothing! Unlike the painfully nostalgic odor (i.e. harsh and chemically) of most sunscreens, ours is completely unscented. **Everyday Endurance Deodorant Scents:** **Santal Dune:** Warm amber and smooth santal finished with earthy spice. **Bergamot Canyon:** Bright citrus and neroli with a crisp oakmoss and bergamot finish',
    '**Deeper Dive Hydrator:** Natural oil color and texture for maximum hydration without the greasy look. **Daily Defender SPF30:** Silky smooth and white. But do not let the color fool you, this will not leave you looking like a ghost. **Peak Performance SPF50:** Cream like consistency to be applied as last step in routine and rubbed into skin. **Peak Performance Sun Stick:** Freakishly easy to apply. Goes on silky smooth with minimal whitecast. **Barrier Balancing Face Wash:** Luxe oil-gel in a light mint blue that transforms into a white frothy milk when activated with water. **Everyday Endurance Deodorant:** A creamy texture that dries within 30 seconds. Not sticky or wet and lasts for 48 hours.',
    array['100% mineral protection', 'Protects + strengthens skin barrier', 'Dermatologist tested', 'Broad spectrum UV protection', 'Reef safe', 'Fragrance free']::text[],
    true
  ),
  (
    'f0000000-0000-0000-0000-000000000013',
    'freak-trio',
    (select id from public.brands where slug = 'freaks-of-nature'),
    'Freak Trio',
    'sunscreen',
    (select id from public.categories where slug = 'sunscreen'),
    108.9,
    'SPF50 Sunscreen & SPF30 Sunscreen & Hydrator Strengthen. Protect. Repair. Repeat.',
    '#2F6F5E',
    'https://freaksofnature.com/products/freak-trio',
    'direct',
    'https://freaksofnature.com/cdn/shop/files/SPF50-_-SPF30-_-HYDRATOR-web-optimized-transparent_2.png?v=1743566002&width=1920',
    4.9,
    247,
    '50 ml / 1.7 fl oz per product',
    '**Daily Defender SPF30** **Step 1:**Complete the skincare routine. We recommend priming the skin with a pump of our Deep Dive Hydrator. **Step 2:**Apply Daily Defender SPF30 Sunscreen in the morning before you go outside, or 15 minutes before going in the sun, and as the final step in the daily skincare routine. Apply one pump amount or more of our Daily Defender SPF30 Sunscreen into hands and gently rub onto face, neck, chest and body if applicable. Reapply after 40 min of swimming or sweating, immediately after towel drying and at least every 2 hours when exposed to the sun. **Peak Performance SPF50** **Step 1:**Complete the skincare routine. We recommend priming the skin with a pump of our Deeper Dive Moisturizer. **Step 2:**Apply Peak Performance SPF50 Sunscreen in the morning before you go outside, or 15 minutes before going in the sun, and as the final step in the daily skincare routine. Apply one pump amount or more of our Peak Performance SPF50 Sunscreen into hands and gently rub onto face, neck, chest and body if applicable. Reapply after 80 min of swimming or sweating, immediately after towel drying and at least every 2 hours when exposed to the sun. **Deep Dive Hydrator** **Step 1:**After AM/PM cleansing, or when you wash yourself after a workout session, apply one pump amount into hands and gently rub onto face, neck and chest if applicable. For optimal results use in the AM and PM. **Step 2:**If heading outside apply Daily Defender SPF30 Sunscreen as the final step in the daily routine.',
    '',
    '',
    '',
    array['100% mineral protection', 'No chemical filters', 'Broad spectrum UV protection', 'Minimal white cast', 'Dermatologist tested']::text[],
    true
  ),
  (
    'f0000000-0000-0000-0000-000000000014',
    'peak-performance-duo',
    (select id from public.brands where slug = 'freaks-of-nature'),
    'Peak Performance Duo',
    'sunscreen',
    (select id from public.categories where slug = 'sunscreen'),
    55.8,
    'SPF50 Sunscreen & SPF50 Stick High-performance, lightweight non-greasy, broad spectrum protection for the long haul.',
    '#2F6F5E',
    'https://freaksofnature.com/products/peak-performance-duo',
    'direct',
    'https://freaksofnature.com/cdn/shop/files/SPF50-_-STICK-web-optimized-transparent_V2.png?v=1743565960&width=1920',
    4.8,
    241,
    'Stick: 0.70 oz / 20 gr || SPF: 50 ml / 1.7 fl oz',
    '**Peak Performance SPF50** **Step 1:**Complete the skincare routine. We recommend priming the skin with a pump of our Deeper Dive Moisturizer. **Step 2:**Apply Peak Performance SPF50 Sunscreen in the morning before you go outside, or 15 minutes before going in the sun, and as the final step in the daily skincare routine. Apply one pump amount or more of our Peak Performance SPF50 Sunscreen into hands and gently rub onto face, neck, chest and body if applicable. Reapply after 80 min of swimming or sweating, immediately after towel drying and at least every 2 hours when exposed to the sun. **Peak Performance SPF50 Sun Stick** Easy to bring with you on the go to be applied liberally onto face, neck, chest and body if applicable. Reapply after 80 min of swimming or sweating, immediately after towel drying and at least every 2 hours when exposed to the sun. Product can be re-applied over or under makeup.',
    'All Skin Types',
    'Nothing! Unlike the painfully nostalgic odor (i.e. harsh and chemically) of most sunscreens, ours is completely unscented.',
    'Peak Performance SPF50: Cream like consistency to be applied as last step in routine and rubbed into skin. Peak Performance Stick: Goes on silky smooth, clear, and easily with a bare skin feel that will not warp, slip or drip into the eyes.',
    array['Water resistant (40 min)', 'Protects + strengthens skin barrier', 'Broad spectrum UV protection', '100% mineral protection', 'Fragrance free', 'Reef safe', 'Dermatologist tested', 'Minimal white cast']::text[],
    true
  ),
  (
    'f0000000-0000-0000-0000-000000000015',
    'balanced-skin-set',
    (select id from public.brands where slug = 'freaks-of-nature'),
    'Balanced Skin Set',
    'skincare',
    (select id from public.categories where slug = 'skincare'),
    70,
    'Deeper Dive & Barrier Balancing Face Wash',
    '#2F6F5E',
    'https://freaksofnature.com/products/balanced-skin-set',
    'direct',
    'https://freaksofnature.com/cdn/shop/files/3D_HYDRATOR_CLEANSER-LIGHTBLUE_E-COMM.png?v=1748543058&width=1920',
    4.9,
    101,
    '100 ml / 3.4 fl oz (Face Wash), 50 ml / 1.7 fl oz (Hydrator)',
    '**Barrier Balancing Cleanser** **Step 1:**After a long day, sweat sesh, or time spent in the sun. Apply 1-2 pumps of barrier balancing face wash to dry or wet face. Rub into skin to release grime. **Step 2:**Add water to skin as face wash begins to froth into a milky texture, helping further cleanse and hydrate the skin. **Step 3:**Towel dry skin. For best results, apply Deeper Dive Hydrator post-cleanse. **Deep Dive Hydrator** **Step 1:**After AM/PM cleansing, or when you wash yourself after a workout session, apply one pump amount into hands and gently rub onto face, neck and chest if applicable. For optimal results use in the AM and PM. **Step 2:**If heading outside apply Daily Defender SPF30 Sunscreen as the final step in the daily routine.',
    'All skin types',
    'Fragrance free',
    'Firm, smooth, and clear',
    array['Fragrance free', 'Dermatologist tested', 'Protects + strengthens skin barrier']::text[],
    true
  ),
  (
    'f0000000-0000-0000-0000-000000000016',
    'daily-system',
    (select id from public.brands where slug = 'freaks-of-nature'),
    'Daily System',
    'sunscreen',
    (select id from public.categories where slug = 'sunscreen'),
    74.7,
    'SPF30 Sunscreen & Hydrator Strengthen. Protect. Repair. Repeat.',
    '#2F6F5E',
    'https://freaksofnature.com/products/daily-system',
    'direct',
    'https://freaksofnature.com/cdn/shop/files/SPF30-_-HYDRATOR-web-optimized-transparent_V2.png?v=1743566064&width=1920',
    4.9,
    191,
    '50 ml / 1.7 fl oz per product',
    '**Daily Defender SPF30** **Step 1:**Complete the skincare routine. We recommend priming the skin with a pump of our Deep Dive Hydrator. **Step 2:**Apply Daily Defender SPF30 Sunscreen in the morning before you go outside, or 15 minutes before going in the sun, and as the final step in the daily skincare routine. Apply one pump amount or more of our Daily Defender SPF30 Sunscreen into hands and gently rub onto face, neck, chest and body if applicable. Reapply after 40 min of swimming or sweating, immediately after towel drying and at least every 2 hours when exposed to the sun. **Deep Dive Hydrator** **Step 1:**After AM/PM cleansing, or when you wash yourself after a workout session, apply one pump amount into hands and gently rub onto face, neck and chest if applicable. For optimal results use in the AM and PM. **Step 2:**If heading outside apply Daily Defender SPF30 Sunscreen as the final step in the daily routine.',
    'All skin types',
    '',
    '',
    array['40 min water resistant', '100% mineral protection', 'No chemical filters', 'Minimal white cast', 'Broad spectrum UV protection', 'Dermatologist tested', 'Reef safe']::text[],
    true
  ),
  (
    'f0000000-0000-0000-0000-000000000017',
    'endurance-system',
    (select id from public.brands where slug = 'freaks-of-nature'),
    'Endurance System',
    'sunscreen',
    (select id from public.categories where slug = 'sunscreen'),
    77.4,
    'SPF50 Sunscreen & Hydrator Strengthen. Protect. Repair. Repeat.',
    '#2F6F5E',
    'https://freaksofnature.com/products/endurance-system',
    'direct',
    'https://freaksofnature.com/cdn/shop/files/SPF50-_-HYDRATOR-web-optimized-transparent_V2.png?v=1743566045&width=1920',
    4.9,
    150,
    '50 ml / 1.7 fl oz per product',
    '**Peak Performance SPF50** **Step 1:**Complete the skincare routine. We recommend priming the skin with a pump of our Deeper Dive Moisturizer. **Step 2:**Apply Peak Performance SPF50 Sunscreen in the morning before you go outside, or 15 minutes before going in the sun, and as the final step in the daily skincare routine. Apply one pump amount or more of our Peak Performance SPF50 Sunscreen into hands and gently rub onto face, neck, chest and body if applicable. Reapply after 80 min of swimming or sweating, immediately after towel drying and at least every 2 hours when exposed to the sun. **Deep Dive Hydrator** **Step 1:**After AM/PM cleansing, or when you wash yourself after a workout session, apply one pump amount into hands and gently rub onto face, neck and chest if applicable. For optimal results use in the AM and PM. **Step 2:**If heading outside apply Daily Defender SPF30 Sunscreen as the final step in the daily routine.',
    'all skin types',
    '',
    '',
    array['100% mineral protection', 'Water resistant (40 min)', 'No chemical filters', 'Broad spectrum UV protection', 'Minimal white cast', 'Dermatologist tested', 'Reef safe']::text[],
    true
  ),
  (
    'f0000000-0000-0000-0000-000000000018',
    'endurance-system-sport-mode',
    (select id from public.brands where slug = 'freaks-of-nature'),
    'Endurance System -- Sport Mode',
    'sunscreen',
    (select id from public.categories where slug = 'sunscreen'),
    64.2,
    'SPF50 Stick & Hydrator Strengthen. Protect. Repair. Repeat.',
    '#2F6F5E',
    'https://freaksofnature.com/products/endurance-system-sport-mode',
    'direct',
    'https://freaksofnature.com/cdn/shop/files/HYDRATOR-_-STICK-web-optimized-transparent_V2.png?v=1743565980&width=1920',
    4.9,
    205,
    'Stick: 0.70 oz / 20 gr || Moisturizer: 50 ml / 1.7 fl oz',
    '**Deeper Dive Moisturizer:** **Step 1:**After AM/PM cleansing, or when you wash yourself after a workout session, apply one pump amount into hands and gently rub onto face, neck and chest if applicable. For optimal results use in the AM and PM. **Step 2:**If heading outside apply Peak Performance SPF50 Sun Stick as the final step in the daily routine. Reapply after 80 min of swimming or sweating, immediately after towel drying and at least every 2 hours when exposed to the sun. Product can be re-applied over or under makeup.',
    'All Skin Types',
    'Deeper Dive Hydrator: Minerally with a slight nuttiness. Think of it like a crisp day near the lake! Peak Performance Sun Stick: Nothing! Unlike the painfully nostalgic odor (i.e. harsh and chemically) of most sunscreens, ours is completely unscented.',
    'Deeper Dive Hydrator: Natural oil color and texture for maximum hydration without the greasy look. Peak Performance Sun Stick: Goes on silky smooth, clear, and easily with a bare skin feel that will not warp, slip or drip into the eyes.',
    array['Water resistant (40 min)', '100% mineral protection', 'No chemical filters', 'Protects + strengthens skin barrier', 'Minimal white cast', 'Broad spectrum UV protection', 'Dermatologist tested', 'Reef safe']::text[],
    true
  ),
  (
    'f0000000-0000-0000-0000-000000000019',
    'deo-duo-bundle',
    (select id from public.brands where slug = 'freaks-of-nature'),
    'Everyday Endurance Duo',
    'deodorant',
    (select id from public.categories where slug = 'deodorant'),
    36,
    'Two all natural scents with 48-hour odor protection',
    '#2F6F5E',
    'https://freaksofnature.com/products/deo-duo-bundle',
    'direct',
    'https://freaksofnature.com/cdn/shop/files/Duo.png?v=1761526305&width=1920',
    4.2,
    55,
    '75ml / 2.6 fl oz (per stick)',
    '**Step 1:**Remove cap **Step 2:**Twist bottom of bottle until formula begins to appear from perforated cap (Do not overtwist! A little goes a long way) **Step 3:**Apply formula directly on underarm For best results, keep deodorant at room temperature (68°F to 77°F / 20°C to 25°C)',
    'All skin types',
    '**Santal Dune:** Warm amber and smooth santal finished with earthy spice. **Bergamot Canyon:** Bright citrus and neroli with a crisp oakmoss and bergamot finish',
    'A creamy texture that dries within 30 seconds. Not sticky or wet and lasts for 48 hours. In our perception study 93% of users found that the deo did not leave stains or marks on clothing.',
    array['Dermatologist tested', 'Protects + strengthens skin barrier', 'Fragrance free']::text[],
    true
  ),
  (
    'f0000000-0000-0000-0000-000000000020',
    'skin-support-electrolyte',
    (select id from public.brands where slug = 'freaks-of-nature'),
    'Skin Support Electrolyte',
    'skincare',
    (select id from public.categories where slug = 'skincare'),
    55,
    'Whole-body hydration and protection from the inside out',
    '#2F6F5E',
    'https://freaksofnature.com/products/skin-support-electrolyte',
    'direct',
    'https://freaksofnature.com/cdn/shop/files/Update_ProductCard.png?v=1773719331&width=1920',
    4.9,
    42,
    '1 sachet / 13.1 g',
    'Mix one sachet into 16--20 oz of cold water, shake or stir until dissolved, and drink daily. Best enjoyed whenever you want--before, during, or after training. The North Shore flavor makes it easy to stay consistent. Just mix and sip.',
    'All skin types.',
    'Tangy passionfruit, guava, and a hint of zesty lime.',
    '',
    array['Hydrates + soothes', 'Protects + strengthens skin barrier']::text[],
    true
  ),
  (
    'f0000000-0000-0000-0000-000000000021',
    'everyday-endurance-trio',
    (select id from public.brands where slug = 'freaks-of-nature'),
    'Everyday Endurance Trio',
    'deodorant',
    (select id from public.categories where slug = 'deodorant'),
    51,
    'Three all natural scents with 48-hour odor protection',
    '#2F6F5E',
    'https://freaksofnature.com/products/everyday-endurance-trio',
    'direct',
    'https://freaksofnature.com/cdn/shop/files/Trio.png?v=1775849441&width=1920',
    4.2,
    55,
    '75ml / 2.6 fl oz (per stick)',
    '**Step 1:**Remove cap **Step 2:**Twist bottom of bottle until formula begins to appear from perforated cap (Do not overtwist! A little goes a long way) **Step 3:**Apply formula directly on underarm For best results, keep deodorant at room temperature (68°F to 77°F / 20°C to 25°C)',
    'All skin types',
    '**Santal Dune:** Warm amber and smooth santal finished with earthy spice.**Bergamot Canyon:** Bright citrus and neroli with a crisp oakmoss and bergamot finish**Cedar Peak:** Cool and sharp. A crisp hit of eucalyptus and mint, layered with herbal lavandin and a sharp touch of geranium to wake up the senses.',
    'A creamy texture that dries within 30 seconds. Not sticky or wet and lasts for 48 hours. In our perception study 93% of users found that the deo did not leave stains or marks on clothing.',
    array['Dermatologist tested', 'Protects + strengthens skin barrier', 'Fragrance free']::text[],
    true
  )
on conflict (slug) do update set
  brand_id = excluded.brand_id,
  name = excluded.name,
  category = excluded.category,
  category_id = excluded.category_id,
  price = excluded.price,
  description = excluded.description,
  affiliate_url = excluded.affiliate_url,
  image_url = excluded.image_url,
  rating = excluded.rating,
  review_count = excluded.review_count,
  size = excluded.size,
  how_to_use = excluded.how_to_use,
  good_for = excluded.good_for,
  smells_like = excluded.smells_like,
  finish = excluded.finish,
  features = excluded.features,
  is_published = excluded.is_published;

insert into public.ingredients (slug, name) values
  ('aloe-barbendensis-leaf-juice', 'Aloe Barbendensis Leaf Juice'),
  ('and-sodium-hyaluronate', 'and Sodium Hyaluronate'),
  ('aqua-water', 'Aqua / Water'),
  ('aspergillus-ferment', 'Aspergillus Ferment'),
  ('astaxanthin', 'Astaxanthin'),
  ('avena-sativa-oat-kernel-oil', 'Avena Sativa (Oat) Kernel Oil'),
  ('bacillus-ferment', 'Bacillus Ferment'),
  ('bambusa-arundinacea-bamboo-stem-extract', 'Bambusa Arundinacea (Bamboo) Stem Extract'),
  ('bentonite', 'Bentonite'),
  ('betaine', 'Betaine'),
  ('c13-15-alkane', 'C13-15 Alkane'),
  ('calcium', 'Calcium'),
  ('camellia-oleifera-seed-oil', 'Camellia Oleifera Seed Oil'),
  ('camellia-sinensis-japanese-green-tea-leaf-extract', 'Camellia Sinensis (Japanese Green Tea) Leaf Extract'),
  ('caprylhydroxamic-acid', 'Caprylhydroxamic Acid'),
  ('caprylic-capric-triglyceride', 'Caprylic / Capric Triglyceride'),
  ('capryliccapric-triglyceride', 'Caprylic/Capric Triglyceride'),
  ('capryloyl-glycerinsebacic-acid-copolymer', 'Capryloyl Glycerin/Sebacic Acid Copolymer'),
  ('cetearyl-olivate', 'Cetearyl Olivate'),
  ('cetyl-alcohol', 'Cetyl Alcohol'),
  ('chloride', 'Chloride'),
  ('chromium-hydroxide-green-ci-77289', 'Chromium Hydroxide Green (CI 77289)'),
  ('citric-acid', 'Citric Acid'),
  ('citronellyl-methylcrotonate', 'Citronellyl Methylcrotonate'),
  ('coco-caprylatecaprate', 'Coco-Caprylate/Caprate'),
  ('copernicia-cerifera-carnauba-wax', 'Copernicia Cerifera (Carnauba) Wax'),
  ('dextrin-palmitate', 'Dextrin Palmitate'),
  ('dilauryl-citrate', 'Dilauryl Citrate'),
  ('dl-alpha-tocopherol', 'DL-Alpha Tocopherol'),
  ('ethylhexyl-olivate', 'Ethylhexyl Olivate'),
  ('ethylhexyl-palmitate', 'Ethylhexyl Palmitate'),
  ('ethylhexylglycerin', 'Ethylhexylglycerin'),
  ('fragrance', 'Fragrance'),
  ('fragrance-parfum', 'Fragrance (Parfum)'),
  ('ginger-zingiber-officinale-root-extract', 'Ginger (Zingiber officinale) Root Extract'),
  ('gluconolactone', 'Gluconolactone'),
  ('glycerin', 'Glycerin'),
  ('glyceryl-laurate', 'Glyceryl Laurate'),
  ('helianthus-annuus-sunflower-seed-oil', 'Helianthus Annuus (Sunflower) Seed Oil'),
  ('helianthus-annuus-sunflower-seed-wax', 'Helianthus Annuus (Sunflower) Seed Wax'),
  ('hydrogenated-methyl-abietate', 'Hydrogenated Methyl Abietate'),
  ('isoamyl-laurate', 'Isoamyl Laurate'),
  ('isopropyl-palmitate', 'Isopropyl Palmitate'),
  ('isostearic-acid', 'Isostearic Acid'),
  ('laurel-lysine', 'Laurel Lysine'),
  ('lauryl-glucoside', 'Lauryl Glucoside'),
  ('lecithin', 'Lecithin'),
  ('leuconostoc-radish-root-ferment-filtrate', 'Leuconostoc / Radish Root Ferment Filtrate'),
  ('lonicera-caprifolium-honeysuckle-flower-extract', 'Lonicera Caprifolium (Honeysuckle) Flower Extract'),
  ('lonicera-japonica-honeysuckle-flower-extract', 'Lonicera Japonica (Honeysuckle) Flower Extract'),
  ('magnesium', 'Magnesium'),
  ('maleated-soybean-oil-glyceryloctyldodecanol-esters', 'Maleated Soybean Oil Glyceryl/Octyldodecanol Esters'),
  ('malic-acid', 'Malic Acid'),
  ('maranta-arundinacea-arrowroot-root-extract', 'Maranta Arundinacea (Arrowroot) Root Extract'),
  ('methylcellulose', 'Methylcellulose'),
  ('methylheptylglycerin', 'Methylheptylglycerin'),
  ('myrica-pubescens-laurel-fruit-wax', 'Myrica Pubescens (Laurel) Fruit Wax'),
  ('natural-flavors', 'Natural Flavors'),
  ('octinoxate', 'Octinoxate'),
  ('octyldodecyl-citrate-crosspolymer', 'Octyldodecyl Citrate Crosspolymer'),
  ('oryza-sativa-rice-bran-oil', 'Oryza Sativa (Rice Bran) Oil'),
  ('oryza-sativa-rice-bran-oil-2', 'Oryza Sativa (Rice) Bran Oil'),
  ('oryza-sativa-rice-bran-wax', 'Oryza Sativa (Rice) Bran Wax'),
  ('oxybenzone', 'Oxybenzone'),
  ('padina-pavonica-thallus-extract', 'Padina Pavonica Thallus Extract'),
  ('partially-hydrolyzed-guar-gum', 'Partially Hydrolyzed Guar Gum'),
  ('phenoxyethanol', 'Phenoxyethanol'),
  ('physalis-angulata-ground-cherry-extract', 'Physalis Angulata (Ground Cherry) Extract'),
  ('plukenetia-volubilis-sacha-inchi-seed-oil', 'Plukenetia Volubilis (Sacha Inchi) Seed Oil'),
  ('polyglyceryl-3-polyricinoleate', 'Polyglyceryl-3 Polyricinoleate'),
  ('polyglyceryl-4-diisostearatepolyhydroxystearatesebacate', 'Polyglyceryl-4 Diisostearate/Polyhydroxystearate/Sebacate'),
  ('polyglyceryl-4-laurate', 'Polyglyceryl-4 Laurate'),
  ('polyhydroxystearic-acid', 'Polyhydroxystearic Acid'),
  ('polypodium-leucotomos-leaf-extract', 'Polypodium leucotomos Leaf Extract'),
  ('polyricinoleic-acid', 'Polyricinoleic acid'),
  ('pongamia-pinnata-seed-extract', 'Pongamia Pinnata Seed Extract'),
  ('populus-tremuloides-bark-extract', 'Populus Tremuloides Bark Extract'),
  ('porphyra-umbilicalis-extract-aqua', 'Porphyra Umbilicalis Extract Aqua'),
  ('potassium', 'Potassium'),
  ('propanediol', 'Propanediol'),
  ('prototheca-moriformis-microalgae-oil', 'Prototheca Moriformis (Microalgae) Oil'),
  ('quaternium-90-bentonite', 'Quaternium-90 Bentonite'),
  ('rebaudioside-a-stevia-leaf-extract', 'Rebaudioside A (Stevia Leaf Extract)'),
  ('red-orange-citrus-sinensis-fruit-extract', 'Red Orange (Citrus sinensis) Fruit Extract'),
  ('rhododendron-ferrugineum-alpenrose-extract', 'Rhododendron Ferrugineum (Alpenrose) Extract'),
  ('saccharomyces-ferment', 'Saccharomyces Ferment'),
  ('silica', 'Silica'),
  ('simmondsia-chinensis-jojoba-seed-oil', 'Simmondsia Chinensis (Jojoba) Seed Oil'),
  ('sodium', 'Sodium'),
  ('sodium-citrate', 'Sodium Citrate'),
  ('sodium-cocoyl-apple-amino-acids', 'Sodium Cocoyl Apple Amino Acids'),
  ('sodium-lauryl-glucose-carboxylate', 'Sodium Lauryl Glucose Carboxylate'),
  ('sodium-phytate', 'Sodium Phytate'),
  ('sodium-stearoyl-glutamate', 'Sodium Stearoyl Glutamate'),
  ('sorbitan-laurate', 'Sorbitan Laurate'),
  ('sorbitan-olivate', 'Sorbitan Olivate'),
  ('spirulina-platensis-extract', 'Spirulina Platensis Extract'),
  ('squalane', 'Squalane'),
  ('sr-wasp-spider-polypeptide-1-oligopeptide-178', 'Sr-wasp spider polypeptide-1 oligopeptide-178'),
  ('stearic-acid', 'Stearic Acid'),
  ('stearyloctyldodecyl-citrate-crosspolymer', 'Stearyl/Octyldodecyl Citrate Crosspolymer'),
  ('sucrose-stearate', 'Sucrose Stearate'),
  ('theobroma-cacao-cocoa-seed-butter', 'Theobroma Cacao (Cocoa) Seed Butter'),
  ('titanium-dioxide', 'Titanium Dioxide'),
  ('tocopherol', 'Tocopherol'),
  ('tocopherol-acetate', 'Tocopherol Acetate'),
  ('tocopheryl-acetate', 'Tocopheryl Acetate'),
  ('trehalose', 'Trehalose'),
  ('triethyl-citrate', 'Triethyl Citrate'),
  ('undaria-pinnatifida-wakame-extract', 'Undaria Pinnatifida (Wakame) Extract'),
  ('vitamin-a', 'Vitamin A'),
  ('vitamin-b3', 'Vitamin B3'),
  ('vitamin-c', 'Vitamin C'),
  ('vitamin-d', 'Vitamin D'),
  ('vitamin-e', 'Vitamin E'),
  ('vitis-vinifera-grape-seed-oil', 'Vitis Vinifera (Grape) Seed Oil'),
  ('water', 'Water'),
  ('xanthan-gum', 'Xanthan Gum'),
  ('zinc', 'Zinc'),
  ('zinc-oxide', 'Zinc Oxide'),
  ('zinc-ricinoleate', 'Zinc Ricinoleate')
on conflict (name) do update set slug = excluded.slug;

with links(product_slug, ingredient_name, kind) as (
  values
  ('solar-shield-spray', 'Zinc Oxide', 'contains'),
  ('solar-shield-spray', 'Aloe Barbendensis Leaf Juice', 'contains'),
  ('solar-shield-spray', 'Aqua / Water', 'contains'),
  ('solar-shield-spray', 'Bambusa Arundinacea (Bamboo) Stem Extract', 'contains'),
  ('solar-shield-spray', 'Camellia Sinensis (Japanese Green Tea) Leaf Extract', 'contains'),
  ('solar-shield-spray', 'Caprylic / Capric Triglyceride', 'contains'),
  ('solar-shield-spray', 'Dilauryl Citrate', 'contains'),
  ('solar-shield-spray', 'Ethylhexylglycerin', 'contains'),
  ('solar-shield-spray', 'Gluconolactone', 'contains'),
  ('solar-shield-spray', 'Glycerin', 'contains'),
  ('solar-shield-spray', 'Hydrogenated Methyl Abietate', 'contains'),
  ('solar-shield-spray', 'Isopropyl Palmitate', 'contains'),
  ('solar-shield-spray', 'Lauryl Glucoside', 'contains'),
  ('solar-shield-spray', 'Leuconostoc / Radish Root Ferment Filtrate', 'contains'),
  ('solar-shield-spray', 'Lonicera Caprifolium (Honeysuckle) Flower Extract', 'contains'),
  ('solar-shield-spray', 'Lonicera Japonica (Honeysuckle) Flower Extract', 'contains'),
  ('solar-shield-spray', 'Methylcellulose', 'contains'),
  ('solar-shield-spray', 'Octyldodecyl Citrate Crosspolymer', 'contains'),
  ('solar-shield-spray', 'Phenoxyethanol', 'contains'),
  ('solar-shield-spray', 'Polyglyceryl-4 Laurate', 'contains'),
  ('solar-shield-spray', 'Populus Tremuloides Bark Extract', 'contains'),
  ('solar-shield-spray', 'Simmondsia Chinensis (Jojoba) Seed Oil', 'contains'),
  ('solar-shield-spray', 'Sodium Lauryl Glucose Carboxylate', 'contains'),
  ('solar-shield-spray', 'Sodium Phytate', 'contains'),
  ('solar-shield-spray', 'Sodium Stearoyl Glutamate', 'contains'),
  ('solar-shield-spray', 'Sorbitan Laurate', 'contains'),
  ('solar-shield-spray', 'Tocopherol', 'contains'),
  ('solar-shield-spray', 'Xanthan Gum', 'contains'),
  ('solar-shield-spray', 'Fragrance', 'free_from'),
  ('solar-shield-spray', 'Oxybenzone', 'free_from'),
  ('solar-shield-spray', 'Octinoxate', 'free_from'),
  ('sun-stick-spf50', 'Zinc Oxide', 'contains'),
  ('sun-stick-spf50', 'Helianthus Annuus (Sunflower) Seed Wax', 'contains'),
  ('sun-stick-spf50', 'Isoamyl Laurate', 'contains'),
  ('sun-stick-spf50', 'Ethylhexyl Olivate', 'contains'),
  ('sun-stick-spf50', 'Caprylic/Capric Triglyceride', 'contains'),
  ('sun-stick-spf50', 'C13-15 Alkane', 'contains'),
  ('sun-stick-spf50', 'Polyhydroxystearic Acid', 'contains'),
  ('sun-stick-spf50', 'Oryza Sativa (Rice Bran) Oil', 'contains'),
  ('sun-stick-spf50', 'Quaternium-90 Bentonite', 'contains'),
  ('sun-stick-spf50', 'Capryloyl Glycerin/Sebacic Acid Copolymer', 'contains'),
  ('sun-stick-spf50', 'Prototheca Moriformis (Microalgae) Oil', 'contains'),
  ('sun-stick-spf50', 'Theobroma Cacao (Cocoa) Seed Butter', 'contains'),
  ('sun-stick-spf50', 'Isostearic Acid', 'contains'),
  ('sun-stick-spf50', 'Lecithin', 'contains'),
  ('sun-stick-spf50', 'Polyglyceryl-3 Polyricinoleate', 'contains'),
  ('sun-stick-spf50', 'Triethyl Citrate', 'contains'),
  ('sun-stick-spf50', 'Squalane', 'contains'),
  ('sun-stick-spf50', 'Physalis Angulata (Ground Cherry) Extract', 'contains'),
  ('sun-stick-spf50', 'Rhododendron Ferrugineum (Alpenrose) Extract', 'contains'),
  ('sun-stick-spf50', 'Undaria Pinnatifida (Wakame) Extract', 'contains'),
  ('sun-stick-spf50', 'Saccharomyces Ferment', 'contains'),
  ('sun-stick-spf50', 'Laurel Lysine', 'contains'),
  ('sun-stick-spf50', 'Tocopherol Acetate', 'contains'),
  ('sun-stick-spf50', 'Tocopherol', 'contains'),
  ('sun-stick-spf50', 'Fragrance', 'free_from'),
  ('sun-stick-spf50', 'Oxybenzone', 'free_from'),
  ('sun-stick-spf50', 'Octinoxate', 'free_from'),
  ('everyday-endurance-deodorant', 'Caprylic/Capric Triglyceride', 'contains'),
  ('everyday-endurance-deodorant', 'Maranta Arundinacea (Arrowroot) Root Extract', 'contains'),
  ('everyday-endurance-deodorant', 'Helianthus Annuus (Sunflower) Seed Oil', 'contains'),
  ('everyday-endurance-deodorant', 'Ethylhexyl Palmitate', 'contains'),
  ('everyday-endurance-deodorant', 'Myrica Pubescens (Laurel) Fruit Wax', 'contains'),
  ('everyday-endurance-deodorant', 'Theobroma Cacao (Cocoa) Seed Butter', 'contains'),
  ('everyday-endurance-deodorant', 'Triethyl Citrate', 'contains'),
  ('everyday-endurance-deodorant', 'Bambusa Arundinacea (Bamboo) Stem Extract', 'contains'),
  ('everyday-endurance-deodorant', 'Zinc Ricinoleate', 'contains'),
  ('everyday-endurance-deodorant', 'Bentonite', 'contains'),
  ('everyday-endurance-deodorant', 'Glyceryl Laurate', 'contains'),
  ('everyday-endurance-deodorant', 'Helianthus Annuus (Sunflower) Seed Wax', 'contains'),
  ('everyday-endurance-deodorant', 'Silica', 'contains'),
  ('everyday-endurance-deodorant', 'Oryza Sativa (Rice) Bran Wax', 'contains'),
  ('everyday-endurance-deodorant', 'Citronellyl Methylcrotonate', 'contains'),
  ('everyday-endurance-deodorant', 'Tocopheryl Acetate', 'contains'),
  ('everyday-endurance-deodorant', 'Fragrance (Parfum)', 'contains'),
  ('everyday-endurance-deodorant', 'Chromium Hydroxide Green (CI 77289)', 'contains'),
  ('jumbo-sun-stick', 'Zinc Oxide', 'contains'),
  ('jumbo-sun-stick', 'Helianthus Annuus (Sunflower) Seed Wax', 'contains'),
  ('jumbo-sun-stick', 'Isoamyl Laurate', 'contains'),
  ('jumbo-sun-stick', 'Ethylhexyl Olivate', 'contains'),
  ('jumbo-sun-stick', 'Caprylic/Capric Triglyceride', 'contains'),
  ('jumbo-sun-stick', 'C13-15 Alkane', 'contains'),
  ('jumbo-sun-stick', 'Polyhydroxystearic Acid', 'contains'),
  ('jumbo-sun-stick', 'Oryza Sativa (Rice Bran) Oil', 'contains'),
  ('jumbo-sun-stick', 'Quaternium-90 Bentonite', 'contains'),
  ('jumbo-sun-stick', 'Capryloyl Glycerin/Sebacic Acid Copolymer', 'contains'),
  ('jumbo-sun-stick', 'Prototheca Moriformis (Microalgae) Oil', 'contains'),
  ('jumbo-sun-stick', 'Theobroma Cacao (Cocoa) Seed Butter', 'contains'),
  ('jumbo-sun-stick', 'Isostearic Acid', 'contains'),
  ('jumbo-sun-stick', 'Lecithin', 'contains'),
  ('jumbo-sun-stick', 'Polyglyceryl-3 Polyricinoleate', 'contains'),
  ('jumbo-sun-stick', 'Triethyl Citrate', 'contains'),
  ('jumbo-sun-stick', 'Squalane', 'contains'),
  ('jumbo-sun-stick', 'Physalis Angulata (Ground Cherry) Extract', 'contains'),
  ('jumbo-sun-stick', 'Rhododendron Ferrugineum (Alpenrose) Extract', 'contains'),
  ('jumbo-sun-stick', 'Undaria Pinnatifida (Wakame) Extract', 'contains'),
  ('jumbo-sun-stick', 'Saccharomyces Ferment', 'contains'),
  ('jumbo-sun-stick', 'Laurel Lysine', 'contains'),
  ('jumbo-sun-stick', 'Tocopherol Acetate', 'contains'),
  ('jumbo-sun-stick', 'Tocopherol', 'contains'),
  ('jumbo-sun-stick', 'Fragrance', 'free_from'),
  ('jumbo-sun-stick', 'Oxybenzone', 'free_from'),
  ('jumbo-sun-stick', 'Octinoxate', 'free_from'),
  ('peak-performance-sunscreen', 'Zinc Oxide', 'contains'),
  ('peak-performance-sunscreen', 'Titanium Dioxide', 'contains'),
  ('peak-performance-sunscreen', 'Water', 'contains'),
  ('peak-performance-sunscreen', 'Coco-Caprylate/Caprate', 'contains'),
  ('peak-performance-sunscreen', 'Caprylic/Capric Triglyceride', 'contains'),
  ('peak-performance-sunscreen', 'Maleated Soybean Oil Glyceryl/Octyldodecanol Esters', 'contains'),
  ('peak-performance-sunscreen', 'Polyglyceryl-4 Diisostearate/Polyhydroxystearate/Sebacate', 'contains'),
  ('peak-performance-sunscreen', 'Propanediol', 'contains'),
  ('peak-performance-sunscreen', 'Stearyl/Octyldodecyl Citrate Crosspolymer', 'contains'),
  ('peak-performance-sunscreen', 'Copernicia Cerifera (Carnauba) Wax', 'contains'),
  ('peak-performance-sunscreen', 'Bentonite', 'contains'),
  ('peak-performance-sunscreen', 'Methylheptylglycerin', 'contains'),
  ('peak-performance-sunscreen', 'Squalane', 'contains'),
  ('peak-performance-sunscreen', 'Sr-wasp spider polypeptide-1 oligopeptide-178', 'contains'),
  ('peak-performance-sunscreen', 'Porphyra Umbilicalis Extract Aqua', 'contains'),
  ('peak-performance-sunscreen', 'Cetearyl Olivate', 'contains'),
  ('peak-performance-sunscreen', 'Sorbitan Olivate', 'contains'),
  ('peak-performance-sunscreen', 'Polyhydroxystearic Acid', 'contains'),
  ('peak-performance-sunscreen', 'Polyricinoleic acid', 'contains'),
  ('peak-performance-sunscreen', 'Glycerin', 'contains'),
  ('peak-performance-sunscreen', 'Xanthan Gum', 'contains'),
  ('peak-performance-sunscreen', 'Cetyl Alcohol', 'contains'),
  ('peak-performance-sunscreen', 'Pongamia Pinnata Seed Extract', 'contains'),
  ('peak-performance-sunscreen', 'Caprylhydroxamic Acid', 'contains'),
  ('peak-performance-sunscreen', 'Oryza Sativa (Rice) Bran Wax', 'contains'),
  ('peak-performance-sunscreen', 'DL-Alpha Tocopherol', 'contains'),
  ('peak-performance-sunscreen', 'Stearic Acid', 'contains'),
  ('peak-performance-sunscreen', 'Sodium Phytate', 'contains'),
  ('peak-performance-sunscreen', 'Fragrance', 'free_from'),
  ('peak-performance-sunscreen', 'Oxybenzone', 'free_from'),
  ('peak-performance-sunscreen', 'Octinoxate', 'free_from'),
  ('deeper-dive-moisturizer', 'Squalane', 'contains'),
  ('deeper-dive-moisturizer', 'Avena Sativa (Oat) Kernel Oil', 'contains'),
  ('deeper-dive-moisturizer', 'Dextrin Palmitate', 'contains'),
  ('deeper-dive-moisturizer', 'Plukenetia Volubilis (Sacha Inchi) Seed Oil', 'contains'),
  ('deeper-dive-moisturizer', 'Simmondsia Chinensis (Jojoba) Seed Oil', 'contains'),
  ('deeper-dive-moisturizer', 'Padina Pavonica Thallus Extract', 'contains'),
  ('deeper-dive-moisturizer', 'Bacillus Ferment', 'contains'),
  ('deeper-dive-moisturizer', 'Tocopherol', 'contains'),
  ('daily-defender-sunscreen', 'Zinc Oxide', 'contains'),
  ('daily-defender-sunscreen', 'Water', 'contains'),
  ('daily-defender-sunscreen', 'Coco-Caprylate/Caprate', 'contains'),
  ('daily-defender-sunscreen', 'Caprylic/Capric Triglyceride', 'contains'),
  ('daily-defender-sunscreen', 'Polyglyceryl-4 Diisostearate/Polyhydroxystearate/Sebacate', 'contains'),
  ('daily-defender-sunscreen', 'Propanediol', 'contains'),
  ('daily-defender-sunscreen', 'C13-15 Alkane', 'contains'),
  ('daily-defender-sunscreen', 'Squalane', 'contains'),
  ('daily-defender-sunscreen', 'Maleated Soybean Oil Glyceryl/Octyldodecanol Esters', 'contains'),
  ('daily-defender-sunscreen', 'Copernicia Cerifera (Carnauba) Wax', 'contains'),
  ('daily-defender-sunscreen', 'Methylheptylglycerin', 'contains'),
  ('daily-defender-sunscreen', 'Sr-wasp spider polypeptide-1 oligopeptide-178', 'contains'),
  ('daily-defender-sunscreen', 'Bentonite', 'contains'),
  ('daily-defender-sunscreen', 'Polyricinoleic acid', 'contains'),
  ('daily-defender-sunscreen', 'Polyhydroxystearic Acid', 'contains'),
  ('daily-defender-sunscreen', 'Glycerin', 'contains'),
  ('daily-defender-sunscreen', 'Pongamia Pinnata Seed Extract', 'contains'),
  ('daily-defender-sunscreen', 'Xanthan Gum', 'contains'),
  ('daily-defender-sunscreen', 'Caprylhydroxamic Acid', 'contains'),
  ('daily-defender-sunscreen', 'Oryza Sativa (Rice) Bran Wax', 'contains'),
  ('daily-defender-sunscreen', 'DL-Alpha Tocopherol', 'contains'),
  ('daily-defender-sunscreen', 'Sodium Phytate', 'contains'),
  ('daily-defender-sunscreen', 'Fragrance', 'free_from'),
  ('daily-defender-sunscreen', 'Oxybenzone', 'free_from'),
  ('daily-defender-sunscreen', 'Octinoxate', 'free_from'),
  ('barrier-balancing-cleanser', 'Glycerin', 'contains'),
  ('barrier-balancing-cleanser', 'Sodium Cocoyl Apple Amino Acids', 'contains'),
  ('barrier-balancing-cleanser', 'Sucrose Stearate', 'contains'),
  ('barrier-balancing-cleanser', 'Betaine', 'contains'),
  ('barrier-balancing-cleanser', 'Saccharomyces Ferment', 'contains'),
  ('barrier-balancing-cleanser', 'Aspergillus Ferment', 'contains'),
  ('barrier-balancing-cleanser', 'Vitis Vinifera (Grape) Seed Oil', 'contains'),
  ('barrier-balancing-cleanser', 'Oryza Sativa (Rice) Bran Oil', 'contains'),
  ('barrier-balancing-cleanser', 'Squalane', 'contains'),
  ('barrier-balancing-cleanser', 'Tocopherol', 'contains'),
  ('barrier-balancing-cleanser', 'Avena Sativa (Oat) Kernel Oil', 'contains'),
  ('barrier-balancing-cleanser', 'Camellia Oleifera Seed Oil', 'contains'),
  ('barrier-balancing-cleanser', 'Spirulina Platensis Extract', 'contains'),
  ('barrier-balancing-cleanser', 'Trehalose', 'contains'),
  ('barrier-balancing-cleanser', 'Sodium Citrate', 'contains'),
  ('barrier-balancing-cleanser', 'Fragrance', 'free_from'),
  ('freaks-full-coverage-bundle', 'Zinc Oxide', 'contains'),
  ('freaks-full-coverage-bundle', 'Helianthus Annuus (Sunflower) Seed Wax', 'contains'),
  ('freaks-full-coverage-bundle', 'Isoamyl Laurate', 'contains'),
  ('freaks-full-coverage-bundle', 'Ethylhexyl Olivate', 'contains'),
  ('freaks-full-coverage-bundle', 'Caprylic/Capric Triglyceride', 'contains'),
  ('freaks-full-coverage-bundle', 'C13-15 Alkane', 'contains'),
  ('freaks-full-coverage-bundle', 'Polyhydroxystearic Acid', 'contains'),
  ('freaks-full-coverage-bundle', 'Oryza Sativa (Rice Bran) Oil', 'contains'),
  ('freaks-full-coverage-bundle', 'Quaternium-90 Bentonite', 'contains'),
  ('freaks-full-coverage-bundle', 'Capryloyl Glycerin/Sebacic Acid Copolymer', 'contains'),
  ('freaks-full-coverage-bundle', 'Prototheca Moriformis (Microalgae) Oil', 'contains'),
  ('freaks-full-coverage-bundle', 'Theobroma Cacao (Cocoa) Seed Butter', 'contains'),
  ('freaks-full-coverage-bundle', 'Isostearic Acid', 'contains'),
  ('freaks-full-coverage-bundle', 'Lecithin', 'contains'),
  ('freaks-full-coverage-bundle', 'Polyglyceryl-3 Polyricinoleate', 'contains'),
  ('freaks-full-coverage-bundle', 'Triethyl Citrate', 'contains'),
  ('freaks-full-coverage-bundle', 'Squalane', 'contains'),
  ('freaks-full-coverage-bundle', 'Physalis Angulata (Ground Cherry) Extract', 'contains'),
  ('freaks-full-coverage-bundle', 'Rhododendron Ferrugineum (Alpenrose) Extract', 'contains'),
  ('freaks-full-coverage-bundle', 'Undaria Pinnatifida (Wakame) Extract', 'contains'),
  ('freaks-full-coverage-bundle', 'Saccharomyces Ferment', 'contains'),
  ('freaks-full-coverage-bundle', 'Laurel Lysine', 'contains'),
  ('freaks-full-coverage-bundle', 'Tocopherol Acetate', 'contains'),
  ('freaks-full-coverage-bundle', 'Tocopherol', 'contains'),
  ('freaks-full-coverage-bundle', 'Aloe Barbendensis Leaf Juice', 'contains'),
  ('freaks-full-coverage-bundle', 'Aqua / Water', 'contains'),
  ('freaks-full-coverage-bundle', 'Bambusa Arundinacea (Bamboo) Stem Extract', 'contains'),
  ('freaks-full-coverage-bundle', 'Camellia Sinensis (Japanese Green Tea) Leaf Extract', 'contains'),
  ('freaks-full-coverage-bundle', 'Caprylic / Capric Triglyceride', 'contains'),
  ('freaks-full-coverage-bundle', 'Dilauryl Citrate', 'contains'),
  ('freaks-full-coverage-bundle', 'Ethylhexylglycerin', 'contains'),
  ('freaks-full-coverage-bundle', 'Gluconolactone', 'contains'),
  ('freaks-full-coverage-bundle', 'Glycerin', 'contains'),
  ('freaks-full-coverage-bundle', 'Hydrogenated Methyl Abietate', 'contains'),
  ('freaks-full-coverage-bundle', 'Isopropyl Palmitate', 'contains'),
  ('freaks-full-coverage-bundle', 'Lauryl Glucoside', 'contains'),
  ('freaks-full-coverage-bundle', 'Leuconostoc / Radish Root Ferment Filtrate', 'contains'),
  ('freaks-full-coverage-bundle', 'Lonicera Caprifolium (Honeysuckle) Flower Extract', 'contains'),
  ('freaks-full-coverage-bundle', 'Lonicera Japonica (Honeysuckle) Flower Extract', 'contains'),
  ('freaks-full-coverage-bundle', 'Methylcellulose', 'contains'),
  ('freaks-full-coverage-bundle', 'Octyldodecyl Citrate Crosspolymer', 'contains'),
  ('freaks-full-coverage-bundle', 'Phenoxyethanol', 'contains'),
  ('freaks-full-coverage-bundle', 'Polyglyceryl-4 Laurate', 'contains'),
  ('freaks-full-coverage-bundle', 'Populus Tremuloides Bark Extract', 'contains'),
  ('freaks-full-coverage-bundle', 'Simmondsia Chinensis (Jojoba) Seed Oil', 'contains'),
  ('freaks-full-coverage-bundle', 'Sodium Lauryl Glucose Carboxylate', 'contains'),
  ('freaks-full-coverage-bundle', 'Sodium Phytate', 'contains'),
  ('freaks-full-coverage-bundle', 'Sodium Stearoyl Glutamate', 'contains'),
  ('freaks-full-coverage-bundle', 'Sorbitan Laurate', 'contains'),
  ('freaks-full-coverage-bundle', 'Xanthan Gum', 'contains'),
  ('freaks-full-coverage-bundle', 'Fragrance', 'free_from'),
  ('freaks-full-coverage-bundle', 'Oxybenzone', 'free_from'),
  ('freaks-full-coverage-bundle', 'Octinoxate', 'free_from'),
  ('sun-stick-set', 'Zinc Oxide', 'contains'),
  ('sun-stick-set', 'Helianthus Annuus (Sunflower) Seed Wax', 'contains'),
  ('sun-stick-set', 'Isoamyl Laurate', 'contains'),
  ('sun-stick-set', 'Ethylhexyl Olivate', 'contains'),
  ('sun-stick-set', 'Caprylic/Capric Triglyceride', 'contains'),
  ('sun-stick-set', 'C13-15 Alkane', 'contains'),
  ('sun-stick-set', 'Polyhydroxystearic Acid', 'contains'),
  ('sun-stick-set', 'Oryza Sativa (Rice Bran) Oil', 'contains'),
  ('sun-stick-set', 'Quaternium-90 Bentonite', 'contains'),
  ('sun-stick-set', 'Capryloyl Glycerin/Sebacic Acid Copolymer', 'contains'),
  ('sun-stick-set', 'Prototheca Moriformis (Microalgae) Oil', 'contains'),
  ('sun-stick-set', 'Theobroma Cacao (Cocoa) Seed Butter', 'contains'),
  ('sun-stick-set', 'Isostearic Acid', 'contains'),
  ('sun-stick-set', 'Lecithin', 'contains'),
  ('sun-stick-set', 'Polyglyceryl-3 Polyricinoleate', 'contains'),
  ('sun-stick-set', 'Triethyl Citrate', 'contains'),
  ('sun-stick-set', 'Squalane', 'contains'),
  ('sun-stick-set', 'Physalis Angulata (Ground Cherry) Extract', 'contains'),
  ('sun-stick-set', 'Rhododendron Ferrugineum (Alpenrose) Extract', 'contains'),
  ('sun-stick-set', 'Undaria Pinnatifida (Wakame) Extract', 'contains'),
  ('sun-stick-set', 'Saccharomyces Ferment', 'contains'),
  ('sun-stick-set', 'Laurel Lysine', 'contains'),
  ('sun-stick-set', 'Tocopherol Acetate', 'contains'),
  ('sun-stick-set', 'Tocopherol', 'contains'),
  ('sun-stick-set', 'Fragrance', 'free_from'),
  ('sun-stick-set', 'Oxybenzone', 'free_from'),
  ('sun-stick-set', 'Octinoxate', 'free_from'),
  ('body-by-freaks-bundle', 'Zinc Oxide', 'contains'),
  ('body-by-freaks-bundle', 'Helianthus Annuus (Sunflower) Seed Wax', 'contains'),
  ('body-by-freaks-bundle', 'Isoamyl Laurate', 'contains'),
  ('body-by-freaks-bundle', 'Ethylhexyl Olivate', 'contains'),
  ('body-by-freaks-bundle', 'Caprylic/Capric Triglyceride', 'contains'),
  ('body-by-freaks-bundle', 'C13-15 Alkane', 'contains'),
  ('body-by-freaks-bundle', 'Polyhydroxystearic Acid', 'contains'),
  ('body-by-freaks-bundle', 'Oryza Sativa (Rice Bran) Oil', 'contains'),
  ('body-by-freaks-bundle', 'Quaternium-90 Bentonite', 'contains'),
  ('body-by-freaks-bundle', 'Capryloyl Glycerin/Sebacic Acid Copolymer', 'contains'),
  ('body-by-freaks-bundle', 'Prototheca Moriformis (Microalgae) Oil', 'contains'),
  ('body-by-freaks-bundle', 'Theobroma Cacao (Cocoa) Seed Butter', 'contains'),
  ('body-by-freaks-bundle', 'Isostearic Acid', 'contains'),
  ('body-by-freaks-bundle', 'Lecithin', 'contains'),
  ('body-by-freaks-bundle', 'Polyglyceryl-3 Polyricinoleate', 'contains'),
  ('body-by-freaks-bundle', 'Triethyl Citrate', 'contains'),
  ('body-by-freaks-bundle', 'Squalane', 'contains'),
  ('body-by-freaks-bundle', 'Physalis Angulata (Ground Cherry) Extract', 'contains'),
  ('body-by-freaks-bundle', 'Rhododendron Ferrugineum (Alpenrose) Extract', 'contains'),
  ('body-by-freaks-bundle', 'Undaria Pinnatifida (Wakame) Extract', 'contains'),
  ('body-by-freaks-bundle', 'Saccharomyces Ferment', 'contains'),
  ('body-by-freaks-bundle', 'Laurel Lysine', 'contains'),
  ('body-by-freaks-bundle', 'Tocopherol Acetate', 'contains'),
  ('body-by-freaks-bundle', 'Tocopherol', 'contains'),
  ('body-by-freaks-bundle', 'Aloe Barbendensis Leaf Juice', 'contains'),
  ('body-by-freaks-bundle', 'Aqua / Water', 'contains'),
  ('body-by-freaks-bundle', 'Bambusa Arundinacea (Bamboo) Stem Extract', 'contains'),
  ('body-by-freaks-bundle', 'Camellia Sinensis (Japanese Green Tea) Leaf Extract', 'contains'),
  ('body-by-freaks-bundle', 'Caprylic / Capric Triglyceride', 'contains'),
  ('body-by-freaks-bundle', 'Dilauryl Citrate', 'contains'),
  ('body-by-freaks-bundle', 'Ethylhexylglycerin', 'contains'),
  ('body-by-freaks-bundle', 'Gluconolactone', 'contains'),
  ('body-by-freaks-bundle', 'Glycerin', 'contains'),
  ('body-by-freaks-bundle', 'Hydrogenated Methyl Abietate', 'contains'),
  ('body-by-freaks-bundle', 'Isopropyl Palmitate', 'contains'),
  ('body-by-freaks-bundle', 'Lauryl Glucoside', 'contains'),
  ('body-by-freaks-bundle', 'Leuconostoc / Radish Root Ferment Filtrate', 'contains'),
  ('body-by-freaks-bundle', 'Lonicera Caprifolium (Honeysuckle) Flower Extract', 'contains'),
  ('body-by-freaks-bundle', 'Lonicera Japonica (Honeysuckle) Flower Extract', 'contains'),
  ('body-by-freaks-bundle', 'Methylcellulose', 'contains'),
  ('body-by-freaks-bundle', 'Octyldodecyl Citrate Crosspolymer', 'contains'),
  ('body-by-freaks-bundle', 'Phenoxyethanol', 'contains'),
  ('body-by-freaks-bundle', 'Polyglyceryl-4 Laurate', 'contains'),
  ('body-by-freaks-bundle', 'Populus Tremuloides Bark Extract', 'contains'),
  ('body-by-freaks-bundle', 'Simmondsia Chinensis (Jojoba) Seed Oil', 'contains'),
  ('body-by-freaks-bundle', 'Sodium Lauryl Glucose Carboxylate', 'contains'),
  ('body-by-freaks-bundle', 'Sodium Phytate', 'contains'),
  ('body-by-freaks-bundle', 'Sodium Stearoyl Glutamate', 'contains'),
  ('body-by-freaks-bundle', 'Sorbitan Laurate', 'contains'),
  ('body-by-freaks-bundle', 'Xanthan Gum', 'contains'),
  ('body-by-freaks-bundle', 'Fragrance', 'free_from'),
  ('body-by-freaks-bundle', 'Oxybenzone', 'free_from'),
  ('body-by-freaks-bundle', 'Octinoxate', 'free_from'),
  ('freak-family-pack-v3', 'Zinc Oxide', 'contains'),
  ('freak-family-pack-v3', 'Water', 'contains'),
  ('freak-family-pack-v3', 'Coco-Caprylate/Caprate', 'contains'),
  ('freak-family-pack-v3', 'Caprylic/Capric Triglyceride', 'contains'),
  ('freak-family-pack-v3', 'Polyglyceryl-4 Diisostearate/Polyhydroxystearate/Sebacate', 'contains'),
  ('freak-family-pack-v3', 'Propanediol', 'contains'),
  ('freak-family-pack-v3', 'C13-15 Alkane', 'contains'),
  ('freak-family-pack-v3', 'Squalane', 'contains'),
  ('freak-family-pack-v3', 'Maleated Soybean Oil Glyceryl/Octyldodecanol Esters', 'contains'),
  ('freak-family-pack-v3', 'Copernicia Cerifera (Carnauba) Wax', 'contains'),
  ('freak-family-pack-v3', 'Methylheptylglycerin', 'contains'),
  ('freak-family-pack-v3', 'Sr-wasp spider polypeptide-1 oligopeptide-178', 'contains'),
  ('freak-family-pack-v3', 'Bentonite', 'contains'),
  ('freak-family-pack-v3', 'Polyricinoleic acid', 'contains'),
  ('freak-family-pack-v3', 'Polyhydroxystearic Acid', 'contains'),
  ('freak-family-pack-v3', 'Glycerin', 'contains'),
  ('freak-family-pack-v3', 'Pongamia Pinnata Seed Extract', 'contains'),
  ('freak-family-pack-v3', 'Xanthan Gum', 'contains'),
  ('freak-family-pack-v3', 'Caprylhydroxamic Acid', 'contains'),
  ('freak-family-pack-v3', 'Oryza Sativa (Rice) Bran Wax', 'contains'),
  ('freak-family-pack-v3', 'DL-Alpha Tocopherol', 'contains'),
  ('freak-family-pack-v3', 'Sodium Phytate', 'contains'),
  ('freak-family-pack-v3', 'Titanium Dioxide', 'contains'),
  ('freak-family-pack-v3', 'Stearyl/Octyldodecyl Citrate Crosspolymer', 'contains'),
  ('freak-family-pack-v3', 'Porphyra Umbilicalis Extract Aqua', 'contains'),
  ('freak-family-pack-v3', 'Cetearyl Olivate', 'contains'),
  ('freak-family-pack-v3', 'Sorbitan Olivate', 'contains'),
  ('freak-family-pack-v3', 'Cetyl Alcohol', 'contains'),
  ('freak-family-pack-v3', 'Stearic Acid', 'contains'),
  ('freak-family-pack-v3', 'Helianthus Annuus (Sunflower) Seed Wax', 'contains'),
  ('freak-family-pack-v3', 'Isoamyl Laurate', 'contains'),
  ('freak-family-pack-v3', 'Ethylhexyl Olivate', 'contains'),
  ('freak-family-pack-v3', 'Oryza Sativa (Rice Bran) Oil', 'contains'),
  ('freak-family-pack-v3', 'Quaternium-90 Bentonite', 'contains'),
  ('freak-family-pack-v3', 'Capryloyl Glycerin/Sebacic Acid Copolymer', 'contains'),
  ('freak-family-pack-v3', 'Prototheca Moriformis (Microalgae) Oil', 'contains'),
  ('freak-family-pack-v3', 'Theobroma Cacao (Cocoa) Seed Butter', 'contains'),
  ('freak-family-pack-v3', 'Isostearic Acid', 'contains'),
  ('freak-family-pack-v3', 'Lecithin', 'contains'),
  ('freak-family-pack-v3', 'Polyglyceryl-3 Polyricinoleate', 'contains'),
  ('freak-family-pack-v3', 'Triethyl Citrate', 'contains'),
  ('freak-family-pack-v3', 'Physalis Angulata (Ground Cherry) Extract', 'contains'),
  ('freak-family-pack-v3', 'Rhododendron Ferrugineum (Alpenrose) Extract', 'contains'),
  ('freak-family-pack-v3', 'Undaria Pinnatifida (Wakame) Extract', 'contains'),
  ('freak-family-pack-v3', 'Saccharomyces Ferment', 'contains'),
  ('freak-family-pack-v3', 'Laurel Lysine', 'contains'),
  ('freak-family-pack-v3', 'Tocopherol Acetate', 'contains'),
  ('freak-family-pack-v3', 'Tocopherol', 'contains'),
  ('freak-family-pack-v3', 'Avena Sativa (Oat) Kernel Oil', 'contains'),
  ('freak-family-pack-v3', 'Dextrin Palmitate', 'contains'),
  ('freak-family-pack-v3', 'Plukenetia Volubilis (Sacha Inchi) Seed Oil', 'contains'),
  ('freak-family-pack-v3', 'Simmondsia Chinensis (Jojoba) Seed Oil', 'contains'),
  ('freak-family-pack-v3', 'Padina Pavonica Thallus Extract', 'contains'),
  ('freak-family-pack-v3', 'Bacillus Ferment', 'contains'),
  ('freak-family-pack-v3', 'Sodium Cocoyl Apple Amino Acids', 'contains'),
  ('freak-family-pack-v3', 'Sucrose Stearate', 'contains'),
  ('freak-family-pack-v3', 'Betaine', 'contains'),
  ('freak-family-pack-v3', 'Aspergillus Ferment', 'contains'),
  ('freak-family-pack-v3', 'Vitis Vinifera (Grape) Seed Oil', 'contains'),
  ('freak-family-pack-v3', 'Oryza Sativa (Rice) Bran Oil', 'contains'),
  ('freak-family-pack-v3', 'Camellia Oleifera Seed Oil', 'contains'),
  ('freak-family-pack-v3', 'Spirulina Platensis Extract', 'contains'),
  ('freak-family-pack-v3', 'Trehalose', 'contains'),
  ('freak-family-pack-v3', 'Sodium Citrate', 'contains'),
  ('freak-family-pack-v3', 'Maranta Arundinacea (Arrowroot) Root Extract', 'contains'),
  ('freak-family-pack-v3', 'Helianthus Annuus (Sunflower) Seed Oil', 'contains'),
  ('freak-family-pack-v3', 'Ethylhexyl Palmitate', 'contains'),
  ('freak-family-pack-v3', 'Myrica Pubescens (Laurel) Fruit Wax', 'contains'),
  ('freak-family-pack-v3', 'Bambusa Arundinacea (Bamboo) Stem Extract', 'contains'),
  ('freak-family-pack-v3', 'Zinc Ricinoleate', 'contains'),
  ('freak-family-pack-v3', 'Glyceryl Laurate', 'contains'),
  ('freak-family-pack-v3', 'Silica', 'contains'),
  ('freak-family-pack-v3', 'Citronellyl Methylcrotonate', 'contains'),
  ('freak-family-pack-v3', 'Tocopheryl Acetate', 'contains'),
  ('freak-family-pack-v3', 'Fragrance (Parfum)', 'contains'),
  ('freak-family-pack-v3', 'Chromium Hydroxide Green (CI 77289)', 'contains'),
  ('freak-family-pack-v3', 'Oxybenzone', 'free_from'),
  ('freak-family-pack-v3', 'Octinoxate', 'free_from'),
  ('freak-trio', 'Zinc Oxide', 'contains'),
  ('freak-trio', 'Water', 'contains'),
  ('freak-trio', 'Coco-Caprylate/Caprate', 'contains'),
  ('freak-trio', 'Caprylic/Capric Triglyceride', 'contains'),
  ('freak-trio', 'Polyglyceryl-4 Diisostearate/Polyhydroxystearate/Sebacate', 'contains'),
  ('freak-trio', 'Propanediol', 'contains'),
  ('freak-trio', 'C13-15 Alkane', 'contains'),
  ('freak-trio', 'Squalane', 'contains'),
  ('freak-trio', 'Maleated Soybean Oil Glyceryl/Octyldodecanol Esters', 'contains'),
  ('freak-trio', 'Copernicia Cerifera (Carnauba) Wax', 'contains'),
  ('freak-trio', 'Methylheptylglycerin', 'contains'),
  ('freak-trio', 'Sr-wasp spider polypeptide-1 oligopeptide-178', 'contains'),
  ('freak-trio', 'Bentonite', 'contains'),
  ('freak-trio', 'Polyricinoleic acid', 'contains'),
  ('freak-trio', 'Polyhydroxystearic Acid', 'contains'),
  ('freak-trio', 'Glycerin', 'contains'),
  ('freak-trio', 'Pongamia Pinnata Seed Extract', 'contains'),
  ('freak-trio', 'Xanthan Gum', 'contains'),
  ('freak-trio', 'Caprylhydroxamic Acid', 'contains'),
  ('freak-trio', 'Oryza Sativa (Rice) Bran Wax', 'contains'),
  ('freak-trio', 'DL-Alpha Tocopherol', 'contains'),
  ('freak-trio', 'Sodium Phytate', 'contains'),
  ('freak-trio', 'Titanium Dioxide', 'contains'),
  ('freak-trio', 'Stearyl/Octyldodecyl Citrate Crosspolymer', 'contains'),
  ('freak-trio', 'Porphyra Umbilicalis Extract Aqua', 'contains'),
  ('freak-trio', 'Cetearyl Olivate', 'contains'),
  ('freak-trio', 'Sorbitan Olivate', 'contains'),
  ('freak-trio', 'Cetyl Alcohol', 'contains'),
  ('freak-trio', 'Stearic Acid', 'contains'),
  ('freak-trio', 'Avena Sativa (Oat) Kernel Oil', 'contains'),
  ('freak-trio', 'Dextrin Palmitate', 'contains'),
  ('freak-trio', 'Plukenetia Volubilis (Sacha Inchi) Seed Oil', 'contains'),
  ('freak-trio', 'Simmondsia Chinensis (Jojoba) Seed Oil', 'contains'),
  ('freak-trio', 'Padina Pavonica Thallus Extract', 'contains'),
  ('freak-trio', 'Bacillus Ferment', 'contains'),
  ('freak-trio', 'Tocopherol', 'contains'),
  ('freak-trio', 'Oxybenzone', 'free_from'),
  ('freak-trio', 'Octinoxate', 'free_from'),
  ('peak-performance-duo', 'Zinc Oxide', 'contains'),
  ('peak-performance-duo', 'Titanium Dioxide', 'contains'),
  ('peak-performance-duo', 'Water', 'contains'),
  ('peak-performance-duo', 'Coco-Caprylate/Caprate', 'contains'),
  ('peak-performance-duo', 'Caprylic/Capric Triglyceride', 'contains'),
  ('peak-performance-duo', 'Maleated Soybean Oil Glyceryl/Octyldodecanol Esters', 'contains'),
  ('peak-performance-duo', 'Polyglyceryl-4 Diisostearate/Polyhydroxystearate/Sebacate', 'contains'),
  ('peak-performance-duo', 'Propanediol', 'contains'),
  ('peak-performance-duo', 'Stearyl/Octyldodecyl Citrate Crosspolymer', 'contains'),
  ('peak-performance-duo', 'Copernicia Cerifera (Carnauba) Wax', 'contains'),
  ('peak-performance-duo', 'Bentonite', 'contains'),
  ('peak-performance-duo', 'Methylheptylglycerin', 'contains'),
  ('peak-performance-duo', 'Squalane', 'contains'),
  ('peak-performance-duo', 'Sr-wasp spider polypeptide-1 oligopeptide-178', 'contains'),
  ('peak-performance-duo', 'Porphyra Umbilicalis Extract Aqua', 'contains'),
  ('peak-performance-duo', 'Cetearyl Olivate', 'contains'),
  ('peak-performance-duo', 'Sorbitan Olivate', 'contains'),
  ('peak-performance-duo', 'Polyhydroxystearic Acid', 'contains'),
  ('peak-performance-duo', 'Polyricinoleic acid', 'contains'),
  ('peak-performance-duo', 'Glycerin', 'contains'),
  ('peak-performance-duo', 'Xanthan Gum', 'contains'),
  ('peak-performance-duo', 'Cetyl Alcohol', 'contains'),
  ('peak-performance-duo', 'Pongamia Pinnata Seed Extract', 'contains'),
  ('peak-performance-duo', 'Caprylhydroxamic Acid', 'contains'),
  ('peak-performance-duo', 'Oryza Sativa (Rice) Bran Wax', 'contains'),
  ('peak-performance-duo', 'DL-Alpha Tocopherol', 'contains'),
  ('peak-performance-duo', 'Stearic Acid', 'contains'),
  ('peak-performance-duo', 'Sodium Phytate', 'contains'),
  ('peak-performance-duo', 'Helianthus Annuus (Sunflower) Seed Wax', 'contains'),
  ('peak-performance-duo', 'Isoamyl Laurate', 'contains'),
  ('peak-performance-duo', 'Ethylhexyl Olivate', 'contains'),
  ('peak-performance-duo', 'C13-15 Alkane', 'contains'),
  ('peak-performance-duo', 'Oryza Sativa (Rice Bran) Oil', 'contains'),
  ('peak-performance-duo', 'Quaternium-90 Bentonite', 'contains'),
  ('peak-performance-duo', 'Capryloyl Glycerin/Sebacic Acid Copolymer', 'contains'),
  ('peak-performance-duo', 'Prototheca Moriformis (Microalgae) Oil', 'contains'),
  ('peak-performance-duo', 'Theobroma Cacao (Cocoa) Seed Butter', 'contains'),
  ('peak-performance-duo', 'Isostearic Acid', 'contains'),
  ('peak-performance-duo', 'Lecithin', 'contains'),
  ('peak-performance-duo', 'Polyglyceryl-3 Polyricinoleate', 'contains'),
  ('peak-performance-duo', 'Triethyl Citrate', 'contains'),
  ('peak-performance-duo', 'Physalis Angulata (Ground Cherry) Extract', 'contains'),
  ('peak-performance-duo', 'Rhododendron Ferrugineum (Alpenrose) Extract', 'contains'),
  ('peak-performance-duo', 'Undaria Pinnatifida (Wakame) Extract', 'contains'),
  ('peak-performance-duo', 'Saccharomyces Ferment', 'contains'),
  ('peak-performance-duo', 'Laurel Lysine', 'contains'),
  ('peak-performance-duo', 'Tocopherol Acetate', 'contains'),
  ('peak-performance-duo', 'Tocopherol', 'contains'),
  ('peak-performance-duo', 'Fragrance', 'free_from'),
  ('peak-performance-duo', 'Oxybenzone', 'free_from'),
  ('peak-performance-duo', 'Octinoxate', 'free_from'),
  ('balanced-skin-set', 'Squalane', 'contains'),
  ('balanced-skin-set', 'Avena Sativa (Oat) Kernel Oil', 'contains'),
  ('balanced-skin-set', 'Dextrin Palmitate', 'contains'),
  ('balanced-skin-set', 'Plukenetia Volubilis (Sacha Inchi) Seed Oil', 'contains'),
  ('balanced-skin-set', 'Simmondsia Chinensis (Jojoba) Seed Oil', 'contains'),
  ('balanced-skin-set', 'Padina Pavonica Thallus Extract', 'contains'),
  ('balanced-skin-set', 'Bacillus Ferment', 'contains'),
  ('balanced-skin-set', 'Tocopherol', 'contains'),
  ('balanced-skin-set', 'Glycerin', 'contains'),
  ('balanced-skin-set', 'Sodium Cocoyl Apple Amino Acids', 'contains'),
  ('balanced-skin-set', 'Sucrose Stearate', 'contains'),
  ('balanced-skin-set', 'Betaine', 'contains'),
  ('balanced-skin-set', 'Saccharomyces Ferment', 'contains'),
  ('balanced-skin-set', 'Aspergillus Ferment', 'contains'),
  ('balanced-skin-set', 'Vitis Vinifera (Grape) Seed Oil', 'contains'),
  ('balanced-skin-set', 'Oryza Sativa (Rice) Bran Oil', 'contains'),
  ('balanced-skin-set', 'Camellia Oleifera Seed Oil', 'contains'),
  ('balanced-skin-set', 'Spirulina Platensis Extract', 'contains'),
  ('balanced-skin-set', 'Trehalose', 'contains'),
  ('balanced-skin-set', 'Sodium Citrate', 'contains'),
  ('balanced-skin-set', 'Fragrance', 'free_from'),
  ('daily-system', 'Zinc Oxide', 'contains'),
  ('daily-system', 'Water', 'contains'),
  ('daily-system', 'Coco-Caprylate/Caprate', 'contains'),
  ('daily-system', 'Caprylic/Capric Triglyceride', 'contains'),
  ('daily-system', 'Polyglyceryl-4 Diisostearate/Polyhydroxystearate/Sebacate', 'contains'),
  ('daily-system', 'Propanediol', 'contains'),
  ('daily-system', 'C13-15 Alkane', 'contains'),
  ('daily-system', 'Squalane', 'contains'),
  ('daily-system', 'Maleated Soybean Oil Glyceryl/Octyldodecanol Esters', 'contains'),
  ('daily-system', 'Copernicia Cerifera (Carnauba) Wax', 'contains'),
  ('daily-system', 'Methylheptylglycerin', 'contains'),
  ('daily-system', 'Sr-wasp spider polypeptide-1 oligopeptide-178', 'contains'),
  ('daily-system', 'Bentonite', 'contains'),
  ('daily-system', 'Polyricinoleic acid', 'contains'),
  ('daily-system', 'Polyhydroxystearic Acid', 'contains'),
  ('daily-system', 'Glycerin', 'contains'),
  ('daily-system', 'Pongamia Pinnata Seed Extract', 'contains'),
  ('daily-system', 'Xanthan Gum', 'contains'),
  ('daily-system', 'Caprylhydroxamic Acid', 'contains'),
  ('daily-system', 'Oryza Sativa (Rice) Bran Wax', 'contains'),
  ('daily-system', 'DL-Alpha Tocopherol', 'contains'),
  ('daily-system', 'Sodium Phytate', 'contains'),
  ('daily-system', 'Avena Sativa (Oat) Kernel Oil', 'contains'),
  ('daily-system', 'Dextrin Palmitate', 'contains'),
  ('daily-system', 'Plukenetia Volubilis (Sacha Inchi) Seed Oil', 'contains'),
  ('daily-system', 'Simmondsia Chinensis (Jojoba) Seed Oil', 'contains'),
  ('daily-system', 'Padina Pavonica Thallus Extract', 'contains'),
  ('daily-system', 'Bacillus Ferment', 'contains'),
  ('daily-system', 'Tocopherol', 'contains'),
  ('daily-system', 'Oxybenzone', 'free_from'),
  ('daily-system', 'Octinoxate', 'free_from'),
  ('endurance-system', 'Zinc Oxide', 'contains'),
  ('endurance-system', 'Titanium Dioxide', 'contains'),
  ('endurance-system', 'Water', 'contains'),
  ('endurance-system', 'Coco-Caprylate/Caprate', 'contains'),
  ('endurance-system', 'Caprylic/Capric Triglyceride', 'contains'),
  ('endurance-system', 'Maleated Soybean Oil Glyceryl/Octyldodecanol Esters', 'contains'),
  ('endurance-system', 'Polyglyceryl-4 Diisostearate/Polyhydroxystearate/Sebacate', 'contains'),
  ('endurance-system', 'Propanediol', 'contains'),
  ('endurance-system', 'Stearyl/Octyldodecyl Citrate Crosspolymer', 'contains'),
  ('endurance-system', 'Copernicia Cerifera (Carnauba) Wax', 'contains'),
  ('endurance-system', 'Bentonite', 'contains'),
  ('endurance-system', 'Methylheptylglycerin', 'contains'),
  ('endurance-system', 'Squalane', 'contains'),
  ('endurance-system', 'Sr-wasp spider polypeptide-1 oligopeptide-178', 'contains'),
  ('endurance-system', 'Porphyra Umbilicalis Extract Aqua', 'contains'),
  ('endurance-system', 'Cetearyl Olivate', 'contains'),
  ('endurance-system', 'Sorbitan Olivate', 'contains'),
  ('endurance-system', 'Polyhydroxystearic Acid', 'contains'),
  ('endurance-system', 'Polyricinoleic acid', 'contains'),
  ('endurance-system', 'Glycerin', 'contains'),
  ('endurance-system', 'Xanthan Gum', 'contains'),
  ('endurance-system', 'Cetyl Alcohol', 'contains'),
  ('endurance-system', 'Pongamia Pinnata Seed Extract', 'contains'),
  ('endurance-system', 'Caprylhydroxamic Acid', 'contains'),
  ('endurance-system', 'Oryza Sativa (Rice) Bran Wax', 'contains'),
  ('endurance-system', 'DL-Alpha Tocopherol', 'contains'),
  ('endurance-system', 'Stearic Acid', 'contains'),
  ('endurance-system', 'Sodium Phytate', 'contains'),
  ('endurance-system', 'Avena Sativa (Oat) Kernel Oil', 'contains'),
  ('endurance-system', 'Dextrin Palmitate', 'contains'),
  ('endurance-system', 'Plukenetia Volubilis (Sacha Inchi) Seed Oil', 'contains'),
  ('endurance-system', 'Simmondsia Chinensis (Jojoba) Seed Oil', 'contains'),
  ('endurance-system', 'Padina Pavonica Thallus Extract', 'contains'),
  ('endurance-system', 'Bacillus Ferment', 'contains'),
  ('endurance-system', 'Tocopherol', 'contains'),
  ('endurance-system', 'Oxybenzone', 'free_from'),
  ('endurance-system', 'Octinoxate', 'free_from'),
  ('endurance-system-sport-mode', 'Zinc Oxide', 'contains'),
  ('endurance-system-sport-mode', 'Helianthus Annuus (Sunflower) Seed Wax', 'contains'),
  ('endurance-system-sport-mode', 'Isoamyl Laurate', 'contains'),
  ('endurance-system-sport-mode', 'Ethylhexyl Olivate', 'contains'),
  ('endurance-system-sport-mode', 'Caprylic/Capric Triglyceride', 'contains'),
  ('endurance-system-sport-mode', 'C13-15 Alkane', 'contains'),
  ('endurance-system-sport-mode', 'Polyhydroxystearic Acid', 'contains'),
  ('endurance-system-sport-mode', 'Oryza Sativa (Rice Bran) Oil', 'contains'),
  ('endurance-system-sport-mode', 'Quaternium-90 Bentonite', 'contains'),
  ('endurance-system-sport-mode', 'Capryloyl Glycerin/Sebacic Acid Copolymer', 'contains'),
  ('endurance-system-sport-mode', 'Prototheca Moriformis (Microalgae) Oil', 'contains'),
  ('endurance-system-sport-mode', 'Theobroma Cacao (Cocoa) Seed Butter', 'contains'),
  ('endurance-system-sport-mode', 'Isostearic Acid', 'contains'),
  ('endurance-system-sport-mode', 'Lecithin', 'contains'),
  ('endurance-system-sport-mode', 'Polyglyceryl-3 Polyricinoleate', 'contains'),
  ('endurance-system-sport-mode', 'Triethyl Citrate', 'contains'),
  ('endurance-system-sport-mode', 'Squalane', 'contains'),
  ('endurance-system-sport-mode', 'Physalis Angulata (Ground Cherry) Extract', 'contains'),
  ('endurance-system-sport-mode', 'Rhododendron Ferrugineum (Alpenrose) Extract', 'contains'),
  ('endurance-system-sport-mode', 'Undaria Pinnatifida (Wakame) Extract', 'contains'),
  ('endurance-system-sport-mode', 'Saccharomyces Ferment', 'contains'),
  ('endurance-system-sport-mode', 'Laurel Lysine', 'contains'),
  ('endurance-system-sport-mode', 'Tocopherol Acetate', 'contains'),
  ('endurance-system-sport-mode', 'Tocopherol', 'contains'),
  ('endurance-system-sport-mode', 'Fragrance', 'free_from'),
  ('endurance-system-sport-mode', 'Oxybenzone', 'free_from'),
  ('endurance-system-sport-mode', 'Octinoxate', 'free_from'),
  ('deo-duo-bundle', 'Caprylic/Capric Triglyceride', 'contains'),
  ('deo-duo-bundle', 'Maranta Arundinacea (Arrowroot) Root Extract', 'contains'),
  ('deo-duo-bundle', 'Helianthus Annuus (Sunflower) Seed Oil', 'contains'),
  ('deo-duo-bundle', 'Ethylhexyl Palmitate', 'contains'),
  ('deo-duo-bundle', 'Myrica Pubescens (Laurel) Fruit Wax', 'contains'),
  ('deo-duo-bundle', 'Theobroma Cacao (Cocoa) Seed Butter', 'contains'),
  ('deo-duo-bundle', 'Triethyl Citrate', 'contains'),
  ('deo-duo-bundle', 'Bambusa Arundinacea (Bamboo) Stem Extract', 'contains'),
  ('deo-duo-bundle', 'Zinc Ricinoleate', 'contains'),
  ('deo-duo-bundle', 'Bentonite', 'contains'),
  ('deo-duo-bundle', 'Glyceryl Laurate', 'contains'),
  ('deo-duo-bundle', 'Helianthus Annuus (Sunflower) Seed Wax', 'contains'),
  ('deo-duo-bundle', 'Silica', 'contains'),
  ('deo-duo-bundle', 'Oryza Sativa (Rice) Bran Wax', 'contains'),
  ('deo-duo-bundle', 'Citronellyl Methylcrotonate', 'contains'),
  ('deo-duo-bundle', 'Tocopheryl Acetate', 'contains'),
  ('deo-duo-bundle', 'Fragrance (Parfum)', 'contains'),
  ('deo-duo-bundle', 'Chromium Hydroxide Green (CI 77289)', 'contains'),
  ('skin-support-electrolyte', 'Vitamin A', 'contains'),
  ('skin-support-electrolyte', 'Vitamin C', 'contains'),
  ('skin-support-electrolyte', 'Vitamin D', 'contains'),
  ('skin-support-electrolyte', 'Vitamin E', 'contains'),
  ('skin-support-electrolyte', 'Vitamin B3', 'contains'),
  ('skin-support-electrolyte', 'Calcium', 'contains'),
  ('skin-support-electrolyte', 'Magnesium', 'contains'),
  ('skin-support-electrolyte', 'Zinc', 'contains'),
  ('skin-support-electrolyte', 'Chloride', 'contains'),
  ('skin-support-electrolyte', 'Sodium', 'contains'),
  ('skin-support-electrolyte', 'Potassium', 'contains'),
  ('skin-support-electrolyte', 'Astaxanthin', 'contains'),
  ('skin-support-electrolyte', 'Polypodium leucotomos Leaf Extract', 'contains'),
  ('skin-support-electrolyte', 'Red Orange (Citrus sinensis) Fruit Extract', 'contains'),
  ('skin-support-electrolyte', 'Partially Hydrolyzed Guar Gum', 'contains'),
  ('skin-support-electrolyte', 'Ginger (Zingiber officinale) Root Extract', 'contains'),
  ('skin-support-electrolyte', 'and Sodium Hyaluronate', 'contains'),
  ('skin-support-electrolyte', 'Natural Flavors', 'contains'),
  ('skin-support-electrolyte', 'Citric Acid', 'contains'),
  ('skin-support-electrolyte', 'Malic Acid', 'contains'),
  ('skin-support-electrolyte', 'Rebaudioside A (Stevia Leaf Extract)', 'contains'),
  ('everyday-endurance-trio', 'Caprylic/Capric Triglyceride', 'contains'),
  ('everyday-endurance-trio', 'Maranta Arundinacea (Arrowroot) Root Extract', 'contains'),
  ('everyday-endurance-trio', 'Helianthus Annuus (Sunflower) Seed Oil', 'contains'),
  ('everyday-endurance-trio', 'Ethylhexyl Palmitate', 'contains'),
  ('everyday-endurance-trio', 'Myrica Pubescens (Laurel) Fruit Wax', 'contains'),
  ('everyday-endurance-trio', 'Theobroma Cacao (Cocoa) Seed Butter', 'contains'),
  ('everyday-endurance-trio', 'Triethyl Citrate', 'contains'),
  ('everyday-endurance-trio', 'Bambusa Arundinacea (Bamboo) Stem Extract', 'contains'),
  ('everyday-endurance-trio', 'Zinc Ricinoleate', 'contains'),
  ('everyday-endurance-trio', 'Bentonite', 'contains'),
  ('everyday-endurance-trio', 'Glyceryl Laurate', 'contains'),
  ('everyday-endurance-trio', 'Helianthus Annuus (Sunflower) Seed Wax', 'contains'),
  ('everyday-endurance-trio', 'Silica', 'contains'),
  ('everyday-endurance-trio', 'Oryza Sativa (Rice) Bran Wax', 'contains'),
  ('everyday-endurance-trio', 'Citronellyl Methylcrotonate', 'contains'),
  ('everyday-endurance-trio', 'Tocopheryl Acetate', 'contains'),
  ('everyday-endurance-trio', 'Fragrance (Parfum)', 'contains'),
  ('everyday-endurance-trio', 'Chromium Hydroxide Green (CI 77289)', 'contains')
)
insert into public.product_ingredients (product_id, ingredient_id, kind)
select p.id, i.id, l.kind::text
from links l
join public.products p on p.slug = l.product_slug
join public.ingredients i on i.name = l.ingredient_name
on conflict do nothing;

insert into public.brand_categories (brand_id, category_id)
select distinct p.brand_id, c.id
from public.products p
join public.categories c on c.slug = p.category::text
on conflict do nothing;

update public.products p
set category_id = c.id
from public.categories c
where c.slug = p.category::text
  and p.category_id is null;
